APM:Rover: Sailboat Class Reference
Sailboat Class Reference
#include <sailboat.h>
Public Member Functions
bool enabled () const
Sailboat ()
void init ()
void update_mainsail (float desired_speed)
float get_VMG () const
void handle_tack_request_acro ()
float get_tack_heading_rad () const
void handle_tack_request_auto ()
void clear_tack ()
bool tacking () const
bool use_indirect_route (float desired_heading_cd) const
float calc_heading (float desired_heading_cd)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum Sailboat_Tack { TACK_PORT, TACK_STARBOARD }
Private Attributes
AP_Int8 enable
AP_Float sail_angle_min
AP_Float sail_angle_max
AP_Float sail_angle_ideal
AP_Float sail_heel_angle_max
AP_Float sail_no_go
bool currently_tacking
float tack_heading_rad
uint32_t auto_tack_request_ms
uint32_t auto_tack_start_ms
Detailed Description
Definition at line 19 of file sailboat.h.
Member Enumeration Documentation
Sailboat_Tack
enum Sailboat::Sailboat_Tack private
Enumerator
TACK_PORT
TACK_STARBOARD
Definition at line 72 of file sailboat.h.
Constructor & Destructor Documentation
Sailboat()
Sailboat::Sailboat ()
Definition at line 85 of file sailboat.cpp.
Member Function Documentation
calc_heading()
float Sailboat::calc_heading (float desired_heading_cd)
Definition at line 203 of file sailboat.cpp.
Referenced by Mode::navigate_to_waypoint().
clear_tack()
void Sailboat::clear_tack ()
Definition at line 174 of file sailboat.cpp.
Referenced by calc_heading(), Mode::enter(), and ModeAcro::update().
enabled()
bool Sailboat::enabled (void) const inline
Definition at line 27 of file sailboat.h.
Referenced by calc_heading(), Rover::get_sailboat_enable(), init(), Rover::Log_Write_Attitude(), Rover::Log_Write_Sail(), tacking(), ModeLoiter::update(), update_mainsail(), and use_indirect_route().
get_tack_heading_rad()
float Sailboat::get_tack_heading_rad () const
Definition at line 161 of file sailboat.cpp.
Referenced by ModeAcro::update().
get_VMG()
float Sailboat::get_VMG () const
Definition at line 137 of file sailboat.cpp.
Referenced by Rover::Log_Write_Sail().
handle_tack_request_acro()
void Sailboat::handle_tack_request_acro ()
Definition at line 153 of file sailboat.cpp.
Referenced by ModeAcro::handle_tack_request().
handle_tack_request_auto()
void Sailboat::handle_tack_request_auto ()
Definition at line 167 of file sailboat.cpp.
Referenced by Mode::handle_tack_request().
init()
void Sailboat::init (void)
Definition at line 90 of file sailboat.cpp.
Referenced by Rover::init_ardupilot().
tacking()
bool Sailboat::tacking () const
Definition at line 181 of file sailboat.cpp.
Referenced by ModeAcro::update().
update_mainsail()
void Sailboat::update_mainsail (float desired_speed)
Definition at line 102 of file sailboat.cpp.
Referenced by Mode::calc_throttle().
use_indirect_route()
bool Sailboat::use_indirect_route (float desired_heading_cd) const
Definition at line 188 of file sailboat.cpp.
Referenced by Mode::navigate_to_waypoint().
Member Data Documentation
auto_tack_request_ms
uint32_t Sailboat::auto_tack_request_ms private
Definition at line 79 of file sailboat.h.
Referenced by calc_heading(), clear_tack(), and handle_tack_request_auto().
auto_tack_start_ms
uint32_t Sailboat::auto_tack_start_ms private
Definition at line 80 of file sailboat.h.
Referenced by calc_heading().
currently_tacking
bool Sailboat::currently_tacking private
Definition at line 77 of file sailboat.h.
Referenced by calc_heading(), clear_tack(), handle_tack_request_acro(), and tacking().
enable
AP_Int8 Sailboat::enable private
Definition at line 65 of file sailboat.h.
Referenced by enabled().
sail_angle_ideal
AP_Float Sailboat::sail_angle_ideal private
Definition at line 68 of file sailboat.h.
Referenced by update_mainsail().
sail_angle_max
AP_Float Sailboat::sail_angle_max private
Definition at line 67 of file sailboat.h.
Referenced by update_mainsail().
sail_angle_min
AP_Float Sailboat::sail_angle_min private
Definition at line 66 of file sailboat.h.
Referenced by update_mainsail().
sail_heel_angle_max
AP_Float Sailboat::sail_heel_angle_max private
Definition at line 69 of file sailboat.h.
Referenced by update_mainsail().
sail_no_go
AP_Float Sailboat::sail_no_go private
Definition at line 70 of file sailboat.h.
Referenced by calc_heading(), and use_indirect_route().
tack_heading_rad
float Sailboat::tack_heading_rad private
Definition at line 78 of file sailboat.h.
Referenced by calc_heading(), get_tack_heading_rad(), and handle_tack_request_acro().
var_info
const AP_Param::GroupInfo Sailboat::var_info static
Definition at line 24 of file sailboat.h.
Referenced by Sailboat().
The documentation for this class was generated from the following files:
APMrover2/sailboat.h
APMrover2/sailboat.cpp