APM:Rover: ModeGuided Class Reference
ModeGuided Class Reference
#include <mode.h>
Public Member Functions
uint32_t mode_number () const override
const char * name4 () const override
void update () override
bool is_autopilot_mode () const override
bool in_guided_mode () const override
float get_distance_to_destination () const override
bool reached_destination () const override
bool get_desired_location (Location &destination) const override WARN_IF_UNUSED
bool set_desired_location (const struct Location &destination, float next_leg_bearing_cd=AR_WPNAV_HEADING_UNKNOWN) override WARN_IF_UNUSED
void set_desired_heading_and_speed (float yaw_angle_cd, float target_speed) override
void set_desired_heading_delta_and_speed (float yaw_delta_cd, float target_speed)
void set_desired_turn_rate_and_speed (float turn_rate_cds, float target_speed)
bool start_loiter ()
void limit_set (uint32_t timeout_ms, float horiz_max)
void limit_clear ()
void limit_init_time_and_location ()
bool limit_breached () const
Public Member Functions inherited from Mode
Mode ()
Mode (const Mode &other)=delete
Mode & operator= (const Mode &)=delete
bool enter ()
void exit ()
virtual bool allows_arming_from_transmitter ()
bool allows_stick_mixing () const
virtual bool has_manual_input () const
virtual bool attitude_stabilized () const
virtual bool requires_position () const
virtual bool requires_velocity () const
virtual float wp_bearing () const
virtual float nav_bearing () const
virtual float crosstrack_error () const
virtual float get_desired_lat_accel () const
float speed_error () const
float get_speed_default (bool rtl=false) const
bool set_desired_speed (float speed)
void set_desired_speed_to_default (bool rtl=false)
void set_reversed (bool value)
virtual void handle_tack_request ()
Protected Types
enum GuidedMode { Guided_WP, Guided_HeadingAndSpeed, Guided_TurnRateAndSpeed, Guided_Loiter }
Protected Member Functions
bool _enter () override
Protected Member Functions inherited from Mode
virtual void _exit ()
void get_pilot_desired_steering_and_throttle (float &steering_out, float &throttle_out)
void get_pilot_desired_steering_and_speed (float &steering_out, float &speed_out)
void get_pilot_desired_lateral (float &lateral_out)
void get_pilot_desired_heading_and_speed (float &heading_out, float &speed_out)
void navigate_to_waypoint ()
void calc_steering_from_turn_rate (float turn_rate, float speed, bool reversed)
void calc_steering_from_lateral_acceleration (float lat_accel, bool reversed=false)
void calc_steering_to_heading (float desired_heading_cd, float rate_max_degs=0.0f)
virtual void calc_throttle (float target_speed, bool avoidance_enabled)
bool stop_vehicle ()
float calc_speed_max (float cruise_speed, float cruise_throttle) const
float calc_speed_nudge (float target_speed, bool reversed)
void calc_stopping_location (Location &stopping_loc)
void get_pilot_input (float &steering_out, float &throttle_out)
void set_steering (float steering_value)
Protected Attributes
GuidedMode _guided_mode
bool have_attitude_target
uint32_t _des_att_time_ms
float _desired_yaw_rate_cds
bool sent_notification
struct {
uint32_t timeout_ms
float horiz_max
uint32_t start_time_ms
Location start_loc
} limit
Protected Attributes inherited from Mode
class AP_AHRS & ahrs
class Parameters & g
class ParametersG2 & g2
class RC_Channel *& channel_steer
class RC_Channel *& channel_throttle
class RC_Channel *& channel_lateral
class AR_AttitudeControl & attitude_control
float _distance_to_destination
bool _reached_destination
float _desired_yaw_cd
float _desired_speed
Additional Inherited Members
Public Types inherited from Mode
enum Number {
MANUAL = 0, ACRO = 1, STEERING = 3, HOLD = 4,
LOITER = 5, FOLLOW = 6, SIMPLE = 7, AUTO = 10,
RTL = 11, SMART_RTL = 12, GUIDED = 15, INITIALISING = 16
}
Detailed Description
Definition at line 352 of file mode.h.
Member Enumeration Documentation
GuidedMode
enum ModeGuided::GuidedMode protected
Enumerator
Guided_WP
Guided_HeadingAndSpeed
Guided_TurnRateAndSpeed
Guided_Loiter
Definition at line 396 of file mode.h.
Member Function Documentation
_enter()
bool ModeGuided::_enter () override protected virtual
Reimplemented from Mode.
Definition at line 4 of file mode_guided.cpp.
get_desired_location()
bool ModeGuided::get_desired_location (Location & destination) const override virtual
Reimplemented from Mode.
Definition at line 148 of file mode_guided.cpp.
Referenced by ModeAuto::get_desired_location().
get_distance_to_destination()
float ModeGuided::get_distance_to_destination () const override virtual
Reimplemented from Mode.
Definition at line 115 of file mode_guided.cpp.
Referenced by ModeAuto::get_distance_to_destination().
in_guided_mode()
bool ModeGuided::in_guided_mode () const inline override virtual
Reimplemented from Mode.
Definition at line 366 of file mode.h.
is_autopilot_mode()
bool ModeGuided::is_autopilot_mode () const inline override virtual
Reimplemented from Mode.
Definition at line 363 of file mode.h.
limit_breached()
bool ModeGuided::limit_breached () const
Definition at line 264 of file mode_guided.cpp.
Referenced by ModeAuto::verify_nav_guided_enable().
limit_clear()
void ModeGuided::limit_clear ()
Definition at line 249 of file mode_guided.cpp.
Referenced by ModeAuto::_enter().
limit_init_time_and_location()
void ModeGuided::limit_init_time_and_location ()
Definition at line 257 of file mode_guided.cpp.
Referenced by ModeAuto::start_guided().
limit_set()
void ModeGuided::limit_set (uint32_t timeout_ms, float horiz_max)
Definition at line 242 of file mode_guided.cpp.
Referenced by ModeAuto::do_guided_limits().
mode_number()
uint32_t ModeGuided::mode_number () const inline override virtual
Implements Mode.
Definition at line 356 of file mode.h.
name4()
const char* ModeGuided::name4 () const inline override virtual
Implements Mode.
Definition at line 357 of file mode.h.
reached_destination()
bool ModeGuided::reached_destination () const override virtual
Reimplemented from Mode.
Definition at line 132 of file mode_guided.cpp.
Referenced by ModeAuto::reached_destination().
set_desired_heading_and_speed()
void ModeGuided::set_desired_heading_and_speed (float yaw_angle_cd, float target_speed) override virtual
Reimplemented from Mode.
Definition at line 186 of file mode_guided.cpp.
Referenced by GCS_MAVLINK_Rover::handleMessage(), and set_desired_heading_delta_and_speed().
set_desired_heading_delta_and_speed()
void ModeGuided::set_desired_heading_delta_and_speed (float yaw_delta_cd, float target_speed)
Definition at line 205 of file mode_guided.cpp.
Referenced by GCS_MAVLINK_Rover::handle_command_long_packet().
set_desired_location()
bool ModeGuided::set_desired_location (const struct Location & destination, float next_leg_bearing_cd = AR_WPNAV_HEADING_UNKNOWN) override virtual
Reimplemented from Mode.
Definition at line 171 of file mode_guided.cpp.
Referenced by GCS_MAVLINK_Rover::handle_guided_request(), and GCS_MAVLINK_Rover::handleMessage().
set_desired_turn_rate_and_speed()
void ModeGuided::set_desired_turn_rate_and_speed (float turn_rate_cds, float target_speed)
Definition at line 216 of file mode_guided.cpp.
Referenced by GCS_MAVLINK_Rover::handleMessage().
start_loiter()
bool ModeGuided::start_loiter ()
Definition at line 232 of file mode_guided.cpp.
Referenced by update().
update()
void ModeGuided::update (void) override virtual
Implements Mode.
Definition at line 20 of file mode_guided.cpp.
Referenced by ModeAuto::update().
Member Data Documentation
_des_att_time_ms
uint32_t ModeGuided::_des_att_time_ms protected
Definition at line 409 of file mode.h.
Referenced by set_desired_heading_and_speed(), set_desired_turn_rate_and_speed(), and update().
_desired_yaw_rate_cds
float ModeGuided::_desired_yaw_rate_cds protected
Definition at line 410 of file mode.h.
Referenced by set_desired_turn_rate_and_speed(), and update().
_guided_mode
GuidedMode ModeGuided::_guided_mode protected
Definition at line 405 of file mode.h.
Referenced by _enter(), get_desired_location(), get_distance_to_destination(), reached_destination(), set_desired_heading_and_speed(), set_desired_heading_delta_and_speed(), set_desired_location(), set_desired_turn_rate_and_speed(), start_loiter(), and update().
have_attitude_target
bool ModeGuided::have_attitude_target protected
Definition at line 408 of file mode.h.
Referenced by set_desired_heading_and_speed(), set_desired_turn_rate_and_speed(), and update().
horiz_max
float ModeGuided::horiz_max
Definition at line 416 of file mode.h.
Referenced by limit_set().
limit
struct { ... } ModeGuided::limit
Referenced by limit_breached(), limit_clear(), limit_init_time_and_location(), and limit_set().
sent_notification
bool ModeGuided::sent_notification protected
Definition at line 411 of file mode.h.
Referenced by _enter(), set_desired_location(), and update().
start_loc
Location ModeGuided::start_loc
Definition at line 418 of file mode.h.
start_time_ms
uint32_t ModeGuided::start_time_ms
Definition at line 417 of file mode.h.
timeout_ms
uint32_t ModeGuided::timeout_ms
Definition at line 415 of file mode.h.
Referenced by limit_set().
The documentation for this class was generated from the following files:
APMrover2/mode.h
APMrover2/mode_guided.cpp