APM:Rover: AP_MotorsUGV Class Reference
AP_MotorsUGV Class Reference
#include <AP_MotorsUGV.h>
Classes
struct AP_MotorsUGV_limit
Public Types
enum pwm_type {
PWM_TYPE_NORMAL = 0, PWM_TYPE_ONESHOT = 1, PWM_TYPE_ONESHOT125 = 2, PWM_TYPE_BRUSHED_WITH_RELAY = 3,
PWM_TYPE_BRUSHED_BIPOLAR = 4, PWM_TYPE_DSHOT150 = 5, PWM_TYPE_DSHOT300 = 6, PWM_TYPE_DSHOT600 = 7,
PWM_TYPE_DSHOT1200 = 8
}
enum motor_test_order {
MOTOR_TEST_THROTTLE = 1, MOTOR_TEST_STEERING = 2, MOTOR_TEST_THROTTLE_LEFT = 3, MOTOR_TEST_THROTTLE_RIGHT = 4,
MOTOR_TEST_MAINSAIL = 5, MOTOR_TEST_LAST
}
enum frame_type { FRAME_TYPE_UNDEFINED = 0, FRAME_TYPE_OMNI3 = 1, FRAME_TYPE_OMNIX = 2, FRAME_TYPE_OMNIPLUS = 3 }
Public Member Functions
AP_MotorsUGV (AP_ServoRelayEvents &relayEvents)
void init ()
bool active () const
void setup_safety_output ()
void setup_servo_output ()
float get_steering () const
void set_steering (float steering, bool apply_scaling=true)
float get_throttle () const
void set_throttle (float throttle)
void set_lateral (float lateral)
void set_mainsail (float mainsail)
float get_mainsail () const
float get_slew_limited_throttle (float throttle, float dt) const
bool have_skid_steering () const
bool have_vectored_thrust () const
void output (bool armed, float ground_speed, float dt)
bool output_test_pct (motor_test_order motor_seq, float pct)
bool output_test_pwm (motor_test_order motor_seq, float pwm)
bool pre_arm_check (bool report) const
Public Attributes
struct AP_MotorsUGV::AP_MotorsUGV_limit limit
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void sanity_check_parameters ()
void setup_pwm_type ()
void setup_omni ()
void add_omni_motor (int8_t motor_num, float throttle_factor, float steering_factor, float lateral_factor)
void add_omni_motor_num (int8_t motor_num)
void clear_omni_motors (int8_t motor_num)
void output_regular (bool armed, float ground_speed, float steering, float throttle)
void output_skid_steering (bool armed, float steering, float throttle, float dt)
void output_omni (bool armed, float steering, float throttle, float lateral)
void output_throttle (SRV_Channel::Aux_servo_function_t function, float throttle, float dt=0.0f)
void output_mainsail ()
bool has_sail () const
void slew_limit_throttle (float dt)
void set_limits_from_input (bool armed, float steering, float throttle)
float get_scaled_throttle (float throttle) const
float get_rate_controlled_throttle (SRV_Channel::Aux_servo_function_t function, float throttle, float dt)
Protected Attributes
AP_ServoRelayEvents & _relayEvents
AP_Int8 _pwm_type
AP_Int8 _pwm_freq
AP_Int8 _disarm_disable_pwm
AP_Int16 _slew_rate
AP_Int8 _throttle_min
AP_Int8 _throttle_max
AP_Float _thrust_curve_expo
AP_Float _vector_throttle_base
AP_Float _speed_scale_base
float _steering
float _throttle
float _throttle_prev
bool _scale_steering = true
float _lateral
float _mainsail
float _throttle_factor [AP_MOTORS_NUM_MOTORS_MAX]
float _steering_factor [AP_MOTORS_NUM_MOTORS_MAX]
float _lateral_factor [AP_MOTORS_NUM_MOTORS_MAX]
uint8_t _motors_num
Static Protected Attributes
static const int8_t AP_MOTORS_NUM_MOTORS_MAX = 4
Detailed Description
Definition at line 7 of file AP_MotorsUGV.h.
Member Enumeration Documentation
frame_type
enum AP_MotorsUGV::frame_type
Enumerator
FRAME_TYPE_UNDEFINED
FRAME_TYPE_OMNI3
FRAME_TYPE_OMNIX
FRAME_TYPE_OMNIPLUS
Definition at line 35 of file AP_MotorsUGV.h.
motor_test_order
enum AP_MotorsUGV::motor_test_order
Enumerator
MOTOR_TEST_THROTTLE
MOTOR_TEST_STEERING
MOTOR_TEST_THROTTLE_LEFT
MOTOR_TEST_THROTTLE_RIGHT
MOTOR_TEST_MAINSAIL
MOTOR_TEST_LAST
Definition at line 25 of file AP_MotorsUGV.h.
pwm_type
enum AP_MotorsUGV::pwm_type
Enumerator
PWM_TYPE_NORMAL
PWM_TYPE_ONESHOT
PWM_TYPE_ONESHOT125
PWM_TYPE_BRUSHED_WITH_RELAY
PWM_TYPE_BRUSHED_BIPOLAR
PWM_TYPE_DSHOT150
PWM_TYPE_DSHOT300
PWM_TYPE_DSHOT600
PWM_TYPE_DSHOT1200
Definition at line 13 of file AP_MotorsUGV.h.
Constructor & Destructor Documentation
AP_MotorsUGV()
AP_MotorsUGV::AP_MotorsUGV (AP_ServoRelayEvents & relayEvents)
Definition at line 102 of file AP_MotorsUGV.cpp.
Member Function Documentation
active()
bool AP_MotorsUGV::active () const
Definition at line 873 of file AP_MotorsUGV.cpp.
Referenced by Rover::rudder_arm_disarm_check(), and Rover::stats_update().
add_omni_motor()
void AP_MotorsUGV::add_omni_motor (int8_t motor_num, float throttle_factor, float steering_factor, float lateral_factor) protected
Definition at line 529 of file AP_MotorsUGV.cpp.
Referenced by setup_omni().
add_omni_motor_num()
void AP_MotorsUGV::add_omni_motor_num (int8_t motor_num) protected
Definition at line 544 of file AP_MotorsUGV.cpp.
Referenced by add_omni_motor().
clear_omni_motors()
void AP_MotorsUGV::clear_omni_motors (int8_t motor_num) protected
Definition at line 558 of file AP_MotorsUGV.cpp.
Referenced by setup_omni().
get_mainsail()
float AP_MotorsUGV::get_mainsail () const inline
Definition at line 69 of file AP_MotorsUGV.h.
Referenced by Rover::Log_Write_Sail().
get_rate_controlled_throttle()
float AP_MotorsUGV::get_rate_controlled_throttle (SRV_Channel::Aux_servo_function_t function, float throttle, float dt) protected
Definition at line 851 of file AP_MotorsUGV.cpp.
Referenced by output_throttle().
get_scaled_throttle()
float AP_MotorsUGV::get_scaled_throttle (float throttle) const protected
Definition at line 823 of file AP_MotorsUGV.cpp.
Referenced by output_throttle().
get_slew_limited_throttle()
float AP_MotorsUGV::get_slew_limited_throttle (float throttle, float dt) const
Definition at line 212 of file AP_MotorsUGV.cpp.
Referenced by Mode::get_pilot_desired_steering_and_throttle(), and slew_limit_throttle().
get_steering()
float AP_MotorsUGV::get_steering () const inline
Definition at line 57 of file AP_MotorsUGV.h.
Referenced by active(), and Rover::Log_Write_Steering().
get_throttle()
float AP_MotorsUGV::get_throttle () const inline
Definition at line 61 of file AP_MotorsUGV.h.
Referenced by active(), Rover::crash_check(), Rover::cruise_learn_start(), Rover::cruise_learn_update(), Rover::Log_Write_Throttle(), Rover::update_ahrs_flyforward(), and GCS_MAVLINK_Rover::vfr_hud_throttle().
has_sail()
bool AP_MotorsUGV::has_sail () const protected
Definition at line 235 of file AP_MotorsUGV.cpp.
Referenced by output_mainsail(), and pre_arm_check().
have_skid_steering()
bool AP_MotorsUGV::have_skid_steering () const
Definition at line 225 of file AP_MotorsUGV.cpp.
Referenced by active(), Rover::one_second_loop(), output_regular(), output_skid_steering(), ModeAcro::requires_velocity(), Rover::send_servo_out(), and ModeSteering::update().
have_vectored_thrust()
bool AP_MotorsUGV::have_vectored_thrust () const inline
Definition at line 80 of file AP_MotorsUGV.h.
Referenced by output_regular().
init()
void AP_MotorsUGV::init (void)
Definition at line 108 of file AP_MotorsUGV.cpp.
Referenced by Rover::init_ardupilot().
output()
void AP_MotorsUGV::output (bool armed, float ground_speed, float dt)
Definition at line 240 of file AP_MotorsUGV.cpp.
Referenced by Rover::set_servos().
output_mainsail()
void AP_MotorsUGV::output_mainsail () protected
Definition at line 790 of file AP_MotorsUGV.cpp.
Referenced by output().
output_omni()
void AP_MotorsUGV::output_omni (bool armed, float steering, float throttle, float lateral) protected
Definition at line 674 of file AP_MotorsUGV.cpp.
Referenced by output().
output_regular()
void AP_MotorsUGV::output_regular (bool armed, float ground_speed, float steering, float throttle) protected
Definition at line 570 of file AP_MotorsUGV.cpp.
Referenced by output().
output_skid_steering()
void AP_MotorsUGV::output_skid_steering (bool armed, float steering, float throttle, float dt) protected
Definition at line 625 of file AP_MotorsUGV.cpp.
Referenced by output().
output_test_pct()
bool AP_MotorsUGV::output_test_pct (motor_test_order motor_seq, float pct)
Definition at line 275 of file AP_MotorsUGV.cpp.
Referenced by Rover::motor_test_output().
output_test_pwm()
bool AP_MotorsUGV::output_test_pwm (motor_test_order motor_seq, float pwm)
Definition at line 337 of file AP_MotorsUGV.cpp.
Referenced by Rover::motor_test_output().
output_throttle()
void AP_MotorsUGV::output_throttle (SRV_Channel::Aux_servo_function_t function, float throttle, float dt = 0.0f) protected
Definition at line 723 of file AP_MotorsUGV.cpp.
Referenced by output_omni(), output_regular(), output_skid_steering(), and output_test_pct().
pre_arm_check()
bool AP_MotorsUGV::pre_arm_check (bool report) const
Definition at line 397 of file AP_MotorsUGV.cpp.
Referenced by AP_Arming_Rover::pre_arm_checks().
sanity_check_parameters()
void AP_MotorsUGV::sanity_check_parameters () protected
Definition at line 438 of file AP_MotorsUGV.cpp.
Referenced by output().
set_lateral()
void AP_MotorsUGV::set_lateral (float lateral)
Definition at line 198 of file AP_MotorsUGV.cpp.
Referenced by ModeManual::_exit(), and ModeManual::update().
set_limits_from_input()
void AP_MotorsUGV::set_limits_from_input (bool armed, float steering, float throttle) protected
Definition at line 813 of file AP_MotorsUGV.cpp.
Referenced by output_omni(), output_regular(), and output_skid_steering().
set_mainsail()
void AP_MotorsUGV::set_mainsail (float mainsail)
Definition at line 204 of file AP_MotorsUGV.cpp.
Referenced by Mode::stop_vehicle(), ModeHold::update(), ModeManual::update(), and Sailboat::update_mainsail().
set_steering()
void AP_MotorsUGV::set_steering (float steering, bool apply_scaling = true)
Definition at line 179 of file AP_MotorsUGV.cpp.
Referenced by Mode::calc_steering_from_turn_rate(), Mode::set_steering(), Mode::stop_vehicle(), ModeHold::update(), ModeManual::update(), ModeSteering::update(), and ModeFollow::update().
set_throttle()
void AP_MotorsUGV::set_throttle (float throttle)
Definition at line 186 of file AP_MotorsUGV.cpp.
Referenced by Mode::calc_throttle(), Mode::stop_vehicle(), ModeAcro::update(), ModeHold::update(), ModeManual::update(), ModeSteering::update(), and ModeFollow::update().
setup_omni()
void AP_MotorsUGV::setup_omni () protected
Definition at line 489 of file AP_MotorsUGV.cpp.
Referenced by init().
setup_pwm_type()
void AP_MotorsUGV::setup_pwm_type () protected
Definition at line 446 of file AP_MotorsUGV.cpp.
Referenced by init().
setup_safety_output()
void AP_MotorsUGV::setup_safety_output ()
Definition at line 126 of file AP_MotorsUGV.cpp.
Referenced by init(), and Rover::set_control_channels().
setup_servo_output()
void AP_MotorsUGV::setup_servo_output ()
Definition at line 154 of file AP_MotorsUGV.cpp.
Referenced by init(), and Rover::set_control_channels().
slew_limit_throttle()
void AP_MotorsUGV::slew_limit_throttle (float dt) protected
Definition at line 800 of file AP_MotorsUGV.cpp.
Referenced by output().
Member Data Documentation
_disarm_disable_pwm
AP_Int8 AP_MotorsUGV::_disarm_disable_pwm protected
Definition at line 167 of file AP_MotorsUGV.h.
Referenced by output_omni(), output_regular(), output_skid_steering(), and setup_safety_output().
_lateral
float AP_MotorsUGV::_lateral protected
Definition at line 180 of file AP_MotorsUGV.h.
Referenced by output(), and set_lateral().
_lateral_factor
float AP_MotorsUGV::_lateral_factor[AP_MOTORS_NUM_MOTORS_MAX] protected
Definition at line 186 of file AP_MotorsUGV.h.
Referenced by add_omni_motor(), clear_omni_motors(), and output_omni().
_mainsail
float AP_MotorsUGV::_mainsail protected
Definition at line 181 of file AP_MotorsUGV.h.
Referenced by get_mainsail(), output_mainsail(), and set_mainsail().
_motors_num
uint8_t AP_MotorsUGV::_motors_num protected
Definition at line 187 of file AP_MotorsUGV.h.
Referenced by output_omni(), pre_arm_check(), setup_omni(), and setup_pwm_type().
_pwm_freq
AP_Int8 AP_MotorsUGV::_pwm_freq protected
Definition at line 166 of file AP_MotorsUGV.h.
Referenced by setup_pwm_type().
_pwm_type
AP_Int8 AP_MotorsUGV::_pwm_type protected
Definition at line 165 of file AP_MotorsUGV.h.
Referenced by output_throttle(), setup_pwm_type(), and setup_safety_output().
_relayEvents
AP_ServoRelayEvents& AP_MotorsUGV::_relayEvents protected
Definition at line 160 of file AP_MotorsUGV.h.
Referenced by output_throttle().
_scale_steering
bool AP_MotorsUGV::_scale_steering = true protected
Definition at line 179 of file AP_MotorsUGV.h.
Referenced by output_regular(), and set_steering().
_slew_rate
AP_Int16 AP_MotorsUGV::_slew_rate protected
Definition at line 168 of file AP_MotorsUGV.h.
Referenced by get_slew_limited_throttle().
_speed_scale_base
AP_Float AP_MotorsUGV::_speed_scale_base protected
Definition at line 173 of file AP_MotorsUGV.h.
Referenced by output_regular().
_steering
float AP_MotorsUGV::_steering protected
Definition at line 176 of file AP_MotorsUGV.h.
Referenced by get_steering(), output(), and set_steering().
_steering_factor
float AP_MotorsUGV::_steering_factor[AP_MOTORS_NUM_MOTORS_MAX] protected
Definition at line 185 of file AP_MotorsUGV.h.
Referenced by add_omni_motor(), clear_omni_motors(), and output_omni().
_throttle
float AP_MotorsUGV::_throttle protected
Definition at line 177 of file AP_MotorsUGV.h.
Referenced by get_throttle(), output(), set_throttle(), and slew_limit_throttle().
_throttle_factor
float AP_MotorsUGV::_throttle_factor[AP_MOTORS_NUM_MOTORS_MAX] protected
Definition at line 184 of file AP_MotorsUGV.h.
Referenced by add_omni_motor(), clear_omni_motors(), and output_omni().
_throttle_max
AP_Int8 AP_MotorsUGV::_throttle_max protected
Definition at line 170 of file AP_MotorsUGV.h.
Referenced by sanity_check_parameters(), set_limits_from_input(), and set_throttle().
_throttle_min
AP_Int8 AP_MotorsUGV::_throttle_min protected
Definition at line 169 of file AP_MotorsUGV.h.
Referenced by get_scaled_throttle(), and sanity_check_parameters().
_throttle_prev
float AP_MotorsUGV::_throttle_prev protected
Definition at line 178 of file AP_MotorsUGV.h.
Referenced by get_slew_limited_throttle(), and slew_limit_throttle().
_thrust_curve_expo
AP_Float AP_MotorsUGV::_thrust_curve_expo protected
Definition at line 171 of file AP_MotorsUGV.h.
Referenced by get_scaled_throttle().
_vector_throttle_base
AP_Float AP_MotorsUGV::_vector_throttle_base protected
Definition at line 172 of file AP_MotorsUGV.h.
Referenced by have_vectored_thrust(), output_regular(), and sanity_check_parameters().
AP_MOTORS_NUM_MOTORS_MAX
const int8_t AP_MotorsUGV::AP_MOTORS_NUM_MOTORS_MAX = 4 static protected
Definition at line 162 of file AP_MotorsUGV.h.
Referenced by add_omni_motor(), add_omni_motor_num(), clear_omni_motors(), output_omni(), setup_omni(), and setup_servo_output().
limit
struct AP_MotorsUGV::AP_MotorsUGV_limit AP_MotorsUGV::limit
Referenced by Rover::balancebot_pitch_control(), Mode::calc_steering_from_lateral_acceleration(), Mode::calc_steering_from_turn_rate(), Mode::calc_steering_to_heading(), Mode::calc_throttle(), output_regular(), set_limits_from_input(), slew_limit_throttle(), Mode::stop_vehicle(), ModeAcro::update(), ModeGuided::update(), and ModeSteering::update().
var_info
const AP_Param::GroupInfo AP_MotorsUGV::var_info static
Definition at line 106 of file AP_MotorsUGV.h.
Referenced by AP_MotorsUGV().
The documentation for this class was generated from the following files:
APMrover2/AP_MotorsUGV.h
APMrover2/AP_MotorsUGV.cpp