APM:Rover: ModeAuto Class Reference
ModeAuto Class Reference
#include <mode.h>
Public Member Functions
uint32_t mode_number () const override
const char * name4 () const override
void update () override
void calc_throttle (float target_speed, bool avoidance_enabled) override
bool is_autopilot_mode () const override
bool in_guided_mode () const override
float get_distance_to_destination () const override
bool get_desired_location (Location &destination) const override WARN_IF_UNUSED
bool set_desired_location (const struct Location &destination, float next_leg_bearing_cd=AR_WPNAV_HEADING_UNKNOWN) override WARN_IF_UNUSED
bool reached_destination () const override
void set_desired_heading_and_speed (float yaw_angle_cd, float target_speed) override
bool reached_heading ()
void start_RTL ()
Public Member Functions inherited from Mode
Mode ()
Mode (const Mode &other)=delete
Mode & operator= (const Mode &)=delete
bool enter ()
void exit ()
virtual bool allows_arming_from_transmitter ()
bool allows_stick_mixing () const
virtual bool has_manual_input () const
virtual bool attitude_stabilized () const
virtual bool requires_position () const
virtual bool requires_velocity () const
virtual float wp_bearing () const
virtual float nav_bearing () const
virtual float crosstrack_error () const
virtual float get_desired_lat_accel () const
float speed_error () const
float get_speed_default (bool rtl=false) const
bool set_desired_speed (float speed)
void set_desired_speed_to_default (bool rtl=false)
void set_reversed (bool value)
virtual void handle_tack_request ()
Public Attributes
AP_Mission mission
Location loc
bool valid
uint32_t last_sent_ms
Protected Types
enum AutoSubMode {
Auto_WP, Auto_HeadingAndSpeed, Auto_RTL, Auto_Loiter,
Auto_Guided
}
Protected Member Functions
bool _enter () override
void _exit () override
Protected Member Functions inherited from Mode
void get_pilot_desired_steering_and_throttle (float &steering_out, float &throttle_out)
void get_pilot_desired_steering_and_speed (float &steering_out, float &speed_out)
void get_pilot_desired_lateral (float &lateral_out)
void get_pilot_desired_heading_and_speed (float &heading_out, float &speed_out)
void navigate_to_waypoint ()
void calc_steering_from_turn_rate (float turn_rate, float speed, bool reversed)
void calc_steering_from_lateral_acceleration (float lat_accel, bool reversed=false)
void calc_steering_to_heading (float desired_heading_cd, float rate_max_degs=0.0f)
bool stop_vehicle ()
float calc_speed_max (float cruise_speed, float cruise_throttle) const
float calc_speed_nudge (float target_speed, bool reversed)
void calc_stopping_location (Location &stopping_loc)
void get_pilot_input (float &steering_out, float &throttle_out)
void set_steering (float steering_value)
Protected Attributes
enum ModeAuto::AutoSubMode _submode
Protected Attributes inherited from Mode
class AP_AHRS & ahrs
class Parameters & g
class ParametersG2 & g2
class RC_Channel *& channel_steer
class RC_Channel *& channel_throttle
class RC_Channel *& channel_lateral
class AR_AttitudeControl & attitude_control
float _distance_to_destination
bool _reached_destination
float _desired_yaw_cd
float _desired_speed
Private Types
enum Mis_Done_Behave { MIS_DONE_BEHAVE_HOLD = 0, MIS_DONE_BEHAVE_LOITER = 1, MIS_DONE_BEHAVE_ACRO = 2 }
Private Member Functions
bool check_trigger (void)
bool start_loiter ()
void start_guided (const Location &target_loc)
void send_guided_position_target ()
bool start_command (const AP_Mission::Mission_Command &cmd)
void exit_mission ()
bool verify_command_callback (const AP_Mission::Mission_Command &cmd)
bool verify_command (const AP_Mission::Mission_Command &cmd)
void do_RTL (void)
bool do_nav_wp (const AP_Mission::Mission_Command &cmd, bool always_stop_at_destination)
void do_nav_guided_enable (const AP_Mission::Mission_Command &cmd)
void do_nav_set_yaw_speed (const AP_Mission::Mission_Command &cmd)
bool verify_nav_wp (const AP_Mission::Mission_Command &cmd)
bool verify_RTL ()
bool verify_loiter_unlimited (const AP_Mission::Mission_Command &cmd)
bool verify_loiter_time (const AP_Mission::Mission_Command &cmd)
bool verify_nav_guided_enable (const AP_Mission::Mission_Command &cmd)
bool verify_nav_set_yaw_speed ()
void do_wait_delay (const AP_Mission::Mission_Command &cmd)
void do_within_distance (const AP_Mission::Mission_Command &cmd)
bool verify_wait_delay ()
bool verify_within_distance ()
void do_change_speed (const AP_Mission::Mission_Command &cmd)
void do_set_home (const AP_Mission::Mission_Command &cmd)
void do_set_reverse (const AP_Mission::Mission_Command &cmd)
void do_guided_limits (const AP_Mission::Mission_Command &cmd)
Private Attributes
bool auto_triggered
bool _reached_heading
uint16_t loiter_duration
uint32_t loiter_start_time
bool previously_reached_wp
struct {
Location loc
bool valid
uint32_t last_sent_ms
} guided_target
int32_t condition_value
int32_t condition_start
Additional Inherited Members
Public Types inherited from Mode
enum Number {
MANUAL = 0, ACRO = 1, STEERING = 3, HOLD = 4,
LOITER = 5, FOLLOW = 6, SIMPLE = 7, AUTO = 10,
RTL = 11, SMART_RTL = 12, GUIDED = 15, INITIALISING = 16
}
Detailed Description
Definition at line 239 of file mode.h.
Member Enumeration Documentation
AutoSubMode
enum ModeAuto::AutoSubMode protected
Enumerator
Auto_WP
Auto_HeadingAndSpeed
Auto_RTL
Auto_Loiter
Auto_Guided
Definition at line 281 of file mode.h.
Mis_Done_Behave
enum ModeAuto::Mis_Done_Behave private
Enumerator
MIS_DONE_BEHAVE_HOLD
MIS_DONE_BEHAVE_LOITER
MIS_DONE_BEHAVE_ACRO
Definition at line 320 of file mode.h.
Member Function Documentation
_enter()
bool ModeAuto::_enter () override protected virtual
Reimplemented from Mode.
Definition at line 6 of file mode_auto.cpp.
_exit()
void ModeAuto::_exit () override protected virtual
Reimplemented from Mode.
Definition at line 33 of file mode_auto.cpp.
calc_throttle()
void ModeAuto::calc_throttle (float target_speed, bool avoidance_enabled) override virtual
Reimplemented from Mode.
Definition at line 103 of file mode_auto.cpp.
Referenced by update().
check_trigger()
bool ModeAuto::check_trigger (void) private
Definition at line 227 of file mode_auto.cpp.
Referenced by calc_throttle().
do_change_speed()
void ModeAuto::do_change_speed (const AP_Mission::Mission_Command & cmd) private
Definition at line 693 of file mode_auto.cpp.
Referenced by start_command().
do_guided_limits()
void ModeAuto::do_guided_limits (const AP_Mission::Mission_Command & cmd) private
Definition at line 720 of file mode_auto.cpp.
Referenced by start_command().
do_nav_guided_enable()
void ModeAuto::do_nav_guided_enable (const AP_Mission::Mission_Command & cmd) private
Definition at line 542 of file mode_auto.cpp.
Referenced by start_command().
do_nav_set_yaw_speed()
void ModeAuto::do_nav_set_yaw_speed (const AP_Mission::Mission_Command & cmd) private
Definition at line 550 of file mode_auto.cpp.
Referenced by start_command().
do_nav_wp()
bool ModeAuto::do_nav_wp (const AP_Mission::Mission_Command & cmd, bool always_stop_at_destination) private
Definition at line 513 of file mode_auto.cpp.
Referenced by start_command().
do_RTL()
void ModeAuto::do_RTL (void) private
Definition at line 507 of file mode_auto.cpp.
Referenced by start_command().
do_set_home()
void ModeAuto::do_set_home (const AP_Mission::Mission_Command & cmd) private
Definition at line 701 of file mode_auto.cpp.
Referenced by start_command().
do_set_reverse()
void ModeAuto::do_set_reverse (const AP_Mission::Mission_Command & cmd) private
Definition at line 714 of file mode_auto.cpp.
Referenced by start_command().
do_wait_delay()
void ModeAuto::do_wait_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 655 of file mode_auto.cpp.
Referenced by start_command().
do_within_distance()
void ModeAuto::do_within_distance (const AP_Mission::Mission_Command & cmd) private
Definition at line 661 of file mode_auto.cpp.
Referenced by start_command().
exit_mission()
void ModeAuto::exit_mission () private
Definition at line 416 of file mode_auto.cpp.
get_desired_location()
bool ModeAuto::get_desired_location (Location & destination) const override virtual
Reimplemented from Mode.
Definition at line 135 of file mode_auto.cpp.
get_distance_to_destination()
float ModeAuto::get_distance_to_destination () const override virtual
Reimplemented from Mode.
Definition at line 114 of file mode_auto.cpp.
Referenced by verify_within_distance().
in_guided_mode()
bool ModeAuto::in_guided_mode () const inline override virtual
Reimplemented from Mode.
Definition at line 254 of file mode.h.
is_autopilot_mode()
bool ModeAuto::is_autopilot_mode () const inline override virtual
Reimplemented from Mode.
Definition at line 251 of file mode.h.
mode_number()
uint32_t ModeAuto::mode_number () const inline override virtual
Implements Mode.
Definition at line 243 of file mode.h.
name4()
const char* ModeAuto::name4 () const inline override virtual
Implements Mode.
Definition at line 244 of file mode.h.
reached_destination()
bool ModeAuto::reached_destination () const override virtual
Reimplemented from Mode.
Definition at line 173 of file mode_auto.cpp.
Referenced by verify_nav_wp(), and verify_RTL().
reached_heading()
bool ModeAuto::reached_heading ()
Definition at line 209 of file mode_auto.cpp.
Referenced by verify_nav_set_yaw_speed().
send_guided_position_target()
void ModeAuto::send_guided_position_target () private
Definition at line 299 of file mode_auto.cpp.
Referenced by update().
set_desired_heading_and_speed()
void ModeAuto::set_desired_heading_and_speed (float yaw_angle_cd, float target_speed) override virtual
Reimplemented from Mode.
Definition at line 199 of file mode_auto.cpp.
Referenced by do_nav_set_yaw_speed().
set_desired_location()
bool ModeAuto::set_desired_location (const struct Location & destination, float next_leg_bearing_cd = AR_WPNAV_HEADING_UNKNOWN) override virtual
Reimplemented from Mode.
Definition at line 160 of file mode_auto.cpp.
Referenced by do_nav_wp().
start_command()
bool ModeAuto::start_command (const AP_Mission::Mission_Command & cmd) private
Definition at line 324 of file mode_auto.cpp.
start_guided()
void ModeAuto::start_guided (const Location & target_loc) private
Definition at line 279 of file mode_auto.cpp.
Referenced by do_nav_guided_enable().
start_loiter()
bool ModeAuto::start_loiter () private
Definition at line 269 of file mode_auto.cpp.
Referenced by update().
start_RTL()
void ModeAuto::start_RTL ()
Definition at line 219 of file mode_auto.cpp.
Referenced by do_RTL().
update()
void ModeAuto::update (void) override virtual
Implements Mode.
Definition at line 41 of file mode_auto.cpp.
verify_command()
bool ModeAuto::verify_command (const AP_Mission::Mission_Command & cmd) private
Definition at line 457 of file mode_auto.cpp.
Referenced by verify_command_callback().
verify_command_callback()
bool ModeAuto::verify_command_callback (const AP_Mission::Mission_Command & cmd) private
Definition at line 436 of file mode_auto.cpp.
verify_loiter_time()
bool ModeAuto::verify_loiter_time (const AP_Mission::Mission_Command & cmd) private
Definition at line 616 of file mode_auto.cpp.
Referenced by verify_command().
verify_loiter_unlimited()
bool ModeAuto::verify_loiter_unlimited (const AP_Mission::Mission_Command & cmd) private
Definition at line 609 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_guided_enable()
bool ModeAuto::verify_nav_guided_enable (const AP_Mission::Mission_Command & cmd) private
Definition at line 626 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_set_yaw_speed()
bool ModeAuto::verify_nav_set_yaw_speed () private
Definition at line 646 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_wp()
bool ModeAuto::verify_nav_wp (const AP_Mission::Mission_Command & cmd) private
Definition at line 571 of file mode_auto.cpp.
Referenced by verify_command(), verify_loiter_time(), and verify_loiter_unlimited().
verify_RTL()
bool ModeAuto::verify_RTL () private
Definition at line 604 of file mode_auto.cpp.
Referenced by verify_command().
verify_wait_delay()
bool ModeAuto::verify_wait_delay () private
Definition at line 670 of file mode_auto.cpp.
Referenced by verify_command().
verify_within_distance()
bool ModeAuto::verify_within_distance () private
Definition at line 679 of file mode_auto.cpp.
Referenced by verify_command().
Member Data Documentation
_reached_heading
bool ModeAuto::_reached_heading private
Definition at line 327 of file mode.h.
Referenced by reached_heading(), set_desired_heading_and_speed(), and update().
_submode
enum ModeAuto::AutoSubMode ModeAuto::_submode protected
Referenced by get_desired_location(), get_distance_to_destination(), in_guided_mode(), reached_destination(), reached_heading(), set_desired_heading_and_speed(), set_desired_location(), start_guided(), start_loiter(), start_RTL(), update(), and verify_nav_guided_enable().
auto_triggered
bool ModeAuto::auto_triggered private
Definition at line 326 of file mode.h.
Referenced by _enter(), and check_trigger().
condition_start
int32_t ModeAuto::condition_start private
Definition at line 347 of file mode.h.
Referenced by do_wait_delay(), and verify_wait_delay().
condition_value
int32_t ModeAuto::condition_value private
Definition at line 344 of file mode.h.
Referenced by do_wait_delay(), do_within_distance(), verify_wait_delay(), and verify_within_distance().
guided_target
struct { ... } ModeAuto::guided_target
Referenced by send_guided_position_target(), start_guided(), and verify_nav_guided_enable().
last_sent_ms
uint32_t ModeAuto::last_sent_ms
Definition at line 338 of file mode.h.
loc
Location ModeAuto::loc
Definition at line 336 of file mode.h.
Referenced by start_guided().
loiter_duration
uint16_t ModeAuto::loiter_duration private
Definition at line 330 of file mode.h.
Referenced by do_nav_wp(), and verify_nav_wp().
loiter_start_time
uint32_t ModeAuto::loiter_start_time private
Definition at line 331 of file mode.h.
Referenced by do_nav_wp(), and verify_nav_wp().
mission
AP_Mission ModeAuto::mission
Initial value:
{
        FUNCTOR_BIND_MEMBER(&ModeAuto::start_command, bool, const AP_Mission::Mission_Command&),
        FUNCTOR_BIND_MEMBER(&ModeAuto::verify_command_callback, bool, const AP_Mission::Mission_Command&),
        FUNCTOR_BIND_MEMBER(&ModeAuto::exit_mission, void)}
Definition at line 271 of file mode.h.
Referenced by _enter(), _exit(), RC_Channel_Rover::add_waypoint_for_current_loc(), AP_Arming_Rover::disarm(), RC_Channel_Rover::do_aux_function(), do_nav_wp(), Rover::Log_Write_Startup(), Rover::set_home(), start_command(), Rover::startup_ground(), and Rover::update_mission().
previously_reached_wp
bool ModeAuto::previously_reached_wp private
Definition at line 332 of file mode.h.
Referenced by do_nav_wp(), and verify_nav_wp().
valid
bool ModeAuto::valid
Definition at line 337 of file mode.h.
The documentation for this class was generated from the following files:
APMrover2/mode.h
APMrover2/mode_auto.cpp