APM:Rover: GCS_Rover Class Reference
GCS_Rover Class Reference
#include <GCS_Rover.h>
Public Member Functions
uint8_t num_gcs () const override
GCS_MAVLINK_Rover & chan (uint8_t ofs) override
const GCS_MAVLINK_Rover & chan (uint8_t ofs) const override
uint32_t custom_mode () const override
MAV_TYPE frame_type () const override
bool vehicle_initialised () const override
void update_vehicle_sensor_status_flags (void) override
bool simple_input_active () const override
bool supersimple_input_active () const override
Public Member Functions inherited from GCS
GCS ()
virtual const char * frame_string () const
void send_to_active_channels (uint32_t msgid, const char *pkt)
void send_text (MAV_SEVERITY severity, const char *fmt,...)
void send_textv (MAV_SEVERITY severity, const char *fmt, va_list arg_list)
virtual void send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char *text)
void service_statustext (void)
void send_message (enum ap_message id)
void send_mission_item_reached_message (uint16_t mission_index)
void send_named_float (const char *name, float value) const
void send_parameter_value (const char *param_name, ap_var_type param_type, float param_value)
MissionItemProtocol * get_prot_for_mission_type (const MAV_MISSION_TYPE mission_type) const
void try_send_queued_message_for_type (MAV_MISSION_TYPE type)
void update_send ()
void update_receive ()
virtual void setup_uarts ()
virtual uint16_t min_loop_time_remaining_for_message_send_us () const
bool out_of_time () const
bool install_alternative_protocol (mavlink_channel_t chan, GCS_MAVLINK::protocol_handler_fn_t handler)
int16_t get_hud_throttle (void) const
void update_passthru ()
void get_sensor_status_flags (uint32_t &present, uint32_t &enabled, uint32_t &health)
Private Attributes
GCS_MAVLINK_Rover _chan [MAVLINK_COMM_NUM_BUFFERS]
Friends
class Rover
Additional Inherited Members
Static Public Member Functions inherited from GCS
static class GCS * get_singleton ()
Public Attributes inherited from GCS
AP_Frsky_Telem * frsky
AP_DEVO_Telem devo_telemetry
bool enabled
bool timer_installed
AP_HAL::UARTDriver * port1
AP_HAL::UARTDriver * port2
uint32_t start_ms
uint32_t last_ms
uint32_t last_port1_data_ms
uint8_t timeout_s
HAL_Semaphore sem
Static Public Attributes inherited from GCS
static MissionItemProtocol_Waypoints * _missionitemprotocol_waypoints
static MissionItemProtocol_Rally * _missionitemprotocol_rally
Protected Member Functions inherited from GCS
void update_sensor_status_flags ()
Protected Attributes inherited from GCS
uint32_t control_sensors_present
uint32_t control_sensors_enabled
uint32_t control_sensors_health
Detailed Description
Definition at line 6 of file GCS_Rover.h.
Member Function Documentation
chan() [1/2]
GCS_MAVLINK_Rover& GCS_Rover::chan (uint8_t ofs) inline override virtual
Implements GCS.
Definition at line 16 of file GCS_Rover.h.
Referenced by Rover::init_ardupilot(), and Rover::mavlink_motor_test_check().
chan() [2/2]
const GCS_MAVLINK_Rover& GCS_Rover::chan (uint8_t ofs) const inline override virtual
Implements GCS.
Definition at line 24 of file GCS_Rover.h.
custom_mode()
uint32_t GCS_Rover::custom_mode () const override virtual
Implements GCS.
Definition at line 56 of file GCS_Mavlink.cpp.
frame_type()
MAV_TYPE GCS_Rover::frame_type () const override virtual
Implements GCS.
Definition at line 7 of file GCS_Mavlink.cpp.
num_gcs()
uint8_t GCS_Rover::num_gcs () const inline override virtual
Implements GCS.
Definition at line 13 of file GCS_Rover.h.
Referenced by chan().
simple_input_active()
bool GCS_Rover::simple_input_active () const override virtual
Reimplemented from GCS.
Definition at line 7 of file GCS_Rover.cpp.
supersimple_input_active()
bool GCS_Rover::supersimple_input_active () const override virtual
Reimplemented from GCS.
Definition at line 15 of file GCS_Rover.cpp.
update_vehicle_sensor_status_flags()
void GCS_Rover::update_vehicle_sensor_status_flags (void) override virtual
Reimplemented from GCS.
Definition at line 23 of file GCS_Rover.cpp.
vehicle_initialised()
bool GCS_Rover::vehicle_initialised () const override virtual
Reimplemented from GCS.
Definition at line 310 of file GCS_Mavlink.cpp.
Friends And Related Function Documentation
Rover
friend class Rover friend
Definition at line 8 of file GCS_Rover.h.
Member Data Documentation
_chan
GCS_MAVLINK_Rover GCS_Rover::_chan[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 44 of file GCS_Rover.h.
Referenced by chan(), and num_gcs().
The documentation for this class was generated from the following files:
APMrover2/GCS_Rover.h
APMrover2/GCS_Mavlink.cpp
APMrover2/GCS_Rover.cpp