APM:Rover: Mode Class Reference
Mode Class Reference abstract
#include <mode.h>
Public Types
enum Number {
MANUAL = 0, ACRO = 1, STEERING = 3, HOLD = 4,
LOITER = 5, FOLLOW = 6, SIMPLE = 7, AUTO = 10,
RTL = 11, SMART_RTL = 12, GUIDED = 15, INITIALISING = 16
}
Public Member Functions
Mode ()
Mode (const Mode &other)=delete
Mode & operator= (const Mode &)=delete
bool enter ()
void exit ()
virtual uint32_t mode_number () const =0
virtual const char * name4 () const =0
virtual void update ()=0
virtual bool is_autopilot_mode () const
virtual bool in_guided_mode () const
virtual bool allows_arming_from_transmitter ()
bool allows_stick_mixing () const
virtual bool has_manual_input () const
virtual bool attitude_stabilized () const
virtual bool requires_position () const
virtual bool requires_velocity () const
virtual float wp_bearing () const
virtual float nav_bearing () const
virtual float crosstrack_error () const
virtual float get_desired_lat_accel () const
float speed_error () const
virtual float get_distance_to_destination () const
virtual bool get_desired_location (Location &destination) const WARN_IF_UNUSED
virtual bool set_desired_location (const struct Location &destination, float next_leg_bearing_cd=AR_WPNAV_HEADING_UNKNOWN) WARN_IF_UNUSED
virtual bool reached_destination () const
virtual void set_desired_heading_and_speed (float yaw_angle_cd, float target_speed)
float get_speed_default (bool rtl=false) const
bool set_desired_speed (float speed)
void set_desired_speed_to_default (bool rtl=false)
void set_reversed (bool value)
virtual void handle_tack_request ()
Protected Member Functions
virtual bool _enter ()
virtual void _exit ()
void get_pilot_desired_steering_and_throttle (float &steering_out, float &throttle_out)
void get_pilot_desired_steering_and_speed (float &steering_out, float &speed_out)
void get_pilot_desired_lateral (float &lateral_out)
void get_pilot_desired_heading_and_speed (float &heading_out, float &speed_out)
void navigate_to_waypoint ()
void calc_steering_from_turn_rate (float turn_rate, float speed, bool reversed)
void calc_steering_from_lateral_acceleration (float lat_accel, bool reversed=false)
void calc_steering_to_heading (float desired_heading_cd, float rate_max_degs=0.0f)
virtual void calc_throttle (float target_speed, bool avoidance_enabled)
bool stop_vehicle ()
float calc_speed_max (float cruise_speed, float cruise_throttle) const
float calc_speed_nudge (float target_speed, bool reversed)
void calc_stopping_location (Location &stopping_loc)
void get_pilot_input (float &steering_out, float &throttle_out)
void set_steering (float steering_value)
Protected Attributes
class AP_AHRS & ahrs
class Parameters & g
class ParametersG2 & g2
class RC_Channel *& channel_steer
class RC_Channel *& channel_throttle
class RC_Channel *& channel_lateral
class AR_AttitudeControl & attitude_control
float _distance_to_destination
bool _reached_destination
float _desired_yaw_cd
float _desired_speed
Detailed Description
Definition at line 15 of file mode.h.
Member Enumeration Documentation
Number
enum Mode::Number
Enumerator
MANUAL
ACRO
STEERING
HOLD
LOITER
FOLLOW
SIMPLE
AUTO
RTL
SMART_RTL
GUIDED
INITIALISING
Definition at line 21 of file mode.h.
Constructor & Destructor Documentation
Mode() [1/2]
Mode::Mode ()
Definition at line 4 of file mode.cpp.
Mode() [2/2]
Mode::Mode (const Mode & other) delete
Member Function Documentation
_enter()
virtual bool Mode::_enter () inline protected virtual
Reimplemented in ModeFollow, ModeSmartRTL, ModeRTL, ModeLoiter, ModeGuided, and ModeAuto.
Definition at line 141 of file mode.h.
Referenced by enter().
_exit()
virtual void Mode::_exit () inline protected virtual
Reimplemented in ModeManual, and ModeAuto.
Definition at line 144 of file mode.h.
Referenced by exit().
allows_arming_from_transmitter()
virtual bool Mode::allows_arming_from_transmitter () inline virtual
Definition at line 73 of file mode.h.
Referenced by Rover::rudder_arm_disarm_check().
allows_stick_mixing()
bool Mode::allows_stick_mixing () const inline
Definition at line 75 of file mode.h.
Referenced by set_steering().
attitude_stabilized()
virtual bool Mode::attitude_stabilized () const inline virtual
Reimplemented in ModeInitializing, ModeManual, and ModeHold.
Definition at line 85 of file mode.h.
Referenced by GCS_Rover::update_vehicle_sensor_status_flags().
calc_speed_max()
float Mode::calc_speed_max (float cruise_speed, float cruise_throttle) const protected
Definition at line 327 of file mode.cpp.
Referenced by calc_speed_nudge(), get_pilot_desired_heading_and_speed(), and get_pilot_desired_steering_and_speed().
calc_speed_nudge()
float Mode::calc_speed_nudge (float target_speed, bool reversed) protected
Definition at line 346 of file mode.cpp.
Referenced by navigate_to_waypoint(), ModeAuto::update(), and ModeGuided::update().
calc_steering_from_lateral_acceleration()
void Mode::calc_steering_from_lateral_acceleration (float lat_accel, bool reversed = false) protected
Definition at line 429 of file mode.cpp.
Referenced by ModeSteering::update().
calc_steering_from_turn_rate()
void Mode::calc_steering_from_turn_rate (float turn_rate, float speed, bool reversed) protected
Definition at line 409 of file mode.cpp.
Referenced by navigate_to_waypoint().
calc_steering_to_heading()
void Mode::calc_steering_to_heading (float desired_heading_cd, float rate_max_degs = 0.0f) protected
Definition at line 450 of file mode.cpp.
Referenced by navigate_to_waypoint(), ModeAuto::update(), ModeGuided::update(), ModeLoiter::update(), ModeFollow::update(), and ModeSimple::update().
calc_stopping_location()
void Mode::calc_stopping_location (Location & stopping_loc) protected
Definition at line 462 of file mode.cpp.
Referenced by ModeLoiter::_enter().
calc_throttle()
void Mode::calc_throttle (float target_speed, bool avoidance_enabled) protected virtual
Reimplemented in ModeAuto.
Definition at line 264 of file mode.cpp.
Referenced by ModeAuto::calc_throttle(), navigate_to_waypoint(), ModeAcro::update(), ModeGuided::update(), ModeLoiter::update(), ModeSteering::update(), ModeFollow::update(), and ModeSimple::update().
crosstrack_error()
float Mode::crosstrack_error (void) const virtual
Reimplemented in ModeFollow, and ModeLoiter.
Definition at line 181 of file mode.cpp.
Referenced by Rover::Log_Write_Nav_Tuning(), and GCS_MAVLINK_Rover::send_nav_controller_output().
enter()
bool Mode::enter ()
Definition at line 20 of file mode.cpp.
Referenced by Rover::set_mode(), ModeAuto::start_guided(), ModeAuto::start_loiter(), ModeGuided::start_loiter(), and ModeAuto::start_RTL().
exit()
void Mode::exit ()
Definition at line 14 of file mode.cpp.
Referenced by Rover::set_mode().
get_desired_lat_accel()
float Mode::get_desired_lat_accel () const virtual
Reimplemented in ModeSteering.
Definition at line 190 of file mode.cpp.
Referenced by Rover::Log_Write_Steering().
get_desired_location()
virtual bool Mode::get_desired_location (Location & destination) const inline virtual
Reimplemented in ModeFollow, ModeSmartRTL, ModeRTL, ModeLoiter, ModeGuided, and ModeAuto.
Definition at line 109 of file mode.h.
Referenced by GCS_MAVLINK_Rover::send_position_target_global_int().
get_distance_to_destination()
virtual float Mode::get_distance_to_destination () const inline virtual
Reimplemented in ModeFollow, ModeSmartRTL, ModeRTL, ModeLoiter, ModeGuided, and ModeAuto.
Definition at line 105 of file mode.h.
Referenced by Rover::Log_Write_Nav_Tuning(), and GCS_MAVLINK_Rover::send_nav_controller_output().
get_pilot_desired_heading_and_speed()
void Mode::get_pilot_desired_heading_and_speed (float & heading_out, float & speed_out) protected
Definition at line 148 of file mode.cpp.
Referenced by ModeSimple::update().
get_pilot_desired_lateral()
void Mode::get_pilot_desired_lateral (float & lateral_out) protected
Definition at line 135 of file mode.cpp.
Referenced by ModeManual::update().
get_pilot_desired_steering_and_speed()
void Mode::get_pilot_desired_steering_and_speed (float & steering_out, float & speed_out) protected
Definition at line 119 of file mode.cpp.
Referenced by ModeAcro::update(), and ModeSteering::update().
get_pilot_desired_steering_and_throttle()
void Mode::get_pilot_desired_steering_and_throttle (float & steering_out, float & throttle_out) protected
Definition at line 103 of file mode.cpp.
Referenced by ModeAcro::update(), and ModeManual::update().
get_pilot_input()
void Mode::get_pilot_input (float & steering_out, float & throttle_out) protected
Definition at line 57 of file mode.cpp.
Referenced by get_pilot_desired_steering_and_speed(), and get_pilot_desired_steering_and_throttle().
get_speed_default()
float Mode::get_speed_default (bool rtl = false) const
Definition at line 224 of file mode.cpp.
Referenced by GCS_MAVLINK_Rover::handle_command_long_packet(), GCS_MAVLINK_Rover::handleMessage(), and set_desired_speed_to_default().
handle_tack_request()
void Mode::handle_tack_request () virtual
Reimplemented in ModeAcro.
Definition at line 256 of file mode.cpp.
Referenced by RC_Channel_Rover::do_aux_function().
has_manual_input()
virtual bool Mode::has_manual_input () const inline virtual
Reimplemented in ModeInitializing, ModeSteering, ModeManual, and ModeAcro.
Definition at line 82 of file mode.h.
Referenced by GCS_MAVLINK_Rover::base_mode().
in_guided_mode()
virtual bool Mode::in_guided_mode () const inline virtual
Reimplemented in ModeGuided, and ModeAuto.
Definition at line 70 of file mode.h.
Referenced by GCS_MAVLINK_Rover::handle_command_long_packet(), GCS_MAVLINK_Rover::handle_guided_request(), and GCS_MAVLINK_Rover::handleMessage().
is_autopilot_mode()
virtual bool Mode::is_autopilot_mode () const inline virtual
Reimplemented in ModeFollow, ModeSmartRTL, ModeRTL, ModeLoiter, ModeGuided, and ModeAuto.
Definition at line 67 of file mode.h.
Referenced by allows_arming_from_transmitter(), allows_stick_mixing(), GCS_MAVLINK_Rover::base_mode(), Rover::crash_check(), crosstrack_error(), get_desired_lat_accel(), Sailboat::get_VMG(), handle_tack_request(), nav_bearing(), Rover::notify_mode(), GCS_MAVLINK_Rover::send_nav_controller_output(), GCS_Rover::update_vehicle_sensor_status_flags(), and wp_bearing().
mode_number()
virtual uint32_t Mode::mode_number () const pure virtual
Implemented in ModeSimple, ModeFollow, ModeInitializing, ModeSteering, ModeSmartRTL, ModeRTL, ModeManual, ModeLoiter, ModeHold, ModeGuided, ModeAuto, and ModeAcro.
Referenced by GCS_Rover::custom_mode(), Rover::Log_Write_Vehicle_Startup_Messages(), Rover::notify_mode(), and Rover::set_mode().
name4()
virtual const char* Mode::name4 () const pure virtual
Implemented in ModeSimple, ModeFollow, ModeInitializing, ModeSteering, ModeSmartRTL, ModeRTL, ModeManual, ModeLoiter, ModeHold, ModeGuided, ModeAuto, and ModeAcro.
Referenced by Rover::notify_mode().
nav_bearing()
float Mode::nav_bearing () const virtual
Reimplemented in ModeFollow, and ModeLoiter.
Definition at line 172 of file mode.cpp.
Referenced by Rover::Log_Write_Nav_Tuning(), and GCS_MAVLINK_Rover::send_nav_controller_output().
navigate_to_waypoint()
void Mode::navigate_to_waypoint () protected
Definition at line 386 of file mode.cpp.
Referenced by ModeAuto::update(), ModeGuided::update(), ModeRTL::update(), and ModeSmartRTL::update().
operator=()
Mode& Mode::operator= (const Mode &) delete
reached_destination()
virtual bool Mode::reached_destination () const inline virtual
Reimplemented in ModeSmartRTL, ModeRTL, ModeGuided, and ModeAuto.
Definition at line 116 of file mode.h.
Referenced by ModeAuto::reached_destination().
requires_position()
virtual bool Mode::requires_position () const inline virtual
Reimplemented in ModeSteering, ModeManual, ModeHold, and ModeAcro.
Definition at line 88 of file mode.h.
Referenced by enter(), Rover::failsafe_ekf_event(), and AP_Arming_Rover::gps_checks().
requires_velocity()
virtual bool Mode::requires_velocity () const inline virtual
Reimplemented in ModeSteering, ModeManual, ModeHold, and ModeAcro.
Definition at line 89 of file mode.h.
Referenced by enter(), and AP_Arming_Rover::gps_checks().
set_desired_heading_and_speed()
void Mode::set_desired_heading_and_speed (float yaw_angle_cd, float target_speed) virtual
Reimplemented in ModeGuided, and ModeAuto.
Definition at line 213 of file mode.cpp.
Referenced by ModeAuto::set_desired_heading_and_speed(), and ModeGuided::set_desired_heading_and_speed().
set_desired_location()
bool Mode::set_desired_location (const struct Location & destination, float next_leg_bearing_cd = AR_WPNAV_HEADING_UNKNOWN) virtual
Reimplemented in ModeGuided, and ModeAuto.
Definition at line 199 of file mode.cpp.
Referenced by ModeAuto::set_desired_location().
set_desired_speed()
bool Mode::set_desired_speed (float speed)
Definition at line 240 of file mode.cpp.
Referenced by ModeAuto::do_change_speed(), GCS_MAVLINK_Rover::handle_command_int_packet(), and GCS_MAVLINK_Rover::handle_command_long_packet().
set_desired_speed_to_default()
void Mode::set_desired_speed_to_default (bool rtl = false)
Definition at line 234 of file mode.cpp.
Referenced by ModeFollow::_enter().
set_reversed()
void Mode::set_reversed (bool value)
Definition at line 250 of file mode.cpp.
Referenced by ModeAuto::do_set_reverse(), enter(), GCS_MAVLINK_Rover::handle_command_int_packet(), and GCS_MAVLINK_Rover::handle_command_long_packet().
set_steering()
void Mode::set_steering (float steering_value) protected
Definition at line 486 of file mode.cpp.
Referenced by calc_steering_from_lateral_acceleration(), calc_steering_to_heading(), ModeAcro::update(), ModeGuided::update(), and ModeSteering::update().
speed_error()
float Mode::speed_error () const inline
Definition at line 98 of file mode.h.
Referenced by GCS_MAVLINK_Rover::send_nav_controller_output().
stop_vehicle()
bool Mode::stop_vehicle () protected
Definition at line 298 of file mode.cpp.
Referenced by ModeAuto::calc_throttle(), ModeAuto::update(), ModeGuided::update(), ModeRTL::update(), ModeSmartRTL::update(), and ModeFollow::update().
update()
virtual void Mode::update () pure virtual
Implemented in ModeSimple, ModeFollow, ModeInitializing, ModeSteering, ModeSmartRTL, ModeRTL, ModeManual, ModeLoiter, ModeHold, ModeGuided, ModeAuto, and ModeAcro.
Referenced by Rover::update_current_mode().
wp_bearing()
float Mode::wp_bearing () const virtual
Reimplemented in ModeFollow, and ModeLoiter.
Definition at line 163 of file mode.cpp.
Referenced by Rover::Log_Write_Nav_Tuning(), and GCS_MAVLINK_Rover::send_nav_controller_output().
Member Data Documentation
_desired_speed
float Mode::_desired_speed protected
Definition at line 213 of file mode.h.
Referenced by ModeLoiter::_enter(), set_desired_heading_and_speed(), ModeGuided::set_desired_heading_and_speed(), set_desired_speed(), set_desired_speed_to_default(), ModeGuided::set_desired_turn_rate_and_speed(), ModeAuto::update(), ModeGuided::update(), ModeLoiter::update(), and ModeFollow::update().
_desired_yaw_cd
float Mode::_desired_yaw_cd protected
Definition at line 212 of file mode.h.
Referenced by ModeLoiter::_enter(), ModeLoiter::nav_bearing(), set_desired_heading_and_speed(), ModeGuided::set_desired_heading_and_speed(), ModeGuided::set_desired_heading_delta_and_speed(), ModeAuto::update(), ModeGuided::update(), ModeLoiter::update(), and ModeLoiter::wp_bearing().
_distance_to_destination
float Mode::_distance_to_destination protected
Definition at line 210 of file mode.h.
Referenced by ModeAuto::get_distance_to_destination(), ModeGuided::get_distance_to_destination(), ModeLoiter::get_distance_to_destination(), ModeRTL::get_distance_to_destination(), ModeSmartRTL::get_distance_to_destination(), navigate_to_waypoint(), set_desired_location(), ModeAuto::update(), ModeGuided::update(), ModeLoiter::update(), and ModeRTL::update().
_reached_destination
bool Mode::_reached_destination protected
Definition at line 211 of file mode.h.
Referenced by ModeGuided::reached_destination(), set_desired_heading_and_speed(), ModeGuided::set_desired_heading_and_speed(), set_desired_location(), ModeGuided::set_desired_turn_rate_and_speed(), ModeSmartRTL::update(), and ModeFollow::update().
ahrs
class AP_AHRS& Mode::ahrs protected
Definition at line 201 of file mode.h.
Referenced by ModeLoiter::_enter(), ModeRTL::_enter(), ModeSmartRTL::_enter(), calc_stopping_location(), calc_throttle(), ModeAuto::do_nav_set_yaw_speed(), ModeSimple::init_heading(), ModeGuided::set_desired_heading_delta_and_speed(), ModeAuto::update(), and ModeLoiter::update().
attitude_control
class AR_AttitudeControl& Mode::attitude_control protected
Definition at line 207 of file mode.h.
Referenced by ModeLoiter::_enter(), calc_steering_from_lateral_acceleration(), calc_steering_from_turn_rate(), calc_steering_to_heading(), calc_stopping_location(), calc_throttle(), stop_vehicle(), ModeAcro::update(), ModeGuided::update(), ModeLoiter::update(), ModeSteering::update(), and ModeFollow::update().
channel_lateral
class RC_Channel*& Mode::channel_lateral protected
Definition at line 206 of file mode.h.
channel_steer
class RC_Channel*& Mode::channel_steer protected
Definition at line 204 of file mode.h.
Referenced by set_steering().
channel_throttle
class RC_Channel*& Mode::channel_throttle protected
Definition at line 205 of file mode.h.
g
class Parameters& Mode::g protected
Definition at line 202 of file mode.h.
Referenced by calc_speed_nudge(), calc_steering_from_lateral_acceleration(), calc_steering_from_turn_rate(), calc_throttle(), ModeAuto::check_trigger(), get_pilot_desired_heading_and_speed(), get_pilot_desired_steering_and_speed(), get_pilot_desired_steering_and_throttle(), stop_vehicle(), and ModeSteering::update().
g2
class ParametersG2& Mode::g2 protected
Definition at line 203 of file mode.h.
Referenced by ModeAuto::_enter(), ModeGuided::_enter(), ModeRTL::_enter(), ModeSmartRTL::_enter(), ModeFollow::_enter(), ModeManual::_exit(), calc_steering_from_lateral_acceleration(), calc_steering_from_turn_rate(), calc_steering_to_heading(), calc_throttle(), crosstrack_error(), ModeAuto::do_nav_set_yaw_speed(), ModeAuto::exit_mission(), get_desired_lat_accel(), ModeAuto::get_desired_location(), ModeGuided::get_desired_location(), ModeRTL::get_desired_location(), ModeSmartRTL::get_desired_location(), ModeFollow::get_distance_to_destination(), get_pilot_desired_steering_and_speed(), get_pilot_desired_steering_and_throttle(), get_speed_default(), nav_bearing(), navigate_to_waypoint(), ModeAuto::reached_destination(), ModeRTL::reached_destination(), ModeAcro::requires_velocity(), ModeSmartRTL::save_position(), set_desired_location(), ModeGuided::set_desired_location(), set_reversed(), set_steering(), ModeAuto::start_command(), stop_vehicle(), ModeAcro::update(), ModeAuto::update(), ModeGuided::update(), ModeHold::update(), ModeLoiter::update(), ModeManual::update(), ModeRTL::update(), ModeSmartRTL::update(), ModeSteering::update(), ModeFollow::update(), ModeSimple::update(), wp_bearing(), and ModeFollow::wp_bearing().
The documentation for this class was generated from the following files:
APMrover2/mode.h
APMrover2/mode.cpp