APM:Rover: AP_Arming_Rover Class Reference
AP_Arming_Rover Class Reference
#include <AP_Arming.h>
Public Member Functions
AP_Arming_Rover ()
AP_Arming_Rover (const AP_Arming_Rover &other)=delete
AP_Arming_Rover & operator= (const AP_Arming_Rover &)=delete
bool pre_arm_checks (bool report) override
bool arm_checks (AP_Arming::Method method) override
bool pre_arm_rc_checks (const bool display_failure)
bool gps_checks (bool display_failure) override
bool disarm () override
bool arm (AP_Arming::Method method, bool do_arming_checks=true) override
void update_soft_armed ()
Public Member Functions inherited from AP_Arming
AP_Arming ()
AP_Arming (const AP_Arming &other)=delete
AP_Arming & operator= (const AP_Arming &)=delete
Required arming_required ()
bool is_armed ()
uint16_t get_enabled_checks ()
uint16_t compass_magfield_expected () const
RudderArming get_rudder_arming_type () const
Protected Member Functions
bool oa_check (bool report)
Protected Member Functions inherited from AP_Arming
virtual bool barometer_checks (bool report)
bool airspeed_checks (bool report)
bool logging_checks (bool report)
virtual bool ins_checks (bool report)
virtual bool compass_checks (bool report)
bool battery_checks (bool report)
bool hardware_safety_check (bool report)
virtual bool board_voltage_checks (bool report)
virtual bool rc_calibration_checks (bool report)
bool manual_transmitter_checks (bool report)
bool mission_checks (bool report)
bool fence_checks (bool report)
virtual bool system_checks (bool report)
bool can_checks (bool report)
virtual bool proximity_checks (bool report) const
bool servo_checks (bool report) const
bool rc_checks_copter_sub (bool display_failure, const RC_Channel *channels[4]) const
bool check_enabled (const enum AP_Arming::ArmingChecks check) const
MAV_SEVERITY check_severity (const enum AP_Arming::ArmingChecks check) const
void check_failed (const enum AP_Arming::ArmingChecks check, bool report, const char *fmt,...) const
void Log_Write_Arm_Disarm ()
Private Member Functions
void change_arm_state (void)
Additional Inherited Members
Public Types inherited from AP_Arming
enum ArmingChecks
enum Method { Method::RUDDER, Method::MAVLINK, Method::AUXSWITCH, Method::MOTORTEST }
enum Required { Required::NO, Required::YES_MIN_PWM, Required::YES_ZERO_PWM }
enum RudderArming { RudderArming::IS_DISABLED, RudderArming::ARMONLY, RudderArming::ARMDISARM }
Static Public Member Functions inherited from AP_Arming
static AP_Arming * get_singleton ()
Public Attributes inherited from AP_Arming
ARMING_CHECK_NONE
ARMING_CHECK_ALL
ARMING_CHECK_BARO
ARMING_CHECK_COMPASS
ARMING_CHECK_GPS
ARMING_CHECK_INS
ARMING_CHECK_PARAMETERS
ARMING_CHECK_RC
ARMING_CHECK_VOLTAGE
ARMING_CHECK_BATTERY
ARMING_CHECK_AIRSPEED
ARMING_CHECK_LOGGING
ARMING_CHECK_SWITCH
ARMING_CHECK_GPS_CONFIG
ARMING_CHECK_SYSTEM
ARMING_CHECK_MISSION
Static Public Attributes inherited from AP_Arming
static const struct AP_Param::GroupInfo var_info []
Protected Attributes inherited from AP_Arming
AP_Int8 require
AP_Int16 checks_to_perform
AP_Float accel_error_threshold
AP_Int8 _rudder_arming
AP_Int32 _required_mission_items
bool armed
uint32_t last_accel_pass_ms [INS_MAX_INSTANCES]
uint32_t last_gyro_pass_ms [INS_MAX_INSTANCES]
Detailed Description
Definition at line 9 of file AP_Arming.h.
Constructor & Destructor Documentation
AP_Arming_Rover() [1/2]
AP_Arming_Rover::AP_Arming_Rover () inline
Definition at line 13 of file AP_Arming.h.
AP_Arming_Rover() [2/2]
AP_Arming_Rover::AP_Arming_Rover (const AP_Arming_Rover & other) delete
Member Function Documentation
arm()
bool AP_Arming_Rover::arm (AP_Arming::Method method, bool do_arming_checks = true) override virtual
Reimplemented from AP_Arming.
Definition at line 127 of file AP_Arming.cpp.
Referenced by Rover::mavlink_motor_test_start(), and Rover::rudder_arm_disarm_check().
arm_checks()
bool AP_Arming_Rover::arm_checks (AP_Arming::Method method) override virtual
Reimplemented from AP_Arming.
Definition at line 99 of file AP_Arming.cpp.
change_arm_state()
void AP_Arming_Rover::change_arm_state (void) private
Definition at line 118 of file AP_Arming.cpp.
Referenced by arm(), and disarm().
disarm()
bool AP_Arming_Rover::disarm (void) override virtual
Reimplemented from AP_Arming.
Definition at line 153 of file AP_Arming.cpp.
Referenced by Rover::crash_check(), Rover::failsafe_check(), Rover::handle_battery_failsafe(), and Rover::rudder_arm_disarm_check().
gps_checks()
bool AP_Arming_Rover::gps_checks (bool display_failure) override virtual
Reimplemented from AP_Arming.
Definition at line 43 of file AP_Arming.cpp.
oa_check()
bool AP_Arming_Rover::oa_check (bool report) protected
Definition at line 172 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
operator=()
AP_Arming_Rover& AP_Arming_Rover::operator= (const AP_Arming_Rover &) delete
pre_arm_checks()
bool AP_Arming_Rover::pre_arm_checks (bool report) override virtual
Reimplemented from AP_Arming.
Definition at line 82 of file AP_Arming.cpp.
Referenced by Rover::one_second_loop().
pre_arm_rc_checks()
bool AP_Arming_Rover::pre_arm_rc_checks (const bool display_failure)
Definition at line 5 of file AP_Arming.cpp.
Referenced by Rover::mavlink_motor_test_check().
update_soft_armed()
void AP_Arming_Rover::update_soft_armed ()
Definition at line 108 of file AP_Arming.cpp.
Referenced by Rover::ahrs_update(), and change_arm_state().
The documentation for this class was generated from the following files:
APMrover2/AP_Arming.h
APMrover2/AP_Arming.cpp