APM:Rover: Rover::cruise_learn_t Struct Reference
Rover::cruise_learn_t Struct Reference
Public Attributes
LowPassFilterFloat speed_filt = LowPassFilterFloat(2.0f)
LowPassFilterFloat throttle_filt = LowPassFilterFloat(2.0f)
uint32_t learn_start_ms
uint32_t log_count
Detailed Description
Definition at line 346 of file Rover.h.
Member Data Documentation
learn_start_ms
uint32_t Rover::cruise_learn_t::learn_start_ms
Definition at line 349 of file Rover.h.
Referenced by Rover::cruise_learn_complete(), Rover::cruise_learn_start(), Rover::cruise_learn_update(), and Rover::log_write_cruise_learn().
log_count
uint32_t Rover::cruise_learn_t::log_count
Definition at line 350 of file Rover.h.
Referenced by Rover::cruise_learn_start(), and Rover::cruise_learn_update().
speed_filt
LowPassFilterFloat Rover::cruise_learn_t::speed_filt = LowPassFilterFloat(2.0f)
Definition at line 347 of file Rover.h.
Referenced by Rover::cruise_learn_complete(), Rover::cruise_learn_start(), Rover::cruise_learn_update(), and Rover::log_write_cruise_learn().
throttle_filt
LowPassFilterFloat Rover::cruise_learn_t::throttle_filt = LowPassFilterFloat(2.0f)
Definition at line 348 of file Rover.h.
Referenced by Rover::cruise_learn_complete(), Rover::cruise_learn_start(), Rover::cruise_learn_update(), and Rover::log_write_cruise_learn().
The documentation for this struct was generated from the following file:
APMrover2/Rover.h