APM:Libraries: libraries/AP_IOMCU/iofirmware/analog.h File Reference
analog.h File Reference
#include <stdint.h>
Functions
void adc_init (void)
uint16_t adc_sample_vservo (void)
uint16_t adc_sample_vrssi (void)
Function Documentation
adc_init()
void adc_init (void)
Definition at line 32 of file analog.cpp.
Referenced by AP_IOMCU_FW::init().
adc_sample_vrssi()
uint16_t adc_sample_vrssi (void)
Definition at line 84 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().
adc_sample_vservo()
uint16_t adc_sample_vservo (void)
Definition at line 75 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().