APM:Libraries: libraries/AP_Mission/examples/AP_Mission_test/AP_Mission_test.cpp File Reference
AP_Mission_test.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_Mission/AP_Mission.h>
#include <AP_InertialSensor/AP_InertialSensor.h>
#include <AP_Baro/AP_Baro.h>
#include <AP_GPS/AP_GPS.h>
#include <AP_Compass/AP_Compass.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_AHRS/AP_AHRS_DCM.h>
#include <GCS_MAVLink/GCS_Dummy.h>
Classes
class GCS_MAVLINK
MAVLink transport control class.
class MissionTest
Functions
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static MissionTest missiontest
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 1362 of file AP_Mission_test.cpp.
setup()
void setup (void)
Definition at line 1358 of file AP_Mission_test.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 16 of file AP_Mission_test.cpp.
Referenced by MissionTest::init_mission(), MissionTest::init_mission_endless_loop(), MissionTest::init_mission_ends_with_do_commands(), MissionTest::init_mission_ends_with_jump_command(), MissionTest::init_mission_jump_to_nonnav(), MissionTest::init_mission_no_nav_commands(), MissionTest::init_mission_starts_with_do_commands(), MissionTest::loop(), MissionTest::mission_complete(), MissionTest::print_mission(), MissionTest::run_max_cmd_test(), MissionTest::run_mission_test(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), MissionTest::run_set_current_cmd_while_stopped_test(), MissionTest::setup(), MissionTest::start_cmd(), and MissionTest::verify_cmd().
missiontest
MissionTest missiontest static
Definition at line 65 of file AP_Mission_test.cpp.
Referenced by loop(), and setup().