APM:Libraries: libraries/AP_Logger/examples/AP_Logger_AllTypes/AP_Logger_AllTypes.cpp File Reference
AP_Logger_AllTypes.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_Logger/AP_Logger.h>
#include <GCS_MAVLink/GCS_Dummy.h>
#include <stdio.h>
Classes
struct log_TYP1
struct log_TYP2
class AP_LoggerTest_AllTypes
class GCS_MAVLINK
MAVLink transport control class.
Macros
#define TYP1_FMT "QabBhHiIfdnNZ"
#define TYP1_LBL "TimeUS,b,B,h,H,i,I,f,d,n,N,Z"
#define TYP2_FMT "QcCeELMqQ"
#define TYP2_LBL "TimeUS,c,C,e,E,L,M,q,Q"
Enumerations
enum MyLogMessages { LOG_TYP1_MSG, LOG_TYP2_MSG }
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static const struct LogStructure log_structure []
static uint16_t log_num
GCS_Dummy _gcs
static AP_LoggerTest_AllTypes loggertest
Macro Definition Documentation
TYP1_FMT
#define TYP1_FMT "QabBhHiIfdnNZ"
Definition at line 79 of file AP_Logger_AllTypes.cpp.
TYP1_LBL
#define TYP1_LBL "TimeUS,b,B,h,H,i,I,f,d,n,N,Z"
Definition at line 80 of file AP_Logger_AllTypes.cpp.
TYP2_FMT
#define TYP2_FMT "QcCeELMqQ"
Definition at line 81 of file AP_Logger_AllTypes.cpp.
TYP2_LBL
#define TYP2_LBL "TimeUS,c,C,e,E,L,M,q,Q"
Definition at line 82 of file AP_Logger_AllTypes.cpp.
Enumeration Type Documentation
MyLogMessages
enum MyLogMessages
Enumerator
LOG_TYP1_MSG
LOG_TYP2_MSG
Definition at line 45 of file AP_Logger_AllTypes.cpp.
Variable Documentation
_gcs
GCS_Dummy _gcs
Definition at line 233 of file AP_Logger_AllTypes.cpp.
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 10 of file AP_Logger_AllTypes.cpp.
Referenced by AP_LoggerTest_AllTypes::flush_logger(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), AP_LoggerTest_AllTypes::loop(), and AP_LoggerTest_AllTypes::setup().
log_num
uint16_t log_num static
Definition at line 84 of file AP_Logger_AllTypes.cpp.
Referenced by AP_Logger_Block::get_log_boundaries(), AP_Logger::get_log_boundaries(), AP_Logger_Block::get_log_data(), AP_Logger::get_log_data(), AP_Logger_Block::get_log_info(), AP_Logger::get_log_info(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), and AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write().
log_structure
const struct LogStructure log_structure[] static
Initial value:
= {
    { LOG_TYP1_MSG,
      sizeof(log_TYP1),
      "TYP1",
      "QbBhHiIfdnNZ",
      "TimeUS,b,B,h,H,i,I,f,d,n,N,Z",
      "s-----------",
      "F-----------"
    },
    { LOG_TYP2_MSG,
      sizeof(log_TYP2),
      "TYP2",
      "QcCeELMqQ",
      "TimeUS,c,C,e,E,L,M,q,Q",
      "s--------",
      "F--------"
    },
    { LOG_MESSAGE_MSG,
      sizeof(log_Message),
      "MSG",
      "QZ",
      "TimeUS,Message",
      "s-",
      "F-"}
}
Definition at line 50 of file AP_Logger_AllTypes.cpp.
Referenced by AP_LoggerTest_AllTypes::setup().
loggertest
AP_HAL_MAIN_CALLBACKS & loggertest static
Definition at line 236 of file AP_Logger_AllTypes.cpp.