APM:Libraries: libraries/AP_HAL_ChibiOS/GPIO.cpp File Reference
GPIO.cpp File Reference
#include "GPIO.h"
#include <AP_BoardConfig/AP_BoardConfig.h>
Classes
struct gpio_entry
Macros
#define NUM_PINS ARRAY_SIZE(_gpio_tab)
#define PIN_ENABLED(pin) ((pin)<NUM_PINS && _gpio_tab[pin].enabled)
Functions
static struct gpio_entry * gpio_by_pin_num (uint8_t pin_num, bool check_enabled=true)
static void pal_interrupt_cb (void *arg)
static void pal_interrupt_cb_functor (void *arg)
Variables
static struct gpio_entry _gpio_tab [] = HAL_GPIO_PINS
const AP_HAL::HAL & hal
Macro Definition Documentation
NUM_PINS
#define NUM_PINS ARRAY_SIZE(_gpio_tab)
Definition at line 34 of file GPIO.cpp.
PIN_ENABLED
#define PIN_ENABLED (pin) ((pin)<NUM_PINS && _gpio_tab[pin].enabled)
Definition at line 35 of file GPIO.cpp.
Function Documentation
gpio_by_pin_num()
static struct gpio_entry* gpio_by_pin_num (uint8_t pin_num, bool check_enabled = true) static
Definition at line 40 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::attach_interrupt(), ChibiOS::GPIO::channel(), ChibiOS::GPIO::pinMode(), ChibiOS::GPIO::read(), ChibiOS::GPIO::toggle(), and ChibiOS::GPIO::write().
pal_interrupt_cb()
void pal_interrupt_cb (void * arg) static
Definition at line 242 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::_attach_interrupt().
pal_interrupt_cb_functor()
void pal_interrupt_cb_functor (void * arg) static
Definition at line 249 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::attach_interrupt().
Variable Documentation
_gpio_tab
struct gpio_entry _gpio_tab[] = HAL_GPIO_PINS static
Referenced by gpio_by_pin_num(), and ChibiOS::GPIO::init().
hal
const AP_HAL::HAL& hal
Definition at line 21 of file AC_PID_test.cpp.
Referenced by HALSITL::DigitalSource::read(), HALSITL::DigitalSource::toggle(), and HALSITL::DigitalSource::write().