APM:Libraries: libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp File Reference
AP_Motors_test.cpp File Reference
#include <AP_Common/AP_Common.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <RC_Channel/RC_Channel.h>
#include <AP_Motors/AP_Motors.h>
#include <SRV_Channel/SRV_Channel.h>
Macros
#define HELI_TEST 0
#define NUM_OUTPUTS 4
Functions
void setup ()
void loop ()
void motor_order_test ()
void stability_test ()
void update_motors ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
SRV_Channels srvs
AP_MotorsMatrix motors (400)
AP_BattMonitor _battmonitor {0, nullptr, nullptr}
Macro Definition Documentation
HELI_TEST
#define HELI_TEST 0
Definition at line 24 of file AP_Motors_test.cpp.
NUM_OUTPUTS
#define NUM_OUTPUTS 4
Definition at line 25 of file AP_Motors_test.cpp.
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 66 of file AP_Motors_test.cpp.
motor_order_test()
void motor_order_test ()
Definition at line 91 of file AP_Motors_test.cpp.
Referenced by loop().
setup()
void setup (void)
Definition at line 39 of file AP_Motors_test.cpp.
stability_test()
void stability_test ()
Definition at line 108 of file AP_Motors_test.cpp.
Referenced by loop().
update_motors()
void update_motors ()
Definition at line 193 of file AP_Motors_test.cpp.
Referenced by stability_test().
Variable Documentation
_battmonitor
AP_BattMonitor _battmonitor {0, nullptr, nullptr}
Definition at line 36 of file AP_Motors_test.cpp.
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 15 of file AP_Motors_test.cpp.
Referenced by loop(), motor_order_test(), setup(), and stability_test().
motors
AP_MotorsMatrix motors(400)
Referenced by motor_order_test(), SITL::Morse::output_quad(), setup(), stability_test(), update_motors(), and AP_Logger::Write_Rate().
srvs
SRV_Channels srvs
Definition at line 27 of file AP_Motors_test.cpp.