APM:Libraries: libraries/AP_Math/AP_Math.cpp File Reference
AP_Math.cpp File Reference
#include "AP_Math.h"
#include <float.h>
#include <AP_InternalError/AP_InternalError.h>
Functions
template<typename Arithmetic1 , typename Arithmetic2 >
std::enable_if< std::is_integral< typename std::common_type< Arithmetic1, Arithmetic2 >::type >::value,bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
template<typename Arithmetic1 , typename Arithmetic2 >
std::enable_if< std::is_floating_point< typename std::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
template bool is_equal< int > (const int v_1, const int v_2)
template bool is_equal< short > (const short v_1, const short v_2)
template bool is_equal< long > (const long v_1, const long v_2)
template bool is_equal< float > (const float v_1, const float v_2)
template bool is_equal< double > (const double v_1, const double v_2)
template<typename T >
float safe_asin (const T v)
template float safe_asin< int > (const int v)
template float safe_asin< short > (const short v)
template float safe_asin< float > (const float v)
template float safe_asin< double > (const double v)
template<typename T >
float safe_sqrt (const T v)
template float safe_sqrt< int > (const int v)
template float safe_sqrt< short > (const short v)
template float safe_sqrt< float > (const float v)
template float safe_sqrt< double > (const double v)
float linear_interpolate (float low_output, float high_output, float var_value, float var_low, float var_high)
float expo_curve (float alpha, float x)
float throttle_curve (float thr_mid, float alpha, float thr_in)
template<typename T >
float wrap_180 (const T angle, float unit_mod)
template float wrap_180< int > (const int angle, float unit_mod)
template float wrap_180< short > (const short angle, float unit_mod)
template float wrap_180< float > (const float angle, float unit_mod)
template float wrap_180< double > (const double angle, float unit_mod)
template<typename T >
auto wrap_180_cd (const T angle) -> decltype(wrap_180(angle, 100.f))
template auto wrap_180_cd< float > (const float angle) -> decltype(wrap_180(angle, 100.f))
template auto wrap_180_cd< int > (const int angle) -> decltype(wrap_180(angle, 100.f))
template auto wrap_180_cd< long > (const long angle) -> decltype(wrap_180(angle, 100.f))
template auto wrap_180_cd< short > (const short angle) -> decltype(wrap_180(angle, 100.f))
template auto wrap_180_cd< double > (const double angle) -> decltype(wrap_360(angle, 100.f))
template<typename T >
float wrap_360 (const T angle, float unit_mod)
template float wrap_360< int > (const int angle, float unit_mod)
template float wrap_360< short > (const short angle, float unit_mod)
template float wrap_360< long > (const long angle, float unit_mod)
template float wrap_360< float > (const float angle, float unit_mod)
template float wrap_360< double > (const double angle, float unit_mod)
template<typename T >
auto wrap_360_cd (const T angle) -> decltype(wrap_360(angle, 100.f))
template auto wrap_360_cd< float > (const float angle) -> decltype(wrap_360(angle, 100.f))
template auto wrap_360_cd< int > (const int angle) -> decltype(wrap_360(angle, 100.f))
template auto wrap_360_cd< long > (const long angle) -> decltype(wrap_360(angle, 100.f))
template auto wrap_360_cd< short > (const short angle) -> decltype(wrap_360(angle, 100.f))
template auto wrap_360_cd< double > (const double angle) -> decltype(wrap_360(angle, 100.f))
template<typename T >
float wrap_PI (const T radian)
template float wrap_PI< int > (const int radian)
template float wrap_PI< short > (const short radian)
template float wrap_PI< float > (const float radian)
template float wrap_PI< double > (const double radian)
template<typename T >
float wrap_2PI (const T radian)
template float wrap_2PI< int > (const int radian)
template float wrap_2PI< short > (const short radian)
template float wrap_2PI< float > (const float radian)
template float wrap_2PI< double > (const double radian)
template<typename T >
T constrain_value (const T amt, const T low, const T high)
template int constrain_value< int > (const int amt, const int low, const int high)
template long constrain_value< long > (const long amt, const long low, const long high)
template long long constrain_value< long long > (const long long amt, const long long low, const long long high)
template short constrain_value< short > (const short amt, const short low, const short high)
template float constrain_value< float > (const float amt, const float low, const float high)
template double constrain_value< double > (const double amt, const double low, const double high)
uint16_t get_random16 (void)
float rand_float (void)
Vector3f rand_vec3f (void)
bool is_valid_octal (uint16_t octal)
bool rotation_equal (enum Rotation r1, enum Rotation r2)
Function Documentation
constrain_value()
template<typename T > T constrain_value (const T amt, const T low, const T high)
Definition at line 213 of file AP_Math.cpp.
Referenced by constrain_float(), constrain_int16(), constrain_int32(), constrain_int64(), and TEST().
constrain_value< double >()
template double constrain_value< double > (const double amt, const double low, const double high)
constrain_value< float >()
template float constrain_value< float > (const float amt, const float low, const float high)
constrain_value< int >()
template int constrain_value< int > (const int amt, const int low, const int high)
constrain_value< long >()
template long constrain_value< long > (const long amt, const long low, const long high)
constrain_value< long long >()
template long long constrain_value< long long > (const long long amt, const long long low, const long long high)
constrain_value< short >()
template short constrain_value< short > (const short amt, const short low, const short high)
expo_curve()
float expo_curve (float alpha, float x)
Definition at line 101 of file AP_Math.cpp.
Referenced by throttle_curve().
get_random16()
uint16_t get_random16 (void)
Definition at line 245 of file AP_Math.cpp.
Referenced by FlashTest::loop(), rand_num(), and CompassCalibrator::thin_samples().
is_equal() [1/2]
template<typename Arithmetic1 , typename Arithmetic2 > std::enable_if<std::is_integral<typename std::common_type<Arithmetic1, Arithmetic2>::type>::value ,bool>::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
Definition at line 14 of file AP_Math.cpp.
Referenced by AP_Baro_Backend::_copy_to_frontend(), AP_GeodesicGrid::_from_neighbor_umbrella(), GCS_MAVLINK::_handle_command_preflight_calibration(), HALSITL::SITL_State::_update_rangefinder(), AP_InertialSensor::accel_calibrated_ok_all(), SITL::Aircraft::adjust_frame_time(), AP_TempCalibration::calculate_calibration(), AP_Camera::control(), AP_Param::convert_old_parameter(), AP_AHRS_DCM::drift_correction(), SITL::Aircraft::fill_fdm(), AP_AccelCal::gcs_vehicle_position(), GCS_MAVLINK::handle_command_do_set_home(), GCS_MAVLINK::handle_command_int_do_set_home(), GCS_MAVLINK::handle_command_long_packet(), GCS_MAVLINK::handle_command_preflight_can(), GCS_MAVLINK::handle_command_preflight_set_sensor_offsets(), GCS_MAVLINK::handle_command_request_autopilot_capabilities(), GCS_MAVLINK::handle_param_set(), SoloGimbal_Parameters::handle_param_value(), GCS_MAVLINK::handle_preflight_reboot(), AC_Circle::init_start_angle(), Location::offset(), Vector2< int32_t >::operator !=(), Vector3< int32_t >::operator !=(), Vector2< int32_t >::operator==(), Vector3< int32_t >::operator==(), AP_Param::save_sync(), SITL::XPlane::send_data(), AR_WPNav::set_desired_location(), HALSITL::SITL_State::set_height_agl(), SoloGimbal_Parameters::set_param(), AC_Circle::set_rate(), Compass::setHIL(), setup(), SITL::Gripper_Servo::should_report(), TEST(), AC_AutoTune::twitching_abort_rate(), CompassCalibrator::update(), AP_InertialSensor_Backend::update_gyro(), AP_L1_Control::update_waypoint(), AP_Logger::validate_structures(), and AP_AHRS_DCM::yaw_error_compass().
is_equal() [2/2]
template<typename Arithmetic1 , typename Arithmetic2 > std::enable_if<std::is_floating_point<typename std::common_type<Arithmetic1, Arithmetic2>::type>::value, bool>::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
Definition at line 26 of file AP_Math.cpp.
is_equal< double >()
template bool is_equal< double > (const double v_1, const double v_2)
is_equal< float >()
template bool is_equal< float > (const float v_1, const float v_2)
is_equal< int >()
template bool is_equal< int > (const int v_1, const int v_2)
is_equal< long >()
template bool is_equal< long > (const long v_1, const long v_2)
is_equal< short >()
template bool is_equal< short > (const short v_1, const short v_2)
is_valid_octal()
bool is_valid_octal (uint16_t octal)
Definition at line 274 of file AP_Math.cpp.
Referenced by AP_ADSB::update().
linear_interpolate()
float linear_interpolate (float low_output, float high_output, float var_value, float var_low, float var_high)
Definition at line 83 of file AP_Math.cpp.
Referenced by SITL::Sailboat::calc_lift_and_drag(), AP_Tuning::check_input(), AP_Landing_Deepstall::override_servos(), throttle_curve(), and AP_WindVane_Analog::update_direction().
rand_float()
float rand_float (void)
Definition at line 257 of file AP_Math.cpp.
Referenced by AP_Baro_SITL::_timer(), HALSITL::SITL_State::_update_airspeed(), HALSITL::SITL_State::_update_rangefinder(), AP_InertialSensor_SITL::generate_accel(), AP_InertialSensor_SITL::generate_gyro(), rand_vec3f(), and AP_OpticalFlow_SITL::update().
rand_vec3f()
Vector3f rand_vec3f (void)
Definition at line 262 of file AP_Math.cpp.
Referenced by AP_Compass_SITL::_timer().
rotation_equal()
bool rotation_equal (enum Rotation r1, enum Rotation r2)
Definition at line 295 of file AP_Math.cpp.
Referenced by CompassCalibrator::calculate_orientation().
safe_asin()
template<typename T > float safe_asin (const T v)
Definition at line 45 of file AP_Math.cpp.
Referenced by Quaternion::get_euler_pitch(), AP_MotorsHeli_Swash::get_linear_servo_output(), AP_MotorsTri::output_armed_stabilizing(), Matrix3< float >::to_euler(), and AP_AHRS::update_AOA_SSA().
safe_asin< double >()
template float safe_asin< double > (const double v)
safe_asin< float >()
template float safe_asin< float > (const float v)
safe_asin< int >()
template float safe_asin< int > (const int v)
safe_asin< short >()
template float safe_asin< short > (const short v)
safe_sqrt()
template<typename T > float safe_sqrt (const T v)
Definition at line 66 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AP_MotorsMulticopter::apply_thrust_curve_and_volt_scaling(), AP_AHRS_NavEKF::attitudes_consistent(), AP_AHRS::calc_trig(), AC_Circle::calc_velocities(), AC_AttitudeControl::control_monitor_log(), AC_AttitudeControl::control_monitor_rms_output_pitch(), AC_AttitudeControl::control_monitor_rms_output_pitch_D(), AC_AttitudeControl::control_monitor_rms_output_pitch_P(), AC_AttitudeControl::control_monitor_rms_output_roll(), AC_AttitudeControl::control_monitor_rms_output_roll_D(), AC_AttitudeControl::control_monitor_rms_output_roll_P(), AC_AttitudeControl::control_monitor_rms_output_yaw(), Vector3< int32_t >::distance_to_segment(), AC_Avoid::get_max_speed(), AC_WPNav::get_slow_down_speed(), AP_Follow::get_target_dist_and_vel_ned(), AP_InertialSensor::get_vibration_levels(), NavEKF2::Log_Write_Beacon(), AP_GPS_SBF::process_message(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), AC_PosControl::set_alt_target_from_climb_rate_ff(), AR_WPNav::set_desired_location(), AC_WPNav::set_spline_origin_and_destination(), AC_WPNav::set_wp_origin_and_destination(), AC_AttitudeControl::sqrt_controller(), AC_PosControl::sqrt_controller(), SITL::Sailboat::update(), and AR_WPNav::update_desired_speed().
safe_sqrt< double >()
template float safe_sqrt< double > (const double v)
safe_sqrt< float >()
template float safe_sqrt< float > (const float v)
safe_sqrt< int >()
template float safe_sqrt< int > (const int v)
safe_sqrt< short >()
template float safe_sqrt< short > (const short v)
throttle_curve()
float throttle_curve (float thr_mid, float alpha, float thr_in)
Definition at line 111 of file AP_Math.cpp.
wrap_180()
template<typename T > float wrap_180 (const T angle, float unit_mod)
Definition at line 127 of file AP_Math.cpp.
Referenced by AP_Proximity_Backend::convert_angle_to_sector(), AP_Beacon_Backend::correct_for_orient_yaw(), AP_Proximity_MAV::handle_msg(), AP_OABendyRuler::update(), SITL::Sailboat::update(), AP_Proximity_Backend::update_locations(), AP_Landing_Deepstall::verify_land(), and wrap_180_cd().
wrap_180< double >()
template float wrap_180< double > (const double angle, float unit_mod)
wrap_180< float >()
template float wrap_180< float > (const float angle, float unit_mod)
wrap_180< int >()
template float wrap_180< int > (const int angle, float unit_mod)
wrap_180< short >()
template float wrap_180< short > (const short angle, float unit_mod)
wrap_180_cd()
template<typename T > auto wrap_180_cd (const T angle) -> decltype(wrap_180(angle, 100.f))
Definition at line 142 of file AP_Math.cpp.
Referenced by AP_L1_Control::_prevent_indecision(), AC_AutoTune::control_attitude(), AC_AutoTune::currently_level(), AR_AttitudeControl::get_forward_speed(), AP_L1_Control::get_yaw_sensor(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_yaw(), AP_L1_Control::nav_bearing_cd(), AR_WPNav::set_desired_location(), AP_L1_Control::target_bearing_cd(), TEST(), test_wrap_cd(), AR_WPNav::update_desired_speed(), AP_L1_Control::update_heading_hold(), AR_WPNav::update_steering(), AP_AHRS_DCM::use_compass(), and AP_Landing_Deepstall::verify_land().
wrap_180_cd< double >()
template auto wrap_180_cd< double > (const double angle) -> decltype(wrap_360(angle, 100.f))
wrap_180_cd< float >()
template auto wrap_180_cd< float > (const float angle) -> decltype(wrap_180(angle, 100.f))
wrap_180_cd< int >()
template auto wrap_180_cd< int > (const int angle) -> decltype(wrap_180(angle, 100.f))
wrap_180_cd< long >()
template auto wrap_180_cd< long > (const long angle) -> decltype(wrap_180(angle, 100.f))
wrap_180_cd< short >()
template auto wrap_180_cd< short > (const short angle) -> decltype(wrap_180(angle, 100.f))
wrap_2PI()
template<typename T > float wrap_2PI (const T radian)
Definition at line 198 of file AP_Math.cpp.
Referenced by AP_Beacon::get_next_boundary_point(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), CompassLearn::process_sample(), TEST(), and wrap_PI().
wrap_2PI< double >()
template float wrap_2PI< double > (const double radian)
wrap_2PI< float >()
template float wrap_2PI< float > (const float radian)
wrap_2PI< int >()
template float wrap_2PI< int > (const int radian)
wrap_2PI< short >()
template float wrap_2PI< short > (const short radian)
wrap_360()
template<typename T > float wrap_360 (const T angle, float unit_mod)
Definition at line 154 of file AP_Math.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AP_GPS_SIRF::_parse_gps(), AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_AHRS_View::AP_AHRS_View(), AP_GPS::calc_blended_state(), AP_Proximity_SITL::get_distance_to_fence(), AP_Proximity_Backend::get_next_ignore_start_or_end(), AP_Proximity_MAV::handle_msg(), AP_GPS_MAV::handle_msg(), AP_Proximity_LightWareSF40C::init_sectors(), AP_Proximity_RPLidarA2::init_sectors(), AP_Proximity_RPLidarA2::parse_response_data(), AP_GPS_SBF::process_message(), CompassLearn::process_sample(), AP_GPS_MTK::read(), AP_GPS_MTK19::read(), AP_WindVane::send_wind(), AP_AHRS_View::set_pitch_trim(), AP_GPS::setHIL(), AP_Proximity_MorseSITL::update(), wrap_180(), and wrap_360_cd().
wrap_360< double >()
template float wrap_360< double > (const double angle, float unit_mod)
wrap_360< float >()
template float wrap_360< float > (const float angle, float unit_mod)
wrap_360< int >()
template float wrap_360< int > (const int angle, float unit_mod)
wrap_360< long >()
template float wrap_360< long > (const long angle, float unit_mod)
wrap_360< short >()
template float wrap_360< short > (const short angle, float unit_mod)
wrap_360_cd()
template<typename T > auto wrap_360_cd (const T angle) -> decltype(wrap_360(angle, 100.f))
Definition at line 171 of file AP_Math.cpp.
Referenced by AP_OSD_Screen::draw_home(), AP_OSD_Screen::draw_speed_vector(), AP_OSD_Screen::draw_waypoint(), NavEKF2::Log_Write_EKF1(), NavEKF3::Log_Write_EKF1(), SITL::SITL::Log_Write_SIMSTATE(), SITL::ADSB::send_report(), TEST(), test_wrap_cd(), AR_WPNav::update_steering(), AP_Logger::Write_AHRS2(), AP_Logger::Write_Attitude(), and AP_Logger::Write_AttitudeView().
wrap_360_cd< double >()
template auto wrap_360_cd< double > (const double angle) -> decltype(wrap_360(angle, 100.f))
wrap_360_cd< float >()
template auto wrap_360_cd< float > (const float angle) -> decltype(wrap_360(angle, 100.f))
wrap_360_cd< int >()
template auto wrap_360_cd< int > (const int angle) -> decltype(wrap_360(angle, 100.f))
wrap_360_cd< long >()
template auto wrap_360_cd< long > (const long angle) -> decltype(wrap_360(angle, 100.f))
wrap_360_cd< short >()
template auto wrap_360_cd< short > (const short angle) -> decltype(wrap_360(angle, 100.f))
wrap_PI()
template<typename T > float wrap_PI (const T radian)
Definition at line 183 of file AP_Math.cpp.
Referenced by AP_Mount_Backend::calc_angle_to_location(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), AP_WindVane_Backend::direction_update_frontend(), AP_AHRS_DCM::drift_correction_yaw(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AP_WindVane::get_apparent_wind_direction_rad(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_L1_Control::get_yaw(), NavEKF2::getLastYawResetAngle(), NavEKF3::getLastYawResetAngle(), AC_Circle::init_start_angle(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_m(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_p(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_shaping_rate_predictor(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AC_Loiter::set_pilot_desired_acceleration(), TEST(), test_wrap_cd(), AC_AttitudeControl::thrust_heading_rotation_angles(), Quaternion::to_axis_angle(), AP_WindVane_NMEA::update(), AC_Circle::update(), AP_WindVane_Home::update_direction(), AP_WindVane_Analog::update_direction(), AP_Landing_Deepstall::update_steering(), AP_WindVane::update_true_wind_speed_and_direction(), NavEKF2::updateLaneSwitchYawResetData(), and NavEKF3::updateLaneSwitchYawResetData().
wrap_PI< double >()
template float wrap_PI< double > (const double radian)
wrap_PI< float >()
template float wrap_PI< float > (const float radian)
wrap_PI< int >()
template float wrap_PI< int > (const int radian)
wrap_PI< short >()
template float wrap_PI< short > (const short radian)