APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.h File Reference
bouncebuffer.h File Reference
Classes
struct bouncebuffer_t
Functions
void bouncebuffer_init (struct bouncebuffer_t **bouncebuffer, uint32_t prealloc_bytes, bool sdcard)
void bouncebuffer_setup_read (struct bouncebuffer_t *bouncebuffer, uint8_t **buf, uint32_t size)
void bouncebuffer_finish_read (struct bouncebuffer_t *bouncebuffer, const uint8_t *buf, uint32_t size)
void bouncebuffer_setup_write (struct bouncebuffer_t *bouncebuffer, const uint8_t **buf, uint32_t size)
void bouncebuffer_finish_write (struct bouncebuffer_t *bouncebuffer, const uint8_t *buf)
Function Documentation
bouncebuffer_finish_read()
void bouncebuffer_finish_read (struct bouncebuffer_t * bouncebuffer, const uint8_t * buf, uint32_t size)
Definition at line 83 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_finish().
bouncebuffer_finish_write()
void bouncebuffer_finish_write (struct bouncebuffer_t * bouncebuffer, const uint8_t * buf)
Definition at line 128 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_finish().
bouncebuffer_init()
void bouncebuffer_init (struct bouncebuffer_t ** bouncebuffer, uint32_t prealloc_bytes, bool sdcard)
Definition at line 39 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::DeviceBus(), and sdcard_init().
bouncebuffer_setup_read()
void bouncebuffer_setup_read (struct bouncebuffer_t * bouncebuffer, uint8_t ** buf, uint32_t size)
Definition at line 56 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_setup().
bouncebuffer_setup_write()
void bouncebuffer_setup_write (struct bouncebuffer_t * bouncebuffer, const uint8_t ** buf, uint32_t size)
Definition at line 98 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_setup().