APM:Libraries: AP_Relay Class Reference
AP_Relay Class Reference
Class to manage the ArduPilot relay.
#include <AP_Relay.h>
Public Member Functions
AP_Relay ()
AP_Relay (const AP_Relay &other)=delete
AP_Relay & operator= (const AP_Relay &)=delete
void init ()
void on (uint8_t relay)
void off (uint8_t relay)
bool enabled (uint8_t relay)
void toggle (uint8_t relay)
Static Public Member Functions
static AP_Relay * get_singleton (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 _pin [AP_RELAY_NUM_RELAYS]
AP_Int8 _default
Static Private Attributes
static AP_Relay * singleton
Detailed Description
Class to manage the ArduPilot relay.
Definition at line 18 of file AP_Relay.h.
Constructor & Destructor Documentation
AP_Relay() [1/2]
AP_Relay::AP_Relay (void)
Definition at line 105 of file AP_Relay.cpp.
AP_Relay() [2/2]
AP_Relay::AP_Relay (const AP_Relay & other) delete
Member Function Documentation
enabled()
bool AP_Relay::enabled (uint8_t relay) inline
Definition at line 36 of file AP_Relay.h.
Referenced by AP_Relay_enabled(), AP_ServoRelayEvents::do_repeat_relay(), and AP_ServoRelayEvents::do_set_relay().
get_singleton()
static AP_Relay* AP_Relay::get_singleton (void) inline static
Definition at line 41 of file AP_Relay.h.
Referenced by AP_Relay_enabled(), AP_Relay_off(), AP_Relay_on(), AP_Relay_toggle(), and AP::relay().
init()
void AP_Relay::init (void)
Definition at line 118 of file AP_Relay.cpp.
off()
void AP_Relay::off (uint8_t relay)
Definition at line 145 of file AP_Relay.cpp.
Referenced by AP_Relay_off(), AP_ServoRelayEvents::do_set_relay(), init(), AP_Camera::relay_pic(), toggle(), AP_Camera::trigger_pic_cleanup(), and AP_Parachute::update().
on()
void AP_Relay::on (uint8_t relay)
Definition at line 136 of file AP_Relay.cpp.
Referenced by AP_Relay_on(), AP_ServoRelayEvents::do_set_relay(), init(), AP_Camera::relay_pic(), toggle(), AP_Camera::trigger_pic_cleanup(), and AP_Parachute::update().
operator=()
AP_Relay& AP_Relay::operator= (const AP_Relay &) delete
toggle()
void AP_Relay::toggle (uint8_t relay)
Definition at line 154 of file AP_Relay.cpp.
Referenced by AP_Relay_toggle(), AP_ServoRelayEvents::do_set_relay(), and AP_ServoRelayEvents::update_events().
Member Data Documentation
_default
AP_Int8 AP_Relay::_default private
Definition at line 49 of file AP_Relay.h.
Referenced by init().
_pin
AP_Int8 AP_Relay::_pin[AP_RELAY_NUM_RELAYS] private
Definition at line 48 of file AP_Relay.h.
Referenced by enabled(), init(), off(), on(), and toggle().
singleton
AP_Relay * AP_Relay::singleton static private
Definition at line 46 of file AP_Relay.h.
Referenced by AP_Relay(), and get_singleton().
var_info
const AP_Param::GroupInfo AP_Relay::var_info static
Definition at line 43 of file AP_Relay.h.
Referenced by AP_Relay().
The documentation for this class was generated from the following files:
libraries/AP_Relay/AP_Relay.h
libraries/AP_Relay/AP_Relay.cpp