APM:Libraries: MissionItemProtocol Class Reference
MissionItemProtocol Class Reference abstract
#include <GCS.h>
Public Member Functions
void handle_mission_request_list (const GCS_MAVLINK &link, const mavlink_mission_request_list_t &packet, const mavlink_message_t &msg)
void handle_mission_request_int (const GCS_MAVLINK &link, const mavlink_mission_request_int_t &packet, const mavlink_message_t &msg)
void handle_mission_request (const GCS_MAVLINK &link, const mavlink_mission_request_t &packet, const mavlink_message_t &msg)
void handle_mission_count (class GCS_MAVLINK &link, const mavlink_mission_count_t &packet, const mavlink_message_t &msg)
void handle_mission_write_partial_list (GCS_MAVLINK &link, const mavlink_message_t &msg, const mavlink_mission_write_partial_list_t &packet)
void handle_mission_item (const mavlink_message_t &msg, const mavlink_mission_item_int_t &cmd)
void handle_mission_clear_all (const GCS_MAVLINK &link, const mavlink_message_t &msg)
void queued_request_send ()
Send the next pending waypoint, called from deferred message handling code.
void update ()
bool active_link_is (const GCS_MAVLINK *_link) const
virtual MAV_MISSION_TYPE mission_type () const =0
Public Attributes
bool receiving
Protected Member Functions
virtual ap_message next_item_ap_message_id () const =0
virtual bool clear_all_items ()=0
Protected Attributes
GCS_MAVLINK * link
uint16_t request_last
Private Member Functions
virtual void truncate (const mavlink_mission_count_t &packet)=0
virtual MAV_MISSION_RESULT get_item (const GCS_MAVLINK &_link, const mavlink_message_t &msg, const mavlink_mission_request_int_t &packet, mavlink_mission_item_int_t &ret_packet)=0
void init_send_requests (GCS_MAVLINK &_link, const mavlink_message_t &msg, const int16_t _request_first, const int16_t _request_last)
void send_mission_ack (const mavlink_message_t &msg, MAV_MISSION_RESULT result) const
void send_mission_ack (const GCS_MAVLINK &link, const mavlink_message_t &msg, MAV_MISSION_RESULT result) const
virtual uint16_t item_count () const =0
virtual uint16_t max_items () const =0
virtual MAV_MISSION_RESULT replace_item (const mavlink_mission_item_int_t &mission_item_int)=0
virtual MAV_MISSION_RESULT append_item (const mavlink_mission_item_int_t &mission_item_int)=0
virtual void complete (const GCS_MAVLINK &_link)
virtual void timeout ()
void convert_MISSION_REQUEST_to_MISSION_REQUEST_INT (const mavlink_mission_request_t &request, mavlink_mission_request_int_t &request_int)
Private Attributes
uint16_t request_i
uint8_t dest_sysid
uint8_t dest_compid
uint32_t timelast_receive_ms
uint32_t timelast_request_ms
const uint16_t upload_timeout_ms = 8000
Detailed Description
Definition at line 126 of file GCS.h.
Member Function Documentation
active_link_is()
bool MissionItemProtocol::active_link_is (const GCS_MAVLINK * _link) const inline
Definition at line 160 of file GCS.h.
Referenced by GCS_MAVLINK::requesting_mission_items().
append_item()
virtual MAV_MISSION_RESULT MissionItemProtocol::append_item (const mavlink_mission_item_int_t & mission_item_int) private pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item().
clear_all_items()
virtual bool MissionItemProtocol::clear_all_items () protected pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_clear_all().
complete()
virtual void MissionItemProtocol::complete (const GCS_MAVLINK & _link) inline private virtual
Reimplemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Definition at line 211 of file GCS.h.
Referenced by handle_mission_count(), and handle_mission_item().
convert_MISSION_REQUEST_to_MISSION_REQUEST_INT()
void MissionItemProtocol::convert_MISSION_REQUEST_to_MISSION_REQUEST_INT (const mavlink_mission_request_t & request, mavlink_mission_request_int_t & request_int) private
Definition at line 659 of file GCS_Common.cpp.
Referenced by handle_mission_request().
get_item()
virtual MAV_MISSION_RESULT MissionItemProtocol::get_item (const GCS_MAVLINK & _link, const mavlink_message_t & msg, const mavlink_mission_request_int_t & packet, mavlink_mission_item_int_t & ret_packet) private pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_request(), and handle_mission_request_int().
handle_mission_clear_all()
void MissionItemProtocol::handle_mission_clear_all (const GCS_MAVLINK & link, const mavlink_message_t & msg)
Definition at line 826 of file GCS_Common.cpp.
handle_mission_count()
void MissionItemProtocol::handle_mission_count (class GCS_MAVLINK & link, const mavlink_mission_count_t & packet, const mavlink_message_t & msg)
Definition at line 756 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_count().
handle_mission_item()
void MissionItemProtocol::handle_mission_item (const mavlink_message_t & msg, const mavlink_mission_item_int_t & cmd)
Definition at line 1073 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_item().
handle_mission_request()
void MissionItemProtocol::handle_mission_request (const GCS_MAVLINK & link, const mavlink_mission_request_t & packet, const mavlink_message_t & msg)
Definition at line 667 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_request().
handle_mission_request_int()
void MissionItemProtocol::handle_mission_request_int (const GCS_MAVLINK & link, const mavlink_mission_request_int_t & packet, const mavlink_message_t & msg)
Definition at line 553 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_request_int().
handle_mission_request_list()
void MissionItemProtocol::handle_mission_request_list (const GCS_MAVLINK & link, const mavlink_mission_request_list_t & packet, const mavlink_message_t & msg)
Definition at line 532 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_request_list().
handle_mission_write_partial_list()
void MissionItemProtocol::handle_mission_write_partial_list (GCS_MAVLINK & link, const mavlink_message_t & msg, const mavlink_mission_write_partial_list_t & packet)
Definition at line 860 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_write_partial_list().
init_send_requests()
void MissionItemProtocol::init_send_requests (GCS_MAVLINK & _link, const mavlink_message_t & msg, const int16_t _request_first, const int16_t _request_last) private
Definition at line 736 of file GCS_Common.cpp.
Referenced by handle_mission_count(), and handle_mission_write_partial_list().
item_count()
virtual uint16_t MissionItemProtocol::item_count () const private pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item(), handle_mission_request_list(), and handle_mission_write_partial_list().
max_items()
virtual uint16_t MissionItemProtocol::max_items () const private pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_count().
mission_type()
virtual MAV_MISSION_TYPE MissionItemProtocol::mission_type () const pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_request_list(), queued_request_send(), and send_mission_ack().
next_item_ap_message_id()
virtual ap_message MissionItemProtocol::next_item_ap_message_id () const protected pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item(), init_send_requests(), and update().
queued_request_send()
void MissionItemProtocol::queued_request_send ()
Send the next pending waypoint, called from deferred message handling code.
Definition at line 188 of file GCS_Common.cpp.
Referenced by handle_mission_item(), and GCS::try_send_queued_message_for_type().
replace_item()
virtual MAV_MISSION_RESULT MissionItemProtocol::replace_item (const mavlink_mission_item_int_t & mission_item_int) private pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item().
send_mission_ack() [1/2]
void MissionItemProtocol::send_mission_ack (const mavlink_message_t & msg, MAV_MISSION_RESULT result) const private
Definition at line 235 of file GCS_Common.cpp.
Referenced by handle_mission_clear_all(), handle_mission_count(), handle_mission_item(), handle_mission_request_int(), handle_mission_request_list(), and handle_mission_write_partial_list().
send_mission_ack() [2/2]
void MissionItemProtocol::send_mission_ack (const GCS_MAVLINK & link, const mavlink_message_t & msg, MAV_MISSION_RESULT result) const private
Definition at line 244 of file GCS_Common.cpp.
timeout()
virtual void MissionItemProtocol::timeout () inline private virtual
Reimplemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Definition at line 212 of file GCS.h.
Referenced by update().
truncate()
virtual void MissionItemProtocol::truncate (const mavlink_mission_count_t & packet) private pure virtual
Implemented in MissionItemProtocol_Rally, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_count().
update()
void MissionItemProtocol::update (void)
Definition at line 209 of file GCS_Common.cpp.
Referenced by GCS::update_send().
Member Data Documentation
dest_compid
uint8_t MissionItemProtocol::dest_compid private
Definition at line 186 of file GCS.h.
Referenced by handle_mission_count(), handle_mission_item(), init_send_requests(), and queued_request_send().
dest_sysid
uint8_t MissionItemProtocol::dest_sysid private
Definition at line 185 of file GCS.h.
Referenced by handle_mission_count(), handle_mission_item(), init_send_requests(), and queued_request_send().
link
GCS_MAVLINK* MissionItemProtocol::link protected
Definition at line 168 of file GCS.h.
Referenced by active_link_is(), handle_mission_item(), init_send_requests(), queued_request_send(), send_mission_ack(), MissionItemProtocol_Waypoints::timeout(), MissionItemProtocol_Rally::timeout(), and update().
receiving
bool MissionItemProtocol::receiving
Definition at line 164 of file GCS.h.
Referenced by handle_mission_clear_all(), handle_mission_count(), handle_mission_item(), GCS_MAVLINK::handle_mission_item(), handle_mission_request_int(), handle_mission_request_list(), init_send_requests(), queued_request_send(), GCS_MAVLINK::requesting_mission_items(), and update().
request_i
uint16_t MissionItemProtocol::request_i private
Definition at line 182 of file GCS.h.
Referenced by handle_mission_item(), init_send_requests(), and queued_request_send().
request_last
uint16_t MissionItemProtocol::request_last protected
Definition at line 176 of file GCS.h.
Referenced by MissionItemProtocol_Waypoints::append_item(), handle_mission_item(), init_send_requests(), queued_request_send(), and MissionItemProtocol_Waypoints::replace_item().
timelast_receive_ms
uint32_t MissionItemProtocol::timelast_receive_ms private
Definition at line 187 of file GCS.h.
Referenced by handle_mission_item(), init_send_requests(), and update().
timelast_request_ms
uint32_t MissionItemProtocol::timelast_request_ms private
Definition at line 188 of file GCS.h.
Referenced by init_send_requests(), queued_request_send(), and update().
upload_timeout_ms
const uint16_t MissionItemProtocol::upload_timeout_ms = 8000 private
Definition at line 189 of file GCS.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp