APM:Libraries: OpticalFlow_backend Class Reference
OpticalFlow_backend Class Reference abstract
#include <OpticalFlow_backend.h>
Public Member Functions
OpticalFlow_backend (OpticalFlow &_frontend)
virtual ~OpticalFlow_backend (void)
virtual void init ()=0
virtual void update ()=0
virtual void handle_msg (const mavlink_message_t *msg)
Protected Member Functions
void _update_frontend (const struct OpticalFlow::OpticalFlow_state &state)
Vector2f _flowScaler (void) const
float _yawAngleRad (void) const
void _applyYaw (Vector2f &v)
uint8_t get_address (void) const
Protected Attributes
OpticalFlow & frontend
HAL_Semaphore _sem
Friends
class OpticalFlow
Detailed Description
Definition at line 23 of file OpticalFlow_backend.h.
Constructor & Destructor Documentation
OpticalFlow_backend()
OpticalFlow_backend::OpticalFlow_backend (OpticalFlow & _frontend)
Definition at line 20 of file OpticalFlow_backend.cpp.
~OpticalFlow_backend()
OpticalFlow_backend::~OpticalFlow_backend (void) virtual
Definition at line 25 of file OpticalFlow_backend.cpp.
Member Function Documentation
_applyYaw()
void OpticalFlow_backend::_applyYaw (Vector2f & v) protected
Definition at line 36 of file OpticalFlow_backend.cpp.
Referenced by AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_MAV::update(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_SITL::update(), and AP_OpticalFlow_Onboard::update().
_flowScaler()
Vector2f OpticalFlow_backend::_flowScaler (void) const inline protected
Definition at line 49 of file OpticalFlow_backend.h.
Referenced by AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_MAV::update(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_CXOF::update(), and AP_OpticalFlow_Onboard::update().
_update_frontend()
void OpticalFlow_backend::_update_frontend (const struct OpticalFlow::OpticalFlow_state & state) protected
Definition at line 30 of file OpticalFlow_backend.cpp.
Referenced by AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_MAV::update(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_SITL::update(), and AP_OpticalFlow_Onboard::update().
_yawAngleRad()
float OpticalFlow_backend::_yawAngleRad (void) const inline protected
Definition at line 52 of file OpticalFlow_backend.h.
Referenced by _applyYaw().
get_address()
uint8_t OpticalFlow_backend::get_address (void) const inline protected
Definition at line 58 of file OpticalFlow_backend.h.
Referenced by AP_OpticalFlow_PX4Flow::scan_buses().
handle_msg()
virtual void OpticalFlow_backend::handle_msg (const mavlink_message_t * msg) inline virtual
Reimplemented in AP_OpticalFlow_MAV.
Definition at line 39 of file OpticalFlow_backend.h.
Referenced by OpticalFlow::handle_msg().
init()
virtual void OpticalFlow_backend::init () pure virtual
Implemented in AP_OpticalFlow_Onboard, AP_OpticalFlow_SITL, AP_OpticalFlow_CXOF, AP_OpticalFlow_MAV, AP_OpticalFlow_Pixart, and AP_OpticalFlow_PX4Flow.
Referenced by OpticalFlow::init().
update()
virtual void OpticalFlow_backend::update () pure virtual
Implemented in AP_OpticalFlow_Onboard, AP_OpticalFlow_SITL, AP_OpticalFlow_CXOF, AP_OpticalFlow_MAV, AP_OpticalFlow_Pixart, and AP_OpticalFlow_PX4Flow.
Referenced by OpticalFlow::update().
Friends And Related Function Documentation
OpticalFlow
friend class OpticalFlow friend
Definition at line 25 of file OpticalFlow_backend.h.
Member Data Documentation
_sem
HAL_Semaphore OpticalFlow_backend::_sem protected
Definition at line 61 of file OpticalFlow_backend.h.
Referenced by AP_OpticalFlow_Pixart::timer(), and AP_OpticalFlow_Pixart::update().
frontend
OpticalFlow& OpticalFlow_backend::frontend protected
Definition at line 43 of file OpticalFlow_backend.h.
Referenced by _flowScaler(), _update_frontend(), _yawAngleRad(), and get_address().
The documentation for this class was generated from the following files:
libraries/AP_OpticalFlow/OpticalFlow_backend.h
libraries/AP_OpticalFlow/OpticalFlow_backend.cpp