APM:Libraries: AP_WheelRateControl Class Reference
AP_WheelRateControl Class Reference
#include <AP_WheelRateControl.h>
Classes
struct AP_MotorsUGV_limit
Public Member Functions
AP_WheelRateControl (const AP_WheelEncoder &wheel_encoder_ref)
bool enabled (uint8_t instance)
float get_rate_controlled_throttle (uint8_t instance, float desired_rate_pct, float dt)
float get_rate_max_rads () const
AC_PID & get_pid (uint8_t instance)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 _enabled
AP_Float _rate_max
AC_PID _rate_pid0 = AC_PID(AP_WHEEL_RATE_CONTROL_P, AP_WHEEL_RATE_CONTROL_I, AP_WHEEL_RATE_CONTROL_D, AP_WHEEL_RATE_CONTROL_IMAX, AP_WHEEL_RATE_CONTROL_FILT, AP_WHEEL_RATE_CONTROL_DT, AP_WHEEL_RATE_CONTROL_FF)
AC_PID _rate_pid1 = AC_PID(AP_WHEEL_RATE_CONTROL_P, AP_WHEEL_RATE_CONTROL_I, AP_WHEEL_RATE_CONTROL_D, AP_WHEEL_RATE_CONTROL_IMAX, AP_WHEEL_RATE_CONTROL_FILT, AP_WHEEL_RATE_CONTROL_DT, AP_WHEEL_RATE_CONTROL_FF)
struct AP_WheelRateControl::AP_MotorsUGV_limit _limit [2]
const AP_WheelEncoder & _wheel_encoder
uint32_t _last_update_ms
Detailed Description
Definition at line 35 of file AP_WheelRateControl.h.
Constructor & Destructor Documentation
AP_WheelRateControl()
AP_WheelRateControl::AP_WheelRateControl (const AP_WheelEncoder & wheel_encoder_ref)
Definition at line 100 of file AP_WheelRateControl.cpp.
Member Function Documentation
enabled()
bool AP_WheelRateControl::enabled (uint8_t instance)
Definition at line 107 of file AP_WheelRateControl.cpp.
Referenced by get_rate_controlled_throttle().
get_pid()
AC_PID & AP_WheelRateControl::get_pid (uint8_t instance)
Definition at line 181 of file AP_WheelRateControl.cpp.
get_rate_controlled_throttle()
float AP_WheelRateControl::get_rate_controlled_throttle (uint8_t instance, float desired_rate_pct, float dt)
Definition at line 119 of file AP_WheelRateControl.cpp.
get_rate_max_rads()
float AP_WheelRateControl::get_rate_max_rads () const inline
Definition at line 49 of file AP_WheelRateControl.h.
Referenced by get_rate_controlled_throttle().
Member Data Documentation
_enabled
AP_Int8 AP_WheelRateControl::_enabled private
Definition at line 59 of file AP_WheelRateControl.h.
Referenced by enabled().
_last_update_ms
uint32_t AP_WheelRateControl::_last_update_ms private
Definition at line 72 of file AP_WheelRateControl.h.
Referenced by get_rate_controlled_throttle().
_limit
struct AP_WheelRateControl::AP_MotorsUGV_limit AP_WheelRateControl::_limit[2] private
Referenced by get_rate_controlled_throttle().
_rate_max
AP_Float AP_WheelRateControl::_rate_max private
Definition at line 60 of file AP_WheelRateControl.h.
Referenced by get_rate_max_rads().
_rate_pid0
AC_PID AP_WheelRateControl::_rate_pid0 = AC_PID(AP_WHEEL_RATE_CONTROL_P, AP_WHEEL_RATE_CONTROL_I, AP_WHEEL_RATE_CONTROL_D, AP_WHEEL_RATE_CONTROL_IMAX, AP_WHEEL_RATE_CONTROL_FILT, AP_WHEEL_RATE_CONTROL_DT, AP_WHEEL_RATE_CONTROL_FF) private
Definition at line 61 of file AP_WheelRateControl.h.
Referenced by get_pid(), and get_rate_controlled_throttle().
_rate_pid1
AC_PID AP_WheelRateControl::_rate_pid1 = AC_PID(AP_WHEEL_RATE_CONTROL_P, AP_WHEEL_RATE_CONTROL_I, AP_WHEEL_RATE_CONTROL_D, AP_WHEEL_RATE_CONTROL_IMAX, AP_WHEEL_RATE_CONTROL_FILT, AP_WHEEL_RATE_CONTROL_DT, AP_WHEEL_RATE_CONTROL_FF) private
Definition at line 62 of file AP_WheelRateControl.h.
Referenced by get_pid(), and get_rate_controlled_throttle().
_wheel_encoder
const AP_WheelEncoder& AP_WheelRateControl::_wheel_encoder private
Definition at line 71 of file AP_WheelRateControl.h.
Referenced by enabled(), and get_rate_controlled_throttle().
var_info
const AP_Param::GroupInfo AP_WheelRateControl::var_info static
Definition at line 54 of file AP_WheelRateControl.h.
Referenced by AP_WheelRateControl().
The documentation for this class was generated from the following files:
libraries/AP_WheelEncoder/AP_WheelRateControl.h
libraries/AP_WheelEncoder/AP_WheelRateControl.cpp