APM:Libraries: Linux::Perf_Lttng Class Reference
Linux::Perf_Lttng Class Reference
#include <Perf_Lttng.h>
Public Member Functions
void begin (const char *name)
void end (const char *name)
void count (const char *name, uint64_t val)
Detailed Description
Definition at line 23 of file Perf_Lttng.h.
Member Function Documentation
begin()
void Perf_Lttng::begin (const char * name)
Definition at line 49 of file Perf_Lttng.cpp.
Referenced by Linux::Perf::begin().
count()
void Perf_Lttng::count (const char * name, uint64_t val)
Definition at line 51 of file Perf_Lttng.cpp.
Referenced by Linux::Perf::count().
end()
void Perf_Lttng::end (const char * name)
Definition at line 50 of file Perf_Lttng.cpp.
Referenced by Linux::Perf::end().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Perf_Lttng.h
libraries/AP_HAL_Linux/Perf_Lttng.cpp