APM:Libraries: AP_AHRS Class Reference
AP_AHRS Class Reference abstract
#include <AP_AHRS.h>
Classes
struct ahrs_flags
Public Member Functions
AP_AHRS ()
virtual ~AP_AHRS ()
virtual void init ()
void set_fly_forward (bool b)
bool get_fly_forward (void) const
void set_likely_flying (bool b)
bool get_likely_flying (void) const
uint32_t get_time_flying_ms (void) const
AHRS_VehicleClass get_vehicle_class (void) const
void set_vehicle_class (AHRS_VehicleClass vclass)
void set_wind_estimation (bool b)
void set_compass (Compass *compass)
const Compass * get_compass () const
void set_optflow (const OpticalFlow *optflow)
const OpticalFlow * get_optflow () const
void update_orientation ()
void set_airspeed (AP_Airspeed *airspeed)
const AP_Airspeed * get_airspeed (void) const
virtual uint8_t get_primary_accel_index (void) const
virtual uint8_t get_primary_gyro_index (void) const
virtual const Vector3f & get_accel_ef (uint8_t i) const
virtual const Vector3f & get_accel_ef (void) const
virtual const Vector3f & get_accel_ef_blended (void) const
float get_yaw_rate_earth (void) const
virtual void update (bool skip_ins_update=false)=0
virtual const char * prearm_failure_reason (void) const
virtual bool attitudes_consistent (char *failure_msg, const uint8_t failure_msg_len) const
virtual bool have_ekf_logging (void) const
virtual void check_lane_switch (void)
virtual const Vector3f & get_gyro (void) const =0
Vector3f get_gyro_latest (void) const
virtual const Vector3f & get_gyro_drift (void) const =0
virtual void reset_gyro_drift (void)=0
virtual void reset (bool recover_eulers=false)=0
virtual void reset_attitude (const float &roll, const float &pitch, const float &yaw)=0
virtual float get_error_rp (void) const =0
virtual float get_error_yaw (void) const =0
virtual const Matrix3f & get_rotation_body_to_ned (void) const =0
void get_quat_body_to_ned (Quaternion &quat) const
const Matrix3f & get_rotation_autopilot_body_to_vehicle_body (void) const
const Matrix3f & get_rotation_vehicle_body_to_autopilot_body (void) const
virtual const Matrix3f & get_DCM_rotation_body_to_ned (void) const =0
virtual bool get_position (struct Location &loc) const =0
virtual bool get_hagl (float &height) const
virtual Vector3f wind_estimate (void) const =0
virtual bool airspeed_estimate (float *airspeed_ret) const WARN_IF_UNUSED
bool airspeed_estimate_true (float *airspeed_ret) const WARN_IF_UNUSED
float get_EAS2TAS (void) const
bool airspeed_sensor_enabled (void) const
uint8_t get_max_wind () const
virtual Vector2f groundspeed_vector (void)
virtual bool get_velocity_NED (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_expected_mag_field_NED (Vector3f &ret) const WARN_IF_UNUSED
virtual bool get_mag_field_correction (Vector3f &ret) const WARN_IF_UNUSED
virtual bool get_relative_position_NED_home (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_relative_position_NED_origin (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_relative_position_NE_home (Vector2f &vecNE) const WARN_IF_UNUSED
virtual bool get_relative_position_NE_origin (Vector2f &vecNE) const WARN_IF_UNUSED
virtual void get_relative_position_D_home (float &posD) const =0
virtual bool get_relative_position_D_origin (float &posD) const WARN_IF_UNUSED
float groundspeed (void)
virtual bool use_compass (void)
bool yaw_initialised (void) const
void set_correct_centrifugal (bool setting)
bool get_correct_centrifugal (void) const
const Vector3f & get_trim () const
void set_trim (const Vector3f &new_trim)
void add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom=true)
float cos_roll () const
float cos_pitch () const
float cos_yaw () const
float sin_roll () const
float sin_pitch () const
float sin_yaw () const
virtual bool get_secondary_attitude (Vector3f &eulers) const WARN_IF_UNUSED
virtual bool get_secondary_quaternion (Quaternion &quat) const WARN_IF_UNUSED
virtual bool get_secondary_position (struct Location &loc) const WARN_IF_UNUSED
const struct Location & get_home (void) const
void lock_home ()
bool home_is_locked () const
bool home_is_set (void) const
virtual bool set_home (const Location &loc) WARN_IF_UNUSED=0
virtual bool set_origin (const Location &loc) WARN_IF_UNUSED
virtual bool get_origin (Location &ret) const WARN_IF_UNUSED
void Log_Write_Home_And_Origin ()
virtual bool have_inertial_nav (void) const
uint8_t get_active_accel_instance (void) const
virtual bool healthy (void) const =0
virtual bool prearm_healthy (void) const
virtual bool initialised (void) const
virtual uint32_t getLastYawResetAngle (float &yawAng) const
virtual uint32_t getLastPosNorthEastReset (Vector2f &pos) const WARN_IF_UNUSED
virtual uint32_t getLastVelNorthEastReset (Vector2f &vel) const WARN_IF_UNUSED
virtual uint32_t getLastPosDownReset (float &posDelta) const WARN_IF_UNUSED
virtual bool resetHeightDatum (void) WARN_IF_UNUSED
virtual bool get_variances (float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar, Vector2f &offset) const
int8_t get_ekf_type (void) const
virtual void getCorrectedDeltaVelocityNED (Vector3f &ret, float &dt) const
AP_AHRS_View * create_view (enum Rotation rotation, float pitch_trim_deg=0)
float getAOA (void)
float getSSA (void)
Vector2f rotate_earth_to_body2D (const Vector2f &ef_vector) const
Vector2f rotate_body_to_earth2D (const Vector2f &bf) const
virtual void update_AOA_SSA (void)
virtual bool get_hgt_ctrl_limit (float &limit) const WARN_IF_UNUSED
virtual void writeExtNavData (const Vector3f &sensOffset, const Vector3f &pos, const Quaternion &quat, float posErr, float angErr, uint32_t timeStamp_ms, uint32_t resetTime_ms)
HAL_Semaphore & get_semaphore (void)
Static Public Member Functions
static AP_AHRS * get_singleton ()
Public Attributes
float roll
float pitch
float yaw
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void update_nmea_out ()
void calc_trig (const Matrix3f &rot, float &cr, float &cp, float &cy, float &sr, float &sp, float &sy) const
void update_trig (void)
void update_cd_values (void)
Protected Attributes
HAL_Semaphore_Recursive _rsem
AHRS_VehicleClass _vehicle_class
AP_Float _kp_yaw
AP_Float _kp
AP_Float gps_gain
AP_Float beta
AP_Int8 _gps_use
AP_Int8 _wind_max
AP_Int8 _board_orientation
AP_Int8 _gps_minsats
AP_Int8 _gps_delay
AP_Int8 _ekf_type
AP_Float _custom_roll
AP_Float _custom_pitch
AP_Float _custom_yaw
Matrix3f _custom_rotation
struct AP_AHRS::ahrs_flags _flags
uint32_t _last_flying_ms
Compass * _compass
const OpticalFlow * _optflow
AP_Airspeed * _airspeed
uint32_t _compass_last_update
AP_Vector3f _trim
Vector3f _last_trim
Matrix3f _rotation_autopilot_body_to_vehicle_body
Matrix3f _rotation_vehicle_body_to_autopilot_body
float _gyro_drift_limit
Vector3f _accel_ef [INS_MAX_INSTANCES]
Vector3f _accel_ef_blended
Vector2f _lp
Vector2f _hp
Vector2f _lastGndVelADS
struct Location _home
bool _home_is_set:1
bool _home_locked:1
float _cos_roll
float _cos_pitch
float _cos_yaw
float _sin_roll
float _sin_pitch
float _sin_yaw
uint8_t _active_accel_instance
AP_AHRS_View * _view
float _AOA
float _SSA
uint32_t _last_AOA_update_ms
Private Attributes
AP_NMEA_Output * _nmea_out
Static Private Attributes
static AP_AHRS * _singleton
Friends
class AP_AHRS_View
Detailed Description
Definition at line 50 of file AP_AHRS.h.
Constructor & Destructor Documentation
AP_AHRS()
AP_AHRS::AP_AHRS () inline
Definition at line 56 of file AP_AHRS.h.
~AP_AHRS()
virtual AP_AHRS::~AP_AHRS () inline virtual
Definition at line 80 of file AP_AHRS.h.
Member Function Documentation
add_trim()
void AP_AHRS::add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom = true)
Definition at line 212 of file AP_AHRS.cpp.
airspeed_estimate()
bool AP_AHRS::airspeed_estimate (float * airspeed_ret) const virtual
Reimplemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Definition at line 183 of file AP_AHRS.cpp.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_TECS::_update_speed(), AP_AHRS_View::airspeed_estimate(), airspeed_estimate_true(), AP_PitchController::get_rate_out(), AP_YawController::get_servo_out(), AP_Landing_Deepstall::override_servos(), and Variometer::update().
airspeed_estimate_true()
bool AP_AHRS::airspeed_estimate_true (float * airspeed_ret) const inline
Definition at line 286 of file AP_AHRS.h.
Referenced by AP_AHRS_View::airspeed_estimate_true(), and groundspeed_vector().
airspeed_sensor_enabled()
bool AP_AHRS::airspeed_sensor_enabled (void) const inline
Definition at line 299 of file AP_AHRS.h.
Referenced by AP_TECS::_update_pitch(), AP_TECS::_update_speed(), AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), NavEKF3_core::setup_core(), AP_TECS::update_pitch_throttle(), NavEKF2_core::useAirspeed(), and NavEKF3_core::useAirspeed().
attitudes_consistent()
virtual bool AP_AHRS::attitudes_consistent (char * failure_msg, const uint8_t failure_msg_len) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 209 of file AP_AHRS.h.
calc_trig()
void AP_AHRS::calc_trig (const Matrix3f & rot, float & cr, float & cp, float & cy, float & sr, float & sp, float & sy) const protected
Definition at line 317 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::update(), and update_trig().
check_lane_switch()
virtual void AP_AHRS::check_lane_switch (void) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 217 of file AP_AHRS.h.
cos_pitch()
float AP_AHRS::cos_pitch () const inline
Definition at line 404 of file AP_AHRS.h.
Referenced by AP_Mount_Servo::stabilize().
cos_roll()
float AP_AHRS::cos_roll () const inline
Definition at line 401 of file AP_AHRS.h.
Referenced by AP_Mount_Servo::stabilize().
cos_yaw()
float AP_AHRS::cos_yaw () const inline
Definition at line 407 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_polygon(), and AR_AttitudeControl::get_forward_speed().
create_view()
AP_AHRS_View * AP_AHRS::create_view (enum Rotation rotation, float pitch_trim_deg = 0)
Definition at line 391 of file AP_AHRS.cpp.
get_accel_ef() [1/2]
virtual const Vector3f& AP_AHRS::get_accel_ef (uint8_t i) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 183 of file AP_AHRS.h.
Referenced by AP_TECS::update_50hz().
get_accel_ef() [2/2]
virtual const Vector3f& AP_AHRS::get_accel_ef (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 186 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::get_accel_ef().
get_accel_ef_blended()
virtual const Vector3f& AP_AHRS::get_accel_ef_blended (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 191 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::get_accel_ef_blended(), and AP_AHRS_View::get_accel_ef_blended().
get_active_accel_instance()
uint8_t AP_AHRS::get_active_accel_instance (void) const inline
Definition at line 480 of file AP_AHRS.h.
get_airspeed()
const AP_Airspeed* AP_AHRS::get_airspeed (void) const inline
Definition at line 168 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::calc_velandyaw(), NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), NavEKF2_core::readAirSpdData(), and NavEKF3_core::readAirSpdData().
get_compass()
const Compass* AP_AHRS::get_compass () const inline
Definition at line 148 of file AP_AHRS.h.
Referenced by NavEKF3_core::alignMagStateDeclination(), SoloGimbalEKF::calcMagHeadingInnov(), NavEKF3_core::calcQuatAndFieldStates(), NavEKF3_core::FuseDeclination(), NavEKF3_core::fuseEulerYaw(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), NavEKF2_core::InitialiseVariablesMag(), NavEKF3_core::InitialiseVariablesMag(), NavEKF2_core::MagDeclination(), SoloGimbalEKF::readMagData(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::use_compass(), and NavEKF3_core::use_compass().
get_correct_centrifugal()
bool AP_AHRS::get_correct_centrifugal (void) const inline
Definition at line 385 of file AP_AHRS.h.
get_DCM_rotation_body_to_ned()
virtual const Matrix3f& AP_AHRS::get_DCM_rotation_body_to_ned (void) const pure virtual
Implemented in AP_AHRS_DCM.
Referenced by CompassCalibrator::AttitudeSample::set_from_ahrs().
get_EAS2TAS()
float AP_AHRS::get_EAS2TAS (void) const
Definition at line 508 of file AP_AHRS.cpp.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_PitchController::_get_rate_out(), AP_RollController::_get_rate_out(), AP_TECS::_update_speed(), AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), airspeed_estimate_true(), NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), AP_AHRS_DCM::estimate_wind(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), AP_AHRS_View::get_EAS2TAS(), AP_TECS::get_target_airspeed(), AP_L1_Control::loiter_radius(), NavEKF2_core::readAirSpdData(), NavEKF3_core::readAirSpdData(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), and AP_L1_Control::turn_distance().
get_ekf_type()
int8_t AP_AHRS::get_ekf_type (void) const inline
Definition at line 536 of file AP_AHRS.h.
Referenced by GCS::update_sensor_status_flags().
get_error_rp()
virtual float AP_AHRS::get_error_rp (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_AHRS_View::get_error_rp().
get_error_yaw()
virtual float AP_AHRS::get_error_yaw (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_AHRS_View::get_error_yaw().
get_expected_mag_field_NED()
virtual bool AP_AHRS::get_expected_mag_field_NED (Vector3f & ret) const inline virtual
Definition at line 319 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_expected_mag_field_NED().
get_fly_forward()
bool AP_AHRS::get_fly_forward (void) const inline
Definition at line 95 of file AP_AHRS.h.
Referenced by NavEKF2_core::assume_zero_sideslip(), and NavEKF3_core::assume_zero_sideslip().
get_gyro()
virtual const Vector3f& AP_AHRS::get_gyro (void) const pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by AP_PitchController::_get_rate_out(), AP_RollController::_get_rate_out(), AP_AHRS_get_gyro(), AP_YawController::get_servo_out(), get_yaw_rate_earth(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), AP_OpticalFlow_MAV::update(), AP_AHRS_View::update(), and AP_Landing_Deepstall::update_steering().
get_gyro_drift()
virtual const Vector3f& AP_AHRS::get_gyro_drift (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by get_gyro_latest().
get_gyro_latest()
Vector3f AP_AHRS::get_gyro_latest (void) const
Definition at line 176 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::get_gyro_latest().
get_hagl()
virtual bool AP_AHRS::get_hagl (float & height) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 275 of file AP_AHRS.h.
Referenced by AP_AHRS_get_hagl().
get_hgt_ctrl_limit()
virtual bool AP_AHRS::get_hgt_ctrl_limit (float & limit) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 570 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_z().
get_home()
const struct Location& AP_AHRS::get_home (void) const inline
Definition at line 440 of file AP_AHRS.h.
Referenced by AP_AHRS_get_home(), AP_Rally::calc_best_rally_or_home_location(), AP_Frsky_Telem::calc_home(), AP_OABendyRuler::calc_margin_from_circular_fence(), AP_Frsky_Telem::calc_nav_alt(), AC_Fence::check_destination_within_fence(), AP_OSD_Screen::draw_home(), Location::get_alt_cm(), AP_AHRS_NavEKF::get_hagl(), AP_AHRS_NavEKF::get_relative_position_D_origin(), AP_AHRS_NavEKF::get_relative_position_NE_origin(), AP_AHRS_NavEKF::get_relative_position_NED_origin(), AP_Follow::get_target_dist_and_vel_ned(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Rally::rally_location_to_location(), AP_Mission::read_cmd_from_storage(), AP_Camera::send_feedback(), GCS_MAVLINK::send_home_position(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), NavEKF3_core::setOriginLLH(), NavEKF2_core::setOriginLLH(), AP_OSD::stats(), AP_Logger::Write_CameraInfo(), and AP_Mission::write_home_to_storage().
get_likely_flying()
bool AP_AHRS::get_likely_flying (void) const inline
Definition at line 116 of file AP_AHRS.h.
get_mag_field_correction()
virtual bool AP_AHRS::get_mag_field_correction (Vector3f & ret) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 324 of file AP_AHRS.h.
get_max_wind()
uint8_t AP_AHRS::get_max_wind () const inline
Definition at line 304 of file AP_AHRS.h.
Referenced by AP_Airspeed::check_sensor_ahrs_wind_max_failures().
get_optflow()
const OpticalFlow* AP_AHRS::get_optflow () const inline
Definition at line 156 of file AP_AHRS.h.
get_origin()
virtual bool AP_AHRS::get_origin (Location & ret) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 469 of file AP_AHRS.h.
Referenced by Log_Write_Home_And_Origin().
get_position()
virtual bool AP_AHRS::get_position (struct Location & loc) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_AHRS_get_position(), AP_Frsky_Telem::calc_home(), AP_Frsky_Telem::calc_nav_alt(), AP_Avoidance::check_for_threats(), AP_AHRS_View::get_position(), AP_Avoidance::get_vector_perpendicular(), AP_Avoidance::handle_avoidance_local(), SoaringController::init_thermalling(), AP_DEVO_Telem::send_frames(), AP_Landing_Deepstall::terminate(), AR_WPNav::update(), AP_L1_Control::update_loiter(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), AP_L1_Control::update_waypoint(), and AP_Landing_Deepstall::verify_land().
get_primary_accel_index()
virtual uint8_t AP_AHRS::get_primary_accel_index (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 173 of file AP_AHRS.h.
Referenced by AC_PrecLand::run_output_prediction().
get_primary_gyro_index()
virtual uint8_t AP_AHRS::get_primary_gyro_index (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 178 of file AP_AHRS.h.
Referenced by get_gyro_latest().
get_quat_body_to_ned()
void AP_AHRS::get_quat_body_to_ned (Quaternion & quat) const inline
Definition at line 260 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::attitudes_consistent().
get_relative_position_D_home()
virtual void AP_AHRS::get_relative_position_D_home (float & posD) const pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by AC_Avoid::adjust_velocity_z(), AC_Fence::check_fence_alt_max(), SoaringController::get_altitude_wrt_home(), AP_AHRS_View::get_relative_position_D_home(), GCS_MAVLINK::global_position_int_relative_alt(), AP_Landing_Deepstall::request_go_around(), AP_DEVO_Telem::send_frames(), AP_OSD::stats(), Variometer::update(), AP_TECS::update_50hz(), and AP_Landing_Deepstall::verify_land().
get_relative_position_D_origin()
virtual bool AP_AHRS::get_relative_position_D_origin (float & posD) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 359 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_z(), and AP_AHRS_View::get_relative_position_D_origin().
get_relative_position_NE_home()
virtual bool AP_AHRS::get_relative_position_NE_home (Vector2f & vecNE) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 343 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_circle_fence(), and AP_AHRS_View::get_relative_position_NE_home().
get_relative_position_NE_origin()
virtual bool AP_AHRS::get_relative_position_NE_origin (Vector2f & vecNE) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 349 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_polygon(), and AP_AHRS_View::get_relative_position_NE_origin().
get_relative_position_NED_home()
virtual bool AP_AHRS::get_relative_position_NED_home (Vector3f & vec) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 331 of file AP_AHRS.h.
Referenced by AP_AHRS_get_relative_position_NED_home(), and AP_AHRS_View::get_relative_position_NED_home().
get_relative_position_NED_origin()
virtual bool AP_AHRS::get_relative_position_NED_origin (Vector3f & vec) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 338 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_relative_position_NED_origin(), AP_SmartRTL::set_home(), AP_ICEngine::update(), and AP_SmartRTL::update().
get_rotation_autopilot_body_to_vehicle_body()
const Matrix3f& AP_AHRS::get_rotation_autopilot_body_to_vehicle_body (void) const inline
Definition at line 264 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_SITL().
get_rotation_body_to_ned()
virtual const Matrix3f& AP_AHRS::get_rotation_body_to_ned (void) const pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), get_quat_body_to_ned(), get_yaw_rate_earth(), AC_PrecLand::run_output_prediction(), AP_IRLock_SITL::update(), AC_PrecLand_SITL::update(), AP_AHRS_View::update(), AP_TECS::update_50hz(), update_AOA_SSA(), and update_trig().
get_rotation_vehicle_body_to_autopilot_body()
const Matrix3f& AP_AHRS::get_rotation_vehicle_body_to_autopilot_body (void) const inline
Definition at line 265 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::euler_angles(), NavEKF3_core::getRotationBodyToNED(), NavEKF2_core::getRotationBodyToNED(), and AP_AHRS_NavEKF::update_SITL().
get_secondary_attitude()
virtual bool AP_AHRS::get_secondary_attitude (Vector3f & eulers) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 424 of file AP_AHRS.h.
get_secondary_position()
virtual bool AP_AHRS::get_secondary_position (struct Location & loc) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 434 of file AP_AHRS.h.
get_secondary_quaternion()
virtual bool AP_AHRS::get_secondary_quaternion (Quaternion & quat) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 429 of file AP_AHRS.h.
get_semaphore()
HAL_Semaphore& AP_AHRS::get_semaphore (void) inline
Definition at line 576 of file AP_AHRS.h.
Referenced by AP_AHRS_get_gyro(), AP_AHRS_get_hagl(), AP_AHRS_get_home(), AP_AHRS_get_position(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_groundspeed_vector(), AP_AHRS_home_is_set(), AP_AHRS_prearm_healthy(), AP_AHRS_wind_estimate(), AP_OSD_Screen::draw_altitude(), AP_OSD_Screen::draw_aspeed(), AP_OSD_Screen::draw_climbeff(), AP_OSD_Screen::draw_eff(), AP_OSD_Screen::draw_gspeed(), AP_OSD_Screen::draw_home(), AP_OSD_Screen::draw_horizon(), AP_OSD_Screen::draw_vspeed(), and AP_OSD_Screen::draw_wind().
get_singleton()
static AP_AHRS* AP_AHRS::get_singleton () inline static
Definition at line 83 of file AP_AHRS.h.
Referenced by AP::ahrs(), AP::ahrs_navekf(), AP_AHRS_get_gyro(), AP_AHRS_get_hagl(), AP_AHRS_get_home(), AP_AHRS_get_position(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_groundspeed_vector(), AP_AHRS_home_is_set(), AP_AHRS_prearm_healthy(), and AP_AHRS_wind_estimate().
get_time_flying_ms()
uint32_t AP_AHRS::get_time_flying_ms (void) const inline
Definition at line 124 of file AP_AHRS.h.
Referenced by NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), and CompassLearn::update().
get_trim()
const Vector3f& AP_AHRS::get_trim () const inline
Definition at line 390 of file AP_AHRS.h.
Referenced by NavEKF2_core::getEulerAngles(), and NavEKF3_core::getEulerAngles().
get_variances()
virtual bool AP_AHRS::get_variances (float & velVar, float & posVar, float & hgtVar, Vector3f & magVar, float & tasVar, Vector2f & offset) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 531 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::check_ekf_status().
get_vehicle_class()
AHRS_VehicleClass AP_AHRS::get_vehicle_class (void) const inline
Definition at line 131 of file AP_AHRS.h.
Referenced by NavEKF2_core::assume_zero_sideslip(), and NavEKF3_core::assume_zero_sideslip().
get_velocity_NED()
virtual bool AP_AHRS::get_velocity_NED (Vector3f & vec) const inline virtual
Reimplemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Definition at line 314 of file AP_AHRS.h.
Referenced by AP_AHRS_get_velocity_NED(), AP_Frsky_Telem::calc_velandyaw(), AP_Avoidance::check_for_threats(), AR_AttitudeControl::get_forward_speed(), AP_AHRS_View::get_velocity_NED(), AP_TECS::update_50hz(), and update_AOA_SSA().
get_yaw_rate_earth()
float AP_AHRS::get_yaw_rate_earth (void) const inline
Definition at line 196 of file AP_AHRS.h.
Referenced by AR_AttitudeControl::get_lat_accel(), AP_SteerController::get_steering_out_rate(), and AR_AttitudeControl::get_steering_out_rate().
getAOA()
float AP_AHRS::getAOA (void)
Definition at line 461 of file AP_AHRS.cpp.
Referenced by AP_Logger::Write_AOA_SSA().
getCorrectedDeltaVelocityNED()
virtual void AP_AHRS::getCorrectedDeltaVelocityNED (Vector3f & ret, float & dt) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 541 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED().
getLastPosDownReset()
virtual uint32_t AP_AHRS::getLastPosDownReset (float & posDelta) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 514 of file AP_AHRS.h.
Referenced by AP_AHRS_View::getLastPosDownReset().
getLastPosNorthEastReset()
virtual uint32_t AP_AHRS::getLastPosNorthEastReset (Vector2f & pos) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 502 of file AP_AHRS.h.
Referenced by AP_AHRS_View::getLastPosNorthEastReset().
getLastVelNorthEastReset()
virtual uint32_t AP_AHRS::getLastVelNorthEastReset (Vector2f & vel) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 508 of file AP_AHRS.h.
getLastYawResetAngle()
virtual uint32_t AP_AHRS::getLastYawResetAngle (float & yawAng) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 496 of file AP_AHRS.h.
getSSA()
float AP_AHRS::getSSA (void)
Definition at line 468 of file AP_AHRS.cpp.
Referenced by AP_Logger::Write_AOA_SSA().
groundspeed()
float AP_AHRS::groundspeed (void) inline
Definition at line 364 of file AP_AHRS.h.
Referenced by AP_Frsky_Telem::calc_velandyaw(), AP_SteerController::get_steering_out_lat_accel(), AP_SteerController::get_steering_out_rate(), AP_AHRS_View::groundspeed(), GCS_MAVLINK::send_vfr_hud(), and AP_Landing::type_slope_setup_landing_glide_slope().
groundspeed_vector()
Vector2f AP_AHRS::groundspeed_vector (void) virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 248 of file AP_AHRS.cpp.
Referenced by AP_AHRS_groundspeed_vector(), AR_WPNav::get_stopping_location(), groundspeed(), AP_AHRS_View::groundspeed_vector(), AP_AHRS_NavEKF::groundspeed_vector(), AP_OAPathPlanner::mission_avoidance(), AP_L1_Control::update_heading_hold(), AP_L1_Control::update_loiter(), AP_L1_Control::update_waypoint(), AP_Landing_Deepstall::verify_breakout(), and AP_Landing_Deepstall::verify_land().
have_ekf_logging()
virtual bool AP_AHRS::have_ekf_logging (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 212 of file AP_AHRS.h.
have_inertial_nav()
virtual bool AP_AHRS::have_inertial_nav (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 475 of file AP_AHRS.h.
healthy()
virtual bool AP_AHRS::healthy (void) const pure virtual
Implemented in AP_AHRS_NavEKF, and AP_AHRS_DCM.
Referenced by prearm_healthy(), and AP_Landing_Deepstall::update_steering().
home_is_locked()
bool AP_AHRS::home_is_locked () const inline
Definition at line 449 of file AP_AHRS.h.
home_is_set()
bool AP_AHRS::home_is_set (void) const inline
Definition at line 454 of file AP_AHRS.h.
Referenced by AP_AHRS_home_is_set(), AP_OSD_Screen::draw_home(), Location::get_alt_cm(), Log_Write_Home_And_Origin(), and AP_OSD::stats().
init()
void AP_AHRS::init (void) virtual
Definition at line 166 of file AP_AHRS.cpp.
Referenced by setup().
initialised()
virtual bool AP_AHRS::initialised (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 490 of file AP_AHRS.h.
lock_home()
void AP_AHRS::lock_home () inline
Definition at line 446 of file AP_AHRS.h.
Log_Write_Home_And_Origin()
void AP_AHRS::Log_Write_Home_And_Origin ()
Definition at line 489 of file AP_AHRS.cpp.
Referenced by GCS_MAVLINK::set_ekf_origin(), and AP_AHRS_DCM::set_home().
prearm_failure_reason()
virtual const char* AP_AHRS::prearm_failure_reason (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 204 of file AP_AHRS.h.
prearm_healthy()
virtual bool AP_AHRS::prearm_healthy (void) const inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 487 of file AP_AHRS.h.
Referenced by AP_AHRS_prearm_healthy().
reset()
virtual void AP_AHRS::reset (bool recover_eulers = false) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_InertialSensor::simple_accel_cal().
reset_attitude()
virtual void AP_AHRS::reset_attitude (const float & roll, const float & pitch, const float & yaw) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
reset_gyro_drift()
virtual void AP_AHRS::reset_gyro_drift (void) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by GCS_MAVLINK::calibrate_gyros().
resetHeightDatum()
virtual bool AP_AHRS::resetHeightDatum (void) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 523 of file AP_AHRS.h.
rotate_body_to_earth2D()
Vector2f AP_AHRS::rotate_body_to_earth2D (const Vector2f & bf) const
Definition at line 482 of file AP_AHRS.cpp.
rotate_earth_to_body2D()
Vector2f AP_AHRS::rotate_earth_to_body2D (const Vector2f & ef_vector) const
Definition at line 475 of file AP_AHRS.cpp.
set_airspeed()
void AP_AHRS::set_airspeed (AP_Airspeed * airspeed) inline
Definition at line 164 of file AP_AHRS.h.
set_compass()
void AP_AHRS::set_compass (Compass * compass) inline
Definition at line 143 of file AP_AHRS.h.
Referenced by Compass::init(), and setup().
set_correct_centrifugal()
void AP_AHRS::set_correct_centrifugal (bool setting) inline
Definition at line 380 of file AP_AHRS.h.
set_fly_forward()
void AP_AHRS::set_fly_forward (bool b) inline
Definition at line 91 of file AP_AHRS.h.
set_home()
virtual bool AP_AHRS::set_home (const Location & loc) pure virtual
Implemented in AP_AHRS_DCM.
set_likely_flying()
void AP_AHRS::set_likely_flying (bool b) inline
Definition at line 104 of file AP_AHRS.h.
set_optflow()
void AP_AHRS::set_optflow (const OpticalFlow * optflow) inline
Definition at line 152 of file AP_AHRS.h.
set_origin()
virtual bool AP_AHRS::set_origin (const Location & loc) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 466 of file AP_AHRS.h.
set_trim()
void AP_AHRS::set_trim (const Vector3f & new_trim)
Definition at line 203 of file AP_AHRS.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration(), and AP_InertialSensor::simple_accel_cal().
set_vehicle_class()
void AP_AHRS::set_vehicle_class (AHRS_VehicleClass vclass) inline
Definition at line 135 of file AP_AHRS.h.
set_wind_estimation()
void AP_AHRS::set_wind_estimation (bool b) inline
Definition at line 139 of file AP_AHRS.h.
sin_pitch()
float AP_AHRS::sin_pitch () const inline
Definition at line 413 of file AP_AHRS.h.
Referenced by AP_Mount_Servo::stabilize().
sin_roll()
float AP_AHRS::sin_roll () const inline
Definition at line 410 of file AP_AHRS.h.
Referenced by AP_Mount_Servo::stabilize().
sin_yaw()
float AP_AHRS::sin_yaw () const inline
Definition at line 416 of file AP_AHRS.h.
Referenced by AC_Avoid::adjust_velocity_polygon(), and AR_AttitudeControl::get_forward_speed().
update()
virtual void AP_AHRS::update (bool skip_ins_update = false) pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
update_AOA_SSA()
void AP_AHRS::update_AOA_SSA (void) virtual
Definition at line 414 of file AP_AHRS.cpp.
Referenced by getAOA(), getSSA(), and AP_AHRS_DCM::update().
update_cd_values()
void AP_AHRS::update_cd_values (void) protected
Definition at line 379 of file AP_AHRS.cpp.
Referenced by AP_AHRS_DCM::euler_angles(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
update_nmea_out()
void AP_AHRS::update_nmea_out () protected
Definition at line 512 of file AP_AHRS.cpp.
Referenced by AP_AHRS_NavEKF::update().
update_orientation()
void AP_AHRS::update_orientation ()
Definition at line 230 of file AP_AHRS.cpp.
Referenced by init(), and set_compass().
update_trig()
void AP_AHRS::update_trig (void) protected
Definition at line 363 of file AP_AHRS.cpp.
Referenced by AP_AHRS_DCM::update(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
use_compass()
virtual bool AP_AHRS::use_compass (void) inline virtual
Reimplemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Definition at line 369 of file AP_AHRS.h.
wind_estimate()
virtual Vector3f AP_AHRS::wind_estimate (void) const pure virtual
Implemented in AP_AHRS_DCM, and AP_AHRS_NavEKF.
Referenced by AP_AHRS_wind_estimate(), AP_Landing_Deepstall::build_approach_path(), groundspeed_vector(), AP_Landing::head_wind(), update_AOA_SSA(), SoaringController::update_thermalling(), AP_Landing_Deepstall::verify_land(), AP_Landing::wind_alignment(), and AP_AHRS_View::wind_estimate().
writeExtNavData()
virtual void AP_AHRS::writeExtNavData (const Vector3f & sensOffset, const Vector3f & pos, const Quaternion & quat, float posErr, float angErr, uint32_t timeStamp_ms, uint32_t resetTime_ms) inline virtual
Reimplemented in AP_AHRS_NavEKF.
Definition at line 573 of file AP_AHRS.h.
Referenced by GCS_MAVLINK::handle_att_pos_mocap(), and GCS_MAVLINK::handle_common_vision_position_estimate_data().
yaw_initialised()
bool AP_AHRS::yaw_initialised (void) const inline
Definition at line 374 of file AP_AHRS.h.
Friends And Related Function Documentation
AP_AHRS_View
friend class AP_AHRS_View friend
Definition at line 53 of file AP_AHRS.h.
Referenced by create_view().
Member Data Documentation
_accel_ef
Vector3f AP_AHRS::_accel_ef[INS_MAX_INSTANCES] protected
Definition at line 656 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::_yaw_gain(), AP_AHRS_DCM::drift_correction(), and get_accel_ef().
_accel_ef_blended
Vector3f AP_AHRS::_accel_ef_blended protected
Definition at line 657 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction(), and get_accel_ef_blended().
_active_accel_instance
uint8_t AP_AHRS::_active_accel_instance protected
Definition at line 675 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::_yaw_gain(), AP_AHRS_DCM::drift_correction(), and get_active_accel_instance().
_airspeed
AP_Airspeed* AP_AHRS::_airspeed protected
Definition at line 638 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), airspeed_sensor_enabled(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), get_airspeed(), and set_airspeed().
_AOA
float AP_AHRS::_AOA protected
Definition at line 681 of file AP_AHRS.h.
Referenced by getAOA(), and update_AOA_SSA().
_board_orientation
AP_Int8 AP_AHRS::_board_orientation protected
Definition at line 597 of file AP_AHRS.h.
Referenced by update_orientation().
_compass
Compass* AP_AHRS::_compass protected
Definition at line 632 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_NavEKF::attitudes_consistent(), AP_AHRS_DCM::drift_correction_yaw(), get_compass(), set_compass(), update_orientation(), AP_AHRS_DCM::use_compass(), use_compass(), and AP_AHRS_DCM::yaw_error_compass().
_compass_last_update
uint32_t AP_AHRS::_compass_last_update protected
Definition at line 641 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw().
_cos_pitch
float AP_AHRS::_cos_pitch protected
Definition at line 671 of file AP_AHRS.h.
Referenced by cos_pitch(), and update_trig().
_cos_roll
float AP_AHRS::_cos_roll protected
Definition at line 671 of file AP_AHRS.h.
Referenced by cos_roll(), and update_trig().
_cos_yaw
float AP_AHRS::_cos_yaw protected
Definition at line 671 of file AP_AHRS.h.
Referenced by cos_yaw(), groundspeed_vector(), rotate_body_to_earth2D(), rotate_earth_to_body2D(), and update_trig().
_custom_pitch
AP_Float AP_AHRS::_custom_pitch protected
Definition at line 602 of file AP_AHRS.h.
Referenced by update_orientation().
_custom_roll
AP_Float AP_AHRS::_custom_roll protected
Definition at line 601 of file AP_AHRS.h.
Referenced by update_orientation().
_custom_rotation
Matrix3f AP_AHRS::_custom_rotation protected
Definition at line 605 of file AP_AHRS.h.
Referenced by update_orientation().
_custom_yaw
AP_Float AP_AHRS::_custom_yaw protected
Definition at line 603 of file AP_AHRS.h.
Referenced by update_orientation().
_ekf_type
AP_Int8 AP_AHRS::_ekf_type protected
Definition at line 600 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::ekf_type(), get_ekf_type(), AP_AHRS_NavEKF::set_ekf_use(), and AP_AHRS_NavEKF::update().
_flags
struct AP_AHRS::ahrs_flags AP_AHRS::_flags protected
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::estimate_wind(), get_correct_centrifugal(), get_fly_forward(), get_likely_flying(), AP_AHRS_DCM::get_position(), get_time_flying_ms(), set_correct_centrifugal(), set_fly_forward(), set_likely_flying(), set_wind_estimation(), AP_AHRS_DCM::use_compass(), and yaw_initialised().
_gps_delay
AP_Int8 AP_AHRS::_gps_delay protected
Definition at line 599 of file AP_AHRS.h.
_gps_minsats
AP_Int8 AP_AHRS::_gps_minsats protected
Definition at line 598 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction().
_gps_use
AP_Int8 AP_AHRS::_gps_use protected
Definition at line 595 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::have_gps().
_gyro_drift_limit
float AP_AHRS::_gyro_drift_limit protected
Definition at line 653 of file AP_AHRS.h.
Referenced by AP_AHRS(), and AP_AHRS_DCM::drift_correction().
_home
struct Location AP_AHRS::_home protected
Definition at line 666 of file AP_AHRS.h.
Referenced by get_home(), AP_AHRS_DCM::get_position(), AP_AHRS_NavEKF::get_relative_position_D_home(), AP_AHRS_NavEKF::get_relative_position_NE_home(), AP_AHRS_NavEKF::get_relative_position_NED_home(), AP_AHRS_DCM::load_watchdog_home(), Log_Write_Home_And_Origin(), and AP_AHRS_DCM::set_home().
_home_is_set
bool AP_AHRS::_home_is_set protected
Definition at line 667 of file AP_AHRS.h.
Referenced by home_is_set(), AP_AHRS_DCM::load_watchdog_home(), and AP_AHRS_DCM::set_home().
_home_locked
bool AP_AHRS::_home_locked protected
Definition at line 668 of file AP_AHRS.h.
Referenced by home_is_locked(), AP_AHRS_DCM::load_watchdog_home(), and lock_home().
_hp
Vector2f AP_AHRS::_hp protected
Definition at line 662 of file AP_AHRS.h.
Referenced by groundspeed_vector().
_kp
AP_Float AP_AHRS::_kp protected
Definition at line 591 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction().
_kp_yaw
AP_Float AP_AHRS::_kp_yaw protected
Definition at line 590 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw().
_last_AOA_update_ms
uint32_t AP_AHRS::_last_AOA_update_ms protected
Definition at line 682 of file AP_AHRS.h.
Referenced by update_AOA_SSA().
_last_flying_ms
uint32_t AP_AHRS::_last_flying_ms protected
Definition at line 617 of file AP_AHRS.h.
Referenced by get_time_flying_ms(), and set_likely_flying().
_last_trim
Vector3f AP_AHRS::_last_trim protected
Definition at line 647 of file AP_AHRS.h.
Referenced by AP_AHRS(), and update_trig().
_lastGndVelADS
Vector2f AP_AHRS::_lastGndVelADS protected
Definition at line 663 of file AP_AHRS.h.
Referenced by groundspeed_vector().
_lp
Vector2f AP_AHRS::_lp protected
Definition at line 661 of file AP_AHRS.h.
Referenced by groundspeed_vector().
_nmea_out
AP_NMEA_Output* AP_AHRS::_nmea_out private
Definition at line 687 of file AP_AHRS.h.
Referenced by init(), and update_nmea_out().
_optflow
const OpticalFlow* AP_AHRS::_optflow protected
Definition at line 635 of file AP_AHRS.h.
Referenced by get_optflow(), and set_optflow().
_rotation_autopilot_body_to_vehicle_body
Matrix3f AP_AHRS::_rotation_autopilot_body_to_vehicle_body protected
Definition at line 648 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_rotation_autopilot_body_to_vehicle_body(), and update_trig().
_rotation_vehicle_body_to_autopilot_body
Matrix3f AP_AHRS::_rotation_vehicle_body_to_autopilot_body protected
Definition at line 649 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_rotation_vehicle_body_to_autopilot_body(), and update_trig().
_rsem
HAL_Semaphore_Recursive AP_AHRS::_rsem protected
Definition at line 584 of file AP_AHRS.h.
Referenced by get_semaphore(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), AP_AHRS_NavEKF::reset_gyro_drift(), AP_AHRS_NavEKF::resetHeightDatum(), AP_AHRS_NavEKF::update(), and AP_AHRS_DCM::update().
_sin_pitch
float AP_AHRS::_sin_pitch protected
Definition at line 672 of file AP_AHRS.h.
Referenced by sin_pitch(), and update_trig().
_sin_roll
float AP_AHRS::_sin_roll protected
Definition at line 672 of file AP_AHRS.h.
Referenced by sin_roll(), and update_trig().
_sin_yaw
float AP_AHRS::_sin_yaw protected
Definition at line 672 of file AP_AHRS.h.
Referenced by groundspeed_vector(), rotate_body_to_earth2D(), rotate_earth_to_body2D(), sin_yaw(), and update_trig().
_singleton
AP_AHRS * AP_AHRS::_singleton static private
Definition at line 685 of file AP_AHRS.h.
Referenced by AP_AHRS(), and get_singleton().
_SSA
float AP_AHRS::_SSA protected
Definition at line 681 of file AP_AHRS.h.
Referenced by getSSA(), and update_AOA_SSA().
_trim
AP_Vector3f AP_AHRS::_trim protected
Definition at line 644 of file AP_AHRS.h.
Referenced by add_trim(), AP_AHRS(), get_trim(), set_trim(), and update_trig().
_vehicle_class
AHRS_VehicleClass AP_AHRS::_vehicle_class protected
Definition at line 586 of file AP_AHRS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), get_vehicle_class(), AP_AHRS_NavEKF::healthy(), and set_vehicle_class().
_view
AP_AHRS_View* AP_AHRS::_view protected
Definition at line 678 of file AP_AHRS.h.
Referenced by create_view(), and AP_AHRS_NavEKF::update().
_wind_max
AP_Int8 AP_AHRS::_wind_max protected
Definition at line 596 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::airspeed_estimate(), airspeed_estimate(), and get_max_wind().
beta
AP_Float AP_AHRS::beta protected
Definition at line 594 of file AP_AHRS.h.
Referenced by groundspeed_vector().
gps_gain
AP_Float AP_AHRS::gps_gain protected
Definition at line 592 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::drift_correction().
pitch
float AP_AHRS::pitch
Definition at line 221 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_TECS::_initialise_states(), AP_AHRS_DCM::backup_attitude(), AP_OSD_Screen::draw_horizon(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::euler_angles(), AR_AttitudeControl::get_throttle_out_from_pitch(), loop(), AP_L1_Control::nav_roll_cd(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), GCS_MAVLINK::send_attitude(), AP_Mount_Servo::stabilize(), CompassLearn::update(), update_cd_values(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
pitch_sensor
int32_t AP_AHRS::pitch_sensor
Definition at line 226 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_PitchController::_get_rate_out(), AP_Frsky_Telem::calc_attiandrng(), AP_OSD_Screen::draw_pitch_angle(), AP_AHRS_DCM::drift_correction(), AP_Camera::send_feedback(), update_cd_values(), AP_Logger::Write_Attitude(), AP_Logger::Write_AttitudeView(), and AP_Logger::Write_CameraInfo().
roll
float AP_AHRS::roll
Definition at line 220 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_AHRS_DCM::backup_attitude(), AP_OSD_Screen::draw_horizon(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::euler_angles(), AR_AttitudeControl::get_sail_out_from_heel(), AP_YawController::get_servo_out(), loop(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), GCS_MAVLINK::send_attitude(), AP_Mount_Servo::stabilize(), CompassLearn::update(), Variometer::update(), update_cd_values(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_AHRS_NavEKF::update_SITL().
roll_sensor
int32_t AP_AHRS::roll_sensor
Definition at line 225 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_rate_out(), AP_Frsky_Telem::calc_attiandrng(), AP_OSD_Screen::draw_roll_angle(), AP_Camera::send_feedback(), update_cd_values(), AP_Logger::Write_Attitude(), AP_Logger::Write_AttitudeView(), and AP_Logger::Write_CameraInfo().
var_info
const AP_Param::GroupInfo AP_AHRS::var_info static
Definition at line 421 of file AP_AHRS.h.
Referenced by AP_AHRS().
yaw
float AP_AHRS::yaw
Definition at line 222 of file AP_AHRS.h.
Referenced by AP_AHRS_DCM::backup_attitude(), AP_Mount_Backend::calc_angle_to_location(), AP_AHRS_DCM::drift_correction_yaw(), AP_AHRS_DCM::euler_angles(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_L1_Control::get_yaw(), groundspeed_vector(), SoaringController::init_thermalling(), loop(), AP_WindVane::record_home_heading(), AP_AHRS_NavEKF::reset(), AP_AHRS_DCM::reset(), AP_AHRS_NavEKF::reset_attitude(), GCS_MAVLINK::send_attitude(), CompassLearn::update(), AP_WindVane_NMEA::update(), update_cd_values(), AP_AHRS_NavEKF::update_DCM(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), AP_L1_Control::update_level_flight(), AP_L1_Control::update_loiter(), AP_AHRS_NavEKF::update_SITL(), and AP_Landing_Deepstall::update_steering().
yaw_sensor
int32_t AP_AHRS::yaw_sensor
Definition at line 227 of file AP_AHRS.h.
Referenced by AP_Landing_Deepstall::build_approach_path(), AP_Frsky_Telem::calc_velandyaw(), AP_OSD_Screen::draw_compass(), AP_OSD_Screen::draw_gspeed(), AP_OSD_Screen::draw_heading(), AP_OSD_Screen::draw_home(), AP_OSD_Screen::draw_waypoint(), AP_OSD_Screen::draw_wind(), AR_AttitudeControl::get_forward_speed(), AP_L1_Control::get_yaw_sensor(), AP_Landing::head_wind(), AP_Frsky_Telem::send_D(), AP_Camera::send_feedback(), GCS_MAVLINK::send_global_position_int(), AP_Frsky_Telem::send_SPort(), GCS_MAVLINK::send_vfr_hud(), AP_OABendyRuler::update(), update_cd_values(), AR_WPNav::update_desired_speed(), AP_L1_Control::update_heading_hold(), AP_L1_Control::update_level_flight(), AP_Proximity_Backend::update_locations(), AP_AHRS_DCM::use_compass(), AP_Logger::Write_Attitude(), AP_Logger::Write_AttitudeView(), and AP_Logger::Write_CameraInfo().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS.cpp