APM:Libraries: AP_RTC Class Reference
AP_RTC Class Reference
#include <AP_RTC.h>
Public Types
enum source_type : uint8_t { SOURCE_GPS = 0, SOURCE_MAVLINK_SYSTEM_TIME = 1, SOURCE_HW = 2, SOURCE_NONE }
Public Member Functions
AP_RTC ()
bool get_utc_usec (uint64_t &usec) const
void set_utc_usec (uint64_t time_utc_usec, source_type type)
bool get_system_clock_utc (int32_t &hour, int32_t &min, int32_t &sec, int32_t &ms)
uint32_t get_time_utc (int32_t hour, int32_t min, int32_t sec, int32_t ms)
Static Public Member Functions
static AP_RTC * get_singleton ()
Public Attributes
AP_Int8 allowed_types
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
source_type rtc_source_type = SOURCE_NONE
int64_t rtc_shift
Static Private Attributes
static AP_RTC * _singleton
Detailed Description
Definition at line 7 of file AP_RTC.h.
Member Enumeration Documentation
source_type
enum AP_RTC::source_type : uint8_t
Enumerator
SOURCE_GPS
SOURCE_MAVLINK_SYSTEM_TIME
SOURCE_HW
SOURCE_NONE
Definition at line 20 of file AP_RTC.h.
Constructor & Destructor Documentation
AP_RTC()
AP_RTC::AP_RTC ()
Definition at line 9 of file AP_RTC.cpp.
Member Function Documentation
get_singleton()
static AP_RTC* AP_RTC::get_singleton (void) inline static
Definition at line 45 of file AP_RTC.h.
Referenced by AP::rtc().
get_system_clock_utc()
bool AP_RTC::get_system_clock_utc (int32_t & hour, int32_t & min, int32_t & sec, int32_t & ms)
Definition at line 75 of file AP_RTC.cpp.
Referenced by get_time_utc().
get_time_utc()
uint32_t AP_RTC::get_time_utc (int32_t hour, int32_t min, int32_t sec, int32_t ms)
Definition at line 100 of file AP_RTC.cpp.
get_utc_usec()
bool AP_RTC::get_utc_usec (uint64_t & usec) const
Definition at line 66 of file AP_RTC.cpp.
Referenced by get_system_clock_utc(), and GCS_MAVLINK::send_system_time().
set_utc_usec()
void AP_RTC::set_utc_usec (uint64_t time_utc_usec, source_type type)
Definition at line 34 of file AP_RTC.cpp.
Referenced by GCS_MAVLINK::handle_system_time_message(), AP_BoardConfig::init(), and AP_GPS::update_instance().
Member Data Documentation
_singleton
AP_RTC * AP_RTC::_singleton static private
Definition at line 51 of file AP_RTC.h.
Referenced by AP_RTC(), and get_singleton().
allowed_types
AP_Int8 AP_RTC::allowed_types
Definition at line 15 of file AP_RTC.h.
Referenced by set_utc_usec().
rtc_shift
int64_t AP_RTC::rtc_shift private
Definition at line 54 of file AP_RTC.h.
Referenced by get_utc_usec(), and set_utc_usec().
rtc_source_type
source_type AP_RTC::rtc_source_type = SOURCE_NONE private
Definition at line 53 of file AP_RTC.h.
Referenced by get_utc_usec(), and set_utc_usec().
var_info
const AP_Param::GroupInfo AP_RTC::var_info static
Initial value:
= {
    AP_GROUPINFO("_TYPES",  1, AP_RTC, allowed_types, 1),
    AP_GROUPEND
}
Definition at line 13 of file AP_RTC.h.
Referenced by AP_RTC().
The documentation for this class was generated from the following files:
libraries/AP_RTC/AP_RTC.h
libraries/AP_RTC/AP_RTC.cpp