APM:Libraries: AP_MotorsMulticopter Class Reference
AP_MotorsMulticopter Class Reference abstract
#include <AP_MotorsMulticopter.h>
Public Member Functions
AP_MotorsMulticopter (uint16_t loop_rate, uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
virtual void output () override
void output_min () override
void set_yaw_headroom (int16_t pwm)
void set_throttle_range (int16_t radio_min, int16_t radio_max)
void update_throttle_hover (float dt)
virtual float get_throttle_hover () const override
void set_throttle_passthrough_for_esc_calibration (float throttle_input)
float get_lift_max ()
float get_batt_voltage_filt () const
float get_throttle_limit () const
float get_throttle_thrust_max () const
bool spool_up_complete () const
virtual void output_motor_mask (float thrust, uint8_t mask, float rudder_dt)
virtual uint16_t get_motor_mask () override
int16_t get_pwm_output_min () const
int16_t get_pwm_output_max () const
FUNCTOR_TYPEDEF (thrust_compensation_fn_t, void, float *, uint8_t)
void set_thrust_compensation_callback (thrust_compensation_fn_t callback)
Public Member Functions inherited from AP_Motors
AP_Motors (uint16_t loop_rate, uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
bool initialised_ok () const
bool armed () const
void armed (bool arm)
void set_interlock (bool set)
bool get_interlock () const
void set_roll (float roll_in)
void set_pitch (float pitch_in)
void set_yaw (float yaw_in)
void set_throttle (float throttle_in)
void set_throttle_avg_max (float throttle_avg_max)
void set_throttle_filter_cutoff (float filt_hz)
void set_forward (float forward_in)
void set_lateral (float lateral_in)
float get_roll () const
float get_pitch () const
float get_yaw () const
float get_throttle () const
float get_throttle_bidirectional () const
float get_forward () const
float get_lateral () const
void set_thrust_boost (bool enable)
bool get_thrust_boost () const
virtual uint8_t get_lost_motor () const
void set_desired_spool_state (enum DesiredSpoolState spool)
enum DesiredSpoolState get_desired_spool_state (void) const
enum SpoolState get_spool_state (void) const
void set_air_density_ratio (float ratio)
virtual void set_update_rate (uint16_t speed_hz)
virtual void init (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void output_test_seq (uint8_t motor_seq, int16_t pwm)=0
void set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
void set_loop_rate (uint16_t loop_rate)
virtual float get_roll_factor (uint8_t i)
pwm_type get_pwm_type (void) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Types
enum HoverLearn { HOVER_LEARN_DISABLED = 0, HOVER_LEARN_ONLY = 1, HOVER_LEARN_AND_SAVE = 2 }
Protected Member Functions
void output_logic ()
virtual void output_to_motors ()=0
virtual void update_throttle_filter () override
virtual float get_current_limit_max_throttle ()
float apply_thrust_curve_and_volt_scaling (float thrust) const
void update_lift_max_from_batt_voltage ()
float get_compensation_gain () const
int16_t output_to_pwm (float _actuator_output)
float thrust_to_actuator (float thrust_in)
void set_actuator_with_slew (float &actuator_output, float input)
float actuator_spin_up_to_ground_idle () const
virtual void thrust_compensation (void)
virtual void output_boost_throttle (void)
void save_params_on_disarm () override
Protected Member Functions inherited from AP_Motors
virtual void output_armed_stabilizing ()=0
virtual void rc_write (uint8_t chan, uint16_t pwm)
virtual void rc_write_angle (uint8_t chan, int16_t angle_cd)
virtual void rc_set_freq (uint32_t mask, uint16_t freq_hz)
virtual uint32_t rc_map_mask (uint32_t mask) const
void add_motor_num (int8_t motor_num)
Protected Attributes
AP_Int16 _yaw_headroom
AP_Float _thrust_curve_expo
AP_Float _slew_up_time
AP_Float _slew_dn_time
AP_Float _spin_min
AP_Float _spin_max
AP_Float _spin_arm
AP_Float _batt_voltage_max
AP_Float _batt_voltage_min
AP_Float _batt_current_max
AP_Float _batt_current_time_constant
AP_Int8 _batt_idx
AP_Int16 _pwm_min
AP_Int16 _pwm_max
AP_Float _throttle_hover
AP_Int8 _throttle_hover_learn
AP_Int8 _disarm_disable_pwm
AP_Float _yaw_servo_angle_max_deg
AP_Float _spool_up_time
AP_Float _boost_scale
bool motor_enabled [AP_MOTORS_MAX_NUM_MOTORS]
int16_t _throttle_radio_min
int16_t _throttle_radio_max
float _spin_up_ratio
LowPassFilterFloat _batt_voltage_filt
float _lift_max
float _throttle_limit
float _throttle_thrust_max
uint16_t _disarm_safety_timer
thrust_compensation_fn_t _thrust_compensation_callback
float _actuator [AP_MOTORS_MAX_NUM_MOTORS]
Protected Attributes inherited from AP_Motors
struct AP_Motors::AP_Motors_flags _flags
uint16_t _loop_rate
uint16_t _speed_hz
float _roll_in
float _pitch_in
float _yaw_in
float _throttle_in
float _forward_in
float _lateral_in
float _throttle_avg_max
LowPassFilterFloat _throttle_filter
DesiredSpoolState _spool_desired
SpoolState _spool_state
float _air_density_ratio
uint16_t _motor_fast_mask
float _roll_radio_passthrough
float _pitch_radio_passthrough
float _throttle_radio_passthrough
float _yaw_radio_passthrough
AP_Int8 _pwm_type
bool _thrust_boost
bool _thrust_balanced
float _thrust_boost_ratio
Additional Inherited Members
Public Types inherited from AP_Motors
enum motor_frame_class {
MOTOR_FRAME_UNDEFINED = 0, MOTOR_FRAME_QUAD = 1, MOTOR_FRAME_HEXA = 2, MOTOR_FRAME_OCTA = 3,
MOTOR_FRAME_OCTAQUAD = 4, MOTOR_FRAME_Y6 = 5, MOTOR_FRAME_HELI = 6, MOTOR_FRAME_TRI = 7,
MOTOR_FRAME_SINGLE = 8, MOTOR_FRAME_COAX = 9, MOTOR_FRAME_TAILSITTER = 10, MOTOR_FRAME_HELI_DUAL = 11,
MOTOR_FRAME_DODECAHEXA = 12, MOTOR_FRAME_HELI_QUAD = 13
}
enum motor_frame_type {
MOTOR_FRAME_TYPE_PLUS = 0, MOTOR_FRAME_TYPE_X = 1, MOTOR_FRAME_TYPE_V = 2, MOTOR_FRAME_TYPE_H = 3,
MOTOR_FRAME_TYPE_VTAIL = 4, MOTOR_FRAME_TYPE_ATAIL = 5, MOTOR_FRAME_TYPE_PLUSREV = 6, MOTOR_FRAME_TYPE_Y6B = 10,
MOTOR_FRAME_TYPE_Y6F = 11, MOTOR_FRAME_TYPE_BF_X = 12, MOTOR_FRAME_TYPE_DJI_X = 13, MOTOR_FRAME_TYPE_CW_X = 14,
MOTOR_FRAME_TYPE_I = 15
}
enum DesiredSpoolState : uint8_t { DesiredSpoolState::SHUT_DOWN = 0, DesiredSpoolState::GROUND_IDLE = 1, DesiredSpoolState::THROTTLE_UNLIMITED = 2 }
enum SpoolState : uint8_t {
SpoolState::SHUT_DOWN = 0, SpoolState::GROUND_IDLE = 1, SpoolState::SPOOLING_UP = 2, SpoolState::THROTTLE_UNLIMITED = 3,
SpoolState::SPOOLING_DOWN = 4
}
enum pwm_type {
PWM_TYPE_NORMAL = 0, PWM_TYPE_ONESHOT = 1, PWM_TYPE_ONESHOT125 = 2, PWM_TYPE_BRUSHED = 3,
PWM_TYPE_DSHOT150 = 4, PWM_TYPE_DSHOT300 = 5, PWM_TYPE_DSHOT600 = 6, PWM_TYPE_DSHOT1200 = 7
}
Static Public Member Functions inherited from AP_Motors
static AP_Motors * get_singleton (void)
Public Attributes inherited from AP_Motors
struct AP_Motors::AP_Motors_limit limit
Detailed Description
Definition at line 31 of file AP_MotorsMulticopter.h.
Member Enumeration Documentation
HoverLearn
enum AP_MotorsMulticopter::HoverLearn protected
Enumerator
HOVER_LEARN_DISABLED
HOVER_LEARN_ONLY
HOVER_LEARN_AND_SAVE
Definition at line 140 of file AP_MotorsMulticopter.h.
Constructor & Destructor Documentation
AP_MotorsMulticopter()
AP_MotorsMulticopter::AP_MotorsMulticopter (uint16_t loop_rate, uint16_t speed_hz = AP_MOTORS_SPEED_DEFAULT)
Definition at line 210 of file AP_MotorsMulticopter.cpp.
Member Function Documentation
actuator_spin_up_to_ground_idle()
float AP_MotorsMulticopter::actuator_spin_up_to_ground_idle () const protected
Definition at line 441 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), and AP_MotorsCoax::output_to_motors().
apply_thrust_curve_and_volt_scaling()
float AP_MotorsMulticopter::apply_thrust_curve_and_volt_scaling (float thrust) const protected
Definition at line 323 of file AP_MotorsMulticopter.cpp.
Referenced by thrust_to_actuator().
FUNCTOR_TYPEDEF()
AP_MotorsMulticopter::FUNCTOR_TYPEDEF (thrust_compensation_fn_t , void , float * , uint8_t)
get_batt_voltage_filt()
float AP_MotorsMulticopter::get_batt_voltage_filt () const inline
Definition at line 62 of file AP_MotorsMulticopter.h.
get_compensation_gain()
float AP_MotorsMulticopter::get_compensation_gain () const protected
Definition at line 366 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsMatrixTS::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), and AP_MotorsMatrix::output_armed_stabilizing().
get_current_limit_max_throttle()
float AP_MotorsMulticopter::get_current_limit_max_throttle () protected virtual
Reimplemented in AP_Motors6DOF.
Definition at line 287 of file AP_MotorsMulticopter.cpp.
Referenced by output_logic().
get_lift_max()
float AP_MotorsMulticopter::get_lift_max () inline
Definition at line 59 of file AP_MotorsMulticopter.h.
get_motor_mask()
uint16_t AP_MotorsMulticopter::get_motor_mask () override virtual
Implements AP_Motors.
Reimplemented in AP_MotorsCoax, AP_MotorsSingle, AP_MotorsMatrix, AP_MotorsTri, and AP_MotorsTailsitter.
Definition at line 726 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsTailsitter::get_motor_mask(), AP_MotorsTri::get_motor_mask(), AP_MotorsMatrix::get_motor_mask(), AP_MotorsSingle::get_motor_mask(), and AP_MotorsCoax::get_motor_mask().
get_pwm_output_max()
int16_t AP_MotorsMulticopter::get_pwm_output_max () const
Definition at line 457 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsMatrixTS::output_motor_mask(), output_motor_mask(), output_to_pwm(), set_throttle_passthrough_for_esc_calibration(), and set_throttle_range().
get_pwm_output_min()
int16_t AP_MotorsMulticopter::get_pwm_output_min () const
Definition at line 447 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsMatrixTS::output_motor_mask(), output_motor_mask(), AP_MotorsTailsitter::output_to_motors(), output_to_pwm(), set_throttle_passthrough_for_esc_calibration(), and set_throttle_range().
get_throttle_hover()
virtual float AP_MotorsMulticopter::get_throttle_hover () const inline override virtual
Implements AP_Motors.
Definition at line 52 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle().
get_throttle_limit()
float AP_MotorsMulticopter::get_throttle_limit () const inline
Definition at line 65 of file AP_MotorsMulticopter.h.
get_throttle_thrust_max()
float AP_MotorsMulticopter::get_throttle_thrust_max () const inline
Definition at line 68 of file AP_MotorsMulticopter.h.
Referenced by AC_AttitudeControl_Sub::update_althold_lean_angle_max(), and AC_AttitudeControl_Multi::update_althold_lean_angle_max().
output()
void AP_MotorsMulticopter::output () override virtual
Implements AP_Motors.
Definition at line 227 of file AP_MotorsMulticopter.cpp.
Referenced by output_min(), and update_motors().
output_boost_throttle()
void AP_MotorsMulticopter::output_boost_throttle (void) protected virtual
Definition at line 252 of file AP_MotorsMulticopter.cpp.
Referenced by output().
output_logic()
void AP_MotorsMulticopter::output_logic () protected
Definition at line 497 of file AP_MotorsMulticopter.cpp.
Referenced by output().
output_min()
void AP_MotorsMulticopter::output_min () override virtual
Implements AP_Motors.
Definition at line 262 of file AP_MotorsMulticopter.cpp.
Referenced by setup().
output_motor_mask()
void AP_MotorsMulticopter::output_motor_mask (float thrust, uint8_t mask, float rudder_dt) virtual
Reimplemented in AP_MotorsTri, and AP_MotorsMatrixTS.
Definition at line 702 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsTri::output_motor_mask().
output_to_motors()
virtual void AP_MotorsMulticopter::output_to_motors () protected pure virtual
Implemented in AP_MotorsCoax, AP_MotorsSingle, AP_MotorsMatrix, AP_Motors6DOF, AP_MotorsTri, AP_MotorsTailsitter, and AP_MotorsMatrixTS.
Referenced by output().
output_to_pwm()
int16_t AP_MotorsMulticopter::output_to_pwm (float _actuator_output) protected
Definition at line 385 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), and AP_MotorsCoax::output_to_motors().
save_params_on_disarm()
void AP_MotorsMulticopter::save_params_on_disarm () override protected virtual
Reimplemented from AP_Motors.
Definition at line 732 of file AP_MotorsMulticopter.cpp.
set_actuator_with_slew()
void AP_MotorsMulticopter::set_actuator_with_slew (float & actuator_output, float input) protected
Definition at line 411 of file AP_MotorsMulticopter.cpp.
Referenced by output_motor_mask(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsCoax::output_to_motors(), and AP_MotorsSingle::output_to_motors().
set_throttle_passthrough_for_esc_calibration()
void AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration (float throttle_input)
Definition at line 683 of file AP_MotorsMulticopter.cpp.
set_throttle_range()
void AP_MotorsMulticopter::set_throttle_range (int16_t radio_min, int16_t radio_max)
Definition at line 468 of file AP_MotorsMulticopter.cpp.
Referenced by setup().
set_thrust_compensation_callback()
void AP_MotorsMulticopter::set_thrust_compensation_callback (thrust_compensation_fn_t callback) inline
Definition at line 88 of file AP_MotorsMulticopter.h.
set_yaw_headroom()
void AP_MotorsMulticopter::set_yaw_headroom (int16_t pwm) inline
Definition at line 44 of file AP_MotorsMulticopter.h.
spool_up_complete()
bool AP_MotorsMulticopter::spool_up_complete () const inline
Definition at line 71 of file AP_MotorsMulticopter.h.
thrust_compensation()
virtual void AP_MotorsMulticopter::thrust_compensation (void) inline protected virtual
Reimplemented in AP_MotorsMatrix, and AP_MotorsTri.
Definition at line 131 of file AP_MotorsMulticopter.h.
Referenced by output().
thrust_to_actuator()
float AP_MotorsMulticopter::thrust_to_actuator (float thrust_in) protected
Definition at line 404 of file AP_MotorsMulticopter.cpp.
Referenced by output_motor_mask(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsCoax::output_to_motors(), and AP_MotorsSingle::output_to_motors().
update_lift_max_from_batt_voltage()
void AP_MotorsMulticopter::update_lift_max_from_batt_voltage () protected
Definition at line 342 of file AP_MotorsMulticopter.cpp.
Referenced by output().
update_throttle_filter()
void AP_MotorsMulticopter::update_throttle_filter () override protected virtual
Implements AP_Motors.
Definition at line 270 of file AP_MotorsMulticopter.cpp.
Referenced by output().
update_throttle_hover()
void AP_MotorsMulticopter::update_throttle_hover (float dt)
Definition at line 488 of file AP_MotorsMulticopter.cpp.
Member Data Documentation
_actuator
float AP_MotorsMulticopter::_actuator[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 194 of file AP_MotorsMulticopter.h.
Referenced by output_motor_mask(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsCoax::output_to_motors(), and AP_MotorsSingle::output_to_motors().
_batt_current_max
AP_Float AP_MotorsMulticopter::_batt_current_max protected
Definition at line 156 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and AP_Motors6DOF::output_armed_stabilizing().
_batt_current_time_constant
AP_Float AP_MotorsMulticopter::_batt_current_time_constant protected
Definition at line 157 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and AP_Motors6DOF::output_armed_stabilizing().
_batt_idx
AP_Int8 AP_MotorsMulticopter::_batt_idx protected
Definition at line 158 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and update_lift_max_from_batt_voltage().
_batt_voltage_filt
LowPassFilterFloat AP_MotorsMulticopter::_batt_voltage_filt protected
Definition at line 184 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMulticopter(), apply_thrust_curve_and_volt_scaling(), get_batt_voltage_filt(), and update_lift_max_from_batt_voltage().
_batt_voltage_max
AP_Float AP_MotorsMulticopter::_batt_voltage_max protected
Definition at line 154 of file AP_MotorsMulticopter.h.
Referenced by update_lift_max_from_batt_voltage().
_batt_voltage_min
AP_Float AP_MotorsMulticopter::_batt_voltage_min protected
Definition at line 155 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and update_lift_max_from_batt_voltage().
_boost_scale
AP_Float AP_MotorsMulticopter::_boost_scale protected
Definition at line 172 of file AP_MotorsMulticopter.h.
Referenced by output_boost_throttle().
_disarm_disable_pwm
AP_Int8 AP_MotorsMulticopter::_disarm_disable_pwm protected
Definition at line 163 of file AP_MotorsMulticopter.h.
Referenced by output_to_pwm().
_disarm_safety_timer
uint16_t AP_MotorsMulticopter::_disarm_safety_timer protected
Definition at line 188 of file AP_MotorsMulticopter.h.
Referenced by output_logic(), and output_to_pwm().
_lift_max
float AP_MotorsMulticopter::_lift_max protected
Definition at line 185 of file AP_MotorsMulticopter.h.
Referenced by apply_thrust_curve_and_volt_scaling(), get_compensation_gain(), get_lift_max(), and update_lift_max_from_batt_voltage().
_pwm_max
AP_Int16 AP_MotorsMulticopter::_pwm_max protected
Definition at line 160 of file AP_MotorsMulticopter.h.
Referenced by get_pwm_output_max(), get_pwm_output_min(), and set_throttle_range().
_pwm_min
AP_Int16 AP_MotorsMulticopter::_pwm_min protected
Definition at line 159 of file AP_MotorsMulticopter.h.
Referenced by get_pwm_output_max(), get_pwm_output_min(), and set_throttle_range().
_slew_dn_time
AP_Float AP_MotorsMulticopter::_slew_dn_time protected
Definition at line 150 of file AP_MotorsMulticopter.h.
Referenced by set_actuator_with_slew().
_slew_up_time
AP_Float AP_MotorsMulticopter::_slew_up_time protected
Definition at line 149 of file AP_MotorsMulticopter.h.
Referenced by set_actuator_with_slew().
_spin_arm
AP_Float AP_MotorsMulticopter::_spin_arm protected
Definition at line 153 of file AP_MotorsMulticopter.h.
Referenced by output_logic().
_spin_max
AP_Float AP_MotorsMulticopter::_spin_max protected
Definition at line 152 of file AP_MotorsMulticopter.h.
Referenced by thrust_to_actuator().
_spin_min
AP_Float AP_MotorsMulticopter::_spin_min protected
Definition at line 151 of file AP_MotorsMulticopter.h.
Referenced by actuator_spin_up_to_ground_idle(), output_logic(), and thrust_to_actuator().
_spin_up_ratio
float AP_MotorsMulticopter::_spin_up_ratio protected
Definition at line 181 of file AP_MotorsMulticopter.h.
Referenced by actuator_spin_up_to_ground_idle(), output_logic(), AP_MotorsSingle::output_to_motors(), and AP_MotorsCoax::output_to_motors().
_spool_up_time
AP_Float AP_MotorsMulticopter::_spool_up_time protected
Definition at line 169 of file AP_MotorsMulticopter.h.
Referenced by output_logic().
_throttle_hover
AP_Float AP_MotorsMulticopter::_throttle_hover protected
Definition at line 161 of file AP_MotorsMulticopter.h.
Referenced by get_throttle_hover(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), save_params_on_disarm(), and update_throttle_hover().
_throttle_hover_learn
AP_Int8 AP_MotorsMulticopter::_throttle_hover_learn protected
Definition at line 162 of file AP_MotorsMulticopter.h.
Referenced by save_params_on_disarm(), and update_throttle_hover().
_throttle_limit
float AP_MotorsMulticopter::_throttle_limit protected
Definition at line 186 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and get_throttle_limit().
_throttle_radio_max
int16_t AP_MotorsMulticopter::_throttle_radio_max protected
Definition at line 177 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMulticopter(), AP_Motors6DOF::calc_thrust_to_pwm(), get_pwm_output_max(), and set_throttle_range().
_throttle_radio_min
int16_t AP_MotorsMulticopter::_throttle_radio_min protected
Definition at line 176 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMulticopter(), AP_Motors6DOF::calc_thrust_to_pwm(), get_pwm_output_min(), and set_throttle_range().
_throttle_thrust_max
float AP_MotorsMulticopter::_throttle_thrust_max protected
Definition at line 187 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMatrix::check_for_failed_motor(), get_throttle_thrust_max(), AP_MotorsMatrixTS::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and output_logic().
_thrust_compensation_callback
thrust_compensation_fn_t AP_MotorsMulticopter::_thrust_compensation_callback protected
Definition at line 191 of file AP_MotorsMulticopter.h.
Referenced by set_thrust_compensation_callback(), AP_MotorsTri::thrust_compensation(), and AP_MotorsMatrix::thrust_compensation().
_thrust_curve_expo
AP_Float AP_MotorsMulticopter::_thrust_curve_expo protected
Definition at line 148 of file AP_MotorsMulticopter.h.
Referenced by apply_thrust_curve_and_volt_scaling(), and update_lift_max_from_batt_voltage().
_yaw_headroom
AP_Int16 AP_MotorsMulticopter::_yaw_headroom protected
Definition at line 147 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), and set_yaw_headroom().
_yaw_servo_angle_max_deg
AP_Float AP_MotorsMulticopter::_yaw_servo_angle_max_deg protected
Definition at line 166 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsTri::output_armed_stabilizing(), and AP_MotorsTri::output_to_motors().
motor_enabled
bool AP_MotorsMulticopter::motor_enabled[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 175 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMatrix::add_motor_raw(), AP_MotorsMatrix::check_for_failed_motor(), AP_MotorsMatrix::get_motor_mask(), AP_MotorsTailsitter::init(), AP_MotorsTri::init(), AP_MotorsSingle::init(), AP_MotorsCoax::init(), AP_MotorsMatrix::normalise_rpy_factors(), AP_MotorsMatrixTS::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_Motors6DOF::output_min(), AP_MotorsMatrixTS::output_motor_mask(), output_motor_mask(), AP_MotorsMatrix::output_test_num(), AP_MotorsMatrix::output_test_seq(), AP_Motors6DOF::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsMatrix::remove_motor(), set_throttle_passthrough_for_esc_calibration(), and AP_MotorsMatrix::set_update_rate().
var_info
const AP_Param::GroupInfo AP_MotorsMulticopter::var_info static
Definition at line 93 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMatrixTS::AP_MotorsMatrixTS(), and AP_MotorsMulticopter().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsMulticopter.h
libraries/AP_Motors/AP_MotorsMulticopter.cpp