APM:Libraries: Linux::Pollable Class Reference
Linux::Pollable Class Reference
#include <Poller.h>
Public Member Functions
Pollable (int fd)
Pollable ()
virtual ~Pollable ()
int get_fd () const
virtual void on_can_read ()
virtual void on_can_write ()
virtual void on_error ()
virtual void on_hang_up ()
Protected Attributes
int _fd = -1
Friends
class Poller
Detailed Description
Definition at line 28 of file Poller.h.
Constructor & Destructor Documentation
Pollable() [1/2]
Linux::Pollable::Pollable (int fd) inline
Definition at line 31 of file Poller.h.
Pollable() [2/2]
Linux::Pollable::Pollable () inline
Definition at line 32 of file Poller.h.
~Pollable()
Linux::Pollable::~Pollable () virtual
Definition at line 148 of file Poller.cpp.
Member Function Documentation
get_fd()
int Linux::Pollable::get_fd () const inline
Definition at line 36 of file Poller.h.
Referenced by Linux::Poller::register_pollable(), Linux::Poller::unregister_pollable(), and Linux::Poller::wakeup().
on_can_read()
virtual void Linux::Pollable::on_can_read () inline virtual
Reimplemented in Linux::WakeupPollable, and Linux::TimerPollable.
Definition at line 39 of file Poller.h.
Referenced by Linux::Poller::poll().
on_can_write()
virtual void Linux::Pollable::on_can_write () inline virtual
Definition at line 45 of file Poller.h.
Referenced by Linux::Poller::poll().
on_error()
virtual void Linux::Pollable::on_error () inline virtual
Definition at line 51 of file Poller.h.
Referenced by Linux::Poller::poll().
on_hang_up()
virtual void Linux::Pollable::on_hang_up () inline virtual
Definition at line 57 of file Poller.h.
Referenced by Linux::Poller::poll().
Friends And Related Function Documentation
Poller
friend class Poller friend
Definition at line 29 of file Poller.h.
Member Data Documentation
_fd
int Linux::Pollable::_fd = -1 protected
Definition at line 60 of file Poller.h.
Referenced by Linux::TimerPollable::adjust_timer(), get_fd(), Linux::TimerPollable::on_can_read(), Linux::WakeupPollable::on_can_read(), Linux::Poller::Poller(), Linux::TimerPollable::setup_timer(), and ~Pollable().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Poller.h
libraries/AP_HAL_Linux/Poller.cpp