APM:Libraries: AP_RangeFinder_BLPing Class Reference
AP_RangeFinder_BLPing Class Reference
#include <AP_RangeFinder_BLPing.h>
Public Member Functions
AP_RangeFinder_BLPing (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_SerialManager &serial_manager, uint8_t serial_instance)
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void handle_msg (mavlink_message_t *msg)
enum Rotation orientation () const
uint16_t distance_cm () const
uint16_t voltage_mv () const
int16_t max_distance_cm () const
int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::RangeFinder_Status status () const
RangeFinder::RangeFinder_Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
Static Public Member Functions
static bool detect (AP_SerialManager &serial_manager, uint8_t serial_instance)
Protected Member Functions
virtual MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status ()
void set_status (RangeFinder::RangeFinder_Status status)
Private Types
enum ParseState {
ParseState::HEADER1 = 0, ParseState::HEADER2, ParseState::LEN_L, ParseState::LEN_H,
ParseState::MSG_ID_L, ParseState::MSG_ID_H, ParseState::SRC_ID, ParseState::DST_ID,
ParseState::PAYLOAD, ParseState::CRC_L, ParseState::CRC_H
}
Private Member Functions
void init_sensor ()
void send_message (uint16_t msgid, const uint8_t *payload, uint16_t payload_len)
bool get_reading (uint16_t &reading_cm)
bool parse_byte (uint8_t b)
Private Attributes
AP_HAL::UARTDriver * uart
uint32_t last_init_ms
uint16_t distance_cm
struct {
ParseState state
uint8_t payload [20]
uint16_t payload_len
uint16_t msgid
uint16_t payload_recv
uint16_t crc
uint16_t crc_expected
} msg
Additional Inherited Members
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::RangeFinder_Type _backend_type
Detailed Description
Definition at line 6 of file AP_RangeFinder_BLPing.h.
Member Enumeration Documentation
ParseState
enum AP_RangeFinder_BLPing::ParseState strong private
Enumerator
HEADER1
HEADER2
LEN_L
LEN_H
MSG_ID_L
MSG_ID_H
SRC_ID
DST_ID
PAYLOAD
CRC_L
CRC_H
Definition at line 44 of file AP_RangeFinder_BLPing.h.
Constructor & Destructor Documentation
AP_RangeFinder_BLPing()
AP_RangeFinder_BLPing::AP_RangeFinder_BLPing (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_SerialManager & serial_manager, uint8_t serial_instance)
Definition at line 54 of file AP_RangeFinder_BLPing.cpp.
Member Function Documentation
_get_mav_distance_sensor_type()
virtual MAV_DISTANCE_SENSOR AP_RangeFinder_BLPing::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 25 of file AP_RangeFinder_BLPing.h.
detect()
bool AP_RangeFinder_BLPing::detect (AP_SerialManager & serial_manager, uint8_t serial_instance) static
Definition at line 67 of file AP_RangeFinder_BLPing.cpp.
Referenced by RangeFinder::detect_instance().
get_reading()
bool AP_RangeFinder_BLPing::get_reading (uint16_t & reading_cm) private
Definition at line 153 of file AP_RangeFinder_BLPing.cpp.
Referenced by update().
init_sensor()
void AP_RangeFinder_BLPing::init_sensor (void) private
Definition at line 98 of file AP_RangeFinder_BLPing.cpp.
Referenced by update().
parse_byte()
bool AP_RangeFinder_BLPing::parse_byte (uint8_t b) private
Definition at line 192 of file AP_RangeFinder_BLPing.cpp.
Referenced by get_reading().
send_message()
void AP_RangeFinder_BLPing::send_message (uint16_t msgid, const uint8_t * payload, uint16_t payload_len) private
Definition at line 105 of file AP_RangeFinder_BLPing.cpp.
Referenced by get_reading(), and init_sensor().
update()
void AP_RangeFinder_BLPing::update (void) override virtual
Implements AP_RangeFinder_Backend.
Definition at line 75 of file AP_RangeFinder_BLPing.cpp.
Member Data Documentation
crc
uint16_t AP_RangeFinder_BLPing::crc
Definition at line 69 of file AP_RangeFinder_BLPing.h.
Referenced by send_message().
crc_expected
uint16_t AP_RangeFinder_BLPing::crc_expected
Definition at line 70 of file AP_RangeFinder_BLPing.h.
distance_cm
uint16_t AP_RangeFinder_BLPing::distance_cm private
Definition at line 60 of file AP_RangeFinder_BLPing.h.
last_init_ms
uint32_t AP_RangeFinder_BLPing::last_init_ms private
Definition at line 59 of file AP_RangeFinder_BLPing.h.
Referenced by update().
msg
struct { ... } AP_RangeFinder_BLPing::msg
Referenced by parse_byte().
msgid
uint16_t AP_RangeFinder_BLPing::msgid
Definition at line 67 of file AP_RangeFinder_BLPing.h.
Referenced by send_message().
payload
uint8_t AP_RangeFinder_BLPing::payload[20]
Definition at line 65 of file AP_RangeFinder_BLPing.h.
Referenced by send_message().
payload_len
uint16_t AP_RangeFinder_BLPing::payload_len
Definition at line 66 of file AP_RangeFinder_BLPing.h.
Referenced by send_message().
payload_recv
uint16_t AP_RangeFinder_BLPing::payload_recv
Definition at line 68 of file AP_RangeFinder_BLPing.h.
state
ParseState AP_RangeFinder_BLPing::state
Definition at line 64 of file AP_RangeFinder_BLPing.h.
Referenced by update().
uart
AP_HAL::UARTDriver* AP_RangeFinder_BLPing::uart private
Definition at line 58 of file AP_RangeFinder_BLPing.h.
Referenced by AP_RangeFinder_BLPing(), get_reading(), send_message(), and update().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_BLPing.h
libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp