APM:Libraries: AP_WindVane_Backend Class Reference
AP_WindVane_Backend Class Reference
#include <AP_WindVane_Backend.h>
Public Member Functions
AP_WindVane_Backend (AP_WindVane &frontend)
virtual ~AP_WindVane_Backend ()
virtual void init (const AP_SerialManager &serial_manager)
virtual void update_speed ()
virtual void update_direction ()
virtual void calibrate ()
Protected Member Functions
void speed_update_frontend (float apparent_speed_in)
void direction_update_frontend (float apparent_angle_ef)
Protected Attributes
AP_WindVane & _frontend
Private Attributes
LowPassFilterFloat _dir_sin_filt = LowPassFilterFloat(2.0f)
LowPassFilterFloat _dir_cos_filt = LowPassFilterFloat(2.0f)
LowPassFilterFloat _speed_filt = LowPassFilterFloat(2.0f)
Detailed Description
Definition at line 22 of file AP_WindVane_Backend.h.
Constructor & Destructor Documentation
AP_WindVane_Backend()
AP_WindVane_Backend::AP_WindVane_Backend (AP_WindVane & frontend)
Definition at line 20 of file AP_WindVane_Backend.cpp.
~AP_WindVane_Backend()
virtual AP_WindVane_Backend::~AP_WindVane_Backend () inline virtual
Definition at line 30 of file AP_WindVane_Backend.h.
Member Function Documentation
calibrate()
void AP_WindVane_Backend::calibrate () virtual
Reimplemented in AP_WindVane_Analog, and AP_WindVane_ModernDevice.
Definition at line 57 of file AP_WindVane_Backend.cpp.
Referenced by AP_WindVane::update().
direction_update_frontend()
void AP_WindVane_Backend::direction_update_frontend (float apparent_angle_ef) protected
Definition at line 38 of file AP_WindVane_Backend.cpp.
Referenced by AP_WindVane_NMEA::update(), AP_WindVane_SITL::update_direction(), AP_WindVane_Home::update_direction(), and AP_WindVane_Analog::update_direction().
init()
virtual void AP_WindVane_Backend::init (const AP_SerialManager & serial_manager) inline virtual
Reimplemented in AP_WindVane_NMEA.
Definition at line 33 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane::init().
speed_update_frontend()
void AP_WindVane_Backend::speed_update_frontend (float apparent_speed_in) protected
Definition at line 26 of file AP_WindVane_Backend.cpp.
Referenced by AP_WindVane_NMEA::update(), AP_WindVane_SITL::update_speed(), AP_WindVane_RPM::update_speed(), AP_WindVane_Airspeed::update_speed(), and AP_WindVane_ModernDevice::update_speed().
update_direction()
virtual void AP_WindVane_Backend::update_direction () inline virtual
Reimplemented in AP_WindVane_Analog, AP_WindVane_NMEA, AP_WindVane_Home, and AP_WindVane_SITL.
Definition at line 37 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane::update().
update_speed()
virtual void AP_WindVane_Backend::update_speed () inline virtual
Reimplemented in AP_WindVane_ModernDevice, AP_WindVane_NMEA, AP_WindVane_Airspeed, AP_WindVane_RPM, and AP_WindVane_SITL.
Definition at line 36 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane::update().
Member Data Documentation
_dir_cos_filt
LowPassFilterFloat AP_WindVane_Backend::_dir_cos_filt = LowPassFilterFloat(2.0f) private
Definition at line 50 of file AP_WindVane_Backend.h.
Referenced by direction_update_frontend().
_dir_sin_filt
LowPassFilterFloat AP_WindVane_Backend::_dir_sin_filt = LowPassFilterFloat(2.0f) private
Definition at line 49 of file AP_WindVane_Backend.h.
Referenced by direction_update_frontend().
_frontend
AP_WindVane& AP_WindVane_Backend::_frontend protected
Definition at line 45 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane_Analog::calibrate(), AP_WindVane_ModernDevice::calibrate(), calibrate(), direction_update_frontend(), speed_update_frontend(), AP_WindVane_NMEA::update(), AP_WindVane_Home::update_direction(), AP_WindVane_NMEA::update_direction(), AP_WindVane_Analog::update_direction(), and AP_WindVane_ModernDevice::update_speed().
_speed_filt
LowPassFilterFloat AP_WindVane_Backend::_speed_filt = LowPassFilterFloat(2.0f) private
Definition at line 51 of file AP_WindVane_Backend.h.
Referenced by speed_update_frontend().
The documentation for this class was generated from the following files:
libraries/AP_WindVane/AP_WindVane_Backend.h
libraries/AP_WindVane/AP_WindVane_Backend.cpp