APM:Libraries: lua_scripts Class Reference
lua_scripts Class Reference
#include <lua_scripts.h>
Classes
struct script_info
Public Member Functions
lua_scripts (const AP_Int32 &vm_steps, const AP_Int32 &heap_size, const AP_Int8 &debug_level)
lua_scripts (const lua_scripts &other)=delete
lua_scripts & operator= (const lua_scripts &)=delete
void run (void)
Static Public Attributes
static bool overtime
Private Types
typedef struct lua_scripts::script_info script_info
Private Member Functions
script_info * load_script (lua_State *L, char *filename)
void load_all_scripts_in_dir (lua_State *L, const char *dirname)
void run_next_script (lua_State *L)
void remove_script (lua_State *L, script_info *script)
void reschedule_script (script_info *script)
Static Private Member Functions
static void hook (lua_State *L, lua_Debug *ar)
static int atpanic (lua_State *L)
static void * alloc (void *ud, void *ptr, size_t osize, size_t nsize)
Private Attributes
script_info * scripts
lua_State * lua_state
const AP_Int32 & _vm_steps
const AP_Int8 & _debug_level
Static Private Attributes
static jmp_buf panic_jmp
static void * _heap
Detailed Description
Definition at line 23 of file lua_scripts.h.
Member Typedef Documentation
script_info
typedef struct lua_scripts::script_info lua_scripts::script_info private
Constructor & Destructor Documentation
lua_scripts() [1/2]
lua_scripts::lua_scripts (const AP_Int32 & vm_steps, const AP_Int32 & heap_size, const AP_Int8 & debug_level)
Definition at line 44 of file lua_scripts.cpp.
lua_scripts() [2/2]
lua_scripts::lua_scripts (const lua_scripts & other) delete
Member Function Documentation
alloc()
void * lua_scripts::alloc (void * ud, void * ptr, size_t osize, size_t nsize) static private
Definition at line 303 of file lua_scripts.cpp.
Referenced by run().
atpanic()
int lua_scripts::atpanic (lua_State * L) static private
Definition at line 60 of file lua_scripts.cpp.
Referenced by run().
hook()
void lua_scripts::hook (lua_State * L, lua_Debug * ar) static private
Definition at line 50 of file lua_scripts.cpp.
Referenced by run_next_script().
load_all_scripts_in_dir()
void lua_scripts::load_all_scripts_in_dir (lua_State * L, const char * dirname) private
Definition at line 114 of file lua_scripts.cpp.
Referenced by run().
load_script()
lua_scripts::script_info * lua_scripts::load_script (lua_State * L, char * filename) private
Definition at line 67 of file lua_scripts.cpp.
Referenced by load_all_scripts_in_dir().
operator=()
lua_scripts& lua_scripts::operator= (const lua_scripts &) delete
remove_script()
void lua_scripts::remove_script (lua_State * L, script_info * script) private
Definition at line 239 of file lua_scripts.cpp.
Referenced by run(), and run_next_script().
reschedule_script()
void lua_scripts::reschedule_script (script_info * script) private
Definition at line 266 of file lua_scripts.cpp.
Referenced by load_all_scripts_in_dir(), and run_next_script().
run()
void lua_scripts::run (void)
Definition at line 308 of file lua_scripts.cpp.
run_next_script()
void lua_scripts::run_next_script (lua_State * L) private
Definition at line 158 of file lua_scripts.cpp.
Referenced by run().
Member Data Documentation
_debug_level
const AP_Int8& lua_scripts::_debug_level private
Definition at line 69 of file lua_scripts.h.
Referenced by run().
_heap
void * lua_scripts::_heap static private
Definition at line 73 of file lua_scripts.h.
Referenced by alloc(), load_all_scripts_in_dir(), load_script(), lua_scripts(), remove_script(), and run().
_vm_steps
const AP_Int32& lua_scripts::_vm_steps private
Definition at line 68 of file lua_scripts.h.
Referenced by run_next_script().
lua_state
lua_State* lua_scripts::lua_state private
Definition at line 66 of file lua_scripts.h.
Referenced by run().
overtime
bool lua_scripts::overtime static
Definition at line 35 of file lua_scripts.h.
Referenced by hook(), run(), and run_next_script().
panic_jmp
jmp_buf lua_scripts::panic_jmp static private
Definition at line 64 of file lua_scripts.h.
Referenced by atpanic(), and run().
scripts
script_info* lua_scripts::scripts private
Definition at line 56 of file lua_scripts.h.
Referenced by remove_script(), reschedule_script(), run(), and run_next_script().
The documentation for this class was generated from the following files:
libraries/AP_Scripting/lua_scripts.h
libraries/AP_Scripting/lua_scripts.cpp