APM:Libraries: AP_Proximity Class Reference
AP_Proximity Class Reference
#include <AP_Proximity.h>
Classes
struct Proximity_Distance_Array
struct Proximity_Location
struct Proximity_State
Public Types
enum Proximity_Type {
Proximity_Type_None = 0, Proximity_Type_SF40C = 1, Proximity_Type_MAV = 2, Proximity_Type_TRTOWER = 3,
Proximity_Type_RangeFinder = 4, Proximity_Type_RPLidarA2 = 5, Proximity_Type_TRTOWEREVO = 6, Proximity_Type_SITL = 10,
Proximity_Type_MorseSITL = 11
}
enum Proximity_Status { Proximity_NotConnected = 0, Proximity_NoData, Proximity_Good }
Public Member Functions
AP_Proximity (AP_SerialManager &_serial_manager)
AP_Proximity (const AP_Proximity &other)=delete
AP_Proximity & operator= (const AP_Proximity)=delete
void init (void)
void update (void)
void set_rangefinder (const RangeFinder *rangefinder)
const RangeFinder * get_rangefinder () const
uint8_t get_orientation (uint8_t instance) const
int16_t get_yaw_correction (uint8_t instance) const
Proximity_Status get_status (uint8_t instance) const
Proximity_Status get_status () const
uint8_t num_sensors (void) const
bool get_horizontal_distance (uint8_t instance, float angle_deg, float &distance) const
bool get_horizontal_distance (float angle_deg, float &distance) const
bool get_horizontal_distances (Proximity_Distance_Array &prx_dist_array) const
const Vector2f * get_boundary_points (uint8_t instance, uint16_t &num_points) const
const Vector2f * get_boundary_points (uint16_t &num_points) const
bool copy_locations (uint8_t instance, Proximity_Location *buff, uint16_t buff_size, uint16_t &num_copied)
bool copy_locations (Proximity_Location *buff, uint16_t buff_size, uint16_t &num_copied)
bool get_closest_object (float &angle_deg, float &distance) const
uint8_t get_object_count () const
bool get_object_angle_and_distance (uint8_t object_number, float &angle_deg, float &distance) const
float distance_max () const
float distance_min () const
void handle_msg (mavlink_message_t *msg)
bool get_upward_distance (uint8_t instance, float &distance) const
bool get_upward_distance (float &distance) const
Proximity_Type get_type (uint8_t instance) const
bool sensor_present () const
bool sensor_enabled () const
bool sensor_failed () const
Static Public Member Functions
static AP_Proximity * get_singleton (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void detect_instance (uint8_t instance)
Private Attributes
Proximity_State state [PROXIMITY_MAX_INSTANCES]
AP_Proximity_Backend * drivers [PROXIMITY_MAX_INSTANCES]
const RangeFinder * _rangefinder
uint8_t primary_instance
uint8_t num_instances
AP_SerialManager & serial_manager
AP_Int8 _type [PROXIMITY_MAX_INSTANCES]
AP_Int8 _orientation [PROXIMITY_MAX_INSTANCES]
AP_Int16 _yaw_correction [PROXIMITY_MAX_INSTANCES]
AP_Int16 _ignore_angle_deg [PROXIMITY_MAX_IGNORE]
AP_Int8 _ignore_width_deg [PROXIMITY_MAX_IGNORE]
Static Private Attributes
static AP_Proximity * _singleton
Friends
class AP_Proximity_Backend
Detailed Description
Definition at line 33 of file AP_Proximity.h.
Member Enumeration Documentation
Proximity_Status
enum AP_Proximity::Proximity_Status
Enumerator
Proximity_NotConnected
Proximity_NoData
Proximity_Good
Definition at line 56 of file AP_Proximity.h.
Proximity_Type
enum AP_Proximity::Proximity_Type
Enumerator
Proximity_Type_None
Proximity_Type_SF40C
Proximity_Type_MAV
Proximity_Type_TRTOWER
Proximity_Type_RangeFinder
Proximity_Type_RPLidarA2
Proximity_Type_TRTOWEREVO
Proximity_Type_SITL
Proximity_Type_MorseSITL
Definition at line 44 of file AP_Proximity.h.
Constructor & Destructor Documentation
AP_Proximity() [1/2]
AP_Proximity::AP_Proximity (AP_SerialManager & _serial_manager)
Definition at line 180 of file AP_Proximity.cpp.
AP_Proximity() [2/2]
AP_Proximity::AP_Proximity (const AP_Proximity & other) delete
Member Function Documentation
copy_locations() [1/2]
bool AP_Proximity::copy_locations (uint8_t instance, Proximity_Location * buff, uint16_t buff_size, uint16_t & num_copied)
Definition at line 386 of file AP_Proximity.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_proximity_sensors(), and copy_locations().
copy_locations() [2/2]
bool AP_Proximity::copy_locations (Proximity_Location * buff, uint16_t buff_size, uint16_t & num_copied)
Definition at line 397 of file AP_Proximity.cpp.
detect_instance()
void AP_Proximity::detect_instance (uint8_t instance) private
Definition at line 282 of file AP_Proximity.cpp.
Referenced by init().
distance_max()
float AP_Proximity::distance_max () const
Definition at line 435 of file AP_Proximity.cpp.
Referenced by GCS_MAVLINK::send_proximity().
distance_min()
float AP_Proximity::distance_min () const
Definition at line 443 of file AP_Proximity.cpp.
Referenced by GCS_MAVLINK::send_proximity().
get_boundary_points() [1/2]
const Vector2f * AP_Proximity::get_boundary_points (uint8_t instance, uint16_t & num_points) const
Definition at line 367 of file AP_Proximity.cpp.
Referenced by AC_Avoid::adjust_velocity_proximity(), and get_boundary_points().
get_boundary_points() [2/2]
const Vector2f * AP_Proximity::get_boundary_points (uint16_t & num_points) const
Definition at line 377 of file AP_Proximity.cpp.
get_closest_object()
bool AP_Proximity::get_closest_object (float & angle_deg, float & distance) const
Definition at line 404 of file AP_Proximity.cpp.
Referenced by AP_Logger::Write_Proximity().
get_horizontal_distance() [1/2]
bool AP_Proximity::get_horizontal_distance (uint8_t instance, float angle_deg, float & distance) const
Definition at line 339 of file AP_Proximity.cpp.
Referenced by get_horizontal_distance().
get_horizontal_distance() [2/2]
bool AP_Proximity::get_horizontal_distance (float angle_deg, float & distance) const
Definition at line 350 of file AP_Proximity.cpp.
get_horizontal_distances()
bool AP_Proximity::get_horizontal_distances (Proximity_Distance_Array & prx_dist_array) const
Definition at line 356 of file AP_Proximity.cpp.
Referenced by GCS_MAVLINK::send_proximity(), and AP_Logger::Write_Proximity().
get_object_angle_and_distance()
bool AP_Proximity::get_object_angle_and_distance (uint8_t object_number, float & angle_deg, float & distance) const
Definition at line 425 of file AP_Proximity.cpp.
Referenced by AC_Avoid::get_proximity_roll_pitch_pct().
get_object_count()
uint8_t AP_Proximity::get_object_count () const
Definition at line 414 of file AP_Proximity.cpp.
Referenced by AC_Avoid::get_proximity_roll_pitch_pct().
get_orientation()
uint8_t AP_Proximity::get_orientation (uint8_t instance) const
Definition at line 236 of file AP_Proximity.cpp.
Referenced by AP_Proximity_MAV::handle_msg(), AP_Proximity_RPLidarA2::parse_response_data(), and AP_Proximity_LightWareSF40C::set_motor_direction().
get_rangefinder()
const RangeFinder* AP_Proximity::get_rangefinder () const inline
Definition at line 83 of file AP_Proximity.h.
Referenced by AP_Proximity_RangeFinder::update().
get_singleton()
static AP_Proximity* AP_Proximity::get_singleton (void) inline static
Definition at line 152 of file AP_Proximity.h.
Referenced by AP_OABendyRuler::calc_margin_from_proximity_sensors(), AP::proximity(), GCS_MAVLINK::send_distance_sensor(), and GCS_MAVLINK::send_proximity().
get_status() [1/2]
AP_Proximity::Proximity_Status AP_Proximity::get_status (uint8_t instance) const
Definition at line 256 of file AP_Proximity.cpp.
Referenced by AC_Avoid::adjust_velocity_proximity(), AC_Avoid::get_proximity_roll_pitch_pct(), AP_Arming::proximity_checks(), GCS_MAVLINK::send_proximity(), and AP_Logger::Write_Proximity().
get_status() [2/2]
AP_Proximity::Proximity_Status AP_Proximity::get_status (void) const
Definition at line 266 of file AP_Proximity.cpp.
Referenced by sensor_failed(), and sensor_present().
get_type()
AP_Proximity::Proximity_Type AP_Proximity::get_type (uint8_t instance) const
Definition at line 467 of file AP_Proximity.cpp.
Referenced by GCS_MAVLINK::send_distance_sensor().
get_upward_distance() [1/2]
bool AP_Proximity::get_upward_distance (uint8_t instance, float & distance) const
Definition at line 453 of file AP_Proximity.cpp.
Referenced by AC_Avoid::adjust_velocity_z(), get_upward_distance(), GCS_MAVLINK::send_proximity(), and AP_Logger::Write_Proximity().
get_upward_distance() [2/2]
bool AP_Proximity::get_upward_distance (float & distance) const
Definition at line 462 of file AP_Proximity.cpp.
get_yaw_correction()
int16_t AP_Proximity::get_yaw_correction (uint8_t instance) const
Definition at line 246 of file AP_Proximity.cpp.
Referenced by AP_Proximity_MAV::handle_msg(), AP_Proximity_LightWareSF40C::initialise(), AP_Proximity_RPLidarA2::parse_response_data(), and AP_Proximity_LightWareSF40C::set_forward_direction().
handle_msg()
void AP_Proximity::handle_msg (mavlink_message_t * msg)
Definition at line 272 of file AP_Proximity.cpp.
init()
void AP_Proximity::init (void)
Definition at line 194 of file AP_Proximity.cpp.
num_sensors()
uint8_t AP_Proximity::num_sensors (void) const inline
Definition at line 94 of file AP_Proximity.h.
Referenced by GCS_MAVLINK::send_distance_sensor().
operator=()
AP_Proximity& AP_Proximity::operator= (const AP_Proximity) delete
sensor_enabled()
bool AP_Proximity::sensor_enabled () const
Definition at line 479 of file AP_Proximity.cpp.
sensor_failed()
bool AP_Proximity::sensor_failed () const
Definition at line 483 of file AP_Proximity.cpp.
sensor_present()
bool AP_Proximity::sensor_present () const
Definition at line 475 of file AP_Proximity.cpp.
set_rangefinder()
void AP_Proximity::set_rangefinder (const RangeFinder * rangefinder) inline
Definition at line 82 of file AP_Proximity.h.
update()
void AP_Proximity::update (void)
Definition at line 214 of file AP_Proximity.cpp.
Friends And Related Function Documentation
AP_Proximity_Backend
friend class AP_Proximity_Backend friend
Definition at line 36 of file AP_Proximity.h.
Member Data Documentation
_ignore_angle_deg
AP_Int16 AP_Proximity::_ignore_angle_deg[PROXIMITY_MAX_IGNORE] private
Definition at line 173 of file AP_Proximity.h.
Referenced by AP_Proximity_Backend::get_ignore_area(), and AP_Proximity_Backend::get_next_ignore_start_or_end().
_ignore_width_deg
AP_Int8 AP_Proximity::_ignore_width_deg[PROXIMITY_MAX_IGNORE] private
Definition at line 174 of file AP_Proximity.h.
Referenced by AP_Proximity_Backend::get_ignore_area(), AP_Proximity_Backend::get_ignore_area_count(), and AP_Proximity_Backend::get_next_ignore_start_or_end().
_orientation
AP_Int8 AP_Proximity::_orientation[PROXIMITY_MAX_INSTANCES] private
Definition at line 171 of file AP_Proximity.h.
Referenced by get_orientation().
_rangefinder
const RangeFinder* AP_Proximity::_rangefinder private
Definition at line 164 of file AP_Proximity.h.
Referenced by get_rangefinder(), and set_rangefinder().
_singleton
AP_Proximity * AP_Proximity::_singleton static private
Definition at line 161 of file AP_Proximity.h.
Referenced by AP_Proximity(), and get_singleton().
_type
AP_Int8 AP_Proximity::_type[PROXIMITY_MAX_INSTANCES] private
Definition at line 170 of file AP_Proximity.h.
Referenced by copy_locations(), detect_instance(), distance_max(), distance_min(), get_boundary_points(), get_closest_object(), get_horizontal_distance(), get_horizontal_distances(), get_object_angle_and_distance(), get_object_count(), get_type(), get_upward_distance(), handle_msg(), sensor_enabled(), and update().
_yaw_correction
AP_Int16 AP_Proximity::_yaw_correction[PROXIMITY_MAX_INSTANCES] private
Definition at line 172 of file AP_Proximity.h.
Referenced by get_yaw_correction().
drivers
AP_Proximity_Backend* AP_Proximity::drivers[PROXIMITY_MAX_INSTANCES] private
Definition at line 163 of file AP_Proximity.h.
Referenced by copy_locations(), detect_instance(), distance_max(), distance_min(), get_boundary_points(), get_closest_object(), get_horizontal_distance(), get_horizontal_distances(), get_object_angle_and_distance(), get_object_count(), get_upward_distance(), handle_msg(), init(), and update().
num_instances
uint8_t AP_Proximity::num_instances private
Definition at line 166 of file AP_Proximity.h.
Referenced by get_status(), handle_msg(), init(), num_sensors(), and update().
primary_instance
uint8_t AP_Proximity::primary_instance private
Definition at line 165 of file AP_Proximity.h.
Referenced by copy_locations(), distance_max(), distance_min(), get_boundary_points(), get_closest_object(), get_horizontal_distance(), get_horizontal_distances(), get_object_angle_and_distance(), get_object_count(), get_status(), get_upward_distance(), sensor_enabled(), and update().
serial_manager
AP_SerialManager& AP_Proximity::serial_manager private
Definition at line 167 of file AP_Proximity.h.
Referenced by detect_instance().
state
Proximity_State AP_Proximity::state[PROXIMITY_MAX_INSTANCES] private
Definition at line 162 of file AP_Proximity.h.
Referenced by detect_instance(), get_status(), init(), and update().
var_info
const AP_Param::GroupInfo AP_Proximity::var_info static
Definition at line 150 of file AP_Proximity.h.
Referenced by AP_Proximity().
The documentation for this class was generated from the following files:
libraries/AP_Proximity/AP_Proximity.h
libraries/AP_Proximity/AP_Proximity.cpp