APM:Libraries: AP_Compass_MAG3110 Class Reference
AP_Compass_MAG3110 Class Reference
#include <AP_Compass_MAG3110.h>
Public Member Functions
void read () override
~AP_Compass_MAG3110 ()
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * probe (AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation=ROTATION_NONE)
Static Public Attributes
static constexpr const char * name = "MAG3110"
Private Member Functions
AP_Compass_MAG3110 (AP_HAL::OwnPtr< AP_HAL::Device > dev)
bool init (enum Rotation rotation)
bool _read_sample ()
bool _hardware_init ()
void _update ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
int32_t _mag_x
int32_t _mag_y
int32_t _mag_z
uint8_t _compass_instance
bool _initialised
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01, DEVTYPE_HMC5883 = 0x07, DEVTYPE_LSM303D = 0x02, DEVTYPE_AK8963 = 0x04,
DEVTYPE_BMM150 = 0x05, DEVTYPE_LSM9DS1 = 0x06, DEVTYPE_LIS3MDL = 0x08, DEVTYPE_AK09916 = 0x09,
DEVTYPE_IST8310 = 0x0A, DEVTYPE_ICM20948 = 0x0B, DEVTYPE_MMC3416 = 0x0C, DEVTYPE_QMC5883L = 0x0D,
DEVTYPE_MAG3110 = 0x0E, DEVTYPE_SITL = 0x0F, DEVTYPE_IST8308 = 0x10, DEVTYPE_RM3100 = 0x11
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
HAL_Semaphore_Recursive _sem
Detailed Description
Definition at line 16 of file AP_Compass_MAG3110.h.
Constructor & Destructor Documentation
~AP_Compass_MAG3110()
AP_Compass_MAG3110::~AP_Compass_MAG3110 () inline
Definition at line 26 of file AP_Compass_MAG3110.h.
AP_Compass_MAG3110()
AP_Compass_MAG3110::AP_Compass_MAG3110 (AP_HAL::OwnPtr< AP_HAL::Device > dev) private
Definition at line 83 of file AP_Compass_MAG3110.cpp.
Referenced by probe().
Member Function Documentation
_hardware_init()
bool AP_Compass_MAG3110::_hardware_init () private
Definition at line 134 of file AP_Compass_MAG3110.cpp.
Referenced by init().
_read_sample()
bool AP_Compass_MAG3110::_read_sample () private
Definition at line 175 of file AP_Compass_MAG3110.cpp.
Referenced by _update().
_update()
void AP_Compass_MAG3110::_update (void) private
Definition at line 202 of file AP_Compass_MAG3110.cpp.
Referenced by init().
init()
bool AP_Compass_MAG3110::init (enum Rotation rotation) private
Definition at line 104 of file AP_Compass_MAG3110.cpp.
Referenced by probe().
probe()
AP_Compass_Backend * AP_Compass_MAG3110::probe (AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation = ROTATION_NONE) static
Definition at line 88 of file AP_Compass_MAG3110.cpp.
Referenced by Compass::_detect_backends().
read()
void AP_Compass_MAG3110::read (void) override virtual
Implements AP_Compass_Backend.
Definition at line 215 of file AP_Compass_MAG3110.cpp.
Referenced by init().
Member Data Documentation
_compass_instance
uint8_t AP_Compass_MAG3110::_compass_instance private
Definition at line 44 of file AP_Compass_MAG3110.h.
Referenced by _update(), init(), and read().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Compass_MAG3110::_dev private
Definition at line 38 of file AP_Compass_MAG3110.h.
Referenced by _hardware_init(), _read_sample(), and init().
_initialised
bool AP_Compass_MAG3110::_initialised private
Definition at line 45 of file AP_Compass_MAG3110.h.
Referenced by init(), and read().
_mag_x
int32_t AP_Compass_MAG3110::_mag_x private
Definition at line 40 of file AP_Compass_MAG3110.h.
Referenced by _read_sample(), and _update().
_mag_y
int32_t AP_Compass_MAG3110::_mag_y private
Definition at line 41 of file AP_Compass_MAG3110.h.
Referenced by _read_sample(), and _update().
_mag_z
int32_t AP_Compass_MAG3110::_mag_z private
Definition at line 42 of file AP_Compass_MAG3110.h.
Referenced by _read_sample(), and _update().
name
constexpr const char* AP_Compass_MAG3110::name = "MAG3110" static
Definition at line 22 of file AP_Compass_MAG3110.h.
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_MAG3110.h
libraries/AP_Compass/AP_Compass_MAG3110.cpp