APM:Libraries: AP_Proximity_Backend Class Reference
AP_Proximity_Backend Class Reference abstract
#include <AP_Proximity_Backend.h>
Public Member Functions
AP_Proximity_Backend (AP_Proximity &_frontend, AP_Proximity::Proximity_State &_state)
virtual ~AP_Proximity_Backend (void)
virtual void update ()=0
virtual float distance_max () const =0
virtual float distance_min () const =0
virtual bool get_upward_distance (float &distance) const
virtual void handle_msg (mavlink_message_t *msg)
bool get_horizontal_distance (float angle_deg, float &distance) const
const Vector2f * get_boundary_points (uint16_t &num_points) const
bool get_closest_object (float &angle_deg, float &distance) const
uint8_t get_object_count () const
bool get_object_angle_and_distance (uint8_t object_number, float &angle_deg, float &distance) const
bool get_horizontal_distances (AP_Proximity::Proximity_Distance_Array &prx_dist_array) const
bool copy_locations (AP_Proximity::Proximity_Location *buff, uint16_t buff_size, uint16_t &num_copied)
Protected Member Functions
void set_status (AP_Proximity::Proximity_Status status)
bool convert_angle_to_sector (float angle_degrees, uint8_t &sector) const
void init_boundary ()
void update_boundary_for_sector (uint8_t sector)
uint8_t get_ignore_area_count () const
bool get_ignore_area (uint8_t index, uint16_t &angle_deg, uint8_t &width_deg) const
bool get_next_ignore_start_or_end (uint8_t start_or_end, int16_t start_angle, int16_t &ignore_start) const
void update_locations ()
Protected Attributes
AP_Proximity & frontend
AP_Proximity::Proximity_State & state
uint8_t _num_sectors = PROXIMITY_MAX_DIRECTION
uint16_t _sector_middle_deg [PROXIMITY_SECTORS_MAX] = {0, 45, 90, 135, 180, 225, 270, 315, 0, 0, 0, 0}
uint8_t _sector_width_deg [PROXIMITY_SECTORS_MAX] = {45, 45, 45, 45, 45, 45, 45, 45, 0, 0, 0, 0}
float _angle [PROXIMITY_SECTORS_MAX]
float _distance [PROXIMITY_SECTORS_MAX]
bool _distance_valid [PROXIMITY_SECTORS_MAX]
Vector2f _sector_edge_vector [PROXIMITY_SECTORS_MAX]
Vector2f _boundary_point [PROXIMITY_SECTORS_MAX]
uint16_t _location_count
AP_Proximity::Proximity_Location _locations [PROXIMITY_SECTORS_MAX]
HAL_Semaphore_Recursive _rsem
Detailed Description
Definition at line 25 of file AP_Proximity_Backend.h.
Constructor & Destructor Documentation
AP_Proximity_Backend()
AP_Proximity_Backend::AP_Proximity_Backend (AP_Proximity & _frontend, AP_Proximity::Proximity_State & _state)
Definition at line 27 of file AP_Proximity_Backend.cpp.
~AP_Proximity_Backend()
virtual AP_Proximity_Backend::~AP_Proximity_Backend (void) inline virtual
Definition at line 33 of file AP_Proximity_Backend.h.
Member Function Documentation
convert_angle_to_sector()
bool AP_Proximity_Backend::convert_angle_to_sector (float angle_degrees, uint8_t & sector) const protected
Definition at line 261 of file AP_Proximity_Backend.cpp.
Referenced by get_horizontal_distance(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::process_reply(), AP_Proximity_TeraRangerTowerEvo::update_sector_data(), and AP_Proximity_TeraRangerTower::update_sector_data().
copy_locations()
bool AP_Proximity_Backend::copy_locations (AP_Proximity::Proximity_Location * buff, uint16_t buff_size, uint16_t & num_copied)
Definition at line 239 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::copy_locations().
distance_max()
virtual float AP_Proximity_Backend::distance_max () const pure virtual
Implemented in AP_Proximity_RPLidarA2, AP_Proximity_LightWareSF40C, AP_Proximity_TeraRangerTower, AP_Proximity_SITL, AP_Proximity_TeraRangerTowerEvo, AP_Proximity_MorseSITL, AP_Proximity_RangeFinder, and AP_Proximity_MAV.
Referenced by AP_Proximity::distance_max(), and get_horizontal_distances().
distance_min()
virtual float AP_Proximity_Backend::distance_min () const pure virtual
Implemented in AP_Proximity_RPLidarA2, AP_Proximity_LightWareSF40C, AP_Proximity_TeraRangerTower, AP_Proximity_SITL, AP_Proximity_TeraRangerTowerEvo, AP_Proximity_MorseSITL, AP_Proximity_RangeFinder, and AP_Proximity_MAV.
Referenced by AP_Proximity::distance_min().
get_boundary_points()
const Vector2f * AP_Proximity_Backend::get_boundary_points (uint16_t & num_points) const
Definition at line 141 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::get_boundary_points().
get_closest_object()
bool AP_Proximity_Backend::get_closest_object (float & angle_deg, float & distance) const
Definition at line 50 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::get_closest_object().
get_horizontal_distance()
bool AP_Proximity_Backend::get_horizontal_distance (float angle_deg, float & distance) const
Definition at line 36 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::get_horizontal_distance().
get_horizontal_distances()
bool AP_Proximity_Backend::get_horizontal_distances (AP_Proximity::Proximity_Distance_Array & prx_dist_array) const
Definition at line 91 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::get_horizontal_distances().
get_ignore_area()
bool AP_Proximity_Backend::get_ignore_area (uint8_t index, uint16_t & angle_deg, uint8_t & width_deg) const protected
Definition at line 317 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity_LightWareSF40C::init_sectors(), and AP_Proximity_RPLidarA2::init_sectors().
get_ignore_area_count()
uint8_t AP_Proximity_Backend::get_ignore_area_count () const protected
Definition at line 304 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity_LightWareSF40C::init_sectors(), and AP_Proximity_RPLidarA2::init_sectors().
get_next_ignore_start_or_end()
bool AP_Proximity_Backend::get_next_ignore_start_or_end (uint8_t start_or_end, int16_t start_angle, int16_t & ignore_start) const protected
Definition at line 329 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity_LightWareSF40C::init_sectors(), and AP_Proximity_RPLidarA2::init_sectors().
get_object_angle_and_distance()
bool AP_Proximity_Backend::get_object_angle_and_distance (uint8_t object_number, float & angle_deg, float & distance) const
Definition at line 80 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::get_object_angle_and_distance(), and update_locations().
get_object_count()
uint8_t AP_Proximity_Backend::get_object_count () const
Definition at line 73 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity::get_object_count(), and update_locations().
get_upward_distance()
virtual bool AP_Proximity_Backend::get_upward_distance (float & distance) const inline virtual
Reimplemented in AP_Proximity_SITL, AP_Proximity_MorseSITL, AP_Proximity_RangeFinder, and AP_Proximity_MAV.
Definition at line 43 of file AP_Proximity_Backend.h.
Referenced by AP_Proximity::get_upward_distance().
handle_msg()
virtual void AP_Proximity_Backend::handle_msg (mavlink_message_t * msg) inline virtual
Reimplemented in AP_Proximity_MAV.
Definition at line 46 of file AP_Proximity_Backend.h.
Referenced by AP_Proximity::handle_msg().
init_boundary()
void AP_Proximity_Backend::init_boundary () protected
Definition at line 169 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity_Backend(), AP_Proximity_LightWareSF40C::init_sectors(), and AP_Proximity_RPLidarA2::init_sectors().
set_status()
void AP_Proximity_Backend::set_status (AP_Proximity::Proximity_Status status) protected
Definition at line 256 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity_MAV::update(), AP_Proximity_RangeFinder::update(), AP_Proximity_MorseSITL::update(), AP_Proximity_TeraRangerTowerEvo::update(), AP_Proximity_SITL::update(), AP_Proximity_LightWareSF40C::update(), AP_Proximity_TeraRangerTower::update(), and AP_Proximity_RPLidarA2::update().
update()
virtual void AP_Proximity_Backend::update () pure virtual
Implemented in AP_Proximity_RPLidarA2, AP_Proximity_LightWareSF40C, AP_Proximity_TeraRangerTower, AP_Proximity_SITL, AP_Proximity_TeraRangerTowerEvo, AP_Proximity_MorseSITL, AP_Proximity_RangeFinder, and AP_Proximity_MAV.
Referenced by AP_Proximity::update().
update_boundary_for_sector()
void AP_Proximity_Backend::update_boundary_for_sector (uint8_t sector) protected
Definition at line 183 of file AP_Proximity_Backend.cpp.
Referenced by AP_Proximity_MAV::handle_msg(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::process_reply(), AP_Proximity_RangeFinder::update(), AP_Proximity_MorseSITL::update(), AP_Proximity_SITL::update(), AP_Proximity_TeraRangerTowerEvo::update_sector_data(), and AP_Proximity_TeraRangerTower::update_sector_data().
update_locations()
void AP_Proximity_Backend::update_locations () protected
Definition at line 354 of file AP_Proximity_Backend.cpp.
Referenced by init_boundary(), and update_boundary_for_sector().
Member Data Documentation
_angle
float AP_Proximity_Backend::_angle[PROXIMITY_SECTORS_MAX] protected
Definition at line 107 of file AP_Proximity_Backend.h.
Referenced by get_closest_object(), get_horizontal_distances(), get_object_angle_and_distance(), AP_Proximity_MAV::handle_msg(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::process_reply(), AP_Proximity_RangeFinder::update(), AP_Proximity_MorseSITL::update(), AP_Proximity_SITL::update(), AP_Proximity_TeraRangerTower::update_sector_data(), and AP_Proximity_TeraRangerTowerEvo::update_sector_data().
_boundary_point
Vector2f AP_Proximity_Backend::_boundary_point[PROXIMITY_SECTORS_MAX] protected
Definition at line 113 of file AP_Proximity_Backend.h.
Referenced by get_boundary_points(), init_boundary(), and update_boundary_for_sector().
_distance
float AP_Proximity_Backend::_distance[PROXIMITY_SECTORS_MAX] protected
Definition at line 108 of file AP_Proximity_Backend.h.
Referenced by get_closest_object(), get_horizontal_distance(), get_horizontal_distances(), get_object_angle_and_distance(), AP_Proximity_MAV::handle_msg(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::process_reply(), AP_Proximity_RangeFinder::update(), AP_Proximity_MorseSITL::update(), AP_Proximity_SITL::update(), update_boundary_for_sector(), AP_Proximity_TeraRangerTower::update_sector_data(), and AP_Proximity_TeraRangerTowerEvo::update_sector_data().
_distance_valid
bool AP_Proximity_Backend::_distance_valid[PROXIMITY_SECTORS_MAX] protected
Definition at line 109 of file AP_Proximity_Backend.h.
Referenced by get_boundary_points(), get_closest_object(), get_horizontal_distance(), get_horizontal_distances(), get_object_angle_and_distance(), AP_Proximity_MAV::handle_msg(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::process_reply(), AP_Proximity_RangeFinder::update(), AP_Proximity_MorseSITL::update(), AP_Proximity_SITL::update(), update_boundary_for_sector(), AP_Proximity_TeraRangerTower::update_sector_data(), and AP_Proximity_TeraRangerTowerEvo::update_sector_data().
_location_count
uint16_t AP_Proximity_Backend::_location_count protected
Definition at line 116 of file AP_Proximity_Backend.h.
Referenced by copy_locations(), and update_locations().
_locations
AP_Proximity::Proximity_Location AP_Proximity_Backend::_locations[PROXIMITY_SECTORS_MAX] protected
Definition at line 117 of file AP_Proximity_Backend.h.
Referenced by copy_locations(), and update_locations().
_num_sectors
uint8_t AP_Proximity_Backend::_num_sectors = PROXIMITY_MAX_DIRECTION protected
Definition at line 102 of file AP_Proximity_Backend.h.
Referenced by convert_angle_to_sector(), get_boundary_points(), get_closest_object(), get_horizontal_distances(), get_object_angle_and_distance(), get_object_count(), AP_Proximity_MAV::handle_msg(), init_boundary(), AP_Proximity_LightWareSF40C::init_sectors(), AP_Proximity_RPLidarA2::init_sectors(), AP_Proximity_LightWareSF40C::send_request_for_distance(), AP_Proximity_SITL::update(), and update_boundary_for_sector().
_rsem
HAL_Semaphore_Recursive AP_Proximity_Backend::_rsem protected
Definition at line 118 of file AP_Proximity_Backend.h.
Referenced by copy_locations(), and update_locations().
_sector_edge_vector
Vector2f AP_Proximity_Backend::_sector_edge_vector[PROXIMITY_SECTORS_MAX] protected
Definition at line 112 of file AP_Proximity_Backend.h.
Referenced by init_boundary(), and update_boundary_for_sector().
_sector_middle_deg
uint16_t AP_Proximity_Backend::_sector_middle_deg[PROXIMITY_SECTORS_MAX] = {0, 45, 90, 135, 180, 225, 270, 315, 0, 0, 0, 0} protected
Definition at line 103 of file AP_Proximity_Backend.h.
Referenced by convert_angle_to_sector(), AP_Proximity_MAV::handle_msg(), init_boundary(), AP_Proximity_LightWareSF40C::init_sectors(), AP_Proximity_RPLidarA2::init_sectors(), AP_Proximity_LightWareSF40C::send_request_for_distance(), and AP_Proximity_SITL::update().
_sector_width_deg
uint8_t AP_Proximity_Backend::_sector_width_deg[PROXIMITY_SECTORS_MAX] = {45, 45, 45, 45, 45, 45, 45, 45, 0, 0, 0, 0} protected
Definition at line 104 of file AP_Proximity_Backend.h.
Referenced by convert_angle_to_sector(), AP_Proximity_MAV::handle_msg(), init_boundary(), AP_Proximity_LightWareSF40C::init_sectors(), AP_Proximity_RPLidarA2::init_sectors(), and AP_Proximity_LightWareSF40C::send_request_for_distance().
frontend
AP_Proximity& AP_Proximity_Backend::frontend protected
Definition at line 98 of file AP_Proximity_Backend.h.
Referenced by get_ignore_area(), get_ignore_area_count(), get_next_ignore_start_or_end(), AP_Proximity_MAV::handle_msg(), AP_Proximity_LightWareSF40C::initialise(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::set_forward_direction(), AP_Proximity_LightWareSF40C::set_motor_direction(), and AP_Proximity_RangeFinder::update().
state
AP_Proximity::Proximity_State& AP_Proximity_Backend::state protected
Definition at line 99 of file AP_Proximity_Backend.h.
Referenced by get_boundary_points(), AP_Proximity_MAV::handle_msg(), AP_Proximity_LightWareSF40C::initialise(), AP_Proximity_RPLidarA2::parse_response_data(), AP_Proximity_LightWareSF40C::set_forward_direction(), AP_Proximity_LightWareSF40C::set_motor_direction(), and set_status().
The documentation for this class was generated from the following files:
libraries/AP_Proximity/AP_Proximity_Backend.h
libraries/AP_Proximity/AP_Proximity_Backend.cpp