APM:Libraries: AP_SBusOut Class Reference
AP_SBusOut Class Reference
#include <AP_SBusOut.h>
Public Member Functions
AP_SBusOut ()
AP_SBusOut (const AP_SBusOut &other)=delete
AP_SBusOut & operator= (const AP_SBusOut &)=delete
void update ()
Static Public Member Functions
static void sbus_format_frame (uint16_t *channels, uint8_t num_channels, uint8_t buffer[25])
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void init (void)
Private Attributes
AP_HAL::UARTDriver * sbus1_uart
uint16_t sbus_frame_interval
AP_Int16 sbus_rate
bool initialised
Detailed Description
Definition at line 13 of file AP_SBusOut.h.
Constructor & Destructor Documentation
AP_SBusOut() [1/2]
AP_SBusOut::AP_SBusOut (void)
Definition at line 71 of file AP_SBusOut.cpp.
AP_SBusOut() [2/2]
AP_SBusOut::AP_SBusOut (const AP_SBusOut & other) delete
Member Function Documentation
init()
void AP_SBusOut::init (void) private
Definition at line 170 of file AP_SBusOut.cpp.
Referenced by update().
operator=()
AP_SBusOut& AP_SBusOut::operator= (const AP_SBusOut &) delete
sbus_format_frame()
void AP_SBusOut::sbus_format_frame (uint16_t * channels, uint8_t num_channels, uint8_t buffer[25]) static
Definition at line 80 of file AP_SBusOut.cpp.
Referenced by sbus_out_write(), and update().
update()
void AP_SBusOut::update (void)
Definition at line 123 of file AP_SBusOut.cpp.
Referenced by SRV_Channels::push().
Member Data Documentation
initialised
bool AP_SBusOut::initialised private
Definition at line 37 of file AP_SBusOut.h.
Referenced by update().
sbus1_uart
AP_HAL::UARTDriver* AP_SBusOut::sbus1_uart private
Definition at line 30 of file AP_SBusOut.h.
Referenced by init(), and update().
sbus_frame_interval
uint16_t AP_SBusOut::sbus_frame_interval private
Definition at line 34 of file AP_SBusOut.h.
Referenced by init(), and update().
sbus_rate
AP_Int16 AP_SBusOut::sbus_rate private
Definition at line 36 of file AP_SBusOut.h.
Referenced by init().
var_info
const AP_Param::GroupInfo AP_SBusOut::var_info static
Initial value:
= {
    AP_GROUPINFO("RATE",  1, AP_SBusOut, sbus_rate, 50),
    AP_GROUPEND
}
Definition at line 21 of file AP_SBusOut.h.
Referenced by AP_SBusOut().
The documentation for this class was generated from the following files:
libraries/AP_SBusOut/AP_SBusOut.h
libraries/AP_SBusOut/AP_SBusOut.cpp