APM:Libraries: AP_MotorsHeli_RSC Class Reference
AP_MotorsHeli_RSC Class Reference
#include <AP_MotorsHeli_RSC.h>
Public Member Functions
AP_MotorsHeli_RSC (SRV_Channel::Aux_servo_function_t aux_fn, uint8_t default_channel)
void init_servo ()
void set_control_mode (RotorControlMode mode)
void set_critical_speed (float critical_speed)
float get_critical_speed () const
float get_idle_output ()
void set_idle_output (float idle_output)
void set_governor_disengage (float governor_disengage)
void set_governor_droop_response (float governor_droop_response)
void set_governor_output (float governor_output)
void set_governor_reference (float governor_reference)
void set_governor_range (float governor_range)
void set_governor_thrcurve (float governor_thrcurve)
float get_desired_speed () const
void set_desired_speed (float desired_speed)
float get_control_output () const
float get_rotor_speed () const
void set_rotor_rpm (float rotor_rpm)
float get_governor_output () const
bool is_runup_complete () const
void set_ramp_time (int8_t ramp_time)
void set_runup_time (int8_t runup_time)
void set_slewrate (int16_t slewrate)
void set_throttle_curve (float thrcrv[5])
void set_collective (float collective)
void output (RotorControlState state)
Private Member Functions
void update_rotor_ramp (float rotor_ramp_input, float dt)
void update_rotor_runup (float dt)
void write_rsc (float servo_out)
float calculate_desired_throttle (float collective_in)
Private Attributes
uint64_t _last_update_us
SRV_Channel::Aux_servo_function_t _aux_fn
uint8_t _default_channel
RotorControlMode _control_mode = ROTOR_CONTROL_MODE_DISABLED
float _critical_speed
float _idle_output
float _desired_speed
float _control_output
float _rotor_ramp_output
float _rotor_runup_output
int8_t _ramp_time
int8_t _runup_time
bool _runup_complete
float _thrcrv_poly [4][4]
uint16_t _power_slewrate
float _collective_in
float _rotor_rpm
float _governor_disengage
float _governor_output
float _governor_range
float _governor_reference
float _governor_droop_response
bool _governor_engage
float _governor_thrcurve
Friends
class AP_MotorsHeli_Single
class AP_MotorsHeli_Dual
class AP_MotorsHeli_Quad
Detailed Description
Definition at line 38 of file AP_MotorsHeli_RSC.h.
Constructor & Destructor Documentation
AP_MotorsHeli_RSC()
AP_MotorsHeli_RSC::AP_MotorsHeli_RSC (SRV_Channel::Aux_servo_function_t aux_fn, uint8_t default_channel) inline
Definition at line 44 of file AP_MotorsHeli_RSC.h.
Member Function Documentation
calculate_desired_throttle()
float AP_MotorsHeli_RSC::calculate_desired_throttle (float collective_in) private
Definition at line 345 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
get_control_output()
float AP_MotorsHeli_RSC::get_control_output () const inline
Definition at line 81 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::get_control_output(), AP_MotorsHeli_Single::get_control_output(), AP_MotorsHeli_Dual::get_control_output(), and AP_MotorsHeli_Single::move_actuators().
get_critical_speed()
float AP_MotorsHeli_RSC::get_critical_speed () const inline
Definition at line 60 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::rotor_speed_above_critical(), AP_MotorsHeli_Single::rotor_speed_above_critical(), and AP_MotorsHeli_Dual::rotor_speed_above_critical().
get_desired_speed()
float AP_MotorsHeli_RSC::get_desired_speed () const inline
Definition at line 75 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::get_desired_rotor_speed().
get_governor_output()
float AP_MotorsHeli_RSC::get_governor_output () const inline
Definition at line 90 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::get_governor_output(), AP_MotorsHeli_Single::get_governor_output(), and AP_MotorsHeli_Dual::get_governor_output().
get_idle_output()
float AP_MotorsHeli_RSC::get_idle_output () inline
Definition at line 63 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::move_actuators().
get_rotor_speed()
float AP_MotorsHeli_RSC::get_rotor_speed () const
Definition at line 325 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Quad::get_desired_rotor_speed(), AP_MotorsHeli_Dual::get_desired_rotor_speed(), AP_MotorsHeli_Quad::get_main_rotor_speed(), AP_MotorsHeli_Single::get_main_rotor_speed(), AP_MotorsHeli_Dual::get_main_rotor_speed(), AP_MotorsHeli_Quad::rotor_speed_above_critical(), AP_MotorsHeli_Single::rotor_speed_above_critical(), AP_MotorsHeli_Dual::rotor_speed_above_critical(), and update_rotor_runup().
init_servo()
void AP_MotorsHeli_RSC::init_servo ()
Definition at line 138 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Quad::init_outputs(), AP_MotorsHeli_Dual::init_outputs(), and AP_MotorsHeli_Single::init_outputs().
is_runup_complete()
bool AP_MotorsHeli_RSC::is_runup_complete () const inline
Definition at line 93 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::update_motor_control(), AP_MotorsHeli_Dual::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
output()
void AP_MotorsHeli_RSC::output (RotorControlState state)
Definition at line 163 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Quad::update_motor_control(), AP_MotorsHeli_Dual::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
set_collective()
void AP_MotorsHeli_RSC::set_collective (float collective) inline
Definition at line 108 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::move_actuators(), AP_MotorsHeli_Single::move_actuators(), and AP_MotorsHeli_Dual::move_actuators().
set_control_mode()
void AP_MotorsHeli_RSC::set_control_mode (RotorControlMode mode) inline
Definition at line 54 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_scalars(), AP_MotorsHeli_Single::calculate_scalars(), and AP_MotorsHeli_Dual::calculate_scalars().
set_critical_speed()
void AP_MotorsHeli_RSC::set_critical_speed (float critical_speed) inline
Definition at line 57 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), AP_MotorsHeli_Dual::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_scalars().
set_desired_speed()
void AP_MotorsHeli_RSC::set_desired_speed (float desired_speed) inline
Definition at line 78 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::set_desired_rotor_speed(), AP_MotorsHeli_Single::set_desired_rotor_speed(), and AP_MotorsHeli_Dual::set_desired_rotor_speed().
set_governor_disengage()
void AP_MotorsHeli_RSC::set_governor_disengage (float governor_disengage) inline
Definition at line 67 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_governor_droop_response()
void AP_MotorsHeli_RSC::set_governor_droop_response (float governor_droop_response) inline
Definition at line 68 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_governor_output()
void AP_MotorsHeli_RSC::set_governor_output (float governor_output) inline
Definition at line 69 of file AP_MotorsHeli_RSC.h.
set_governor_range()
void AP_MotorsHeli_RSC::set_governor_range (float governor_range) inline
Definition at line 71 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_governor_reference()
void AP_MotorsHeli_RSC::set_governor_reference (float governor_reference) inline
Definition at line 70 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_governor_thrcurve()
void AP_MotorsHeli_RSC::set_governor_thrcurve (float governor_thrcurve) inline
Definition at line 72 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_idle_output()
void AP_MotorsHeli_RSC::set_idle_output (float idle_output) inline
Definition at line 64 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), AP_MotorsHeli_Dual::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_scalars().
set_ramp_time()
void AP_MotorsHeli_RSC::set_ramp_time (int8_t ramp_time) inline
Definition at line 96 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), AP_MotorsHeli_Dual::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_scalars().
set_rotor_rpm()
void AP_MotorsHeli_RSC::set_rotor_rpm (float rotor_rpm) inline
Definition at line 87 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::set_rpm(), AP_MotorsHeli_Dual::set_rpm(), and AP_MotorsHeli_Single::set_rpm().
set_runup_time()
void AP_MotorsHeli_RSC::set_runup_time (int8_t runup_time) inline
Definition at line 99 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), AP_MotorsHeli_Dual::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_scalars().
set_slewrate()
void AP_MotorsHeli_RSC::set_slewrate (int16_t slewrate) inline
Definition at line 102 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_throttle_curve()
void AP_MotorsHeli_RSC::set_throttle_curve (float thrcrv[5])
Definition at line 150 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
update_rotor_ramp()
void AP_MotorsHeli_RSC::update_rotor_ramp (float rotor_ramp_input, float dt) private
Definition at line 256 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
update_rotor_runup()
void AP_MotorsHeli_RSC::update_rotor_runup (float dt) private
Definition at line 281 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
write_rsc()
void AP_MotorsHeli_RSC::write_rsc (float servo_out) private
Definition at line 333 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
Friends And Related Function Documentation
AP_MotorsHeli_Dual
friend class AP_MotorsHeli_Dual friend
Definition at line 41 of file AP_MotorsHeli_RSC.h.
AP_MotorsHeli_Quad
friend class AP_MotorsHeli_Quad friend
Definition at line 42 of file AP_MotorsHeli_RSC.h.
AP_MotorsHeli_Single
friend class AP_MotorsHeli_Single friend
Definition at line 40 of file AP_MotorsHeli_RSC.h.
Member Data Documentation
_aux_fn
SRV_Channel::Aux_servo_function_t AP_MotorsHeli_RSC::_aux_fn private
Definition at line 117 of file AP_MotorsHeli_RSC.h.
Referenced by init_servo(), and write_rsc().
_collective_in
float AP_MotorsHeli_RSC::_collective_in private
Definition at line 133 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_collective().
_control_mode
RotorControlMode AP_MotorsHeli_RSC::_control_mode = ROTOR_CONTROL_MODE_DISABLED private
Definition at line 121 of file AP_MotorsHeli_RSC.h.
Referenced by output(), set_control_mode(), update_rotor_runup(), and write_rsc().
_control_output
float AP_MotorsHeli_RSC::_control_output private
Definition at line 125 of file AP_MotorsHeli_RSC.h.
Referenced by get_control_output(), and output().
_critical_speed
float AP_MotorsHeli_RSC::_critical_speed private
Definition at line 122 of file AP_MotorsHeli_RSC.h.
Referenced by get_critical_speed(), set_critical_speed(), and update_rotor_runup().
_default_channel
uint8_t AP_MotorsHeli_RSC::_default_channel private
Definition at line 118 of file AP_MotorsHeli_RSC.h.
Referenced by init_servo().
_desired_speed
float AP_MotorsHeli_RSC::_desired_speed private
Definition at line 124 of file AP_MotorsHeli_RSC.h.
Referenced by get_desired_speed(), output(), and set_desired_speed().
_governor_disengage
float AP_MotorsHeli_RSC::_governor_disengage private
Definition at line 135 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_governor_disengage().
_governor_droop_response
float AP_MotorsHeli_RSC::_governor_droop_response private
Definition at line 139 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_governor_droop_response().
_governor_engage
bool AP_MotorsHeli_RSC::_governor_engage private
Definition at line 140 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_governor_output
float AP_MotorsHeli_RSC::_governor_output private
Definition at line 136 of file AP_MotorsHeli_RSC.h.
Referenced by get_governor_output(), output(), and set_governor_output().
_governor_range
float AP_MotorsHeli_RSC::_governor_range private
Definition at line 137 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_governor_range().
_governor_reference
float AP_MotorsHeli_RSC::_governor_reference private
Definition at line 138 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_governor_reference().
_governor_thrcurve
float AP_MotorsHeli_RSC::_governor_thrcurve private
Definition at line 141 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_governor_thrcurve().
_idle_output
float AP_MotorsHeli_RSC::_idle_output private
Definition at line 123 of file AP_MotorsHeli_RSC.h.
Referenced by get_idle_output(), output(), and set_idle_output().
_last_update_us
uint64_t AP_MotorsHeli_RSC::_last_update_us private
Definition at line 114 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_power_slewrate
uint16_t AP_MotorsHeli_RSC::_power_slewrate private
Definition at line 132 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_slewrate().
_ramp_time
int8_t AP_MotorsHeli_RSC::_ramp_time private
Definition at line 128 of file AP_MotorsHeli_RSC.h.
Referenced by set_ramp_time(), update_rotor_ramp(), and update_rotor_runup().
_rotor_ramp_output
float AP_MotorsHeli_RSC::_rotor_ramp_output private
Definition at line 126 of file AP_MotorsHeli_RSC.h.
Referenced by output(), update_rotor_ramp(), and update_rotor_runup().
_rotor_rpm
float AP_MotorsHeli_RSC::_rotor_rpm private
Definition at line 134 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_rotor_rpm().
_rotor_runup_output
float AP_MotorsHeli_RSC::_rotor_runup_output private
Definition at line 127 of file AP_MotorsHeli_RSC.h.
Referenced by get_rotor_speed(), update_rotor_ramp(), and update_rotor_runup().
_runup_complete
bool AP_MotorsHeli_RSC::_runup_complete private
Definition at line 130 of file AP_MotorsHeli_RSC.h.
Referenced by is_runup_complete(), and update_rotor_runup().
_runup_time
int8_t AP_MotorsHeli_RSC::_runup_time private
Definition at line 129 of file AP_MotorsHeli_RSC.h.
Referenced by set_runup_time(), and update_rotor_runup().
_thrcrv_poly
float AP_MotorsHeli_RSC::_thrcrv_poly[4][4] private
Definition at line 131 of file AP_MotorsHeli_RSC.h.
Referenced by calculate_desired_throttle(), and set_throttle_curve().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp