APM:Libraries: AP_HAL::I2CDeviceManager Class Reference
AP_HAL::I2CDeviceManager Class Reference abstract
#include <I2CDevice.h>
Public Member Functions
virtual OwnPtr< AP_HAL::I2CDevice > get_device (uint8_t bus, uint8_t address, uint32_t bus_clock=400000, bool use_smbus=false, uint32_t timeout_ms=4)=0
virtual OwnPtr< I2CDevice > get_device (std::vector< const char * > devpaths, uint8_t address)
virtual uint32_t get_bus_mask (void) const
virtual uint32_t get_bus_mask_external (void) const
virtual uint32_t get_bus_mask_internal (void) const
Detailed Description
Definition at line 72 of file I2CDevice.h.
Member Function Documentation
get_bus_mask()
virtual uint32_t AP_HAL::I2CDeviceManager::get_bus_mask (void) const inline virtual
Reimplemented in ChibiOS::I2CDeviceManager, and Linux::I2CDeviceManager.
Definition at line 96 of file I2CDevice.h.
get_bus_mask_external()
virtual uint32_t AP_HAL::I2CDeviceManager::get_bus_mask_external (void) const inline virtual
Reimplemented in ChibiOS::I2CDeviceManager, and Linux::I2CDeviceManager.
Definition at line 101 of file I2CDevice.h.
Referenced by AP_Baro::_probe_i2c_barometers().
get_bus_mask_internal()
virtual uint32_t AP_HAL::I2CDeviceManager::get_bus_mask_internal (void) const inline virtual
Reimplemented in ChibiOS::I2CDeviceManager, and Linux::I2CDeviceManager.
Definition at line 106 of file I2CDevice.h.
Referenced by AP_Baro::_probe_i2c_barometers().
get_device() [1/2]
virtual OwnPtr<AP_HAL::I2CDevice> AP_HAL::I2CDeviceManager::get_device (uint8_t bus, uint8_t address, uint32_t bus_clock = 400000, bool use_smbus = false, uint32_t timeout_ms = 4) pure virtual
Implemented in ChibiOS::I2CDeviceManager, Linux::I2CDeviceManager, and Empty::I2CDeviceManager.
Referenced by AP_Baro::_probe_i2c_barometers(), AP_InertialSensor::detect_backends(), RangeFinder::detect_instance(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), ToshibaLED_I2C::hw_init(), PCA9685LED_I2C::hw_init(), NCP5623::hw_init(), AP_IRLock_I2C::init(), TSYS01::init(), Display::init(), AP_ADC_ADS1115::init(), OreoLED_I2C::init(), AP_Airspeed_DLVR::init(), AP_Airspeed_MS4525::init(), Linux::OpticalFlow_Onboard::init(), AP_Airspeed_SDP3X::init(), AP_Airspeed_MS5525::init(), AP_Baro::init(), AP_BattMonitor::init(), AP_OpticalFlow_PX4Flow::scan_buses(), and setup().
get_device() [2/2]
virtual OwnPtr<I2CDevice> AP_HAL::I2CDeviceManager::get_device (std::vector< const char * > devpaths, uint8_t address) inline virtual
Reimplemented in Linux::I2CDeviceManager.
Definition at line 87 of file I2CDevice.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/I2CDevice.h