APM:Libraries: AP_RPM Class Reference
AP_RPM Class Reference
#include <AP_RPM.h>
Classes
struct RPM_State
Public Types
enum RPM_Type { RPM_TYPE_NONE = 0, RPM_TYPE_PX4_PWM = 1, RPM_TYPE_PIN = 2 }
Public Member Functions
AP_RPM ()
AP_RPM (const AP_RPM &other)=delete
AP_RPM & operator= (const AP_RPM &)=delete
uint8_t num_sensors (void) const
void init (void)
void update (void)
float get_rpm (uint8_t instance) const
float get_signal_quality (uint8_t instance) const
bool healthy (uint8_t instance) const
bool enabled (uint8_t instance) const
Static Public Member Functions
static AP_RPM * get_singleton ()
Public Attributes
AP_Int8 _type [RPM_MAX_INSTANCES]
AP_Int8 _pin [RPM_MAX_INSTANCES]
AP_Float _scaling [RPM_MAX_INSTANCES]
AP_Float _maximum [RPM_MAX_INSTANCES]
AP_Float _minimum [RPM_MAX_INSTANCES]
AP_Float _quality_min [RPM_MAX_INSTANCES]
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void detect_instance (uint8_t instance)
Private Attributes
RPM_State state [RPM_MAX_INSTANCES]
AP_RPM_Backend * drivers [RPM_MAX_INSTANCES]
uint8_t num_instances:2
Static Private Attributes
static AP_RPM * _singleton
Friends
class AP_RPM_Backend
Detailed Description
Definition at line 27 of file AP_RPM.h.
Member Enumeration Documentation
RPM_Type
enum AP_RPM::RPM_Type
Enumerator
RPM_TYPE_NONE
RPM_TYPE_PX4_PWM
RPM_TYPE_PIN
Definition at line 39 of file AP_RPM.h.
Constructor & Destructor Documentation
AP_RPM() [1/2]
AP_RPM::AP_RPM (void)
Definition at line 92 of file AP_RPM.cpp.
AP_RPM() [2/2]
AP_RPM::AP_RPM (const AP_RPM & other) delete
Member Function Documentation
detect_instance()
void AP_RPM::detect_instance (uint8_t instance) private
enabled()
bool AP_RPM::enabled (uint8_t instance) const
Definition at line 170 of file AP_RPM.cpp.
Referenced by loop(), and GCS_MAVLINK::send_rpm().
get_rpm()
float AP_RPM::get_rpm (uint8_t instance) const inline
Definition at line 77 of file AP_RPM.h.
Referenced by loop(), GCS_MAVLINK::send_rpm(), AP_ICEngine::update(), AP_WindVane_RPM::update_speed(), and AP_Logger::Write_RPM().
get_signal_quality()
float AP_RPM::get_signal_quality (uint8_t instance) const inline
Definition at line 87 of file AP_RPM.h.
Referenced by loop().
get_singleton()
static AP_RPM* AP_RPM::get_singleton (void) inline static
Definition at line 95 of file AP_RPM.h.
Referenced by AP::rpm(), and AP_WindVane_RPM::update_speed().
healthy()
bool AP_RPM::healthy (uint8_t instance) const
Definition at line 153 of file AP_RPM.cpp.
Referenced by get_rpm(), loop(), and AP_ICEngine::update().
init()
void AP_RPM::init (void)
Definition at line 105 of file AP_RPM.cpp.
Referenced by setup().
num_sensors()
uint8_t AP_RPM::num_sensors (void) const inline
Definition at line 64 of file AP_RPM.h.
Referenced by loop(), and setup().
operator=()
AP_RPM& AP_RPM::operator= (const AP_RPM &) delete
update()
void AP_RPM::update (void)
Definition at line 135 of file AP_RPM.cpp.
Referenced by loop().
Friends And Related Function Documentation
AP_RPM_Backend
friend class AP_RPM_Backend friend
Definition at line 29 of file AP_RPM.h.
Member Data Documentation
_maximum
AP_Float AP_RPM::_maximum[RPM_MAX_INSTANCES]
Definition at line 57 of file AP_RPM.h.
Referenced by AP_RPM_Pin::update().
_minimum
AP_Float AP_RPM::_minimum[RPM_MAX_INSTANCES]
Definition at line 58 of file AP_RPM.h.
Referenced by AP_RPM_Pin::update().
_pin
AP_Int8 AP_RPM::_pin[RPM_MAX_INSTANCES]
Definition at line 55 of file AP_RPM.h.
Referenced by AP_RPM_Backend::get_pin().
_quality_min
AP_Float AP_RPM::_quality_min[RPM_MAX_INSTANCES]
Definition at line 59 of file AP_RPM.h.
Referenced by healthy().
_scaling
AP_Float AP_RPM::_scaling[RPM_MAX_INSTANCES]
Definition at line 56 of file AP_RPM.h.
Referenced by AP_RPM_Pin::update(), and AP_RPM_SITL::update().
_singleton
AP_RPM * AP_RPM::_singleton static private
Definition at line 98 of file AP_RPM.h.
Referenced by AP_RPM(), and get_singleton().
_type
AP_Int8 AP_RPM::_type[RPM_MAX_INSTANCES]
Definition at line 54 of file AP_RPM.h.
Referenced by enabled(), healthy(), init(), and update().
drivers
AP_RPM_Backend* AP_RPM::drivers[RPM_MAX_INSTANCES] private
Definition at line 101 of file AP_RPM.h.
Referenced by init(), and update().
num_instances
uint8_t AP_RPM::num_instances private
Definition at line 102 of file AP_RPM.h.
Referenced by enabled(), healthy(), init(), num_sensors(), and update().
state
RPM_State AP_RPM::state[RPM_MAX_INSTANCES] private
Definition at line 100 of file AP_RPM.h.
Referenced by get_rpm(), get_signal_quality(), healthy(), init(), and update().
var_info
const AP_Param::GroupInfo AP_RPM::var_info static
Definition at line 61 of file AP_RPM.h.
Referenced by AP_RPM().
The documentation for this class was generated from the following files:
libraries/AP_RPM/AP_RPM.h
libraries/AP_RPM/AP_RPM.cpp