APM:Libraries: MAVLink_routing Class Reference
MAVLink_routing Class Reference
#include <MAVLink_routing.h>
Classes
struct route
Public Member Functions
MAVLink_routing (void)
bool check_and_forward (mavlink_channel_t in_channel, const mavlink_message_t *msg)
void send_to_components (const mavlink_message_t *msg)
bool find_by_mavtype (uint8_t mavtype, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
Private Member Functions
void learn_route (mavlink_channel_t in_channel, const mavlink_message_t *msg)
void get_targets (const mavlink_message_t *msg, int16_t &sysid, int16_t &compid)
void handle_heartbeat (mavlink_channel_t in_channel, const mavlink_message_t *msg)
Private Attributes
uint8_t num_routes
struct MAVLink_routing::route routes [MAVLINK_MAX_ROUTES]
uint8_t no_route_mask
Friends
class GCS_MAVLINK
Detailed Description
Definition at line 16 of file MAVLink_routing.h.
Constructor & Destructor Documentation
MAVLink_routing()
MAVLink_routing::MAVLink_routing (void)
Definition at line 30 of file MAVLink_routing.cpp.
Member Function Documentation
check_and_forward()
bool MAVLink_routing::check_and_forward (mavlink_channel_t in_channel, const mavlink_message_t * msg)
Definition at line 91 of file MAVLink_routing.cpp.
Referenced by loop(), and GCS_MAVLINK::packetReceived().
find_by_mavtype()
bool MAVLink_routing::find_by_mavtype (uint8_t mavtype, uint8_t & sysid, uint8_t & compid, mavlink_channel_t & channel)
Definition at line 215 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::find_by_mavtype().
get_targets()
void MAVLink_routing::get_targets (const mavlink_message_t * msg, int16_t & sysid, int16_t & compid) private
Definition at line 323 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
handle_heartbeat()
void MAVLink_routing::handle_heartbeat (mavlink_channel_t in_channel, const mavlink_message_t * msg) private
Definition at line 275 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
learn_route()
void MAVLink_routing::learn_route (mavlink_channel_t in_channel, const mavlink_message_t * msg) private
Definition at line 234 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
send_to_components()
void MAVLink_routing::send_to_components (const mavlink_message_t * msg)
Definition at line 187 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::send_to_components().
Friends And Related Function Documentation
GCS_MAVLINK
friend class GCS_MAVLINK friend
Definition at line 18 of file MAVLink_routing.h.
Member Data Documentation
no_route_mask
uint8_t MAVLink_routing::no_route_mask private
Definition at line 56 of file MAVLink_routing.h.
Referenced by GCS_MAVLINK::disable_channel_routing(), and handle_heartbeat().
num_routes
uint8_t MAVLink_routing::num_routes private
Definition at line 47 of file MAVLink_routing.h.
Referenced by check_and_forward(), find_by_mavtype(), handle_heartbeat(), learn_route(), and send_to_components().
routes
struct MAVLink_routing::route MAVLink_routing::routes[MAVLINK_MAX_ROUTES] private
Referenced by check_and_forward(), find_by_mavtype(), handle_heartbeat(), learn_route(), and send_to_components().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/MAVLink_routing.h
libraries/GCS_MAVLink/MAVLink_routing.cpp