APM:Libraries: AP_RCProtocol_Backend Class Reference
AP_RCProtocol_Backend Class Reference
#include <AP_RCProtocol_Backend.h>
Public Types
enum { PARSE_TYPE_SIGREAD, PARSE_TYPE_SERIAL }
Public Member Functions
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_pulse (uint32_t width_s0, uint32_t width_s1)
virtual void process_byte (uint8_t byte, uint32_t baudrate)
uint16_t read (uint8_t chan)
bool new_input ()
uint8_t num_channels ()
virtual void start_bind (void)
virtual void update (void)
uint32_t get_rc_frame_count (void) const
uint32_t get_rc_input_count (void) const
Protected Member Functions
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe)
Private Attributes
AP_RCProtocol & frontend
uint32_t rc_input_count
uint32_t last_rc_input_count
uint32_t rc_frame_count
uint16_t _pwm_values [MAX_RCIN_CHANNELS]
uint8_t _num_channels
Friends
class AP_RCProtcol
Detailed Description
Definition at line 22 of file AP_RCProtocol_Backend.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PARSE_TYPE_SIGREAD
PARSE_TYPE_SERIAL
Definition at line 39 of file AP_RCProtocol_Backend.h.
Constructor & Destructor Documentation
AP_RCProtocol_Backend()
AP_RCProtocol_Backend::AP_RCProtocol_Backend (AP_RCProtocol & _frontend)
Definition at line 23 of file AP_RCProtocol_Backend.cpp.
~AP_RCProtocol_Backend()
virtual AP_RCProtocol_Backend::~AP_RCProtocol_Backend () inline virtual
Definition at line 27 of file AP_RCProtocol_Backend.h.
Member Function Documentation
add_input()
void AP_RCProtocol_Backend::add_input (uint8_t num_channels, uint16_t * values, bool in_failsafe) protected
Definition at line 52 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol_SBUS::_process_byte(), AP_RCProtocol_IBUS::_process_byte(), AP_RCProtocol_SUMD::_process_byte(), AP_RCProtocol_DSM::_process_byte(), AP_RCProtocol_SRXL::_process_byte(), and AP_RCProtocol_PPMSum::process_pulse().
get_rc_frame_count()
uint32_t AP_RCProtocol_Backend::get_rc_frame_count (void) const inline
Definition at line 45 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_byte(), and AP_RCProtocol::process_pulse().
get_rc_input_count()
uint32_t AP_RCProtocol_Backend::get_rc_input_count (void) const inline
Definition at line 50 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_byte(), and AP_RCProtocol::process_pulse().
new_input()
bool AP_RCProtocol_Backend::new_input (void)
Definition at line 30 of file AP_RCProtocol_Backend.cpp.
num_channels()
uint8_t AP_RCProtocol_Backend::num_channels (void)
Definition at line 39 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol::num_channels().
process_byte()
virtual void AP_RCProtocol_Backend::process_byte (uint8_t byte, uint32_t baudrate) inline virtual
Reimplemented in AP_RCProtocol_SRXL, AP_RCProtocol_ST24, AP_RCProtocol_IBUS, AP_RCProtocol_DSM, AP_RCProtocol_SUMD, and AP_RCProtocol_SBUS.
Definition at line 29 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_byte().
process_pulse()
virtual void AP_RCProtocol_Backend::process_pulse (uint32_t width_s0, uint32_t width_s1) inline virtual
Reimplemented in AP_RCProtocol_SRXL, AP_RCProtocol_ST24, AP_RCProtocol_IBUS, AP_RCProtocol_DSM, AP_RCProtocol_SUMD, AP_RCProtocol_SBUS, and AP_RCProtocol_PPMSum.
Definition at line 28 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_pulse().
read()
uint16_t AP_RCProtocol_Backend::read (uint8_t chan)
Definition at line 44 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol::read().
start_bind()
virtual void AP_RCProtocol_Backend::start_bind (void) inline virtual
Reimplemented in AP_RCProtocol_DSM.
Definition at line 35 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::start_bind().
update()
virtual void AP_RCProtocol_Backend::update (void) inline virtual
Reimplemented in AP_RCProtocol_DSM.
Definition at line 38 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::new_input().
Friends And Related Function Documentation
AP_RCProtcol
friend class AP_RCProtcol friend
Definition at line 23 of file AP_RCProtocol_Backend.h.
Member Data Documentation
_num_channels
uint8_t AP_RCProtocol_Backend::_num_channels private
Definition at line 64 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), and num_channels().
_pwm_values
uint16_t AP_RCProtocol_Backend::_pwm_values[MAX_RCIN_CHANNELS] private
Definition at line 63 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), and read().
frontend
AP_RCProtocol& AP_RCProtocol_Backend::frontend private
Definition at line 58 of file AP_RCProtocol_Backend.h.
last_rc_input_count
uint32_t AP_RCProtocol_Backend::last_rc_input_count private
Definition at line 60 of file AP_RCProtocol_Backend.h.
Referenced by new_input().
rc_frame_count
uint32_t AP_RCProtocol_Backend::rc_frame_count private
Definition at line 61 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), and get_rc_frame_count().
rc_input_count
uint32_t AP_RCProtocol_Backend::rc_input_count private
Definition at line 59 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), get_rc_input_count(), and new_input().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_Backend.h
libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp