APM:Libraries: AP_Beacon Class Reference
AP_Beacon Class Reference
#include <AP_Beacon.h>
Classes
struct BeaconState
Public Types
enum AP_BeaconType { AP_BeaconType_None = 0, AP_BeaconType_Pozyx = 1, AP_BeaconType_Marvelmind = 2, AP_BeaconType_SITL = 10 }
Public Member Functions
AP_Beacon (AP_SerialManager &_serial_manager)
void init (void)
bool enabled (void)
bool healthy (void)
void update (void)
bool get_origin (Location &origin_loc) const
bool get_vehicle_position_ned (Vector3f &pos, float &accuracy_estimate) const
uint8_t count () const
bool get_beacon_data (uint8_t beacon_instance, struct BeaconState &state) const
uint8_t beacon_id (uint8_t beacon_instance) const
bool beacon_healthy (uint8_t beacon_instance) const
float beacon_distance (uint8_t beacon_instance) const
Vector3f beacon_position (uint8_t beacon_instance) const
uint32_t beacon_last_update_ms (uint8_t beacon_instance) const
void update_boundary_points ()
const Vector2f * get_boundary_points (uint16_t &num_points) const
Static Public Member Functions
static AP_Beacon * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool device_ready (void) const
Static Private Member Functions
static bool get_next_boundary_point (const Vector2f *boundary, uint8_t num_points, uint8_t current_index, float start_angle, uint8_t &next_index, float &next_angle)
Private Attributes
AP_Int8 _type
AP_Float origin_lat
AP_Float origin_lon
AP_Float origin_alt
AP_Int16 orient_yaw
AP_Beacon_Backend * _driver
AP_SerialManager & serial_manager
Vector3f veh_pos_ned
float veh_pos_accuracy
uint32_t veh_pos_update_ms
uint8_t num_beacons = 0
BeaconState beacon_state [AP_BEACON_MAX_BEACONS]
Vector2f boundary [AP_BEACON_MAX_BEACONS+1]
uint8_t boundary_num_points
uint8_t boundary_num_beacons
Static Private Attributes
static AP_Beacon * _singleton
Friends
class AP_Beacon_Backend
Detailed Description
Definition at line 30 of file AP_Beacon.h.
Member Enumeration Documentation
AP_BeaconType
enum AP_Beacon::AP_BeaconType
Enumerator
AP_BeaconType_None
AP_BeaconType_Pozyx
AP_BeaconType_Marvelmind
AP_BeaconType_SITL
Definition at line 41 of file AP_Beacon.h.
Constructor & Destructor Documentation
AP_Beacon()
AP_Beacon::AP_Beacon (AP_SerialManager & _serial_manager)
Definition at line 75 of file AP_Beacon.cpp.
Member Function Documentation
beacon_distance()
float AP_Beacon::beacon_distance (uint8_t beacon_instance) const
Definition at line 212 of file AP_Beacon.cpp.
Referenced by NavEKF2_core::readRngBcnData(), NavEKF3_core::readRngBcnData(), and AP_Logger::Write_Beacon().
beacon_healthy()
bool AP_Beacon::beacon_healthy (uint8_t beacon_instance) const
Definition at line 203 of file AP_Beacon.cpp.
Referenced by NavEKF2_core::readRngBcnData(), and NavEKF3_core::readRngBcnData().
beacon_id()
uint8_t AP_Beacon::beacon_id (uint8_t beacon_instance) const
Definition at line 194 of file AP_Beacon.cpp.
beacon_last_update_ms()
uint32_t AP_Beacon::beacon_last_update_ms (uint8_t beacon_instance) const
Definition at line 231 of file AP_Beacon.cpp.
Referenced by NavEKF2_core::readRngBcnData(), and NavEKF3_core::readRngBcnData().
beacon_position()
Vector3f AP_Beacon::beacon_position (uint8_t beacon_instance) const
Definition at line 221 of file AP_Beacon.cpp.
Referenced by NavEKF2_core::readRngBcnData(), NavEKF3_core::readRngBcnData(), and update_boundary_points().
count()
uint8_t AP_Beacon::count () const
Definition at line 175 of file AP_Beacon.cpp.
Referenced by NavEKF2_core::readRngBcnData(), NavEKF3_core::readRngBcnData(), and AP_Logger::Write_Beacon().
device_ready()
bool AP_Beacon::device_ready (void) const private
Definition at line 383 of file AP_Beacon.cpp.
Referenced by beacon_position(), count(), get_beacon_data(), get_boundary_points(), get_origin(), get_vehicle_position_ned(), healthy(), update(), and update_boundary_points().
enabled()
bool AP_Beacon::enabled (void)
Definition at line 109 of file AP_Beacon.cpp.
Referenced by AP_Logger::Write_Beacon().
get_beacon_data()
bool AP_Beacon::get_beacon_data (uint8_t beacon_instance, struct BeaconState & state) const
Definition at line 184 of file AP_Beacon.cpp.
get_boundary_points()
const Vector2f * AP_Beacon::get_boundary_points (uint16_t & num_points) const
Definition at line 371 of file AP_Beacon.cpp.
Referenced by AC_Avoid::adjust_velocity_beacon_fence().
get_next_boundary_point()
bool AP_Beacon::get_next_boundary_point (const Vector2f * boundary, uint8_t num_points, uint8_t current_index, float start_angle, uint8_t & next_index, float & next_angle) static private
Definition at line 331 of file AP_Beacon.cpp.
Referenced by update_boundary_points().
get_origin()
bool AP_Beacon::get_origin (Location & origin_loc) const
Definition at line 136 of file AP_Beacon.cpp.
Referenced by NavEKF2_core::readRngBcnData(), and NavEKF3_core::readRngBcnData().
get_singleton()
static AP_Beacon* AP_Beacon::get_singleton (void) inline static
Definition at line 38 of file AP_Beacon.h.
Referenced by AP::beacon().
get_vehicle_position_ned()
bool AP_Beacon::get_vehicle_position_ned (Vector3f & pos, float & accuracy_estimate) const
Definition at line 157 of file AP_Beacon.cpp.
Referenced by loop(), NavEKF2_core::readRngBcnData(), NavEKF3_core::readRngBcnData(), and AP_Logger::Write_Beacon().
healthy()
bool AP_Beacon::healthy (void)
Definition at line 115 of file AP_Beacon.cpp.
Referenced by beacon_distance(), and AP_Logger::Write_Beacon().
init()
void AP_Beacon::init (void)
Definition at line 88 of file AP_Beacon.cpp.
Referenced by setup().
update()
void AP_Beacon::update (void)
Definition at line 124 of file AP_Beacon.cpp.
Referenced by loop().
update_boundary_points()
void AP_Beacon::update_boundary_points ()
Definition at line 240 of file AP_Beacon.cpp.
Referenced by update().
Friends And Related Function Documentation
AP_Beacon_Backend
friend class AP_Beacon_Backend friend
Definition at line 33 of file AP_Beacon.h.
Member Data Documentation
_driver
AP_Beacon_Backend* AP_Beacon::_driver private
Definition at line 129 of file AP_Beacon.h.
Referenced by device_ready(), healthy(), init(), and update().
_singleton
AP_Beacon * AP_Beacon::_singleton static private
Definition at line 108 of file AP_Beacon.h.
Referenced by AP_Beacon(), and get_singleton().
_type
AP_Int8 AP_Beacon::_type private
Definition at line 122 of file AP_Beacon.h.
Referenced by beacon_last_update_ms(), device_ready(), enabled(), and init().
beacon_state
BeaconState AP_Beacon::beacon_state[AP_BEACON_MAX_BEACONS] private
Definition at line 139 of file AP_Beacon.h.
Referenced by beacon_distance(), beacon_healthy(), beacon_id(), beacon_last_update_ms(), beacon_position(), get_beacon_data(), AP_Beacon_Backend::set_beacon_distance(), and AP_Beacon_Backend::set_beacon_position().
boundary
Vector2f AP_Beacon::boundary[AP_BEACON_MAX_BEACONS+1] private
Definition at line 142 of file AP_Beacon.h.
Referenced by get_boundary_points(), and update_boundary_points().
boundary_num_beacons
uint8_t AP_Beacon::boundary_num_beacons private
Definition at line 144 of file AP_Beacon.h.
Referenced by update_boundary_points().
boundary_num_points
uint8_t AP_Beacon::boundary_num_points private
Definition at line 143 of file AP_Beacon.h.
Referenced by get_boundary_points(), and update_boundary_points().
num_beacons
uint8_t AP_Beacon::num_beacons = 0 private
Definition at line 138 of file AP_Beacon.h.
Referenced by beacon_distance(), beacon_healthy(), beacon_id(), beacon_last_update_ms(), beacon_position(), count(), get_beacon_data(), AP_Beacon_Backend::set_beacon_distance(), AP_Beacon_Backend::set_beacon_position(), and update_boundary_points().
orient_yaw
AP_Int16 AP_Beacon::orient_yaw private
Definition at line 126 of file AP_Beacon.h.
Referenced by AP_Beacon_Backend::correct_for_orient_yaw().
origin_alt
AP_Float AP_Beacon::origin_alt private
Definition at line 125 of file AP_Beacon.h.
Referenced by AP_Beacon_Backend::get_beacon_origin_alt(), and get_origin().
origin_lat
AP_Float AP_Beacon::origin_lat private
Definition at line 123 of file AP_Beacon.h.
Referenced by AP_Beacon_Backend::get_beacon_origin_lat(), and get_origin().
origin_lon
AP_Float AP_Beacon::origin_lon private
Definition at line 124 of file AP_Beacon.h.
Referenced by AP_Beacon_Backend::get_beacon_origin_lon(), and get_origin().
serial_manager
AP_SerialManager& AP_Beacon::serial_manager private
Definition at line 130 of file AP_Beacon.h.
Referenced by init().
var_info
const AP_Param::GroupInfo AP_Beacon::var_info static
Definition at line 104 of file AP_Beacon.h.
Referenced by AP_Beacon(), and setup().
veh_pos_accuracy
float AP_Beacon::veh_pos_accuracy private
Definition at line 134 of file AP_Beacon.h.
Referenced by get_vehicle_position_ned(), and AP_Beacon_Backend::set_vehicle_position().
veh_pos_ned
Vector3f AP_Beacon::veh_pos_ned private
Definition at line 133 of file AP_Beacon.h.
Referenced by get_vehicle_position_ned(), and AP_Beacon_Backend::set_vehicle_position().
veh_pos_update_ms
uint32_t AP_Beacon::veh_pos_update_ms private
Definition at line 135 of file AP_Beacon.h.
Referenced by get_vehicle_position_ned(), and AP_Beacon_Backend::set_vehicle_position().
The documentation for this class was generated from the following files:
libraries/AP_Beacon/AP_Beacon.h
libraries/AP_Beacon/AP_Beacon.cpp