APM:Libraries: AP_DEVO_Telem Class Reference
AP_DEVO_Telem Class Reference
#include <AP_Devo_Telem.h>
Public Member Functions
AP_DEVO_Telem ()
AP_DEVO_Telem (const AP_DEVO_Telem &other)=delete
AP_DEVO_Telem & operator= (const AP_DEVO_Telem &)=delete
void init ()
Private Member Functions
uint32_t gpsDdToDmsFormat (float ddm)
void tick (void)
void send_frames ()
Private Attributes
AP_HAL::UARTDriver * _port
uint32_t _last_frame_ms
Detailed Description
Definition at line 21 of file AP_Devo_Telem.h.
Constructor & Destructor Documentation
AP_DEVO_Telem() [1/2]
AP_DEVO_Telem::AP_DEVO_Telem () inline
Definition at line 24 of file AP_Devo_Telem.h.
AP_DEVO_Telem() [2/2]
AP_DEVO_Telem::AP_DEVO_Telem (const AP_DEVO_Telem & other) delete
Member Function Documentation
gpsDdToDmsFormat()
uint32_t AP_DEVO_Telem::gpsDdToDmsFormat (float ddm) private
Definition at line 51 of file AP_Devo_Telem.cpp.
Referenced by send_frames().
init()
void AP_DEVO_Telem::init (void)
Definition at line 36 of file AP_Devo_Telem.cpp.
Referenced by GCS::setup_uarts().
operator=()
AP_DEVO_Telem& AP_DEVO_Telem::operator= (const AP_DEVO_Telem &) delete
send_frames()
void AP_DEVO_Telem::send_frames () private
< 0xAA for a valid packet
Definition at line 73 of file AP_Devo_Telem.cpp.
Referenced by tick().
tick()
void AP_DEVO_Telem::tick (void) private
Definition at line 127 of file AP_Devo_Telem.cpp.
Referenced by init().
Member Data Documentation
_last_frame_ms
uint32_t AP_DEVO_Telem::_last_frame_ms private
Definition at line 43 of file AP_Devo_Telem.h.
Referenced by tick().
_port
AP_HAL::UARTDriver* AP_DEVO_Telem::_port private
Definition at line 42 of file AP_Devo_Telem.h.
Referenced by init(), and send_frames().
The documentation for this class was generated from the following files:
libraries/AP_Devo_Telem/AP_Devo_Telem.h
libraries/AP_Devo_Telem/AP_Devo_Telem.cpp