APM:Libraries: SITL::Submarine Class Reference
SITL::Submarine Class Reference
#include <SIM_Submarine.h>
Public Member Functions
Submarine (const char *home_str, const char *frame_str)
void update (const struct sitl_input &input) override
Public Member Functions inherited from SITL::Aircraft
Aircraft (const char *home_str, const char *frame_str)
void set_speedup (float speedup)
void set_instance (uint8_t _instance)
void set_autotest_dir (const char *_autotest_dir)
virtual void set_interface_ports (const char *address, const int port_in, const int port_out)
void fill_fdm (struct sitl_fdm &fdm)
void smooth_sensors (void)
float get_rate_hz (void) const
const Vector3f & get_gyro (void) const
const Vector3f & get_velocity_ef (void) const
const Vector3f & get_velocity_air_ef (void) const
const Matrix3f & get_dcm (void) const
const Vector3f & get_mag_field_bf (void) const
float gross_mass () const
const Location & get_location () const
const Vector3f & get_position () const
void get_attitude (Quaternion &attitude) const
const Location & get_home () const
float get_home_yaw () const
void set_sprayer (Sprayer *_sprayer)
void set_parachute (Parachute *_parachute)
void set_gripper_servo (Gripper_Servo *_gripper)
void set_gripper_epm (Gripper_EPM *_gripper_epm)
void set_precland (SIM_Precland *_precland)
Static Public Member Functions
static Aircraft * create (const char *home_str, const char *frame_str)
Static Public Member Functions inherited from SITL::Aircraft
static double rand_normal (double mean, double stddev)
static bool parse_home (const char *home_str, Location &loc, float &yaw_degrees)
Protected Member Functions
bool on_ground () const override
void calculate_forces (const struct sitl_input &input, Vector3f &rot_accel, Vector3f &body_accel)
float calculate_buoyancy_acceleration ()
Calculate buoyancy force of the frame.
void calculate_drag_force (const Vector3f &velocity, const Vector3f &drag_coefficient, Vector3f &force)
Calculate drag force against body.
Protected Member Functions inherited from SITL::Aircraft
float ground_height_difference () const
float hagl () const
void update_position (void)
void update_mag_field_bf (void)
void time_advance ()
void setup_frame_time (float rate, float speedup)
void adjust_frame_time (float rate)
void sync_frame_time (void)
void add_noise (float throttle)
uint64_t get_wall_time_us (void) const
void update_dynamics (const Vector3f &rot_accel)
void update_wind (const struct sitl_input &input)
float filtered_idx (float v, uint8_t idx)
float filtered_servo_angle (const struct sitl_input &input, uint8_t idx)
float filtered_servo_range (const struct sitl_input &input, uint8_t idx)
void extrapolate_sensors (float delta_time)
void update_external_payload (const struct sitl_input &input)
void add_shove_forces (Vector3f &rot_accel, Vector3f &body_accel)
void add_twist_forces (Vector3f &rot_accel)
Protected Attributes
const float water_density = 1023.6
struct {
float length = 0.457
float width = 0.338
float height = 0.254
float weight = 10.5
float net_buoyancy = 2.0
float buoyancy_acceleration = GRAVITY_MSS + net_buoyancy/weight
const Vector3f linear_drag_coefficient = Vector3f(0.2, 0.3, 0.4)
const Vector3f angular_drag_coefficient = Vector3f(1, 1, 1)
float volume = buoyancy_acceleration * weight / (GRAVITY_MSS * 1023.6f)
float equivalent_sphere_area = M_PI_4 * pow(volume * 3.0f / 4.0f, 2.0f / 3.0f)
} frame_property
Frame * frame
Protected Attributes inherited from SITL::Aircraft
SITL * sitl
Location home
Location location
float ground_level
float home_yaw
float frame_height
Matrix3f dcm
Vector3f gyro
Vector3f gyro_prev
Vector3f ang_accel
Vector3f velocity_ef
Vector3f wind_ef
Vector3f velocity_air_ef
Vector3f velocity_air_bf
Vector3f position
float mass
float external_payload_mass = 0.0f
Vector3f accel_body
float airspeed
float airspeed_pitot
float battery_voltage = -1.0f
float battery_current = 0.0f
float rpm1 = 0
float rpm2 = 0
uint8_t rcin_chan_count = 0
float rcin [8]
float range = -1.0f
struct {
struct vector3f_array points
struct float_array ranges
} scanner
float turbulence_azimuth = 0.0f
float turbulence_horizontal_speed = 0.0f
float turbulence_vertical_speed = 0.0f
Vector3f mag_bf
uint64_t time_now_us
const float gyro_noise
const float accel_noise
float rate_hz
float achieved_rate_hz
float target_speedup
uint64_t frame_time_us
float scaled_frame_time_us
uint64_t last_wall_time_us
uint8_t instance
const char * autotest_dir
const char * frame
bool use_time_sync = true
float last_speedup = -1.0f
AP_Int8 * ahrs_orientation
enum SITL::Aircraft::GroundBehaviour ground_behavior
bool use_smoothing
AP_Terrain * terrain
const float FEET_TO_METERS = 0.3048f
const float KNOTS_TO_METERS_PER_SECOND = 0.51444f
Additional Inherited Members
Protected Types inherited from SITL::Aircraft
enum GroundBehaviour { GROUND_BEHAVIOR_NONE = 0, GROUND_BEHAVIOR_NO_MOVEMENT, GROUND_BEHAVIOR_FWD_ONLY, GROUND_BEHAVIOR_TAILSITTER }
Detailed Description
Definition at line 32 of file SIM_Submarine.h.
Constructor & Destructor Documentation
Submarine()
Submarine::Submarine (const char * home_str, const char * frame_str)
Definition at line 38 of file SIM_Submarine.cpp.
Referenced by create().
Member Function Documentation
calculate_buoyancy_acceleration()
float Submarine::calculate_buoyancy_acceleration () protected
Calculate buoyancy force of the frame.
Returns
float
Definition at line 117 of file SIM_Submarine.cpp.
Referenced by calculate_forces().
calculate_drag_force()
void Submarine::calculate_drag_force (const Vector3f & velocity, const Vector3f & drag_coefficient, Vector3f & force) protected
Calculate drag force against body.
Parameters
velocity Body frame velocity of fluid
drag_coefficient Drag coefficient of body
force Output forces $ F_D = rho * v^2 * A * C_D / 2 $ rho = water density (kg/m^3), V = velocity (m/s), A = area (m^2), C_D = drag_coefficient
It's necessary to keep the velocity orientation from the body frame. To do so, a mathematical artifice is used to do velocity square but without loosing the direction. $(|V|/V)*V^2$ = $|V|*V$
Definition at line 95 of file SIM_Submarine.cpp.
Referenced by calculate_forces().
calculate_forces()
void Submarine::calculate_forces (const struct sitl_input & input, Vector3f & rot_accel, Vector3f & body_accel) protected
Definition at line 47 of file SIM_Submarine.cpp.
Referenced by update().
create()
static Aircraft* SITL::Submarine::create (const char * home_str, const char * frame_str) inline static
Definition at line 40 of file SIM_Submarine.h.
on_ground()
bool Submarine::on_ground () const override protected virtual
Reimplemented from SITL::Aircraft.
Definition at line 160 of file SIM_Submarine.cpp.
update()
void Submarine::update (const struct sitl_input & input) override virtual
Implements SITL::Aircraft.
Definition at line 138 of file SIM_Submarine.cpp.
Member Data Documentation
angular_drag_coefficient
const Vector3f SITL::Submarine::angular_drag_coefficient = Vector3f(1, 1, 1)
Definition at line 59 of file SIM_Submarine.h.
buoyancy_acceleration
float SITL::Submarine::buoyancy_acceleration = GRAVITY_MSS + net_buoyancy/weight
Definition at line 55 of file SIM_Submarine.h.
equivalent_sphere_area
float SITL::Submarine::equivalent_sphere_area = M_PI_4 * pow(volume * 3.0f / 4.0f, 2.0f / 3.0f)
Definition at line 69 of file SIM_Submarine.h.
frame
Frame* SITL::Submarine::frame protected
Definition at line 82 of file SIM_Submarine.h.
frame_property
const { ... } SITL::Submarine::frame_property
Referenced by calculate_buoyancy_acceleration(), calculate_drag_force(), and calculate_forces().
height
float SITL::Submarine::height = 0.254
Definition at line 51 of file SIM_Submarine.h.
length
float SITL::Submarine::length = 0.457
Definition at line 49 of file SIM_Submarine.h.
linear_drag_coefficient
const Vector3f SITL::Submarine::linear_drag_coefficient = Vector3f(0.2, 0.3, 0.4)
Definition at line 58 of file SIM_Submarine.h.
net_buoyancy
float SITL::Submarine::net_buoyancy = 2.0
Definition at line 53 of file SIM_Submarine.h.
volume
float SITL::Submarine::volume = buoyancy_acceleration * weight / (GRAVITY_MSS * 1023.6f)
Definition at line 63 of file SIM_Submarine.h.
water_density
const float SITL::Submarine::water_density = 1023.6 protected
Definition at line 46 of file SIM_Submarine.h.
Referenced by calculate_drag_force().
weight
float SITL::Submarine::weight = 10.5
Definition at line 52 of file SIM_Submarine.h.
width
float SITL::Submarine::width = 0.338
Definition at line 50 of file SIM_Submarine.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Submarine.h
libraries/SITL/SIM_Submarine.cpp