APM:Libraries: SITL::Frame Class Reference
SITL::Frame Class Reference
#include <SIM_Frame.h>
Public Member Functions
Frame (const char *_name, uint8_t _num_motors, Motor *_motors)
void init (float mass, float hover_throttle, float terminal_velocity, float terminal_rotation_rate)
void calculate_forces (const Aircraft &aircraft, const struct sitl_input &input, Vector3f &rot_accel, Vector3f &body_accel)
void current_and_voltage (const struct sitl_input &input, float &voltage, float &current)
Static Public Member Functions
static Frame * find_frame (const char *name)
Public Attributes
const char * name
uint8_t num_motors
Motor * motors
float terminal_velocity
float terminal_rotation_rate
float thrust_scale
uint8_t motor_offset
Detailed Description
Definition at line 29 of file SIM_Frame.h.
Constructor & Destructor Documentation
Frame()
SITL::Frame::Frame (const char * _name, uint8_t _num_motors, Motor * _motors) inline
Definition at line 35 of file SIM_Frame.h.
Member Function Documentation
calculate_forces()
void Frame::calculate_forces (const Aircraft & aircraft, const struct sitl_input & input, Vector3f & rot_accel, Vector3f & body_accel)
Definition at line 236 of file SIM_Frame.cpp.
Referenced by SITL::MultiCopter::calculate_forces(), and SITL::QuadPlane::update().
current_and_voltage()
void Frame::current_and_voltage (const struct sitl_input & input, float & voltage, float & current)
Definition at line 280 of file SIM_Frame.cpp.
Referenced by SITL::MultiCopter::update(), and SITL::QuadPlane::update().
find_frame()
Frame * Frame::find_frame (const char * name) static
Definition at line 224 of file SIM_Frame.cpp.
Referenced by SITL::MultiCopter::MultiCopter(), and SITL::QuadPlane::QuadPlane().
init()
void Frame::init (float mass, float hover_throttle, float terminal_velocity, float terminal_rotation_rate)
Definition at line 209 of file SIM_Frame.cpp.
Referenced by SITL::MultiCopter::MultiCopter(), and SITL::QuadPlane::QuadPlane().
Member Data Documentation
motor_offset
uint8_t SITL::Frame::motor_offset
Definition at line 57 of file SIM_Frame.h.
Referenced by calculate_forces(), current_and_voltage(), and SITL::QuadPlane::QuadPlane().
motors
Motor* SITL::Frame::motors
Definition at line 33 of file SIM_Frame.h.
Referenced by calculate_forces(), current_and_voltage(), and SITL::QuadPlane::QuadPlane().
name
const char* SITL::Frame::name
Definition at line 31 of file SIM_Frame.h.
Referenced by find_frame().
num_motors
uint8_t SITL::Frame::num_motors
Definition at line 32 of file SIM_Frame.h.
Referenced by calculate_forces(), current_and_voltage(), and init().
terminal_rotation_rate
float SITL::Frame::terminal_rotation_rate
Definition at line 55 of file SIM_Frame.h.
Referenced by calculate_forces(), and init().
terminal_velocity
float SITL::Frame::terminal_velocity
Definition at line 54 of file SIM_Frame.h.
Referenced by calculate_forces(), and init().
thrust_scale
float SITL::Frame::thrust_scale
Definition at line 56 of file SIM_Frame.h.
Referenced by calculate_forces(), and init().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Frame.h
libraries/SITL/SIM_Frame.cpp