APM:Libraries: AP_AHRS_NavEKF Class Reference
AP_AHRS_NavEKF Class Reference
#include <AP_AHRS_NavEKF.h>
Public Types
enum Flags { FLAG_NONE = 0, FLAG_ALWAYS_USE_EKF = 0x1 }
Public Member Functions
AP_AHRS_NavEKF (NavEKF2 &_EKF2, NavEKF3 &_EKF3, Flags flags=FLAG_NONE)
AP_AHRS_NavEKF (const AP_AHRS_NavEKF &other)=delete
AP_AHRS_NavEKF & operator= (const AP_AHRS_NavEKF &)=delete
const Vector3f & get_gyro (void) const override
const Matrix3f & get_rotation_body_to_ned (void) const override
const Vector3f & get_gyro_drift (void) const override
void reset_gyro_drift () override
void update (bool skip_ins_update=false) override
void reset (bool recover_eulers=false) override
void reset_attitude (const float &roll, const float &pitch, const float &yaw) override
bool get_position (struct Location &loc) const override
bool get_hagl (float &hagl) const override
float get_error_rp () const override
float get_error_yaw () const override
Vector3f wind_estimate () const override
bool airspeed_estimate (float *airspeed_ret) const override
bool use_compass () override
NavEKF2 & get_NavEKF2 (void)
const NavEKF2 & get_NavEKF2_const (void) const
NavEKF3 & get_NavEKF3 (void)
const NavEKF3 & get_NavEKF3_const (void) const
bool get_secondary_attitude (Vector3f &eulers) const override
bool get_secondary_quaternion (Quaternion &quat) const override
bool get_secondary_position (struct Location &loc) const override
Vector2f groundspeed_vector () override
const Vector3f & get_accel_ef (uint8_t i) const override
const Vector3f & get_accel_ef () const override
void getCorrectedDeltaVelocityNED (Vector3f &ret, float &dt) const override
const Vector3f & get_accel_ef_blended () const override
bool set_origin (const Location &loc) override
bool get_origin (Location &ret) const override
bool have_inertial_nav () const override
bool get_velocity_NED (Vector3f &vec) const override
bool get_relative_position_NED_home (Vector3f &vec) const override
bool get_relative_position_NED_origin (Vector3f &vec) const override
bool get_relative_position_NE_home (Vector2f &posNE) const override
bool get_relative_position_NE_origin (Vector2f &posNE) const override
void get_relative_position_D_home (float &posD) const override
bool get_relative_position_D_origin (float &posD) const override
bool get_vert_pos_rate (float &velocity) const
void writeOptFlowMeas (const uint8_t rawFlowQuality, const Vector2f &rawFlowRates, const Vector2f &rawGyroRates, const uint32_t msecFlowMeas, const Vector3f &posOffset)
void writeBodyFrameOdom (float quality, const Vector3f &delPos, const Vector3f &delAng, float delTime, uint32_t timeStamp_ms, const Vector3f &posOffset)
void writeExtNavData (const Vector3f &sensOffset, const Vector3f &pos, const Quaternion &quat, float posErr, float angErr, uint32_t timeStamp_ms, uint32_t resetTime_ms) override
uint8_t setInhibitGPS (void)
void getEkfControlLimits (float &ekfGndSpdLimit, float &ekfNavVelGainScaler) const
void set_ekf_use (bool setting)
bool healthy () const override
bool prearm_healthy () const override
bool initialised () const override
bool get_filter_status (nav_filter_status &status) const
bool getMagOffsets (uint8_t mag_idx, Vector3f &magOffsets) const
const char * prearm_failure_reason (void) const override
bool attitudes_consistent (char *failure_msg, const uint8_t failure_msg_len) const override
uint32_t getLastYawResetAngle (float &yawAng) const override
uint32_t getLastPosNorthEastReset (Vector2f &pos) const override
uint32_t getLastVelNorthEastReset (Vector2f &vel) const override
uint32_t getLastPosDownReset (float &posDelta) const override
bool resetHeightDatum () override
void send_ekf_status_report (mavlink_channel_t chan) const
bool get_hgt_ctrl_limit (float &limit) const override
bool get_location (struct Location &loc) const
bool get_variances (float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar, Vector2f &offset) const override
bool get_mag_field_NED (Vector3f &ret) const
bool get_mag_field_correction (Vector3f &ret) const override
void setTakeoffExpected (bool val)
void setTouchdownExpected (bool val)
bool getGpsGlitchStatus () const
void force_ekf_start (void)
bool have_ekf_logging (void) const override
uint8_t get_primary_accel_index (void) const override
uint8_t get_primary_gyro_index (void) const override
void check_lane_switch (void) override
void Log_Write ()
Public Member Functions inherited from AP_AHRS_DCM
AP_AHRS_DCM ()
AP_AHRS_DCM (const AP_AHRS_DCM &other)=delete
AP_AHRS_DCM & operator= (const AP_AHRS_DCM &)=delete
const Matrix3f & get_DCM_rotation_body_to_ned (void) const override
bool set_home (const Location &loc) override WARN_IF_UNUSED
void estimate_wind (void)
Public Member Functions inherited from AP_AHRS
AP_AHRS ()
virtual ~AP_AHRS ()
virtual void init ()
void set_fly_forward (bool b)
bool get_fly_forward (void) const
void set_likely_flying (bool b)
bool get_likely_flying (void) const
uint32_t get_time_flying_ms (void) const
AHRS_VehicleClass get_vehicle_class (void) const
void set_vehicle_class (AHRS_VehicleClass vclass)
void set_wind_estimation (bool b)
void set_compass (Compass *compass)
const Compass * get_compass () const
void set_optflow (const OpticalFlow *optflow)
const OpticalFlow * get_optflow () const
void update_orientation ()
void set_airspeed (AP_Airspeed *airspeed)
const AP_Airspeed * get_airspeed (void) const
float get_yaw_rate_earth (void) const
Vector3f get_gyro_latest (void) const
void get_quat_body_to_ned (Quaternion &quat) const
const Matrix3f & get_rotation_autopilot_body_to_vehicle_body (void) const
const Matrix3f & get_rotation_vehicle_body_to_autopilot_body (void) const
bool airspeed_estimate_true (float *airspeed_ret) const WARN_IF_UNUSED
float get_EAS2TAS (void) const
bool airspeed_sensor_enabled (void) const
uint8_t get_max_wind () const
virtual bool get_expected_mag_field_NED (Vector3f &ret) const WARN_IF_UNUSED
float groundspeed (void)
bool yaw_initialised (void) const
void set_correct_centrifugal (bool setting)
bool get_correct_centrifugal (void) const
const Vector3f & get_trim () const
void set_trim (const Vector3f &new_trim)
void add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom=true)
float cos_roll () const
float cos_pitch () const
float cos_yaw () const
float sin_roll () const
float sin_pitch () const
float sin_yaw () const
const struct Location & get_home (void) const
void lock_home ()
bool home_is_locked () const
bool home_is_set (void) const
void Log_Write_Home_And_Origin ()
uint8_t get_active_accel_instance (void) const
int8_t get_ekf_type (void) const
AP_AHRS_View * create_view (enum Rotation rotation, float pitch_trim_deg=0)
float getAOA (void)
float getSSA (void)
Vector2f rotate_earth_to_body2D (const Vector2f &ef_vector) const
Vector2f rotate_body_to_earth2D (const Vector2f &bf) const
virtual void update_AOA_SSA (void)
HAL_Semaphore & get_semaphore (void)
Private Types
enum EKF_TYPE { EKF_TYPE_NONE =0, EKF_TYPE3 =3, EKF_TYPE2 =2, EKF_TYPE_SITL =10 }
Private Member Functions
EKF_TYPE active_EKF_type (void) const
bool always_use_EKF () const
uint8_t ekf_type (void) const
void update_DCM (bool skip_ins_update)
void update_EKF2 (void)
void update_EKF3 (void)
uint8_t get_primary_IMU_index (void) const
void update_SITL (void)
Private Attributes
NavEKF2 & EKF2
NavEKF3 & EKF3
bool _ekf2_started
bool _ekf3_started
bool _force_ekf
Matrix3f _dcm_matrix
Vector3f _dcm_attitude
Vector3f _gyro_drift
Vector3f _gyro_estimate
Vector3f _accel_ef_ekf [INS_MAX_INSTANCES]
Vector3f _accel_ef_ekf_blended
const uint16_t startup_delay_ms = 1000
uint32_t start_time_ms = 0
Flags _ekf_flags
SITL::SITL * _sitl
uint32_t _last_body_odm_update_ms = 0
Additional Inherited Members
Static Public Member Functions inherited from AP_AHRS
static AP_AHRS * get_singleton ()
Public Attributes inherited from AP_AHRS
float roll
float pitch
float yaw
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
Static Public Attributes inherited from AP_AHRS
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions inherited from AP_AHRS
void update_nmea_out ()
void calc_trig (const Matrix3f &rot, float &cr, float &cp, float &cy, float &sr, float &sp, float &sy) const
void update_trig (void)
void update_cd_values (void)
Protected Attributes inherited from AP_AHRS
HAL_Semaphore_Recursive _rsem
AHRS_VehicleClass _vehicle_class
AP_Float _kp_yaw
AP_Float _kp
AP_Float gps_gain
AP_Float beta
AP_Int8 _gps_use
AP_Int8 _wind_max
AP_Int8 _board_orientation
AP_Int8 _gps_minsats
AP_Int8 _gps_delay
AP_Int8 _ekf_type
AP_Float _custom_roll
AP_Float _custom_pitch
AP_Float _custom_yaw
Matrix3f _custom_rotation
struct AP_AHRS::ahrs_flags _flags
uint32_t _last_flying_ms
Compass * _compass
const OpticalFlow * _optflow
AP_Airspeed * _airspeed
uint32_t _compass_last_update
AP_Vector3f _trim
Vector3f _last_trim
Matrix3f _rotation_autopilot_body_to_vehicle_body
Matrix3f _rotation_vehicle_body_to_autopilot_body
float _gyro_drift_limit
Vector3f _accel_ef [INS_MAX_INSTANCES]
Vector3f _accel_ef_blended
Vector2f _lp
Vector2f _hp
Vector2f _lastGndVelADS
struct Location _home
bool _home_is_set:1
bool _home_locked:1
float _cos_roll
float _cos_pitch
float _cos_yaw
float _sin_roll
float _sin_pitch
float _sin_yaw
uint8_t _active_accel_instance
AP_AHRS_View * _view
float _AOA
float _SSA
uint32_t _last_AOA_update_ms
Detailed Description
Definition at line 40 of file AP_AHRS_NavEKF.h.
Member Enumeration Documentation
EKF_TYPE
enum AP_AHRS_NavEKF::EKF_TYPE private
Enumerator
EKF_TYPE_NONE
EKF_TYPE3
EKF_TYPE2
EKF_TYPE_SITL
Definition at line 268 of file AP_AHRS_NavEKF.h.
Flags
enum AP_AHRS_NavEKF::Flags
Enumerator
FLAG_NONE
FLAG_ALWAYS_USE_EKF
Definition at line 42 of file AP_AHRS_NavEKF.h.
Constructor & Destructor Documentation
AP_AHRS_NavEKF() [1/2]
AP_AHRS_NavEKF::AP_AHRS_NavEKF (NavEKF2 & _EKF2, NavEKF3 & _EKF3, Flags flags = FLAG_NONE)
Definition at line 38 of file AP_AHRS_NavEKF.cpp.
AP_AHRS_NavEKF() [2/2]
AP_AHRS_NavEKF::AP_AHRS_NavEKF (const AP_AHRS_NavEKF & other) delete
Member Function Documentation
active_EKF_type()
AP_AHRS_NavEKF::EKF_TYPE AP_AHRS_NavEKF::active_EKF_type (void) const private
Definition at line 966 of file AP_AHRS_NavEKF.cpp.
Referenced by check_lane_switch(), get_accel_ef(), get_accel_ef_blended(), get_gyro(), get_gyro_drift(), get_hagl(), get_mag_field_correction(), get_mag_field_NED(), get_position(), get_relative_position_D_origin(), get_relative_position_NE_origin(), get_relative_position_NED_origin(), get_rotation_body_to_ned(), get_secondary_attitude(), get_secondary_position(), get_secondary_quaternion(), get_velocity_NED(), get_vert_pos_rate(), getCorrectedDeltaVelocityNED(), groundspeed_vector(), have_inertial_nav(), healthy(), set_origin(), update_EKF2(), update_EKF3(), update_SITL(), use_compass(), and wind_estimate().
airspeed_estimate()
bool AP_AHRS_NavEKF::airspeed_estimate (float * airspeed_ret) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 491 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_OSD_Screen::draw_aspeed().
always_use_EKF()
bool AP_AHRS_NavEKF::always_use_EKF () const inline private
Definition at line 277 of file AP_AHRS_NavEKF.h.
Referenced by active_EKF_type(), and ekf_type().
attitudes_consistent()
bool AP_AHRS_NavEKF::attitudes_consistent (char * failure_msg, const uint8_t failure_msg_len) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1350 of file AP_AHRS_NavEKF.cpp.
check_lane_switch()
void AP_AHRS_NavEKF::check_lane_switch (void) override virtual
Reimplemented from AP_AHRS.
Definition at line 1792 of file AP_AHRS_NavEKF.cpp.
ekf_type()
uint8_t AP_AHRS_NavEKF::ekf_type (void) const private
Definition at line 952 of file AP_AHRS_NavEKF.cpp.
Referenced by active_EKF_type(), get_filter_status(), get_hgt_ctrl_limit(), get_location(), get_origin(), get_primary_accel_index(), get_primary_gyro_index(), get_primary_IMU_index(), get_variances(), getEkfControlLimits(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastVelNorthEastReset(), getLastYawResetAngle(), getMagOffsets(), have_ekf_logging(), healthy(), initialised(), prearm_failure_reason(), prearm_healthy(), resetHeightDatum(), send_ekf_status_report(), setInhibitGPS(), setTakeoffExpected(), and setTouchdownExpected().
force_ekf_start()
void AP_AHRS_NavEKF::force_ekf_start (void) inline
Definition at line 251 of file AP_AHRS_NavEKF.h.
get_accel_ef() [1/2]
const Vector3f & AP_AHRS_NavEKF::get_accel_ef (uint8_t i) const override virtual
Reimplemented from AP_AHRS.
Definition at line 364 of file AP_AHRS_NavEKF.cpp.
get_accel_ef() [2/2]
const Vector3f & AP_AHRS_NavEKF::get_accel_ef (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1767 of file AP_AHRS_NavEKF.cpp.
get_accel_ef_blended()
const Vector3f & AP_AHRS_NavEKF::get_accel_ef_blended (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 373 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_Logger::Write_Rate().
get_error_rp()
float AP_AHRS_NavEKF::get_error_rp (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 452 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_ahrs(), AP_Logger::Write_Attitude(), and AP_Logger::Write_AttitudeView().
get_error_yaw()
float AP_AHRS_NavEKF::get_error_yaw (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 457 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_ahrs(), AP_Logger::Write_Attitude(), and AP_Logger::Write_AttitudeView().
get_filter_status()
bool AP_AHRS_NavEKF::get_filter_status (nav_filter_status & status) const
Definition at line 1180 of file AP_AHRS_NavEKF.cpp.
Referenced by active_EKF_type(), SoloGimbalEKF::fuseVelocity(), getGpsGlitchStatus(), and SoloGimbalEKF::RunEKF().
get_gyro()
const Vector3f & AP_AHRS_NavEKF::get_gyro (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 50 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_attitude(), AP_Mount_Servo::stabilize(), AP_OpticalFlow_Pixart::timer(), AP_OpticalFlow_CXOF::update(), and AP_Logger::Write_Rate().
get_gyro_drift()
const Vector3f & AP_AHRS_NavEKF::get_gyro_drift (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 66 of file AP_AHRS_NavEKF.cpp.
Referenced by loop(), GCS_MAVLINK::send_ahrs(), and update().
get_hagl()
bool AP_AHRS_NavEKF::get_hagl (float & hagl) const override virtual
Reimplemented from AP_AHRS.
Definition at line 753 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_opticalflow().
get_hgt_ctrl_limit()
bool AP_AHRS_NavEKF::get_hgt_ctrl_limit (float & limit) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1602 of file AP_AHRS_NavEKF.cpp.
get_location()
bool AP_AHRS_NavEKF::get_location (struct Location & loc) const
Definition at line 1625 of file AP_AHRS_NavEKF.cpp.
get_mag_field_correction()
bool AP_AHRS_NavEKF::get_mag_field_correction (Vector3f & ret) const override virtual
Reimplemented from AP_AHRS.
Definition at line 700 of file AP_AHRS_NavEKF.cpp.
Referenced by SoloGimbalEKF::calcMagHeadingInnov().
get_mag_field_NED()
bool AP_AHRS_NavEKF::get_mag_field_NED (Vector3f & ret) const
Definition at line 677 of file AP_AHRS_NavEKF.cpp.
Referenced by SoloGimbalEKF::calcMagHeadingInnov().
get_NavEKF2()
NavEKF2& AP_AHRS_NavEKF::get_NavEKF2 (void) inline
Definition at line 92 of file AP_AHRS_NavEKF.h.
Referenced by Log_Write().
get_NavEKF2_const()
const NavEKF2& AP_AHRS_NavEKF::get_NavEKF2_const (void) const inline
Definition at line 95 of file AP_AHRS_NavEKF.h.
Referenced by GCS_MAVLINK::send_ahrs3().
get_NavEKF3()
NavEKF3& AP_AHRS_NavEKF::get_NavEKF3 (void) inline
Definition at line 99 of file AP_AHRS_NavEKF.h.
Referenced by Log_Write().
get_NavEKF3_const()
const NavEKF3& AP_AHRS_NavEKF::get_NavEKF3_const (void) const inline
Definition at line 102 of file AP_AHRS_NavEKF.h.
get_origin()
bool AP_AHRS_NavEKF::get_origin (Location & ret) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1568 of file AP_AHRS_NavEKF.cpp.
Referenced by get_relative_position_D_home(), get_relative_position_NE_home(), get_relative_position_NED_home(), and GCS_MAVLINK::set_ekf_origin().
get_position()
bool AP_AHRS_NavEKF::get_position (struct Location & loc) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 413 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_OSD_Screen::draw_home(), get_location(), get_relative_position_NE_origin(), get_relative_position_NED_origin(), GCS_MAVLINK::send_global_position_int(), GCS_MAVLINK::send_vfr_hud(), AP_OSD::stats(), CompassLearn::update(), and AP_Logger::Write_POS().
get_primary_accel_index()
uint8_t AP_AHRS_NavEKF::get_primary_accel_index (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1774 of file AP_AHRS_NavEKF.cpp.
Referenced by get_accel_ef().
get_primary_gyro_index()
uint8_t AP_AHRS_NavEKF::get_primary_gyro_index (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1783 of file AP_AHRS_NavEKF.cpp.
get_primary_IMU_index()
uint8_t AP_AHRS_NavEKF::get_primary_IMU_index (void) const private
Definition at line 1745 of file AP_AHRS_NavEKF.cpp.
Referenced by get_primary_accel_index(), and get_primary_gyro_index().
get_relative_position_D_home()
void AP_AHRS_NavEKF::get_relative_position_D_home (float & posD) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 935 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_OSD_Screen::draw_altitude(), and AP_Logger::Write_POS().
get_relative_position_D_origin()
bool AP_AHRS_NavEKF::get_relative_position_D_origin (float & posD) const override virtual
Reimplemented from AP_AHRS.
Definition at line 903 of file AP_AHRS_NavEKF.cpp.
Referenced by get_relative_position_D_home(), and AP_Logger::Write_POS().
get_relative_position_NE_home()
bool AP_AHRS_NavEKF::get_relative_position_NE_home (Vector2f & posNE) const override virtual
Reimplemented from AP_AHRS.
Definition at line 882 of file AP_AHRS_NavEKF.cpp.
get_relative_position_NE_origin()
bool AP_AHRS_NavEKF::get_relative_position_NE_origin (Vector2f & posNE) const override virtual
Reimplemented from AP_AHRS.
Definition at line 852 of file AP_AHRS_NavEKF.cpp.
Referenced by get_relative_position_NE_home().
get_relative_position_NED_home()
bool AP_AHRS_NavEKF::get_relative_position_NED_home (Vector3f & vec) const override virtual
Reimplemented from AP_AHRS.
Definition at line 833 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_local_position().
get_relative_position_NED_origin()
bool AP_AHRS_NavEKF::get_relative_position_NED_origin (Vector3f & vec) const override virtual
Reimplemented from AP_AHRS.
Definition at line 781 of file AP_AHRS_NavEKF.cpp.
Referenced by get_relative_position_NED_home().
get_rotation_body_to_ned()
const Matrix3f & AP_AHRS_NavEKF::get_rotation_body_to_ned (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 58 of file AP_AHRS_NavEKF.cpp.
Referenced by loop(), SoloGimbalEKF::RunEKF(), and AP_Mount_Servo::stabilize().
get_secondary_attitude()
bool AP_AHRS_NavEKF::get_secondary_attitude (Vector3f & eulers) const override virtual
Reimplemented from AP_AHRS.
Definition at line 518 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_ahrs2(), and AP_Logger::Write_AHRS2().
get_secondary_position()
bool AP_AHRS_NavEKF::get_secondary_position (struct Location & loc) const override virtual
Reimplemented from AP_AHRS.
Definition at line 559 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::send_ahrs2(), and AP_Logger::Write_AHRS2().
get_secondary_quaternion()
bool AP_AHRS_NavEKF::get_secondary_quaternion (Quaternion & quat) const override virtual
Reimplemented from AP_AHRS.
Definition at line 539 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_Logger::Write_AHRS2().
get_variances()
bool AP_AHRS_NavEKF::get_variances (float & velVar, float & posVar, float & hgtVar, Vector3f & magVar, float & tasVar, Vector2f & offset) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1650 of file AP_AHRS_NavEKF.cpp.
get_velocity_NED()
bool AP_AHRS_NavEKF::get_velocity_NED (Vector3f & vec) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 649 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_OSD_Screen::draw_climbeff(), AP_OSD_Screen::draw_vspeed(), SoloGimbalEKF::fuseVelocity(), GCS_MAVLINK::send_global_position_int(), and GCS_MAVLINK::send_local_position().
get_vert_pos_rate()
bool AP_AHRS_NavEKF::get_vert_pos_rate (float & velocity) const
Definition at line 724 of file AP_AHRS_NavEKF.cpp.
getCorrectedDeltaVelocityNED()
void AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED (Vector3f & ret, float & dt) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1300 of file AP_AHRS_NavEKF.cpp.
getEkfControlLimits()
void AP_AHRS_NavEKF::getEkfControlLimits (float & ekfGndSpdLimit, float & ekfNavVelGainScaler) const
Definition at line 1254 of file AP_AHRS_NavEKF.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), and AC_PosControl::run_xy_controller().
getGpsGlitchStatus()
bool AP_AHRS_NavEKF::getGpsGlitchStatus () const
Definition at line 1719 of file AP_AHRS_NavEKF.cpp.
getLastPosDownReset()
uint32_t AP_AHRS_NavEKF::getLastPosDownReset (float & posDelta) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1479 of file AP_AHRS_NavEKF.cpp.
getLastPosNorthEastReset()
uint32_t AP_AHRS_NavEKF::getLastPosNorthEastReset (Vector2f & pos) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1436 of file AP_AHRS_NavEKF.cpp.
getLastVelNorthEastReset()
uint32_t AP_AHRS_NavEKF::getLastVelNorthEastReset (Vector2f & vel) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1457 of file AP_AHRS_NavEKF.cpp.
getLastYawResetAngle()
uint32_t AP_AHRS_NavEKF::getLastYawResetAngle (float & yawAng) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1415 of file AP_AHRS_NavEKF.cpp.
getMagOffsets()
bool AP_AHRS_NavEKF::getMagOffsets (uint8_t mag_idx, Vector3f & magOffsets) const
Definition at line 1279 of file AP_AHRS_NavEKF.cpp.
groundspeed_vector()
Vector2f AP_AHRS_NavEKF::groundspeed_vector (void) override virtual
Reimplemented from AP_AHRS.
Definition at line 579 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_OSD_Screen::draw_eff(), AP_OSD_Screen::draw_gspeed(), and AP_OSD::stats().
have_ekf_logging()
bool AP_AHRS_NavEKF::have_ekf_logging (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1729 of file AP_AHRS_NavEKF.cpp.
have_inertial_nav()
bool AP_AHRS_NavEKF::have_inertial_nav (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 642 of file AP_AHRS_NavEKF.cpp.
Referenced by SoloGimbalEKF::fuseVelocity(), GCS_MAVLINK::send_opticalflow(), and GCS::update_sensor_status_flags().
healthy()
bool AP_AHRS_NavEKF::healthy (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 1076 of file AP_AHRS_NavEKF.cpp.
Referenced by prearm_healthy(), and GCS::update_sensor_status_flags().
initialised()
bool AP_AHRS_NavEKF::initialised (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1157 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS::update_sensor_status_flags().
Log_Write()
void AP_AHRS_NavEKF::Log_Write ()
Definition at line 1813 of file AP_AHRS_NavEKF.cpp.
operator=()
AP_AHRS_NavEKF& AP_AHRS_NavEKF::operator= (const AP_AHRS_NavEKF &) delete
prearm_failure_reason()
const char * AP_AHRS_NavEKF::prearm_failure_reason (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1332 of file AP_AHRS_NavEKF.cpp.
prearm_healthy()
bool AP_AHRS_NavEKF::prearm_healthy (void) const override virtual
Reimplemented from AP_AHRS.
Definition at line 1124 of file AP_AHRS_NavEKF.cpp.
reset()
void AP_AHRS_NavEKF::reset (bool recover_eulers = false) override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 381 of file AP_AHRS_NavEKF.cpp.
reset_attitude()
void AP_AHRS_NavEKF::reset_attitude (const float & roll, const float & pitch, const float & yaw) override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 397 of file AP_AHRS_NavEKF.cpp.
reset_gyro_drift()
void AP_AHRS_NavEKF::reset_gyro_drift (void) override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 76 of file AP_AHRS_NavEKF.cpp.
resetHeightDatum()
bool AP_AHRS_NavEKF::resetHeightDatum (void) override virtual
Reimplemented from AP_AHRS.
Definition at line 1501 of file AP_AHRS_NavEKF.cpp.
send_ekf_status_report()
void AP_AHRS_NavEKF::send_ekf_status_report (mavlink_channel_t chan) const
Definition at line 1528 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::try_send_message().
set_ekf_use()
void AP_AHRS_NavEKF::set_ekf_use (bool setting)
Definition at line 1151 of file AP_AHRS_NavEKF.cpp.
set_origin()
bool AP_AHRS_NavEKF::set_origin (const Location & loc) override virtual
Reimplemented from AP_AHRS.
Definition at line 612 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS_MAVLINK::set_ekf_origin().
setInhibitGPS()
uint8_t AP_AHRS_NavEKF::setInhibitGPS (void)
Definition at line 1234 of file AP_AHRS_NavEKF.cpp.
setTakeoffExpected()
void AP_AHRS_NavEKF::setTakeoffExpected (bool val)
Definition at line 1681 of file AP_AHRS_NavEKF.cpp.
setTouchdownExpected()
void AP_AHRS_NavEKF::setTouchdownExpected (bool val)
Definition at line 1700 of file AP_AHRS_NavEKF.cpp.
update()
void AP_AHRS_NavEKF::update (bool skip_ins_update = false) override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 89 of file AP_AHRS_NavEKF.cpp.
Referenced by loop().
update_DCM()
void AP_AHRS_NavEKF::update_DCM (bool skip_ins_update) private
Definition at line 142 of file AP_AHRS_NavEKF.cpp.
Referenced by update().
update_EKF2()
void AP_AHRS_NavEKF::update_EKF2 (void) private
Definition at line 158 of file AP_AHRS_NavEKF.cpp.
Referenced by update().
update_EKF3()
void AP_AHRS_NavEKF::update_EKF3 (void) private
Definition at line 231 of file AP_AHRS_NavEKF.cpp.
Referenced by update().
update_SITL()
void AP_AHRS_NavEKF::update_SITL (void) private
Definition at line 306 of file AP_AHRS_NavEKF.cpp.
Referenced by update().
use_compass()
bool AP_AHRS_NavEKF::use_compass (void) override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 497 of file AP_AHRS_NavEKF.cpp.
Referenced by GCS::update_sensor_status_flags().
wind_estimate()
Vector3f AP_AHRS_NavEKF::wind_estimate (void) const override virtual
Reimplemented from AP_AHRS_DCM.
Definition at line 463 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_OSD_Screen::draw_wind().
writeBodyFrameOdom()
void AP_AHRS_NavEKF::writeBodyFrameOdom (float quality, const Vector3f & delPos, const Vector3f & delAng, float delTime, uint32_t timeStamp_ms, const Vector3f & posOffset)
Definition at line 1221 of file AP_AHRS_NavEKF.cpp.
Referenced by AP_VisualOdom::update().
writeExtNavData()
void AP_AHRS_NavEKF::writeExtNavData (const Vector3f & sensOffset, const Vector3f & pos, const Quaternion & quat, float posErr, float angErr, uint32_t timeStamp_ms, uint32_t resetTime_ms) override virtual
Reimplemented from AP_AHRS.
Definition at line 1227 of file AP_AHRS_NavEKF.cpp.
writeOptFlowMeas()
void AP_AHRS_NavEKF::writeOptFlowMeas (const uint8_t rawFlowQuality, const Vector2f & rawFlowRates, const Vector2f & rawGyroRates, const uint32_t msecFlowMeas, const Vector3f & posOffset)
Definition at line 1214 of file AP_AHRS_NavEKF.cpp.
Referenced by OpticalFlow::update_state().
Member Data Documentation
_accel_ef_ekf
Vector3f AP_AHRS_NavEKF::_accel_ef_ekf[INS_MAX_INSTANCES] private
Definition at line 293 of file AP_AHRS_NavEKF.h.
Referenced by get_accel_ef(), update_EKF2(), update_EKF3(), and update_SITL().
_accel_ef_ekf_blended
Vector3f AP_AHRS_NavEKF::_accel_ef_ekf_blended private
Definition at line 294 of file AP_AHRS_NavEKF.h.
Referenced by get_accel_ef_blended(), update_EKF2(), update_EKF3(), and update_SITL().
_dcm_attitude
Vector3f AP_AHRS_NavEKF::_dcm_attitude private
Definition at line 289 of file AP_AHRS_NavEKF.h.
Referenced by get_secondary_attitude(), reset(), reset_attitude(), and update_DCM().
_dcm_matrix
Matrix3f AP_AHRS_NavEKF::_dcm_matrix private
Definition at line 288 of file AP_AHRS_NavEKF.h.
Referenced by AP_AHRS_NavEKF(), get_rotation_body_to_ned(), getCorrectedDeltaVelocityNED(), update_EKF2(), update_EKF3(), and update_SITL().
_ekf2_started
bool AP_AHRS_NavEKF::_ekf2_started private
Definition at line 283 of file AP_AHRS_NavEKF.h.
Referenced by active_EKF_type(), get_secondary_attitude(), get_secondary_position(), get_secondary_quaternion(), healthy(), initialised(), prearm_healthy(), reset(), reset_attitude(), and update_EKF2().
_ekf3_started
bool AP_AHRS_NavEKF::_ekf3_started private
Definition at line 284 of file AP_AHRS_NavEKF.h.
Referenced by active_EKF_type(), healthy(), initialised(), prearm_healthy(), reset(), reset_attitude(), and update_EKF3().
_ekf_flags
Flags AP_AHRS_NavEKF::_ekf_flags private
Definition at line 297 of file AP_AHRS_NavEKF.h.
Referenced by always_use_EKF().
_force_ekf
bool AP_AHRS_NavEKF::_force_ekf private
Definition at line 285 of file AP_AHRS_NavEKF.h.
Referenced by force_ekf_start(), update_EKF2(), and update_EKF3().
_gyro_drift
Vector3f AP_AHRS_NavEKF::_gyro_drift private
Definition at line 291 of file AP_AHRS_NavEKF.h.
Referenced by get_gyro_drift(), update_EKF2(), update_EKF3(), and update_SITL().
_gyro_estimate
Vector3f AP_AHRS_NavEKF::_gyro_estimate private
Definition at line 292 of file AP_AHRS_NavEKF.h.
Referenced by get_gyro(), update_EKF2(), update_EKF3(), and update_SITL().
_last_body_odm_update_ms
uint32_t AP_AHRS_NavEKF::_last_body_odm_update_ms = 0 private
Definition at line 309 of file AP_AHRS_NavEKF.h.
Referenced by update_SITL().
_sitl
SITL::SITL* AP_AHRS_NavEKF::_sitl private
Definition at line 308 of file AP_AHRS_NavEKF.h.
Referenced by get_hagl(), get_origin(), get_position(), get_relative_position_D_origin(), get_relative_position_NED_origin(), get_velocity_NED(), get_vert_pos_rate(), groundspeed_vector(), set_origin(), and update_SITL().
EKF2
NavEKF2& AP_AHRS_NavEKF::EKF2 private
Definition at line 281 of file AP_AHRS_NavEKF.h.
Referenced by active_EKF_type(), attitudes_consistent(), check_lane_switch(), get_filter_status(), get_hagl(), get_hgt_ctrl_limit(), get_location(), get_mag_field_correction(), get_mag_field_NED(), get_NavEKF2(), get_NavEKF2_const(), get_origin(), get_position(), get_primary_IMU_index(), get_relative_position_D_origin(), get_relative_position_NE_origin(), get_relative_position_NED_origin(), get_secondary_attitude(), get_secondary_position(), get_secondary_quaternion(), get_variances(), get_velocity_NED(), get_vert_pos_rate(), getCorrectedDeltaVelocityNED(), getEkfControlLimits(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastVelNorthEastReset(), getLastYawResetAngle(), getMagOffsets(), groundspeed_vector(), have_ekf_logging(), healthy(), prearm_failure_reason(), prearm_healthy(), reset(), reset_attitude(), reset_gyro_drift(), resetHeightDatum(), send_ekf_status_report(), set_origin(), setInhibitGPS(), setTakeoffExpected(), setTouchdownExpected(), update_EKF2(), use_compass(), wind_estimate(), writeExtNavData(), and writeOptFlowMeas().
EKF3
NavEKF3& AP_AHRS_NavEKF::EKF3 private
Definition at line 282 of file AP_AHRS_NavEKF.h.
Referenced by active_EKF_type(), attitudes_consistent(), check_lane_switch(), get_filter_status(), get_hagl(), get_hgt_ctrl_limit(), get_location(), get_mag_field_correction(), get_mag_field_NED(), get_NavEKF3(), get_NavEKF3_const(), get_origin(), get_position(), get_primary_IMU_index(), get_relative_position_D_origin(), get_relative_position_NE_origin(), get_relative_position_NED_origin(), get_variances(), get_velocity_NED(), get_vert_pos_rate(), getCorrectedDeltaVelocityNED(), getEkfControlLimits(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastVelNorthEastReset(), getLastYawResetAngle(), getMagOffsets(), groundspeed_vector(), have_ekf_logging(), healthy(), prearm_failure_reason(), prearm_healthy(), reset(), reset_attitude(), reset_gyro_drift(), resetHeightDatum(), send_ekf_status_report(), set_origin(), setInhibitGPS(), setTakeoffExpected(), setTouchdownExpected(), update_EKF3(), update_SITL(), use_compass(), wind_estimate(), writeBodyFrameOdom(), and writeOptFlowMeas().
start_time_ms
uint32_t AP_AHRS_NavEKF::start_time_ms = 0 private
Definition at line 296 of file AP_AHRS_NavEKF.h.
Referenced by initialised(), update_EKF2(), and update_EKF3().
startup_delay_ms
const uint16_t AP_AHRS_NavEKF::startup_delay_ms = 1000 private
Definition at line 295 of file AP_AHRS_NavEKF.h.
Referenced by update_EKF2(), and update_EKF3().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS_NavEKF.h
libraries/AP_AHRS/AP_AHRS_NavEKF.cpp