APM:Libraries: AP_Baro_DPS280 Class Reference
AP_Baro_DPS280 Class Reference
#include <AP_Baro_DPS280.h>
Classes
struct dps280_cal
Public Member Functions
AP_Baro_DPS280 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
Private Member Functions
bool init (void)
bool read_calibration (void)
void timer (void)
void calculate_PT (int32_t UT, int32_t UP, float &pressure, float &temperature)
void fix_config_bits16 (int16_t &v, uint8_t bits) const
void fix_config_bits32 (int32_t &v, uint8_t bits) const
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > dev
uint8_t instance
uint32_t count
float pressure_sum
float temperature_sum
struct AP_Baro_DPS280::dps280_cal calibration
Additional Inherited Members
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore_Recursive _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 16 of file AP_Baro_DPS280.h.
Constructor & Destructor Documentation
AP_Baro_DPS280()
AP_Baro_DPS280::AP_Baro_DPS280 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
Definition at line 42 of file AP_Baro_DPS280.cpp.
Referenced by probe().
Member Function Documentation
calculate_PT()
void AP_Baro_DPS280::calculate_PT (int32_t UT, int32_t UP, float & pressure, float & temperature) private
Definition at line 164 of file AP_Baro_DPS280.cpp.
Referenced by timer().
fix_config_bits16()
void AP_Baro_DPS280::fix_config_bits16 (int16_t & v, uint8_t bits) const private
Definition at line 66 of file AP_Baro_DPS280.cpp.
Referenced by read_calibration().
fix_config_bits32()
void AP_Baro_DPS280::fix_config_bits32 (int32_t & v, uint8_t bits) const private
Definition at line 76 of file AP_Baro_DPS280.cpp.
Referenced by read_calibration(), and timer().
init()
bool AP_Baro_DPS280::init (void) private
Definition at line 123 of file AP_Baro_DPS280.cpp.
Referenced by probe().
probe()
AP_Baro_Backend * AP_Baro_DPS280::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) static
Definition at line 48 of file AP_Baro_DPS280.cpp.
Referenced by AP_Baro::_probe_i2c_barometers(), and AP_Baro::init().
read_calibration()
bool AP_Baro_DPS280::read_calibration (void) private
Definition at line 86 of file AP_Baro_DPS280.cpp.
Referenced by init().
timer()
void AP_Baro_DPS280::timer (void) private
Definition at line 185 of file AP_Baro_DPS280.cpp.
Referenced by init().
update()
void AP_Baro_DPS280::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 222 of file AP_Baro_DPS280.cpp.
Member Data Documentation
calibration
struct AP_Baro_DPS280::dps280_cal AP_Baro_DPS280::calibration private
Referenced by calculate_PT(), init(), and read_calibration().
count
uint32_t AP_Baro_DPS280::count private
Definition at line 38 of file AP_Baro_DPS280.h.
Referenced by timer(), and update().
dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Baro_DPS280::dev private
Definition at line 34 of file AP_Baro_DPS280.h.
Referenced by init(), read_calibration(), and timer().
instance
uint8_t AP_Baro_DPS280::instance private
Definition at line 36 of file AP_Baro_DPS280.h.
Referenced by init(), and update().
pressure_sum
float AP_Baro_DPS280::pressure_sum private
Definition at line 39 of file AP_Baro_DPS280.h.
Referenced by timer(), and update().
temperature_sum
float AP_Baro_DPS280::temperature_sum private
Definition at line 40 of file AP_Baro_DPS280.h.
Referenced by timer(), and update().
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_DPS280.h
libraries/AP_Baro/AP_Baro_DPS280.cpp