APM:Libraries: IRLock Class Reference
IRLock Class Reference abstract
#include <IRLock.h>
Classes
struct AP_IRLock_Flags
struct irlock_target_info
Public Member Functions
virtual void init (int8_t bus)=0
bool healthy () const
uint32_t last_update_ms () const
size_t num_targets () const
virtual bool update ()=0
bool get_unit_vector_body (Vector3f &ret) const
Protected Attributes
struct IRLock::AP_IRLock_Flags _flags
uint32_t _last_update_ms
irlock_target_info _target_info
Detailed Description
Definition at line 26 of file IRLock.h.
Member Function Documentation
get_unit_vector_body()
bool IRLock::get_unit_vector_body (Vector3f & ret) const
Definition at line 12 of file IRLock.cpp.
Referenced by AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
healthy()
bool IRLock::healthy (void) const inline
Definition at line 34 of file IRLock.h.
Referenced by AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
init()
virtual void IRLock::init (int8_t bus) pure virtual
Implemented in AP_IRLock_SITL_Gazebo, AP_IRLock_SITL, and AP_IRLock_I2C.
last_update_ms()
uint32_t IRLock::last_update_ms (void) const inline
Definition at line 37 of file IRLock.h.
Referenced by AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
num_targets()
size_t IRLock::num_targets () const inline
Definition at line 40 of file IRLock.h.
Referenced by AP_IRLock_SITL_Gazebo::update(), AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
update()
virtual bool IRLock::update () pure virtual
Implemented in AP_IRLock_SITL_Gazebo, AP_IRLock_SITL, and AP_IRLock_I2C.
Member Data Documentation
_flags
struct IRLock::AP_IRLock_Flags IRLock::_flags protected
Referenced by get_unit_vector_body(), healthy(), AP_IRLock_SITL_Gazebo::init(), num_targets(), AP_IRLock_I2C::update(), AP_IRLock_SITL::update(), and AP_IRLock_SITL_Gazebo::update().
_last_update_ms
uint32_t IRLock::_last_update_ms protected
Definition at line 56 of file IRLock.h.
Referenced by last_update_ms(), AP_IRLock_I2C::update(), AP_IRLock_SITL::update(), and AP_IRLock_SITL_Gazebo::update().
_target_info
irlock_target_info IRLock::_target_info protected
Definition at line 66 of file IRLock.h.
Referenced by get_unit_vector_body(), AP_IRLock_I2C::read_frames(), AP_IRLock_I2C::update(), AP_IRLock_SITL::update(), and AP_IRLock_SITL_Gazebo::update().
The documentation for this class was generated from the following files:
libraries/AP_IRLock/IRLock.h
libraries/AP_IRLock/IRLock.cpp