APM:Libraries: Linux::PollerThread Class Reference
Linux::PollerThread Class Reference
#include <PollerThread.h>
Public Member Functions
PollerThread ()
virtual ~PollerThread ()
TimerPollable * add_timer (TimerPollable::PeriodicCb cb, TimerPollable::WrapperCb *wrapper, uint32_t timeout_usec)
bool adjust_timer (TimerPollable *p, uint32_t timeout_usec)
void mainloop ()
bool stop () override
Public Member Functions inherited from Linux::Thread
FUNCTOR_TYPEDEF (task_t, void)
Thread (task_t t)
virtual ~Thread ()
bool start (const char *name, int policy, int prio)
bool is_current_thread ()
bool is_started () const
size_t get_stack_usage ()
bool set_stack_size (size_t stack_size)
void set_auto_free (bool auto_free)
bool join ()
Protected Member Functions
void _cleanup_timers ()
Protected Member Functions inherited from Linux::Thread
virtual bool _run ()
void _poison_stack ()
Protected Attributes
Poller _poller {}
std::vector< TimerPollable * > _timers {}
Protected Attributes inherited from Linux::Thread
task_t _task
bool _started = false
bool _should_exit = false
bool _auto_free = false
pthread_t _ctx = 0
struct Linux::Thread::stack_debug _stack_debug
size_t _stack_size = 0
Additional Inherited Members
Static Protected Member Functions inherited from Linux::Thread
static void * _run_trampoline (void *arg)
Detailed Description
Definition at line 63 of file PollerThread.h.
Constructor & Destructor Documentation
PollerThread()
Linux::PollerThread::PollerThread () inline
Definition at line 65 of file PollerThread.h.
~PollerThread()
virtual Linux::PollerThread::~PollerThread () inline virtual
Definition at line 66 of file PollerThread.h.
Member Function Documentation
_cleanup_timers()
void Linux::PollerThread::_cleanup_timers () protected
Definition at line 119 of file PollerThread.cpp.
Referenced by mainloop().
add_timer()
TimerPollable * Linux::PollerThread::add_timer (TimerPollable::PeriodicCb cb, TimerPollable::WrapperCb * wrapper, uint32_t timeout_usec)
Definition at line 89 of file PollerThread.cpp.
Referenced by Linux::SPIDevice::register_periodic_callback(), and Linux::I2CDevice::register_periodic_callback().
adjust_timer()
bool Linux::PollerThread::adjust_timer (TimerPollable * p, uint32_t timeout_usec)
Definition at line 108 of file PollerThread.cpp.
Referenced by Linux::SPIDevice::adjust_periodic_callback(), and Linux::I2CDevice::adjust_periodic_callback().
mainloop()
void Linux::PollerThread::mainloop ()
Definition at line 135 of file PollerThread.cpp.
Referenced by PollerThread().
stop()
bool Linux::PollerThread::stop () override virtual
Reimplemented from Linux::Thread.
Definition at line 150 of file PollerThread.cpp.
Referenced by TEST().
Member Data Documentation
_poller
Poller Linux::PollerThread::_poller {} protected
Definition at line 80 of file PollerThread.h.
Referenced by _cleanup_timers(), add_timer(), mainloop(), and stop().
_timers
std::vector<TimerPollable*> Linux::PollerThread::_timers {} protected
Definition at line 81 of file PollerThread.h.
Referenced by _cleanup_timers(), add_timer(), and adjust_timer().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/PollerThread.h
libraries/AP_HAL_Linux/PollerThread.cpp