APM:Libraries: AP_KDECAN Class Reference
AP_KDECAN Class Reference
#include <AP_KDECAN.h>
Classes
union frame_id_t
struct telemetry_info_t
Public Member Functions
AP_KDECAN ()
AP_KDECAN (const AP_KDECAN &other)=delete
AP_KDECAN & operator= (const AP_KDECAN &)=delete
void init (uint8_t driver_index, bool enable_filters) override
void update ()
bool pre_arm_check (const char *&reason)
void send_mavlink (uint8_t chan)
bool run_enumeration (bool start_stop)
Static Public Member Functions
static AP_KDECAN * get_kdecan (uint8_t driver_index)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum enumeration_state_t : uint8_t { ENUMERATION_STOPPED, ENUMERATION_START, ENUMERATION_STOP, ENUMERATION_RUNNING }
Private Member Functions
void loop ()
Private Attributes
bool _initialized
char _thread_name [9]
uint8_t _driver_index
uavcan::ICanDriver * _can_driver
AP_Int8 _num_poles
uint16_t _esc_present_bitmask
uint8_t _esc_max_node_id
HAL_Semaphore _enum_sem
enum AP_KDECAN::enumeration_state_t _enumeration_state = ENUMERATION_STOPPED
HAL_Semaphore _rc_out_sem
std::atomic< bool > _new_output
uint16_t _scaled_output [KDECAN_MAX_NUM_ESCS]
HAL_Semaphore _telem_sem
struct AP_KDECAN::telemetry_info_t _telemetry [KDECAN_MAX_NUM_ESCS]
Static Private Attributes
static const uint8_t AUTOPILOT_NODE_ID = 0
static const uint8_t BROADCAST_NODE_ID = 1
static const uint8_t ESC_NODE_ID_FIRST = 2
static const uint8_t ESC_INFO_OBJ_ADDR = 0
static const uint8_t SET_PWM_OBJ_ADDR = 1
static const uint8_t VOLTAGE_OBJ_ADDR = 2
static const uint8_t CURRENT_OBJ_ADDR = 3
static const uint8_t RPM_OBJ_ADDR = 4
static const uint8_t TEMPERATURE_OBJ_ADDR = 5
static const uint8_t GET_PWM_INPUT_OBJ_ADDR = 6
static const uint8_t GET_PWM_OUTPUT_OBJ_ADDR = 7
static const uint8_t MCU_ID_OBJ_ADDR = 8
static const uint8_t UPDATE_NODE_ID_OBJ_ADDR = 9
static const uint8_t ENUM_OBJ_ADDR = 10
static const uint8_t TELEMETRY_OBJ_ADDR = 11
static const uint16_t SET_PWM_MIN_INTERVAL_US = 2500
static const uint32_t TELEMETRY_INTERVAL_US = 100000
static const uint32_t SET_PWM_TIMEOUT_US = 2000
static const uint16_t TELEMETRY_TIMEOUT_US = 500
static const uint16_t ENUMERATION_TIMEOUT_MS = 30000
static const uint8_t CAN_IFACE_INDEX = 0
Detailed Description
Definition at line 33 of file AP_KDECAN.h.
Member Enumeration Documentation
enumeration_state_t
enum AP_KDECAN::enumeration_state_t : uint8_t private
Enumerator
ENUMERATION_STOPPED
ENUMERATION_START
ENUMERATION_STOP
ENUMERATION_RUNNING
Definition at line 77 of file AP_KDECAN.h.
Constructor & Destructor Documentation
AP_KDECAN() [1/2]
AP_KDECAN::AP_KDECAN ()
AP_KDECAN() [2/2]
AP_KDECAN::AP_KDECAN (const AP_KDECAN & other) delete
Member Function Documentation
get_kdecan()
static AP_KDECAN* AP_KDECAN::get_kdecan (uint8_t driver_index) static
Referenced by AP_Arming::can_checks(), GCS_MAVLINK::handle_command_preflight_can(), SRV_Channels::push(), and GCS_MAVLINK::try_send_message().
init()
void AP_KDECAN::init (uint8_t driver_index, bool enable_filters) override
loop()
void AP_KDECAN::loop () private
operator=()
AP_KDECAN& AP_KDECAN::operator= (const AP_KDECAN &) delete
pre_arm_check()
bool AP_KDECAN::pre_arm_check (const char *& reason)
Referenced by AP_Arming::can_checks().
run_enumeration()
bool AP_KDECAN::run_enumeration (bool start_stop)
Referenced by GCS_MAVLINK::handle_command_preflight_can().
send_mavlink()
void AP_KDECAN::send_mavlink (uint8_t chan)
Referenced by GCS_MAVLINK::try_send_message().
update()
void AP_KDECAN::update ()
Referenced by SRV_Channels::push().
Member Data Documentation
_can_driver
uavcan::ICanDriver* AP_KDECAN::_can_driver private
Definition at line 67 of file AP_KDECAN.h.
_driver_index
uint8_t AP_KDECAN::_driver_index private
Definition at line 66 of file AP_KDECAN.h.
_enum_sem
HAL_Semaphore AP_KDECAN::_enum_sem private
Definition at line 76 of file AP_KDECAN.h.
_enumeration_state
enum AP_KDECAN::enumeration_state_t AP_KDECAN::_enumeration_state = ENUMERATION_STOPPED private
_esc_max_node_id
uint8_t AP_KDECAN::_esc_max_node_id private
Definition at line 73 of file AP_KDECAN.h.
_esc_present_bitmask
uint16_t AP_KDECAN::_esc_present_bitmask private
Definition at line 72 of file AP_KDECAN.h.
_initialized
bool AP_KDECAN::_initialized private
Definition at line 64 of file AP_KDECAN.h.
_new_output
std::atomic<bool> AP_KDECAN::_new_output private
Definition at line 86 of file AP_KDECAN.h.
_num_poles
AP_Int8 AP_KDECAN::_num_poles private
Definition at line 69 of file AP_KDECAN.h.
_rc_out_sem
HAL_Semaphore AP_KDECAN::_rc_out_sem private
Definition at line 85 of file AP_KDECAN.h.
_scaled_output
uint16_t AP_KDECAN::_scaled_output[KDECAN_MAX_NUM_ESCS] private
Definition at line 87 of file AP_KDECAN.h.
_telem_sem
HAL_Semaphore AP_KDECAN::_telem_sem private
Definition at line 90 of file AP_KDECAN.h.
_telemetry
struct AP_KDECAN::telemetry_info_t AP_KDECAN::_telemetry[KDECAN_MAX_NUM_ESCS] private
_thread_name
char AP_KDECAN::_thread_name[9] private
Definition at line 65 of file AP_KDECAN.h.
AUTOPILOT_NODE_ID
const uint8_t AP_KDECAN::AUTOPILOT_NODE_ID = 0 static private
Definition at line 112 of file AP_KDECAN.h.
BROADCAST_NODE_ID
const uint8_t AP_KDECAN::BROADCAST_NODE_ID = 1 static private
Definition at line 113 of file AP_KDECAN.h.
CAN_IFACE_INDEX
const uint8_t AP_KDECAN::CAN_IFACE_INDEX = 0 static private
Definition at line 136 of file AP_KDECAN.h.
CURRENT_OBJ_ADDR
const uint8_t AP_KDECAN::CURRENT_OBJ_ADDR = 3 static private
Definition at line 119 of file AP_KDECAN.h.
ENUM_OBJ_ADDR
const uint8_t AP_KDECAN::ENUM_OBJ_ADDR = 10 static private
Definition at line 126 of file AP_KDECAN.h.
ENUMERATION_TIMEOUT_MS
const uint16_t AP_KDECAN::ENUMERATION_TIMEOUT_MS = 30000 static private
Definition at line 134 of file AP_KDECAN.h.
ESC_INFO_OBJ_ADDR
const uint8_t AP_KDECAN::ESC_INFO_OBJ_ADDR = 0 static private
Definition at line 116 of file AP_KDECAN.h.
ESC_NODE_ID_FIRST
const uint8_t AP_KDECAN::ESC_NODE_ID_FIRST = 2 static private
Definition at line 114 of file AP_KDECAN.h.
GET_PWM_INPUT_OBJ_ADDR
const uint8_t AP_KDECAN::GET_PWM_INPUT_OBJ_ADDR = 6 static private
Definition at line 122 of file AP_KDECAN.h.
GET_PWM_OUTPUT_OBJ_ADDR
const uint8_t AP_KDECAN::GET_PWM_OUTPUT_OBJ_ADDR = 7 static private
Definition at line 123 of file AP_KDECAN.h.
MCU_ID_OBJ_ADDR
const uint8_t AP_KDECAN::MCU_ID_OBJ_ADDR = 8 static private
Definition at line 124 of file AP_KDECAN.h.
RPM_OBJ_ADDR
const uint8_t AP_KDECAN::RPM_OBJ_ADDR = 4 static private
Definition at line 120 of file AP_KDECAN.h.
SET_PWM_MIN_INTERVAL_US
const uint16_t AP_KDECAN::SET_PWM_MIN_INTERVAL_US = 2500 static private
Definition at line 129 of file AP_KDECAN.h.
SET_PWM_OBJ_ADDR
const uint8_t AP_KDECAN::SET_PWM_OBJ_ADDR = 1 static private
Definition at line 117 of file AP_KDECAN.h.
SET_PWM_TIMEOUT_US
const uint32_t AP_KDECAN::SET_PWM_TIMEOUT_US = 2000 static private
Definition at line 132 of file AP_KDECAN.h.
TELEMETRY_INTERVAL_US
const uint32_t AP_KDECAN::TELEMETRY_INTERVAL_US = 100000 static private
Definition at line 130 of file AP_KDECAN.h.
TELEMETRY_OBJ_ADDR
const uint8_t AP_KDECAN::TELEMETRY_OBJ_ADDR = 11 static private
Definition at line 127 of file AP_KDECAN.h.
TELEMETRY_TIMEOUT_US
const uint16_t AP_KDECAN::TELEMETRY_TIMEOUT_US = 500 static private
Definition at line 133 of file AP_KDECAN.h.
TEMPERATURE_OBJ_ADDR
const uint8_t AP_KDECAN::TEMPERATURE_OBJ_ADDR = 5 static private
Definition at line 121 of file AP_KDECAN.h.
UPDATE_NODE_ID_OBJ_ADDR
const uint8_t AP_KDECAN::UPDATE_NODE_ID_OBJ_ADDR = 9 static private
Definition at line 125 of file AP_KDECAN.h.
var_info
const struct AP_Param::GroupInfo AP_KDECAN::var_info[] static
Definition at line 41 of file AP_KDECAN.h.
VOLTAGE_OBJ_ADDR
const uint8_t AP_KDECAN::VOLTAGE_OBJ_ADDR = 2 static private
Definition at line 118 of file AP_KDECAN.h.
The documentation for this class was generated from the following file:
libraries/AP_KDECAN/AP_KDECAN.h