APM:Libraries: AP_VisualOdom Class Reference
AP_VisualOdom Class Reference
#include <AP_VisualOdom.h>
Classes
struct VisualOdomState
Public Types
enum AP_VisualOdom_Type { AP_VisualOdom_Type_None = 0, AP_VisualOdom_Type_MAV = 1 }
Public Member Functions
AP_VisualOdom ()
void init ()
void update ()
bool enabled () const
bool healthy () const
const Vector3f & get_pos_offset (void) const
void handle_msg (mavlink_message_t *msg)
Static Public Member Functions
static AP_VisualOdom * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
const Vector3f & get_angle_delta () const
const Vector3f & get_position_delta () const
uint64_t get_time_delta_usec () const
float get_confidence () const
uint32_t get_last_update_ms () const
Private Attributes
AP_Int8 _type
AP_Vector3f _pos_offset
AP_Int8 _orientation
AP_VisualOdom_Backend * _driver
VisualOdomState _state
Static Private Attributes
static AP_VisualOdom * _singleton
Friends
class AP_VisualOdom_Backend
Detailed Description
Definition at line 26 of file AP_VisualOdom.h.
Member Enumeration Documentation
AP_VisualOdom_Type
enum AP_VisualOdom::AP_VisualOdom_Type
Enumerator
AP_VisualOdom_Type_None
AP_VisualOdom_Type_MAV
Definition at line 39 of file AP_VisualOdom.h.
Constructor & Destructor Documentation
AP_VisualOdom()
AP_VisualOdom::AP_VisualOdom ()
Definition at line 62 of file AP_VisualOdom.cpp.
Member Function Documentation
enabled()
bool AP_VisualOdom::enabled (void) const
Definition at line 83 of file AP_VisualOdom.cpp.
Referenced by handle_msg(), healthy(), and update().
get_angle_delta()
const Vector3f& AP_VisualOdom::get_angle_delta () const inline private
Definition at line 81 of file AP_VisualOdom.h.
Referenced by update().
get_confidence()
float AP_VisualOdom::get_confidence () const inline private
Definition at line 84 of file AP_VisualOdom.h.
Referenced by update().
get_last_update_ms()
uint32_t AP_VisualOdom::get_last_update_ms () const inline private
Definition at line 85 of file AP_VisualOdom.h.
Referenced by update().
get_pos_offset()
const Vector3f& AP_VisualOdom::get_pos_offset (void) const inline
Definition at line 69 of file AP_VisualOdom.h.
Referenced by update().
get_position_delta()
const Vector3f& AP_VisualOdom::get_position_delta () const inline private
Definition at line 82 of file AP_VisualOdom.h.
Referenced by update().
get_singleton()
static AP_VisualOdom* AP_VisualOdom::get_singleton (void) inline static
Definition at line 34 of file AP_VisualOdom.h.
Referenced by AP::visualodom().
get_time_delta_usec()
uint64_t AP_VisualOdom::get_time_delta_usec () const inline private
Definition at line 83 of file AP_VisualOdom.h.
Referenced by update().
handle_msg()
void AP_VisualOdom::handle_msg (mavlink_message_t * msg)
Definition at line 129 of file AP_VisualOdom.cpp.
Referenced by GCS_MAVLINK::handle_vision_position_delta().
healthy()
bool AP_VisualOdom::healthy (void) const
Definition at line 118 of file AP_VisualOdom.cpp.
init()
void AP_VisualOdom::init (void)
Definition at line 74 of file AP_VisualOdom.cpp.
update()
void AP_VisualOdom::update (void)
Definition at line 89 of file AP_VisualOdom.cpp.
Friends And Related Function Documentation
AP_VisualOdom_Backend
friend class AP_VisualOdom_Backend friend
Definition at line 29 of file AP_VisualOdom.h.
Member Data Documentation
_driver
AP_VisualOdom_Backend* AP_VisualOdom::_driver private
Definition at line 93 of file AP_VisualOdom.h.
Referenced by enabled(), handle_msg(), and init().
_orientation
AP_Int8 AP_VisualOdom::_orientation private
Definition at line 90 of file AP_VisualOdom.h.
Referenced by AP_VisualOdom_Backend::set_deltas().
_pos_offset
AP_Vector3f AP_VisualOdom::_pos_offset private
Definition at line 89 of file AP_VisualOdom.h.
Referenced by get_pos_offset().
_singleton
AP_VisualOdom * AP_VisualOdom::_singleton static private
Definition at line 78 of file AP_VisualOdom.h.
Referenced by AP_VisualOdom(), and get_singleton().
_state
VisualOdomState AP_VisualOdom::_state private
Definition at line 96 of file AP_VisualOdom.h.
Referenced by get_angle_delta(), get_confidence(), get_last_update_ms(), get_position_delta(), get_time_delta_usec(), healthy(), AP_VisualOdom_Backend::set_deltas(), and update().
_type
AP_Int8 AP_VisualOdom::_type private
Definition at line 88 of file AP_VisualOdom.h.
Referenced by enabled(), and init().
var_info
const AP_Param::GroupInfo AP_VisualOdom::var_info static
Definition at line 74 of file AP_VisualOdom.h.
Referenced by AP_VisualOdom().
The documentation for this class was generated from the following files:
libraries/AP_VisualOdom/AP_VisualOdom.h
libraries/AP_VisualOdom/AP_VisualOdom.cpp