APM:Libraries: AP_RangeFinder_PWM Class Reference
AP_RangeFinder_PWM Class Reference
#include <AP_RangeFinder_PWM.h>
Public Member Functions
AP_RangeFinder_PWM (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, float &_estimated_terrain_height)
~AP_RangeFinder_PWM (void)
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void handle_msg (mavlink_message_t *msg)
enum Rotation orientation () const
uint16_t distance_cm () const
uint16_t voltage_mv () const
int16_t max_distance_cm () const
int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::RangeFinder_Status status () const
RangeFinder::RangeFinder_Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
Static Public Member Functions
static bool detect ()
Protected Member Functions
bool get_reading (uint16_t &reading_cm)
MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status ()
void set_status (RangeFinder::RangeFinder_Status status)
Private Member Functions
void irq_handler (uint8_t pin, bool pin_high, uint32_t timestamp_us)
void check_pin ()
void check_stop_pin ()
void check_pins ()
bool out_of_range (void) const
Private Attributes
int8_t last_pin
uint32_t irq_value_us
uint16_t irq_sample_count
uint32_t irq_pulse_start_us
uint8_t last_stop_pin = -1
float & estimated_terrain_height
bool was_out_of_range = -1
Additional Inherited Members
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::RangeFinder_Type _backend_type
Detailed Description
Definition at line 20 of file AP_RangeFinder_PWM.h.
Constructor & Destructor Documentation
AP_RangeFinder_PWM()
AP_RangeFinder_PWM::AP_RangeFinder_PWM (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, float & _estimated_terrain_height)
Definition at line 26 of file AP_RangeFinder_PWM.cpp.
~AP_RangeFinder_PWM()
AP_RangeFinder_PWM::~AP_RangeFinder_PWM (void) inline
Definition at line 29 of file AP_RangeFinder_PWM.h.
Member Function Documentation
_get_mav_distance_sensor_type()
MAV_DISTANCE_SENSOR AP_RangeFinder_PWM::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 41 of file AP_RangeFinder_PWM.h.
check_pin()
void AP_RangeFinder_PWM::check_pin () private
Definition at line 74 of file AP_RangeFinder_PWM.cpp.
Referenced by check_pins().
check_pins()
void AP_RangeFinder_PWM::check_pins () private
Definition at line 128 of file AP_RangeFinder_PWM.cpp.
Referenced by update().
check_stop_pin()
void AP_RangeFinder_PWM::check_stop_pin () private
Definition at line 117 of file AP_RangeFinder_PWM.cpp.
Referenced by check_pins().
detect()
bool AP_RangeFinder_PWM::detect () static
Definition at line 37 of file AP_RangeFinder_PWM.cpp.
Referenced by RangeFinder::detect_instance().
get_reading()
bool AP_RangeFinder_PWM::get_reading (uint16_t & reading_cm) protected
Definition at line 57 of file AP_RangeFinder_PWM.cpp.
Referenced by update().
irq_handler()
void AP_RangeFinder_PWM::irq_handler (uint8_t pin, bool pin_high, uint32_t timestamp_us) private
Definition at line 43 of file AP_RangeFinder_PWM.cpp.
Referenced by check_pin().
out_of_range()
bool AP_RangeFinder_PWM::out_of_range (void) const private
Definition at line 183 of file AP_RangeFinder_PWM.cpp.
Referenced by update().
update()
void AP_RangeFinder_PWM::update (void) override virtual
Implements AP_RangeFinder_Backend.
Definition at line 138 of file AP_RangeFinder_PWM.cpp.
Member Data Documentation
estimated_terrain_height
float& AP_RangeFinder_PWM::estimated_terrain_height private
Definition at line 61 of file AP_RangeFinder_PWM.h.
Referenced by out_of_range().
irq_pulse_start_us
uint32_t AP_RangeFinder_PWM::irq_pulse_start_us private
Definition at line 52 of file AP_RangeFinder_PWM.h.
Referenced by irq_handler().
irq_sample_count
uint16_t AP_RangeFinder_PWM::irq_sample_count private
Definition at line 51 of file AP_RangeFinder_PWM.h.
Referenced by get_reading(), and irq_handler().
irq_value_us
uint32_t AP_RangeFinder_PWM::irq_value_us private
Definition at line 50 of file AP_RangeFinder_PWM.h.
Referenced by get_reading(), and irq_handler().
last_pin
int8_t AP_RangeFinder_PWM::last_pin private
Definition at line 47 of file AP_RangeFinder_PWM.h.
Referenced by check_pin(), and update().
last_stop_pin
uint8_t AP_RangeFinder_PWM::last_stop_pin = -1 private
Definition at line 59 of file AP_RangeFinder_PWM.h.
Referenced by check_stop_pin().
was_out_of_range
bool AP_RangeFinder_PWM::was_out_of_range = -1 private
Definition at line 65 of file AP_RangeFinder_PWM.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_PWM.h
libraries/AP_RangeFinder/AP_RangeFinder_PWM.cpp