APM:Libraries: AP_RSSI Class Reference
AP_RSSI Class Reference
#include <AP_RSSI.h>
Classes
struct PWMState
Public Types
enum RssiType {
RssiType::TYPE_DISABLED = 0, RssiType::ANALOG_PIN = 1, RssiType::RC_CHANNEL_VALUE = 2, RssiType::RECEIVER = 3,
RssiType::PWM_PIN = 4
}
Public Member Functions
AP_RSSI ()
AP_RSSI (const AP_RSSI &other)=delete
AP_RSSI & operator= (const AP_RSSI &)=delete
~AP_RSSI (void)
void init ()
bool enabled () const
float read_receiver_rssi ()
uint8_t read_receiver_rssi_uint8 ()
Static Public Member Functions
static AP_RSSI * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
float read_pin_rssi ()
void check_pwm_pin_rssi ()
float read_channel_rssi ()
float read_pwm_pin_rssi ()
float scale_and_constrain_float_rssi (float current_rssi_value, float low_rssi_range, float high_rssi_range)
void irq_handler (uint8_t pin, bool pin_state, uint32_t timestamp)
Private Attributes
AP_Int8 rssi_type
AP_Int8 rssi_analog_pin
AP_Float rssi_analog_pin_range_low
AP_Float rssi_analog_pin_range_high
AP_Int8 rssi_channel
AP_Int16 rssi_channel_low_pwm_value
AP_Int16 rssi_channel_high_pwm_value
AP_HAL::AnalogSource * rssi_analog_source
struct AP_RSSI::PWMState pwm_state
Static Private Attributes
static AP_RSSI * _singleton = nullptr
Detailed Description
Definition at line 21 of file AP_RSSI.h.
Member Enumeration Documentation
RssiType
enum AP_RSSI::RssiType strong
Enumerator
TYPE_DISABLED
ANALOG_PIN
RC_CHANNEL_VALUE
RECEIVER
PWM_PIN
Definition at line 24 of file AP_RSSI.h.
Constructor & Destructor Documentation
AP_RSSI() [1/2]
AP_RSSI::AP_RSSI ()
Definition at line 100 of file AP_RSSI.cpp.
AP_RSSI() [2/2]
AP_RSSI::AP_RSSI (const AP_RSSI & other) delete
~AP_RSSI()
AP_RSSI::~AP_RSSI (void)
Definition at line 110 of file AP_RSSI.cpp.
Member Function Documentation
check_pwm_pin_rssi()
void AP_RSSI::check_pwm_pin_rssi () private
Definition at line 186 of file AP_RSSI.cpp.
Referenced by read_pwm_pin_rssi().
enabled()
bool AP_RSSI::enabled (void) const inline
Definition at line 47 of file AP_RSSI.h.
get_singleton()
AP_RSSI * AP_RSSI::get_singleton (void) static
Definition at line 117 of file AP_RSSI.cpp.
Referenced by AP_OSD_Screen::draw_rssi(), and AP::rssi().
init()
void AP_RSSI::init (void)
Definition at line 123 of file AP_RSSI.cpp.
irq_handler()
void AP_RSSI::irq_handler (uint8_t pin, bool pin_state, uint32_t timestamp) private
Definition at line 291 of file AP_RSSI.cpp.
Referenced by check_pwm_pin_rssi().
operator=()
AP_RSSI& AP_RSSI::operator= (const AP_RSSI &) delete
read_channel_rssi()
float AP_RSSI::read_channel_rssi () private
Definition at line 175 of file AP_RSSI.cpp.
Referenced by read_receiver_rssi().
read_pin_rssi()
float AP_RSSI::read_pin_rssi () private
Definition at line 166 of file AP_RSSI.cpp.
Referenced by read_receiver_rssi().
read_pwm_pin_rssi()
float AP_RSSI::read_pwm_pin_rssi () private
Definition at line 228 of file AP_RSSI.cpp.
Referenced by read_receiver_rssi().
read_receiver_rssi()
float AP_RSSI::read_receiver_rssi ()
Definition at line 132 of file AP_RSSI.cpp.
Referenced by read_receiver_rssi_uint8(), and AP_Logger::Write_RSSI().
read_receiver_rssi_uint8()
uint8_t AP_RSSI::read_receiver_rssi_uint8 ()
Definition at line 157 of file AP_RSSI.cpp.
Referenced by AP_OSD_Screen::draw_rssi(), GCS_MAVLINK::send_rc_channels(), and GCS_MAVLINK::send_rc_channels_raw().
scale_and_constrain_float_rssi()
float AP_RSSI::scale_and_constrain_float_rssi (float current_rssi_value, float low_rssi_range, float high_rssi_range) private
Definition at line 261 of file AP_RSSI.cpp.
Referenced by read_channel_rssi(), read_pin_rssi(), and read_pwm_pin_rssi().
Member Data Documentation
_singleton
AP_RSSI * AP_RSSI::_singleton = nullptr static private
Definition at line 62 of file AP_RSSI.h.
Referenced by AP_RSSI(), and get_singleton().
pwm_state
struct AP_RSSI::PWMState AP_RSSI::pwm_state private
Referenced by check_pwm_pin_rssi(), irq_handler(), and read_pwm_pin_rssi().
rssi_analog_pin
AP_Int8 AP_RSSI::rssi_analog_pin private
Definition at line 66 of file AP_RSSI.h.
Referenced by check_pwm_pin_rssi(), and read_pin_rssi().
rssi_analog_pin_range_high
AP_Float AP_RSSI::rssi_analog_pin_range_high private
Definition at line 68 of file AP_RSSI.h.
Referenced by read_pin_rssi().
rssi_analog_pin_range_low
AP_Float AP_RSSI::rssi_analog_pin_range_low private
Definition at line 67 of file AP_RSSI.h.
Referenced by read_pin_rssi().
rssi_analog_source
AP_HAL::AnalogSource* AP_RSSI::rssi_analog_source private
Definition at line 75 of file AP_RSSI.h.
Referenced by init(), and read_pin_rssi().
rssi_channel
AP_Int8 AP_RSSI::rssi_channel private
Definition at line 69 of file AP_RSSI.h.
Referenced by read_channel_rssi().
rssi_channel_high_pwm_value
AP_Int16 AP_RSSI::rssi_channel_high_pwm_value private
Definition at line 71 of file AP_RSSI.h.
Referenced by read_channel_rssi(), and read_pwm_pin_rssi().
rssi_channel_low_pwm_value
AP_Int16 AP_RSSI::rssi_channel_low_pwm_value private
Definition at line 70 of file AP_RSSI.h.
Referenced by read_channel_rssi(), and read_pwm_pin_rssi().
rssi_type
AP_Int8 AP_RSSI::rssi_type private
Definition at line 65 of file AP_RSSI.h.
Referenced by enabled(), and read_receiver_rssi().
var_info
const AP_Param::GroupInfo AP_RSSI::var_info static
Definition at line 58 of file AP_RSSI.h.
Referenced by AP_RSSI().
The documentation for this class was generated from the following files:
libraries/AP_RSSI/AP_RSSI.h
libraries/AP_RSSI/AP_RSSI.cpp