APM:Libraries: Linux::Poller Class Reference
Linux::Poller Class Reference
#include <Poller.h>
Public Member Functions
Poller ()
~Poller ()
bool operator! () const
operator bool () const
bool register_pollable (Pollable *p, uint32_t events)
void unregister_pollable (const Pollable *p)
int poll () const
void wakeup () const
Private Attributes
int _epfd = -1
WakeupPollable _wakeup {}
Detailed Description
Definition at line 73 of file Poller.h.
Constructor & Destructor Documentation
Poller()
Linux::Poller::Poller ()
Definition at line 43 of file Poller.cpp.
~Poller()
Linux::Poller::~Poller () inline
Definition at line 77 of file Poller.h.
Member Function Documentation
operator bool()
Linux::Poller::operator bool () const inline explicit
Definition at line 93 of file Poller.h.
operator!()
bool Linux::Poller::operator! () const inline
Definition at line 88 of file Poller.h.
poll()
int Linux::Poller::poll () const
Definition at line 100 of file Poller.cpp.
Referenced by Linux::PollerThread::mainloop().
register_pollable()
bool Linux::Poller::register_pollable (Pollable * p, uint32_t events)
Definition at line 72 of file Poller.cpp.
Referenced by Linux::PollerThread::add_timer(), and Poller().
unregister_pollable()
void Linux::Poller::unregister_pollable (const Pollable * p)
Definition at line 93 of file Poller.cpp.
Referenced by Linux::PollerThread::_cleanup_timers(), and ~Poller().
wakeup()
void Linux::Poller::wakeup () const
Definition at line 134 of file Poller.cpp.
Referenced by Linux::PollerThread::stop().
Member Data Documentation
_epfd
int Linux::Poller::_epfd = -1 private
Definition at line 123 of file Poller.h.
Referenced by operator bool(), operator!(), poll(), Poller(), register_pollable(), unregister_pollable(), and ~Poller().
_wakeup
WakeupPollable Linux::Poller::_wakeup {} private
Definition at line 124 of file Poller.h.
Referenced by Poller(), wakeup(), and ~Poller().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Poller.h
libraries/AP_HAL_Linux/Poller.cpp