APM:Libraries: AP_GPS_GSOF Class Reference
AP_GPS_GSOF Class Reference
#include <AP_GPS_GSOF.h>
Classes
struct gsof_msg_parser_t
Public Member Functions
AP_GPS_GSOF (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
AP_GPS::GPS_Status highest_supported_status (void) override
bool read () override
const char * name () const override
Public Member Functions inherited from AP_GPS_Backend
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual bool is_configured (void)
virtual void inject_data (const uint8_t *data, uint16_t len)
virtual bool supports_mavlink_gps_rtk_message ()
virtual void send_mavlink_gps_rtk (mavlink_channel_t chan)
virtual void broadcast_configuration_failure_reason (void) const
virtual void handle_msg (const mavlink_message_t *msg)
virtual bool get_lag (float &lag) const
virtual bool is_healthy (void) const
void broadcast_gps_type () const
virtual void Write_AP_Logger_Log_Startup_messages () const
virtual bool prepare_for_arming (void)
Private Member Functions
bool parse (uint8_t temp)
bool process_message ()
void requestBaud (uint8_t portindex)
void requestGSOF (uint8_t messagetype, uint8_t portindex)
double SwapDouble (uint8_t *src, uint32_t pos)
float SwapFloat (uint8_t *src, uint32_t pos)
uint32_t SwapUint32 (uint8_t *src, uint32_t pos)
uint16_t SwapUint16 (uint8_t *src, uint32_t pos)
Private Attributes
struct AP_GPS_GSOF::gsof_msg_parser_t gsof_msg
uint8_t packetcount = 0
uint32_t gsofmsg_time = 0
uint8_t gsofmsgreq_index = 0
uint8_t gsofmsgreq [5] = {1,2,8,9,12}
Static Private Attributes
static const uint8_t GSOF_STX = 0x02
static const uint8_t GSOF_ETX = 0x03
Additional Inherited Members
Protected Member Functions inherited from AP_GPS_Backend
int32_t swap_int32 (int32_t v) const
int16_t swap_int16 (int16_t v) const
void fill_3d_velocity (void)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
void _detection_message (char *buffer, uint8_t buflen) const
bool should_log () const
void set_uart_timestamp (uint16_t nbytes)
void check_new_itow (uint32_t itow, uint32_t msg_length)
Protected Attributes inherited from AP_GPS_Backend
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
Detailed Description
Definition at line 25 of file AP_GPS_GSOF.h.
Constructor & Destructor Documentation
AP_GPS_GSOF()
AP_GPS_GSOF::AP_GPS_GSOF (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port)
Definition at line 43 of file AP_GPS_GSOF.cpp.
Member Function Documentation
highest_supported_status()
AP_GPS::GPS_Status AP_GPS_GSOF::highest_supported_status (void) inline override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 30 of file AP_GPS_GSOF.h.
name()
const char* AP_GPS_GSOF::name () const inline override virtual
Implements AP_GPS_Backend.
Definition at line 37 of file AP_GPS_GSOF.h.
parse()
bool AP_GPS_GSOF::parse (uint8_t temp) private
Definition at line 84 of file AP_GPS_GSOF.cpp.
Referenced by read().
process_message()
bool AP_GPS_GSOF::process_message (void) private
Definition at line 245 of file AP_GPS_GSOF.cpp.
Referenced by parse().
read()
bool AP_GPS_GSOF::read (void) override virtual
Implements AP_GPS_Backend.
Definition at line 61 of file AP_GPS_GSOF.cpp.
requestBaud()
void AP_GPS_GSOF::requestBaud (uint8_t portindex) private
Definition at line 140 of file AP_GPS_GSOF.cpp.
Referenced by AP_GPS_GSOF().
requestGSOF()
void AP_GPS_GSOF::requestGSOF (uint8_t messagetype, uint8_t portindex) private
Definition at line 161 of file AP_GPS_GSOF.cpp.
Referenced by read().
SwapDouble()
double AP_GPS_GSOF::SwapDouble (uint8_t * src, uint32_t pos) private
Definition at line 183 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
SwapFloat()
float AP_GPS_GSOF::SwapFloat (uint8_t * src, uint32_t pos) private
Definition at line 202 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
SwapUint16()
uint16_t AP_GPS_GSOF::SwapUint16 (uint8_t * src, uint32_t pos) private
Definition at line 232 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
SwapUint32()
uint32_t AP_GPS_GSOF::SwapUint32 (uint8_t * src, uint32_t pos) private
Definition at line 217 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
Member Data Documentation
GSOF_ETX
const uint8_t AP_GPS_GSOF::GSOF_ETX = 0x03 static private
Definition at line 77 of file AP_GPS_GSOF.h.
gsof_msg
struct AP_GPS_GSOF::gsof_msg_parser_t AP_GPS_GSOF::gsof_msg private
Referenced by AP_GPS_GSOF(), parse(), and process_message().
GSOF_STX
const uint8_t AP_GPS_GSOF::GSOF_STX = 0x02 static private
Definition at line 76 of file AP_GPS_GSOF.h.
Referenced by parse().
gsofmsg_time
uint32_t AP_GPS_GSOF::gsofmsg_time = 0 private
Definition at line 81 of file AP_GPS_GSOF.h.
Referenced by AP_GPS_GSOF(), and read().
gsofmsgreq
uint8_t AP_GPS_GSOF::gsofmsgreq[5] = {1,2,8,9,12} private
Definition at line 83 of file AP_GPS_GSOF.h.
Referenced by read().
gsofmsgreq_index
uint8_t AP_GPS_GSOF::gsofmsgreq_index = 0 private
Definition at line 82 of file AP_GPS_GSOF.h.
Referenced by read().
packetcount
uint8_t AP_GPS_GSOF::packetcount = 0 private
Definition at line 79 of file AP_GPS_GSOF.h.
Referenced by requestBaud(), and requestGSOF().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS_GSOF.h
libraries/AP_GPS/AP_GPS_GSOF.cpp