APM:Libraries: AP_InertialSensor::BatchSampler Class Reference
AP_InertialSensor::BatchSampler Class Reference
#include <AP_InertialSensor.h>
Public Member Functions
BatchSampler (const AP_InertialSensor &imu)
void init ()
void sample (uint8_t instance, IMU_SENSOR_TYPE _type, uint64_t sample_us, const Vector3f &sample)
void periodic ()
bool doing_sensor_rate_logging () const
bool doing_post_filter_logging () const
Public Attributes
AP_Int16 _required_count
AP_Int8 _sensor_mask
AP_Int8 _batch_options_mask
AP_Int16 samples_per_msg
AP_Int8 push_interval_ms
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum batch_opt_t { BATCH_OPT_SENSOR_RATE = (1<<0), BATCH_OPT_POST_FILTER = (1<<1) }
Private Member Functions
void rotate_to_next_sensor ()
void update_doing_sensor_rate_logging ()
bool should_log (uint8_t instance, IMU_SENSOR_TYPE type)
void push_data_to_log ()
Private Attributes
uint64_t measurement_started_us
bool initialised: 1
bool isbh_sent: 1
bool _doing_sensor_rate_logging: 1
bool _doing_post_filter_logging: 1
uint8_t instance: 3
AP_InertialSensor::IMU_SENSOR_TYPE type: 1
uint16_t isb_seqnum
int16_t * data_x
int16_t * data_y
int16_t * data_z
uint16_t data_write_offset
uint16_t data_read_offset
uint32_t last_sent_ms
uint16_t multiplier
const AP_InertialSensor & _imu
Detailed Description
Definition at line 285 of file AP_InertialSensor.h.
Member Enumeration Documentation
batch_opt_t
enum AP_InertialSensor::BatchSampler::batch_opt_t private
Enumerator
BATCH_OPT_SENSOR_RATE
BATCH_OPT_POST_FILTER
Definition at line 325 of file AP_InertialSensor.h.
Constructor & Destructor Documentation
BatchSampler()
AP_InertialSensor::BatchSampler::BatchSampler (const AP_InertialSensor & imu) inline
Definition at line 287 of file AP_InertialSensor.h.
Member Function Documentation
doing_post_filter_logging()
bool AP_InertialSensor::BatchSampler::doing_post_filter_logging () const inline
Definition at line 300 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::_notify_new_gyro_raw_sample().
doing_sensor_rate_logging()
bool AP_InertialSensor::BatchSampler::doing_sensor_rate_logging () const inline
Definition at line 299 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_sensor_rate_sample(), AP_InertialSensor_Backend::_notify_new_gyro_sensor_rate_sample(), AP_InertialSensor_Backend::log_accel_raw(), and AP_InertialSensor_Backend::log_gyro_raw().
init()
void AP_InertialSensor::BatchSampler::init (void)
Definition at line 47 of file BatchSampler.cpp.
Referenced by AP_InertialSensor::init().
periodic()
void AP_InertialSensor::BatchSampler::periodic ()
Definition at line 80 of file BatchSampler.cpp.
Referenced by AP_InertialSensor::periodic().
push_data_to_log()
void AP_InertialSensor::BatchSampler::push_data_to_log () private
Definition at line 171 of file BatchSampler.cpp.
rotate_to_next_sensor()
void AP_InertialSensor::BatchSampler::rotate_to_next_sensor () private
Definition at line 112 of file BatchSampler.cpp.
Referenced by init().
sample()
void AP_InertialSensor::BatchSampler::sample (uint8_t instance, AP_InertialSensor::IMU_SENSOR_TYPE _type, uint64_t sample_us, const Vector3f & sample)
Definition at line 272 of file BatchSampler.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_sensor_rate_sample(), AP_InertialSensor_Backend::_notify_new_gyro_sensor_rate_sample(), AP_InertialSensor_Backend::log_accel_raw(), and AP_InertialSensor_Backend::log_gyro_raw().
should_log()
bool AP_InertialSensor::BatchSampler::should_log (uint8_t instance, IMU_SENSOR_TYPE type) private
Definition at line 244 of file BatchSampler.cpp.
update_doing_sensor_rate_logging()
void AP_InertialSensor::BatchSampler::update_doing_sensor_rate_logging () private
Definition at line 88 of file BatchSampler.cpp.
Member Data Documentation
_batch_options_mask
AP_Int8 AP_InertialSensor::BatchSampler::_batch_options_mask
Definition at line 308 of file AP_InertialSensor.h.
_doing_post_filter_logging
bool AP_InertialSensor::BatchSampler::_doing_post_filter_logging private
Definition at line 341 of file AP_InertialSensor.h.
Referenced by doing_post_filter_logging().
_doing_sensor_rate_logging
bool AP_InertialSensor::BatchSampler::_doing_sensor_rate_logging private
Definition at line 340 of file AP_InertialSensor.h.
Referenced by doing_sensor_rate_logging().
_imu
const AP_InertialSensor& AP_InertialSensor::BatchSampler::_imu private
Definition at line 355 of file AP_InertialSensor.h.
_required_count
AP_Int16 AP_InertialSensor::BatchSampler::_required_count
Definition at line 306 of file AP_InertialSensor.h.
Referenced by init().
_sensor_mask
AP_Int8 AP_InertialSensor::BatchSampler::_sensor_mask
Definition at line 307 of file AP_InertialSensor.h.
Referenced by init().
data_read_offset
uint16_t AP_InertialSensor::BatchSampler::data_read_offset private
Definition at line 349 of file AP_InertialSensor.h.
data_write_offset
uint16_t AP_InertialSensor::BatchSampler::data_write_offset private
Definition at line 348 of file AP_InertialSensor.h.
data_x
int16_t* AP_InertialSensor::BatchSampler::data_x private
Definition at line 345 of file AP_InertialSensor.h.
Referenced by init().
data_y
int16_t* AP_InertialSensor::BatchSampler::data_y private
Definition at line 346 of file AP_InertialSensor.h.
Referenced by init().
data_z
int16_t* AP_InertialSensor::BatchSampler::data_z private
Definition at line 347 of file AP_InertialSensor.h.
Referenced by init().
initialised
bool AP_InertialSensor::BatchSampler::initialised private
Definition at line 338 of file AP_InertialSensor.h.
Referenced by init().
instance
uint8_t AP_InertialSensor::BatchSampler::instance private
Definition at line 342 of file AP_InertialSensor.h.
isb_seqnum
uint16_t AP_InertialSensor::BatchSampler::isb_seqnum private
Definition at line 344 of file AP_InertialSensor.h.
isbh_sent
bool AP_InertialSensor::BatchSampler::isbh_sent private
Definition at line 339 of file AP_InertialSensor.h.
last_sent_ms
uint32_t AP_InertialSensor::BatchSampler::last_sent_ms private
Definition at line 350 of file AP_InertialSensor.h.
measurement_started_us
uint64_t AP_InertialSensor::BatchSampler::measurement_started_us private
Definition at line 336 of file AP_InertialSensor.h.
multiplier
uint16_t AP_InertialSensor::BatchSampler::multiplier private
Definition at line 353 of file AP_InertialSensor.h.
push_interval_ms
AP_Int8 AP_InertialSensor::BatchSampler::push_interval_ms
Definition at line 319 of file AP_InertialSensor.h.
samples_per_msg
AP_Int16 AP_InertialSensor::BatchSampler::samples_per_msg
Definition at line 318 of file AP_InertialSensor.h.
type
AP_InertialSensor::IMU_SENSOR_TYPE AP_InertialSensor::BatchSampler::type private
Definition at line 343 of file AP_InertialSensor.h.
var_info
const AP_Param::GroupInfo AP_InertialSensor::BatchSampler::var_info static
Definition at line 303 of file AP_InertialSensor.h.
Referenced by BatchSampler().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor.h
libraries/AP_InertialSensor/BatchSampler.cpp