APM:Libraries: AP_Compass_HMC5843 Class Reference
AP_Compass_HMC5843 Class Reference
#include <AP_Compass_HMC5843.h>
Public Member Functions
virtual ~AP_Compass_HMC5843 ()
void read () override
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * probe (AP_HAL::OwnPtr< AP_HAL::Device > dev, bool force_external=false, enum Rotation rotation=ROTATION_NONE)
static AP_Compass_Backend * probe_mpu6000 (enum Rotation rotation=ROTATION_NONE)
Static Public Attributes
static constexpr const char * name = "HMC5843"
Private Member Functions
AP_Compass_HMC5843 (AP_HMC5843_BusDriver *bus, bool force_external, enum Rotation rotation)
bool init ()
bool _check_whoami ()
bool _calibrate ()
bool _setup_sampling_mode ()
void _timer ()
bool _read_sample ()
void _take_sample ()
Private Attributes
AP_HMC5843_BusDriver * _bus
Vector3f _scaling
float _gain_scale
int16_t _mag_x
int16_t _mag_y
int16_t _mag_z
uint8_t _compass_instance
enum Rotation _rotation
bool _initialised:1
bool _force_external:1
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01, DEVTYPE_HMC5883 = 0x07, DEVTYPE_LSM303D = 0x02, DEVTYPE_AK8963 = 0x04,
DEVTYPE_BMM150 = 0x05, DEVTYPE_LSM9DS1 = 0x06, DEVTYPE_LIS3MDL = 0x08, DEVTYPE_AK09916 = 0x09,
DEVTYPE_IST8310 = 0x0A, DEVTYPE_ICM20948 = 0x0B, DEVTYPE_MMC3416 = 0x0C, DEVTYPE_QMC5883L = 0x0D,
DEVTYPE_MAG3110 = 0x0E, DEVTYPE_SITL = 0x0F, DEVTYPE_IST8308 = 0x10, DEVTYPE_RM3100 = 0x11
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
HAL_Semaphore_Recursive _sem
Detailed Description
Definition at line 16 of file AP_Compass_HMC5843.h.
Constructor & Destructor Documentation
~AP_Compass_HMC5843()
virtual AP_Compass_HMC5843::~AP_Compass_HMC5843 () virtual
AP_Compass_HMC5843()
AP_Compass_HMC5843::AP_Compass_HMC5843 (AP_HMC5843_BusDriver * bus, bool force_external, enum Rotation rotation) private
Member Function Documentation
_calibrate()
bool AP_Compass_HMC5843::_calibrate () private
_check_whoami()
bool AP_Compass_HMC5843::_check_whoami () private
_read_sample()
bool AP_Compass_HMC5843::_read_sample () private
_setup_sampling_mode()
bool AP_Compass_HMC5843::_setup_sampling_mode () private
_take_sample()
void AP_Compass_HMC5843::_take_sample () private
_timer()
void AP_Compass_HMC5843::_timer () private
init()
bool AP_Compass_HMC5843::init () private
probe()
static AP_Compass_Backend* AP_Compass_HMC5843::probe (AP_HAL::OwnPtr< AP_HAL::Device > dev, bool force_external = false, enum Rotation rotation = ROTATION_NONE) static
Referenced by Compass::_detect_backends(), and Compass::_probe_external_i2c_compasses().
probe_mpu6000()
static AP_Compass_Backend* AP_Compass_HMC5843::probe_mpu6000 (enum Rotation rotation = ROTATION_NONE) static
Referenced by Compass::_detect_backends().
read()
void AP_Compass_HMC5843::read () override virtual
Implements AP_Compass_Backend.
Member Data Documentation
_bus
AP_HMC5843_BusDriver* AP_Compass_HMC5843::_bus private
Definition at line 48 of file AP_Compass_HMC5843.h.
_compass_instance
uint8_t AP_Compass_HMC5843::_compass_instance private
Definition at line 57 of file AP_Compass_HMC5843.h.
_force_external
bool AP_Compass_HMC5843::_force_external private
Definition at line 62 of file AP_Compass_HMC5843.h.
_gain_scale
float AP_Compass_HMC5843::_gain_scale private
Definition at line 51 of file AP_Compass_HMC5843.h.
_initialised
bool AP_Compass_HMC5843::_initialised private
Definition at line 61 of file AP_Compass_HMC5843.h.
_mag_x
int16_t AP_Compass_HMC5843::_mag_x private
Definition at line 53 of file AP_Compass_HMC5843.h.
_mag_y
int16_t AP_Compass_HMC5843::_mag_y private
Definition at line 54 of file AP_Compass_HMC5843.h.
_mag_z
int16_t AP_Compass_HMC5843::_mag_z private
Definition at line 55 of file AP_Compass_HMC5843.h.
_rotation
enum Rotation AP_Compass_HMC5843::_rotation private
Definition at line 59 of file AP_Compass_HMC5843.h.
_scaling
Vector3f AP_Compass_HMC5843::_scaling private
Definition at line 50 of file AP_Compass_HMC5843.h.
name
constexpr const char* AP_Compass_HMC5843::name = "HMC5843" static
Definition at line 25 of file AP_Compass_HMC5843.h.
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_HMC5843.h