APM:Libraries: AP_AK8963_BusDriver Class Reference
AP_AK8963_BusDriver Class Reference abstract
#include <AP_Compass_AK8963.h>
Public Member Functions
virtual ~AP_AK8963_BusDriver ()
virtual bool block_read (uint8_t reg, uint8_t *buf, uint32_t size)=0
virtual bool register_read (uint8_t reg, uint8_t *val)=0
virtual bool register_write (uint8_t reg, uint8_t val)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual bool configure ()
virtual bool start_measurements ()
virtual AP_HAL::Device::PeriodicHandle register_periodic_callback (uint32_t, AP_HAL::Device::PeriodicCb)=0
virtual void set_device_type (uint8_t devtype)=0
virtual uint32_t get_bus_id (void) const =0
Detailed Description
Definition at line 62 of file AP_Compass_AK8963.h.
Constructor & Destructor Documentation
~AP_AK8963_BusDriver()
virtual AP_AK8963_BusDriver::~AP_AK8963_BusDriver () inline virtual
Definition at line 65 of file AP_Compass_AK8963.h.
Member Function Documentation
block_read()
virtual bool AP_AK8963_BusDriver::block_read (uint8_t reg, uint8_t * buf, uint32_t size) pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::_calibrate(), and AP_Compass_AK8963::_update().
configure()
virtual bool AP_AK8963_BusDriver::configure () inline virtual
Reimplemented in AP_AK8963_BusDriver_Auxiliary.
Definition at line 73 of file AP_Compass_AK8963.h.
Referenced by AP_Compass_AK8963::init().
get_bus_id()
virtual uint32_t AP_AK8963_BusDriver::get_bus_id (void) const pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::init().
get_semaphore()
virtual AP_HAL::Semaphore* AP_AK8963_BusDriver::get_semaphore () pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::init().
register_periodic_callback()
virtual AP_HAL::Device::PeriodicHandle AP_AK8963_BusDriver::register_periodic_callback (uint32_t , AP_HAL::Device::PeriodicCb) pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::init().
register_read()
virtual bool AP_AK8963_BusDriver::register_read (uint8_t reg, uint8_t * val) pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::_check_id().
register_write()
virtual bool AP_AK8963_BusDriver::register_write (uint8_t reg, uint8_t val) pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::_calibrate(), AP_Compass_AK8963::_reset(), and AP_Compass_AK8963::_setup_mode().
set_device_type()
virtual void AP_AK8963_BusDriver::set_device_type (uint8_t devtype) pure virtual
Implemented in AP_AK8963_BusDriver_Auxiliary, and AP_AK8963_BusDriver_HALDevice.
Referenced by AP_Compass_AK8963::init().
start_measurements()
virtual bool AP_AK8963_BusDriver::start_measurements () inline virtual
Reimplemented in AP_AK8963_BusDriver_Auxiliary.
Definition at line 74 of file AP_Compass_AK8963.h.
Referenced by AP_Compass_AK8963::init().
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_AK8963.h