APM:Libraries: ChibiOS::Semaphore Class Reference
ChibiOS::Semaphore Class Reference
#include <Semaphores.h>
Public Member Functions
Semaphore ()
virtual bool give () override
virtual bool take (uint32_t timeout_ms) override
virtual bool take_nonblocking () override
bool check_owner (void)
void assert_owner (void)
Public Member Functions inherited from AP_HAL::Semaphore
virtual void take_blocking ()
virtual ~Semaphore (void)
Protected Attributes
uint64_t _lock [2]
Detailed Description
Definition at line 25 of file Semaphores.h.
Constructor & Destructor Documentation
Semaphore()
Semaphore::Semaphore ()
Definition at line 28 of file Semaphores.cpp.
Member Function Documentation
assert_owner()
void Semaphore::assert_owner (void)
Definition at line 74 of file Semaphores.cpp.
Referenced by ChibiOS::SPIDevice::acquire_bus(), ChibiOS::SPIDevice::clock_pulse(), and ChibiOS::SPIDevice::transfer_fullduplex().
check_owner()
bool Semaphore::check_owner (void)
Definition at line 68 of file Semaphores.cpp.
Referenced by assert_owner(), ChibiOS::I2CDevice::transfer(), and ChibiOS::SPIDevice::transfer().
give()
bool Semaphore::give () override virtual
Implements AP_HAL::Semaphore.
Reimplemented in ChibiOS::Semaphore_Recursive.
Definition at line 35 of file Semaphores.cpp.
Referenced by ChibiOS::UARTDriver::_timer_tick(), ChibiOS::RCInput::_timer_tick(), ChibiOS::DeviceBus::bus_thread(), ChibiOS::SPIDevice::clock_pulse(), ChibiOS::RCInput::new_input(), ChibiOS::RCInput::rc_bind(), ChibiOS::RCInput::read(), ChibiOS::UARTDriver::write(), and ChibiOS::UARTDriver::write_locked().
take()
bool Semaphore::take (uint32_t timeout_ms) override virtual
Implements AP_HAL::Semaphore.
Reimplemented in ChibiOS::Semaphore_Recursive.
Definition at line 42 of file Semaphores.cpp.
Referenced by ChibiOS::UARTDriver::_timer_tick(), ChibiOS::RCInput::_timer_tick(), ChibiOS::DeviceBus::bus_thread(), ChibiOS::SPIDevice::clock_pulse(), ChibiOS::RCInput::rc_bind(), ChibiOS::RCInput::read(), and ChibiOS::Semaphore_Recursive::take().
take_nonblocking()
bool Semaphore::take_nonblocking (void) override virtual
Implements AP_HAL::Semaphore.
Reimplemented in ChibiOS::Semaphore_Recursive.
Definition at line 62 of file Semaphores.cpp.
Referenced by ChibiOS::RCInput::new_input(), take(), ChibiOS::Semaphore_Recursive::take(), ChibiOS::Semaphore_Recursive::take_nonblocking(), ChibiOS::UARTDriver::write(), and ChibiOS::UARTDriver::write_locked().
Member Data Documentation
_lock
uint64_t ChibiOS::Semaphore::_lock[2] protected
Definition at line 38 of file Semaphores.h.
Referenced by check_owner(), give(), ChibiOS::Semaphore_Recursive::give(), Semaphore(), take(), ChibiOS::Semaphore_Recursive::take(), take_nonblocking(), and ChibiOS::Semaphore_Recursive::take_nonblocking().
The documentation for this class was generated from the following files:
libraries/AP_HAL_ChibiOS/Semaphores.h
libraries/AP_HAL_ChibiOS/Semaphores.cpp