APM:Libraries: AP_HAL::SPIDeviceManager Class Reference
AP_HAL::SPIDeviceManager Class Reference
#include <SPIDevice.h>
Public Member Functions
virtual OwnPtr< SPIDevice > get_device (const char *name)
virtual uint8_t get_count ()
virtual const char * get_device_name (uint8_t idx)
Detailed Description
Definition at line 69 of file SPIDevice.h.
Member Function Documentation
get_count()
virtual uint8_t AP_HAL::SPIDeviceManager::get_count (void) inline virtual
Reimplemented in Linux::SPIDeviceManager.
Definition at line 77 of file SPIDevice.h.
Referenced by get_device().
get_device()
virtual OwnPtr<SPIDevice> AP_HAL::SPIDeviceManager::get_device (const char * name) inline virtual
Reimplemented in ChibiOS::SPIDeviceManager, Linux::SPIDeviceManager, and Empty::SPIDeviceManager.
Definition at line 71 of file SPIDevice.h.
Referenced by Compass::_detect_backends(), AP_OpticalFlow_Pixart::AP_OpticalFlow_Pixart(), Linux::SPIUARTDriver::begin(), AP_InertialSensor::detect_backends(), get_device(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), AP_RAMTRON::init(), Linux::RCOutput_AeroIO::init(), AP_Baro::init(), AP_OSD::init(), sdcard_init(), and setup().
get_device_name()
virtual const char* AP_HAL::SPIDeviceManager::get_device_name (uint8_t idx) inline virtual
Reimplemented in Linux::SPIDeviceManager.
Definition at line 80 of file SPIDevice.h.
Referenced by get_device().
The documentation for this class was generated from the following file:
libraries/AP_HAL/SPIDevice.h