APM:Libraries: SITL::JSBSim Class Reference
SITL::JSBSim Class Reference
#include <SIM_JSBSim.h>
Public Member Functions
JSBSim (const char *home_str, const char *frame_str)
void update (const struct sitl_input &input) override
Public Member Functions inherited from SITL::Aircraft
Aircraft (const char *home_str, const char *frame_str)
void set_speedup (float speedup)
void set_instance (uint8_t _instance)
void set_autotest_dir (const char *_autotest_dir)
virtual void set_interface_ports (const char *address, const int port_in, const int port_out)
void fill_fdm (struct sitl_fdm &fdm)
void smooth_sensors (void)
float get_rate_hz (void) const
const Vector3f & get_gyro (void) const
const Vector3f & get_velocity_ef (void) const
const Vector3f & get_velocity_air_ef (void) const
const Matrix3f & get_dcm (void) const
const Vector3f & get_mag_field_bf (void) const
float gross_mass () const
const Location & get_location () const
const Vector3f & get_position () const
void get_attitude (Quaternion &attitude) const
const Location & get_home () const
float get_home_yaw () const
void set_sprayer (Sprayer *_sprayer)
void set_parachute (Parachute *_parachute)
void set_gripper_servo (Gripper_Servo *_gripper)
void set_gripper_epm (Gripper_EPM *_gripper_epm)
void set_precland (SIM_Precland *_precland)
Static Public Member Functions
static Aircraft * create (const char *home_str, const char *frame_str)
Static Public Member Functions inherited from SITL::Aircraft
static double rand_normal (double mean, double stddev)
static bool parse_home (const char *home_str, Location &loc, float &yaw_degrees)
Private Types
enum { FRAME_NORMAL, FRAME_ELEVON, FRAME_VTAIL }
Private Member Functions
bool create_templates (void)
bool start_JSBSim (void)
bool open_control_socket (void)
bool open_fdm_socket (void)
void send_servos (const struct sitl_input &input)
void recv_fdm (const struct sitl_input &input)
void check_stdout (void)
bool expect (const char *str)
void drain_control_socket ()
Private Attributes
SocketAPM sock_control
SocketAPM sock_fgfdm
bool initialised
uint16_t control_port
uint16_t fdm_port
char * jsbsim_script
char * jsbsim_fgout
int jsbsim_stdout
const char * jsbsim_model = "Rascal"
bool created_templates
bool started_jsbsim
bool opened_control_socket
bool opened_fdm_socket
enum SITL::JSBSim:: { ... } frame
Additional Inherited Members
Protected Types inherited from SITL::Aircraft
enum GroundBehaviour { GROUND_BEHAVIOR_NONE = 0, GROUND_BEHAVIOR_NO_MOVEMENT, GROUND_BEHAVIOR_FWD_ONLY, GROUND_BEHAVIOR_TAILSITTER }
Protected Member Functions inherited from SITL::Aircraft
float ground_height_difference () const
virtual bool on_ground () const
float hagl () const
void update_position (void)
void update_mag_field_bf (void)
void time_advance ()
void setup_frame_time (float rate, float speedup)
void adjust_frame_time (float rate)
void sync_frame_time (void)
void add_noise (float throttle)
uint64_t get_wall_time_us (void) const
void update_dynamics (const Vector3f &rot_accel)
void update_wind (const struct sitl_input &input)
float filtered_idx (float v, uint8_t idx)
float filtered_servo_angle (const struct sitl_input &input, uint8_t idx)
float filtered_servo_range (const struct sitl_input &input, uint8_t idx)
void extrapolate_sensors (float delta_time)
void update_external_payload (const struct sitl_input &input)
void add_shove_forces (Vector3f &rot_accel, Vector3f &body_accel)
void add_twist_forces (Vector3f &rot_accel)
Protected Attributes inherited from SITL::Aircraft
SITL * sitl
Location home
Location location
float ground_level
float home_yaw
float frame_height
Matrix3f dcm
Vector3f gyro
Vector3f gyro_prev
Vector3f ang_accel
Vector3f velocity_ef
Vector3f wind_ef
Vector3f velocity_air_ef
Vector3f velocity_air_bf
Vector3f position
float mass
float external_payload_mass = 0.0f
Vector3f accel_body
float airspeed
float airspeed_pitot
float battery_voltage = -1.0f
float battery_current = 0.0f
float rpm1 = 0
float rpm2 = 0
uint8_t rcin_chan_count = 0
float rcin [8]
float range = -1.0f
struct {
struct vector3f_array points
struct float_array ranges
} scanner
float turbulence_azimuth = 0.0f
float turbulence_horizontal_speed = 0.0f
float turbulence_vertical_speed = 0.0f
Vector3f mag_bf
uint64_t time_now_us
const float gyro_noise
const float accel_noise
float rate_hz
float achieved_rate_hz
float target_speedup
uint64_t frame_time_us
float scaled_frame_time_us
uint64_t last_wall_time_us
uint8_t instance
const char * autotest_dir
const char * frame
bool use_time_sync = true
float last_speedup = -1.0f
AP_Int8 * ahrs_orientation
enum SITL::Aircraft::GroundBehaviour ground_behavior
bool use_smoothing
AP_Terrain * terrain
const float FEET_TO_METERS = 0.3048f
const float KNOTS_TO_METERS_PER_SECOND = 0.51444f
Detailed Description
Definition at line 30 of file SIM_JSBSim.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
FRAME_NORMAL
FRAME_ELEVON
FRAME_VTAIL
Definition at line 65 of file SIM_JSBSim.h.
Constructor & Destructor Documentation
JSBSim()
SITL::JSBSim::JSBSim (const char * home_str, const char * frame_str)
Definition at line 39 of file SIM_JSBSim.cpp.
Referenced by create().
Member Function Documentation
check_stdout()
void SITL::JSBSim::check_stdout (void) private
Definition at line 257 of file SIM_JSBSim.cpp.
Referenced by open_fdm_socket(), recv_fdm(), and start_JSBSim().
create()
static Aircraft* SITL::JSBSim::create (const char * home_str, const char * frame_str) inline static
Definition at line 38 of file SIM_JSBSim.h.
create_templates()
bool SITL::JSBSim::create_templates (void) private
Definition at line 73 of file SIM_JSBSim.cpp.
Referenced by update().
drain_control_socket()
void SITL::JSBSim::drain_control_socket () private
Definition at line 452 of file SIM_JSBSim.cpp.
Referenced by update().
expect()
bool SITL::JSBSim::expect (const char * str) private
Definition at line 271 of file SIM_JSBSim.cpp.
Referenced by start_JSBSim().
open_control_socket()
bool SITL::JSBSim::open_control_socket (void) private
Definition at line 294 of file SIM_JSBSim.cpp.
Referenced by start_JSBSim(), and update().
open_fdm_socket()
bool SITL::JSBSim::open_fdm_socket (void) private
Definition at line 318 of file SIM_JSBSim.cpp.
Referenced by start_JSBSim(), and update().
recv_fdm()
void SITL::JSBSim::recv_fdm (const struct sitl_input & input) private
Definition at line 414 of file SIM_JSBSim.cpp.
Referenced by update().
send_servos()
void SITL::JSBSim::send_servos (const struct sitl_input & input) private
Definition at line 337 of file SIM_JSBSim.cpp.
Referenced by recv_fdm(), and update().
start_JSBSim()
bool SITL::JSBSim::start_JSBSim (void) private
Definition at line 178 of file SIM_JSBSim.cpp.
Referenced by update().
update()
void SITL::JSBSim::update (const struct sitl_input & input) override virtual
Implements SITL::Aircraft.
Definition at line 464 of file SIM_JSBSim.cpp.
Member Data Documentation
control_port
uint16_t SITL::JSBSim::control_port private
Definition at line 51 of file SIM_JSBSim.h.
Referenced by create_templates(), JSBSim(), and open_control_socket().
created_templates
bool SITL::JSBSim::created_templates private
Definition at line 60 of file SIM_JSBSim.h.
Referenced by create_templates().
fdm_port
uint16_t SITL::JSBSim::fdm_port private
Definition at line 52 of file SIM_JSBSim.h.
Referenced by create_templates(), JSBSim(), and open_fdm_socket().
frame
enum { ... } SITL::JSBSim::frame
Referenced by JSBSim(), and send_servos().
initialised
bool SITL::JSBSim::initialised private
Definition at line 49 of file SIM_JSBSim.h.
Referenced by update().
jsbsim_fgout
char* SITL::JSBSim::jsbsim_fgout private
Definition at line 54 of file SIM_JSBSim.h.
Referenced by create_templates(), and start_JSBSim().
jsbsim_model
const char* SITL::JSBSim::jsbsim_model = "Rascal" private
Definition at line 58 of file SIM_JSBSim.h.
Referenced by create_templates(), and JSBSim().
jsbsim_script
char* SITL::JSBSim::jsbsim_script private
Definition at line 53 of file SIM_JSBSim.h.
Referenced by create_templates(), and start_JSBSim().
jsbsim_stdout
int SITL::JSBSim::jsbsim_stdout private
Definition at line 55 of file SIM_JSBSim.h.
Referenced by check_stdout(), expect(), and start_JSBSim().
opened_control_socket
bool SITL::JSBSim::opened_control_socket private
Definition at line 62 of file SIM_JSBSim.h.
Referenced by open_control_socket().
opened_fdm_socket
bool SITL::JSBSim::opened_fdm_socket private
Definition at line 63 of file SIM_JSBSim.h.
Referenced by open_fdm_socket().
sock_control
SocketAPM SITL::JSBSim::sock_control private
Definition at line 44 of file SIM_JSBSim.h.
Referenced by drain_control_socket(), open_control_socket(), and send_servos().
sock_fgfdm
SocketAPM SITL::JSBSim::sock_fgfdm private
Definition at line 47 of file SIM_JSBSim.h.
Referenced by open_fdm_socket(), and recv_fdm().
started_jsbsim
bool SITL::JSBSim::started_jsbsim private
Definition at line 61 of file SIM_JSBSim.h.
Referenced by start_JSBSim().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_JSBSim.h
libraries/SITL/SIM_JSBSim.cpp