APM:Libraries: AC_Avoid Class Reference
AC_Avoid Class Reference
#include <AC_Avoid.h>
Public Member Functions
AC_Avoid ()
Constructor.
AC_Avoid (const AC_Avoid &other)=delete
AC_Avoid & operator= (const AC_Avoid &)=delete
void adjust_velocity (float kP, float accel_cmss, Vector2f &desired_vel_cms, float dt)
void adjust_velocity (float kP, float accel_cmss, Vector3f &desired_vel_cms, float dt)
void adjust_speed (float kP, float accel, float heading, float &speed, float dt)
void adjust_velocity_z (float kP, float accel_cmss, float &climb_rate_cms, float dt)
void adjust_roll_pitch (float &roll, float &pitch, float angle_max)
void proximity_avoidance_enable (bool on_off)
bool proximity_avoidance_enabled ()
void limit_velocity (float kP, float accel_cmss, Vector2f &desired_vel_cms, const Vector2f &limit_direction, float limit_distance_cm, float dt) const
float get_max_speed (float kP, float accel_cmss, float distance_cm, float dt) const
Static Public Member Functions
static AC_Avoid * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum BehaviourType { BEHAVIOR_SLIDE = 0, BEHAVIOR_STOP = 1 }
Private Member Functions
void adjust_velocity_circle_fence (float kP, float accel_cmss, Vector2f &desired_vel_cms, float dt)
void adjust_velocity_polygon_fence (float kP, float accel_cmss, Vector2f &desired_vel_cms, float dt)
void adjust_velocity_beacon_fence (float kP, float accel_cmss, Vector2f &desired_vel_cms, float dt)
void adjust_velocity_proximity (float kP, float accel_cmss, Vector2f &desired_vel_cms, float dt)
void adjust_velocity_polygon (float kP, float accel_cmss, Vector2f &desired_vel_cms, const Vector2f *boundary, uint16_t num_points, bool earth_frame, float margin, float dt)
float get_stopping_distance (float kP, float accel_cmss, float speed_cms) const
float distance_to_lean_pct (float dist_m)
void get_proximity_roll_pitch_pct (float &roll_positive, float &roll_negative, float &pitch_positive, float &pitch_negative)
Private Attributes
AP_Int8 _enabled
AP_Int16 _angle_max
AP_Float _dist_max
AP_Float _margin
AP_Int8 _behavior
bool _proximity_enabled = true
Static Private Attributes
static AC_Avoid * _singleton
Detailed Description
Definition at line 25 of file AC_Avoid.h.
Member Enumeration Documentation
BehaviourType
enum AC_Avoid::BehaviourType private
Enumerator
BEHAVIOR_SLIDE
BEHAVIOR_STOP
Definition at line 83 of file AC_Avoid.h.
Constructor & Destructor Documentation
AC_Avoid() [1/2]
AC_Avoid::AC_Avoid ()
Constructor.
Definition at line 73 of file AC_Avoid.cpp.
AC_Avoid() [2/2]
AC_Avoid::AC_Avoid (const AC_Avoid & other) delete
Member Function Documentation
adjust_roll_pitch()
void AC_Avoid::adjust_roll_pitch (float & roll, float & pitch, float angle_max)
Definition at line 207 of file AC_Avoid.cpp.
adjust_speed()
void AC_Avoid::adjust_speed (float kP, float accel, float heading, float & speed, float dt)
Definition at line 118 of file AC_Avoid.cpp.
adjust_velocity() [1/2]
void AC_Avoid::adjust_velocity (float kP, float accel_cmss, Vector2f & desired_vel_cms, float dt)
Definition at line 80 of file AC_Avoid.cpp.
Referenced by adjust_speed(), adjust_velocity(), and AC_Loiter::calc_desired_velocity().
adjust_velocity() [2/2]
void AC_Avoid::adjust_velocity (float kP, float accel_cmss, Vector3f & desired_vel_cms, float dt)
Definition at line 105 of file AC_Avoid.cpp.
adjust_velocity_beacon_fence()
void AC_Avoid::adjust_velocity_beacon_fence (float kP, float accel_cmss, Vector2f & desired_vel_cms, float dt) private
Definition at line 411 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
adjust_velocity_circle_fence()
void AC_Avoid::adjust_velocity_circle_fence (float kP, float accel_cmss, Vector2f & desired_vel_cms, float dt) private
Definition at line 287 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
adjust_velocity_polygon()
void AC_Avoid::adjust_velocity_polygon (float kP, float accel_cmss, Vector2f & desired_vel_cms, const Vector2f * boundary, uint16_t num_points, bool earth_frame, float margin, float dt) private
Definition at line 461 of file AC_Avoid.cpp.
Referenced by adjust_velocity_beacon_fence(), adjust_velocity_polygon_fence(), and adjust_velocity_proximity().
adjust_velocity_polygon_fence()
void AC_Avoid::adjust_velocity_polygon_fence (float kP, float accel_cmss, Vector2f & desired_vel_cms, float dt) private
Definition at line 381 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
adjust_velocity_proximity()
void AC_Avoid::adjust_velocity_proximity (float kP, float accel_cmss, Vector2f & desired_vel_cms, float dt) private
Definition at line 438 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
adjust_velocity_z()
void AC_Avoid::adjust_velocity_z (float kP, float accel_cmss, float & climb_rate_cms, float dt)
Definition at line 135 of file AC_Avoid.cpp.
distance_to_lean_pct()
float AC_Avoid::distance_to_lean_pct (float dist_m) private
Definition at line 594 of file AC_Avoid.cpp.
Referenced by get_proximity_roll_pitch_pct().
get_max_speed()
float AC_Avoid::get_max_speed (float kP, float accel_cmss, float distance_cm, float dt) const
Definition at line 275 of file AC_Avoid.cpp.
Referenced by adjust_velocity_circle_fence(), adjust_velocity_z(), and limit_velocity().
get_proximity_roll_pitch_pct()
void AC_Avoid::get_proximity_roll_pitch_pct (float & roll_positive, float & roll_negative, float & pitch_positive, float & pitch_negative) private
Definition at line 605 of file AC_Avoid.cpp.
Referenced by adjust_roll_pitch().
get_singleton()
static AC_Avoid* AC_Avoid::get_singleton () inline static
Definition at line 34 of file AC_Avoid.h.
Referenced by AP::ac_avoid().
get_stopping_distance()
float AC_Avoid::get_stopping_distance (float kP, float accel_cmss, float speed_cms) const private
Definition at line 571 of file AC_Avoid.cpp.
Referenced by adjust_velocity_circle_fence(), and adjust_velocity_polygon().
limit_velocity()
void AC_Avoid::limit_velocity (float kP, float accel_cmss, Vector2f & desired_vel_cms, const Vector2f & limit_direction, float limit_distance_cm, float dt) const
Definition at line 260 of file AC_Avoid.cpp.
Referenced by adjust_velocity_polygon().
operator=()
AC_Avoid& AC_Avoid::operator= (const AC_Avoid &) delete
proximity_avoidance_enable()
void AC_Avoid::proximity_avoidance_enable (bool on_off) inline
Definition at line 63 of file AC_Avoid.h.
Referenced by RC_Channel::do_aux_function_avoid_proximity().
proximity_avoidance_enabled()
bool AC_Avoid::proximity_avoidance_enabled () inline
Definition at line 64 of file AC_Avoid.h.
Member Data Documentation
_angle_max
AP_Int16 AC_Avoid::_angle_max private
Definition at line 132 of file AC_Avoid.h.
Referenced by adjust_roll_pitch().
_behavior
AP_Int8 AC_Avoid::_behavior private
Definition at line 135 of file AC_Avoid.h.
Referenced by adjust_velocity_circle_fence(), and adjust_velocity_polygon().
_dist_max
AP_Float AC_Avoid::_dist_max private
Definition at line 133 of file AC_Avoid.h.
Referenced by distance_to_lean_pct(), and get_proximity_roll_pitch_pct().
_enabled
AP_Int8 AC_Avoid::_enabled private
Definition at line 131 of file AC_Avoid.h.
Referenced by adjust_roll_pitch(), adjust_velocity(), and adjust_velocity_z().
_margin
AP_Float AC_Avoid::_margin private
Definition at line 134 of file AC_Avoid.h.
Referenced by adjust_velocity_proximity(), and adjust_velocity_z().
_proximity_enabled
bool AC_Avoid::_proximity_enabled = true private
Definition at line 137 of file AC_Avoid.h.
Referenced by adjust_roll_pitch(), adjust_velocity(), proximity_avoidance_enable(), and proximity_avoidance_enabled().
_singleton
AC_Avoid * AC_Avoid::_singleton static private
Definition at line 139 of file AC_Avoid.h.
Referenced by AC_Avoid(), and get_singleton().
var_info
const AP_Param::GroupInfo AC_Avoid::var_info static
Definition at line 79 of file AC_Avoid.h.
Referenced by AC_Avoid().
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AC_Avoid.h
libraries/AC_Avoidance/AC_Avoid.cpp