APM:Libraries: AP_HAL::BetterStream Class Reference
AP_HAL::BetterStream Class Reference abstract
#include <BetterStream.h>
Public Member Functions
virtual void printf (const char *,...) FMT_PRINTF(2
virtual void virtual void vprintf (const char *, va_list)
void print (const char *str)
void println (const char *str)
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
virtual uint32_t available ()=0
virtual int16_t read ()=0
virtual uint32_t txspace ()=0
Detailed Description
Definition at line 27 of file BetterStream.h.
Member Function Documentation
available()
virtual uint32_t AP_HAL::BetterStream::available () pure virtual
Implemented in StdioBufferPrinter, HALSITL::UARTDriver, ChibiOS::UARTDriver, BufferPrinter, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by Menu::_check_for_input(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), AP_Proximity_LightWareSF40C::check_for_reply(), comm_get_available(), AP_RangeFinder_uLanding::detect_version(), drive(), AP_RangeFinder_MaxsonarSerialLV::get_reading(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_uLanding::get_reading(), AP_RangeFinder_BLPing::get_reading(), AP_RangeFinder_Benewake::get_reading(), AP_RangeFinder_Wasp::get_reading(), AP_RangeFinder_NMEA::get_reading(), AP_RangeFinder_LeddarOne::get_reading(), AP_Proximity_RPLidarA2::get_readings(), GCS_MAVLINK::handle_serial_control(), loop(), AP_RangeFinder_LeddarOne::parse_response(), AP_GPS_NOVA::read(), AP_GPS_ERB::read(), AP_GPS_MTK::read(), AP_GPS_SIRF::read(), AP_GPS_GSOF::read(), AP_GPS_MTK19::read(), AP_GPS_SBF::read(), AP_GPS_NMEA::read(), AP_GPS_UBLOX::read(), AP_RobotisServo::read_bytes(), AP_Mount_SToRM32_serial::read_incoming(), AP_Mount_Alexmos::read_incoming(), AP_Proximity_TeraRangerTower::read_sensor_data(), AP_Proximity_TeraRangerTowerEvo::read_sensor_data(), run_test(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), AP_OpticalFlow_CXOF::update(), AP_Beacon_Pozyx::update(), AP_WindVane_NMEA::update(), and AP_Beacon_Marvelmind::update().
print()
void AP_HAL::BetterStream::print (const char * str) inline
Definition at line 33 of file BetterStream.h.
printf()
void AP_HAL::BetterStream::printf (const char * fmt, ...) virtual
Definition at line 5 of file BetterStream.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), Linux::CameraSensor_Mt9v117::_apply_patch(), AP_InertialSensor::_calculate_trim(), Linux::RCInput_SoloLink::_check_hdr(), AP_Compass_LSM9DS1::_check_id(), AP_Baro_LPS2XH::_check_whoami(), Linux::CameraSensor_Mt9v117::_config_change(), AP_InertialSensor_BMI160::_configure_fifo(), AP_InertialSensor_BMI160::_configure_int1_pin(), AP_ADC_ADS1115::_convert_register_data_to_mv(), Linux::VideoIn::_dequeue_frame(), Compass::_detect_backends(), Menu::_display_prompt(), AP_Compass_LSM9DS1::_dump_registers(), Linux::GPIO_Sysfs::_export_pin(), ChibiOS::Storage::_flash_load(), ChibiOS::Storage::_flash_write_data(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_LSM9DS1::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), Menu::_help(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_InertialSensor_BMI160::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), AP_InertialSensor::_init_gyro(), AP_Compass_BMM150::_load_trim_values(), Linux::GPIO_Sysfs::_open_pin_value(), AP_GPS_UBLOX::_parse_gps(), Linux::GPIO_Sysfs::_pinMode(), AP_RCProtocol_SUMD::_process_byte(), Linux::VideoIn::_queue_buffer(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS1::_read_data_transaction_g(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), AP_InertialSensor_LSM9DS1::_read_data_transaction_x(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_BMI160::_read_fifo(), Linux::CameraSensor_Mt9v117::_read_reg16(), Linux::CameraSensor_Mt9v117::_read_reg8(), AP_Compass_LSM303D::_read_sample(), Menu::_run_command(), HALSITL::Storage::_storage_open(), ChibiOS::Storage::_storage_open(), Linux::RCInput_UDP::_timer_tick(), HALSITL::UARTDriver::_uart_start_connection(), Linux::CameraSensor_Mt9v117::_write_reg16(), Linux::CameraSensor_Mt9v117::_write_reg32(), Linux::CameraSensor_Mt9v117::_write_reg8(), AP_InertialSensor_BMI055::accel_init(), AP_InertialSensor_BMI088::accel_init(), Linux::VideoIn::allocate_buffers(), lua_scripts::atpanic(), Linux::SPIUARTDriver::begin(), HALSITL::UARTDriver::begin(), Linux::Perf::begin(), AP_BoardConfig::board_setup_sbus(), AnalogIn_ADS1115::channel(), AnalogIn_Navio2::channel(), ChibiOS::AnalogIn::channel(), check_path(), check_result(), AP_Param::convert_old_parameter(), Linux::Perf::count(), display_offsets_and_scaling(), drive(), Linux::PWM_Sysfs_Base::enable(), Linux::Perf::end(), SchedTest::five_second_call(), ChibiOS::Util::flash_bootloader(), get_device(), Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), AP_RangeFinder_VL53L1X::get_reading(), MenuCommands::gpio_input_channel(), MenuCommands::gpio_output_channel(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), Compass::handle_mag_cal_command(), ChibiOS::I2CDevice::I2CDevice(), Linux::ToneAlarm::init(), AP_Logger_Block::Init(), AP_RAMTRON::init(), Linux::RCInput_UDP::init(), AP_IRLock_SITL_Gazebo::init(), AP_Compass_LSM9DS1::init(), AP_SBusOut::init(), AP_Airspeed_SDP3X::init(), AP_Compass_AK8963::init(), AP_Compass_BMM150::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), Compass::init(), AP_ADSB::init(), AP_Avoidance::init(), AP_Logger::Init(), AP_OSD::init(), MissionTest::init_mission(), MissionTest::init_mission_endless_loop(), MissionTest::init_mission_ends_with_do_commands(), MissionTest::init_mission_ends_with_jump_command(), MissionTest::init_mission_jump_to_nonnav(), MissionTest::init_mission_no_nav_commands(), MissionTest::init_mission_starts_with_do_commands(), inverse4x4(), Linux::PWM_Sysfs_Base::is_enabled(), AP_Param::load_embedded_param_defaults(), AP_Param::load_object_from_eeprom(), lua_scripts::load_script(), GCS_MAVLINK::load_signing_key(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), FlashTest::loop(), loop(), RC_UART::loop(), AP_LoggerTest::loop(), AP_LoggerTest_AllTypes::loop(), missing_rotations(), MissionTest::mission_complete(), motor_order_test(), SchedTest::one_hz_print(), Linux::VideoIn::open_device(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_write(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), print_latlon(), MissionTest::print_mission(), print_radio_values(), print_vector(), println(), AP_RobotisServo::process_packet(), Linux::DigitalSource_Sysfs::read(), AP_GPS_MTK19::read(), Linux::GPIO_Sysfs::read(), AP_Invensensev2_AuxiliaryBusSlave::read(), AP_Invensense_AuxiliaryBusSlave::read(), read_channels(), readTemp(), Linux::Scheduler::register_io_process(), ChibiOS::Scheduler::register_io_process(), Linux::Scheduler::register_timer_process(), ChibiOS::Scheduler::register_timer_process(), HAL_SITL::run(), MissionTest::run_max_cmd_test(), MissionTest::run_mission_test(), lua_scripts::run_next_script(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), MissionTest::run_set_current_cmd_while_stopped_test(), run_test(), SoloGimbalEKF::RunEKF(), AP_Param::save_sync(), AP_SBusOut::sbus_format_frame(), GCS_Dummy::send_statustext(), SRV_Channels::set_aux_channel_default(), AnalogSource_Navio2::set_channel(), Linux::VideoIn::set_crop(), Linux::VideoIn::set_format(), AP_SerialManager::set_options(), Linux::PWM_Sysfs_Base::set_period(), Linux::PWM_Sysfs_Base::set_polarity(), FlashTest::setup(), setup(), RC_UART::setup(), MissionTest::setup(), AP_LoggerTest::setup(), AP_LoggerTest_AllTypes::setup(), AP_InertialSensor_BMI088::setup_accel_config(), AP_InertialSensor::simple_accel_cal(), HALSITL::Scheduler::sitl_end_atomic(), stability_test(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensense::start(), MissionTest::start_cmd(), test_accuracy(), test_conversion(), test_conversions(), test_euler(), test_eulers(), test_frame_transforms(), test_gpio_input(), test_gpio_output(), test_high_low_byte(), test_matrix_eulers(), test_matrix_inverse(), test_matrix_rotate(), test_one_offset(), test_passed_waypoint(), test_printf_floats(), test_printf_null_termination(), test_quaternion_eulers(), test_rotate_inverse(), test_rotate_matrix(), test_rotation_accuracy(), test_uart(), test_wgs_conversion_functions(), test_wrap_cd(), Linux::SPIDevice::transfer(), ChibiOS::I2CDevice::transfer(), ChibiOS::SPIDevice::transfer(), Linux::SPIDevice::transfer_fullduplex(), AP_OpticalFlow_Onboard::update(), SoloGimbal_Parameters::update(), AP_OSD_MAX7456::update_font(), MissionTest::verify_cmd(), AP_InertialSensor::wait_for_sample(), Linux::DigitalSource_Sysfs::write(), Linux::GPIO_Sysfs::write(), and ChibiOS::UARTDriver::write_pending_bytes().
println()
void AP_HAL::BetterStream::println (const char * str) inline
Definition at line 34 of file BetterStream.h.
Referenced by setup().
read()
virtual int16_t AP_HAL::BetterStream::read () pure virtual
Implemented in StdioBufferPrinter, HALSITL::UARTDriver, ChibiOS::UARTDriver, BufferPrinter, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by Menu::_check_for_input(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), AP_Proximity_LightWareSF40C::check_for_reply(), AP_GPS::detect_instance(), AP_RangeFinder_uLanding::detect_version(), AP_RangeFinder_MaxsonarSerialLV::get_reading(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_uLanding::get_reading(), AP_RangeFinder_BLPing::get_reading(), AP_RangeFinder_Benewake::get_reading(), AP_RangeFinder_Wasp::get_reading(), AP_RangeFinder_NMEA::get_reading(), AP_RangeFinder_LeddarOne::get_reading(), AP_Proximity_RPLidarA2::get_readings(), GCS_MAVLINK::handle_serial_control(), loop(), AP_RangeFinder_LeddarOne::parse_response(), AP_GPS_NOVA::read(), AP_GPS_MTK::read(), AP_GPS_ERB::read(), AP_GPS_SIRF::read(), AP_GPS_MTK19::read(), AP_GPS_GSOF::read(), AP_GPS_SBF::read(), AP_GPS_NMEA::read(), AP_GPS_UBLOX::read(), AP_RobotisServo::read_bytes(), AP_Mount_SToRM32_serial::read_incoming(), AP_Mount_Alexmos::read_incoming(), AP_Proximity_TeraRangerTowerEvo::read_sensor_data(), AP_Proximity_TeraRangerTower::read_sensor_data(), run_test(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), AP_OpticalFlow_CXOF::update(), AP_Beacon_Pozyx::update(), AP_WindVane_NMEA::update(), AP_Beacon_Marvelmind::update(), and GCS_MAVLINK::update_receive().
txspace()
virtual uint32_t AP_HAL::BetterStream::txspace () pure virtual
Implemented in StdioBufferPrinter, HALSITL::UARTDriver, ChibiOS::UARTDriver, BufferPrinter, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by AP_GPS_UBLOX::_configure_message_rate(), AP_AccelCal::_printf(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_UBLOX::_request_port(), AP_GPS_UBLOX::_send_message(), AP_Mount_SToRM32_serial::can_send(), comm_get_txspace(), AP_Mount_SToRM32_serial::get_angles(), GCS_MAVLINK::handle_serial_control(), AP_GPS_NOVA::inject_data(), AP_GPS_SBP2::inject_data(), AP_GPS_SBP::inject_data(), AP_GPS_Backend::inject_data(), AP_GPS::send_blob_update(), AP_Mount_Alexmos::send_command(), AP_RangeFinder_BLPing::send_message(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), AP_Mount_SToRM32_serial::send_target_angles(), GCS::send_to_active_channels(), and AP_Volz_Protocol::update().
vprintf()
void AP_HAL::BetterStream::vprintf (const char * fmt, va_list ap) virtual
Definition at line 13 of file BetterStream.cpp.
Referenced by hal_console_vprintf(), and printf().
write() [1/3]
virtual size_t AP_HAL::BetterStream::write (uint8_t) pure virtual
Implemented in HALSITL::UARTDriver, ChibiOS::UARTDriver, StdioBufferPrinter, Linux::UARTDriver, Empty::UARTDriver, and BufferPrinter.
Referenced by Menu::_check_for_input(), AP_GPS_UBLOX::_send_message(), AP_GPS_NOVA::AP_GPS_NOVA(), AP_GPS_SBF::AP_GPS_SBF(), comm_send_buffer(), AP_Mount_SToRM32_serial::get_angles(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_LeddarOne::get_reading(), GCS_MAVLINK::handle_serial_control(), AP_GPS_NOVA::inject_data(), AP_GPS_SBP2::inject_data(), AP_GPS_SBP::inject_data(), AP_GPS_Backend::inject_data(), loop(), AP_GPS_SBF::mount_disk(), print(), print_vprintf(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_GPS_GSOF::requestBaud(), AP_GPS_GSOF::requestGSOF(), AP_Proximity_RPLidarA2::reset_rplidar(), AP_GPS::send_blob_update(), AP_Frsky_Telem::send_byte(), AP_Volz_Protocol::send_command(), AP_Mount_Alexmos::send_command(), AP_DEVO_Telem::send_frames(), AP_RangeFinder_BLPing::send_message(), AP_RobotisServo::send_packet(), AP_Proximity_LightWareSF40C::send_request_for_distance(), AP_Proximity_LightWareSF40C::send_request_for_health(), AP_Proximity_RPLidarA2::send_request_for_health(), AP_Mount_SToRM32_serial::send_target_angles(), AP_Frsky_Telem::send_uint16(), AP_Proximity_LightWareSF40C::set_forward_direction(), AP_Proximity_TeraRangerTowerEvo::set_mode(), AP_Proximity_LightWareSF40C::set_motor_direction(), AP_Proximity_LightWareSF40C::set_motor_speed(), AP_Proximity_RPLidarA2::set_scan_mode(), GCS_MAVLINK::setup_uart(), AP_GPS_SBF::unmount_disk(), AP_RangeFinder_Wasp::update(), and AP_SBusOut::update().
write() [2/3]
virtual size_t AP_HAL::BetterStream::write (const uint8_t * buffer, size_t size) pure virtual
Implemented in StdioBufferPrinter, HALSITL::UARTDriver, ChibiOS::UARTDriver, Linux::UARTDriver, BufferPrinter, and Empty::UARTDriver.
write() [3/3]
size_t AP_HAL::BetterStream::write (const char * str)
Definition at line 18 of file BetterStream.cpp.
The documentation for this class was generated from the following files:
libraries/AP_HAL/utility/BetterStream.h
libraries/AP_HAL/utility/BetterStream.cpp