APM:Libraries: AP_RobotisServo Class Reference
AP_RobotisServo Class Reference
#include <AP_RobotisServo.h>
Public Member Functions
AP_RobotisServo ()
AP_RobotisServo (const AP_RobotisServo &other)=delete
AP_RobotisServo & operator= (const AP_RobotisServo &)=delete
void update ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void init (void)
void detect_servos ()
uint16_t update_crc (uint16_t crc_accum, uint8_t *data_blk_ptr, uint16_t data_blk_size)
void add_stuffing (uint8_t *packet)
void send_packet (uint8_t *txpacket)
void read_bytes ()
void process_packet (const uint8_t *pkt, uint8_t length)
void send_command (uint8_t id, uint16_t reg, uint32_t value, uint8_t len)
void configure_servos (void)
Private Attributes
AP_HAL::UARTDriver * port
uint32_t baudrate
uint32_t us_per_byte
uint32_t us_gap
uint16_t servo_mask
uint8_t detection_count
uint8_t configured_servos
bool initialised
uint8_t pktbuf [64]
uint8_t pktbuf_ofs
AP_Int32 pos_min
AP_Int32 pos_max
uint32_t last_send_us
uint32_t delay_time_us
Detailed Description
Definition at line 24 of file AP_RobotisServo.h.
Constructor & Destructor Documentation
AP_RobotisServo() [1/2]
AP_RobotisServo::AP_RobotisServo (void)
Definition at line 128 of file AP_RobotisServo.cpp.
AP_RobotisServo() [2/2]
AP_RobotisServo::AP_RobotisServo (const AP_RobotisServo & other) delete
Member Function Documentation
add_stuffing()
void AP_RobotisServo::add_stuffing (uint8_t * packet) private
Definition at line 201 of file AP_RobotisServo.cpp.
Referenced by send_packet().
configure_servos()
void AP_RobotisServo::configure_servos (void) private
Definition at line 293 of file AP_RobotisServo.cpp.
Referenced by update().
detect_servos()
void AP_RobotisServo::detect_servos (void) private
Definition at line 274 of file AP_RobotisServo.cpp.
Referenced by update().
init()
void AP_RobotisServo::init (void) private
Definition at line 134 of file AP_RobotisServo.cpp.
Referenced by update().
operator=()
AP_RobotisServo& AP_RobotisServo::operator= (const AP_RobotisServo &) delete
process_packet()
void AP_RobotisServo::process_packet (const uint8_t * pkt, uint8_t length) private
Definition at line 385 of file AP_RobotisServo.cpp.
Referenced by read_bytes().
read_bytes()
void AP_RobotisServo::read_bytes (void) private
Definition at line 330 of file AP_RobotisServo.cpp.
Referenced by update().
send_command()
void AP_RobotisServo::send_command (uint8_t id, uint16_t reg, uint32_t value, uint8_t len) private
Definition at line 312 of file AP_RobotisServo.cpp.
Referenced by configure_servos(), and update().
send_packet()
void AP_RobotisServo::send_packet (uint8_t * txpacket) private
Definition at line 248 of file AP_RobotisServo.cpp.
Referenced by detect_servos(), and send_command().
update()
void AP_RobotisServo::update (void)
Definition at line 403 of file AP_RobotisServo.cpp.
Referenced by SRV_Channels::push().
update_crc()
uint16_t AP_RobotisServo::update_crc (uint16_t crc_accum, uint8_t * data_blk_ptr, uint16_t data_blk_size) private
Definition at line 148 of file AP_RobotisServo.cpp.
Referenced by read_bytes(), and send_packet().
Member Data Documentation
baudrate
uint32_t AP_RobotisServo::baudrate private
Definition at line 38 of file AP_RobotisServo.h.
Referenced by init().
configured_servos
uint8_t AP_RobotisServo::configured_servos private
Definition at line 56 of file AP_RobotisServo.h.
Referenced by update().
delay_time_us
uint32_t AP_RobotisServo::delay_time_us private
Definition at line 67 of file AP_RobotisServo.h.
Referenced by detect_servos(), send_packet(), and update().
detection_count
uint8_t AP_RobotisServo::detection_count private
Definition at line 55 of file AP_RobotisServo.h.
Referenced by update().
initialised
bool AP_RobotisServo::initialised private
Definition at line 57 of file AP_RobotisServo.h.
Referenced by update().
last_send_us
uint32_t AP_RobotisServo::last_send_us private
Definition at line 66 of file AP_RobotisServo.h.
Referenced by detect_servos(), and update().
pktbuf
uint8_t AP_RobotisServo::pktbuf[64] private
Definition at line 59 of file AP_RobotisServo.h.
Referenced by read_bytes().
pktbuf_ofs
uint8_t AP_RobotisServo::pktbuf_ofs private
Definition at line 60 of file AP_RobotisServo.h.
Referenced by read_bytes().
port
AP_HAL::UARTDriver* AP_RobotisServo::port private
Definition at line 37 of file AP_RobotisServo.h.
Referenced by init(), read_bytes(), send_packet(), and update().
pos_max
AP_Int32 AP_RobotisServo::pos_max private
Definition at line 64 of file AP_RobotisServo.h.
Referenced by update().
pos_min
AP_Int32 AP_RobotisServo::pos_min private
Definition at line 63 of file AP_RobotisServo.h.
Referenced by update().
servo_mask
uint16_t AP_RobotisServo::servo_mask private
Definition at line 54 of file AP_RobotisServo.h.
Referenced by process_packet(), and update().
us_gap
uint32_t AP_RobotisServo::us_gap private
Definition at line 40 of file AP_RobotisServo.h.
Referenced by init(), and send_packet().
us_per_byte
uint32_t AP_RobotisServo::us_per_byte private
Definition at line 39 of file AP_RobotisServo.h.
Referenced by detect_servos(), init(), and send_packet().
var_info
const AP_Param::GroupInfo AP_RobotisServo::var_info static
Initial value:
= {
    AP_GROUPINFO("POSMIN",  1, AP_RobotisServo, pos_min, 0),
    AP_GROUPINFO("POSMAX",  2, AP_RobotisServo, pos_max, 4095),
    AP_GROUPEND
}
Definition at line 32 of file AP_RobotisServo.h.
Referenced by AP_RobotisServo().
The documentation for this class was generated from the following files:
libraries/AP_RobotisServo/AP_RobotisServo.h
libraries/AP_RobotisServo/AP_RobotisServo.cpp