APM:Libraries: AP_Param Class Reference
AP_Param Class Reference
#include <AP_Param.h>
Classes
struct ConversionInfo
struct defaults_table_struct
struct EEPROM_header
struct GroupInfo
struct GroupNesting
struct Info
struct param_defaults_struct
struct Param_header
struct param_override
struct param_save
struct ParamToken
Public Types
enum { CONVERT_FLAG_REVERSE =1, CONVERT_FLAG_FORCE =2 }
Public Member Functions
AP_Param (const struct Info *info)
AP_Param ()
void copy_name_info (const struct AP_Param::Info *info, const struct GroupInfo *ginfo, const struct GroupNesting &group_nesting, uint8_t idx, char *buffer, size_t bufferSize, bool force_scalar=false) const
void copy_name_token (const ParamToken &token, char *buffer, size_t bufferSize, bool force_scalar=false) const
void notify () const
void save_sync (bool force_save=false)
void save (bool force_save=false)
bool load (void)
void set_float (float value, enum ap_var_type var_type)
float cast_to_float (enum ap_var_type type) const
cast a variable to a float given its type
bool configured_in_defaults_file (void) const
bool configured_in_storage (void) const
bool configured (void) const
Static Public Member Functions
static bool setup ()
static bool initialised (void)
static uint32_t group_id (const struct GroupInfo *grpinfo, uint32_t base, uint8_t i, uint8_t shift)
static AP_Param * find (const char *name, enum ap_var_type *ptype)
static bool set_default_by_name (const char *name, float value)
static void set_defaults_from_table (const struct defaults_table_struct *table, uint8_t count)
static bool set_by_name (const char *name, float value)
static bool set_and_save_by_name (const char *name, float value)
static AP_Param * find_by_index (uint16_t idx, enum ap_var_type *ptype, ParamToken *token)
static bool find_key_by_pointer_group (const void *ptr, uint16_t vindex, const struct GroupInfo *group_info, ptrdiff_t offset, uint16_t &key)
static bool find_key_by_pointer (const void *ptr, uint16_t &key)
static AP_Param * find_object (const char *name)
static void flush (void)
static bool load_all ()
static void reload_defaults_file (bool last_pass)
static void load_object_from_eeprom (const void *object_pointer, const struct GroupInfo *group_info)
static void set_value (enum ap_var_type type, void *ptr, float def_value)
static void setup_object_defaults (const void *object_pointer, const struct GroupInfo *group_info)
static bool set_object_value (const void *object_pointer, const struct GroupInfo *group_info, const char *name, float value)
static void setup_sketch_defaults (void)
static bool find_old_parameter (const struct ConversionInfo *info, AP_Param *value)
static void convert_old_parameters (const struct ConversionInfo *conversion_table, uint8_t table_size, uint8_t flags=0)
static void convert_old_parameter (const struct ConversionInfo *info, float scaler, uint8_t flags=0)
static void convert_parent_class (uint8_t param_key, void *object_pointer, const struct AP_Param::GroupInfo *group_info)
static void erase_all (void)
static AP_Param * first (ParamToken *token, enum ap_var_type *ptype)
static AP_Param * next (ParamToken *token, enum ap_var_type *ptype)
static AP_Param * next_scalar (ParamToken *token, enum ap_var_type *ptype)
static bool check_var_info (void)
static uint16_t count_parameters (void)
static void set_hide_disabled_groups (bool value)
static void set_frame_type_flags (uint16_t flags_to_set)
static bool check_frame_type (uint16_t flags)
Private Member Functions
const struct Info * find_var_info_group (const struct GroupInfo *group_info, uint16_t vindex, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
const struct Info * find_var_info (uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
const struct Info * find_var_info_token (const ParamToken &token, uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
void add_vector3f_suffix (char *buffer, size_t buffer_size, uint8_t idx) const
void send_parameter (const char *name, enum ap_var_type param_header_type, uint8_t idx) const
void save_io_handler (void)
Static Private Member Functions
static bool check_group_info (const struct GroupInfo *group_info, uint16_t *total_size, uint8_t max_bits, uint8_t prefix_length)
static bool duplicate_key (uint16_t vindex, uint16_t key)
static bool adjust_group_offset (uint16_t vindex, const struct GroupInfo &group_info, ptrdiff_t &new_offset)
static bool get_base (const struct Info &info, ptrdiff_t &base)
static const struct GroupInfo * get_group_info (const struct GroupInfo &ginfo)
get group_info pointer based on flags
static const struct GroupInfo * get_group_info (const struct Info &ginfo)
get group_info pointer based on flags
static const struct Info * find_by_header_group (struct Param_header phdr, void **ptr, uint16_t vindex, const struct GroupInfo *group_info, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset)
static const struct Info * find_by_header (struct Param_header phdr, void **ptr)
static AP_Param * find_group (const char *name, uint16_t vindex, ptrdiff_t group_offset, const struct GroupInfo *group_info, enum ap_var_type *ptype)
static void write_sentinal (uint16_t ofs)
static uint16_t get_key (const Param_header &phdr)
static void set_key (Param_header &phdr, uint16_t key)
static bool is_sentinal (const Param_header &phrd)
static bool scan (const struct Param_header *phdr, uint16_t *pofs)
static uint8_t type_size (enum ap_var_type type)
static void eeprom_write_check (const void *ptr, uint16_t ofs, uint8_t size)
static AP_Param * next_group (uint16_t vindex, const struct GroupInfo *group_info, bool *found_current, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, ParamToken *token, enum ap_var_type *ptype)
static float get_default_value (const AP_Param *object_ptr, const float *def_value_ptr)
static bool parse_param_line (char *line, char **vname, float &value)
static bool count_embedded_param_defaults (uint16_t &count)
static void load_embedded_param_defaults (bool last_pass)
Static Private Attributes
static const uint8_t _group_level_shift = 6
static const uint8_t _group_bits = 18
static const uint16_t _sentinal_key = 0x1FF
static const uint8_t _sentinal_type = 0x1F
static const uint8_t _sentinal_group = 0xFF
static uint16_t _frame_type_flags
static const param_defaults_struct param_defaults_data
static StorageAccess _storage
static uint16_t _num_vars
static uint16_t _parameter_count
static const struct Info * _var_info
static struct param_override * param_overrides = nullptr
static uint16_t num_param_overrides = 0
static const uint8_t k_EEPROM_magic0 = 0x50
static const uint8_t k_EEPROM_magic1 = 0x41
"AP"
static const uint8_t k_EEPROM_revision = 6
current format revision
static bool _hide_disabled_groups = true
static ObjectBuffer< struct param_save > save_queue {30}
static bool registered_save_handler
Detailed Description
Base class for variables.
Provides naming and lookup services for variables.
Definition at line 136 of file AP_Param.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
CONVERT_FLAG_REVERSE
CONVERT_FLAG_FORCE
Definition at line 381 of file AP_Param.h.
Constructor & Destructor Documentation
AP_Param() [1/2]
AP_Param::AP_Param (const struct Info * info) inline
Definition at line 185 of file AP_Param.h.
AP_Param() [2/2]
AP_Param::AP_Param () inline
Definition at line 194 of file AP_Param.h.
Member Function Documentation
add_vector3f_suffix()
void AP_Param::add_vector3f_suffix (char * buffer, size_t buffer_size, uint8_t idx) const private
add a _X, _Y, _Z suffix to the name of a Vector3f element
Parameters
buffer
buffer_size
idx Suffix: 0 --> _X; 1 --> _Y; 2 --> _Z; (other --> undefined)
Definition at line 705 of file AP_Param.cpp.
Referenced by copy_name_info().
adjust_group_offset()
bool AP_Param::adjust_group_offset (uint16_t vindex, const struct GroupInfo & group_info, ptrdiff_t & new_offset) static private
Definition at line 333 of file AP_Param.cpp.
Referenced by find_by_header_group(), find_group(), find_key_by_pointer_group(), find_var_info_group(), load_object_from_eeprom(), and next_group().
cast_to_float()
float AP_Param::cast_to_float (enum ap_var_type type) const
cast a variable to a float given its type
Definition at line 1644 of file AP_Param.cpp.
Referenced by convert_old_parameter(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::queued_param_send(), save_sync(), and send_parameter().
check_frame_type()
bool AP_Param::check_frame_type (uint16_t flags) static
Definition at line 158 of file AP_Param.cpp.
Referenced by next(), and next_group().
check_group_info()
bool AP_Param::check_group_info (const struct GroupInfo * group_info, uint16_t * total_size, uint8_t max_bits, uint8_t prefix_length) static private
Definition at line 168 of file AP_Param.cpp.
Referenced by check_var_info().
check_var_info()
bool AP_Param::check_var_info (void) static
Definition at line 257 of file AP_Param.cpp.
configured()
bool AP_Param::configured (void) const inline
Definition at line 423 of file AP_Param.h.
Referenced by SITL::FlightAxis::FlightAxis(), SITL::Morse::Morse(), AP_ParamT< T, PT >::set_default(), and SITL::SilentWings::SilentWings().
configured_in_defaults_file()
bool AP_Param::configured_in_defaults_file (void) const
Definition at line 1220 of file AP_Param.cpp.
Referenced by configured().
configured_in_storage()
bool AP_Param::configured_in_storage (void) const
Definition at line 1190 of file AP_Param.cpp.
Referenced by configured(), convert_old_parameter(), and load_embedded_param_defaults().
convert_old_parameter()
void AP_Param::convert_old_parameter (const struct ConversionInfo * info, float scaler, uint8_t flags = 0) static
Definition at line 1685 of file AP_Param.cpp.
Referenced by convert_old_parameters(), RangeFinder::convert_params(), and AP_BattMonitor::convert_params().
convert_old_parameters()
void AP_Param::convert_old_parameters (const struct ConversionInfo * conversion_table, uint8_t table_size, uint8_t flags = 0) static
Definition at line 1743 of file AP_Param.cpp.
convert_parent_class()
void AP_Param::convert_parent_class (uint8_t param_key, void * object_pointer, const struct AP_Param::GroupInfo * group_info) static
Definition at line 1757 of file AP_Param.cpp.
copy_name_info()
void AP_Param::copy_name_info (const struct AP_Param::Info * info, const struct GroupInfo * ginfo, const struct GroupNesting & group_nesting, uint8_t idx, char * buffer, size_t bufferSize, bool force_scalar = false) const
Copy the variable's name, prefixed by any containing group name, to a buffer.
If the variable has no name, the buffer will contain an empty string.
Note that if the combination of names is larger than the buffer, the result in the buffer will be truncated.
Parameters
token token giving current variable
buffer The destination buffer
bufferSize Total size of the destination buffer.
Definition at line 736 of file AP_Param.cpp.
Referenced by copy_name_token(), notify(), and save_sync().
copy_name_token()
void AP_Param::copy_name_token (const ParamToken & token, char * buffer, size_t bufferSize, bool force_scalar = false) const
Copy the variable's name, prefixed by any containing group name, to a buffer.
Uses token to look up AP_Param::Info for the variable
Definition at line 721 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::queued_param_send().
count_embedded_param_defaults()
bool AP_Param::count_embedded_param_defaults (uint16_t & count) static private
Definition at line 1978 of file AP_Param.cpp.
Referenced by load_embedded_param_defaults().
count_parameters()
uint16_t AP_Param::count_parameters (void) static
Definition at line 2152 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_request_list(), GCS_MAVLINK::param_io_timer(), and GCS::send_parameter_value().
duplicate_key()
bool AP_Param::duplicate_key (uint16_t vindex, uint16_t key) static private
Definition at line 222 of file AP_Param.cpp.
Referenced by check_var_info().
eeprom_write_check()
void AP_Param::eeprom_write_check (const void * ptr, uint16_t ofs, uint8_t size) static private
Definition at line 97 of file AP_Param.cpp.
Referenced by erase_all(), save_sync(), and write_sentinal().
erase_all()
void AP_Param::erase_all (void) static
Erase all variables in EEPROM.
Definition at line 116 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_parse_command_line(), GCS_MAVLINK::handle_command_long_packet(), and setup().
find()
AP_Param * AP_Param::find (const char * name, enum ap_var_type * ptype) static
Find a variable by name.
If the variable has no name, it cannot be found by this interface.
Parameters
name The full name of the variable to be found.
Returns
A pointer to the variable, or nullptr if it does not exist.
Definition at line 828 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_set_param_default(), SITL::Aircraft::Aircraft(), AP_Proximity_SITL::AP_Proximity_SITL(), convert_old_parameter(), count_embedded_param_defaults(), SITL::FlightAxis::FlightAxis(), GCS_MAVLINK::handle_param_set(), load_embedded_param_defaults(), SITL::Morse::Morse(), GCS_MAVLINK::param_io_timer(), set_and_save_by_name(), set_by_name(), set_default_by_name(), and SITL::SilentWings::SilentWings().
find_by_header()
const struct AP_Param::Info * AP_Param::find_by_header (struct Param_header phdr, void ** ptr) static private
Definition at line 424 of file AP_Param.cpp.
Referenced by load_all(), and load_object_from_eeprom().
find_by_header_group()
const struct AP_Param::Info * AP_Param::find_by_header_group (struct Param_header phdr, void ** ptr, uint16_t vindex, const struct GroupInfo * group_info, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset) static private
Definition at line 373 of file AP_Param.cpp.
Referenced by find_by_header().
find_by_index()
AP_Param * AP_Param::find_by_index (uint16_t idx, enum ap_var_type * ptype, ParamToken * token) static
Find a variable by index.
Parameters
idx The index of the variable
Returns
A pointer to the variable, or nullptr if it does not exist.
Definition at line 863 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::param_io_timer().
find_group()
AP_Param * AP_Param::find_group (const char * name, uint16_t vindex, ptrdiff_t group_offset, const struct GroupInfo * group_info, enum ap_var_type * ptype) static private
Definition at line 764 of file AP_Param.cpp.
Referenced by find().
find_key_by_pointer()
bool AP_Param::find_key_by_pointer (const void * ptr, uint16_t & key) static
Definition at line 919 of file AP_Param.cpp.
Referenced by load_object_from_eeprom().
find_key_by_pointer_group()
bool AP_Param::find_key_by_pointer_group (const void * ptr, uint16_t vindex, const struct GroupInfo * group_info, ptrdiff_t offset, uint16_t & key) static
Find a variable by pointer
Parameters
p Pointer to variable
Returns
key for variable
Definition at line 879 of file AP_Param.cpp.
Referenced by find_key_by_pointer().
find_object()
AP_Param * AP_Param::find_object (const char * name) static
Find a object in the top level var_info table
If the variable has no name, it cannot be found by this interface.
Parameters
name The full name of the variable to be found.
Definition at line 946 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_sitl_setup(), and SITL::Aircraft::Aircraft().
find_old_parameter()
bool AP_Param::find_old_parameter (const struct ConversionInfo * info, AP_Param * value) static
Definition at line 1663 of file AP_Param.cpp.
Referenced by convert_old_parameter(), convert_parent_class(), SRV_Channels::upgrade_motors_servo(), and SRV_Channels::upgrade_parameters().
find_var_info()
const struct AP_Param::Info * AP_Param::find_var_info (uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 526 of file AP_Param.cpp.
Referenced by configured_in_defaults_file(), configured_in_storage(), load(), notify(), and save_sync().
find_var_info_group()
const struct AP_Param::Info * AP_Param::find_var_info_group (const struct GroupInfo * group_info, uint16_t vindex, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 455 of file AP_Param.cpp.
Referenced by find_var_info(), and find_var_info_token().
find_var_info_token()
const struct AP_Param::Info * AP_Param::find_var_info_token (const ParamToken & token, uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 568 of file AP_Param.cpp.
Referenced by copy_name_token().
first()
AP_Param * AP_Param::first (ParamToken * token, enum ap_var_type * ptype) static
Returns the first variable
Returns
The first variable in _var_info, or nullptr if there are none.
Definition at line 1445 of file AP_Param.cpp.
Referenced by count_parameters(), find_by_index(), GCS_MAVLINK::handle_param_request_list(), and LoggerMessageWriter_DFLogStart::reset().
flush()
void AP_Param::flush (void) static
flush all pending parameter saves used on reboot
Definition at line 1117 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_preflight_reboot().
get_base()
bool AP_Param::get_base (const struct Info & info, ptrdiff_t & base) static private
Definition at line 360 of file AP_Param.cpp.
Referenced by adjust_group_offset(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer_group(), find_object(), find_var_info(), find_var_info_group(), find_var_info_token(), first(), load(), next_group(), and setup_sketch_defaults().
get_default_value()
float AP_Param::get_default_value (const AP_Param * object_ptr, const float * def_value_ptr) static private
Definition at line 2103 of file AP_Param.cpp.
Referenced by load(), save_sync(), setup_object_defaults(), and setup_sketch_defaults().
get_group_info() [1/2]
const struct AP_Param::GroupInfo * AP_Param::get_group_info (const struct GroupInfo & ginfo) static private
get group_info pointer based on flags
Definition at line 237 of file AP_Param.cpp.
Referenced by check_group_info(), check_var_info(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer(), find_key_by_pointer_group(), find_var_info(), find_var_info_group(), find_var_info_token(), load_object_from_eeprom(), next(), and next_group().
get_group_info() [2/2]
const struct AP_Param::GroupInfo * AP_Param::get_group_info (const struct Info & ginfo) static private
get group_info pointer based on flags
Definition at line 248 of file AP_Param.cpp.
get_key()
uint16_t AP_Param::get_key (const Param_header & phdr) static private
Definition at line 633 of file AP_Param.cpp.
Referenced by find_by_header(), is_sentinal(), load_object_from_eeprom(), and scan().
group_id()
uint32_t AP_Param::group_id (const struct GroupInfo * grpinfo, uint32_t base, uint8_t i, uint8_t shift) static
Definition at line 138 of file AP_Param.cpp.
Referenced by find_by_header_group(), find_var_info_group(), and next_group().
initialised()
bool AP_Param::initialised (void) static
Definition at line 322 of file AP_Param.cpp.
is_sentinal()
bool AP_Param::is_sentinal (const Param_header & phrd) static private
Definition at line 650 of file AP_Param.cpp.
Referenced by load_all(), load_object_from_eeprom(), and scan().
load()
bool AP_Param::load (void)
Load the variable from EEPROM.
Returns
True if the variable was loaded successfully.
Definition at line 1127 of file AP_Param.cpp.
load_all()
bool AP_Param::load_all () static
Load all variables from EEPROM
This function performs a best-efforts attempt to load all of the variables from EEPROM. If some fail to load, their values will remain as they are.
Returns
False if any variable failed to load
Definition at line 1323 of file AP_Param.cpp.
load_embedded_param_defaults()
void AP_Param::load_embedded_param_defaults (bool last_pass) static private
Definition at line 2029 of file AP_Param.cpp.
Referenced by reload_defaults_file().
load_object_from_eeprom()
void AP_Param::load_object_from_eeprom (const void * object_pointer, const struct GroupInfo * group_info) static
Definition at line 1393 of file AP_Param.cpp.
Referenced by RangeFinder::detect_instance().
next()
AP_Param * AP_Param::next (ParamToken * token, enum ap_var_type * ptype) static
Returns the next variable in _var_info, recursing into groups as needed
Definition at line 1539 of file AP_Param.cpp.
Referenced by next_scalar().
next_group()
AP_Param * AP_Param::next_group (uint16_t vindex, const struct GroupInfo * group_info, bool * found_current, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, ParamToken * token, enum ap_var_type * ptype) static private
Returns the next variable in a group, recursing into groups as needed
Definition at line 1466 of file AP_Param.cpp.
Referenced by next().
next_scalar()
AP_Param * AP_Param::next_scalar (ParamToken * token, enum ap_var_type * ptype) static
Returns the next scalar variable in _var_info, recursing into groups as needed
Returns the next scalar in _var_info, recursing into groups as needed
Definition at line 1593 of file AP_Param.cpp.
Referenced by count_parameters(), find_by_index(), LoggerMessageWriter_DFLogStart::process(), and GCS_MAVLINK::queued_param_send().
notify()
void AP_Param::notify () const
Notify GCS of current parameter value
Definition at line 961 of file AP_Param.cpp.
Referenced by AP_ParamT< T, PT >::set_and_notify(), and AP_ParamV< T, PT >::set_and_notify().
parse_param_line()
bool AP_Param::parse_param_line (char * line, char ** vname, float & value) static private
Definition at line 1819 of file AP_Param.cpp.
Referenced by count_embedded_param_defaults(), and load_embedded_param_defaults().
reload_defaults_file()
void AP_Param::reload_defaults_file (bool last_pass) static
reoad the hal.util defaults file. Called after pointer parameters have been allocated
Definition at line 1365 of file AP_Param.cpp.
Referenced by load_all().
save()
void AP_Param::save (bool force_save = false)
Save the current value of the variable to storage, async interface
Parameters
force_save If true then force save even if default
Definition at line 1084 of file AP_Param.cpp.
Referenced by convert_old_parameter(), SITL::FlightAxis::FlightAxis(), GCS_MAVLINK::handle_param_set(), SITL::Morse::Morse(), AP_ParamT< T, PT >::set_and_save(), AP_ParamV< T, PT >::set_and_save(), AP_ParamT< T, PT >::set_and_save_ifchanged(), and SITL::SilentWings::SilentWings().
save_io_handler()
void AP_Param::save_io_handler (void) private
Definition at line 1106 of file AP_Param.cpp.
Referenced by load_all().
save_sync()
void AP_Param::save_sync (bool force_save = false)
Save the current value of the variable to storage, synchronous API
Parameters
force_save If true then force save even if default
Returns
True if the variable was saved successfully.
Definition at line 990 of file AP_Param.cpp.
Referenced by save_io_handler().
scan()
bool AP_Param::scan (const struct Param_header * phdr, uint16_t * pofs) static private
Definition at line 674 of file AP_Param.cpp.
Referenced by configured_in_storage(), find_old_parameter(), load(), and save_sync().
send_parameter()
void AP_Param::send_parameter (const char * name, enum ap_var_type param_header_type, uint8_t idx) const private
Definition at line 2114 of file AP_Param.cpp.
Referenced by notify(), and save_sync().
set_and_save_by_name()
bool AP_Param::set_and_save_by_name (const char * name, float value) static
set and save a value by name
Parameters
name The full name of the variable to be found.
value The new value
Returns
true if the variable is found
Definition at line 2249 of file AP_Param.cpp.
set_by_name()
bool AP_Param::set_by_name (const char * name, float value) static
set a value by name
Parameters
name The full name of the variable to be found.
value The new value
Returns
true if the variable is found
Definition at line 2219 of file AP_Param.cpp.
set_default_by_name()
bool AP_Param::set_default_by_name (const char * name, float value) static
set a default value by name
Parameters
name The full name of the variable to be found.
value The default value
Returns
true if the variable is found
Definition at line 2173 of file AP_Param.cpp.
Referenced by SITL::FlightAxis::FlightAxis(), SITL::Morse::Morse(), set_defaults_from_table(), SITL::SilentWings::SilentWings(), and SITL::XPlane::XPlane().
set_defaults_from_table()
void AP_Param::set_defaults_from_table (const struct defaults_table_struct * table, uint8_t count) static
set parameter defaults from a defaults_table_struct
Parameters
table pointer to array of defaults_table_struct structures
count number of elements in table array
Definition at line 2204 of file AP_Param.cpp.
set_float()
void AP_Param::set_float (float value, enum ap_var_type var_type)
Definition at line 1783 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), and load_embedded_param_defaults().
set_frame_type_flags()
static void AP_Param::set_frame_type_flags (uint16_t flags_to_set) inline static
Definition at line 431 of file AP_Param.h.
set_hide_disabled_groups()
static void AP_Param::set_hide_disabled_groups (bool value) inline static
Definition at line 428 of file AP_Param.h.
Referenced by HALSITL::SITL_State::_parse_command_line().
set_key()
void AP_Param::set_key (Param_header & phdr, uint16_t key) static private
Definition at line 641 of file AP_Param.cpp.
Referenced by configured_in_storage(), find_old_parameter(), load(), save_sync(), and write_sentinal().
set_object_value()
bool AP_Param::set_object_value (const void * object_pointer, const struct GroupInfo * group_info, const char * name, float value) static
Definition at line 1282 of file AP_Param.cpp.
Referenced by set_object_value_and_report(), and setup().
set_value()
void AP_Param::set_value (enum ap_var_type type, void * ptr, float def_value) static
Definition at line 1242 of file AP_Param.cpp.
Referenced by convert_old_parameter(), load(), set_object_value(), setup_object_defaults(), and setup_sketch_defaults().
setup()
bool AP_Param::setup (void) static
Definition at line 303 of file AP_Param.cpp.
Referenced by setup_sketch_defaults().
setup_object_defaults()
void AP_Param::setup_object_defaults (const void * object_pointer, const struct GroupInfo * group_info) static
Definition at line 1265 of file AP_Param.cpp.
Referenced by AC_AttitudeControl::AC_AttitudeControl(), AC_AttitudeControl_Heli::AC_AttitudeControl_Heli(), AC_AttitudeControl_Multi::AC_AttitudeControl_Multi(), AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), AC_AutoTune::AC_AutoTune(), AC_Avoid::AC_Avoid(), AC_Circle::AC_Circle(), AC_Fence::AC_Fence(), AC_InputManager::AC_InputManager(), AC_InputManager_Heli::AC_InputManager_Heli(), AC_Loiter::AC_Loiter(), AC_P::AC_P(), AC_PI_2D::AC_PI_2D(), AC_PID::AC_PID(), AC_PID_2D::AC_PID_2D(), AC_PosControl::AC_PosControl(), AC_PrecLand::AC_PrecLand(), AC_Sprayer::AC_Sprayer(), AC_WPNav::AC_WPNav(), AP_ADSB::AP_ADSB(), AP_AdvancedFailsafe::AP_AdvancedFailsafe(), AP_AHRS::AP_AHRS(), AP_Airspeed::AP_Airspeed(), AP_Arming::AP_Arming(), AP_Avoidance::AP_Avoidance(), AP_Baro::AP_Baro(), AP_BattMonitor::AP_BattMonitor(), AP_BattMonitor_Params::AP_BattMonitor_Params(), AP_Beacon::AP_Beacon(), AP_BoardConfig::AP_BoardConfig(), AP_Button::AP_Button(), AP_Camera::AP_Camera(), AP_Follow::AP_Follow(), AP_GPS::AP_GPS(), AP_Gripper::AP_Gripper(), AP_ICEngine::AP_ICEngine(), AP_InertialSensor::AP_InertialSensor(), AP_L1_Control::AP_L1_Control(), AP_Landing::AP_Landing(), AP_Landing_Deepstall::AP_Landing_Deepstall(), AP_LandingGear::AP_LandingGear(), AP_LeakDetector::AP_LeakDetector(), AP_Logger::AP_Logger(), AP_Mission::AP_Mission(), AP_Motors6DOF::AP_Motors6DOF(), AP_MotorsHeli::AP_MotorsHeli(), AP_MotorsHeli_Dual::AP_MotorsHeli_Dual(), AP_MotorsHeli_Quad::AP_MotorsHeli_Quad(), AP_MotorsHeli_Single::AP_MotorsHeli_Single(), AP_MotorsHeli_Swash::AP_MotorsHeli_Swash(), AP_MotorsMatrixTS::AP_MotorsMatrixTS(), AP_MotorsMulticopter::AP_MotorsMulticopter(), AP_Mount::AP_Mount(), AP_Notify::AP_Notify(), AP_OAPathPlanner::AP_OAPathPlanner(), AP_OSD::AP_OSD(), AP_Parachute::AP_Parachute(), AP_PitchController::AP_PitchController(), AP_Proximity::AP_Proximity(), AP_Rally::AP_Rally(), AP_RangeFinder_Params::AP_RangeFinder_Params(), AP_RangeFinder_Wasp::AP_RangeFinder_Wasp(), AP_Relay::AP_Relay(), AP_RobotisServo::AP_RobotisServo(), AP_RollController::AP_RollController(), AP_RPM::AP_RPM(), AP_RSSI::AP_RSSI(), AP_RTC::AP_RTC(), AP_SBusOut::AP_SBusOut(), AP_Scheduler::AP_Scheduler(), AP_SerialManager::AP_SerialManager(), AP_SmartRTL::AP_SmartRTL(), AP_SteerController::AP_SteerController(), AP_TECS::AP_TECS(), AP_Tuning::AP_Tuning(), AP_VisualOdom::AP_VisualOdom(), AP_Volz_Protocol::AP_Volz_Protocol(), AP_WheelEncoder::AP_WheelEncoder(), AP_WheelRateControl::AP_WheelRateControl(), AP_Winch::AP_Winch(), AP_WindVane::AP_WindVane(), AP_YawController::AP_YawController(), AR_AttitudeControl::AR_AttitudeControl(), AR_WPNav::AR_WPNav(), AP_InertialSensor::BatchSampler::BatchSampler(), Compass::Compass(), Compass_PerMotor::Compass_PerMotor(), GCS_MAVLINK::GCS_MAVLINK(), SITL::Gripper_EPM::Gripper_EPM(), SITL::Gripper_Servo::Gripper_Servo(), JSButton::JSButton(), NavEKF2::NavEKF2(), NavEKF3::NavEKF3(), NotchFilterParams::NotchFilterParams(), OpticalFlow::OpticalFlow(), SITL::Parachute::Parachute(), PID::PID(), RangeFinder::RangeFinder(), RC_Channel::RC_Channel(), RC_Channels::RC_Channels(), RCMapper::RCMapper(), RSCGovParam::RSCGovParam(), RSCThrCrvParam::RSCThrCrvParam(), SITL::SIM_Precland::SIM_Precland(), SITL::SITL::SITL(), SoaringController::SoaringController(), SoloGimbalEKF::SoloGimbalEKF(), SITL::Sprayer::Sprayer(), SRV_Channel::SRV_Channel(), and SRV_Channels::SRV_Channels().
setup_sketch_defaults()
void AP_Param::setup_sketch_defaults (void) static
Definition at line 1305 of file AP_Param.cpp.
type_size()
uint8_t AP_Param::type_size (enum ap_var_type type) static private
Definition at line 609 of file AP_Param.cpp.
Referenced by check_group_info(), check_var_info(), convert_old_parameter(), convert_parent_class(), find_old_parameter(), load(), load_all(), load_object_from_eeprom(), save_sync(), and scan().
write_sentinal()
void AP_Param::write_sentinal (uint16_t ofs) static private
Definition at line 105 of file AP_Param.cpp.
Referenced by erase_all(), and save_sync().
Member Data Documentation
_frame_type_flags
uint16_t AP_Param::_frame_type_flags static private
Definition at line 495 of file AP_Param.h.
Referenced by check_frame_type(), and set_frame_type_flags().
_group_bits
const uint8_t AP_Param::_group_bits = 18 static private
Definition at line 489 of file AP_Param.h.
Referenced by check_group_info(), find_by_header_group(), and find_var_info_group().
_group_level_shift
const uint8_t AP_Param::_group_level_shift = 6 static private
Definition at line 488 of file AP_Param.h.
Referenced by check_group_info(), find_by_header_group(), find_var_info_group(), and next_group().
_hide_disabled_groups
bool AP_Param::_hide_disabled_groups = true static private
Definition at line 628 of file AP_Param.h.
Referenced by next_scalar(), and set_hide_disabled_groups().
_num_vars
uint16_t AP_Param::_num_vars static private
Definition at line 609 of file AP_Param.h.
Referenced by AP_Param(), check_var_info(), duplicate_key(), find(), find_by_header(), find_key_by_pointer(), find_object(), find_var_info(), first(), next(), and setup_sketch_defaults().
_parameter_count
uint16_t AP_Param::_parameter_count static private
Definition at line 610 of file AP_Param.h.
Referenced by count_parameters(), load_object_from_eeprom(), and save_sync().
_sentinal_group
const uint8_t AP_Param::_sentinal_group = 0xFF static private
Definition at line 493 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
_sentinal_key
const uint16_t AP_Param::_sentinal_key = 0x1FF static private
Definition at line 491 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
_sentinal_type
const uint8_t AP_Param::_sentinal_type = 0x1F static private
Definition at line 492 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
_storage
StorageAccess AP_Param::_storage static private
Definition at line 608 of file AP_Param.h.
Referenced by eeprom_write_check(), find_old_parameter(), load(), load_all(), load_object_from_eeprom(), save_sync(), scan(), and setup().
_var_info
const AP_Param::Info * AP_Param::_var_info static private
Definition at line 611 of file AP_Param.h.
Referenced by adjust_group_offset(), AP_Param(), check_var_info(), duplicate_key(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer(), find_key_by_pointer_group(), find_object(), find_var_info(), find_var_info_group(), find_var_info_token(), first(), initialised(), next(), next_group(), and setup_sketch_defaults().
k_EEPROM_magic0
const uint8_t AP_Param::k_EEPROM_magic0 = 0x50 static private
Definition at line 624 of file AP_Param.h.
Referenced by erase_all(), and setup().
k_EEPROM_magic1
const uint8_t AP_Param::k_EEPROM_magic1 = 0x41 static private
"AP"
Definition at line 625 of file AP_Param.h.
Referenced by erase_all(), and setup().
k_EEPROM_revision
const uint8_t AP_Param::k_EEPROM_revision = 6 static private
current format revision
Definition at line 626 of file AP_Param.h.
Referenced by erase_all(), and setup().
num_param_overrides
uint16_t AP_Param::num_param_overrides = 0 static private
Definition at line 621 of file AP_Param.h.
Referenced by configured_in_defaults_file(), get_default_value(), and load_embedded_param_defaults().
param_defaults_data
const AP_Param::param_defaults_struct AP_Param::param_defaults_data static private
Initial value:
= {
    "PARMDEF",
    { 0x55, 0x37, 0xf4, 0xa0, 0x38, 0x5d, 0x48, 0x5b },
    AP_PARAM_MAX_EMBEDDED_PARAM,
    0
}
Definition at line 507 of file AP_Param.h.
Referenced by count_embedded_param_defaults(), load_embedded_param_defaults(), and reload_defaults_file().
param_overrides
struct AP_Param::param_override * AP_Param::param_overrides = nullptr static private
Definition at line 620 of file AP_Param.h.
Referenced by configured_in_defaults_file(), get_default_value(), and load_embedded_param_defaults().
registered_save_handler
bool AP_Param::registered_save_handler static private
Definition at line 637 of file AP_Param.h.
Referenced by load_all().
save_queue
ObjectBuffer< AP_Param::param_save > AP_Param::save_queue {30} static private
Definition at line 636 of file AP_Param.h.
Referenced by flush(), save(), and save_io_handler().
The documentation for this class was generated from the following files:
libraries/AP_Param/AP_Param.h
libraries/AP_Param/AP_Param.cpp