APM:Libraries: SRV_Channels Class Reference
SRV_Channels Class Reference
#include <SRV_Channel.h>
Classes
struct srv_function
Public Member Functions
SRV_Channels (void)
void set_esc_scaling_for (SRV_Channel::Aux_servo_function_t function)
bool auto_trim_enabled (void) const
void adjust_trim (SRV_Channel::Aux_servo_function_t function, float v)
void save_trim (void)
void set_reversible_throttle (void)
void disable_passthrough (bool disable)
Static Public Member Functions
static void set_default_function (uint8_t chan, SRV_Channel::Aux_servo_function_t function)
static void set_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t value)
static void set_output_pwm_first (SRV_Channel::Aux_servo_function_t function, uint16_t value)
static void set_output_pwm_chan (uint8_t chan, uint16_t value)
static void set_output_scaled (SRV_Channel::Aux_servo_function_t function, int16_t value)
static int16_t get_output_scaled (SRV_Channel::Aux_servo_function_t function)
static bool get_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t &value)
static float get_output_norm (SRV_Channel::Aux_servo_function_t function)
static uint16_t get_output_channel_mask (SRV_Channel::Aux_servo_function_t function)
static void limit_slew_rate (SRV_Channel::Aux_servo_function_t function, float slew_rate, float dt)
static void output_ch_all (void)
static void set_output_min_max (SRV_Channel::Aux_servo_function_t function, uint16_t min_pwm, uint16_t max_pwm)
static void setup_failsafe_trim_all_non_motors (void)
static void set_output_pwm_trimmed (SRV_Channel::Aux_servo_function_t function, int16_t value)
static void set_trim_to_servo_out_for (SRV_Channel::Aux_servo_function_t function)
static void set_trim_to_min_for (SRV_Channel::Aux_servo_function_t function)
static void set_trim_to_pwm_for (SRV_Channel::Aux_servo_function_t function, int16_t pwm)
static void set_output_to_min (SRV_Channel::Aux_servo_function_t function)
static void set_output_to_max (SRV_Channel::Aux_servo_function_t function)
static void set_output_to_trim (SRV_Channel::Aux_servo_function_t function)
static void copy_radio_in_out (SRV_Channel::Aux_servo_function_t function, bool do_input_output=false)
static void copy_radio_in_out_mask (uint16_t mask)
static void set_failsafe_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t pwm)
static void set_failsafe_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::LimitValue limit)
static void set_safety_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::LimitValue limit)
static void set_output_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::LimitValue limit)
static bool function_assigned (SRV_Channel::Aux_servo_function_t function)
static void move_servo (SRV_Channel::Aux_servo_function_t function, int16_t value, int16_t angle_min, int16_t angle_max)
static void enable_aux_servos (void)
Should be called after the the servo functions have been initialized.
static void enable_by_mask (uint16_t mask)
enable output channels using a channel mask
static SRV_Channel::Aux_servo_function_t channel_function (uint8_t channel)
static void update_aux_servo_function (void)
setup the output range types of all functions
static bool set_aux_channel_default (SRV_Channel::Aux_servo_function_t function, uint8_t channel)
static bool find_channel (SRV_Channel::Aux_servo_function_t function, uint8_t &chan)
static SRV_Channel * get_channel_for (SRV_Channel::Aux_servo_function_t function, int8_t default_chan=-1)
static void set_angle (SRV_Channel::Aux_servo_function_t function, uint16_t angle)
static void set_range (SRV_Channel::Aux_servo_function_t function, uint16_t range)
static void set_rc_frequency (SRV_Channel::Aux_servo_function_t function, uint16_t frequency)
static void constrain_pwm (SRV_Channel::Aux_servo_function_t function)
static void calc_pwm (void)
static SRV_Channel * srv_channel (uint8_t i)
static bool upgrade_parameters (const uint8_t old_keys[14], uint16_t aux_channel_mask, RCMapper *rcmap)
static void upgrade_motors_servo (uint8_t ap_motors_key, uint8_t ap_motors_idx, uint8_t new_channel)
static SRV_Channel::Aux_servo_function_t get_motor_function (uint8_t channel)
static void cork ()
static void push ()
static void set_disabled_channel_mask (uint16_t mask)
static void set_reversible_mask (uint16_t mask)
static void set_digital_mask (uint16_t mask)
static void set_emergency_stop (bool state)
static bool get_emergency_stop ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Static Private Member Functions
static bool passthrough_disabled (void)
Private Attributes
struct {
bool k_throttle_reversible:1
} flags
SRV_Channel::servo_mask_t trimmed_mask
AP_Volz_Protocol volz
AP_SBusOut sbus
AP_RobotisServo robotis
SRV_Channel obj_channels [NUM_SERVO_CHANNELS]
AP_Int8 auto_trim
AP_Int16 default_rate
Static Private Attributes
static bool disabled_passthrough
static Bitmask< SRV_Channel::k_nr_aux_servo_functions > function_mask
static bool initialised
static SRV_Channel * channels
static SRV_Channels * _singleton
static AP_Volz_Protocol * volz_ptr
static AP_SBusOut * sbus_ptr
static AP_RobotisServo * robotis_ptr
static uint16_t disabled_mask
static uint16_t digital_mask
static uint16_t reversible_mask
static struct SRV_Channels::srv_function functions [SRV_Channel::k_nr_aux_servo_functions]
static bool emergency_stop
Friends
class SRV_Channel
Detailed Description
Definition at line 287 of file SRV_Channel.h.
Constructor & Destructor Documentation
SRV_Channels()
SRV_Channels::SRV_Channels (void)
Definition at line 162 of file SRV_Channels.cpp.
Member Function Documentation
adjust_trim()
void SRV_Channels::adjust_trim (SRV_Channel::Aux_servo_function_t function, float v)
Definition at line 568 of file SRV_Channel_aux.cpp.
auto_trim_enabled()
bool SRV_Channels::auto_trim_enabled (void) const inline
Definition at line 335 of file SRV_Channel.h.
calc_pwm()
void SRV_Channels::calc_pwm (void) static
Definition at line 208 of file SRV_Channels.cpp.
channel_function()
SRV_Channel::Aux_servo_function_t SRV_Channels::channel_function (uint8_t channel) static
Definition at line 81 of file SRV_Channel_aux.cpp.
constrain_pwm()
void SRV_Channels::constrain_pwm (SRV_Channel::Aux_servo_function_t function) static
Definition at line 703 of file SRV_Channel_aux.cpp.
copy_radio_in_out()
void SRV_Channels::copy_radio_in_out (SRV_Channel::Aux_servo_function_t function, bool do_input_output = false) static
Definition at line 278 of file SRV_Channel_aux.cpp.
copy_radio_in_out_mask()
void SRV_Channels::copy_radio_in_out_mask (uint16_t mask) static
Definition at line 301 of file SRV_Channel_aux.cpp.
cork()
void SRV_Channels::cork (void) static
Definition at line 226 of file SRV_Channels.cpp.
Referenced by GCS_MAVLINK::zero_rc_outputs().
disable_passthrough()
void SRV_Channels::disable_passthrough (bool disable) inline
Definition at line 431 of file SRV_Channel.h.
enable_aux_servos()
void SRV_Channels::enable_aux_servos (void) static
Should be called after the the servo functions have been initialized.
Definition at line 164 of file SRV_Channel_aux.cpp.
Referenced by stability_test().
enable_by_mask()
void SRV_Channels::enable_by_mask (uint16_t mask) static
enable output channels using a channel mask
Definition at line 207 of file SRV_Channel_aux.cpp.
find_channel()
bool SRV_Channels::find_channel (SRV_Channel::Aux_servo_function_t function, uint8_t & chan) static
Definition at line 459 of file SRV_Channel_aux.cpp.
Referenced by AP_Motors::add_motor_num(), get_channel_for(), AP_MotorsTailsitter::get_motor_mask(), get_output_norm(), get_output_pwm(), AP_MotorsTailsitter::init(), Compass_PerMotor::scaled_output(), SITL::XPlane::send_data(), and set_esc_scaling_for().
function_assigned()
bool SRV_Channels::function_assigned (SRV_Channel::Aux_servo_function_t function) static
Definition at line 398 of file SRV_Channel_aux.cpp.
Referenced by AP_Mount_Servo::check_servo_map(), copy_radio_in_out(), find_channel(), AP_Mount::init(), move_servo(), set_aux_channel_default(), set_failsafe_limit(), set_failsafe_pwm(), set_output_limit(), set_output_pwm(), set_output_pwm_trimmed(), set_safety_limit(), set_trim_to_servo_out_for(), AP_Winch_Servo::update(), AC_Sprayer::update(), and AP_Gripper_Servo::valid().
get_channel_for()
SRV_Channel * SRV_Channels::get_channel_for (SRV_Channel::Aux_servo_function_t function, int8_t default_chan = -1) static
Definition at line 479 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsTri::init(), AP_Landing_Deepstall::override_servos(), and AP_Landing_Deepstall::verify_land().
get_emergency_stop()
static bool SRV_Channels::get_emergency_stop () inline static
Definition at line 480 of file SRV_Channel.h.
get_motor_function()
static SRV_Channel::Aux_servo_function_t SRV_Channels::get_motor_function (uint8_t channel) inline static
Definition at line 450 of file SRV_Channel.h.
Referenced by AP_Motors::add_motor_num(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsHeli_Quad::init_outputs(), AP_MotorsHeli_Dual::init_outputs(), AP_MotorsHeli_Single::init_outputs(), AP_MotorsHeli_RSC::init_servo(), AP_Motors::rc_map_mask(), AP_Motors::rc_write(), AP_Motors::rc_write_angle(), and AP_MotorsHeli::rc_write_swash().
get_output_channel_mask()
uint16_t SRV_Channels::get_output_channel_mask (SRV_Channel::Aux_servo_function_t function) static
Definition at line 510 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsMulticopter::get_motor_mask(), and AP_Motors::rc_map_mask().
get_output_norm()
float SRV_Channels::get_output_norm (SRV_Channel::Aux_servo_function_t function) static
Definition at line 631 of file SRV_Channel_aux.cpp.
get_output_pwm()
bool SRV_Channels::get_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t & value) static
Definition at line 595 of file SRV_Channel_aux.cpp.
Referenced by AP_Gripper_Servo::has_state_pwm().
get_output_scaled()
int16_t SRV_Channels::get_output_scaled (SRV_Channel::Aux_servo_function_t function) static
Definition at line 499 of file SRV_Channel_aux.cpp.
Referenced by AP_ICEngine::throttle_override().
limit_slew_rate()
void SRV_Channels::limit_slew_rate (SRV_Channel::Aux_servo_function_t function, float slew_rate, float dt) static
Definition at line 645 of file SRV_Channel_aux.cpp.
move_servo()
void SRV_Channels::move_servo (SRV_Channel::Aux_servo_function_t function, int16_t value, int16_t angle_min, int16_t angle_max) static
Definition at line 408 of file SRV_Channel_aux.cpp.
Referenced by AP_Mount_Servo::move_servo(), and AC_Sprayer::update().
output_ch_all()
void SRV_Channels::output_ch_all (void) static
Definition at line 71 of file SRV_Channel_aux.cpp.
passthrough_disabled()
static bool SRV_Channels::passthrough_disabled (void) inline static private
Definition at line 538 of file SRV_Channel.h.
Referenced by SRV_Channel::output_ch().
push()
void SRV_Channels::push (void) static
Definition at line 234 of file SRV_Channels.cpp.
Referenced by GCS_MAVLINK::zero_rc_outputs().
save_trim()
void SRV_Channels::save_trim (void)
Definition at line 186 of file SRV_Channels.cpp.
set_angle()
void SRV_Channels::set_angle (SRV_Channel::Aux_servo_function_t function, uint16_t angle) static
Definition at line 672 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsTailsitter::init(), AP_Winch_Servo::init(), AP_MotorsSingle::init(), AP_MotorsCoax::init(), AP_MotorsHeli_Quad::init_outputs(), and AP_MotorsHeli_Single::init_outputs().
set_aux_channel_default()
bool SRV_Channels::set_aux_channel_default (SRV_Channel::Aux_servo_function_t function, uint8_t channel) static
Definition at line 432 of file SRV_Channel_aux.cpp.
Referenced by AP_Motors::add_motor_num(), get_channel_for(), AP_MotorsTailsitter::init(), and AP_MotorsHeli_RSC::init_servo().
set_default_function()
void SRV_Channels::set_default_function (uint8_t chan, SRV_Channel::Aux_servo_function_t function) static
Definition at line 545 of file SRV_Channel_aux.cpp.
set_digital_mask()
static void SRV_Channels::set_digital_mask (uint16_t mask) inline static
Definition at line 470 of file SRV_Channel.h.
set_disabled_channel_mask()
static void SRV_Channels::set_disabled_channel_mask (uint16_t mask) inline static
Definition at line 462 of file SRV_Channel.h.
set_emergency_stop()
static void SRV_Channels::set_emergency_stop (bool state) inline static
Definition at line 475 of file SRV_Channel.h.
Referenced by RC_Channel::do_aux_function().
set_esc_scaling_for()
void SRV_Channels::set_esc_scaling_for (SRV_Channel::Aux_servo_function_t function)
Definition at line 556 of file SRV_Channel_aux.cpp.
set_failsafe_limit()
void SRV_Channels::set_failsafe_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::LimitValue limit) static
Definition at line 336 of file SRV_Channel_aux.cpp.
set_failsafe_pwm()
void SRV_Channels::set_failsafe_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t pwm) static
Definition at line 319 of file SRV_Channel_aux.cpp.
set_output_limit()
void SRV_Channels::set_output_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::LimitValue limit) static
Definition at line 372 of file SRV_Channel_aux.cpp.
Referenced by AP_LandingGear::deploy(), AP_LandingGear::retract(), AC_Sprayer::stop_spraying(), AP_Winch_Servo::update(), AP_MotorsHeli_Quad::update_motor_control(), AP_MotorsHeli_Dual::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
set_output_min_max()
void SRV_Channels::set_output_min_max (SRV_Channel::Aux_servo_function_t function, uint16_t min_pwm, uint16_t max_pwm) static
Definition at line 692 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli_Single::init_outputs(), and AP_MotorsHeli::reset_swash_servo().
set_output_pwm()
void SRV_Channels::set_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t value) static
Definition at line 219 of file SRV_Channel_aux.cpp.
Referenced by AP_Camera::configure(), AP_Gripper_Servo::grab(), AP_Gripper_EPM::grab(), lua_servo_set_output_pwm(), AP_Gripper_EPM::neutral(), AP_MotorsTailsitter::output_test_seq(), AP_MotorsTailsitter::output_to_motors(), AP_Motors::rc_write(), AP_Gripper_Servo::release(), AP_Gripper_EPM::release(), AP_Camera::servo_pic(), AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration(), AP_Camera::trigger_pic_cleanup(), AP_ICEngine::update(), AC_Sprayer::update(), and AP_Parachute::update().
set_output_pwm_chan()
void SRV_Channels::set_output_pwm_chan (uint8_t chan, uint16_t value) static
Definition at line 216 of file SRV_Channels.cpp.
Referenced by RCOutputRGBLed::hw_set_rgb().
set_output_pwm_first()
void SRV_Channels::set_output_pwm_first (SRV_Channel::Aux_servo_function_t function, uint16_t value) static
Definition at line 617 of file SRV_Channel_aux.cpp.
set_output_pwm_trimmed()
void SRV_Channels::set_output_pwm_trimmed (SRV_Channel::Aux_servo_function_t function, int16_t value) static
Definition at line 238 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli::rc_write_swash().
set_output_scaled()
void SRV_Channels::set_output_scaled (SRV_Channel::Aux_servo_function_t function, int16_t value) static
Definition at line 491 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsMulticopter::output_boost_throttle(), AP_MotorsMatrixTS::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), AP_Landing_Deepstall::override_servos(), AP_Motors::rc_write_angle(), AP_Winch_Servo::update(), and AP_MotorsHeli_RSC::write_rsc().
set_output_to_max()
static void SRV_Channels::set_output_to_max (SRV_Channel::Aux_servo_function_t function) static
set_output_to_min()
static void SRV_Channels::set_output_to_min (SRV_Channel::Aux_servo_function_t function) static
set_output_to_trim()
void SRV_Channels::set_output_to_trim (SRV_Channel::Aux_servo_function_t function) static
Definition at line 607 of file SRV_Channel_aux.cpp.
set_range()
void SRV_Channels::set_range (SRV_Channel::Aux_servo_function_t function, uint16_t range) static
Definition at line 682 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli_RSC::init_servo(), and AP_MotorsHeli::reset_swash_servo().
set_rc_frequency()
void SRV_Channels::set_rc_frequency (SRV_Channel::Aux_servo_function_t function, uint16_t frequency) static
Definition at line 893 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsTailsitter::set_update_rate().
set_reversible_mask()
static void SRV_Channels::set_reversible_mask (uint16_t mask) inline static
Definition at line 465 of file SRV_Channel.h.
set_reversible_throttle()
void SRV_Channels::set_reversible_throttle (void) inline
Definition at line 347 of file SRV_Channel.h.
set_safety_limit()
void SRV_Channels::set_safety_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::LimitValue limit) static
Definition at line 354 of file SRV_Channel_aux.cpp.
set_trim_to_min_for()
void SRV_Channels::set_trim_to_min_for (SRV_Channel::Aux_servo_function_t function) static
Definition at line 533 of file SRV_Channel_aux.cpp.
set_trim_to_pwm_for()
void SRV_Channels::set_trim_to_pwm_for (SRV_Channel::Aux_servo_function_t function, int16_t pwm) static
Definition at line 523 of file SRV_Channel_aux.cpp.
set_trim_to_servo_out_for()
void SRV_Channels::set_trim_to_servo_out_for (SRV_Channel::Aux_servo_function_t function) static
Definition at line 262 of file SRV_Channel_aux.cpp.
setup_failsafe_trim_all_non_motors()
void SRV_Channels::setup_failsafe_trim_all_non_motors (void) static
Definition at line 196 of file SRV_Channels.cpp.
srv_channel()
static SRV_Channel* SRV_Channels::srv_channel (uint8_t i) inline static
Definition at line 441 of file SRV_Channel.h.
Referenced by AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), GCS_MAVLINK::send_servo_output_raw(), AP_Arming::servo_checks(), setup(), stability_test(), AP_SBusOut::update(), AP_RobotisServo::update(), AP_Volz_Protocol::update(), and AP_ServoRelayEvents::update_events().
update_aux_servo_function()
void SRV_Channels::update_aux_servo_function (void) static
setup the output range types of all functions
Definition at line 141 of file SRV_Channel_aux.cpp.
Referenced by enable_aux_servos(), find_channel(), get_output_channel_mask(), and set_aux_channel_default().
upgrade_motors_servo()
void SRV_Channels::upgrade_motors_servo (uint8_t ap_motors_key, uint8_t ap_motors_idx, uint8_t new_channel) static
Definition at line 840 of file SRV_Channel_aux.cpp.
upgrade_parameters()
bool SRV_Channels::upgrade_parameters (const uint8_t old_keys[14], uint16_t aux_channel_mask, RCMapper * rcmap) static
Definition at line 731 of file SRV_Channel_aux.cpp.
Friends And Related Function Documentation
SRV_Channel
friend class SRV_Channel friend
Definition at line 289 of file SRV_Channel.h.
Member Data Documentation
_singleton
SRV_Channels * SRV_Channels::_singleton static private
Definition at line 496 of file SRV_Channel.h.
Referenced by enable_aux_servos(), and SRV_Channels().
auto_trim
AP_Int8 SRV_Channels::auto_trim private
Definition at line 534 of file SRV_Channel.h.
Referenced by auto_trim_enabled().
channels
SRV_Channel * SRV_Channels::channels static private
Definition at line 495 of file SRV_Channel.h.
Referenced by adjust_trim(), calc_pwm(), channel_function(), constrain_pwm(), copy_radio_in_out(), copy_radio_in_out_mask(), enable_aux_servos(), find_channel(), get_channel_for(), get_output_norm(), get_output_pwm(), limit_slew_rate(), move_servo(), output_ch_all(), save_trim(), set_angle(), set_aux_channel_default(), set_default_function(), set_esc_scaling_for(), set_failsafe_limit(), set_failsafe_pwm(), set_output_limit(), set_output_min_max(), set_output_pwm(), set_output_pwm_chan(), set_output_pwm_first(), set_output_pwm_trimmed(), set_output_to_trim(), set_range(), set_rc_frequency(), set_safety_limit(), set_trim_to_min_for(), set_trim_to_pwm_for(), set_trim_to_servo_out_for(), setup_failsafe_trim_all_non_motors(), srv_channel(), SRV_Channels(), update_aux_servo_function(), upgrade_motors_servo(), and upgrade_parameters().
default_rate
AP_Int16 SRV_Channels::default_rate private
Definition at line 535 of file SRV_Channel.h.
Referenced by enable_aux_servos().
digital_mask
uint16_t SRV_Channels::digital_mask static private
Definition at line 519 of file SRV_Channel.h.
Referenced by enable_aux_servos(), and set_digital_mask().
disabled_mask
uint16_t SRV_Channels::disabled_mask static private
Definition at line 515 of file SRV_Channel.h.
Referenced by SRV_Channel::output_ch(), and set_disabled_channel_mask().
disabled_passthrough
bool SRV_Channels::disabled_passthrough static private
Definition at line 487 of file SRV_Channel.h.
Referenced by disable_passthrough(), and passthrough_disabled().
emergency_stop
bool SRV_Channels::emergency_stop static private
Definition at line 542 of file SRV_Channel.h.
Referenced by SRV_Channel::calc_pwm(), get_emergency_stop(), and set_emergency_stop().
flags
struct { ... } SRV_Channels::flags
Referenced by set_reversible_throttle(), upgrade_motors_servo(), and upgrade_parameters().
function_mask
Bitmask< SRV_Channel::k_nr_aux_servo_functions > SRV_Channels::function_mask static private
Definition at line 491 of file SRV_Channel.h.
Referenced by function_assigned(), set_aux_channel_default(), set_default_function(), and update_aux_servo_function().
functions
SRV_Channels::srv_function SRV_Channels::functions static private
Definition at line 56 of file SRV_Channels.cpp.
Referenced by calc_pwm(), get_output_channel_mask(), get_output_norm(), get_output_pwm(), get_output_scaled(), limit_slew_rate(), set_aux_channel_default(), set_output_scaled(), and update_aux_servo_function().
initialised
bool SRV_Channels::initialised static private
Definition at line 492 of file SRV_Channel.h.
Referenced by find_channel(), get_output_channel_mask(), set_aux_channel_default(), and update_aux_servo_function().
k_throttle_reversible
bool SRV_Channels::k_throttle_reversible
Definition at line 484 of file SRV_Channel.h.
obj_channels
SRV_Channel SRV_Channels::obj_channels[NUM_SERVO_CHANNELS] private
Definition at line 524 of file SRV_Channel.h.
Referenced by SRV_Channels().
reversible_mask
uint16_t SRV_Channels::reversible_mask static private
Definition at line 522 of file SRV_Channel.h.
Referenced by enable_aux_servos(), and set_reversible_mask().
robotis
AP_RobotisServo SRV_Channels::robotis private
Definition at line 507 of file SRV_Channel.h.
Referenced by SRV_Channels().
robotis_ptr
AP_RobotisServo * SRV_Channels::robotis_ptr static private
Definition at line 508 of file SRV_Channel.h.
Referenced by push(), and SRV_Channels().
sbus
AP_SBusOut SRV_Channels::sbus private
Definition at line 503 of file SRV_Channel.h.
Referenced by SRV_Channels().
sbus_ptr
AP_SBusOut * SRV_Channels::sbus_ptr static private
Definition at line 504 of file SRV_Channel.h.
Referenced by push(), and SRV_Channels().
trimmed_mask
SRV_Channel::servo_mask_t SRV_Channels::trimmed_mask private
Definition at line 489 of file SRV_Channel.h.
Referenced by adjust_trim(), and save_trim().
var_info
const AP_Param::GroupInfo SRV_Channels::var_info static
Definition at line 294 of file SRV_Channel.h.
Referenced by SRV_Channels().
volz
AP_Volz_Protocol SRV_Channels::volz private
Definition at line 499 of file SRV_Channel.h.
Referenced by SRV_Channels().
volz_ptr
AP_Volz_Protocol * SRV_Channels::volz_ptr static private
Definition at line 500 of file SRV_Channel.h.
Referenced by push(), and SRV_Channels().
The documentation for this class was generated from the following files:
libraries/SRV_Channel/SRV_Channel.h
libraries/SRV_Channel/SRV_Channel_aux.cpp
libraries/SRV_Channel/SRV_Channels.cpp