APM:Libraries: AC_PosControl Class Reference
AC_PosControl Class Reference
#include <AC_PosControl.h>
Classes
struct poscontrol_flags
struct poscontrol_limit_flags
Public Member Functions
AC_PosControl (const AP_AHRS_View &ahrs, const AP_InertialNav &inav, const AP_Motors &motors, AC_AttitudeControl &attitude_control)
Constructor.
void set_dt (float delta_sec)
set_dt - sets time delta in seconds for all controllers (i.e. 100hz = 0.01, 400hz = 0.0025)
float get_dt () const
void set_max_speed_z (float speed_down, float speed_up)
float get_max_speed_up () const
get_max_speed_up - accessor for current maximum up speed in cm/s
float get_max_speed_down () const
get_max_speed_down - accessors for current maximum down speed in cm/s. Will be a negative number
float get_vel_target_z () const
get_vel_target_z - returns current vertical speed in cm/s
void set_max_accel_z (float accel_cmss)
set_max_accel_z - set the maximum vertical acceleration in cm/s/s
float get_max_accel_z () const
get_max_accel_z - returns current maximum vertical acceleration in cm/s/s
void calc_leash_length_z ()
void set_alt_target (float alt_cm)
set_alt_target - set altitude target in cm above home
void set_alt_target_with_slew (float alt_cm, float dt)
virtual void set_alt_target_from_climb_rate (float climb_rate_cms, float dt, bool force_descend)
virtual void set_alt_target_from_climb_rate_ff (float climb_rate_cms, float dt, bool force_descend)
void add_takeoff_climb_rate (float climb_rate_cms, float dt)
void set_alt_target_to_current_alt ()
set_alt_target_to_current_alt - set altitude target to current altitude
void shift_alt_target (float z_cm)
shift altitude target (positive means move altitude up)
void relax_alt_hold_controllers (float throttle_setting)
relax_alt_hold_controllers - set all desired and targets to measured
float get_alt_target () const
get_alt_target - get desired altitude (in cm above home) from loiter or wp controller which should be fed into throttle controller
float get_alt_error () const
get_alt_error - returns altitude error in cm
float get_horizontal_error () const
void set_target_to_stopping_point_z ()
set_target_to_stopping_point_z - sets altitude target to reasonable stopping altitude in cm above home
void get_stopping_point_z (Vector3f &stopping_point) const
get_stopping_point_z - calculates stopping point based on current position, velocity, vehicle acceleration
void init_takeoff ()
init_takeoff - initialises target altitude if we are taking off
bool is_active_z () const
void update_z_controller ()
update_z_controller - fly to altitude in cm above home
float get_leash_down_z () const
float get_leash_up_z () const
float get_lean_angle_max_cd () const
get_lean_angle_max_cd - returns the maximum lean angle the autopilot may request
void init_xy_controller ()
void set_max_accel_xy (float accel_cmss)
set_max_accel_xy - set the maximum horizontal acceleration in cm/s/s
float get_max_accel_xy () const
void set_max_speed_xy (float speed_cms)
set_max_speed_xy - set the maximum horizontal speed maximum in cm/s
float get_max_speed_xy () const
void set_limit_accel_xy (void)
void calc_leash_length_xy ()
void set_leash_length_xy (float leash)
set the horizontal leash length
const Vector3f & get_pos_target () const
get_pos_target - get target as position vector (from home in cm)
void set_pos_target (const Vector3f &position)
set_pos_target in cm from home
void set_xy_target (float x, float y)
set_xy_target in cm from home
void shift_pos_xy_target (float x_cm, float y_cm)
shift position target target in x, y axis
const Vector3f & get_desired_velocity ()
get_desired_velocity - returns xy desired velocity (i.e. feed forward) in cm/s in lat and lon direction
void set_desired_velocity_z (float vel_z_cms)
set_desired_velocity_z - sets desired velocity in cm/s in z axis
void clear_desired_velocity_ff_z ()
void set_desired_accel_xy (float accel_lat_cms, float accel_lon_cms)
void set_desired_velocity_xy (float vel_lat_cms, float vel_lon_cms)
void set_desired_velocity (const Vector3f &des_vel)
void override_vehicle_velocity_xy (const Vector2f &vel_xy)
void freeze_ff_z ()
freeze_ff_z - used to stop the feed forward being calculated during a known discontinuity
bool is_active_xy () const
void update_xy_controller ()
update_xy_controller - run the horizontal position controller - should be called at 100hz or higher
void set_target_to_stopping_point_xy ()
set_target_to_stopping_point_xy - sets horizontal target to reasonable stopping position in cm from home
void get_stopping_point_xy (Vector3f &stopping_point) const
float get_distance_to_target () const
get_distance_to_target - get horizontal distance to position target in cm (used for reporting)
int32_t get_bearing_to_target () const
get_bearing_to_target - get bearing to target position in centi-degrees
void init_vel_controller_xyz ()
xyz velocity controller
void update_vel_controller_xy ()
void update_vel_controller_xyz ()
float get_roll () const
get desired roll, pitch which should be fed into stabilize controllers
float get_pitch () const
float get_leash_xy () const
AC_P & get_pos_z_p ()
get pid controllers
AC_P & get_vel_z_p ()
AC_PID & get_accel_z_pid ()
AC_P & get_pos_xy_p ()
AC_PID_2D & get_vel_xy_pid ()
const Vector3f & get_vel_target () const
accessors for reporting
const Vector3f & get_accel_target () const
void accel_to_lean_angles (float accel_x_cmss, float accel_y_cmss, float &roll_target, float &pitch_target) const
void lean_angles_to_accel (float &accel_x_cmss, float &accel_y_cmss) const
float time_since_last_xy_update () const
void write_log ()
bool pre_arm_checks (const char *param_prefix, char *failure_msg, const uint8_t failure_msg_len)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void run_z_controller ()
void desired_accel_to_vel (float nav_dt)
move velocity target using desired acceleration
void desired_vel_to_pos (float nav_dt)
desired_vel_to_pos - move position target using desired velocities
void run_xy_controller (float dt)
float calc_leash_length (float speed_cms, float accel_cms, float kP) const
calc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration and position kP gain
void init_ekf_xy_reset ()
initialise and check for ekf position resets
void check_for_ekf_xy_reset ()
check for ekf position reset and adjust loiter or brake target position
void init_ekf_z_reset ()
initialise ekf z axis reset check
void check_for_ekf_z_reset ()
check for ekf position reset and adjust loiter or brake target position
Static Protected Member Functions
static bool limit_vector_length (float &vector_x, float &vector_y, float max_length)
limit vector to a given length, returns true if vector was limited
static Vector3f sqrt_controller (const Vector3f &error, float p, float second_ord_lim)
Proportional controller with piecewise sqrt sections to constrain second derivative.
Protected Attributes
struct AC_PosControl::poscontrol_flags _flags
struct AC_PosControl::poscontrol_limit_flags _limit
const AP_AHRS_View & _ahrs
const AP_InertialNav & _inav
const AP_Motors & _motors
AC_AttitudeControl & _attitude_control
AP_Float _accel_xy_filt_hz
AP_Float _lean_angle_max
AC_P _p_pos_z
AC_P _p_vel_z
AC_PID _pid_accel_z
AC_P _p_pos_xy
AC_PID_2D _pid_vel_xy
float _dt
uint64_t _last_update_xy_us
uint64_t _last_update_z_us
float _speed_down_cms
float _speed_up_cms
float _speed_cms
float _accel_z_cms
float _accel_last_z_cms
float _accel_cms
float _leash
float _leash_down_z
float _leash_up_z
float _roll_target
float _pitch_target
Vector3f _pos_target
Vector3f _pos_error
Vector3f _vel_desired
Vector3f _vel_target
Vector3f _vel_error
Vector3f _vel_last
Vector3f _accel_desired
Vector3f _accel_target
Vector3f _accel_error
Vector2f _vehicle_horiz_vel
LowPassFilterFloat _vel_error_filter
LowPassFilterVector2f _accel_target_filter
uint32_t _ekf_xy_reset_ms
uint32_t _ekf_z_reset_ms
Detailed Description
Definition at line 43 of file AC_PosControl.h.
Constructor & Destructor Documentation
AC_PosControl()
AC_PosControl::AC_PosControl (const AP_AHRS_View & ahrs, const AP_InertialNav & inav, const AP_Motors & motors, AC_AttitudeControl & attitude_control)
Constructor.
Definition at line 188 of file AC_PosControl.cpp.
Member Function Documentation
accel_to_lean_angles()
void AC_PosControl::accel_to_lean_angles (float accel_x_cmss, float accel_y_cmss, float & roll_target, float & pitch_target) const
Definition at line 1095 of file AC_PosControl.cpp.
Referenced by AC_Loiter::init_target(), and run_xy_controller().
add_takeoff_climb_rate()
void AC_PosControl::add_takeoff_climb_rate (float climb_rate_cms, float dt)
add_takeoff_climb_rate - adjusts alt target up or down using a climb rate in cm/s should be called continuously (with dt set to be the expected time between calls) almost no checks are performed on the input
Definition at line 355 of file AC_PosControl.cpp.
calc_leash_length()
float AC_PosControl::calc_leash_length (float speed_cms, float accel_cms, float kP) const protected
calc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration and position kP gain
Definition at line 1120 of file AC_PosControl.cpp.
Referenced by calc_leash_length_xy(), and calc_leash_length_z().
calc_leash_length_xy()
void AC_PosControl::calc_leash_length_xy ()
calc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration should be called whenever the speed, acceleration or position kP is modified
private methodscalc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration should be called whenever the speed, acceleration or position kP is modified
Definition at line 947 of file AC_PosControl.cpp.
Referenced by set_max_accel_xy(), set_max_speed_xy(), set_target_to_stopping_point_xy(), update_vel_controller_xy(), update_xy_controller(), and AC_WPNav::wp_and_spline_init().
calc_leash_length_z()
void AC_PosControl::calc_leash_length_z ()
calc_leash_length - calculates the vertical leash lengths from maximum speed, acceleration called by update_z_controller if z-axis speed or accelerations are changed
Definition at line 487 of file AC_PosControl.cpp.
Referenced by set_max_accel_z(), set_max_speed_z(), set_target_to_stopping_point_z(), update_z_controller(), and AC_WPNav::wp_and_spline_init().
check_for_ekf_xy_reset()
void AC_PosControl::check_for_ekf_xy_reset () protected
check for ekf position reset and adjust loiter or brake target position
Definition at line 1159 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xy(), and update_xy_controller().
check_for_ekf_z_reset()
void AC_PosControl::check_for_ekf_z_reset () protected
check for ekf position reset and adjust loiter or brake target position
Definition at line 1178 of file AC_PosControl.cpp.
Referenced by update_z_controller().
clear_desired_velocity_ff_z()
void AC_PosControl::clear_desired_velocity_ff_z () inline
Definition at line 207 of file AC_PosControl.h.
Referenced by AC_WPNav::wp_and_spline_init().
desired_accel_to_vel()
void AC_PosControl::desired_accel_to_vel (float nav_dt) protected
move velocity target using desired acceleration
xy controller private methods
Definition at line 957 of file AC_PosControl.cpp.
desired_vel_to_pos()
void AC_PosControl::desired_vel_to_pos (float nav_dt) protected
desired_vel_to_pos - move position target using desired velocities
Definition at line 974 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xy(), and update_xy_controller().
freeze_ff_z()
void AC_PosControl::freeze_ff_z () inline
freeze_ff_z - used to stop the feed forward being calculated during a known discontinuity
Definition at line 225 of file AC_PosControl.h.
Referenced by init_takeoff(), shift_alt_target(), AC_WPNav::shift_wp_origin_to_current_pos(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
get_accel_target()
const Vector3f& AC_PosControl::get_accel_target () const inline
Definition at line 283 of file AC_PosControl.h.
Referenced by write_log(), and AP_Logger::Write_Rate().
get_accel_z_pid()
AC_PID& AC_PosControl::get_accel_z_pid () inline
Definition at line 277 of file AC_PosControl.h.
Referenced by pre_arm_checks().
get_alt_error()
float AC_PosControl::get_alt_error () const
get_alt_error - returns altitude error in cm
Definition at line 387 of file AC_PosControl.cpp.
get_alt_target()
float AC_PosControl::get_alt_target () const inline
get_alt_target - get desired altitude (in cm above home) from loiter or wp controller which should be fed into throttle controller
Definition at line 127 of file AC_PosControl.h.
Referenced by AC_Circle::update().
get_bearing_to_target()
int32_t AC_PosControl::get_bearing_to_target () const
get_bearing_to_target - get bearing to target position in centi-degrees
Definition at line 748 of file AC_PosControl.cpp.
Referenced by AC_Loiter::get_bearing_to_target(), and AC_Circle::get_bearing_to_target().
get_desired_velocity()
const Vector3f& AC_PosControl::get_desired_velocity () inline
get_desired_velocity - returns xy desired velocity (i.e. feed forward) in cm/s in lat and lon direction
Definition at line 201 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity().
get_distance_to_target()
float AC_PosControl::get_distance_to_target () const
get_distance_to_target - get horizontal distance to position target in cm (used for reporting)
get_distance_to_target - get horizontal distance to target position in cm
Definition at line 742 of file AC_PosControl.cpp.
Referenced by AC_Loiter::get_distance_to_target(), and AC_Circle::get_distance_to_target().
get_dt()
float AC_PosControl::get_dt () const inline
Definition at line 58 of file AC_PosControl.h.
Referenced by AC_WPNav::set_spline_origin_and_destination(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
get_horizontal_error()
float AC_PosControl::get_horizontal_error () const
Definition at line 936 of file AC_PosControl.cpp.
get_lean_angle_max_cd()
float AC_PosControl::get_lean_angle_max_cd () const
get_lean_angle_max_cd - returns the maximum lean angle the autopilot may request
xy position controller
Definition at line 760 of file AC_PosControl.cpp.
Referenced by AC_Loiter::get_angle_max_cd(), and run_xy_controller().
get_leash_down_z()
float AC_PosControl::get_leash_down_z () const inline
Definition at line 151 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calculate_wp_leash_length().
get_leash_up_z()
float AC_PosControl::get_leash_up_z () const inline
Definition at line 152 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calculate_wp_leash_length().
get_leash_xy()
float AC_PosControl::get_leash_xy () const inline
Definition at line 272 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calculate_wp_leash_length().
get_max_accel_xy()
float AC_PosControl::get_max_accel_xy () const inline
Definition at line 170 of file AC_PosControl.h.
Referenced by AC_Circle::calc_velocities().
get_max_accel_z()
float AC_PosControl::get_max_accel_z () const inline
get_max_accel_z - returns current maximum vertical acceleration in cm/s/s
Definition at line 83 of file AC_PosControl.h.
get_max_speed_down()
float AC_PosControl::get_max_speed_down () const inline
get_max_speed_down - accessors for current maximum down speed in cm/s. Will be a negative number
Definition at line 73 of file AC_PosControl.h.
Referenced by AC_WPNav::calculate_wp_leash_length(), and AC_WPNav::set_speed_up().
get_max_speed_up()
float AC_PosControl::get_max_speed_up () const inline
get_max_speed_up - accessor for current maximum up speed in cm/s
Definition at line 70 of file AC_PosControl.h.
Referenced by AC_WPNav::calculate_wp_leash_length(), and AC_WPNav::set_speed_down().
get_max_speed_xy()
float AC_PosControl::get_max_speed_xy () const inline
Definition at line 175 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AC_Circle::calc_velocities(), AC_WPNav::calculate_wp_leash_length(), AC_WPNav::set_spline_origin_and_destination(), and AC_WPNav::set_wp_origin_and_destination().
get_pitch()
float AC_PosControl::get_pitch () const inline
Definition at line 269 of file AC_PosControl.h.
Referenced by AC_Circle::get_pitch(), AC_Loiter::get_pitch(), and AC_WPNav::get_pitch().
get_pos_target()
const Vector3f& AC_PosControl::get_pos_target () const inline
get_pos_target - get target as position vector (from home in cm)
Definition at line 189 of file AC_PosControl.h.
Referenced by AC_Circle::init(), AC_WPNav::set_spline_destination(), AC_WPNav::set_wp_destination(), AC_WPNav::shift_wp_origin_to_current_pos(), and write_log().
get_pos_xy_p()
AC_P& AC_PosControl::get_pos_xy_p () inline
Definition at line 278 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_Loiter::calc_desired_velocity(), and pre_arm_checks().
get_pos_z_p()
AC_P& AC_PosControl::get_pos_z_p () inline
get pid controllers
Definition at line 275 of file AC_PosControl.h.
Referenced by pre_arm_checks().
get_roll()
float AC_PosControl::get_roll () const inline
get desired roll, pitch which should be fed into stabilize controllers
Definition at line 268 of file AC_PosControl.h.
Referenced by AC_Circle::get_roll(), AC_Loiter::get_roll(), and AC_WPNav::get_roll().
get_stopping_point_xy()
void AC_PosControl::get_stopping_point_xy (Vector3f & stopping_point) const
get_stopping_point_xy - calculates stopping point based on current position, velocity, vehicle acceleration distance_max allows limiting distance to stopping point results placed in stopping_position vector set_accel_xy() should be called before this method to set vehicle acceleration set_leash_length() should have been called before this method
get_stopping_point_xy - calculates stopping point based on current position, velocity, vehicle acceleration distance_max allows limiting distance to stopping point results placed in stopping_position vector set_max_accel_xy() should be called before this method to set vehicle acceleration set_leash_length() should have been called before this method
Definition at line 697 of file AC_PosControl.cpp.
Referenced by AC_Circle::get_closest_point_on_circle(), AC_Loiter::get_stopping_point_xy(), AC_WPNav::get_wp_stopping_point(), AC_WPNav::get_wp_stopping_point_xy(), AC_WPNav::set_spline_destination(), set_target_to_stopping_point_xy(), and AC_WPNav::set_wp_destination().
get_stopping_point_z()
void AC_PosControl::get_stopping_point_z (Vector3f & stopping_point) const
get_stopping_point_z - calculates stopping point based on current position, velocity, vehicle acceleration
Definition at line 402 of file AC_PosControl.cpp.
Referenced by AC_WPNav::get_wp_stopping_point(), AC_WPNav::set_spline_destination(), set_target_to_stopping_point_z(), and AC_WPNav::set_wp_destination().
get_vel_target()
const Vector3f& AC_PosControl::get_vel_target () const inline
accessors for reporting
Definition at line 282 of file AC_PosControl.h.
Referenced by AC_WPNav::set_spline_origin_and_destination(), and write_log().
get_vel_target_z()
float AC_PosControl::get_vel_target_z () const inline
get_vel_target_z - returns current vertical speed in cm/s
Definition at line 76 of file AC_PosControl.h.
get_vel_xy_pid()
AC_PID_2D& AC_PosControl::get_vel_xy_pid () inline
Definition at line 279 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity().
get_vel_z_p()
AC_P& AC_PosControl::get_vel_z_p () inline
Definition at line 276 of file AC_PosControl.h.
Referenced by pre_arm_checks().
init_ekf_xy_reset()
void AC_PosControl::init_ekf_xy_reset () protected
initialise and check for ekf position resets
initialise ekf xy position reset check
Definition at line 1152 of file AC_PosControl.cpp.
Referenced by init_vel_controller_xyz(), and init_xy_controller().
init_ekf_z_reset()
void AC_PosControl::init_ekf_z_reset () protected
initialise ekf z axis reset check
Definition at line 1171 of file AC_PosControl.cpp.
Referenced by init_takeoff(), and init_vel_controller_xyz().
init_takeoff()
void AC_PosControl::init_takeoff ()
init_takeoff - initialises target altitude if we are taking off
Definition at line 442 of file AC_PosControl.cpp.
init_vel_controller_xyz()
void AC_PosControl::init_vel_controller_xyz ()
xyz velocity controller
init_vel_controller_xyz - initialise the velocity controller - should be called once before the caller attempts to use the controller
Definition at line 858 of file AC_PosControl.cpp.
init_xy_controller()
void AC_PosControl::init_xy_controller ()
init_xy_controller - initialise the xy controller sets target roll angle, pitch angle and I terms based on vehicle current lean angles should be called once whenever significant changes to the position target are made this does not update the xy target
init_xy_controller - initialise the xy controller this should be called after setting the position target and the desired velocity and acceleration sets target roll angle, pitch angle and I terms based on vehicle current lean angles should be called once whenever significant changes to the position target are made this does not update the xy target
Definition at line 773 of file AC_PosControl.cpp.
Referenced by AC_Circle::init(), AC_Loiter::init_target(), and AC_WPNav::wp_and_spline_init().
is_active_xy()
bool AC_PosControl::is_active_xy () const
Definition at line 754 of file AC_PosControl.cpp.
Referenced by get_stopping_point_xy(), and AC_Loiter::init_target().
is_active_z()
bool AC_PosControl::is_active_z () const
Definition at line 459 of file AC_PosControl.cpp.
Referenced by get_stopping_point_z(), and AC_AutoTune::start().
lean_angles_to_accel()
void AC_PosControl::lean_angles_to_accel (float & accel_x_cmss, float & accel_y_cmss) const
Definition at line 1111 of file AC_PosControl.cpp.
Referenced by init_vel_controller_xyz(), init_xy_controller(), and write_log().
limit_vector_length()
bool AC_PosControl::limit_vector_length (float & vector_x, float & vector_y, float max_length) static protected
limit vector to a given length, returns true if vector was limited
Definition at line 1190 of file AC_PosControl.cpp.
Referenced by run_xy_controller().
override_vehicle_velocity_xy()
void AC_PosControl::override_vehicle_velocity_xy (const Vector2f & vel_xy) inline
Definition at line 222 of file AC_PosControl.h.
pre_arm_checks()
bool AC_PosControl::pre_arm_checks (const char * param_prefix, char * failure_msg, const uint8_t failure_msg_len)
Definition at line 1218 of file AC_PosControl.cpp.
relax_alt_hold_controllers()
void AC_PosControl::relax_alt_hold_controllers (float throttle_setting)
relax_alt_hold_controllers - set all desired and targets to measured
Definition at line 372 of file AC_PosControl.cpp.
Referenced by AC_PosControl_Sub::relax_alt_hold_controllers(), and AC_AutoTune::run().
run_xy_controller()
void AC_PosControl::run_xy_controller (float dt) protected
run horizontal position controller correcting position and velocity converts position (_pos_target) to target velocity (_vel_target) desired velocity (_vel_desired) is combined into final target velocity converts desired velocities in lat/lon directions to accelerations in lat/lon frame converts desired accelerations provided in lat/lon frame to roll/pitch angles
Definition at line 995 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xy(), and update_xy_controller().
run_z_controller()
void AC_PosControl::run_z_controller () protected
z controller private methods
Definition at line 500 of file AC_PosControl.cpp.
Referenced by update_z_controller().
set_alt_target()
void AC_PosControl::set_alt_target (float alt_cm) inline
set_alt_target - set altitude target in cm above home
Definition at line 90 of file AC_PosControl.h.
Referenced by init_vel_controller_xyz().
set_alt_target_from_climb_rate()
void AC_PosControl::set_alt_target_from_climb_rate (float climb_rate_cms, float dt, bool force_descend) virtual
set_alt_target_from_climb_rate - adjusts target up or down using a climb rate in cm/s should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded set force_descend to true during landing to allow target to move low enough to slow the motors
set_alt_target_from_climb_rate - adjusts target up or down using a climb rate in cm/s should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded
Reimplemented in AC_PosControl_Sub.
Definition at line 302 of file AC_PosControl.cpp.
set_alt_target_from_climb_rate_ff()
void AC_PosControl::set_alt_target_from_climb_rate_ff (float climb_rate_cms, float dt, bool force_descend) virtual
set_alt_target_from_climb_rate_ff - adjusts target up or down using a climb rate in cm/s using feed-forward should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded set force_descend to true during landing to allow target to move low enough to slow the motors
Reimplemented in AC_PosControl_Sub.
Definition at line 321 of file AC_PosControl.cpp.
Referenced by AC_AutoTune::run(), and update_vel_controller_xyz().
set_alt_target_to_current_alt()
void AC_PosControl::set_alt_target_to_current_alt () inline
set_alt_target_to_current_alt - set altitude target to current altitude
Definition at line 118 of file AC_PosControl.h.
Referenced by AC_AutoTune::start().
set_alt_target_with_slew()
void AC_PosControl::set_alt_target_with_slew (float alt_cm, float dt)
set_alt_target_with_slew - adjusts target towards a final altitude target should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded
Definition at line 274 of file AC_PosControl.cpp.
set_desired_accel_xy()
void AC_PosControl::set_desired_accel_xy (float accel_lat_cms, float accel_lon_cms) inline
Definition at line 210 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), AC_Circle::init(), AC_Loiter::init_target(), init_vel_controller_xyz(), and AC_WPNav::wp_and_spline_init().
set_desired_velocity()
void AC_PosControl::set_desired_velocity (const Vector3f & des_vel) inline
set_desired_velocity - sets desired velocity in cm/s in all 3 axis when update_vel_controller_xyz is next called the position target is moved based on the desired velocity
Definition at line 219 of file AC_PosControl.h.
Referenced by init_vel_controller_xyz().
set_desired_velocity_xy()
void AC_PosControl::set_desired_velocity_xy (float vel_lat_cms, float vel_lon_cms) inline
set_desired_velocity_xy - sets desired velocity in cm/s in lat and lon directions when update_xy_controller is next called the position target is moved based on the desired velocity and the desired velocities are fed forward into the rate_to_accel step
Definition at line 215 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), AC_Circle::init(), AC_Loiter::init_target(), and AC_WPNav::wp_and_spline_init().
set_desired_velocity_z()
void AC_PosControl::set_desired_velocity_z (float vel_z_cms) inline
set_desired_velocity_z - sets desired velocity in cm/s in z axis
Definition at line 204 of file AC_PosControl.h.
Referenced by AC_AutoTune::start().
set_dt()
void AC_PosControl::set_dt (float delta_sec)
set_dt - sets time delta in seconds for all controllers (i.e. 100hz = 0.01, 400hz = 0.0025)
initialisation functionsset_dt - sets time delta in seconds for all controllers (i.e. 100hz = 0.01, 400hz = 0.0025) updates z axis accel controller's D term filter
z-axis position controller
Definition at line 233 of file AC_PosControl.cpp.
set_leash_length_xy()
void AC_PosControl::set_leash_length_xy (float leash) inline
set the horizontal leash length
Definition at line 186 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), and AC_Loiter::init_target().
set_limit_accel_xy()
void AC_PosControl::set_limit_accel_xy (void) inline
set_limit_accel_xy - mark that accel has been limited this prevents integrator buildup
Definition at line 179 of file AC_PosControl.h.
Referenced by AC_Loiter::soften_for_landing().
set_max_accel_xy()
void AC_PosControl::set_max_accel_xy (float accel_cmss)
set_max_accel_xy - set the maximum horizontal acceleration in cm/s/s
set_max_accel_xy - set the maximum horizontal acceleration in cm/s/s leash length will be recalculated
lateral position controller
Definition at line 636 of file AC_PosControl.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), AC_Loiter::init_target(), AC_Loiter::update(), AC_WPNav::update_wpnav(), and AC_WPNav::wp_and_spline_init().
set_max_accel_z()
void AC_PosControl::set_max_accel_z (float accel_cmss)
set_max_accel_z - set the maximum vertical acceleration in cm/s/s
set_max_accel_z - set the maximum vertical acceleration in cm/s/s leash length will be recalculated
Definition at line 261 of file AC_PosControl.cpp.
Referenced by AC_WPNav::update_wpnav(), and AC_WPNav::wp_and_spline_init().
set_max_speed_xy()
void AC_PosControl::set_max_speed_xy (float speed_cms)
set_max_speed_xy - set the maximum horizontal speed maximum in cm/s
set_max_speed_xy - set the maximum horizontal speed maximum in cm/s leash length will be recalculated
Definition at line 646 of file AC_PosControl.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), AC_Loiter::init_target(), AC_WPNav::set_speed_xy(), AC_Loiter::update(), and AC_WPNav::wp_and_spline_init().
set_max_speed_z()
void AC_PosControl::set_max_speed_z (float speed_down, float speed_up)
z position controllerset_max_speed_z - sets maximum climb and descent rates speed_down can be positive or negative but will always be interpreted as a descent speed leash length will be recalculated
set_max_speed_z - set the maximum climb and descent rates To-Do: call this in the main code as part of flight mode initialisation
Definition at line 247 of file AC_PosControl.cpp.
Referenced by AC_WPNav::set_speed_down(), AC_WPNav::set_speed_up(), and AC_WPNav::wp_and_spline_init().
set_pos_target()
void AC_PosControl::set_pos_target (const Vector3f & position)
set_pos_target in cm from home
Definition at line 656 of file AC_PosControl.cpp.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AC_WPNav::set_spline_origin_and_destination(), AC_WPNav::set_wp_origin_and_destination(), and AC_WPNav::shift_wp_origin_to_current_pos().
set_target_to_stopping_point_xy()
void AC_PosControl::set_target_to_stopping_point_xy ()
set_target_to_stopping_point_xy - sets horizontal target to reasonable stopping position in cm from home
Definition at line 684 of file AC_PosControl.cpp.
Referenced by AC_Circle::init().
set_target_to_stopping_point_z()
void AC_PosControl::set_target_to_stopping_point_z ()
set_target_to_stopping_point_z - sets altitude target to reasonable stopping altitude in cm above home
set_target_to_stopping_point_z - returns reasonable stopping altitude in cm above home
Definition at line 393 of file AC_PosControl.cpp.
Referenced by AC_Circle::init().
set_xy_target()
void AC_PosControl::set_xy_target (float x, float y)
set_xy_target in cm from home
Definition at line 669 of file AC_PosControl.cpp.
Referenced by AC_Loiter::init_target(), init_vel_controller_xyz(), AC_Loiter::soften_for_landing(), and AC_Circle::update().
shift_alt_target()
void AC_PosControl::shift_alt_target (float z_cm)
shift altitude target (positive means move altitude up)
Definition at line 361 of file AC_PosControl.cpp.
Referenced by check_for_ekf_z_reset().
shift_pos_xy_target()
void AC_PosControl::shift_pos_xy_target (float x_cm, float y_cm)
shift position target target in x, y axis
Definition at line 676 of file AC_PosControl.cpp.
Referenced by check_for_ekf_xy_reset().
sqrt_controller()
Vector3f AC_PosControl::sqrt_controller (const Vector3f & error, float p, float second_ord_lim) static protected
Proportional controller with piecewise sqrt sections to constrain second derivative.
Definition at line 1202 of file AC_PosControl.cpp.
Referenced by run_xy_controller().
time_since_last_xy_update()
float AC_PosControl::time_since_last_xy_update () const
Definition at line 821 of file AC_PosControl.cpp.
Referenced by AC_Circle::update(), and AC_Loiter::update().
update_vel_controller_xy()
void AC_PosControl::update_vel_controller_xy ()
update_velocity_controller_xy - run the XY velocity controller - should be called at 100hz or higher velocity targets should we set using set_desired_velocity_xy() method callers should use get_roll() and get_pitch() methods and sent to the attitude controller throttle targets will be sent directly to the motors
update_velocity_controller_xy - run the velocity controller - should be called at 100hz or higher velocity targets should we set using set_desired_velocity_xy() method callers should use get_roll() and get_pitch() methods and sent to the attitude controller throttle targets will be sent directly to the motors
Definition at line 893 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xyz().
update_vel_controller_xyz()
void AC_PosControl::update_vel_controller_xyz ()
update_velocity_controller_xyz - run the velocity controller - should be called at 100hz or higher velocity targets should we set using set_desired_velocity_xyz() method callers should use get_roll() and get_pitch() methods and sent to the attitude controller throttle targets will be sent directly to the motors
Definition at line 925 of file AC_PosControl.cpp.
update_xy_controller()
void AC_PosControl::update_xy_controller ()
update_xy_controller - run the horizontal position controller - should be called at 100hz or higher
update_xy_controller - run the horizontal position controller - should be called at 100hz or higher when use_desired_velocity is true the desired velocity (i.e. feed forward) is incorporated at the pos_to_rate step
Definition at line 794 of file AC_PosControl.cpp.
Referenced by AC_Circle::update(), AC_Loiter::update(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
update_z_controller()
void AC_PosControl::update_z_controller ()
update_z_controller - fly to altitude in cm above home
Definition at line 465 of file AC_PosControl.cpp.
Referenced by AC_AutoTune::run(), and update_vel_controller_xyz().
write_log()
void AC_PosControl::write_log ()
Definition at line 827 of file AC_PosControl.cpp.
Member Data Documentation
_accel_cms
float AC_PosControl::_accel_cms protected
Definition at line 394 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_max_accel_xy(), get_stopping_point_xy(), run_xy_controller(), and set_max_accel_xy().
_accel_desired
Vector3f AC_PosControl::_accel_desired protected
Definition at line 410 of file AC_PosControl.h.
Referenced by desired_accel_to_vel(), init_xy_controller(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), run_z_controller(), and set_desired_accel_xy().
_accel_error
Vector3f AC_PosControl::_accel_error protected
Definition at line 412 of file AC_PosControl.h.
Referenced by run_z_controller().
_accel_last_z_cms
float AC_PosControl::_accel_last_z_cms protected
Definition at line 393 of file AC_PosControl.h.
Referenced by AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), and set_alt_target_from_climb_rate_ff().
_accel_target
Vector3f AC_PosControl::_accel_target protected
Definition at line 411 of file AC_PosControl.h.
Referenced by get_accel_target(), init_vel_controller_xyz(), init_xy_controller(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), and run_z_controller().
_accel_target_filter
LowPassFilterVector2f AC_PosControl::_accel_target_filter protected
Definition at line 416 of file AC_PosControl.h.
Referenced by run_xy_controller().
_accel_xy_filt_hz
AP_Float AC_PosControl::_accel_xy_filt_hz protected
Definition at line 377 of file AC_PosControl.h.
Referenced by run_xy_controller().
_accel_z_cms
float AC_PosControl::_accel_z_cms protected
Definition at line 392 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_max_accel_z(), get_stopping_point_z(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), and set_max_accel_z().
_ahrs
const AP_AHRS_View& AC_PosControl::_ahrs protected
Definition at line 371 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), check_for_ekf_xy_reset(), check_for_ekf_z_reset(), init_ekf_xy_reset(), init_ekf_z_reset(), init_vel_controller_xyz(), init_xy_controller(), lean_angles_to_accel(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), and run_z_controller().
_attitude_control
AC_AttitudeControl& AC_PosControl::_attitude_control protected
Definition at line 374 of file AC_PosControl.h.
Referenced by get_lean_angle_max_cd(), run_xy_controller(), and run_z_controller().
_dt
float AC_PosControl::_dt protected
Definition at line 386 of file AC_PosControl.h.
Referenced by get_dt(), run_z_controller(), set_dt(), and update_vel_controller_xyz().
_ekf_xy_reset_ms
uint32_t AC_PosControl::_ekf_xy_reset_ms protected
Definition at line 419 of file AC_PosControl.h.
Referenced by check_for_ekf_xy_reset(), and init_ekf_xy_reset().
_ekf_z_reset_ms
uint32_t AC_PosControl::_ekf_z_reset_ms protected
Definition at line 420 of file AC_PosControl.h.
Referenced by check_for_ekf_z_reset(), and init_ekf_z_reset().
_flags
struct AC_PosControl::poscontrol_flags AC_PosControl::_flags protected
Referenced by AC_PosControl(), calc_leash_length_xy(), calc_leash_length_z(), clear_desired_velocity_ff_z(), desired_accel_to_vel(), desired_vel_to_pos(), freeze_ff_z(), get_stopping_point_z(), init_vel_controller_xyz(), init_xy_controller(), override_vehicle_velocity_xy(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), set_leash_length_xy(), set_max_accel_xy(), set_max_accel_z(), set_max_speed_xy(), set_max_speed_z(), set_pos_target(), and update_z_controller().
_inav
const AP_InertialNav& AC_PosControl::_inav protected
Definition at line 372 of file AC_PosControl.h.
Referenced by get_alt_error(), get_bearing_to_target(), get_stopping_point_xy(), get_stopping_point_z(), init_takeoff(), init_vel_controller_xyz(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), run_z_controller(), set_alt_target_to_current_alt(), set_alt_target_with_slew(), and write_log().
_last_update_xy_us
uint64_t AC_PosControl::_last_update_xy_us protected
Definition at line 387 of file AC_PosControl.h.
Referenced by is_active_xy(), time_since_last_xy_update(), update_vel_controller_xy(), and update_xy_controller().
_last_update_z_us
uint64_t AC_PosControl::_last_update_z_us protected
Definition at line 388 of file AC_PosControl.h.
Referenced by is_active_z(), and update_z_controller().
_lean_angle_max
AP_Float AC_PosControl::_lean_angle_max protected
Definition at line 378 of file AC_PosControl.h.
Referenced by get_lean_angle_max_cd().
_leash
float AC_PosControl::_leash protected
Definition at line 395 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_leash_xy(), get_stopping_point_xy(), run_xy_controller(), and set_leash_length_xy().
_leash_down_z
float AC_PosControl::_leash_down_z protected
Definition at line 396 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_leash_down_z(), run_z_controller(), and set_alt_target_with_slew().
_leash_up_z
float AC_PosControl::_leash_up_z protected
Definition at line 397 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_leash_up_z(), run_z_controller(), and set_alt_target_with_slew().
_limit
struct AC_PosControl::poscontrol_limit_flags AC_PosControl::_limit protected
Referenced by AC_PosControl(), run_xy_controller(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), and set_limit_accel_xy().
_motors
const AP_Motors& AC_PosControl::_motors protected
Definition at line 373 of file AC_PosControl.h.
Referenced by init_takeoff(), relax_alt_hold_controllers(), run_xy_controller(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), and set_alt_target_with_slew().
_p_pos_xy
AC_P AC_PosControl::_p_pos_xy protected
Definition at line 382 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_pos_xy_p(), get_stopping_point_xy(), and run_xy_controller().
_p_pos_z
AC_P AC_PosControl::_p_pos_z protected
Definition at line 379 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_pos_z_p(), get_stopping_point_z(), and run_z_controller().
_p_vel_z
AC_P AC_PosControl::_p_vel_z protected
Definition at line 380 of file AC_PosControl.h.
Referenced by get_vel_z_p(), and run_z_controller().
_pid_accel_z
AC_PID AC_PosControl::_pid_accel_z protected
Definition at line 381 of file AC_PosControl.h.
Referenced by get_accel_z_pid(), init_takeoff(), relax_alt_hold_controllers(), run_z_controller(), and set_dt().
_pid_vel_xy
AC_PID_2D AC_PosControl::_pid_vel_xy protected
Definition at line 383 of file AC_PosControl.h.
Referenced by get_vel_xy_pid(), init_vel_controller_xyz(), init_xy_controller(), run_xy_controller(), and set_dt().
_pitch_target
float AC_PosControl::_pitch_target protected
Definition at line 401 of file AC_PosControl.h.
Referenced by get_pitch(), init_vel_controller_xyz(), init_xy_controller(), and run_xy_controller().
_pos_error
Vector3f AC_PosControl::_pos_error protected
Definition at line 405 of file AC_PosControl.h.
Referenced by get_distance_to_target(), get_horizontal_error(), run_xy_controller(), and run_z_controller().
_pos_target
Vector3f AC_PosControl::_pos_target protected
Definition at line 404 of file AC_PosControl.h.
Referenced by add_takeoff_climb_rate(), desired_vel_to_pos(), get_alt_error(), get_alt_target(), get_bearing_to_target(), get_pos_target(), init_takeoff(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), run_z_controller(), set_alt_target(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_to_current_alt(), set_alt_target_with_slew(), set_pos_target(), set_target_to_stopping_point_xy(), set_target_to_stopping_point_z(), set_xy_target(), shift_alt_target(), and shift_pos_xy_target().
_roll_target
float AC_PosControl::_roll_target protected
Definition at line 400 of file AC_PosControl.h.
Referenced by get_roll(), init_vel_controller_xyz(), init_xy_controller(), and run_xy_controller().
_speed_cms
float AC_PosControl::_speed_cms protected
Definition at line 391 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_max_speed_xy(), and set_max_speed_xy().
_speed_down_cms
float AC_PosControl::_speed_down_cms protected
Definition at line 389 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_max_speed_down(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), and set_max_speed_z().
_speed_up_cms
float AC_PosControl::_speed_up_cms protected
Definition at line 390 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_max_speed_up(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), and set_max_speed_z().
_vehicle_horiz_vel
Vector2f AC_PosControl::_vehicle_horiz_vel protected
Definition at line 413 of file AC_PosControl.h.
Referenced by override_vehicle_velocity_xy(), and run_xy_controller().
_vel_desired
Vector3f AC_PosControl::_vel_desired protected
Definition at line 406 of file AC_PosControl.h.
Referenced by desired_accel_to_vel(), desired_vel_to_pos(), get_desired_velocity(), get_stopping_point_z(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), run_z_controller(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), set_desired_velocity(), set_desired_velocity_xy(), set_desired_velocity_z(), set_pos_target(), and update_vel_controller_xyz().
_vel_error
Vector3f AC_PosControl::_vel_error protected
Definition at line 408 of file AC_PosControl.h.
Referenced by get_stopping_point_xy(), get_stopping_point_z(), run_xy_controller(), and run_z_controller().
_vel_error_filter
LowPassFilterFloat AC_PosControl::_vel_error_filter protected
Definition at line 414 of file AC_PosControl.h.
Referenced by run_z_controller(), and set_dt().
_vel_last
Vector3f AC_PosControl::_vel_last protected
Definition at line 409 of file AC_PosControl.h.
Referenced by AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), and run_z_controller().
_vel_target
Vector3f AC_PosControl::_vel_target protected
Definition at line 407 of file AC_PosControl.h.
Referenced by get_vel_target(), get_vel_target_z(), AC_PosControl_Sub::relax_alt_hold_controllers(), relax_alt_hold_controllers(), run_xy_controller(), and run_z_controller().
var_info
const AP_Param::GroupInfo AC_PosControl::var_info static
Definition at line 301 of file AC_PosControl.h.
Referenced by AC_PosControl().
The documentation for this class was generated from the following files:
libraries/AC_AttitudeControl/AC_PosControl.h
libraries/AC_AttitudeControl/AC_PosControl.cpp