APM:Libraries: AP_HAL::Flash Class Reference
AP_HAL::Flash Class Reference abstract
#include <Flash.h>
Public Member Functions
virtual uint32_t getpageaddr (uint32_t page)=0
virtual uint32_t getpagesize (uint32_t page)=0
virtual uint32_t getnumpages (void)=0
virtual bool erasepage (uint32_t page)=0
virtual bool write (uint32_t addr, const void *buf, uint32_t count)=0
virtual void keep_unlocked (bool set)=0
virtual bool ispageerased (uint32_t page)=0
Detailed Description
Definition at line 9 of file Flash.h.
Member Function Documentation
erasepage()
virtual bool AP_HAL::Flash::erasepage (uint32_t page) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
Referenced by ChibiOS::Storage::_flash_erase_sector(), and ChibiOS::Util::flash_bootloader().
getnumpages()
virtual uint32_t AP_HAL::Flash::getnumpages (void) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
getpageaddr()
virtual uint32_t AP_HAL::Flash::getpageaddr (uint32_t page) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
Referenced by ChibiOS::Storage::_flash_read_data(), ChibiOS::Storage::_flash_write_data(), and ChibiOS::Util::flash_bootloader().
getpagesize()
virtual uint32_t AP_HAL::Flash::getpagesize (uint32_t page) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
ispageerased()
virtual bool AP_HAL::Flash::ispageerased (uint32_t page) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
keep_unlocked()
virtual void AP_HAL::Flash::keep_unlocked (bool set) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
write()
virtual bool AP_HAL::Flash::write (uint32_t addr, const void * buf, uint32_t count) pure virtual
Implemented in ChibiOS::Flash, and Empty::Flash.
Referenced by ChibiOS::Storage::_flash_write_data(), and ChibiOS::Util::flash_bootloader().
The documentation for this class was generated from the following file:
libraries/AP_HAL/Flash.h