APM:Libraries: ChibiOS::I2CBus Class Reference
ChibiOS::I2CBus Class Reference
#include <I2CDevice.h>
Public Member Functions
void dma_allocate (Shared_DMA *)
void dma_deallocate (Shared_DMA *)
void dma_init (void)
Public Member Functions inherited from ChibiOS::DeviceBus
DeviceBus (uint8_t _thread_priority=APM_I2C_PRIORITY)
AP_HAL::Device::PeriodicHandle register_periodic_callback (uint32_t period_usec, AP_HAL::Device::PeriodicCb, AP_HAL::Device *hal_device)
bool adjust_timer (AP_HAL::Device::PeriodicHandle h, uint32_t period_usec)
void bouncebuffer_setup (const uint8_t *&buf_tx, uint16_t tx_len, uint8_t *&buf_rx, uint16_t rx_len)
void bouncebuffer_finish (const uint8_t *buf_tx, uint8_t *buf_rx, uint16_t rx_len)
Static Public Member Functions
static void clear_all (void)
static void clear_bus (uint8_t busidx)
static uint8_t read_sda (uint8_t busidx)
Static Public Member Functions inherited from ChibiOS::DeviceBus
static void bus_thread (void *arg)
Public Attributes
I2CConfig i2ccfg
uint8_t busnum
uint32_t busclock
mutex_t dma_lock
Public Attributes inherited from ChibiOS::DeviceBus
struct DeviceBus * next
Semaphore semaphore
Shared_DMA * dma_handle
Detailed Description
Definition at line 37 of file I2CDevice.h.
Member Function Documentation
clear_all()
void I2CBus::clear_all (void) static
Definition at line 73 of file I2CDevice.cpp.
Referenced by main_loop().
clear_bus()
void I2CBus::clear_bus (uint8_t busidx) static
Definition at line 85 of file I2CDevice.cpp.
Referenced by ChibiOS::I2CDevice::_transfer(), and clear_all().
dma_allocate()
void I2CBus::dma_allocate (Shared_DMA * ctx)
Definition at line 181 of file I2CDevice.cpp.
Referenced by dma_init().
dma_deallocate()
void I2CBus::dma_deallocate (Shared_DMA *)
Definition at line 188 of file I2CDevice.cpp.
Referenced by dma_init().
dma_init()
void I2CBus::dma_init (void)
Definition at line 64 of file I2CDevice.cpp.
Referenced by ChibiOS::I2CDeviceManager::I2CDeviceManager().
read_sda()
uint8_t I2CBus::read_sda (uint8_t busidx) static
Definition at line 100 of file I2CDevice.cpp.
Referenced by ChibiOS::I2CDevice::_transfer().
Member Data Documentation
busclock
uint32_t ChibiOS::I2CBus::busclock
Definition at line 41 of file I2CDevice.h.
Referenced by ChibiOS::I2CDevice::_transfer(), ChibiOS::I2CDevice::I2CDevice(), and ChibiOS::I2CDeviceManager::I2CDeviceManager().
busnum
uint8_t ChibiOS::I2CBus::busnum
Definition at line 40 of file I2CDevice.h.
Referenced by ChibiOS::I2CDevice::_transfer(), dma_init(), ChibiOS::I2CDeviceManager::I2CDeviceManager(), and ChibiOS::I2CDevice::~I2CDevice().
dma_lock
mutex_t ChibiOS::I2CBus::dma_lock
Definition at line 47 of file I2CDevice.h.
Referenced by dma_init().
i2ccfg
I2CConfig ChibiOS::I2CBus::i2ccfg
Definition at line 39 of file I2CDevice.h.
Referenced by ChibiOS::I2CDevice::_transfer(), ChibiOS::I2CDevice::I2CDevice(), ChibiOS::I2CDeviceManager::I2CDeviceManager(), and ChibiOS::I2CDevice::transfer().
The documentation for this class was generated from the following files:
libraries/AP_HAL_ChibiOS/I2CDevice.h
libraries/AP_HAL_ChibiOS/I2CDevice.cpp