APM:Libraries: TSYS01 Class Reference
TSYS01 Class Reference
#include <TSYS01.h>
Public Member Functions
bool init (void)
float temperature (void)
bool healthy (void)
Public Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
Private Member Functions
bool _reset (void)
bool _read_prom (void)
bool _convert (void)
uint32_t _read_adc (void)
uint16_t _read_prom_word (uint8_t word)
void _timer (void)
void _calculate (uint32_t adc)
Private Attributes
float _temperature = 42.42
bool _healthy
uint16_t _k [5]
Detailed Description
Definition at line 13 of file TSYS01.h.
Member Function Documentation
_calculate()
void TSYS01::_calculate (uint32_t adc) private
Definition at line 125 of file TSYS01.cpp.
Referenced by _timer().
_convert()
bool TSYS01::_convert (void) private
Definition at line 95 of file TSYS01.cpp.
Referenced by _timer(), and init().
_read_adc()
uint32_t TSYS01::_read_adc (void) private
Definition at line 100 of file TSYS01.cpp.
Referenced by _timer().
_read_prom()
bool TSYS01::_read_prom (void) private
Definition at line 73 of file TSYS01.cpp.
Referenced by init().
_read_prom_word()
uint16_t TSYS01::_read_prom_word (uint8_t word) private
Definition at line 85 of file TSYS01.cpp.
Referenced by _read_prom().
_reset()
bool TSYS01::_reset (void) private
Definition at line 58 of file TSYS01.cpp.
Referenced by init().
_timer()
void TSYS01::_timer (void) private
Definition at line 109 of file TSYS01.cpp.
Referenced by init().
healthy()
bool TSYS01::healthy (void) inline
Definition at line 18 of file TSYS01.h.
init()
bool TSYS01::init (void)
Definition at line 16 of file TSYS01.cpp.
temperature()
float TSYS01::temperature (void) inline
Definition at line 17 of file TSYS01.h.
Member Data Documentation
_dev
AP_HAL::OwnPtr<AP_HAL::Device> TSYS01::_dev
Definition at line 25 of file TSYS01.h.
Referenced by _convert(), _read_adc(), _read_prom_word(), _reset(), and init().
_healthy
bool TSYS01::_healthy private
Definition at line 33 of file TSYS01.h.
Referenced by _timer(), and healthy().
_k
uint16_t TSYS01::_k[5] private
Definition at line 34 of file TSYS01.h.
Referenced by _calculate(), and _read_prom().
_temperature
float TSYS01::_temperature = 42.42 private
Definition at line 29 of file TSYS01.h.
Referenced by _calculate(), _timer(), and temperature().
The documentation for this class was generated from the following files:
libraries/AP_TemperatureSensor/TSYS01.h
libraries/AP_TemperatureSensor/TSYS01.cpp