APM:Libraries: AP_AccelCal_Client Class Reference
AP_AccelCal_Client Class Reference abstract
#include <AP_AccelCal.h>
Private Member Functions
virtual bool _acal_get_saving ()
virtual bool _acal_get_ready_to_sample ()
virtual bool _acal_get_fail ()
virtual AccelCalibrator * _acal_get_calibrator (uint8_t instance)=0
virtual void _acal_save_calibrations ()=0
virtual void _acal_event_success ()
virtual void _acal_event_cancellation ()
virtual void _acal_event_failure ()
Friends
class AP_AccelCal
Detailed Description
Definition at line 80 of file AP_AccelCal.h.
Member Function Documentation
_acal_event_cancellation()
virtual void AP_AccelCal_Client::_acal_event_cancellation () inline private virtual
Definition at line 92 of file AP_AccelCal.h.
Referenced by AP_AccelCal::cancel().
_acal_event_failure()
virtual void AP_AccelCal_Client::_acal_event_failure () inline private virtual
Reimplemented in AP_InertialSensor.
Definition at line 93 of file AP_AccelCal.h.
Referenced by AP_AccelCal::fail().
_acal_event_success()
virtual void AP_AccelCal_Client::_acal_event_success () inline private virtual
Definition at line 91 of file AP_AccelCal.h.
Referenced by AP_AccelCal::success().
_acal_get_calibrator()
virtual AccelCalibrator* AP_AccelCal_Client::_acal_get_calibrator (uint8_t instance) private pure virtual
Implemented in AP_InertialSensor.
Referenced by AP_AccelCal::client_active(), and AP_AccelCal::get_calibrator().
_acal_get_fail()
virtual bool AP_AccelCal_Client::_acal_get_fail () inline private virtual
Definition at line 86 of file AP_AccelCal.h.
_acal_get_ready_to_sample()
virtual bool AP_AccelCal_Client::_acal_get_ready_to_sample () inline private virtual
Definition at line 85 of file AP_AccelCal.h.
_acal_get_saving()
virtual bool AP_AccelCal_Client::_acal_get_saving () inline private virtual
Definition at line 84 of file AP_AccelCal.h.
_acal_save_calibrations()
virtual void AP_AccelCal_Client::_acal_save_calibrations () private pure virtual
Implemented in AP_InertialSensor.
Referenced by AP_AccelCal::update().
Friends And Related Function Documentation
AP_AccelCal
friend class AP_AccelCal friend
Definition at line 81 of file AP_AccelCal.h.
Referenced by AP_InertialSensor::acal_init().
The documentation for this class was generated from the following file:
libraries/AP_AccelCal/AP_AccelCal.h