APM:Libraries: GCS Class Reference
GCS Class Reference abstract
global GCS object
#include <GCS.h>
Classes
struct statustext_t
Public Member Functions
GCS ()
virtual uint32_t custom_mode () const =0
virtual MAV_TYPE frame_type () const =0
virtual const char * frame_string () const
void send_to_active_channels (uint32_t msgid, const char *pkt)
void send_text (MAV_SEVERITY severity, const char *fmt,...)
void send_textv (MAV_SEVERITY severity, const char *fmt, va_list arg_list)
virtual void send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char *text)
void service_statustext (void)
virtual GCS_MAVLINK & chan (const uint8_t ofs)=0
virtual const GCS_MAVLINK & chan (const uint8_t ofs) const =0
virtual uint8_t num_gcs () const =0
void send_message (enum ap_message id)
void send_mission_item_reached_message (uint16_t mission_index)
void send_named_float (const char *name, float value) const
void send_parameter_value (const char *param_name, ap_var_type param_type, float param_value)
MissionItemProtocol * get_prot_for_mission_type (const MAV_MISSION_TYPE mission_type) const
void try_send_queued_message_for_type (MAV_MISSION_TYPE type)
void update_send ()
void update_receive ()
virtual void setup_uarts ()
virtual uint16_t min_loop_time_remaining_for_message_send_us () const
bool out_of_time () const
bool install_alternative_protocol (mavlink_channel_t chan, GCS_MAVLINK::protocol_handler_fn_t handler)
int16_t get_hud_throttle (void) const
void update_passthru ()
void get_sensor_status_flags (uint32_t &present, uint32_t &enabled, uint32_t &health)
virtual bool vehicle_initialised () const
virtual bool simple_input_active () const
virtual bool supersimple_input_active () const
Static Public Member Functions
static class GCS * get_singleton ()
Public Attributes
AP_Frsky_Telem * frsky
AP_DEVO_Telem devo_telemetry
bool enabled
bool timer_installed
AP_HAL::UARTDriver * port1
AP_HAL::UARTDriver * port2
uint32_t start_ms
uint32_t last_ms
uint32_t last_port1_data_ms
uint8_t timeout_s
HAL_Semaphore sem
Static Public Attributes
static MissionItemProtocol_Waypoints * _missionitemprotocol_waypoints
static MissionItemProtocol_Rally * _missionitemprotocol_rally
Protected Member Functions
void update_sensor_status_flags ()
virtual void update_vehicle_sensor_status_flags ()
Protected Attributes
uint32_t control_sensors_present
uint32_t control_sensors_enabled
uint32_t control_sensors_health
Private Member Functions
void passthru_timer ()
Private Attributes
HAL_Semaphore _statustext_sem
ObjectArray< statustext_t > _statustext_queue {_status_capacity}
bool initialised_missionitemprotocol_objects
struct {
bool enabled
bool timer_installed
AP_HAL::UARTDriver * port1
AP_HAL::UARTDriver * port2
uint32_t start_ms
uint32_t last_ms
uint32_t last_port1_data_ms
uint8_t timeout_s
HAL_Semaphore sem
} _passthru
Static Private Attributes
static GCS * _singleton = nullptr
static const uint8_t _status_capacity = 5
Detailed Description
global GCS object
Definition at line 918 of file GCS.h.
Constructor & Destructor Documentation
GCS()
GCS::GCS () inline
Definition at line 923 of file GCS.h.
Member Function Documentation
chan() [1/2]
virtual GCS_MAVLINK& GCS::chan (const uint8_t ofs) pure virtual
Implemented in GCS_Dummy.
Referenced by get_hud_throttle(), install_alternative_protocol(), send_message(), send_mission_item_reached_message(), send_to_active_channels(), setup(), setup_uarts(), update_receive(), and update_send().
chan() [2/2]
virtual const GCS_MAVLINK& GCS::chan (const uint8_t ofs) const pure virtual
Implemented in GCS_Dummy.
custom_mode()
virtual uint32_t GCS::custom_mode () const pure virtual
Implemented in GCS_Dummy.
Referenced by AP_Frsky_Telem::calc_ap_status(), and AP_DEVO_Telem::send_frames().
frame_string()
virtual const char* GCS::frame_string () const inline virtual
Definition at line 941 of file GCS.h.
Referenced by AP_Frsky_Telem::init().
frame_type()
virtual MAV_TYPE GCS::frame_type () const pure virtual
Implemented in GCS_Dummy.
Referenced by AP_Frsky_Telem::calc_param().
get_hud_throttle()
int16_t GCS::get_hud_throttle (void) const inline
Definition at line 988 of file GCS.h.
get_prot_for_mission_type()
MissionItemProtocol * GCS::get_prot_for_mission_type (const MAV_MISSION_TYPE mission_type) const
Definition at line 500 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_clear_all(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_request(), GCS_MAVLINK::handle_mission_request_int(), GCS_MAVLINK::handle_mission_request_list(), GCS_MAVLINK::handle_mission_write_partial_list(), GCS_MAVLINK::requesting_mission_items(), and try_send_queued_message_for_type().
get_sensor_status_flags()
void GCS::get_sensor_status_flags (uint32_t & present, uint32_t & enabled, uint32_t & health)
Definition at line 11 of file GCS.cpp.
Referenced by GCS_MAVLINK::send_sys_status(), and AP_Frsky_Telem::sensor_status_flags().
get_singleton()
static class GCS* GCS::get_singleton (void) inline static
Definition at line 935 of file GCS.h.
Referenced by gcs(), and GCS_send_text().
install_alternative_protocol()
bool GCS::install_alternative_protocol (mavlink_channel_t chan, GCS_MAVLINK::protocol_handler_fn_t handler)
Definition at line 87 of file GCS.cpp.
min_loop_time_remaining_for_message_send_us()
virtual uint16_t GCS::min_loop_time_remaining_for_message_send_us () const inline virtual
Definition at line 973 of file GCS.h.
Referenced by out_of_time().
num_gcs()
virtual uint8_t GCS::num_gcs () const pure virtual
Implemented in GCS_Dummy.
Referenced by get_hud_throttle(), install_alternative_protocol(), send_message(), send_mission_item_reached_message(), send_to_active_channels(), update_receive(), and update_send().
out_of_time()
bool GCS::out_of_time () const
Definition at line 185 of file GCS.cpp.
passthru_timer()
void GCS::passthru_timer (void) private
Definition at line 4896 of file GCS_Common.cpp.
Referenced by update_passthru().
send_message()
void GCS::send_message (enum ap_message id)
Definition at line 2234 of file GCS_Common.cpp.
Referenced by AP_Camera::log_picture(), AP_AHRS_DCM::set_home(), and AP_Camera::update_trigger().
send_mission_item_reached_message()
void GCS::send_mission_item_reached_message (uint16_t mission_index)
Definition at line 2283 of file GCS_Common.cpp.
send_named_float()
void GCS::send_named_float (const char * name, float value) const
Definition at line 70 of file GCS.cpp.
Referenced by AP_Airspeed::update().
send_parameter_value()
void GCS::send_parameter_value (const char * param_name, ap_var_type param_type, float param_value)
Definition at line 305 of file GCS_Param.cpp.
Referenced by AP_Param::save_sync(), and AP_Param::send_parameter().
send_statustext()
void GCS::send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char * text) virtual
Reimplemented in GCS_Dummy.
Definition at line 2148 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::send_textv(), and send_textv().
send_text()
void GCS::send_text (MAV_SEVERITY severity, const char * fmt, ...)
Definition at line 40 of file GCS.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_save_cfg(), ChibiOS::RCInput::_timer_tick(), AP_Motors::add_motor_num(), lua_scripts::atpanic(), AP_BoardConfig::board_init_safety(), AP_GPS_SBF::broadcast_configuration_failure_reason(), AP_GPS_UBLOX::broadcast_configuration_failure_reason(), AP_GPS::broadcast_first_configuration_failure_reason(), AP_GPS_Backend::broadcast_gps_type(), AP_Landing_Deepstall::build_approach_path(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), CompassCalibrator::calculate_orientation(), AP_WindVane_Analog::calibrate(), AP_WindVane_ModernDevice::calibrate(), AP_WindVane_Backend::calibrate(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), AP_AdvancedFailsafe::check(), AP_Tuning::check_controller_error(), SoaringController::check_cruise_criteria(), AP_BattMonitor::check_failsafes(), AP_Tuning::check_input(), AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), AP_Tuning::check_selector_switch(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), NavEKF2_core::checkAttitudeAlignmentStatus(), NavEKF3_core::checkAttitudeAlignmentStatus(), NavEKF2::checkLaneSwitch(), NavEKF3::checkLaneSwitch(), AP_BattMonitor::checkPoweringOff(), CompassLearn::CompassLearn(), AC_AutoTune::control_attitude(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AP_SmartRTL::deactivate(), AP_LandingGear::deploy(), RC_Channel::do_aux_function(), AC_AutoTune::do_gcs_announcements(), AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), AP_ICEngine::engine_control(), NavEKF3_core::FuseBodyVel(), NavEKF3_core::FuseOptFlow(), GCS_send_text(), AP_AdvancedFailsafe::gcs_terminate(), AP_Gripper_Servo::grab(), AP_Gripper_EPM::grab(), GCS_MAVLINK::handle_command_flash_bootloader(), MissionItemProtocol::handle_mission_write_partial_list(), AP_ADSB::handle_out_cfg(), GCS_MAVLINK::handle_timesync(), AP_ADSB::handle_transceiver_report(), AP_Gripper_Servo::has_state_pwm(), AP_Mission::increment_jump_times_run(), AP_MotorsTri::init(), AP_SmartRTL::init(), AP_Airspeed::init(), AP_Compass_AK09916::init(), AP_Logger::Init(), AP_InertialSensor::BatchSampler::init(), AP_Mission::init(), RC_Channel::init_aux_function(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Mission::jump_to_abort_landing_sequence(), AP_Mission::jump_to_landing_sequence(), lua_scripts::load_all_scripts_in_dir(), lua_scripts::load_script(), AP_AHRS_DCM::load_watchdog_home(), GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame(), AP_Tuning::next_parameter(), AP_Landing_Deepstall::override_servos(), AP_MotorsHeli::parameter_check(), AP_MotorsHeli_Dual::parameter_check(), AP_MotorsHeli_Single::parameter_check(), AP_Landing_Deepstall::predict_travel_distance(), AP_GPS_SBF::prepare_for_arming(), AP_Compass_AK09916::probe_ICM20948(), AP_GPS_SBF::process_message(), AP_BattMonitor_FuelFlow::read(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AP_Gripper_Servo::release(), AP_Gripper_EPM::release(), AP_Parachute::release(), AP_AHRS_DCM::reset(), AP_Landing::restart_landing_sequence(), AP_LandingGear::retract(), AC_AutoTune::run(), lua_scripts::run(), lua_scripts::run_next_script(), AC_AutoTune::send_step_string(), AP_BoardConfig::sensor_config_error(), GCS_MAVLINK::set_mavlink_message_id_interval(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), NavEKF3_core::setup_core(), AP_Mission::start_command(), AP_Mission::start_command_do_gripper(), GCS_MAVLINK::try_send_message(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_do_land(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), CompassLearn::update(), AP_RPM_Pin::update(), AP_ICEngine::update(), SITL::Parachute::update(), AP_WindVane::update(), AP_ADSB::update(), AP_Airspeed::update_calibration(), AC_AutoTune::update_gcs(), AP::PerfInfo::update_logging(), update_passthru(), AP_WheelEncoder_Quadrature::update_pin(), GCS_MAVLINK::update_receive(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), NavEKF2_core::UpdateFilter(), and AP_Landing::verify_land().
send_textv()
void GCS::send_textv (MAV_SEVERITY severity, const char * fmt, va_list arg_list)
Definition at line 33 of file GCS.cpp.
Referenced by AP_Arming::check_failed(), and send_text().
send_to_active_channels()
void GCS::send_to_active_channels (uint32_t msgid, const char * pkt)
Definition at line 48 of file GCS.cpp.
Referenced by AP_Airspeed::send_airspeed_calibration(), send_named_float(), send_parameter_value(), and AP_Button::send_report().
service_statustext()
void GCS::service_statustext (void)
Definition at line 2189 of file GCS_Common.cpp.
Referenced by send_statustext(), and update_send().
setup_uarts()
void GCS::setup_uarts () virtual
Definition at line 2293 of file GCS_Common.cpp.
simple_input_active()
virtual bool GCS::simple_input_active () const inline virtual
Definition at line 996 of file GCS.h.
Referenced by AP_Frsky_Telem::calc_ap_status().
supersimple_input_active()
virtual bool GCS::supersimple_input_active () const inline virtual
Definition at line 997 of file GCS.h.
Referenced by AP_Frsky_Telem::calc_ap_status().
try_send_queued_message_for_type()
void GCS::try_send_queued_message_for_type (MAV_MISSION_TYPE type)
Definition at line 4201 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::try_send_mission_message().
update_passthru()
void GCS::update_passthru (void)
Definition at line 4860 of file GCS_Common.cpp.
Referenced by update_receive().
update_receive()
void GCS::update_receive (void)
Definition at line 2272 of file GCS_Common.cpp.
Referenced by AP_BoardConfig::sensor_config_error().
update_send()
void GCS::update_send ()
Definition at line 2243 of file GCS_Common.cpp.
Referenced by AP_BoardConfig::sensor_config_error().
update_sensor_status_flags()
void GCS::update_sensor_status_flags () protected
Definition at line 101 of file GCS.cpp.
Referenced by get_sensor_status_flags().
update_vehicle_sensor_status_flags()
virtual void GCS::update_vehicle_sensor_status_flags () inline protected virtual
Definition at line 1005 of file GCS.h.
Referenced by update_sensor_status_flags().
vehicle_initialised()
virtual bool GCS::vehicle_initialised () const inline virtual
Definition at line 994 of file GCS.h.
Member Data Documentation
_missionitemprotocol_rally
MissionItemProtocol_Rally * GCS::_missionitemprotocol_rally static
Definition at line 961 of file GCS.h.
Referenced by get_prot_for_mission_type(), and update_send().
_missionitemprotocol_waypoints
MissionItemProtocol_Waypoints * GCS::_missionitemprotocol_waypoints static
Definition at line 960 of file GCS.h.
Referenced by get_prot_for_mission_type(), and update_send().
_passthru
struct { ... } GCS::_passthru
Referenced by passthru_timer(), and update_passthru().
_singleton
GCS * GCS::_singleton = nullptr static private
Definition at line 1009 of file GCS.h.
Referenced by GCS(), and get_singleton().
_status_capacity
const uint8_t GCS::_status_capacity = 5 static private
Definition at line 1017 of file GCS.h.
Referenced by service_statustext().
_statustext_queue
ObjectArray<statustext_t> GCS::_statustext_queue {_status_capacity} private
Definition at line 1027 of file GCS.h.
Referenced by send_statustext(), and service_statustext().
_statustext_sem
HAL_Semaphore GCS::_statustext_sem private
Definition at line 1024 of file GCS.h.
Referenced by send_statustext(), and update_send().
control_sensors_enabled
uint32_t GCS::control_sensors_enabled protected
Definition at line 1002 of file GCS.h.
Referenced by get_sensor_status_flags(), and update_sensor_status_flags().
control_sensors_health
uint32_t GCS::control_sensors_health protected
Definition at line 1003 of file GCS.h.
Referenced by get_sensor_status_flags(), and update_sensor_status_flags().
control_sensors_present
uint32_t GCS::control_sensors_present protected
Definition at line 1001 of file GCS.h.
Referenced by get_sensor_status_flags(), and update_sensor_status_flags().
devo_telemetry
AP_DEVO_Telem GCS::devo_telemetry
Definition at line 982 of file GCS.h.
Referenced by setup_uarts().
enabled
bool GCS::enabled
Definition at line 1034 of file GCS.h.
Referenced by get_sensor_status_flags(), update_passthru(), and update_sensor_status_flags().
frsky
AP_Frsky_Telem* GCS::frsky
Definition at line 979 of file GCS.h.
Referenced by send_statustext(), and setup_uarts().
initialised_missionitemprotocol_objects
bool GCS::initialised_missionitemprotocol_objects private
Definition at line 1030 of file GCS.h.
Referenced by update_send().
last_ms
uint32_t GCS::last_ms
Definition at line 1039 of file GCS.h.
last_port1_data_ms
uint32_t GCS::last_port1_data_ms
Definition at line 1040 of file GCS.h.
port1
AP_HAL::UARTDriver* GCS::port1
Definition at line 1036 of file GCS.h.
port2
AP_HAL::UARTDriver* GCS::port2
Definition at line 1037 of file GCS.h.
sem
HAL_Semaphore GCS::sem
Definition at line 1042 of file GCS.h.
start_ms
uint32_t GCS::start_ms
Definition at line 1038 of file GCS.h.
timeout_s
uint8_t GCS::timeout_s
Definition at line 1041 of file GCS.h.
timer_installed
bool GCS::timer_installed
Definition at line 1035 of file GCS.h.
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_Param.cpp