APM:Libraries: ByteBuffer Class Reference
ByteBuffer Class Reference
#include <RingBuffer.h>
Classes
struct IoVec
Public Member Functions
ByteBuffer (uint32_t size)
~ByteBuffer (void)
uint32_t available (void) const
void clear (void)
uint32_t space (void) const
bool empty (void) const
uint32_t write (const uint8_t *data, uint32_t len)
uint32_t read (uint8_t *data, uint32_t len)
bool read_byte (uint8_t *data)
bool update (const uint8_t *data, uint32_t len)
uint32_t get_size (void) const
bool set_size (uint32_t size)
bool advance (uint32_t n)
const uint8_t * readptr (uint32_t &available_bytes)
int16_t peek (uint32_t ofs) const
uint32_t peekbytes (uint8_t *data, uint32_t len)
uint8_t peekiovec (IoVec vec[2], uint32_t len)
uint8_t reserve (IoVec vec[2], uint32_t len)
bool commit (uint32_t len)
Private Attributes
uint8_t * buf
uint32_t size
std::atomic< uint32_t > head {0}
std::atomic< uint32_t > tail {0}
Detailed Description
Definition at line 9 of file RingBuffer.h.
Constructor & Destructor Documentation
ByteBuffer()
ByteBuffer::ByteBuffer (uint32_t size)
Definition at line 6 of file RingBuffer.cpp.
~ByteBuffer()
ByteBuffer::~ByteBuffer (void)
Definition at line 12 of file RingBuffer.cpp.
Member Function Documentation
advance()
bool ByteBuffer::advance (uint32_t n)
Definition at line 116 of file RingBuffer.cpp.
Referenced by HALSITL::UARTDriver::_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::advance(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::pop(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::push_force(), read(), read_byte(), ChibiOS::UARTDriver::write_pending_bytes_DMA(), and ChibiOS::UARTDriver::write_pending_bytes_NODMA().
available()
uint32_t ByteBuffer::available (void) const
Definition at line 37 of file RingBuffer.cpp.
Referenced by ChibiOS::UARTDriver::_timer_tick(), HALSITL::UARTDriver::_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), advance(), Linux::UARTDriver::available(), ChibiOS::UARTDriver::available(), HALSITL::UARTDriver::available(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::available(), AP_Logger_Block::io_timer(), peek(), peekiovec(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::pop(), ChibiOS::UARTDriver::rxbuff_full_irq(), ChibiOS::UARTDriver::tx_complete(), Linux::UARTDriver::tx_pending(), update(), and ChibiOS::UARTDriver::write_pending_bytes().
clear()
void ByteBuffer::clear (void)
Definition at line 49 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::begin(), HALSITL::UARTDriver::begin(), ChibiOS::UARTDriver::begin(), and ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::clear().
commit()
bool ByteBuffer::commit (uint32_t len)
Definition at line 209 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_timer_tick(), ChibiOS::UARTDriver::_timer_tick(), and write().
empty()
bool ByteBuffer::empty (void) const
Definition at line 74 of file RingBuffer.cpp.
Referenced by ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::empty().
get_size()
uint32_t ByteBuffer::get_size (void) const inline
Definition at line 42 of file RingBuffer.h.
Referenced by ChibiOS::UARTDriver::begin(), and AP_Logger_Block::Init().
peek()
int16_t ByteBuffer::peek (uint32_t ofs) const
Definition at line 253 of file RingBuffer.cpp.
Referenced by mavlink_packetise(), and read_byte().
peekbytes()
uint32_t ByteBuffer::peekbytes (uint8_t * data, uint32_t len)
Definition at line 164 of file RingBuffer.cpp.
Referenced by HALSITL::UARTDriver::_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::peek(), read(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
peekiovec()
uint8_t ByteBuffer::peekiovec (ByteBuffer::IoVec iovec[2], uint32_t len)
Definition at line 125 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_write_pending_bytes(), peekbytes(), and ChibiOS::UARTDriver::write_pending_bytes_NODMA().
read()
uint32_t ByteBuffer::read (uint8_t * data, uint32_t len)
Definition at line 219 of file RingBuffer.cpp.
Referenced by consumer_thread(), AP_Logger_Block::io_timer(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::pop(), and HALSITL::UARTDriver::read().
read_byte()
bool ByteBuffer::read_byte (uint8_t * data)
Definition at line 226 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::read(), ChibiOS::UARTDriver::read(), and ChibiOS::UARTDriver::read_locked().
readptr()
const uint8_t * ByteBuffer::readptr (uint32_t & available_bytes)
Definition at line 245 of file RingBuffer.cpp.
Referenced by HALSITL::UARTDriver::_timer_tick(), peekiovec(), and ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::readptr().
reserve()
uint8_t ByteBuffer::reserve (ByteBuffer::IoVec iovec[2], uint32_t len)
Definition at line 178 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_timer_tick(), ChibiOS::UARTDriver::_timer_tick(), and write().
set_size()
bool ByteBuffer::set_size (uint32_t size)
Definition at line 20 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_allocate_buffers(), Linux::UARTDriver::_deallocate_buffers(), HALSITL::UARTDriver::_uart_start_connection(), Linux::SPIUARTDriver::begin(), ChibiOS::UARTDriver::begin(), ChibiOS::UARTDriver::end(), and AP_Logger_Block::Init().
space()
uint32_t ByteBuffer::space (void) const
Definition at line 54 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_timer_tick(), ChibiOS::UARTDriver::_timer_tick(), HALSITL::UARTDriver::_timer_tick(), AP_Logger_Block::_WritePrioritisedBlock(), commit(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::push(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::push_force(), reserve(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::space(), Linux::UARTDriver::txspace(), ChibiOS::UARTDriver::txspace(), HALSITL::UARTDriver::txspace(), ChibiOS::UARTDriver::update_rts_line(), Linux::UARTDriver::write(), and ChibiOS::UARTDriver::write().
update()
bool ByteBuffer::update (const uint8_t * data, uint32_t len)
Definition at line 98 of file RingBuffer.cpp.
Referenced by ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::update().
write()
uint32_t ByteBuffer::write (const uint8_t * data, uint32_t len)
Definition at line 79 of file RingBuffer.cpp.
Referenced by ChibiOS::UARTDriver::_timer_tick(), HALSITL::UARTDriver::_timer_tick(), Linux::SPIUARTDriver::_write_fd(), AP_Logger_Block::_WritePrioritisedBlock(), producer_thread(), ObjectBuffer< ChibiOS::SoftSigReader::PACKED >::push(), ChibiOS::UARTDriver::rxbuff_full_irq(), Linux::UARTDriver::write(), ChibiOS::UARTDriver::write(), HALSITL::UARTDriver::write(), and ChibiOS::UARTDriver::write_locked().
Member Data Documentation
buf
uint8_t* ByteBuffer::buf private
Definition at line 87 of file RingBuffer.h.
Referenced by ByteBuffer(), peek(), peekiovec(), readptr(), reserve(), set_size(), update(), and ~ByteBuffer().
head
std::atomic<uint32_t> ByteBuffer::head {0} private
Definition at line 90 of file RingBuffer.h.
Referenced by advance(), available(), clear(), empty(), peek(), readptr(), set_size(), space(), and update().
size
uint32_t ByteBuffer::size private
Definition at line 88 of file RingBuffer.h.
Referenced by advance(), available(), ByteBuffer(), commit(), get_size(), peek(), readptr(), reserve(), set_size(), space(), and update().
tail
std::atomic<uint32_t> ByteBuffer::tail {0} private
Definition at line 91 of file RingBuffer.h.
Referenced by available(), clear(), commit(), empty(), readptr(), reserve(), set_size(), and space().
The documentation for this class was generated from the following files:
libraries/AP_HAL/utility/RingBuffer.h
libraries/AP_HAL/utility/RingBuffer.cpp