APM:Libraries: AP_OABendyRuler Class Reference
AP_OABendyRuler Class Reference
#include <AP_OABendyRuler.h>
Public Member Functions
AP_OABendyRuler ()
AP_OABendyRuler (const AP_OABendyRuler &other)=delete
AP_OABendyRuler & operator= (const AP_OABendyRuler &)=delete
void set_config (float lookahead, float margin_max)
bool update (const Location &current_loc, const Location &destination, const Vector2f &ground_speed_vec, Location &origin_new, Location &destination_new)
Private Member Functions
float calc_avoidance_margin (const Location &start, const Location &end)
bool calc_margin_from_circular_fence (const Location &start, const Location &end, float &margin)
bool calc_margin_from_polygon_fence (const Location &start, const Location &end, float &margin)
bool calc_margin_from_proximity_sensors (const Location &start, const Location &end, float &margin)
Private Attributes
float _lookahead
float _margin_max
float _current_lookahead
AP_Proximity::Proximity_Location _prx_locs [PROXIMITY_MAX_DIRECTION]
uint16_t _prx_loc_count
Detailed Description
Definition at line 12 of file AP_OABendyRuler.h.
Constructor & Destructor Documentation
AP_OABendyRuler() [1/2]
AP_OABendyRuler::AP_OABendyRuler () inline
Definition at line 15 of file AP_OABendyRuler.h.
AP_OABendyRuler() [2/2]
AP_OABendyRuler::AP_OABendyRuler (const AP_OABendyRuler & other) delete
Member Function Documentation
calc_avoidance_margin()
float AP_OABendyRuler::calc_avoidance_margin (const Location & start, const Location & end) private
Definition at line 147 of file AP_OABendyRuler.cpp.
Referenced by update().
calc_margin_from_circular_fence()
bool AP_OABendyRuler::calc_margin_from_circular_fence (const Location & start, const Location & end, float & margin) private
Definition at line 170 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
calc_margin_from_polygon_fence()
bool AP_OABendyRuler::calc_margin_from_polygon_fence (const Location & start, const Location & end, float & margin) private
Definition at line 196 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
calc_margin_from_proximity_sensors()
bool AP_OABendyRuler::calc_margin_from_proximity_sensors (const Location & start, const Location & end, float & margin) private
Definition at line 231 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
operator=()
AP_OABendyRuler& AP_OABendyRuler::operator= (const AP_OABendyRuler &) delete
set_config()
void AP_OABendyRuler::set_config (float lookahead, float margin_max) inline
Definition at line 22 of file AP_OABendyRuler.h.
Referenced by AP_OAPathPlanner::avoidance_thread().
update()
bool AP_OABendyRuler::update (const Location & current_loc, const Location & destination, const Vector2f & ground_speed_vec, Location & origin_new, Location & destination_new)
Definition at line 29 of file AP_OABendyRuler.cpp.
Referenced by AP_OAPathPlanner::avoidance_thread().
Member Data Documentation
_current_lookahead
float AP_OABendyRuler::_current_lookahead private
Definition at line 50 of file AP_OABendyRuler.h.
Referenced by update().
_lookahead
float AP_OABendyRuler::_lookahead private
Definition at line 46 of file AP_OABendyRuler.h.
Referenced by set_config(), and update().
_margin_max
float AP_OABendyRuler::_margin_max private
Definition at line 47 of file AP_OABendyRuler.h.
Referenced by set_config(), and update().
_prx_loc_count
uint16_t AP_OABendyRuler::_prx_loc_count private
Definition at line 52 of file AP_OABendyRuler.h.
Referenced by calc_margin_from_proximity_sensors().
_prx_locs
AP_Proximity::Proximity_Location AP_OABendyRuler::_prx_locs[PROXIMITY_MAX_DIRECTION] private
Definition at line 51 of file AP_OABendyRuler.h.
Referenced by calc_margin_from_proximity_sensors().
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AP_OABendyRuler.h
libraries/AC_Avoidance/AP_OABendyRuler.cpp