APM:Libraries: AP_RCProtocol_IBUS Class Reference
AP_RCProtocol_IBUS Class Reference
#include <AP_RCProtocol_IBUS.h>
Public Member Functions
AP_RCProtocol_IBUS (AP_RCProtocol &_frontend)
void process_pulse (uint32_t width_s0, uint32_t width_s1) override
void process_byte (uint8_t byte, uint32_t baudrate) override
Public Member Functions inherited from AP_RCProtocol_Backend
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
uint16_t read (uint8_t chan)
bool new_input ()
uint8_t num_channels ()
virtual void start_bind (void)
virtual void update (void)
uint32_t get_rc_frame_count (void) const
uint32_t get_rc_input_count (void) const
Private Member Functions
void _process_byte (uint32_t timestamp_us, uint8_t byte)
bool ibus_decode (const uint8_t frame[IBUS_FRAME_SIZE], uint16_t *values, bool *ibus_failsafe)
Private Attributes
SoftSerial ss {115200, SoftSerial::SERIAL_CONFIG_8N1}
uint32_t saved_width
struct {
uint8_t buf [IBUS_FRAME_SIZE]
uint8_t ofs
uint32_t last_byte_us
} byte_input
Additional Inherited Members
Public Types inherited from AP_RCProtocol_Backend
enum { PARSE_TYPE_SIGREAD, PARSE_TYPE_SERIAL }
Protected Member Functions inherited from AP_RCProtocol_Backend
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe)
Detailed Description
Definition at line 25 of file AP_RCProtocol_IBUS.h.
Constructor & Destructor Documentation
AP_RCProtocol_IBUS()
AP_RCProtocol_IBUS::AP_RCProtocol_IBUS (AP_RCProtocol & _frontend)
Definition at line 20 of file AP_RCProtocol_IBUS.cpp.
Member Function Documentation
_process_byte()
void AP_RCProtocol_IBUS::_process_byte (uint32_t timestamp_us, uint8_t byte) private
Definition at line 68 of file AP_RCProtocol_IBUS.cpp.
Referenced by process_byte(), and process_pulse().
ibus_decode()
bool AP_RCProtocol_IBUS::ibus_decode (const uint8_t frame[IBUS_FRAME_SIZE], uint16_t * values, bool * ibus_failsafe) private
Definition at line 25 of file AP_RCProtocol_IBUS.cpp.
Referenced by _process_byte().
process_byte()
void AP_RCProtocol_IBUS::process_byte (uint8_t byte, uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 100 of file AP_RCProtocol_IBUS.cpp.
process_pulse()
void AP_RCProtocol_IBUS::process_pulse (uint32_t width_s0, uint32_t width_s1) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 59 of file AP_RCProtocol_IBUS.cpp.
Member Data Documentation
buf
uint8_t AP_RCProtocol_IBUS::buf[IBUS_FRAME_SIZE]
Definition at line 39 of file AP_RCProtocol_IBUS.h.
byte_input
struct { ... } AP_RCProtocol_IBUS::byte_input
Referenced by _process_byte().
last_byte_us
uint32_t AP_RCProtocol_IBUS::last_byte_us
Definition at line 41 of file AP_RCProtocol_IBUS.h.
ofs
uint8_t AP_RCProtocol_IBUS::ofs
Definition at line 40 of file AP_RCProtocol_IBUS.h.
saved_width
uint32_t AP_RCProtocol_IBUS::saved_width private
Definition at line 36 of file AP_RCProtocol_IBUS.h.
ss
SoftSerial AP_RCProtocol_IBUS::ss {115200, SoftSerial::SERIAL_CONFIG_8N1} private
Definition at line 35 of file AP_RCProtocol_IBUS.h.
Referenced by process_pulse().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_IBUS.h
libraries/AP_RCProtocol/AP_RCProtocol_IBUS.cpp