APM:Libraries: RCMapper Class Reference
RCMapper Class Reference
#include <AP_RCMapper.h>
Public Member Functions
RCMapper ()
RCMapper (const RCMapper &other)=delete
RCMapper & operator= (const RCMapper &)=delete
uint8_t roll () const
roll - return input channel number for roll / aileron input
uint8_t pitch () const
pitch - return input channel number for pitch / elevator input
uint8_t throttle () const
throttle - return input channel number for throttle input
uint8_t yaw () const
yaw - return input channel number for yaw / rudder input
uint8_t forward () const
forward - return input channel number for forward input
uint8_t lateral () const
lateral - return input channel number for lateral input
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 _ch_roll
AP_Int8 _ch_pitch
AP_Int8 _ch_yaw
AP_Int8 _ch_throttle
AP_Int8 _ch_forward
AP_Int8 _ch_lateral
Detailed Description
Definition at line 7 of file AP_RCMapper.h.
Constructor & Destructor Documentation
RCMapper() [1/2]
RCMapper::RCMapper (void)
Definition at line 65 of file AP_RCMapper.cpp.
RCMapper() [2/2]
RCMapper::RCMapper (const RCMapper & other) delete
Member Function Documentation
forward()
uint8_t RCMapper::forward () const inline
forward - return input channel number for forward input
Definition at line 28 of file AP_RCMapper.h.
lateral()
uint8_t RCMapper::lateral () const inline
lateral - return input channel number for lateral input
Definition at line 31 of file AP_RCMapper.h.
operator=()
RCMapper& RCMapper::operator= (const RCMapper &) delete
pitch()
uint8_t RCMapper::pitch () const inline
pitch - return input channel number for pitch / elevator input
Definition at line 19 of file AP_RCMapper.h.
Referenced by SRV_Channels::upgrade_parameters().
roll()
uint8_t RCMapper::roll () const inline
roll - return input channel number for roll / aileron input
Definition at line 16 of file AP_RCMapper.h.
Referenced by SRV_Channels::upgrade_parameters().
throttle()
uint8_t RCMapper::throttle () const inline
throttle - return input channel number for throttle input
Definition at line 22 of file AP_RCMapper.h.
Referenced by SRV_Channels::upgrade_parameters().
yaw()
uint8_t RCMapper::yaw () const inline
yaw - return input channel number for yaw / rudder input
Definition at line 25 of file AP_RCMapper.h.
Referenced by SRV_Channels::upgrade_parameters().
Member Data Documentation
_ch_forward
AP_Int8 RCMapper::_ch_forward private
Definition at line 41 of file AP_RCMapper.h.
Referenced by forward().
_ch_lateral
AP_Int8 RCMapper::_ch_lateral private
Definition at line 42 of file AP_RCMapper.h.
Referenced by lateral().
_ch_pitch
AP_Int8 RCMapper::_ch_pitch private
Definition at line 38 of file AP_RCMapper.h.
Referenced by pitch().
_ch_roll
AP_Int8 RCMapper::_ch_roll private
Definition at line 37 of file AP_RCMapper.h.
Referenced by roll().
_ch_throttle
AP_Int8 RCMapper::_ch_throttle private
Definition at line 40 of file AP_RCMapper.h.
Referenced by throttle().
_ch_yaw
AP_Int8 RCMapper::_ch_yaw private
Definition at line 39 of file AP_RCMapper.h.
Referenced by yaw().
var_info
const AP_Param::GroupInfo RCMapper::var_info static
Definition at line 33 of file AP_RCMapper.h.
Referenced by RCMapper().
The documentation for this class was generated from the following files:
libraries/AP_RCMapper/AP_RCMapper.h
libraries/AP_RCMapper/AP_RCMapper.cpp