APM:Libraries: NotchFilterParams Class Reference
NotchFilterParams Class Reference
#include <NotchFilter.h>
Public Member Functions
NotchFilterParams (void)
uint16_t center_freq_hz (void) const
uint16_t bandwidth_hz (void) const
float attenuation_dB (void) const
uint8_t enabled (void) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 _enable
AP_Int16 _center_freq_hz
AP_Int16 _bandwidth_hz
AP_Float _attenuation_dB
Detailed Description
Definition at line 46 of file NotchFilter.h.
Constructor & Destructor Documentation
NotchFilterParams()
NotchFilterParams::NotchFilterParams (void)
Definition at line 105 of file NotchFilter.cpp.
Member Function Documentation
attenuation_dB()
float NotchFilterParams::attenuation_dB (void) const inline
Definition at line 53 of file NotchFilter.h.
Referenced by AP_InertialSensor_Backend::_gyro_notch_attenuation_dB().
bandwidth_hz()
uint16_t NotchFilterParams::bandwidth_hz (void) const inline
Definition at line 52 of file NotchFilter.h.
Referenced by AP_InertialSensor_Backend::_gyro_notch_bandwidth_hz().
center_freq_hz()
uint16_t NotchFilterParams::center_freq_hz (void) const inline
Definition at line 51 of file NotchFilter.h.
Referenced by AP_InertialSensor_Backend::_gyro_notch_center_freq_hz().
enabled()
uint8_t NotchFilterParams::enabled (void) const inline
Definition at line 54 of file NotchFilter.h.
Referenced by AP_InertialSensor_Backend::_gyro_notch_enabled().
Member Data Documentation
_attenuation_dB
AP_Float NotchFilterParams::_attenuation_dB private
Definition at line 60 of file NotchFilter.h.
Referenced by attenuation_dB().
_bandwidth_hz
AP_Int16 NotchFilterParams::_bandwidth_hz private
Definition at line 59 of file NotchFilter.h.
Referenced by bandwidth_hz().
_center_freq_hz
AP_Int16 NotchFilterParams::_center_freq_hz private
Definition at line 58 of file NotchFilter.h.
Referenced by center_freq_hz().
_enable
AP_Int8 NotchFilterParams::_enable private
Definition at line 57 of file NotchFilter.h.
Referenced by enabled().
var_info
const AP_Param::GroupInfo NotchFilterParams::var_info static
Definition at line 49 of file NotchFilter.h.
Referenced by NotchFilterParams().
The documentation for this class was generated from the following files:
libraries/Filter/NotchFilter.h
libraries/Filter/NotchFilter.cpp