APM:Libraries: AP_GPS Class Reference
AP_GPS Class Reference
#include <AP_GPS.h>
Classes
struct detect_state
struct GPS_State
struct GPS_timing
struct rtcm_buffer
Public Types
enum GPS_Type {
GPS_TYPE_NONE = 0, GPS_TYPE_AUTO = 1, GPS_TYPE_UBLOX = 2, GPS_TYPE_MTK = 3,
GPS_TYPE_MTK19 = 4, GPS_TYPE_NMEA = 5, GPS_TYPE_SIRF = 6, GPS_TYPE_HIL = 7,
GPS_TYPE_SBP = 8, GPS_TYPE_UAVCAN = 9, GPS_TYPE_SBF = 10, GPS_TYPE_GSOF = 11,
GPS_TYPE_ERB = 13, GPS_TYPE_MAV = 14, GPS_TYPE_NOVA = 15
}
enum GPS_Status {
NO_GPS = GPS_FIX_TYPE_NO_GPS, NO_FIX = GPS_FIX_TYPE_NO_FIX, GPS_OK_FIX_2D = GPS_FIX_TYPE_2D_FIX, GPS_OK_FIX_3D = GPS_FIX_TYPE_3D_FIX,
GPS_OK_FIX_3D_DGPS = GPS_FIX_TYPE_DGPS, GPS_OK_FIX_3D_RTK_FLOAT = GPS_FIX_TYPE_RTK_FLOAT, GPS_OK_FIX_3D_RTK_FIXED = GPS_FIX_TYPE_RTK_FIXED
}
GPS status codes.
enum GPS_Engine_Setting {
GPS_ENGINE_NONE = -1, GPS_ENGINE_PORTABLE = 0, GPS_ENGINE_STATIONARY = 2, GPS_ENGINE_PEDESTRIAN = 3,
GPS_ENGINE_AUTOMOTIVE = 4, GPS_ENGINE_SEA = 5, GPS_ENGINE_AIRBORNE_1G = 6, GPS_ENGINE_AIRBORNE_2G = 7,
GPS_ENGINE_AIRBORNE_4G = 8
}
enum GPS_Config { GPS_ALL_CONFIGURED = 255 }
Public Member Functions
AP_GPS ()
AP_GPS (const AP_GPS &other)=delete
AP_GPS & operator= (const AP_GPS &)=delete
void init (const AP_SerialManager &serial_manager)
Startup initialisation.
void update (void)
void handle_msg (const mavlink_message_t *msg)
uint8_t num_sensors (void) const
uint8_t primary_sensor (void) const
GPS_Status status (uint8_t instance) const
Query GPS status.
GPS_Status status (void) const
GPS_Status highest_supported_status (uint8_t instance) const
const Location & location (uint8_t instance) const
const Location & location () const
bool speed_accuracy (uint8_t instance, float &sacc) const
bool speed_accuracy (float &sacc) const
bool horizontal_accuracy (uint8_t instance, float &hacc) const
bool horizontal_accuracy (float &hacc) const
bool vertical_accuracy (uint8_t instance, float &vacc) const
bool vertical_accuracy (float &vacc) const
const Vector3f & velocity (uint8_t instance) const
const Vector3f & velocity () const
float ground_speed (uint8_t instance) const
float ground_speed () const
uint32_t ground_speed_cm (void)
float ground_course (uint8_t instance) const
float ground_course () const
int32_t ground_course_cd (uint8_t instance) const
int32_t ground_course_cd () const
uint8_t num_sats (uint8_t instance) const
uint8_t num_sats () const
uint32_t time_week_ms (uint8_t instance) const
uint32_t time_week_ms () const
uint16_t time_week (uint8_t instance) const
uint16_t time_week () const
uint16_t get_hdop (uint8_t instance) const
uint16_t get_hdop () const
uint16_t get_vdop (uint8_t instance) const
uint16_t get_vdop () const
uint32_t last_fix_time_ms (uint8_t instance) const
uint32_t last_fix_time_ms (void) const
uint32_t last_message_time_ms (uint8_t instance) const
uint32_t last_message_time_ms (void) const
uint16_t last_message_delta_time_ms (uint8_t instance) const
uint16_t last_message_delta_time_ms (void) const
bool have_vertical_velocity (uint8_t instance) const
bool have_vertical_velocity (void) const
bool get_lag (uint8_t instance, float &lag_sec) const
bool get_lag (float &lag_sec) const
const Vector3f & get_antenna_offset (uint8_t instance) const
void setHIL (uint8_t instance, GPS_Status status, uint64_t time_epoch_ms, const Location &location, const Vector3f &velocity, uint8_t num_sats, uint16_t hdop)
void setHIL_Accuracy (uint8_t instance, float vdop, float hacc, float vacc, float sacc, bool _have_vertical_velocity, uint32_t sample_ms)
void lock_port (uint8_t instance, bool locked)
void send_mavlink_gps_raw (mavlink_channel_t chan)
void send_mavlink_gps2_raw (mavlink_channel_t chan)
void send_mavlink_gps_rtk (mavlink_channel_t chan, uint8_t inst)
uint8_t first_unconfigured_gps (void) const
void broadcast_first_configuration_failure_reason (void) const
bool all_configured (void) const
bool all_consistent (float &distance) const
bool blend_health_check () const
void send_blob_start (uint8_t instance, const char *_blob, uint16_t size)
void send_blob_update (uint8_t instance)
uint64_t time_epoch_usec (uint8_t instance) const
uint64_t time_epoch_usec (void) const
void Write_AP_Logger_Log_Startup_messages ()
void set_log_gps_bit (uint32_t bit)
bool is_healthy (uint8_t instance) const
bool is_healthy (void) const
bool prepare_for_arming (void)
void force_disable (bool disable)
Static Public Member Functions
static AP_GPS * get_singleton ()
static uint64_t time_epoch_convert (uint16_t gps_week, uint32_t gps_ms)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
AP_Int8 _type [GPS_MAX_RECEIVERS]
AP_Int8 _navfilter
AP_Int8 _auto_switch
AP_Int8 _min_dgps
AP_Int16 _sbp_logmask
AP_Int8 _inject_to
uint32_t _last_instance_swap_ms
AP_Int8 _sbas_mode
AP_Int8 _min_elevation
AP_Int8 _raw_data
AP_Int8 _gnss_mode [GPS_MAX_RECEIVERS]
AP_Int16 _rate_ms [GPS_MAX_RECEIVERS]
AP_Int8 _save_config
AP_Int8 _auto_config
AP_Vector3f _antenna_offset [GPS_MAX_RECEIVERS]
AP_Int16 _delay_ms [GPS_MAX_RECEIVERS]
AP_Int8 _blend_mask
AP_Float _blend_tc
uint32_t _log_gps_bit = -1
Private Types
enum GPS_AUTO_CONFIG { GPS_AUTO_CONFIG_DISABLE = 0, GPS_AUTO_CONFIG_ENABLE = 1 }
Private Member Functions
uint16_t get_rate_ms (uint8_t instance) const
void detect_instance (uint8_t instance)
void update_instance (uint8_t instance)
void handle_gps_rtcm_data (const mavlink_message_t *msg)
void handle_gps_inject (const mavlink_message_t *msg)
void inject_data (uint8_t *data, uint16_t len)
void inject_data (uint8_t instance, uint8_t *data, uint16_t len)
bool calc_blend_weights (void)
void calc_blended_state (void)
bool should_log () const
Private Attributes
GPS_timing timing [GPS_MAX_INSTANCES]
GPS_State state [GPS_MAX_INSTANCES]
AP_GPS_Backend * drivers [GPS_MAX_RECEIVERS]
AP_HAL::UARTDriver * _port [GPS_MAX_RECEIVERS]
uint8_t primary_instance
primary GPS instance
uint8_t num_instances
number of GPS instances present
uint8_t locked_ports
struct AP_GPS::detect_state detect_state [GPS_MAX_RECEIVERS]
struct {
const char * blob
uint16_t remaining
} initblob_state [GPS_MAX_RECEIVERS]
struct AP_GPS::rtcm_buffer * rtcm_buffer
Vector2f _NE_pos_offset_m [GPS_MAX_RECEIVERS]
float _hgt_offset_cm [GPS_MAX_RECEIVERS]
Vector3f _blended_antenna_offset
float _blended_lag_sec
float _blend_weights [GPS_MAX_RECEIVERS]
uint32_t _last_time_updated [GPS_MAX_RECEIVERS]
float _omega_lpf
bool _output_is_blended
uint8_t _blend_health_counter
bool _force_disable_gps
Static Private Attributes
static AP_GPS * _singleton
static const uint32_t _baudrates [] = {9600U, 115200U, 4800U, 19200U, 38400U, 57600U, 230400U}
static const char _initialisation_blob [] = UBLOX_SET_BINARY MTK_SET_BINARY SIRF_SET_BINARY
static const char _initialisation_raw_blob []
Friends
class AP_GPS_ERB
class AP_GPS_GSOF
class AP_GPS_MAV
class AP_GPS_MTK
class AP_GPS_MTK19
class AP_GPS_NMEA
class AP_GPS_NOVA
class AP_GPS_PX4
class AP_GPS_SBF
class AP_GPS_SBP
class AP_GPS_SBP2
class AP_GPS_SIRF
class AP_GPS_UBLOX
class AP_GPS_Backend
Detailed Description
GPS driver main class
Definition at line 43 of file AP_GPS.h.
Member Enumeration Documentation
GPS_AUTO_CONFIG
enum AP_GPS::GPS_AUTO_CONFIG private
Enumerator
GPS_AUTO_CONFIG_DISABLE
GPS_AUTO_CONFIG_ENABLE
Definition at line 541 of file AP_GPS.h.
GPS_Config
enum AP_GPS::GPS_Config
Enumerator
GPS_ALL_CONFIGURED
Definition at line 115 of file AP_GPS.h.
GPS_Engine_Setting
enum AP_GPS::GPS_Engine_Setting
Enumerator
GPS_ENGINE_NONE
GPS_ENGINE_PORTABLE
GPS_ENGINE_STATIONARY
GPS_ENGINE_PEDESTRIAN
GPS_ENGINE_AUTOMOTIVE
GPS_ENGINE_SEA
GPS_ENGINE_AIRBORNE_1G
GPS_ENGINE_AIRBORNE_2G
GPS_ENGINE_AIRBORNE_4G
Definition at line 103 of file AP_GPS.h.
GPS_Status
enum AP_GPS::GPS_Status
GPS status codes.
Enumerator
NO_GPS
No GPS connected/detected.
NO_FIX
Receiving valid GPS messages but no lock.
GPS_OK_FIX_2D
Receiving valid messages and 2D lock.
GPS_OK_FIX_3D
Receiving valid messages and 3D lock.
GPS_OK_FIX_3D_DGPS
Receiving valid messages and 3D lock with differential improvements.
GPS_OK_FIX_3D_RTK_FLOAT
Receiving valid messages and 3D RTK Float.
GPS_OK_FIX_3D_RTK_FIXED
Receiving valid messages and 3D RTK Fixed.
Definition at line 91 of file AP_GPS.h.
GPS_Type
enum AP_GPS::GPS_Type
Enumerator
GPS_TYPE_NONE
GPS_TYPE_AUTO
GPS_TYPE_UBLOX
GPS_TYPE_MTK
GPS_TYPE_MTK19
GPS_TYPE_NMEA
GPS_TYPE_SIRF
GPS_TYPE_HIL
GPS_TYPE_SBP
GPS_TYPE_UAVCAN
GPS_TYPE_SBF
GPS_TYPE_GSOF
GPS_TYPE_ERB
GPS_TYPE_MAV
GPS_TYPE_NOVA
Definition at line 72 of file AP_GPS.h.
Constructor & Destructor Documentation
AP_GPS() [1/2]
AP_GPS::AP_GPS ()
Definition at line 276 of file AP_GPS.cpp.
AP_GPS() [2/2]
AP_GPS::AP_GPS (const AP_GPS & other) delete
Member Function Documentation
all_configured()
bool AP_GPS::all_configured (void) const inline
Definition at line 364 of file AP_GPS.h.
Referenced by AP_GPS_all_configured(), and get_lag().
all_consistent()
bool AP_GPS::all_consistent (float & distance) const
Definition at line 1003 of file AP_GPS.cpp.
Referenced by AP_Arming::gps_checks().
blend_health_check()
bool AP_GPS::blend_health_check () const
Definition at line 1019 of file AP_GPS.cpp.
Referenced by AP_Arming::gps_checks(), and is_healthy().
broadcast_first_configuration_failure_reason()
void AP_GPS::broadcast_first_configuration_failure_reason (void) const
Definition at line 992 of file AP_GPS.cpp.
Referenced by AP_Arming::gps_checks().
calc_blend_weights()
bool AP_GPS::calc_blend_weights (void) private
Definition at line 1176 of file AP_GPS.cpp.
Referenced by update().
calc_blended_state()
void AP_GPS::calc_blended_state (void) private
Definition at line 1338 of file AP_GPS.cpp.
Referenced by update().
detect_instance()
void AP_GPS::detect_instance (uint8_t instance) private
Definition at line 419 of file AP_GPS.cpp.
Referenced by update_instance().
first_unconfigured_gps()
uint8_t AP_GPS::first_unconfigured_gps (void) const
Definition at line 982 of file AP_GPS.cpp.
Referenced by all_configured(), AP_GPS_first_unconfigured_gps(), broadcast_first_configuration_failure_reason(), and AP_Arming::gps_checks().
force_disable()
void AP_GPS::force_disable (bool disable) inline
Definition at line 403 of file AP_GPS.h.
Referenced by RC_Channel::do_aux_function().
get_antenna_offset()
const Vector3f & AP_GPS::get_antenna_offset (uint8_t instance) const
Definition at line 1143 of file AP_GPS.cpp.
Referenced by AP_GPS_get_antenna_offset(), NavEKF2_core::SelectVelPosFusion(), and NavEKF3_core::SelectVelPosFusion().
get_hdop() [1/2]
uint16_t AP_GPS::get_hdop (uint8_t instance) const inline
Definition at line 283 of file AP_GPS.h.
Referenced by AP_GPS_get_hdop(), AP_Frsky_Telem::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_OSD_Screen::draw_hdop(), and AP_Logger::Write_GPS().
get_hdop() [2/2]
uint16_t AP_GPS::get_hdop () const inline
Definition at line 286 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
get_lag() [1/2]
bool AP_GPS::get_lag (uint8_t instance, float & lag_sec) const
Definition at line 1108 of file AP_GPS.cpp.
Referenced by calc_blended_state(), get_lag(), AP_AHRS_DCM::get_position(), NavEKF2_core::readGpsData(), and NavEKF3_core::readGpsData().
get_lag() [2/2]
bool AP_GPS::get_lag (float & lag_sec) const inline
Definition at line 335 of file AP_GPS.h.
get_rate_ms()
uint16_t AP_GPS::get_rate_ms (uint8_t instance) const private
Definition at line 1164 of file AP_GPS.cpp.
Referenced by AP_GPS_UBLOX::_configure_rate(), calc_blend_weights(), and AP_GPS_Backend::check_new_itow().
get_singleton()
static AP_GPS* AP_GPS::get_singleton (void) inline static
Definition at line 67 of file AP_GPS.h.
Referenced by AP_GPS_all_configured(), AP_GPS_first_unconfigured_gps(), AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_num_sensors(), AP_GPS_primary_sensor(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), AP_GPS_vertical_accuracy(), and AP::gps().
get_vdop() [1/2]
uint16_t AP_GPS::get_vdop (uint8_t instance) const inline
Definition at line 291 of file AP_GPS.h.
Referenced by AP_GPS_get_vdop(), and AP_Logger::Write_GPS().
get_vdop() [2/2]
uint16_t AP_GPS::get_vdop () const inline
Definition at line 294 of file AP_GPS.h.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
ground_course() [1/2]
float AP_GPS::ground_course (uint8_t instance) const inline
Definition at line 244 of file AP_GPS.h.
Referenced by AP_GPS_ground_course(), and AP_Logger::Write_GPS().
ground_course() [2/2]
float AP_GPS::ground_course () const inline
Definition at line 247 of file AP_GPS.h.
Referenced by ground_course_cd(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
ground_course_cd() [1/2]
int32_t AP_GPS::ground_course_cd (uint8_t instance) const inline
Definition at line 251 of file AP_GPS.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw(), AR_AttitudeControl::get_forward_speed(), AP_AHRS_DCM::get_position(), and loop().
ground_course_cd() [2/2]
int32_t AP_GPS::ground_course_cd () const inline
Definition at line 254 of file AP_GPS.h.
ground_speed() [1/2]
float AP_GPS::ground_speed (uint8_t instance) const inline
Definition at line 231 of file AP_GPS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), AP_GPS_ground_speed(), AP_Frsky_Telem::calc_gps_position(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::drift_correction_yaw(), AR_AttitudeControl::get_forward_speed(), AP_AHRS_DCM::get_position(), AP_AHRS::groundspeed_vector(), loop(), AP_DEVO_Telem::send_frames(), AP_Landing::type_slope_verify_land(), AP_AHRS_DCM::use_compass(), GCS_MAVLINK::vfr_hud_airspeed(), and AP_Logger::Write_GPS().
ground_speed() [2/2]
float AP_GPS::ground_speed () const inline
Definition at line 234 of file AP_GPS.h.
Referenced by ground_speed_cm(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
ground_speed_cm()
uint32_t AP_GPS::ground_speed_cm (void) inline
Definition at line 239 of file AP_GPS.h.
handle_gps_inject()
void AP_GPS::handle_gps_inject (const mavlink_message_t * msg) private
Definition at line 779 of file AP_GPS.cpp.
Referenced by handle_msg().
handle_gps_rtcm_data()
void AP_GPS::handle_gps_rtcm_data (const mavlink_message_t * msg) private
Definition at line 1027 of file AP_GPS.cpp.
Referenced by handle_msg().
handle_msg()
void AP_GPS::handle_msg (const mavlink_message_t * msg)
Definition at line 791 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::handle_common_message().
have_vertical_velocity() [1/2]
bool AP_GPS::have_vertical_velocity (uint8_t instance) const inline
Definition at line 325 of file AP_GPS.h.
Referenced by AP_GPS_have_vertical_velocity(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_Logger::Write_GPS().
have_vertical_velocity() [2/2]
bool AP_GPS::have_vertical_velocity (void) const inline
Definition at line 328 of file AP_GPS.h.
Referenced by calc_blended_state().
highest_supported_status()
AP_GPS::GPS_Status AP_GPS::highest_supported_status (uint8_t instance) const
Definition at line 559 of file AP_GPS.cpp.
horizontal_accuracy() [1/2]
bool AP_GPS::horizontal_accuracy (uint8_t instance, float & hacc) const
Definition at line 336 of file AP_GPS.cpp.
Referenced by AP_GPS_horizontal_accuracy(), calc_blend_weights(), calc_blended_state(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), horizontal_accuracy(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_ADSB::send_dynamic_out(), send_mavlink_gps_raw(), and AP_Logger::Write_GPS().
horizontal_accuracy() [2/2]
bool AP_GPS::horizontal_accuracy (float & hacc) const inline
Definition at line 213 of file AP_GPS.h.
init()
void AP_GPS::init (const AP_SerialManager & serial_manager)
Startup initialisation.
Definition at line 290 of file AP_GPS.cpp.
Referenced by setup().
inject_data() [1/2]
void AP_GPS::inject_data (uint8_t * data, uint16_t len) private
Definition at line 881 of file AP_GPS.cpp.
Referenced by handle_gps_inject(), and handle_gps_rtcm_data().
inject_data() [2/2]
void AP_GPS::inject_data (uint8_t instance, uint8_t * data, uint16_t len) private
Definition at line 893 of file AP_GPS.cpp.
is_healthy() [1/2]
bool AP_GPS::is_healthy (uint8_t instance) const
Definition at line 1543 of file AP_GPS.cpp.
Referenced by AP_Arming::gps_checks().
is_healthy() [2/2]
bool AP_GPS::is_healthy (void) const inline
Definition at line 397 of file AP_GPS.h.
Referenced by is_healthy().
last_fix_time_ms() [1/2]
uint32_t AP_GPS::last_fix_time_ms (uint8_t instance) const inline
Definition at line 300 of file AP_GPS.h.
Referenced by AP_GPS_last_fix_time_ms(), AP_AdvancedFailsafe::check(), AP_AHRS_DCM::drift_correction(), and AP_AHRS_DCM::drift_correction_yaw().
last_fix_time_ms() [2/2]
uint32_t AP_GPS::last_fix_time_ms (void) const inline
Definition at line 303 of file AP_GPS.h.
Referenced by calc_blended_state(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
last_message_delta_time_ms() [1/2]
uint16_t AP_GPS::last_message_delta_time_ms (uint8_t instance) const inline
Definition at line 317 of file AP_GPS.h.
Referenced by AP_Logger::Write_GPS().
last_message_delta_time_ms() [2/2]
uint16_t AP_GPS::last_message_delta_time_ms (void) const inline
Definition at line 320 of file AP_GPS.h.
Referenced by is_healthy().
last_message_time_ms() [1/2]
uint32_t AP_GPS::last_message_time_ms (uint8_t instance) const inline
Definition at line 309 of file AP_GPS.h.
Referenced by AP_GPS_last_message_time_ms(), loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_Logger::Write_GPS().
last_message_time_ms() [2/2]
uint32_t AP_GPS::last_message_time_ms (void) const inline
Definition at line 312 of file AP_GPS.h.
Referenced by calc_blended_state(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), and update_instance().
location() [1/2]
const Location& AP_GPS::location (uint8_t instance) const inline
Definition at line 199 of file AP_GPS.h.
Referenced by AP_GPS_location(), AP_Frsky_Telem::calc_gps_latlng(), AP_Frsky_Telem::calc_gps_position(), AP_Frsky_Telem::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_AdvancedFailsafe::check_altlimit(), AP_OSD_Screen::draw_gps_latitude(), AP_OSD_Screen::draw_gps_longitude(), AP_AHRS_DCM::drift_correction(), NavEKF3_core::getLLH(), NavEKF2_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), AP_Arming::gps_checks(), loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF2_core::resetHeightDatum(), NavEKF3_core::resetHeightDatum(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), AP_Logger::Write_CameraInfo(), and AP_Logger::Write_GPS().
location() [2/2]
const Location& AP_GPS::location () const inline
Definition at line 202 of file AP_GPS.h.
Referenced by all_consistent(), calc_blended_state(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
lock_port()
void AP_GPS::lock_port (uint8_t instance, bool lock)
Lock a GPS port, preventing the GPS driver from using it. This can be used to allow a user to control a GPS port via the SERIAL_CONTROL protocol
Definition at line 867 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::handle_serial_control().
num_sats() [1/2]
uint8_t AP_GPS::num_sats (uint8_t instance) const inline
Definition at line 259 of file AP_GPS.h.
Referenced by AP_GPS_num_sats(), AP_Frsky_Telem::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_OSD_Screen::draw_sats(), AP_AHRS_DCM::drift_correction(), loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_ADSB::send_dynamic_out(), and AP_Logger::Write_GPS().
num_sats() [2/2]
uint8_t AP_GPS::num_sats () const inline
Definition at line 262 of file AP_GPS.h.
Referenced by calc_blended_state(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), and update().
num_sensors()
uint8_t AP_GPS::num_sensors (void) const
Definition at line 318 of file AP_GPS.cpp.
Referenced by AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_num_sensors(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), and AP_GPS_vertical_accuracy().
operator=()
AP_GPS& AP_GPS::operator= (const AP_GPS &) delete
prepare_for_arming()
bool AP_GPS::prepare_for_arming (void)
Definition at line 1562 of file AP_GPS.cpp.
primary_sensor()
uint8_t AP_GPS::primary_sensor (void) const inline
Definition at line 180 of file AP_GPS.h.
Referenced by AP_GPS_primary_sensor(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_Logger::Write_GPS().
send_blob_start()
void AP_GPS::send_blob_start (uint8_t instance, const char * _blob, uint16_t size)
Definition at line 382 of file AP_GPS.cpp.
Referenced by AP_GPS_MTK::AP_GPS_MTK(), AP_GPS_SIRF::AP_GPS_SIRF(), AP_GPS_UBLOX::AP_GPS_UBLOX(), detect_instance(), and AP_GPS_MTK::send_init_blob().
send_blob_update()
void AP_GPS::send_blob_update (uint8_t instance)
Definition at line 392 of file AP_GPS.cpp.
Referenced by detect_instance(), and update_instance().
send_mavlink_gps2_raw()
void AP_GPS::send_mavlink_gps2_raw (mavlink_channel_t chan)
Definition at line 943 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::try_send_message().
send_mavlink_gps_raw()
void AP_GPS::send_mavlink_gps_raw (mavlink_channel_t chan)
Definition at line 900 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::try_send_message().
send_mavlink_gps_rtk()
void AP_GPS::send_mavlink_gps_rtk (mavlink_channel_t chan, uint8_t inst)
Definition at line 972 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::try_send_message().
set_log_gps_bit()
void AP_GPS::set_log_gps_bit (uint32_t bit) inline
Definition at line 392 of file AP_GPS.h.
setHIL()
void AP_GPS::setHIL (uint8_t instance, GPS_Status status, uint64_t time_epoch_ms, const Location & location, const Vector3f & velocity, uint8_t num_sats, uint16_t hdop)
Definition at line 816 of file AP_GPS.cpp.
setHIL_Accuracy()
void AP_GPS::setHIL_Accuracy (uint8_t instance, float vdop, float hacc, float vacc, float sacc, bool _have_vertical_velocity, uint32_t sample_ms)
Definition at line 842 of file AP_GPS.cpp.
should_log()
bool AP_GPS::should_log () const private
Definition at line 567 of file AP_GPS.cpp.
Referenced by AP_GPS_Backend::should_log(), and update_instance().
speed_accuracy() [1/2]
bool AP_GPS::speed_accuracy (uint8_t instance, float & sacc) const
Definition at line 327 of file AP_GPS.cpp.
Referenced by AP_GPS_speed_accuracy(), calc_blend_weights(), calc_blended_state(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_ADSB::send_dynamic_out(), send_mavlink_gps_raw(), speed_accuracy(), and AP_Logger::Write_GPS().
speed_accuracy() [2/2]
bool AP_GPS::speed_accuracy (float & sacc) const inline
Definition at line 208 of file AP_GPS.h.
status() [1/2]
GPS_Status AP_GPS::status (uint8_t instance) const inline
Query GPS status.
Definition at line 185 of file AP_GPS.h.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_GPS_status(), AP_Frsky_Telem::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_AdvancedFailsafe::check_altlimit(), AP_OSD_Screen::draw_sats(), AP_AHRS_DCM::drift_correction(), AR_AttitudeControl::get_forward_speed(), AP_AHRS_DCM::get_velocity_NED(), NavEKF3_core::getLLH(), NavEKF2_core::getLLH(), AP_Arming::gps_checks(), AP_AHRS::groundspeed_vector(), loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_ADSB::send_dynamic_out(), AP_Logger::Write_CameraInfo(), and AP_Logger::Write_GPS().
status() [2/2]
GPS_Status AP_GPS::status (void) const inline
Definition at line 191 of file AP_GPS.h.
Referenced by calc_blend_weights(), calc_blended_state(), get_lag(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), status(), update(), update_instance(), and Write_AP_Logger_Log_Startup_messages().
time_epoch_convert()
uint64_t AP_GPS::time_epoch_convert (uint16_t gps_week, uint32_t gps_ms) static
convert GPS week and milliseconds to unix epoch in milliseconds
Definition at line 358 of file AP_GPS.cpp.
Referenced by time_epoch_usec().
time_epoch_usec() [1/2]
uint64_t AP_GPS::time_epoch_usec (uint8_t instance) const
calculate current time since the unix epoch in microseconds
Definition at line 367 of file AP_GPS.cpp.
Referenced by AP_ADSB::genICAO(), and AP_ADSB::send_dynamic_out().
time_epoch_usec() [2/2]
uint64_t AP_GPS::time_epoch_usec (void) const inline
Definition at line 380 of file AP_GPS.h.
Referenced by update_instance().
time_week() [1/2]
uint16_t AP_GPS::time_week (uint8_t instance) const inline
Definition at line 275 of file AP_GPS.h.
Referenced by AP_GPS_time_week(), loop(), AP_Logger::Write_CameraInfo(), and AP_Logger::Write_GPS().
time_week() [2/2]
uint16_t AP_GPS::time_week () const inline
Definition at line 278 of file AP_GPS.h.
Referenced by calc_blended_state().
time_week_ms() [1/2]
uint32_t AP_GPS::time_week_ms (uint8_t instance) const inline
Definition at line 267 of file AP_GPS.h.
Referenced by AP_GPS_time_week_ms(), loop(), AP_Logger::Write_CameraInfo(), and AP_Logger::Write_GPS().
time_week_ms() [2/2]
uint32_t AP_GPS::time_week_ms () const inline
Definition at line 270 of file AP_GPS.h.
Referenced by calc_blended_state().
update()
void AP_GPS::update (void)
Update GPS state based on possible bytes received from the module. This routine must be called periodically (typically at 10Hz or more) to process incoming data.
Definition at line 677 of file AP_GPS.cpp.
Referenced by loop().
update_instance()
void AP_GPS::update_instance (uint8_t instance) private
Definition at line 586 of file AP_GPS.cpp.
Referenced by update().
velocity() [1/2]
const Vector3f& AP_GPS::velocity (uint8_t instance) const inline
Definition at line 223 of file AP_GPS.h.
Referenced by AP_GPS_velocity(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::get_velocity_NED(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_ADSB::send_dynamic_out(), and AP_Logger::Write_GPS().
velocity() [2/2]
const Vector3f& AP_GPS::velocity () const inline
Definition at line 226 of file AP_GPS.h.
Referenced by calc_blended_state().
vertical_accuracy() [1/2]
bool AP_GPS::vertical_accuracy (uint8_t instance, float & vacc) const
Definition at line 345 of file AP_GPS.cpp.
Referenced by AP_GPS_vertical_accuracy(), calc_blend_weights(), calc_blended_state(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_ADSB::send_dynamic_out(), send_mavlink_gps_raw(), vertical_accuracy(), and AP_Logger::Write_GPS().
vertical_accuracy() [2/2]
bool AP_GPS::vertical_accuracy (float & vacc) const inline
Definition at line 218 of file AP_GPS.h.
Write_AP_Logger_Log_Startup_messages()
void AP_GPS::Write_AP_Logger_Log_Startup_messages ()
Definition at line 1094 of file AP_GPS.cpp.
Friends And Related Function Documentation
AP_GPS_Backend
friend class AP_GPS_Backend friend
Definition at line 58 of file AP_GPS.h.
AP_GPS_ERB
friend class AP_GPS_ERB friend
Definition at line 45 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_GSOF
friend class AP_GPS_GSOF friend
Definition at line 46 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_MAV
friend class AP_GPS_MAV friend
Definition at line 47 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_MTK
friend class AP_GPS_MTK friend
Definition at line 48 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_MTK19
friend class AP_GPS_MTK19 friend
Definition at line 49 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_NMEA
friend class AP_GPS_NMEA friend
Definition at line 50 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_NOVA
friend class AP_GPS_NOVA friend
Definition at line 51 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_PX4
friend class AP_GPS_PX4 friend
Definition at line 52 of file AP_GPS.h.
AP_GPS_SBF
friend class AP_GPS_SBF friend
Definition at line 53 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_SBP
friend class AP_GPS_SBP friend
Definition at line 54 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_SBP2
friend class AP_GPS_SBP2 friend
Definition at line 55 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_SIRF
friend class AP_GPS_SIRF friend
Definition at line 56 of file AP_GPS.h.
Referenced by detect_instance().
AP_GPS_UBLOX
friend class AP_GPS_UBLOX friend
Definition at line 57 of file AP_GPS.h.
Referenced by detect_instance().
Member Data Documentation
_antenna_offset
AP_Vector3f AP_GPS::_antenna_offset[GPS_MAX_RECEIVERS] protected
Definition at line 424 of file AP_GPS.h.
Referenced by calc_blended_state(), get_antenna_offset(), and update().
_auto_config
AP_Int8 AP_GPS::_auto_config protected
Definition at line 423 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_request_next_config(), AP_GPS_SBF::broadcast_configuration_failure_reason(), detect_instance(), AP_GPS_UBLOX::get_lag(), AP_GPS_SBF::is_configured(), AP_GPS_UBLOX::is_configured(), AP_GPS_SBF::read(), and update_instance().
_auto_switch
AP_Int8 AP_GPS::_auto_switch protected
Definition at line 412 of file AP_GPS.h.
Referenced by update().
_baudrates
const uint32_t AP_GPS::_baudrates = {9600U, 115200U, 4800U, 19200U, 38400U, 57600U, 230400U} static private
Definition at line 485 of file AP_GPS.h.
Referenced by AP_GPS_Backend::_detection_message(), and detect_instance().
_blend_health_counter
uint8_t AP_GPS::_blend_health_counter private
Definition at line 530 of file AP_GPS.h.
Referenced by blend_health_check(), and update().
_blend_mask
AP_Int8 AP_GPS::_blend_mask protected
Definition at line 426 of file AP_GPS.h.
Referenced by calc_blend_weights().
_blend_tc
AP_Float AP_GPS::_blend_tc protected
Definition at line 427 of file AP_GPS.h.
Referenced by init().
_blend_weights
float AP_GPS::_blend_weights[GPS_MAX_RECEIVERS] private
Definition at line 526 of file AP_GPS.h.
Referenced by calc_blend_weights(), and calc_blended_state().
_blended_antenna_offset
Vector3f AP_GPS::_blended_antenna_offset private
Definition at line 524 of file AP_GPS.h.
Referenced by calc_blended_state(), get_antenna_offset(), and update().
_blended_lag_sec
float AP_GPS::_blended_lag_sec private
Definition at line 525 of file AP_GPS.h.
Referenced by calc_blended_state(), and get_lag().
_delay_ms
AP_Int16 AP_GPS::_delay_ms[GPS_MAX_RECEIVERS] protected
Definition at line 425 of file AP_GPS.h.
Referenced by get_lag().
_force_disable_gps
bool AP_GPS::_force_disable_gps private
Definition at line 547 of file AP_GPS.h.
Referenced by force_disable(), and status().
_gnss_mode
AP_Int8 AP_GPS::_gnss_mode[GPS_MAX_RECEIVERS] protected
Definition at line 420 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
_hgt_offset_cm
float AP_GPS::_hgt_offset_cm[GPS_MAX_RECEIVERS] private
Definition at line 523 of file AP_GPS.h.
Referenced by calc_blended_state().
_initialisation_blob
const char AP_GPS::_initialisation_blob = UBLOX_SET_BINARY MTK_SET_BINARY SIRF_SET_BINARY static private
Definition at line 486 of file AP_GPS.h.
Referenced by AP_GPS(), and detect_instance().
_initialisation_raw_blob
const char AP_GPS::_initialisation_raw_blob[] static private
Definition at line 487 of file AP_GPS.h.
_inject_to
AP_Int8 AP_GPS::_inject_to protected
Definition at line 415 of file AP_GPS.h.
Referenced by inject_data().
_last_instance_swap_ms
uint32_t AP_GPS::_last_instance_swap_ms protected
Definition at line 416 of file AP_GPS.h.
Referenced by init(), and update().
_last_time_updated
uint32_t AP_GPS::_last_time_updated[GPS_MAX_RECEIVERS] private
Definition at line 527 of file AP_GPS.h.
Referenced by calc_blended_state().
_log_gps_bit
uint32_t AP_GPS::_log_gps_bit = -1 protected
Definition at line 429 of file AP_GPS.h.
Referenced by set_log_gps_bit(), and should_log().
_min_dgps
AP_Int8 AP_GPS::_min_dgps protected
Definition at line 413 of file AP_GPS.h.
_min_elevation
AP_Int8 AP_GPS::_min_elevation protected
Definition at line 418 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
_navfilter
AP_Int8 AP_GPS::_navfilter protected
Definition at line 411 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
_NE_pos_offset_m
Vector2f AP_GPS::_NE_pos_offset_m[GPS_MAX_RECEIVERS] private
Definition at line 522 of file AP_GPS.h.
Referenced by calc_blended_state().
_omega_lpf
float AP_GPS::_omega_lpf private
Definition at line 528 of file AP_GPS.h.
Referenced by calc_blended_state(), and init().
_output_is_blended
bool AP_GPS::_output_is_blended private
Definition at line 529 of file AP_GPS.h.
Referenced by num_sensors(), and update().
_port
AP_HAL::UARTDriver* AP_GPS::_port[GPS_MAX_RECEIVERS] private
Definition at line 454 of file AP_GPS.h.
Referenced by detect_instance(), init(), and send_blob_update().
_rate_ms
AP_Int16 AP_GPS::_rate_ms[GPS_MAX_RECEIVERS] protected
Definition at line 421 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), get_rate_ms(), and init().
_raw_data
AP_Int8 AP_GPS::_raw_data protected
Definition at line 419 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_UBLOX::_verify_rate(), AP_GPS_SBF::prepare_for_arming(), and AP_GPS_SBF::read().
_save_config
AP_Int8 AP_GPS::_save_config protected
Definition at line 422 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::read().
_sbas_mode
AP_Int8 AP_GPS::_sbas_mode protected
Definition at line 417 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), and AP_GPS_UBLOX::_request_next_config().
_sbp_logmask
AP_Int16 AP_GPS::_sbp_logmask protected
Definition at line 414 of file AP_GPS.h.
Referenced by AP_GPS_SBP::logging_log_raw_sbp(), and AP_GPS_SBP2::logging_log_raw_sbp().
_singleton
AP_GPS * AP_GPS::_singleton static private
Definition at line 432 of file AP_GPS.h.
Referenced by AP_GPS(), and get_singleton().
_type
AP_Int8 AP_GPS::_type[GPS_MAX_RECEIVERS] protected
Definition at line 410 of file AP_GPS.h.
Referenced by all_consistent(), detect_instance(), first_unconfigured_gps(), get_lag(), handle_msg(), setHIL(), and update_instance().
blob
const char* AP_GPS::blob
Definition at line 481 of file AP_GPS.h.
Referenced by send_blob_update().
detect_state
struct AP_GPS::detect_state AP_GPS::detect_state[GPS_MAX_RECEIVERS] private
Referenced by AP_GPS_Backend::_detection_message().
drivers
AP_GPS_Backend* AP_GPS::drivers[GPS_MAX_RECEIVERS] private
Definition at line 453 of file AP_GPS.h.
Referenced by all_consistent(), broadcast_first_configuration_failure_reason(), detect_instance(), first_unconfigured_gps(), get_lag(), handle_msg(), highest_supported_status(), inject_data(), is_healthy(), prepare_for_arming(), send_mavlink_gps_rtk(), update_instance(), and Write_AP_Logger_Log_Startup_messages().
initblob_state
struct { ... } AP_GPS::initblob_state[GPS_MAX_RECEIVERS]
Referenced by detect_instance(), send_blob_start(), and send_blob_update().
locked_ports
uint8_t AP_GPS::locked_ports private
Definition at line 463 of file AP_GPS.h.
Referenced by lock_port(), and update_instance().
num_instances
uint8_t AP_GPS::num_instances private
number of GPS instances present
Definition at line 460 of file AP_GPS.h.
Referenced by all_consistent(), get_rate_ms(), handle_msg(), num_sensors(), send_mavlink_gps2_raw(), update(), and Write_AP_Logger_Log_Startup_messages().
primary_instance
uint8_t AP_GPS::primary_instance private
primary GPS instance
Definition at line 457 of file AP_GPS.h.
Referenced by get_hdop(), get_lag(), get_vdop(), ground_course(), ground_course_cd(), ground_speed(), have_vertical_velocity(), horizontal_accuracy(), init(), is_healthy(), last_fix_time_ms(), last_message_delta_time_ms(), last_message_time_ms(), location(), num_sats(), primary_sensor(), speed_accuracy(), status(), time_epoch_usec(), time_week(), time_week_ms(), update(), velocity(), and vertical_accuracy().
remaining
uint16_t AP_GPS::remaining
Definition at line 482 of file AP_GPS.h.
Referenced by detect_instance(), and send_blob_update().
rtcm_buffer
struct AP_GPS::rtcm_buffer * AP_GPS::rtcm_buffer private
state
GPS_State AP_GPS::state[GPS_MAX_INSTANCES] private
Definition at line 452 of file AP_GPS.h.
Referenced by all_consistent(), calc_blend_weights(), calc_blended_state(), detect_instance(), get_hdop(), get_lag(), get_vdop(), ground_course(), ground_speed(), have_vertical_velocity(), horizontal_accuracy(), init(), location(), num_sats(), send_mavlink_gps2_raw(), setHIL(), setHIL_Accuracy(), speed_accuracy(), status(), time_epoch_usec(), time_week(), time_week_ms(), update(), update_instance(), velocity(), vertical_accuracy(), and Write_AP_Logger_Log_Startup_messages().
timing
GPS_timing AP_GPS::timing[GPS_MAX_INSTANCES] private
Definition at line 451 of file AP_GPS.h.
Referenced by calc_blended_state(), detect_instance(), last_fix_time_ms(), last_message_delta_time_ms(), last_message_time_ms(), setHIL(), setHIL_Accuracy(), and update_instance().
var_info
const AP_Param::GroupInfo AP_GPS::var_info static
Definition at line 387 of file AP_GPS.h.
Referenced by AP_GPS().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS.h
libraries/AP_GPS/AP_GPS.cpp