APM:Libraries: Quaternion Class Reference
Quaternion Class Reference
#include <quaternion.h>
Public Member Functions
Quaternion ()
Quaternion (const float _q1, const float _q2, const float _q3, const float _q4)
Quaternion (const float _q[4])
void operator() (const float _q1, const float _q2, const float _q3, const float _q4)
bool is_nan (void) const
void rotation_matrix (Matrix3f &m) const
void rotation_matrix_norm (Matrix3f &m) const
void from_rotation_matrix (const Matrix3f &m)
void earth_to_body (Vector3f &v) const
void from_euler (float roll, float pitch, float yaw)
void from_vector312 (float roll, float pitch, float yaw)
void to_axis_angle (Vector3f &v)
void from_axis_angle (Vector3f v)
void from_axis_angle (const Vector3f &axis, float theta)
void rotate (const Vector3f &v)
void from_axis_angle_fast (Vector3f v)
void from_axis_angle_fast (const Vector3f &axis, float theta)
void rotate_fast (const Vector3f &v)
float get_euler_roll () const
float get_euler_pitch () const
float get_euler_yaw () const
void to_euler (float &roll, float &pitch, float &yaw) const
Vector3f to_vector312 (void) const
float length (void) const
void normalize ()
void initialise ()
Quaternion inverse (void) const
float & operator[] (uint8_t i)
const float & operator[] (uint8_t i) const
Quaternion operator * (const Quaternion &v) const
Quaternion & operator *= (const Quaternion &v)
Quaternion operator/ (const Quaternion &v) const
Quaternion angular_difference (const Quaternion &v) const
Public Attributes
float q1
float q2
float q3
float q4
Detailed Description
Definition at line 26 of file quaternion.h.
Constructor & Destructor Documentation
Quaternion() [1/3]
Quaternion::Quaternion () inline
Definition at line 32 of file quaternion.h.
Referenced by inverse().
Quaternion() [2/3]
Quaternion::Quaternion (const float _q1, const float _q2, const float _q3, const float _q4) inline
Definition at line 39 of file quaternion.h.
Quaternion() [3/3]
Quaternion::Quaternion (const float _q[4]) inline
Definition at line 45 of file quaternion.h.
Member Function Documentation
angular_difference()
Quaternion Quaternion::angular_difference (const Quaternion & v) const
Definition at line 371 of file quaternion.cpp.
Referenced by AP_AHRS_NavEKF::attitudes_consistent().
earth_to_body()
void Quaternion::earth_to_body (Vector3f & v) const
Definition at line 122 of file quaternion.cpp.
Referenced by test_frame_transforms().
from_axis_angle() [1/2]
void Quaternion::from_axis_angle (Vector3f v)
Definition at line 154 of file quaternion.cpp.
Referenced by AC_AttitudeControl::attitude_controller_run_quat(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_m(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_p(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), rotate(), AC_AttitudeControl::shift_ef_yaw_target(), and AC_AttitudeControl::thrust_heading_rotation_angles().
from_axis_angle() [2/2]
void Quaternion::from_axis_angle (const Vector3f & axis, float theta)
Definition at line 166 of file quaternion.cpp.
from_axis_angle_fast() [1/2]
void Quaternion::from_axis_angle_fast (Vector3f v)
Definition at line 199 of file quaternion.cpp.
from_axis_angle_fast() [2/2]
void Quaternion::from_axis_angle_fast (const Vector3f & axis, float theta)
Definition at line 211 of file quaternion.cpp.
from_euler()
void Quaternion::from_euler (float roll, float pitch, float yaw)
Definition at line 130 of file quaternion.cpp.
Referenced by SITL::Calibration::_attitude_set(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), NavEKF2_core::controlMagYawReset(), GCS_MAVLINK::handle_common_vision_position_estimate_data(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_m(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_p(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), test_conversion(), test_frame_transforms(), and test_quaternion().
from_rotation_matrix()
void Quaternion::from_rotation_matrix (const Matrix3f & m)
Definition at line 76 of file quaternion.cpp.
Referenced by SITL::Calibration::_attitude_set(), AP_AHRS_NavEKF::attitudes_consistent(), SITL::Aircraft::fill_fdm(), from_vector312(), SITL::Aircraft::get_attitude(), AP_AHRS_View::get_quat_body_to_ned(), AP_AHRS::get_quat_body_to_ned(), AP_AHRS_NavEKF::get_secondary_quaternion(), NavEKF3::getQuaternionBodyToNED(), NavEKF2::getQuaternionBodyToNED(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_m(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_p(), SoloGimbalEKF::RunEKF(), SITL::Aircraft::smooth_sensors(), and test_quaternion().
from_vector312()
void Quaternion::from_vector312 (float roll, float pitch, float yaw)
Definition at line 146 of file quaternion.cpp.
Referenced by SoloGimbalEKF::RunEKF().
get_euler_pitch()
float Quaternion::get_euler_pitch () const
Definition at line 260 of file quaternion.cpp.
Referenced by to_euler().
get_euler_roll()
float Quaternion::get_euler_roll () const
Definition at line 254 of file quaternion.cpp.
Referenced by to_euler().
get_euler_yaw()
float Quaternion::get_euler_yaw () const
Definition at line 266 of file quaternion.cpp.
Referenced by to_euler().
initialise()
void Quaternion::initialise () inline
Definition at line 114 of file quaternion.h.
Referenced by AC_AttitudeControl::relax_attitude_controllers().
inverse()
Quaternion Quaternion::inverse (void) const
Definition at line 292 of file quaternion.cpp.
Referenced by AC_AttitudeControl::attitude_controller_run_quat(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_m(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_p(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::thrust_heading_rotation_angles(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
is_nan()
bool Quaternion::is_nan (void) const inline
Definition at line 60 of file quaternion.h.
Referenced by NavEKF2_core::getFilterFaults(), NavEKF3_core::getFilterFaults(), NavEKF2_core::updateFilterStatus(), and NavEKF3_core::updateFilterStatus().
length()
float Quaternion::length (void) const
Definition at line 287 of file quaternion.cpp.
Referenced by NavEKF3_core::getTiltError(), and normalize().
normalize()
void Quaternion::normalize (void)
Definition at line 297 of file quaternion.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), SITL::Calibration::_attitude_set(), SoloGimbalEKF::alignHeading(), AC_AttitudeControl::attitude_controller_run_quat(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), NavEKF3_core::FuseAirspeed(), NavEKF3_core::FuseBodyVel(), SoloGimbalEKF::fuseCompass(), NavEKF3_core::FuseDeclination(), NavEKF3_core::fuseEulerYaw(), NavEKF3_core::FuseMagnetometer(), NavEKF3_core::FuseOptFlow(), NavEKF3_core::FuseSideslip(), SoloGimbalEKF::fuseVelocity(), NavEKF3_core::FuseVelPosNED(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), SoloGimbalEKF::predictStates(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), SITL::Aircraft::smooth_sensors(), test_frame_transforms(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
operator *()
Quaternion Quaternion::operator * (const Quaternion & v) const
Definition at line 309 of file quaternion.cpp.
operator *=()
Quaternion & Quaternion::operator *= (const Quaternion & v)
Definition at line 330 of file quaternion.cpp.
operator()()
void Quaternion::operator() (const float _q1, const float _q2, const float _q3, const float _q4) inline
Definition at line 51 of file quaternion.h.
operator/()
Quaternion Quaternion::operator/ (const Quaternion & v) const
Definition at line 350 of file quaternion.cpp.
operator[]() [1/2]
float& Quaternion::operator[] (uint8_t i) inline
Definition at line 123 of file quaternion.h.
operator[]() [2/2]
const float& Quaternion::operator[] (uint8_t i) const inline
Definition at line 132 of file quaternion.h.
rotate()
void Quaternion::rotate (const Vector3f & v)
Definition at line 182 of file quaternion.cpp.
Referenced by SoloGimbalEKF::alignHeading(), NavEKF2_core::FuseAirspeed(), SoloGimbalEKF::fuseCompass(), NavEKF2_core::FuseDeclination(), NavEKF2_core::fuseEulerYaw(), NavEKF2_core::FuseMagnetometer(), NavEKF2_core::FuseOptFlow(), NavEKF2_core::FuseRngBcn(), NavEKF2_core::FuseSideslip(), SoloGimbalEKF::fuseVelocity(), NavEKF2_core::FuseVelPosNED(), SoloGimbalEKF::predictStates(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
rotate_fast()
void Quaternion::rotate_fast (const Vector3f & v)
Definition at line 223 of file quaternion.cpp.
rotation_matrix()
void Quaternion::rotation_matrix (Matrix3f & m) const
Definition at line 24 of file quaternion.cpp.
Referenced by HALSITL::SITL_State::_update_gps(), HALSITL::SITL_State::_update_rangefinder(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), earth_to_body(), NavEKF2_core::getRotationBodyToNED(), NavEKF3_core::getRotationBodyToNED(), SITL::Gimbal::Gimbal(), SoloGimbalEKF::predictStates(), NavEKF2_core::quat2Tbn(), NavEKF3_core::quat2Tbn(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), SITL::Gazebo::recv_fdm(), test_conversion(), test_quaternion(), AC_AttitudeControl::thrust_heading_rotation_angles(), to_vector312(), SITL::Gimbal::update(), SITL::FlightAxis::update(), AP_AHRS_NavEKF::update_SITL(), NavEKF2_core::UpdateStrapdownEquationsNED(), NavEKF3_core::UpdateStrapdownEquationsNED(), NavEKF2_core::writeOptFlowMeas(), and NavEKF3_core::writeOptFlowMeas().
rotation_matrix_norm()
void Quaternion::rotation_matrix_norm (Matrix3f & m) const
Definition at line 48 of file quaternion.cpp.
to_axis_angle()
void Quaternion::to_axis_angle (Vector3f & v)
Definition at line 189 of file quaternion.cpp.
Referenced by SITL::Calibration::_attitude_set(), AP_AHRS_NavEKF::attitudes_consistent(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_m(), AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll_p(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), SITL::Aircraft::smooth_sensors(), and AC_AttitudeControl::thrust_heading_rotation_angles().
to_euler()
void Quaternion::to_euler (float & roll, float & pitch, float & yaw) const
Definition at line 272 of file quaternion.cpp.
Referenced by NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), NavEKF2_core::getEulerAngles(), NavEKF3_core::getEulerAngles(), GCS_MAVLINK::handle_att_pos_mocap(), AC_AttitudeControl::inertial_frame_reset(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_2(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AC_AttitudeControl::relax_attitude_controllers(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), test_conversion(), test_quaternion(), and SITL::Vicon::update_vicon_position_estimate().
to_vector312()
Vector3f Quaternion::to_vector312 (void) const
Definition at line 280 of file quaternion.cpp.
Referenced by NavEKF2_core::fuseEulerYaw(), and NavEKF3_core::fuseEulerYaw().
Member Data Documentation
q1
float Quaternion::q1
Definition at line 28 of file quaternion.h.
Referenced by from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), NavEKF2::Log_Write_Quaternion(), NavEKF3::Log_Write_Quaternion(), normalize(), operator *(), operator *=(), operator()(), operator/(), operator[](), Quaternion(), rotate_fast(), rotation_matrix(), rotation_matrix_norm(), and to_axis_angle().
q2
float Quaternion::q2
Definition at line 28 of file quaternion.h.
Referenced by AC_AttitudeControl::attitude_controller_run_quat(), from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), NavEKF2::Log_Write_Quaternion(), NavEKF3::Log_Write_Quaternion(), normalize(), operator *(), operator *=(), operator()(), operator/(), Quaternion(), rotate_fast(), rotation_matrix(), rotation_matrix_norm(), and to_axis_angle().
q3
float Quaternion::q3
Definition at line 28 of file quaternion.h.
Referenced by AC_AttitudeControl::attitude_controller_run_quat(), from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), NavEKF2::Log_Write_Quaternion(), NavEKF3::Log_Write_Quaternion(), normalize(), operator *(), operator *=(), operator()(), operator/(), Quaternion(), rotate_fast(), rotation_matrix(), rotation_matrix_norm(), and to_axis_angle().
q4
float Quaternion::q4
Definition at line 28 of file quaternion.h.
Referenced by AC_AttitudeControl::attitude_controller_run_quat(), from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), NavEKF2::Log_Write_Quaternion(), NavEKF3::Log_Write_Quaternion(), normalize(), operator *(), operator *=(), operator()(), operator/(), Quaternion(), rotate_fast(), rotation_matrix(), rotation_matrix_norm(), and to_axis_angle().
The documentation for this class was generated from the following files:
libraries/AP_Math/quaternion.h
libraries/AP_Math/quaternion.cpp