APM:Libraries: AP_InertialSensor Class Reference
AP_InertialSensor Class Reference
#include <AP_InertialSensor.h>
Classes
class BatchSampler
struct PeakHoldState
Public Types
enum Gyro_Calibration_Timing { GYRO_CAL_NEVER = 0, GYRO_CAL_STARTUP_ONLY = 1 }
enum IMU_SENSOR_TYPE { IMU_SENSOR_TYPE_ACCEL = 0, IMU_SENSOR_TYPE_GYRO = 1 }
Public Member Functions
AP_InertialSensor ()
AP_InertialSensor (const AP_InertialSensor &other)=delete
AP_InertialSensor & operator= (const AP_InertialSensor &)=delete
void init (uint16_t sample_rate_hz)
uint8_t register_gyro (uint16_t raw_sample_rate_hz, uint32_t id)
uint8_t register_accel (uint16_t raw_sample_rate_hz, uint32_t id)
void periodic ()
bool calibrate_trim (float &trim_roll, float &trim_pitch)
bool calibrating () const
calibrating - returns true if the gyros or accels are currently being calibrated
void init_gyro (void)
const Vector3f & get_gyro (uint8_t i) const
const Vector3f & get_gyro (void) const
const Vector3f & get_gyro_offsets (uint8_t i) const
const Vector3f & get_gyro_offsets (void) const
bool get_delta_angle (uint8_t i, Vector3f &delta_angle) const
bool get_delta_angle (Vector3f &delta_angle) const
float get_delta_angle_dt (uint8_t i) const
float get_delta_angle_dt () const
bool get_delta_velocity (uint8_t i, Vector3f &delta_velocity) const
bool get_delta_velocity (Vector3f &delta_velocity) const
float get_delta_velocity_dt (uint8_t i) const
float get_delta_velocity_dt () const
const Vector3f & get_accel (uint8_t i) const
const Vector3f & get_accel (void) const
uint32_t get_gyro_error_count (uint8_t i) const
uint32_t get_accel_error_count (uint8_t i) const
bool get_gyro_health (uint8_t instance) const
bool get_gyro_health (void) const
bool get_gyro_health_all (void) const
uint8_t get_gyro_count (void) const
bool gyro_calibrated_ok (uint8_t instance) const
bool gyro_calibrated_ok_all () const
bool use_gyro (uint8_t instance) const
Gyro_Calibration_Timing gyro_calibration_timing ()
bool get_accel_health (uint8_t instance) const
bool get_accel_health (void) const
bool get_accel_health_all (void) const
uint8_t get_accel_count (void) const
bool accel_calibrated_ok_all () const
bool use_accel (uint8_t instance) const
uint16_t get_gyro_rate_hz (uint8_t instance) const
uint16_t get_accel_rate_hz (uint8_t instance) const
const Vector3f & get_accel_offsets (uint8_t i) const
const Vector3f & get_accel_offsets (void) const
const Vector3f & get_accel_scale (uint8_t i) const
const Vector3f & get_accel_scale (void) const
const Vector3f & get_imu_pos_offset (uint8_t instance) const
const Vector3f & get_imu_pos_offset (void) const
float get_temperature (uint8_t instance) const
float get_delta_time () const
float get_gyro_drift_rate (void) const
void update (void)
void wait_for_sample (void)
void set_board_orientation (enum Rotation orientation, Matrix3f *custom_rotation=nullptr)
uint16_t get_sample_rate (void) const
float get_loop_delta_t (void) const
bool healthy (void) const
uint8_t get_primary_accel (void) const
uint8_t get_primary_gyro (void) const
void set_hil_mode (void)
uint16_t get_gyro_filter_hz (void) const
uint16_t get_accel_filter_hz (void) const
void set_log_raw_bit (uint32_t log_raw_bit)
void calc_vibration_and_clipping (uint8_t instance, const Vector3f &accel, float dt)
Vector3f get_vibration_levels () const
Vector3f get_vibration_levels (uint8_t instance) const
uint32_t get_accel_clip_count (uint8_t instance) const
bool is_still ()
void set_accel (uint8_t instance, const Vector3f &accel)
void set_gyro (uint8_t instance, const Vector3f &gyro)
void set_delta_time (float delta_time)
void set_delta_velocity (uint8_t instance, float deltavt, const Vector3f &deltav)
void set_delta_angle (uint8_t instance, const Vector3f &deltaa, float deltaat)
AuxiliaryBus * get_auxiliary_bus (int16_t backend_id)
AuxiliaryBus * get_auxiliary_bus (int16_t backend_id, uint8_t instance)
void detect_backends (void)
void set_accel_peak_hold (uint8_t instance, const Vector3f &accel)
float get_accel_peak_hold_neg_x () const
AP_AccelCal * get_acal () const
bool get_fixed_mount_accel_cal_sample (uint8_t sample_num, Vector3f &ret) const
bool get_primary_accel_cal_sample_avg (uint8_t sample_num, Vector3f &ret) const
bool get_new_trim (float &trim_roll, float &trim_pitch)
void acal_init ()
void acal_update ()
MAV_RESULT simple_accel_cal ()
bool accel_cal_requires_reboot () const
uint32_t get_last_update_usec (void) const
void kill_imu (uint8_t imu_idx, bool kill_it)
Static Public Member Functions
static AP_InertialSensor * get_singleton ()
Public Attributes
BatchSampler batchsampler {*this}
float delta_time
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool _add_backend (AP_InertialSensor_Backend *backend)
void _start_backends ()
AP_InertialSensor_Backend * _find_backend (int16_t backend_id, uint8_t instance)
void _init_gyro ()
bool _calculate_trim (const Vector3f &accel_sample, float &trim_roll, float &trim_pitch)
void _save_gyro_calibration ()
void _acal_save_calibrations () override
void _acal_event_failure () override
AccelCalibrator * _acal_get_calibrator (uint8_t i) override
Private Attributes
AP_InertialSensor_Backend * _backends [INS_MAX_BACKENDS]
uint8_t _gyro_count
uint8_t _accel_count
uint8_t _backend_count
uint16_t _sample_rate
float _loop_delta_t
float _loop_delta_t_max
Vector3f _accel [INS_MAX_INSTANCES]
Vector3f _delta_velocity [INS_MAX_INSTANCES]
float _delta_velocity_dt [INS_MAX_INSTANCES]
bool _delta_velocity_valid [INS_MAX_INSTANCES]
Vector3f _delta_velocity_acc [INS_MAX_INSTANCES]
float _delta_velocity_acc_dt [INS_MAX_INSTANCES]
LowPassFilter2pVector3f _accel_filter [INS_MAX_INSTANCES]
LowPassFilter2pVector3f _gyro_filter [INS_MAX_INSTANCES]
Vector3f _accel_filtered [INS_MAX_INSTANCES]
Vector3f _gyro_filtered [INS_MAX_INSTANCES]
bool _new_accel_data [INS_MAX_INSTANCES]
bool _new_gyro_data [INS_MAX_INSTANCES]
NotchFilterParams _notch_filter
NotchFilterVector3f _gyro_notch_filter [INS_MAX_INSTANCES]
Vector3f _gyro [INS_MAX_INSTANCES]
Vector3f _delta_angle [INS_MAX_INSTANCES]
float _delta_angle_dt [INS_MAX_INSTANCES]
bool _delta_angle_valid [INS_MAX_INSTANCES]
float _delta_angle_acc_dt [INS_MAX_INSTANCES]
Vector3f _delta_angle_acc [INS_MAX_INSTANCES]
Vector3f _last_delta_angle [INS_MAX_INSTANCES]
Vector3f _last_raw_gyro [INS_MAX_INSTANCES]
uint8_t _accel_sensor_rate_sampling_enabled
uint8_t _gyro_sensor_rate_sampling_enabled
uint16_t _accel_raw_sampling_multiplier [INS_MAX_INSTANCES]
uint16_t _gyro_raw_sampling_multiplier [INS_MAX_INSTANCES]
AP_Int32 _accel_id [INS_MAX_INSTANCES]
AP_Int32 _gyro_id [INS_MAX_INSTANCES]
AP_Vector3f _accel_scale [INS_MAX_INSTANCES]
AP_Vector3f _accel_offset [INS_MAX_INSTANCES]
AP_Vector3f _gyro_offset [INS_MAX_INSTANCES]
AP_Vector3f _accel_pos [INS_MAX_INSTANCES]
float _accel_max_abs_offsets [INS_MAX_INSTANCES]
float _accel_raw_sample_rates [INS_MAX_INSTANCES]
float _gyro_raw_sample_rates [INS_MAX_INSTANCES]
uint8_t _accel_over_sampling [INS_MAX_INSTANCES]
uint8_t _gyro_over_sampling [INS_MAX_INSTANCES]
uint64_t _accel_last_sample_us [INS_MAX_INSTANCES]
uint64_t _gyro_last_sample_us [INS_MAX_INSTANCES]
uint16_t _sample_accel_count [INS_MAX_INSTANCES]
uint32_t _sample_accel_start_us [INS_MAX_INSTANCES]
uint16_t _sample_gyro_count [INS_MAX_INSTANCES]
uint32_t _sample_gyro_start_us [INS_MAX_INSTANCES]
float _temperature [INS_MAX_INSTANCES]
AP_Int16 _accel_filter_cutoff
AP_Int16 _gyro_filter_cutoff
AP_Int8 _gyro_cal_timing
AP_Int8 _use [INS_MAX_INSTANCES]
AP_Int8 _fast_sampling_mask
AP_Int8 _enable_mask
enum Rotation _board_orientation
Matrix3f * _custom_rotation
enum Rotation _gyro_orientation [INS_MAX_INSTANCES]
enum Rotation _accel_orientation [INS_MAX_INSTANCES]
bool _gyro_cal_ok [INS_MAX_INSTANCES]
bool _accel_id_ok [INS_MAX_INSTANCES]
uint8_t _primary_gyro
uint8_t _primary_accel
uint8_t _gyro_wait_mask
uint8_t _accel_wait_mask
uint32_t _log_raw_bit
bool _have_sample:1
bool _hil_mode:1
bool _calibrating:1
bool _backends_detected:1
float _delta_time
uint32_t _last_sample_usec
uint32_t _next_sample_usec
uint32_t _sample_period_usec
uint32_t _last_update_usec
bool _gyro_healthy [INS_MAX_INSTANCES]
bool _accel_healthy [INS_MAX_INSTANCES]
uint32_t _accel_error_count [INS_MAX_INSTANCES]
uint32_t _gyro_error_count [INS_MAX_INSTANCES]
uint32_t _accel_clip_count [INS_MAX_INSTANCES]
LowPassFilterVector3f _accel_vibe_floor_filter [INS_VIBRATION_CHECK_INSTANCES]
LowPassFilterVector3f _accel_vibe_filter [INS_VIBRATION_CHECK_INSTANCES]
struct AP_InertialSensor::PeakHoldState _peak_hold_state
AP_Float _still_threshold
struct {
float delta_time
} _hil
AP_Int8 _acc_body_aligned
AP_Int8 _trim_option
AP_AccelCal * _acal
AccelCalibrator * _accel_calibrator
float _trim_pitch
float _trim_roll
bool _new_trim
bool _accel_cal_requires_reboot
uint32_t _accel_startup_error_count [INS_MAX_INSTANCES]
uint32_t _gyro_startup_error_count [INS_MAX_INSTANCES]
bool _startup_error_counts_set
uint32_t _startup_ms
uint8_t imu_kill_mask
Static Private Attributes
static AP_InertialSensor * _singleton = nullptr
Friends
class AP_InertialSensor_Backend
Detailed Description
Definition at line 46 of file AP_InertialSensor.h.
Member Enumeration Documentation
Gyro_Calibration_Timing
enum AP_InertialSensor::Gyro_Calibration_Timing
Enumerator
GYRO_CAL_NEVER
GYRO_CAL_STARTUP_ONLY
Definition at line 59 of file AP_InertialSensor.h.
IMU_SENSOR_TYPE
enum AP_InertialSensor::IMU_SENSOR_TYPE
Enumerator
IMU_SENSOR_TYPE_ACCEL
IMU_SENSOR_TYPE_GYRO
Definition at line 280 of file AP_InertialSensor.h.
Constructor & Destructor Documentation
AP_InertialSensor() [1/2]
AP_InertialSensor::AP_InertialSensor ()
Definition at line 465 of file AP_InertialSensor.cpp.
Referenced by get_singleton().
AP_InertialSensor() [2/2]
AP_InertialSensor::AP_InertialSensor (const AP_InertialSensor & other) delete
Member Function Documentation
_acal_event_failure()
void AP_InertialSensor::_acal_event_failure () override private virtual
Reimplemented from AP_AccelCal_Client.
Definition at line 1807 of file AP_InertialSensor.cpp.
_acal_get_calibrator()
AccelCalibrator* AP_InertialSensor::_acal_get_calibrator (uint8_t i) inline override private virtual
Implements AP_AccelCal_Client.
Definition at line 577 of file AP_InertialSensor.h.
_acal_save_calibrations()
void AP_InertialSensor::_acal_save_calibrations () override private virtual
Implements AP_AccelCal_Client.
Definition at line 1743 of file AP_InertialSensor.cpp.
_add_backend()
bool AP_InertialSensor::_add_backend (AP_InertialSensor_Backend * backend) private
Definition at line 659 of file AP_InertialSensor.cpp.
Referenced by detect_backends().
_calculate_trim()
bool AP_InertialSensor::_calculate_trim (const Vector3f & accel_sample, float & trim_roll, float & trim_pitch) private
Definition at line 898 of file AP_InertialSensor.cpp.
Referenced by calibrate_trim().
_find_backend()
AP_InertialSensor_Backend * AP_InertialSensor::_find_backend (int16_t backend_id, uint8_t instance) private
Definition at line 596 of file AP_InertialSensor.cpp.
Referenced by get_auxiliary_bus().
_init_gyro()
void AP_InertialSensor::_init_gyro () private
Definition at line 1094 of file AP_InertialSensor.cpp.
Referenced by init_gyro().
_save_gyro_calibration()
void AP_InertialSensor::_save_gyro_calibration () private
Definition at line 1235 of file AP_InertialSensor.cpp.
Referenced by init_gyro().
_start_backends()
void AP_InertialSensor::_start_backends () private
Definition at line 573 of file AP_InertialSensor.cpp.
Referenced by init().
acal_init()
void AP_InertialSensor::acal_init ()
Definition at line 1714 of file AP_InertialSensor.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration().
acal_update()
void AP_InertialSensor::acal_update ()
Definition at line 1726 of file AP_InertialSensor.cpp.
accel_cal_requires_reboot()
bool AP_InertialSensor::accel_cal_requires_reboot () const inline
Definition at line 272 of file AP_InertialSensor.h.
Referenced by AP_Arming::ins_checks().
accel_calibrated_ok_all()
bool AP_InertialSensor::accel_calibrated_ok_all () const
Definition at line 1039 of file AP_InertialSensor.cpp.
Referenced by AP_Arming::ins_checks(), and GCS::update_sensor_status_flags().
calc_vibration_and_clipping()
void AP_InertialSensor::calc_vibration_and_clipping (uint8_t instance, const Vector3f & accel, float dt)
Definition at line 1647 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample().
calibrate_trim()
bool AP_InertialSensor::calibrate_trim (float & trim_roll, float & trim_pitch)
Definition at line 987 of file AP_InertialSensor.cpp.
calibrating()
bool AP_InertialSensor::calibrating () const inline
calibrating - returns true if the gyros or accels are currently being calibrated
Definition at line 85 of file AP_InertialSensor.h.
Referenced by GCS::update_sensor_status_flags().
detect_backends()
void AP_InertialSensor::detect_backends (void)
Definition at line 676 of file AP_InertialSensor.cpp.
Referenced by _start_backends(), get_auxiliary_bus(), and AP_Compass_AK8963::probe_mpu9250().
get_acal()
AP_AccelCal* AP_InertialSensor::get_acal () const inline
Definition at line 251 of file AP_InertialSensor.h.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration(), and GCS_MAVLINK::handle_command_ack().
get_accel() [1/2]
const Vector3f& AP_InertialSensor::get_accel (uint8_t i) const inline
Fetch the current accelerometer values
Returns
vector of current accelerations in m/s/s
Definition at line 123 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_YawController::get_servo_out(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Arming::ins_accels_consistent(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), AP_AHRS_DCM::reset(), run_test(), GCS_MAVLINK::send_raw_imu(), GCS_MAVLINK::send_scaled_imu(), SITL::Gimbal::update(), AP_TECS::update_50hz(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), AP_AHRS_NavEKF::update_SITL(), and AP_Logger::Write_IMU_instance().
get_accel() [2/2]
const Vector3f& AP_InertialSensor::get_accel (void) const inline
Definition at line 124 of file AP_InertialSensor.h.
Referenced by _init_gyro(), calibrate_trim(), get_accel(), get_delta_velocity(), and simple_accel_cal().
get_accel_clip_count()
uint32_t AP_InertialSensor::get_accel_clip_count (uint8_t instance) const
Definition at line 923 of file AP_InertialSensor.cpp.
Referenced by GCS_MAVLINK::send_vibration(), and AP_Logger::Write_Vibration().
get_accel_count()
uint8_t AP_InertialSensor::get_accel_count (void) const inline
Definition at line 142 of file AP_InertialSensor.h.
Referenced by _acal_get_calibrator(), _start_backends(), accel_calibrated_ok_all(), AP_AHRS_DCM::drift_correction(), get_accel_clip_count(), get_accel_health_all(), init(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), AP_Arming::ins_accels_consistent(), NavEKF2_core::readDeltaVelocity(), NavEKF3_core::readDeltaVelocity(), run_test(), GCS_MAVLINK::send_scaled_imu(), setup(), simple_accel_cal(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), AP_Logger::Write_IMU(), and AP_Logger::Write_IMUDT().
get_accel_error_count()
uint32_t AP_InertialSensor::get_accel_error_count (uint8_t i) const inline
Definition at line 127 of file AP_InertialSensor.h.
Referenced by AP_Logger::Write_IMU_instance().
get_accel_filter_hz()
uint16_t AP_InertialSensor::get_accel_filter_hz (void) const inline
Definition at line 212 of file AP_InertialSensor.h.
get_accel_health() [1/2]
bool AP_InertialSensor::get_accel_health (uint8_t instance) const inline
Definition at line 139 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction(), run_test(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_Logger::Write_IMU_instance().
get_accel_health() [2/2]
bool AP_InertialSensor::get_accel_health (void) const inline
Definition at line 140 of file AP_InertialSensor.h.
Referenced by calibrate_trim(), get_accel_health(), get_accel_health_all(), get_delta_velocity(), healthy(), and use_accel().
get_accel_health_all()
bool AP_InertialSensor::get_accel_health_all (void) const
Definition at line 971 of file AP_InertialSensor.cpp.
Referenced by AP_Arming::ins_checks(), and GCS::update_sensor_status_flags().
get_accel_offsets() [1/2]
const Vector3f& AP_InertialSensor::get_accel_offsets (uint8_t i) const inline
Definition at line 151 of file AP_InertialSensor.h.
Referenced by display_offsets_and_scaling(), and GCS_MAVLINK::send_sensor_offsets().
get_accel_offsets() [2/2]
const Vector3f& AP_InertialSensor::get_accel_offsets (void) const inline
Definition at line 152 of file AP_InertialSensor.h.
Referenced by get_accel_offsets().
get_accel_peak_hold_neg_x()
float AP_InertialSensor::get_accel_peak_hold_neg_x () const inline
Definition at line 248 of file AP_InertialSensor.h.
get_accel_rate_hz()
uint16_t AP_InertialSensor::get_accel_rate_hz (uint8_t instance) const inline
Definition at line 148 of file AP_InertialSensor.h.
Referenced by AP_Logger::Write_IMU_instance().
get_accel_scale() [1/2]
const Vector3f& AP_InertialSensor::get_accel_scale (uint8_t i) const inline
Definition at line 155 of file AP_InertialSensor.h.
Referenced by display_offsets_and_scaling().
get_accel_scale() [2/2]
const Vector3f& AP_InertialSensor::get_accel_scale (void) const inline
Definition at line 156 of file AP_InertialSensor.h.
Referenced by get_accel_scale().
get_auxiliary_bus() [1/2]
AuxiliaryBus* AP_InertialSensor::get_auxiliary_bus (int16_t backend_id) inline
Definition at line 241 of file AP_InertialSensor.h.
Referenced by AP_AK09916_BusDriver_Auxiliary::AP_AK09916_BusDriver_Auxiliary(), AP_AK8963_BusDriver_Auxiliary::AP_AK8963_BusDriver_Auxiliary(), and get_auxiliary_bus().
get_auxiliary_bus() [2/2]
AuxiliaryBus * AP_InertialSensor::get_auxiliary_bus (int16_t backend_id, uint8_t instance)
Definition at line 1634 of file AP_InertialSensor.cpp.
get_delta_angle() [1/2]
bool AP_InertialSensor::get_delta_angle (uint8_t i, Vector3f & delta_angle) const
Definition at line 1499 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::matrix_update(), NavEKF2_core::readDeltaAngle(), NavEKF3_core::readDeltaAngle(), and AP_Logger::Write_IMUDT_instance().
get_delta_angle() [2/2]
bool AP_InertialSensor::get_delta_angle (Vector3f & delta_angle) const inline
Definition at line 107 of file AP_InertialSensor.h.
Referenced by get_delta_angle().
get_delta_angle_dt() [1/2]
float AP_InertialSensor::get_delta_angle_dt (uint8_t i) const
Definition at line 1546 of file AP_InertialSensor.cpp.
Referenced by NavEKF2_core::readDeltaAngle(), NavEKF3_core::readIMUData(), and AP_Logger::Write_IMUDT_instance().
get_delta_angle_dt() [2/2]
float AP_InertialSensor::get_delta_angle_dt () const inline
Definition at line 110 of file AP_InertialSensor.h.
Referenced by get_delta_angle_dt().
get_delta_time()
float AP_InertialSensor::get_delta_time () const inline
Definition at line 173 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), get_delta_angle_dt(), get_delta_velocity(), get_delta_velocity_dt(), AP_AHRS_DCM::update(), and AP_Logger::Write_IMUDT_instance().
get_delta_velocity() [1/2]
bool AP_InertialSensor::get_delta_velocity (uint8_t i, Vector3f & delta_velocity) const
Definition at line 1516 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), AP_AHRS::getCorrectedDeltaVelocityNED(), NavEKF2_core::readDeltaVelocity(), NavEKF3_core::readDeltaVelocity(), and AP_Logger::Write_IMUDT_instance().
get_delta_velocity() [2/2]
bool AP_InertialSensor::get_delta_velocity (Vector3f & delta_velocity) const inline
Definition at line 114 of file AP_InertialSensor.h.
Referenced by get_delta_velocity().
get_delta_velocity_dt() [1/2]
float AP_InertialSensor::get_delta_velocity_dt (uint8_t i) const
Definition at line 1531 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), AP_AHRS::getCorrectedDeltaVelocityNED(), NavEKF2_core::readDeltaVelocity(), NavEKF3_core::readDeltaVelocity(), and AP_Logger::Write_IMUDT_instance().
get_delta_velocity_dt() [2/2]
float AP_InertialSensor::get_delta_velocity_dt () const inline
Definition at line 117 of file AP_InertialSensor.h.
Referenced by get_delta_velocity_dt().
get_fixed_mount_accel_cal_sample()
bool AP_InertialSensor::get_fixed_mount_accel_cal_sample (uint8_t sample_num, Vector3f & ret) const
Definition at line 1832 of file AP_InertialSensor.cpp.
Referenced by _acal_save_calibrations().
get_gyro() [1/2]
const Vector3f& AP_InertialSensor::get_gyro (uint8_t i) const inline
Fetch the current gyro values
Returns
vector of rotational rates in radians/sec
Definition at line 98 of file AP_InertialSensor.h.
Referenced by NavEKF2_core::detectOptFlowTakeoff(), NavEKF3_core::detectOptFlowTakeoff(), AP_AHRS::get_gyro_latest(), AP_Arming::ins_gyros_consistent(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), run_test(), GCS_MAVLINK::send_raw_imu(), GCS_MAVLINK::send_scaled_imu(), SITL::Gimbal::update(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), AP_AHRS_NavEKF::update_SITL(), and AP_Logger::Write_IMU_instance().
get_gyro() [2/2]
const Vector3f& AP_InertialSensor::get_gyro (void) const inline
Definition at line 99 of file AP_InertialSensor.h.
Referenced by _init_gyro(), get_delta_angle(), and get_gyro().
get_gyro_count()
uint8_t AP_InertialSensor::get_gyro_count (void) const inline
Definition at line 133 of file AP_InertialSensor.h.
Referenced by _init_gyro(), _start_backends(), get_gyro_health_all(), gyro_calibrated_ok_all(), AP_Arming::ins_gyros_consistent(), AP_AHRS_DCM::matrix_update(), NavEKF2_core::readDeltaAngle(), NavEKF3_core::readDeltaAngle(), run_test(), setup(), AP_Logger::Write_IMU(), and AP_Logger::Write_IMUDT().
get_gyro_drift_rate()
float AP_InertialSensor::get_gyro_drift_rate (void) const inline
Definition at line 177 of file AP_InertialSensor.h.
Referenced by AP_AHRS::AP_AHRS().
get_gyro_error_count()
uint32_t AP_InertialSensor::get_gyro_error_count (uint8_t i) const inline
Definition at line 126 of file AP_InertialSensor.h.
Referenced by AP_Logger::Write_IMU_instance().
get_gyro_filter_hz()
uint16_t AP_InertialSensor::get_gyro_filter_hz (void) const inline
Definition at line 209 of file AP_InertialSensor.h.
get_gyro_health() [1/2]
bool AP_InertialSensor::get_gyro_health (uint8_t instance) const inline
Definition at line 130 of file AP_InertialSensor.h.
Referenced by run_test(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), and AP_Logger::Write_IMU_instance().
get_gyro_health() [2/2]
bool AP_InertialSensor::get_gyro_health (void) const inline
Definition at line 131 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), get_gyro_health(), get_gyro_health_all(), healthy(), and use_gyro().
get_gyro_health_all()
bool AP_InertialSensor::get_gyro_health_all (void) const
Definition at line 932 of file AP_InertialSensor.cpp.
Referenced by AP_Arming::ins_checks(), and GCS::update_sensor_status_flags().
get_gyro_offsets() [1/2]
const Vector3f& AP_InertialSensor::get_gyro_offsets (uint8_t i) const inline
Definition at line 102 of file AP_InertialSensor.h.
Referenced by display_offsets_and_scaling(), and GCS_MAVLINK::send_sensor_offsets().
get_gyro_offsets() [2/2]
const Vector3f& AP_InertialSensor::get_gyro_offsets (void) const inline
Definition at line 103 of file AP_InertialSensor.h.
Referenced by get_gyro_offsets().
get_gyro_rate_hz()
uint16_t AP_InertialSensor::get_gyro_rate_hz (uint8_t instance) const inline
Definition at line 147 of file AP_InertialSensor.h.
Referenced by AP_Logger::Write_IMU_instance().
get_imu_pos_offset() [1/2]
const Vector3f& AP_InertialSensor::get_imu_pos_offset (uint8_t instance) const inline
Definition at line 159 of file AP_InertialSensor.h.
Referenced by AC_PrecLand::construct_pos_meas_using_rangefinder(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), and AC_PrecLand::run_output_prediction().
get_imu_pos_offset() [2/2]
const Vector3f& AP_InertialSensor::get_imu_pos_offset (void) const inline
Definition at line 162 of file AP_InertialSensor.h.
get_last_update_usec()
uint32_t AP_InertialSensor::get_last_update_usec (void) const inline
Definition at line 275 of file AP_InertialSensor.h.
Referenced by NavEKF3::UpdateFilter(), and NavEKF2::UpdateFilter().
get_loop_delta_t()
float AP_InertialSensor::get_loop_delta_t (void) const inline
Definition at line 198 of file AP_InertialSensor.h.
Referenced by NavEKF2_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
get_new_trim()
bool AP_InertialSensor::get_new_trim (float & trim_roll, float & trim_pitch)
Definition at line 1818 of file AP_InertialSensor.cpp.
get_primary_accel()
uint8_t AP_InertialSensor::get_primary_accel (void) const inline
Definition at line 202 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS::get_primary_accel_index(), AP_AHRS_NavEKF::get_primary_accel_index(), AP_AHRS_NavEKF::get_primary_IMU_index(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
get_primary_accel_cal_sample_avg()
bool AP_InertialSensor::get_primary_accel_cal_sample_avg (uint8_t sample_num, Vector3f & ret) const
Definition at line 1849 of file AP_InertialSensor.cpp.
Referenced by _acal_save_calibrations().
get_primary_gyro()
uint8_t AP_InertialSensor::get_primary_gyro (void) const inline
Definition at line 203 of file AP_InertialSensor.h.
Referenced by AP_AHRS::get_primary_gyro_index(), AP_AHRS_NavEKF::get_primary_gyro_index(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
get_sample_rate()
uint16_t AP_InertialSensor::get_sample_rate (void) const inline
Definition at line 195 of file AP_InertialSensor.h.
Referenced by calibrate_trim(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), and NavEKF3_core::setup_core().
get_singleton()
AP_InertialSensor * AP_InertialSensor::get_singleton (void) static
Definition at line 489 of file AP_InertialSensor.cpp.
Referenced by HALSITL::SITL_State::_sitl_setup(), AP::ins(), and AP_Compass_AK8963::probe_mpu9250().
get_temperature()
float AP_InertialSensor::get_temperature (uint8_t instance) const inline
Definition at line 168 of file AP_InertialSensor.h.
Referenced by run_test(), and AP_Logger::Write_IMU_instance().
get_vibration_levels() [1/2]
Vector3f AP_InertialSensor::get_vibration_levels () const inline
Definition at line 221 of file AP_InertialSensor.h.
Referenced by get_vibration_levels(), is_still(), GCS_MAVLINK::send_vibration(), and AP_Logger::Write_Vibration().
get_vibration_levels() [2/2]
Vector3f AP_InertialSensor::get_vibration_levels (uint8_t instance) const
Definition at line 1691 of file AP_InertialSensor.cpp.
gyro_calibrated_ok()
bool AP_InertialSensor::gyro_calibrated_ok (uint8_t instance) const inline
Definition at line 134 of file AP_InertialSensor.h.
Referenced by gyro_calibrated_ok_all().
gyro_calibrated_ok_all()
bool AP_InertialSensor::gyro_calibrated_ok_all () const
Definition at line 944 of file AP_InertialSensor.cpp.
Referenced by AP_Arming::ins_checks(), and GCS::update_sensor_status_flags().
gyro_calibration_timing()
AP_InertialSensor::Gyro_Calibration_Timing AP_InertialSensor::gyro_calibration_timing ()
Definition at line 2040 of file AP_InertialSensor.cpp.
Referenced by init().
healthy()
bool AP_InertialSensor::healthy (void) const inline
Definition at line 200 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction().
init()
void AP_InertialSensor::init (uint16_t sample_rate_hz)
Perform startup initialisation.
Called to initialise the state of the IMU.
Gyros will be calibrated unless INS_GYRO_CAL is zero
Parameters
style The initialisation startup style.
Definition at line 619 of file AP_InertialSensor.cpp.
Referenced by setup(), and SchedTest::setup().
init_gyro()
void AP_InertialSensor::init_gyro (void)
Perform cold-start initialisation for just the gyros.
Note
This should not be called unless ::init has previously been called, as ::init may perform other work
Definition at line 914 of file AP_InertialSensor.cpp.
Referenced by GCS_MAVLINK::calibrate_gyros(), and init().
is_still()
bool AP_InertialSensor::is_still ()
Definition at line 1704 of file AP_InertialSensor.cpp.
Referenced by AP_TempCalibration::learn_calibration().
kill_imu()
void AP_InertialSensor::kill_imu (uint8_t imu_idx, bool kill_it)
Definition at line 2052 of file AP_InertialSensor.cpp.
Referenced by RC_Channel::do_aux_function().
operator=()
AP_InertialSensor& AP_InertialSensor::operator= (const AP_InertialSensor &) delete
periodic()
void AP_InertialSensor::periodic ()
Definition at line 887 of file AP_InertialSensor.cpp.
register_accel()
uint8_t AP_InertialSensor::register_accel (uint16_t raw_sample_rate_hz, uint32_t id)
Definition at line 534 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_HIL::_init_sensor(), AP_InertialSensor_SITL::init_sensor(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_LSM9DS1::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_RST::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensense::start().
register_gyro()
uint8_t AP_InertialSensor::register_gyro (uint16_t raw_sample_rate_hz, uint32_t id)
Register a new gyro/accel driver, allocating an instance number
Definition at line 500 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_HIL::_init_sensor(), AP_InertialSensor_SITL::init_sensor(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_LSM9DS1::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_RST::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensense::start().
set_accel()
void AP_InertialSensor::set_accel (uint8_t instance, const Vector3f & accel)
Definition at line 1562 of file AP_InertialSensor.cpp.
set_accel_peak_hold()
void AP_InertialSensor::set_accel_peak_hold (uint8_t instance, const Vector3f & accel)
Definition at line 1674 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample().
set_board_orientation()
void AP_InertialSensor::set_board_orientation (enum Rotation orientation, Matrix3f * custom_rotation = nullptr) inline
Definition at line 189 of file AP_InertialSensor.h.
Referenced by AP_AHRS::update_orientation().
set_delta_angle()
void AP_InertialSensor::set_delta_angle (uint8_t instance, const Vector3f & deltaa, float deltaat)
Definition at line 1622 of file AP_InertialSensor.cpp.
set_delta_time()
void AP_InertialSensor::set_delta_time (float delta_time)
Definition at line 1602 of file AP_InertialSensor.cpp.
set_delta_velocity()
void AP_InertialSensor::set_delta_velocity (uint8_t instance, float deltavt, const Vector3f & deltav)
Definition at line 1610 of file AP_InertialSensor.cpp.
set_gyro()
void AP_InertialSensor::set_gyro (uint8_t instance, const Vector3f & gyro)
Definition at line 1580 of file AP_InertialSensor.cpp.
set_hil_mode()
void AP_InertialSensor::set_hil_mode (void) inline
Definition at line 206 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_HIL::_init_sensor().
set_log_raw_bit()
void AP_InertialSensor::set_log_raw_bit (uint32_t log_raw_bit) inline
Definition at line 215 of file AP_InertialSensor.h.
simple_accel_cal()
MAV_RESULT AP_InertialSensor::simple_accel_cal ()
Definition at line 1878 of file AP_InertialSensor.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration().
update()
void AP_InertialSensor::update (void)
Definition at line 1251 of file AP_InertialSensor.cpp.
Referenced by _init_gyro(), calibrate_trim(), SchedTest::ins_update(), AP_AHRS_DCM::reset(), run_test(), simple_accel_cal(), and AP_AHRS_DCM::update().
use_accel()
bool AP_InertialSensor::use_accel (uint8_t instance) const
Definition at line 1084 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), AP_Arming::ins_accels_consistent(), kill_imu(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
use_gyro()
bool AP_InertialSensor::use_gyro (uint8_t instance) const
Definition at line 961 of file AP_InertialSensor.cpp.
Referenced by NavEKF2_core::detectOptFlowTakeoff(), NavEKF3_core::detectOptFlowTakeoff(), AP_Arming::ins_gyros_consistent(), kill_imu(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), AP_AHRS_DCM::matrix_update(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), and AP_Logger::Write_IMUDT().
wait_for_sample()
void AP_InertialSensor::wait_for_sample (void)
Definition at line 1358 of file AP_InertialSensor.cpp.
Referenced by calibrate_trim(), AP_Scheduler::loop(), AP_AHRS_DCM::reset(), run_test(), and update().
Friends And Related Function Documentation
AP_InertialSensor_Backend
friend class AP_InertialSensor_Backend friend
Definition at line 48 of file AP_InertialSensor.h.
Member Data Documentation
_acal
AP_AccelCal* AP_InertialSensor::_acal private
Definition at line 568 of file AP_InertialSensor.h.
Referenced by acal_init(), acal_update(), and get_acal().
_acc_body_aligned
AP_Int8 AP_InertialSensor::_acc_body_aligned private
Definition at line 564 of file AP_InertialSensor.h.
Referenced by get_fixed_mount_accel_cal_sample().
_accel
Vector3f AP_InertialSensor::_accel[INS_MAX_INSTANCES] private
Definition at line 393 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_accel(), and set_accel().
_accel_cal_requires_reboot
bool AP_InertialSensor::_accel_cal_requires_reboot private
Definition at line 583 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and accel_cal_requires_reboot().
_accel_calibrator
AccelCalibrator* AP_InertialSensor::_accel_calibrator private
Definition at line 570 of file AP_InertialSensor.h.
Referenced by _acal_get_calibrator(), _acal_save_calibrations(), AP_InertialSensor_Backend::_publish_accel(), acal_init(), get_fixed_mount_accel_cal_sample(), and get_primary_accel_cal_sample_avg().
_accel_clip_count
uint32_t AP_InertialSensor::_accel_clip_count[INS_MAX_INSTANCES] private
Definition at line 543 of file AP_InertialSensor.h.
Referenced by calc_vibration_and_clipping(), get_accel_clip_count(), and AP_InertialSensor_Backend::increment_clip_count().
_accel_count
uint8_t AP_InertialSensor::_accel_count private
Definition at line 384 of file AP_InertialSensor.h.
Referenced by _acal_event_failure(), _acal_save_calibrations(), _start_backends(), get_accel_count(), get_accel_health(), get_fixed_mount_accel_cal_sample(), get_primary_accel_cal_sample_avg(), init(), kill_imu(), register_accel(), AP_InertialSensor::BatchSampler::rotate_to_next_sensor(), set_accel(), and wait_for_sample().
_accel_error_count
uint32_t AP_InertialSensor::_accel_error_count[INS_MAX_INSTANCES] private
Definition at line 539 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_inc_accel_error_count(), AP_InertialSensor_Backend::_set_accel_error_count(), get_accel_error_count(), and update().
_accel_filter
LowPassFilter2pVector3f AP_InertialSensor::_accel_filter[INS_MAX_INSTANCES] private
Definition at line 403 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::update_accel().
_accel_filter_cutoff
AP_Int16 AP_InertialSensor::_accel_filter_cutoff private
Definition at line 472 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_accel_filter_cutoff(), and get_accel_filter_hz().
_accel_filtered
Vector3f AP_InertialSensor::_accel_filtered[INS_MAX_INSTANCES] private
Definition at line 405 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::update_accel().
_accel_healthy
bool AP_InertialSensor::_accel_healthy[INS_MAX_INSTANCES] private
Definition at line 537 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_accel_health(), set_accel(), set_gyro(), and update().
_accel_id
AP_Int32 AP_InertialSensor::_accel_id[INS_MAX_INSTANCES] private
Definition at line 435 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), _start_backends(), accel_calibrated_ok_all(), register_accel(), and simple_accel_cal().
_accel_id_ok
bool AP_InertialSensor::_accel_id_ok[INS_MAX_INSTANCES] private
Definition at line 495 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), accel_calibrated_ok_all(), register_accel(), and simple_accel_cal().
_accel_last_sample_us
uint64_t AP_InertialSensor::_accel_last_sample_us[INS_MAX_INSTANCES] private
Definition at line 459 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample().
_accel_max_abs_offsets
float AP_InertialSensor::_accel_max_abs_offsets[INS_MAX_INSTANCES] private
Definition at line 447 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_accel_max_abs_offset(), and AP_InertialSensor().
_accel_offset
AP_Vector3f AP_InertialSensor::_accel_offset[INS_MAX_INSTANCES] private
Definition at line 440 of file AP_InertialSensor.h.
Referenced by _acal_event_failure(), _acal_save_calibrations(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_rotate_and_correct_accel(), accel_calibrated_ok_all(), get_accel_offsets(), and simple_accel_cal().
_accel_orientation
enum Rotation AP_InertialSensor::_accel_orientation[INS_MAX_INSTANCES] private
Definition at line 491 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_rotate_and_correct_accel(), and AP_InertialSensor_Backend::set_accel_orientation().
_accel_over_sampling
uint8_t AP_InertialSensor::_accel_over_sampling[INS_MAX_INSTANCES] private
Definition at line 454 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_accel_oversampling(), get_accel_rate_hz(), AP_InertialSensor::BatchSampler::push_data_to_log(), and register_accel().
_accel_pos
AP_Vector3f AP_InertialSensor::_accel_pos[INS_MAX_INSTANCES] private
Definition at line 444 of file AP_InertialSensor.h.
Referenced by get_imu_pos_offset().
_accel_raw_sample_rates
float AP_InertialSensor::_accel_raw_sample_rates[INS_MAX_INSTANCES] private
Definition at line 450 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_accel_raw_sample_rate(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_set_accel_raw_sample_rate(), get_accel_rate_hz(), AP_InertialSensor::BatchSampler::push_data_to_log(), and register_accel().
_accel_raw_sampling_multiplier
uint16_t AP_InertialSensor::_accel_raw_sampling_multiplier[INS_MAX_INSTANCES] private
Definition at line 430 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_raw_sample_accel_multiplier(), register_accel(), and AP_InertialSensor::BatchSampler::rotate_to_next_sensor().
_accel_scale
AP_Vector3f AP_InertialSensor::_accel_scale[INS_MAX_INSTANCES] private
Definition at line 439 of file AP_InertialSensor.h.
Referenced by _acal_event_failure(), _acal_save_calibrations(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_rotate_and_correct_accel(), accel_calibrated_ok_all(), get_accel_scale(), init(), and simple_accel_cal().
_accel_sensor_rate_sampling_enabled
uint8_t AP_InertialSensor::_accel_sensor_rate_sampling_enabled private
Definition at line 426 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_accel_sensor_rate_sampling_enabled(), and AP_InertialSensor::BatchSampler::update_doing_sensor_rate_logging().
_accel_startup_error_count
uint32_t AP_InertialSensor::_accel_startup_error_count[INS_MAX_INSTANCES] private
Definition at line 586 of file AP_InertialSensor.h.
Referenced by update().
_accel_vibe_filter
LowPassFilterVector3f AP_InertialSensor::_accel_vibe_filter[INS_VIBRATION_CHECK_INSTANCES] private
Definition at line 545 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), calc_vibration_and_clipping(), and get_vibration_levels().
_accel_vibe_floor_filter
LowPassFilterVector3f AP_InertialSensor::_accel_vibe_floor_filter[INS_VIBRATION_CHECK_INSTANCES] private
Definition at line 544 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), and calc_vibration_and_clipping().
_accel_wait_mask
uint8_t AP_InertialSensor::_accel_wait_mask private
Definition at line 504 of file AP_InertialSensor.h.
Referenced by wait_for_sample().
_backend_count
uint8_t AP_InertialSensor::_backend_count private
Definition at line 385 of file AP_InertialSensor.h.
Referenced by _add_backend(), _find_backend(), _start_backends(), detect_backends(), update(), and wait_for_sample().
_backends
AP_InertialSensor_Backend* AP_InertialSensor::_backends[INS_MAX_BACKENDS] private
Definition at line 378 of file AP_InertialSensor.h.
Referenced by _add_backend(), _find_backend(), _start_backends(), calc_vibration_and_clipping(), update(), and wait_for_sample().
_backends_detected
bool AP_InertialSensor::_backends_detected private
Definition at line 518 of file AP_InertialSensor.h.
Referenced by _find_backend(), and detect_backends().
_board_orientation
enum Rotation AP_InertialSensor::_board_orientation private
Definition at line 486 of file AP_InertialSensor.h.
Referenced by _init_gyro(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_rotate_and_correct_accel(), AP_InertialSensor_Backend::_rotate_and_correct_gyro(), get_fixed_mount_accel_cal_sample(), get_primary_accel_cal_sample_avg(), set_board_orientation(), and simple_accel_cal().
_calibrating
bool AP_InertialSensor::_calibrating private
Definition at line 516 of file AP_InertialSensor.h.
Referenced by _init_gyro(), calibrate_trim(), calibrating(), and simple_accel_cal().
_custom_rotation
Matrix3f* AP_InertialSensor::_custom_rotation private
Definition at line 487 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_rotate_and_correct_accel(), AP_InertialSensor_Backend::_rotate_and_correct_gyro(), get_fixed_mount_accel_cal_sample(), get_primary_accel_cal_sample_avg(), and set_board_orientation().
_delta_angle
Vector3f AP_InertialSensor::_delta_angle[INS_MAX_INSTANCES] private
Definition at line 416 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_delta_angle(), and set_delta_angle().
_delta_angle_acc
Vector3f AP_InertialSensor::_delta_angle_acc[INS_MAX_INSTANCES] private
Definition at line 421 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_publish_gyro(), and update().
_delta_angle_acc_dt
float AP_InertialSensor::_delta_angle_acc_dt[INS_MAX_INSTANCES] private
Definition at line 420 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_publish_gyro(), and update().
_delta_angle_dt
float AP_InertialSensor::_delta_angle_dt[INS_MAX_INSTANCES] private
Definition at line 417 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_delta_angle_dt(), and set_delta_angle().
_delta_angle_valid
bool AP_InertialSensor::_delta_angle_valid[INS_MAX_INSTANCES] private
Definition at line 418 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_delta_angle(), get_delta_angle_dt(), set_delta_angle(), and update().
_delta_time
float AP_InertialSensor::_delta_time private
Definition at line 521 of file AP_InertialSensor.h.
Referenced by get_delta_time(), init(), and wait_for_sample().
_delta_velocity
Vector3f AP_InertialSensor::_delta_velocity[INS_MAX_INSTANCES] private
Definition at line 394 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_delta_velocity(), and set_delta_velocity().
_delta_velocity_acc
Vector3f AP_InertialSensor::_delta_velocity_acc[INS_MAX_INSTANCES] private
Definition at line 398 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_publish_accel(), and update().
_delta_velocity_acc_dt
float AP_InertialSensor::_delta_velocity_acc_dt[INS_MAX_INSTANCES] private
Definition at line 400 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_publish_accel(), and update().
_delta_velocity_dt
float AP_InertialSensor::_delta_velocity_dt[INS_MAX_INSTANCES] private
Definition at line 395 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_delta_velocity_dt(), and set_delta_velocity().
_delta_velocity_valid
bool AP_InertialSensor::_delta_velocity_valid[INS_MAX_INSTANCES] private
Definition at line 396 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_delta_velocity(), get_delta_velocity_dt(), set_delta_velocity(), and update().
_enable_mask
AP_Int8 AP_InertialSensor::_enable_mask private
Definition at line 483 of file AP_InertialSensor.h.
Referenced by detect_backends().
_fast_sampling_mask
AP_Int8 AP_InertialSensor::_fast_sampling_mask private
Definition at line 480 of file AP_InertialSensor.h.
Referenced by detect_backends(), and AP_InertialSensor_Backend::enable_fast_sampling().
_gyro
Vector3f AP_InertialSensor::_gyro[INS_MAX_INSTANCES] private
Definition at line 415 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_gyro(), and set_gyro().
_gyro_cal_ok
bool AP_InertialSensor::_gyro_cal_ok[INS_MAX_INSTANCES] private
Definition at line 494 of file AP_InertialSensor.h.
Referenced by _init_gyro(), AP_InertialSensor(), gyro_calibrated_ok(), register_gyro(), and set_gyro().
_gyro_cal_timing
AP_Int8 AP_InertialSensor::_gyro_cal_timing private
Definition at line 474 of file AP_InertialSensor.h.
Referenced by gyro_calibration_timing().
_gyro_count
uint8_t AP_InertialSensor::_gyro_count private
Definition at line 383 of file AP_InertialSensor.h.
Referenced by _save_gyro_calibration(), _start_backends(), get_gyro_count(), get_gyro_health(), init(), kill_imu(), register_gyro(), AP_InertialSensor::BatchSampler::rotate_to_next_sensor(), set_gyro(), and wait_for_sample().
_gyro_error_count
uint32_t AP_InertialSensor::_gyro_error_count[INS_MAX_INSTANCES] private
Definition at line 540 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_inc_gyro_error_count(), AP_InertialSensor_Backend::_set_gyro_error_count(), get_gyro_error_count(), and update().
_gyro_filter
LowPassFilter2pVector3f AP_InertialSensor::_gyro_filter[INS_MAX_INSTANCES] private
Definition at line 404 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::update_gyro().
_gyro_filter_cutoff
AP_Int16 AP_InertialSensor::_gyro_filter_cutoff private
Definition at line 473 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_gyro_filter_cutoff(), and get_gyro_filter_hz().
_gyro_filtered
Vector3f AP_InertialSensor::_gyro_filtered[INS_MAX_INSTANCES] private
Definition at line 406 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::update_gyro().
_gyro_healthy
bool AP_InertialSensor::_gyro_healthy[INS_MAX_INSTANCES] private
Definition at line 536 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_gyro_health(), set_gyro(), and update().
_gyro_id
AP_Int32 AP_InertialSensor::_gyro_id[INS_MAX_INSTANCES] private
Definition at line 436 of file AP_InertialSensor.h.
Referenced by _save_gyro_calibration(), _start_backends(), gyro_calibrated_ok_all(), and register_gyro().
_gyro_last_sample_us
uint64_t AP_InertialSensor::_gyro_last_sample_us[INS_MAX_INSTANCES] private
Definition at line 460 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample().
_gyro_notch_filter
NotchFilterVector3f AP_InertialSensor::_gyro_notch_filter[INS_MAX_INSTANCES] private
Definition at line 412 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::update_gyro().
_gyro_offset
AP_Vector3f AP_InertialSensor::_gyro_offset[INS_MAX_INSTANCES] private
Definition at line 441 of file AP_InertialSensor.h.
Referenced by _init_gyro(), AP_InertialSensor_Backend::_rotate_and_correct_gyro(), _save_gyro_calibration(), and get_gyro_offsets().
_gyro_orientation
enum Rotation AP_InertialSensor::_gyro_orientation[INS_MAX_INSTANCES] private
Definition at line 490 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_rotate_and_correct_gyro(), and AP_InertialSensor_Backend::set_gyro_orientation().
_gyro_over_sampling
uint8_t AP_InertialSensor::_gyro_over_sampling[INS_MAX_INSTANCES] private
Definition at line 455 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_gyro_oversampling(), get_gyro_rate_hz(), AP_InertialSensor::BatchSampler::push_data_to_log(), and register_gyro().
_gyro_raw_sample_rates
float AP_InertialSensor::_gyro_raw_sample_rates[INS_MAX_INSTANCES] private
Definition at line 451 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_gyro_raw_sample_rate(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_set_gyro_raw_sample_rate(), get_gyro_rate_hz(), AP_InertialSensor::BatchSampler::push_data_to_log(), and register_gyro().
_gyro_raw_sampling_multiplier
uint16_t AP_InertialSensor::_gyro_raw_sampling_multiplier[INS_MAX_INSTANCES] private
Definition at line 431 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_raw_sampl_gyro_multiplier(), register_gyro(), and AP_InertialSensor::BatchSampler::rotate_to_next_sensor().
_gyro_sensor_rate_sampling_enabled
uint8_t AP_InertialSensor::_gyro_sensor_rate_sampling_enabled private
Definition at line 427 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_gyro_sensor_rate_sampling_enabled(), and AP_InertialSensor::BatchSampler::update_doing_sensor_rate_logging().
_gyro_startup_error_count
uint32_t AP_InertialSensor::_gyro_startup_error_count[INS_MAX_INSTANCES] private
Definition at line 587 of file AP_InertialSensor.h.
Referenced by update().
_gyro_wait_mask
uint8_t AP_InertialSensor::_gyro_wait_mask private
Definition at line 503 of file AP_InertialSensor.h.
Referenced by wait_for_sample().
_have_sample
bool AP_InertialSensor::_have_sample private
Definition at line 510 of file AP_InertialSensor.h.
Referenced by init(), update(), and wait_for_sample().
_hil
struct { ... } AP_InertialSensor::_hil
Referenced by set_delta_time(), and wait_for_sample().
_hil_mode
bool AP_InertialSensor::_hil_mode private
Definition at line 513 of file AP_InertialSensor.h.
Referenced by accel_calibrated_ok_all(), detect_backends(), set_hil_mode(), update(), and wait_for_sample().
_last_delta_angle
Vector3f AP_InertialSensor::_last_delta_angle[INS_MAX_INSTANCES] private
Definition at line 422 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample().
_last_raw_gyro
Vector3f AP_InertialSensor::_last_raw_gyro[INS_MAX_INSTANCES] private
Definition at line 423 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample().
_last_sample_usec
uint32_t AP_InertialSensor::_last_sample_usec private
Definition at line 524 of file AP_InertialSensor.h.
Referenced by init(), and wait_for_sample().
_last_update_usec
uint32_t AP_InertialSensor::_last_update_usec private
Definition at line 533 of file AP_InertialSensor.h.
Referenced by get_last_update_usec(), and update().
_log_raw_bit
uint32_t AP_InertialSensor::_log_raw_bit private
Definition at line 507 of file AP_InertialSensor.h.
Referenced by set_log_raw_bit(), and AP_InertialSensor_Backend::should_log_imu_raw().
_loop_delta_t
float AP_InertialSensor::_loop_delta_t private
Definition at line 389 of file AP_InertialSensor.h.
Referenced by get_loop_delta_t(), and init().
_loop_delta_t_max
float AP_InertialSensor::_loop_delta_t_max private
Definition at line 390 of file AP_InertialSensor.h.
Referenced by get_delta_angle_dt(), get_delta_time(), get_delta_velocity_dt(), and init().
_new_accel_data
bool AP_InertialSensor::_new_accel_data[INS_MAX_INSTANCES] private
Definition at line 407 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::update_accel(), and wait_for_sample().
_new_gyro_data
bool AP_InertialSensor::_new_gyro_data[INS_MAX_INSTANCES] private
Definition at line 408 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::update_gyro(), and wait_for_sample().
_new_trim
bool AP_InertialSensor::_new_trim private
Definition at line 581 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and get_new_trim().
_next_sample_usec
uint32_t AP_InertialSensor::_next_sample_usec private
Definition at line 527 of file AP_InertialSensor.h.
Referenced by init(), and wait_for_sample().
_notch_filter
NotchFilterParams AP_InertialSensor::_notch_filter private
Definition at line 411 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_gyro_notch_attenuation_dB(), AP_InertialSensor_Backend::_gyro_notch_bandwidth_hz(), AP_InertialSensor_Backend::_gyro_notch_center_freq_hz(), and AP_InertialSensor_Backend::_gyro_notch_enabled().
_peak_hold_state
struct AP_InertialSensor::PeakHoldState AP_InertialSensor::_peak_hold_state private
Referenced by get_accel_peak_hold_neg_x(), and set_accel_peak_hold().
_primary_accel
uint8_t AP_InertialSensor::_primary_accel private
Definition at line 499 of file AP_InertialSensor.h.
Referenced by get_accel(), get_accel_health(), get_accel_offsets(), get_accel_scale(), get_delta_angle_dt(), get_delta_velocity(), get_delta_velocity_dt(), get_imu_pos_offset(), get_primary_accel(), get_vibration_levels(), set_accel(), set_accel_peak_hold(), set_gyro(), and update().
_primary_gyro
uint8_t AP_InertialSensor::_primary_gyro private
Definition at line 498 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), get_gyro(), get_gyro_health(), get_gyro_offsets(), get_primary_gyro(), and update().
_sample_accel_count
uint16_t AP_InertialSensor::_sample_accel_count[INS_MAX_INSTANCES] private
Definition at line 463 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::notify_accel_fifo_reset().
_sample_accel_start_us
uint32_t AP_InertialSensor::_sample_accel_start_us[INS_MAX_INSTANCES] private
Definition at line 464 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::notify_accel_fifo_reset().
_sample_gyro_count
uint16_t AP_InertialSensor::_sample_gyro_count[INS_MAX_INSTANCES] private
Definition at line 465 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::notify_gyro_fifo_reset().
_sample_gyro_start_us
uint32_t AP_InertialSensor::_sample_gyro_start_us[INS_MAX_INSTANCES] private
Definition at line 466 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::notify_gyro_fifo_reset().
_sample_period_usec
uint32_t AP_InertialSensor::_sample_period_usec private
Definition at line 530 of file AP_InertialSensor.h.
Referenced by init(), and wait_for_sample().
_sample_rate
uint16_t AP_InertialSensor::_sample_rate private
Definition at line 388 of file AP_InertialSensor.h.
Referenced by get_sample_rate(), AP_InertialSensor_Backend::get_sample_rate_hz(), and init().
_singleton
AP_InertialSensor * AP_InertialSensor::_singleton = nullptr static private
Definition at line 567 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), and get_singleton().
_startup_error_counts_set
bool AP_InertialSensor::_startup_error_counts_set private
Definition at line 588 of file AP_InertialSensor.h.
Referenced by update().
_startup_ms
uint32_t AP_InertialSensor::_startup_ms private
Definition at line 589 of file AP_InertialSensor.h.
Referenced by update().
_still_threshold
AP_Float AP_InertialSensor::_still_threshold private
Definition at line 554 of file AP_InertialSensor.h.
Referenced by is_still().
_temperature
float AP_InertialSensor::_temperature[INS_MAX_INSTANCES] private
Definition at line 469 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_temperature(), and get_temperature().
_trim_option
AP_Int8 AP_InertialSensor::_trim_option private
Definition at line 565 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations().
_trim_pitch
float AP_InertialSensor::_trim_pitch private
Definition at line 579 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and get_new_trim().
_trim_roll
float AP_InertialSensor::_trim_roll private
Definition at line 580 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and get_new_trim().
_use
AP_Int8 AP_InertialSensor::_use[INS_MAX_INSTANCES] private
Definition at line 477 of file AP_InertialSensor.h.
Referenced by update(), use_accel(), use_gyro(), and wait_for_sample().
batchsampler
BatchSampler AP_InertialSensor::batchsampler {*this}
Definition at line 357 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_accel_sensor_rate_sample(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_sensor_rate_sample(), init(), AP_InertialSensor_Backend::log_accel_raw(), AP_InertialSensor_Backend::log_gyro_raw(), and periodic().
delta_time
float AP_InertialSensor::delta_time
Definition at line 560 of file AP_InertialSensor.h.
Referenced by set_delta_time().
imu_kill_mask
uint8_t AP_InertialSensor::imu_kill_mask private
Definition at line 591 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_publish_gyro(), AP_InertialSensor_Backend::_publish_temperature(), kill_imu(), AP_InertialSensor_Backend::update_accel(), and AP_InertialSensor_Backend::update_gyro().
var_info
const AP_Param::GroupInfo AP_InertialSensor::var_info static
Definition at line 186 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor.h
libraries/AP_InertialSensor/AP_InertialSensor.cpp