APM:Libraries: AP_Mount_Backend Class Reference
AP_Mount_Backend Class Reference abstract
#include <AP_Mount_Backend.h>
Public Member Functions
AP_Mount_Backend (AP_Mount &frontend, AP_Mount::mount_state &state, uint8_t instance)
virtual ~AP_Mount_Backend (void)
virtual void init (const AP_SerialManager &serial_manager)=0
virtual void update ()=0
virtual void update_fast ()
virtual bool has_pan_control () const =0
virtual void set_mode (enum MAV_MOUNT_MODE mode)=0
virtual void set_angle_targets (float roll, float tilt, float pan)
virtual void set_roi_target (const struct Location &target_loc)
virtual void control (int32_t pitch_or_lat, int32_t roll_or_lon, int32_t yaw_or_alt, MAV_MOUNT_MODE mount_mode)
void handle_mount_configure (const mavlink_mount_configure_t &msg)
void handle_mount_control (const mavlink_mount_control_t &packet)
virtual void send_mount_status (mavlink_channel_t chan)=0
virtual void handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t *msg)
virtual void handle_param_value (const mavlink_message_t *msg)
virtual void send_gimbal_report (const mavlink_channel_t chan)
Protected Member Functions
void update_targets_from_rc ()
float angle_input_rad (const RC_Channel *rc, int16_t angle_min, int16_t angle_max)
void calc_angle_to_location (const struct Location &target, Vector3f &angles_to_target_rad, bool calc_tilt, bool calc_pan, bool relative_pan=true)
MAV_MOUNT_MODE get_mode (void) const
Protected Attributes
AP_Mount & _frontend
AP_Mount::mount_state & _state
uint8_t _instance
Vector3f _angle_ef_target_rad
Private Member Functions
void rate_input_rad (float &out, const RC_Channel *ch, float min, float max) const
Detailed Description
Definition at line 26 of file AP_Mount_Backend.h.
Constructor & Destructor Documentation
AP_Mount_Backend()
AP_Mount_Backend::AP_Mount_Backend (AP_Mount & frontend, AP_Mount::mount_state & state, uint8_t instance) inline
Definition at line 30 of file AP_Mount_Backend.h.
~AP_Mount_Backend()
virtual AP_Mount_Backend::~AP_Mount_Backend (void) inline virtual
Definition at line 37 of file AP_Mount_Backend.h.
Member Function Documentation
angle_input_rad()
float AP_Mount_Backend::angle_input_rad (const RC_Channel * rc, int16_t angle_min, int16_t angle_max) protected
Definition at line 129 of file AP_Mount_Backend.cpp.
Referenced by update_targets_from_rc().
calc_angle_to_location()
void AP_Mount_Backend::calc_angle_to_location (const struct Location & target, Vector3f & angles_to_target_rad, bool calc_tilt, bool calc_pan, bool relative_pan = true) protected
Definition at line 135 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), and AP_Mount_Alexmos::update().
control()
void AP_Mount_Backend::control (int32_t pitch_or_lat, int32_t roll_or_lon, int32_t yaw_or_alt, MAV_MOUNT_MODE mount_mode) virtual
Definition at line 43 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_command_do_mount_control(), and handle_mount_control().
get_mode()
MAV_MOUNT_MODE AP_Mount_Backend::get_mode (void) const inline protected
Definition at line 93 of file AP_Mount_Backend.h.
Referenced by AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), and AP_Mount_Alexmos::update().
handle_gimbal_report()
virtual void AP_Mount_Backend::handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t * msg) inline virtual
Definition at line 73 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_gimbal_report().
handle_mount_configure()
void AP_Mount_Backend::handle_mount_configure (const mavlink_mount_configure_t & msg)
Definition at line 29 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_mount_configure().
handle_mount_control()
void AP_Mount_Backend::handle_mount_control (const mavlink_mount_control_t & packet)
Definition at line 38 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_mount_control().
handle_param_value()
virtual void AP_Mount_Backend::handle_param_value (const mavlink_message_t * msg) inline virtual
Definition at line 76 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_param_value().
has_pan_control()
virtual bool AP_Mount_Backend::has_pan_control () const pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::has_pan_control().
init()
virtual void AP_Mount_Backend::init (const AP_SerialManager & serial_manager) pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::init().
rate_input_rad()
void AP_Mount_Backend::rate_input_rad (float & out, const RC_Channel * ch, float min, float max) const private
Definition at line 83 of file AP_Mount_Backend.cpp.
Referenced by update_targets_from_rc().
send_gimbal_report()
virtual void AP_Mount_Backend::send_gimbal_report (const mavlink_channel_t chan) inline virtual
Definition at line 79 of file AP_Mount_Backend.h.
Referenced by AP_Mount::send_gimbal_report().
send_mount_status()
virtual void AP_Mount_Backend::send_mount_status (mavlink_channel_t chan) pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::send_mount_status().
set_angle_targets()
void AP_Mount_Backend::set_angle_targets (float roll, float tilt, float pan) virtual
Definition at line 7 of file AP_Mount_Backend.cpp.
Referenced by control(), and AP_Mount::set_angle_targets().
set_mode()
virtual void AP_Mount_Backend::set_mode (enum MAV_MOUNT_MODE mode) pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::handle_command_do_mount_configure(), handle_mount_configure(), and AP_Mount::set_mode().
set_roi_target()
void AP_Mount_Backend::set_roi_target (const struct Location & target_loc) virtual
Definition at line 19 of file AP_Mount_Backend.cpp.
Referenced by control(), and AP_Mount::set_roi_target().
update()
virtual void AP_Mount_Backend::update () pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_SToRM32, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::update().
update_fast()
virtual void AP_Mount_Backend::update_fast () inline virtual
Definition at line 46 of file AP_Mount_Backend.h.
Referenced by AP_Mount::update_fast().
update_targets_from_rc()
void AP_Mount_Backend::update_targets_from_rc () protected
Definition at line 93 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), and AP_Mount_Alexmos::update().
Member Data Documentation
_angle_ef_target_rad
Vector3f AP_Mount_Backend::_angle_ef_target_rad protected
Definition at line 98 of file AP_Mount_Backend.h.
Referenced by AP_Mount_SToRM32::send_mount_status(), set_angle_targets(), AP_Mount_Servo::stabilize(), AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), AP_Mount_Alexmos::update(), and update_targets_from_rc().
_frontend
AP_Mount& AP_Mount_Backend::_frontend protected
Definition at line 95 of file AP_Mount_Backend.h.
Referenced by calc_angle_to_location(), control(), get_mode(), rate_input_rad(), set_angle_targets(), set_roi_target(), and update_targets_from_rc().
_instance
uint8_t AP_Mount_Backend::_instance protected
Definition at line 97 of file AP_Mount_Backend.h.
Referenced by control(), get_mode(), AP_Mount_Servo::init(), set_angle_targets(), and set_roi_target().
_state
AP_Mount::mount_state& AP_Mount_Backend::_state protected
Definition at line 96 of file AP_Mount_Backend.h.
Referenced by handle_mount_configure(), handle_mount_control(), AP_Mount_SToRM32_serial::init(), AP_Mount_SToRM32_serial::set_mode(), AP_Mount_SToRM32::set_mode(), AP_Mount_Servo::set_mode(), AP_Mount_Alexmos::set_mode(), set_roi_target(), AP_Mount_Servo::stabilize(), AP_Mount_SToRM32_serial::update(), AP_Mount_SToRM32::update(), AP_Mount_Servo::update(), AP_Mount_Alexmos::update(), and update_targets_from_rc().
The documentation for this class was generated from the following files:
libraries/AP_Mount/AP_Mount_Backend.h
libraries/AP_Mount/AP_Mount_Backend.cpp