APM:Libraries: AP_Logger Class Reference
AP_Logger Class Reference
#include <AP_Logger.h>
Classes
struct log_write_fmt
struct PID_Info
Public Member Functions
FUNCTOR_TYPEDEF (vehicle_startup_message_Writer, void)
AP_Logger (const AP_Int32 &log_bitmask)
AP_Logger (const AP_Logger &other)=delete
AP_Logger & operator= (const AP_Logger &)=delete
void Init (const struct LogStructure *structure, uint8_t num_types)
void set_num_types (uint8_t num_types)
bool CardInserted (void)
void EraseAll ()
void WriteBlock (const void *pBuffer, uint16_t size)
void WriteCriticalBlock (const void *pBuffer, uint16_t size)
uint16_t find_last_log () const
void get_log_boundaries (uint16_t log_num, uint32_t &start_page, uint32_t &end_page)
uint16_t get_num_logs (void)
void setVehicle_Startup_Writer (vehicle_startup_message_Writer writer)
void PrepForArming ()
void EnableWrites (bool enable)
bool WritesEnabled () const
void StopLogging ()
void Write_Parameter (const char *name, float value)
void Write_Event (Log_Event id)
void Write_Error (LogErrorSubsystem sub_system, LogErrorCode error_code)
void Write_GPS (uint8_t instance, uint64_t time_us=0)
void Write_IMU ()
void Write_IMUDT (uint64_t time_us, uint8_t imu_mask)
bool Write_ISBH (uint16_t seqno, AP_InertialSensor::IMU_SENSOR_TYPE sensor_type, uint8_t instance, uint16_t multiplier, uint16_t sample_count, uint64_t sample_us, float sample_rate_hz)
bool Write_ISBD (uint16_t isb_seqno, uint16_t seqno, const int16_t x[32], const int16_t y[32], const int16_t z[32])
void Write_Vibration ()
void Write_RCIN (void)
void Write_RCOUT (void)
void Write_RSSI ()
void Write_Rally ()
void Write_Baro (uint64_t time_us=0)
void Write_Power (void)
void Write_AHRS2 (AP_AHRS &ahrs)
void Write_POS (AP_AHRS &ahrs)
void Write_Radio (const mavlink_radio_t &packet)
void Write_Message (const char *message)
void Write_MessageF (const char *fmt,...)
void Write_CameraInfo (enum LogMessages msg, const Location &current_loc, uint64_t timestamp_us=0)
void Write_Camera (const Location &current_loc, uint64_t timestamp_us=0)
void Write_Trigger (const Location &current_loc)
void Write_ESC (uint8_t id, uint64_t time_us, int32_t rpm, uint16_t voltage, uint16_t current, int16_t temperature, uint16_t current_tot)
void Write_Attitude (AP_AHRS &ahrs, const Vector3f &targets)
void Write_AttitudeView (AP_AHRS_View &ahrs, const Vector3f &targets)
void Write_Current ()
void Write_Compass (uint64_t time_us=0)
void Write_Mode (uint8_t mode, uint8_t reason)
void Write_EntireMission ()
void Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
void Write_Origin (uint8_t origin_type, const Location &loc)
void Write_RPM (const AP_RPM &rpm_sensor)
void Write_Rate (const AP_AHRS_View *ahrs, const AP_Motors &motors, const AC_AttitudeControl &attitude_control, const AC_PosControl &pos_control)
void Write_RallyPoint (uint8_t total, uint8_t sequence, const RallyLocation &rally_point)
void Write_VisualOdom (float time_delta, const Vector3f &angle_delta, const Vector3f &position_delta, float confidence)
void Write_AOA_SSA (AP_AHRS &ahrs)
void Write_Beacon (AP_Beacon &beacon)
void Write_Proximity (AP_Proximity &proximity)
void Write_SRTL (bool active, uint16_t num_points, uint16_t max_points, uint8_t action, const Vector3f &point)
void Write_OA (uint8_t algorithm, const Location &final_dest, const Location &oa_dest)
void Write (const char *name, const char *labels, const char *fmt,...)
void Write (const char *name, const char *labels, const char *units, const char *mults, const char *fmt,...)
void WriteCritical (const char *name, const char *labels, const char *fmt,...)
void WriteCritical (const char *name, const char *labels, const char *units, const char *mults, const char *fmt,...)
void WriteV (const char *name, const char *labels, const char *units, const char *mults, const char *fmt, va_list arg_list, bool is_critical=false)
void Write_PID (uint8_t msg_type, const PID_Info &info)
bool should_log (uint32_t mask) const
bool logging_started (void)
void flush (void)
void handle_mavlink_msg (class GCS_MAVLINK &, mavlink_message_t *msg)
void periodic_tasks ()
uint32_t num_dropped (void) const
void set_force_log_disarmed (bool force_logging)
bool log_while_disarmed (void) const
uint8_t log_replay (void) const
const struct LogStructure * structure (uint16_t num) const
const struct UnitStructure * unit (uint16_t num) const
const struct MultiplierStructure * multiplier (uint16_t num) const
bool logging_present () const
bool logging_enabled () const
bool logging_failed () const
void arming_failure ()
void set_vehicle_armed (bool armed_state)
bool vehicle_is_armed () const
void handle_log_send ()
bool in_log_download () const
float quiet_nanf () const
double quiet_nan () const
bool msg_type_in_use (uint8_t msg_type) const
Static Public Member Functions
static AP_Logger * get_singleton (void)
Public Attributes
vehicle_startup_message_Writer _vehicle_messages
struct {
AP_Int8 backend_types
AP_Int8 file_bufsize
AP_Int8 file_disarm_rot
AP_Int8 log_disarmed
AP_Int8 log_replay
AP_Int8 mav_bufsize
} _params
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
Protected Attributes
const struct LogStructure * _structures
uint8_t _num_types
const struct UnitStructure * _units = log_Units
const struct MultiplierStructure * _multipliers = log_Multipliers
const uint8_t _num_units = (sizeof(log_Units) / sizeof(log_Units[0]))
const uint8_t _num_multipliers = (sizeof(log_Multipliers) / sizeof(log_Multipliers[0]))
Private Types
enum Backend_Type : uint8_t { Backend_Type::NONE = 0, Backend_Type::FILESYSTEM = (1<<0), Backend_Type::MAVLINK = (1<<1), Backend_Type::BLOCK = (1<<2) }
enum transfer_activity_t : uint8_t { IDLE, LISTING, SENDING }
Private Member Functions
struct log_write_fmt * msg_fmt_for_name (const char *name, const char *labels, const char *units, const char *mults, const char *fmt)
const struct log_write_fmt * log_write_fmt_for_msg_type (uint8_t msg_type) const
const struct LogStructure * structure_for_msg_type (uint8_t msg_type)
int16_t find_free_msg_type () const
bool fill_log_write_logstructure (struct LogStructure &logstruct, const uint8_t msg_type) const
int16_t Write_calc_msg_len (const char *fmt) const
void Write_Baro_instance (uint64_t time_us, uint8_t baro_instance, enum LogMessages type)
void Write_IMU_instance (uint64_t time_us, uint8_t imu_instance, enum LogMessages type)
void Write_Compass_instance (uint64_t time_us, uint8_t mag_instance, enum LogMessages type)
void Write_Current_instance (uint64_t time_us, uint8_t battery_instance, enum LogMessages type, enum LogMessages celltype)
void Write_IMUDT_instance (uint64_t time_us, uint8_t imu_instance, enum LogMessages type)
void backend_starting_new_log (const AP_Logger_Backend *backend)
bool validate_structure (const struct LogStructure *logstructure, int16_t offset)
void validate_structures (const struct LogStructure *logstructures, const uint8_t num_types)
void dump_structure_field (const struct LogStructure *logstructure, const char *label, const uint8_t fieldnum)
pretty-print field information from a log structure
void dump_structures (const struct LogStructure *logstructures, const uint8_t num_types)
void assert_same_fmt_for_name (const log_write_fmt *f, const char *name, const char *labels, const char *units, const char *mults, const char *fmt) const
const char * unit_name (const uint8_t unit_id)
return a unit name given its ID
double multiplier_name (const uint8_t multiplier_id)
return a multiplier value given its ID
void Prep ()
bool should_handle_log_message ()
void handle_log_message (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_list (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_data (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_erase (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_request_end (class GCS_MAVLINK &, mavlink_message_t *msg)
void handle_log_send_listing ()
void handle_log_sending ()
bool handle_log_send_data ()
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
Private Attributes
uint8_t _next_backend
AP_Logger_Backend * backends [LOGGER_MAX_BACKENDS]
const AP_Int32 & _log_bitmask
struct AP_Logger::log_write_fmt * log_write_fmts
bool _armed
bool seen_ids [256] = { }
bool _writes_enabled:1
bool _force_log_disarmed:1
enum AP_Logger::transfer_activity_t transfer_activity = IDLE
uint16_t _log_next_list_entry
uint16_t _log_last_list_entry
uint16_t _log_num_logs
uint16_t _log_num_data
uint32_t _log_data_offset
uint32_t _log_data_size
uint32_t _log_data_remaining
uint32_t _log_data_page
GCS_MAVLINK * _log_sending_link
HAL_Semaphore_Recursive _log_send_sem
uint32_t _last_arming_failure_ms
Static Private Attributes
static AP_Logger * _singleton
Friends
class AP_Logger_Backend
Detailed Description
Definition at line 169 of file AP_Logger.h.
Member Enumeration Documentation
Backend_Type
enum AP_Logger::Backend_Type : uint8_t strong private
Enumerator
NONE
FILESYSTEM
MAVLINK
BLOCK
Definition at line 379 of file AP_Logger.h.
transfer_activity_t
enum AP_Logger::transfer_activity_t : uint8_t private
Enumerator
IDLE
LISTING
SENDING
Definition at line 467 of file AP_Logger.h.
Constructor & Destructor Documentation
AP_Logger() [1/2]
AP_Logger::AP_Logger (const AP_Int32 & log_bitmask)
Definition at line 86 of file AP_Logger.cpp.
AP_Logger() [2/2]
AP_Logger::AP_Logger (const AP_Logger & other) delete
Member Function Documentation
arming_failure()
void AP_Logger::arming_failure () inline
Definition at line 344 of file AP_Logger.h.
Referenced by AP_Arming::arm().
assert_same_fmt_for_name()
void AP_Logger::assert_same_fmt_for_name (const log_write_fmt * f, const char * name, const char * labels, const char * units, const char * mults, const char * fmt) const private
Definition at line 797 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name().
backend_starting_new_log()
void AP_Logger::backend_starting_new_log (const AP_Logger_Backend * backend) private
Definition at line 502 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::start_new_log_reset_variables().
CardInserted()
bool AP_Logger::CardInserted (void)
Definition at line 595 of file AP_Logger.cpp.
dump_structure_field()
void AP_Logger::dump_structure_field (const struct LogStructure * logstructure, const char * label, const uint8_t fieldnum) private
pretty-print field information from a log structure
Definition at line 247 of file AP_Logger.cpp.
Referenced by dump_structures().
dump_structures()
void AP_Logger::dump_structures (const struct LogStructure * logstructures, const uint8_t num_types) private
pretty-print log structures
Note
structures MUST be well-formed
Definition at line 254 of file AP_Logger.cpp.
Referenced by Init().
EnableWrites()
void AP_Logger::EnableWrites (bool enable) inline
Definition at line 210 of file AP_Logger.h.
Referenced by Init().
EraseAll()
void AP_Logger::EraseAll ()
Definition at line 591 of file AP_Logger.cpp.
Referenced by handle_log_request_erase().
fill_log_write_logstructure()
bool AP_Logger::fill_log_write_logstructure (struct LogStructure & logstruct, const uint8_t msg_type) const private
Definition at line 983 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::Write_Emit_FMT().
find_free_msg_type()
int16_t AP_Logger::find_free_msg_type () const private
Definition at line 968 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name().
find_last_log()
uint16_t AP_Logger::find_last_log () const
Definition at line 613 of file AP_Logger.cpp.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), and AP_LoggerTest::setup().
flush()
void AP_Logger::flush (void)
Definition at line 679 of file AP_Logger.cpp.
Referenced by AP_LoggerTest_AllTypes::flush_logger(), and AP_LoggerTest::setup().
FUNCTOR_TYPEDEF()
AP_Logger::FUNCTOR_TYPEDEF (vehicle_startup_message_Writer , void)
get_log_boundaries()
void AP_Logger::get_log_boundaries (uint16_t log_num, uint32_t & start_page, uint32_t & end_page)
Definition at line 619 of file AP_Logger.cpp.
Referenced by handle_log_request_data().
get_log_data()
int16_t AP_Logger::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) private
Definition at line 631 of file AP_Logger.cpp.
Referenced by handle_log_send_data().
get_log_info()
void AP_Logger::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc) private
Definition at line 625 of file AP_Logger.cpp.
Referenced by handle_log_request_data(), and handle_log_send_listing().
get_num_logs()
uint16_t AP_Logger::get_num_logs (void)
Definition at line 637 of file AP_Logger.cpp.
Referenced by handle_log_request_data(), and handle_log_request_list().
get_singleton()
static AP_Logger* AP_Logger::get_singleton (void) inline static
Definition at line 183 of file AP_Logger.h.
Referenced by AP_Arming::arm_checks(), RC_Channel::do_aux_function(), GCS_MAVLINK::handle_param_set(), SoloGimbal_Parameters::handle_param_value(), GCS_MAVLINK::handle_statustext(), GCS_MAVLINK::handle_timesync(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), AP_InertialSensor_Backend::log_accel_raw(), AP_InertialSensor_Backend::log_gyro_raw(), AP_AutoTune::log_param_change(), AP_Camera::log_picture(), AP_AHRS::Log_Write_Home_And_Origin(), OpticalFlow::Log_Write_Optflow(), AP::logger(), AP_InertialSensor::BatchSampler::push_data_to_log(), AP_BattMonitor::read(), ChibiOS::Scheduler::reboot(), GCS::send_parameter_value(), GCS::send_statustext(), AP_Baro::should_log(), AP_InertialSensor::BatchSampler::should_log(), AP_GPS::should_log(), AP_InertialSensor_Backend::should_log_imu_raw(), AP_Camera::update_trigger(), and AP_AutoTune::write_log().
handle_log_message()
void AP_Logger::handle_log_message (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle all types of log download requests from the GCS
Definition at line 43 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_mavlink_msg().
handle_log_request_data()
void AP_Logger::handle_log_request_data (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle request for log data
Definition at line 105 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
handle_log_request_end()
void AP_Logger::handle_log_request_end (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle request to stop transfer and resume normal logging
Definition at line 172 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
handle_log_request_erase()
void AP_Logger::handle_log_request_erase (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle request to erase log data
Definition at line 161 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
handle_log_request_list()
void AP_Logger::handle_log_request_list (class GCS_MAVLINK & link, mavlink_message_t * msg) private
handle all types of log download requests from the GCS
Definition at line 67 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
handle_log_send()
void AP_Logger::handle_log_send ()
trigger sending of log messages if there are some pending
Definition at line 185 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_request_data(), periodic_tasks(), and GCS_MAVLINK::update_send().
handle_log_send_data()
bool AP_Logger::handle_log_send_data () private
trigger sending of log data if there are some pending
Definition at line 280 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_sending().
handle_log_send_listing()
void AP_Logger::handle_log_send_listing () private
trigger sending of log messages if there are some pending
Definition at line 243 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_request_list(), and handle_log_send().
handle_log_sending()
void AP_Logger::handle_log_sending () private
Definition at line 208 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_send().
handle_mavlink_msg()
void AP_Logger::handle_mavlink_msg (class GCS_MAVLINK & link, mavlink_message_t * msg)
Definition at line 654 of file AP_Logger.cpp.
Referenced by GCS_MAVLINK::handle_common_message().
in_log_download()
bool AP_Logger::in_log_download () const inline
Definition at line 350 of file AP_Logger.h.
Referenced by should_log(), and AP_Logger_Backend::StartNewLogOK().
Init()
void AP_Logger::Init (const struct LogStructure * structure, uint8_t num_types)
Definition at line 97 of file AP_Logger.cpp.
Referenced by AP_LoggerTest::setup(), and AP_LoggerTest_AllTypes::setup().
log_replay()
uint8_t AP_Logger::log_replay (void) const inline
Definition at line 316 of file AP_Logger.h.
log_while_disarmed()
bool AP_Logger::log_while_disarmed (void) const
Definition at line 1154 of file AP_Logger.cpp.
Referenced by should_log(), and AP_Logger_Backend::ShouldLog().
log_write_fmt_for_msg_type()
const struct AP_Logger::log_write_fmt * AP_Logger::log_write_fmt_for_msg_type (uint8_t msg_type) const private
Definition at line 934 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::validate_WritePrioritisedBlock().
logging_enabled()
bool AP_Logger::logging_enabled () const
Definition at line 464 of file AP_Logger.cpp.
Referenced by RC_Channel::do_aux_function(), and GCS::update_sensor_status_flags().
logging_failed()
bool AP_Logger::logging_failed () const
Definition at line 476 of file AP_Logger.cpp.
Referenced by GCS::update_sensor_status_flags().
logging_present()
bool AP_Logger::logging_present () const
Definition at line 460 of file AP_Logger.cpp.
Referenced by AP_Arming::arm_checks(), and GCS::update_sensor_status_flags().
logging_started()
bool AP_Logger::logging_started (void)
Definition at line 645 of file AP_Logger.cpp.
Referenced by AP_Arming::arm_checks(), AP_AutoTune::log_param_change(), and AP_AutoTune::write_log().
msg_fmt_for_name()
AP_Logger::log_write_fmt * AP_Logger::msg_fmt_for_name (const char * name, const char * labels, const char * units, const char * mults, const char * fmt) private
Definition at line 843 of file AP_Logger.cpp.
Referenced by WriteV().
msg_type_in_use()
bool AP_Logger::msg_type_in_use (uint8_t msg_type) const
Definition at line 947 of file AP_Logger.cpp.
Referenced by find_free_msg_type().
multiplier()
const struct MultiplierStructure * AP_Logger::multiplier (uint16_t num) const
Definition at line 539 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::multiplier(), and Write_ISBH().
multiplier_name()
double AP_Logger::multiplier_name (const uint8_t multiplier_id) private
return a multiplier value given its ID
Definition at line 235 of file AP_Logger.cpp.
Referenced by dump_structure_field().
num_dropped()
uint32_t AP_Logger::num_dropped (void) const
Definition at line 723 of file AP_Logger.cpp.
operator=()
AP_Logger& AP_Logger::operator= (const AP_Logger &) delete
periodic_tasks()
void AP_Logger::periodic_tasks ()
Definition at line 672 of file AP_Logger.cpp.
Prep()
void AP_Logger::Prep () private
Definition at line 604 of file AP_Logger.cpp.
Referenced by Init().
PrepForArming()
void AP_Logger::PrepForArming ()
Definition at line 551 of file AP_Logger.cpp.
Referenced by AP_Arming::arm_checks().
quiet_nan()
double AP_Logger::quiet_nan () const inline
Definition at line 353 of file AP_Logger.h.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write().
quiet_nanf()
float AP_Logger::quiet_nanf () const inline
Definition at line 352 of file AP_Logger.h.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), and Write_POS().
set_force_log_disarmed()
void AP_Logger::set_force_log_disarmed (bool force_logging) inline
Definition at line 314 of file AP_Logger.h.
set_num_types()
void AP_Logger::set_num_types (uint8_t num_types) inline
Definition at line 189 of file AP_Logger.h.
set_vehicle_armed()
void AP_Logger::set_vehicle_armed (bool armed_state)
Definition at line 561 of file AP_Logger.cpp.
Referenced by AP_LoggerTest::setup(), and AP_LoggerTest_AllTypes::setup().
setVehicle_Startup_Writer()
void AP_Logger::setVehicle_Startup_Writer (vehicle_startup_message_Writer writer)
Definition at line 556 of file AP_Logger.cpp.
should_handle_log_message()
bool AP_Logger::should_handle_log_message () private
Definition at line 28 of file AP_Logger_MAVLinkLogTransfer.cpp.
Referenced by handle_log_message().
should_log()
bool AP_Logger::should_log (uint32_t mask) const
Definition at line 515 of file AP_Logger.cpp.
Referenced by AP_Camera::log_picture(), RangeFinder::Log_RFND(), OpticalFlow::Log_Write_Optflow(), AP_BattMonitor::read(), AP_Baro::should_log(), AP_InertialSensor::BatchSampler::should_log(), AP_GPS::should_log(), AP_InertialSensor_Backend::should_log_imu_raw(), and AP_Camera::update_trigger().
StopLogging()
void AP_Logger::StopLogging ()
Definition at line 608 of file AP_Logger.cpp.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), and ChibiOS::Scheduler::reboot().
structure()
const struct LogStructure * AP_Logger::structure (uint16_t num) const
Definition at line 455 of file AP_Logger.cpp.
Referenced by msg_type_in_use(), AP_Logger_Backend::structure(), and structure_for_msg_type().
structure_for_msg_type()
const struct LogStructure * AP_Logger::structure_for_msg_type (uint8_t msg_type) private
Definition at line 922 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::validate_WritePrioritisedBlock().
unit()
const struct UnitStructure * AP_Logger::unit (uint16_t num) const
Definition at line 534 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::unit().
unit_name()
const char * AP_Logger::unit_name (const uint8_t unit_id) private
return a unit name given its ID
Definition at line 224 of file AP_Logger.cpp.
Referenced by dump_structure_field().
validate_structure()
bool AP_Logger::validate_structure (const struct LogStructure * logstructure, int16_t offset) private
Definition at line 283 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name(), and validate_structures().
validate_structures()
void AP_Logger::validate_structures (const struct LogStructure * logstructures, const uint8_t num_types) private
Definition at line 399 of file AP_Logger.cpp.
Referenced by Init().
vehicle_is_armed()
bool AP_Logger::vehicle_is_armed () const inline
Definition at line 347 of file AP_Logger.h.
Referenced by should_handle_log_message(), should_log(), and AP_Logger_Backend::ShouldLog().
Write() [1/2]
void AP_Logger::Write (const char * name, const char * labels, const char * fmt, ...)
Definition at line 735 of file AP_Logger.cpp.
Referenced by ChibiOS::Scheduler::_monitor_thread(), AC_AttitudeControl::control_monitor_log(), AP_Follow::handle_msg(), GCS_MAVLINK::handle_timesync(), GCS_MAVLINK::log_vision_position_estimate_data(), AP_LandingGear::log_wow_state(), AC_AutoTune::Log_Write_AutoTune(), AC_AutoTune::Log_Write_AutoTuneDetails(), AP_Tuning::Log_Write_Parameter_Tuning(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), AP_LoggerTest::setup(), SITL::Aircraft::smooth_sensors(), AP_Compass_MMC3416::timer(), AP_Landing::type_slope_log(), CompassLearn::update(), AP_Baro_ICM20789::update(), Variometer::update(), AP_TECS::update_pitch_throttle(), SITL::Aircraft::update_position(), SoaringController::update_thermalling(), and AC_PosControl::write_log().
Write() [2/2]
void AP_Logger::Write (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, ...)
Definition at line 744 of file AP_Logger.cpp.
Write_AHRS2()
void AP_Logger::Write_AHRS2 (AP_AHRS & ahrs)
Definition at line 458 of file LogFile.cpp.
Write_AOA_SSA()
void AP_Logger::Write_AOA_SSA (AP_AHRS & ahrs)
Definition at line 863 of file LogFile.cpp.
Write_Attitude()
void AP_Logger::Write_Attitude (AP_AHRS & ahrs, const Vector3f & targets)
Definition at line 595 of file LogFile.cpp.
Write_AttitudeView()
void AP_Logger::Write_AttitudeView (AP_AHRS_View & ahrs, const Vector3f & targets)
Definition at line 613 of file LogFile.cpp.
Write_Baro()
void AP_Logger::Write_Baro (uint64_t time_us = 0)
Definition at line 266 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and AP_Baro::update().
Write_Baro_instance()
void AP_Logger::Write_Baro_instance (uint64_t time_us, uint8_t baro_instance, enum LogMessages type) private
Definition at line 245 of file LogFile.cpp.
Referenced by Write_Baro().
Write_Beacon()
void AP_Logger::Write_Beacon (AP_Beacon & beacon)
Definition at line 876 of file LogFile.cpp.
Write_calc_msg_len()
int16_t AP_Logger::Write_calc_msg_len (const char * fmt) const private
Definition at line 1027 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name(), and validate_structure().
Write_Camera()
void AP_Logger::Write_Camera (const Location & current_loc, uint64_t timestamp_us = 0)
Definition at line 583 of file LogFile.cpp.
Referenced by AP_Camera::log_picture(), and AP_Camera::update_trigger().
Write_CameraInfo()
void AP_Logger::Write_CameraInfo (enum LogMessages msg, const Location & current_loc, uint64_t timestamp_us = 0)
Definition at line 546 of file LogFile.cpp.
Referenced by Write_Camera(), and Write_Trigger().
Write_Compass()
void AP_Logger::Write_Compass (uint64_t time_us = 0)
Definition at line 719 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and Compass::read().
Write_Compass_instance()
void AP_Logger::Write_Compass_instance (uint64_t time_us, uint8_t mag_instance, enum LogMessages type) private
Definition at line 693 of file LogFile.cpp.
Referenced by Write_Compass().
Write_Current()
void AP_Logger::Write_Current ()
Definition at line 671 of file LogFile.cpp.
Referenced by AP_BattMonitor::read().
Write_Current_instance()
void AP_Logger::Write_Current_instance (uint64_t time_us, uint8_t battery_instance, enum LogMessages type, enum LogMessages celltype) private
Definition at line 630 of file LogFile.cpp.
Referenced by Write_Current().
Write_EntireMission()
void AP_Logger::Write_EntireMission ()
Definition at line 685 of file AP_Logger.cpp.
Referenced by MissionItemProtocol_Waypoints::complete().
Write_Error()
void AP_Logger::Write_Error (LogErrorSubsystem sub_system, LogErrorCode error_code)
Definition at line 1139 of file AP_Logger.cpp.
Referenced by Compass::init().
Write_ESC()
void AP_Logger::Write_ESC (uint8_t id, uint64_t time_us, int32_t rpm, uint16_t voltage, uint16_t current, int16_t temperature, uint16_t current_tot)
Definition at line 758 of file LogFile.cpp.
Write_Event()
void AP_Logger::Write_Event (Log_Event id)
Definition at line 1128 of file AP_Logger.cpp.
Referenced by RC_Channel::do_aux_function(), AP_Parachute::enabled(), and AP_Parachute::release().
Write_GPS()
void AP_Logger::Write_GPS (uint8_t instance, uint64_t time_us = 0)
Definition at line 134 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), NavEKF2::check_log_write(), and AP_GPS::update_instance().
Write_IMU()
void AP_Logger::Write_IMU ()
Definition at line 307 of file LogFile.cpp.
Write_IMU_instance()
void AP_Logger::Write_IMU_instance (uint64_t time_us, uint8_t imu_instance, enum LogMessages type) private
Definition at line 281 of file LogFile.cpp.
Referenced by Write_IMU().
Write_IMUDT()
void AP_Logger::Write_IMUDT (uint64_t time_us, uint8_t imu_mask)
Definition at line 354 of file LogFile.cpp.
Referenced by NavEKF3::check_log_write(), and NavEKF2::check_log_write().
Write_IMUDT_instance()
void AP_Logger::Write_IMUDT_instance (uint64_t time_us, uint8_t imu_instance, enum LogMessages type) private
Definition at line 328 of file LogFile.cpp.
Referenced by Write_IMUDT().
Write_ISBD()
bool AP_Logger::Write_ISBD (uint16_t isb_seqno, uint16_t seqno, const int16_t x[32], const int16_t y[32], const int16_t z[32])
Definition at line 1100 of file AP_Logger.cpp.
Referenced by AP_InertialSensor::BatchSampler::push_data_to_log().
Write_ISBH()
bool AP_Logger::Write_ISBH (uint16_t seqno, AP_InertialSensor::IMU_SENSOR_TYPE sensor_type, uint8_t instance, uint16_t multiplier, uint16_t sample_count, uint64_t sample_us, float sample_rate_hz)
Definition at line 1067 of file AP_Logger.cpp.
Referenced by AP_InertialSensor::BatchSampler::push_data_to_log().
Write_Message()
void AP_Logger::Write_Message (const char * message)
Definition at line 690 of file AP_Logger.cpp.
Referenced by GCS_MAVLINK::handle_statustext(), GCS::send_statustext(), AP_LoggerTest::setup(), AP_LoggerTest_AllTypes::setup(), AP_GPS_Backend::Write_AP_Logger_Log_Startup_messages(), and Write_MessageF().
Write_MessageF()
void AP_Logger::Write_MessageF (const char * fmt, ...)
Definition at line 490 of file AP_Logger.cpp.
Referenced by AP_GPS_UBLOX::Write_AP_Logger_Log_Startup_messages().
Write_Mission_Cmd()
void AP_Logger::Write_Mission_Cmd (const AP_Mission & mission, const AP_Mission::Mission_Command & cmd)
Definition at line 705 of file AP_Logger.cpp.
Write_Mode()
void AP_Logger::Write_Mode (uint8_t mode, uint8_t reason)
Definition at line 695 of file AP_Logger.cpp.
Write_OA()
void AP_Logger::Write_OA (uint8_t algorithm, const Location & final_dest, const Location & oa_dest)
Definition at line 956 of file LogFile.cpp.
Referenced by AP_OAPathPlanner::mission_avoidance().
Write_Origin()
void AP_Logger::Write_Origin (uint8_t origin_type, const Location & loc)
Definition at line 792 of file LogFile.cpp.
Referenced by AP_AHRS::Log_Write_Home_And_Origin().
Write_Parameter()
void AP_Logger::Write_Parameter (const char * name, float value)
Definition at line 700 of file AP_Logger.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), SoloGimbal_Parameters::handle_param_value(), AP_AutoTune::log_param_change(), and GCS::send_parameter_value().
Write_PID()
void AP_Logger::Write_PID (uint8_t msg_type, const PID_Info & info)
Definition at line 777 of file LogFile.cpp.
Write_POS()
void AP_Logger::Write_POS (AP_AHRS & ahrs)
Definition at line 484 of file LogFile.cpp.
Write_Power()
void AP_Logger::Write_Power (void)
Definition at line 437 of file LogFile.cpp.
Referenced by AP_BattMonitor::read().
Write_Proximity()
void AP_Logger::Write_Proximity (AP_Proximity & proximity)
Definition at line 903 of file LogFile.cpp.
Write_Radio()
void AP_Logger::Write_Radio (const mavlink_radio_t & packet)
Definition at line 529 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_radio_status().
Write_Rally()
void AP_Logger::Write_Rally ()
Definition at line 718 of file AP_Logger.cpp.
Referenced by MissionItemProtocol_Rally::complete().
Write_RallyPoint()
void AP_Logger::Write_RallyPoint (uint8_t total, uint8_t sequence, const RallyLocation & rally_point)
Definition at line 711 of file AP_Logger.cpp.
Referenced by AP_Rally::set_rally_point_with_index().
Write_Rate()
void AP_Logger::Write_Rate (const AP_AHRS_View * ahrs, const AP_Motors & motors, const AC_AttitudeControl & attitude_control, const AC_PosControl & pos_control)
Definition at line 818 of file LogFile.cpp.
Referenced by AC_AutoTune::control_attitude().
Write_RCIN()
void AP_Logger::Write_RCIN (void)
Definition at line 180 of file LogFile.cpp.
Referenced by RC_Channels::read_aux_all().
Write_RCOUT()
void AP_Logger::Write_RCOUT (void)
Definition at line 206 of file LogFile.cpp.
Write_RPM()
void AP_Logger::Write_RPM (const AP_RPM & rpm_sensor)
Definition at line 806 of file LogFile.cpp.
Write_RSSI()
void AP_Logger::Write_RSSI ()
Definition at line 230 of file LogFile.cpp.
Write_SRTL()
void AP_Logger::Write_SRTL (bool active, uint16_t num_points, uint16_t max_points, uint8_t action, const Vector3f & point)
Definition at line 940 of file LogFile.cpp.
Referenced by AP_SmartRTL::log_action().
Write_Trigger()
void AP_Logger::Write_Trigger (const Location & current_loc)
Definition at line 589 of file LogFile.cpp.
Referenced by AP_Camera::log_picture().
Write_Vibration()
void AP_Logger::Write_Vibration ()
Definition at line 377 of file LogFile.cpp.
Write_VisualOdom()
void AP_Logger::Write_VisualOdom (float time_delta, const Vector3f & angle_delta, const Vector3f & position_delta, float confidence)
Definition at line 845 of file LogFile.cpp.
Referenced by AP_VisualOdom::update().
WriteBlock()
void AP_Logger::WriteBlock (const void * pBuffer, uint16_t size)
Definition at line 578 of file AP_Logger.cpp.
Referenced by AP_Landing_Deepstall::Log(), AP_InertialSensor_Backend::log_accel_raw(), AP_Airspeed::Log_Airspeed(), AP_InertialSensor_Backend::log_gyro_raw(), GCS_MAVLINK::log_mavlink_stats(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), RangeFinder::Log_RFND(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), AP_WheelEncoder::Log_Write(), NavEKF2::Log_Write_Beacon(), NavEKF3::Log_Write_Beacon(), NavEKF3::Log_Write_BodyOdom(), NavEKF2::Log_Write_EKF1(), NavEKF3::Log_Write_EKF1(), NavEKF2::Log_Write_NKF2(), NavEKF3::Log_Write_NKF2a(), NavEKF2::Log_Write_NKF3(), NavEKF3::Log_Write_NKF3(), NavEKF2::Log_Write_NKF4(), NavEKF3::Log_Write_NKF4(), NavEKF2::Log_Write_NKF5(), NavEKF3::Log_Write_NKF5(), OpticalFlow::Log_Write_Optflow(), NavEKF2::Log_Write_Quaternion(), NavEKF3::Log_Write_Quaternion(), SITL::SITL::Log_Write_SIMSTATE(), NavEKF3::Log_Write_State_Variances(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_GPS_SBP2::logging_ext_event(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP2::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), AP_GPS_SBP2::logging_log_raw_sbp(), AP_LoggerTest::setup(), Write_AHRS2(), Write_AOA_SSA(), Write_Attitude(), Write_AttitudeView(), Write_Baro_instance(), Write_Beacon(), Write_Compass_instance(), Write_Current_instance(), Write_ESC(), Write_GPS(), Write_IMU_instance(), Write_IMUDT_instance(), AP_AutoTune::write_log(), AP_ADSB::write_log(), Write_OA(), Write_Origin(), Write_PID(), Write_POS(), Write_Power(), Write_Proximity(), Write_Radio(), Write_Rate(), Write_RCIN(), Write_RCOUT(), Write_RPM(), Write_RSSI(), Write_SRTL(), Write_Vibration(), and Write_VisualOdom().
WriteCritical() [1/2]
void AP_Logger::WriteCritical (const char * name, const char * labels, const char * fmt, ...)
Definition at line 753 of file AP_Logger.cpp.
Referenced by main_loop(), HAL_SITL::run(), and AP_LoggerTest::setup().
WriteCritical() [2/2]
void AP_Logger::WriteCritical (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, ...)
Definition at line 762 of file AP_Logger.cpp.
WriteCriticalBlock()
void AP_Logger::WriteCriticalBlock (const void * pBuffer, uint16_t size)
Definition at line 582 of file AP_Logger.cpp.
Referenced by AP_Arming::Log_Write_Arm_Disarm(), AP_Scheduler::Log_Write_Performance(), Write_CameraInfo(), Write_Error(), and Write_Event().
WritePrioritisedBlock()
void AP_Logger::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) protected
Definition at line 586 of file AP_Logger.cpp.
WritesEnabled()
bool AP_Logger::WritesEnabled () const inline
Definition at line 211 of file AP_Logger.h.
Referenced by should_handle_log_message(), and AP_Logger_Backend::ShouldLog().
WriteV()
void AP_Logger::WriteV (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, va_list arg_list, bool is_critical = false)
Definition at line 771 of file AP_Logger.cpp.
Referenced by Write(), and WriteCritical().
Friends And Related Function Documentation
AP_Logger_Backend
friend class AP_Logger_Backend friend
Definition at line 171 of file AP_Logger.h.
Member Data Documentation
_armed
bool AP_Logger::_armed private
Definition at line 422 of file AP_Logger.h.
Referenced by set_vehicle_armed(), and vehicle_is_armed().
_force_log_disarmed
bool AP_Logger::_force_log_disarmed private
Definition at line 463 of file AP_Logger.h.
Referenced by log_while_disarmed(), and set_force_log_disarmed().
_last_arming_failure_ms
uint32_t AP_Logger::_last_arming_failure_ms private
Definition at line 501 of file AP_Logger.h.
Referenced by arming_failure(), and log_while_disarmed().
_log_bitmask
const AP_Int32& AP_Logger::_log_bitmask private
Definition at line 377 of file AP_Logger.h.
Referenced by should_log(), and AP_Logger_Backend::StartNewLogOK().
_log_data_offset
uint32_t AP_Logger::_log_data_offset private
Definition at line 486 of file AP_Logger.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
_log_data_page
uint32_t AP_Logger::_log_data_page private
Definition at line 495 of file AP_Logger.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
_log_data_remaining
uint32_t AP_Logger::_log_data_remaining private
Definition at line 492 of file AP_Logger.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
_log_data_size
uint32_t AP_Logger::_log_data_size private
Definition at line 489 of file AP_Logger.h.
Referenced by handle_log_request_data().
_log_last_list_entry
uint16_t AP_Logger::_log_last_list_entry private
Definition at line 477 of file AP_Logger.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
_log_next_list_entry
uint16_t AP_Logger::_log_next_list_entry private
Definition at line 474 of file AP_Logger.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
_log_num_data
uint16_t AP_Logger::_log_num_data private
Definition at line 483 of file AP_Logger.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
_log_num_logs
uint16_t AP_Logger::_log_num_logs private
Definition at line 480 of file AP_Logger.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
_log_send_sem
HAL_Semaphore_Recursive AP_Logger::_log_send_sem private
Definition at line 498 of file AP_Logger.h.
Referenced by handle_log_request_data(), handle_log_request_end(), handle_log_request_list(), handle_log_send(), handle_log_send_data(), handle_log_send_listing(), and handle_log_sending().
_log_sending_link
GCS_MAVLINK* AP_Logger::_log_sending_link private
Definition at line 497 of file AP_Logger.h.
Referenced by handle_log_request_data(), handle_log_request_end(), handle_log_request_list(), handle_log_send(), handle_log_send_data(), handle_log_send_listing(), and handle_log_sending().
_multipliers
const struct MultiplierStructure* AP_Logger::_multipliers = log_Multipliers protected
Definition at line 363 of file AP_Logger.h.
Referenced by multiplier_name(), and validate_structure().
_next_backend
uint8_t AP_Logger::_next_backend private
Definition at line 375 of file AP_Logger.h.
Referenced by backend_starting_new_log(), CardInserted(), find_last_log(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), Init(), logging_enabled(), logging_failed(), logging_present(), logging_started(), num_dropped(), should_log(), Write_ISBD(), Write_ISBH(), and WriteV().
_num_multipliers
const uint8_t AP_Logger::_num_multipliers = (sizeof(log_Multipliers) / sizeof(log_Multipliers[0])) protected
Definition at line 365 of file AP_Logger.h.
Referenced by AP_Logger_Backend::num_multipliers(), and validate_structure().
_num_types
uint8_t AP_Logger::_num_types protected
Definition at line 361 of file AP_Logger.h.
Referenced by Init(), msg_type_in_use(), AP_Logger_Backend::num_types(), set_num_types(), and structure_for_msg_type().
_num_units
const uint8_t AP_Logger::_num_units = (sizeof(log_Units) / sizeof(log_Units[0])) protected
Definition at line 364 of file AP_Logger.h.
Referenced by AP_Logger_Backend::num_units(), and validate_structure().
_params
struct { ... } AP_Logger::_params
Referenced by AP_Logger_MAVLink::AP_Logger_MAVLink(), AP_Logger_Block::Init(), Init(), log_replay(), log_while_disarmed(), and AP_Logger_Backend::ShouldLog().
_singleton
AP_Logger * AP_Logger::_singleton static private
Definition at line 441 of file AP_Logger.h.
Referenced by AP_Logger(), and get_singleton().
_structures
const struct LogStructure* AP_Logger::_structures protected
Definition at line 360 of file AP_Logger.h.
Referenced by Init(), and structure().
_units
const struct UnitStructure* AP_Logger::_units = log_Units protected
Definition at line 362 of file AP_Logger.h.
Referenced by unit(), unit_name(), and validate_structure().
_vehicle_messages
vehicle_startup_message_Writer AP_Logger::_vehicle_messages
Definition at line 318 of file AP_Logger.h.
Referenced by setVehicle_Startup_Writer(), and AP_Logger_Backend::vehicle_message_writer().
_writes_enabled
bool AP_Logger::_writes_enabled private
Definition at line 462 of file AP_Logger.h.
Referenced by EnableWrites(), and WritesEnabled().
backend_types
AP_Int8 AP_Logger::backend_types
Definition at line 323 of file AP_Logger.h.
backends
AP_Logger_Backend* AP_Logger::backends[LOGGER_MAX_BACKENDS] private
Definition at line 376 of file AP_Logger.h.
Referenced by backend_starting_new_log(), CardInserted(), find_last_log(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), Init(), logging_enabled(), logging_failed(), logging_started(), num_dropped(), Write_ISBD(), Write_ISBH(), and WriteV().
file_bufsize
AP_Int8 AP_Logger::file_bufsize
Definition at line 324 of file AP_Logger.h.
Referenced by AP_Logger_Block::Init().
file_disarm_rot
AP_Int8 AP_Logger::file_disarm_rot
Definition at line 325 of file AP_Logger.h.
Referenced by AP_Logger_Backend::ShouldLog().
log_disarmed
AP_Int8 AP_Logger::log_disarmed
Definition at line 326 of file AP_Logger.h.
log_replay
AP_Int8 AP_Logger::log_replay
Definition at line 327 of file AP_Logger.h.
Referenced by NavEKF3::InitialiseFilter(), and NavEKF2::InitialiseFilter().
log_write_fmts
struct AP_Logger::log_write_fmt * AP_Logger::log_write_fmts private
Referenced by backend_starting_new_log(), fill_log_write_logstructure(), log_write_fmt_for_msg_type(), msg_fmt_for_name(), msg_type_in_use(), and AP_Logger_Backend::Write().
mav_bufsize
AP_Int8 AP_Logger::mav_bufsize
Definition at line 328 of file AP_Logger.h.
Referenced by AP_Logger_MAVLink::AP_Logger_MAVLink().
seen_ids
bool AP_Logger::seen_ids[256] = { } private
Definition at line 456 of file AP_Logger.h.
Referenced by validate_structure().
transfer_activity
enum AP_Logger::transfer_activity_t AP_Logger::transfer_activity = IDLE private
Referenced by handle_log_request_data(), handle_log_request_end(), handle_log_request_list(), handle_log_send(), handle_log_send_data(), handle_log_send_listing(), handle_log_sending(), and in_log_download().
var_info
const AP_Param::GroupInfo AP_Logger::var_info static
Definition at line 321 of file AP_Logger.h.
Referenced by AP_Logger().
The documentation for this class was generated from the following files:
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/AP_Logger.cpp
libraries/AP_Logger/AP_Logger_MAVLinkLogTransfer.cpp
libraries/AP_Logger/LogFile.cpp