APM:Libraries: AP_BoardConfig Class Reference
AP_BoardConfig Class Reference
#include <AP_BoardConfig.h>
Public Types
enum px4_board_type {
BOARD_TYPE_UNKNOWN = -1, PX4_BOARD_AUTO = 0, PX4_BOARD_PX4V1 = 1, PX4_BOARD_PIXHAWK = 2,
PX4_BOARD_PIXHAWK2 = 3, PX4_BOARD_PIXRACER = 4, PX4_BOARD_PHMINI = 5, PX4_BOARD_PH2SLIM = 6,
PX4_BOARD_AEROFC = 13, PX4_BOARD_PIXHAWK_PRO = 14, PX4_BOARD_AUAV21 = 20, PX4_BOARD_PCNC1 = 21,
PX4_BOARD_MINDPXV2 = 22, PX4_BOARD_SP01 = 23, PX4_BOARD_FMUV5 = 24, VRX_BOARD_BRAIN51 = 30,
VRX_BOARD_BRAIN52 = 32, VRX_BOARD_BRAIN52E = 33, VRX_BOARD_UBRAIN51 = 34, VRX_BOARD_UBRAIN52 = 35,
VRX_BOARD_CORE10 = 36, VRX_BOARD_BRAIN54 = 38, PX4_BOARD_OLDDRIVERS = 100, PX4_BOARD_FMUV6 = 39
}
enum board_options { BOARD_OPTION_WATCHDOG = (1 << 0) }
Public Member Functions
AP_BoardConfig ()
AP_BoardConfig (const AP_BoardConfig &other)=delete
AP_BoardConfig & operator= (const AP_BoardConfig &)=delete
void init (void)
void init_safety (void)
void set_default_safety_ignore_mask (uint16_t mask)
uint16_t get_safety_mask (void) const
Static Public Member Functions
static AP_BoardConfig * get_singleton (void)
static void sensor_config_error (const char *reason)
static bool in_sensor_config_error (void)
static enum px4_board_type get_board_type (void)
static uint8_t io_enabled (void)
static uint8_t get_pwm_count (void)
static uint8_t get_sdcard_slowdown (void)
static bool watchdog_enabled (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void board_init_safety (void)
void board_setup_uart (void)
void board_setup_sbus (void)
void board_setup (void)
Private Attributes
AP_Int16 vehicleSerialNumber
AP_Int8 pwm_count
AP_Int8 _imu_target_temperature
AP_RTC rtc
AP_Int8 _sdcard_slowdown
AP_Int32 _options
Static Private Attributes
static AP_BoardConfig * _singleton
static bool _in_sensor_config_error
Detailed Description
Definition at line 34 of file AP_BoardConfig.h.
Member Enumeration Documentation
board_options
enum AP_BoardConfig::board_options
Enumerator
BOARD_OPTION_WATCHDOG
Definition at line 161 of file AP_BoardConfig.h.
px4_board_type
enum AP_BoardConfig::px4_board_type
Enumerator
BOARD_TYPE_UNKNOWN
PX4_BOARD_AUTO
PX4_BOARD_PX4V1
PX4_BOARD_PIXHAWK
PX4_BOARD_PIXHAWK2
PX4_BOARD_PIXRACER
PX4_BOARD_PHMINI
PX4_BOARD_PH2SLIM
PX4_BOARD_AEROFC
PX4_BOARD_PIXHAWK_PRO
PX4_BOARD_AUAV21
PX4_BOARD_PCNC1
PX4_BOARD_MINDPXV2
PX4_BOARD_SP01
PX4_BOARD_FMUV5
VRX_BOARD_BRAIN51
VRX_BOARD_BRAIN52
VRX_BOARD_BRAIN52E
VRX_BOARD_UBRAIN51
VRX_BOARD_UBRAIN52
VRX_BOARD_CORE10
VRX_BOARD_BRAIN54
PX4_BOARD_OLDDRIVERS
PX4_BOARD_FMUV6
Definition at line 64 of file AP_BoardConfig.h.
Constructor & Destructor Documentation
AP_BoardConfig() [1/2]
AP_BoardConfig::AP_BoardConfig () inline
Definition at line 36 of file AP_BoardConfig.h.
AP_BoardConfig() [2/2]
AP_BoardConfig::AP_BoardConfig (const AP_BoardConfig & other) delete
Member Function Documentation
board_init_safety()
void AP_BoardConfig::board_init_safety (void) private
Definition at line 30 of file board_drivers.cpp.
Referenced by init_safety().
board_setup()
void AP_BoardConfig::board_setup (void) private
Definition at line 437 of file board_drivers.cpp.
Referenced by init().
board_setup_sbus()
void AP_BoardConfig::board_setup_sbus (void) private
Definition at line 404 of file board_drivers.cpp.
Referenced by board_setup().
board_setup_uart()
void AP_BoardConfig::board_setup_uart (void) private
Definition at line 391 of file board_drivers.cpp.
Referenced by board_setup().
get_board_type()
static enum px4_board_type AP_BoardConfig::get_board_type (void) inline static
Definition at line 94 of file AP_BoardConfig.h.
Referenced by Compass::_detect_backends(), Compass::_probe_external_i2c_compasses(), AP_Baro::_probe_i2c_barometers(), AP_InertialSensor::detect_backends(), and AP_Baro::init().
get_pwm_count()
static uint8_t AP_BoardConfig::get_pwm_count (void) inline static
Definition at line 114 of file AP_BoardConfig.h.
Referenced by ChibiOS::RCOutput::init(), and ChibiOS::GPIO::init().
get_safety_mask()
uint16_t AP_BoardConfig::get_safety_mask (void) const inline
Definition at line 133 of file AP_BoardConfig.h.
Referenced by ChibiOS::RCOutput::safety_update().
get_sdcard_slowdown()
static uint8_t AP_BoardConfig::get_sdcard_slowdown (void) inline static
Definition at line 156 of file AP_BoardConfig.h.
Referenced by sdcard_init().
get_singleton()
static AP_BoardConfig* AP_BoardConfig::get_singleton (void) inline static
Definition at line 46 of file AP_BoardConfig.h.
Referenced by AP_Arming::disarm(), and ChibiOS::RCOutput::safety_update().
in_sensor_config_error()
static bool AP_BoardConfig::in_sensor_config_error (void) inline static
Definition at line 60 of file AP_BoardConfig.h.
Referenced by GCS::out_of_time(), and HALSITL::Scheduler::reboot().
init()
void AP_BoardConfig::init (void)
Definition at line 251 of file AP_BoardConfig.cpp.
Referenced by setup(), and SchedTest::setup().
init_safety()
void AP_BoardConfig::init_safety (void)
Definition at line 290 of file AP_BoardConfig.cpp.
io_enabled()
static uint8_t AP_BoardConfig::io_enabled (void) inline static
Definition at line 105 of file AP_BoardConfig.h.
Referenced by ChibiOS::RCOutput::_safety_switch_state(), ChibiOS::RCInput::_timer_tick(), ChibiOS::RCOutput::cork(), ChibiOS::RCOutput::enable_px4io_sbus_out(), ChibiOS::RCOutput::force_safety_off(), ChibiOS::RCOutput::force_safety_on(), ChibiOS::RCOutput::init(), ChibiOS::RCOutput::push(), ChibiOS::RCInput::rc_bind(), ChibiOS::Scheduler::reboot(), ChibiOS::RCOutput::set_default_rate(), ChibiOS::RCOutput::set_failsafe_pwm(), ChibiOS::RCOutput::set_freq(), ChibiOS::Util::set_imu_temp(), ChibiOS::RCOutput::set_output_mode(), ChibiOS::RCOutput::set_safety_pwm(), and ChibiOS::RCOutput::write().
operator=()
AP_BoardConfig& AP_BoardConfig::operator= (const AP_BoardConfig &) delete
sensor_config_error()
void AP_BoardConfig::sensor_config_error (const char * reason) static
Definition at line 300 of file AP_BoardConfig.cpp.
Referenced by AP_InertialSensor::detect_backends(), AP_Baro::init(), and AP_Param::set_defaults_from_table().
set_default_safety_ignore_mask()
void AP_BoardConfig::set_default_safety_ignore_mask (uint16_t mask)
Definition at line 283 of file AP_BoardConfig.cpp.
watchdog_enabled()
static bool AP_BoardConfig::watchdog_enabled (void) inline static
Definition at line 166 of file AP_BoardConfig.h.
Referenced by ChibiOS::Scheduler::_monitor_thread(), main_loop(), and HAL_SITL::run().
Member Data Documentation
_imu_target_temperature
AP_Int8 AP_BoardConfig::_imu_target_temperature private
Definition at line 211 of file AP_BoardConfig.h.
Referenced by init().
_in_sensor_config_error
bool AP_BoardConfig::_in_sensor_config_error static private
Definition at line 208 of file AP_BoardConfig.h.
Referenced by in_sensor_config_error(), and sensor_config_error().
_options
AP_Int32 AP_BoardConfig::_options private
Definition at line 237 of file AP_BoardConfig.h.
Referenced by watchdog_enabled().
_sdcard_slowdown
AP_Int8 AP_BoardConfig::_sdcard_slowdown private
Definition at line 234 of file AP_BoardConfig.h.
Referenced by get_sdcard_slowdown(), and init().
_singleton
AP_BoardConfig * AP_BoardConfig::_singleton static private
Definition at line 171 of file AP_BoardConfig.h.
Referenced by AP_BoardConfig(), get_pwm_count(), get_sdcard_slowdown(), get_singleton(), io_enabled(), and watchdog_enabled().
pwm_count
AP_Int8 AP_BoardConfig::pwm_count private
Definition at line 174 of file AP_BoardConfig.h.
Referenced by get_pwm_count().
rtc
AP_RTC AP_BoardConfig::rtc private
Definition at line 219 of file AP_BoardConfig.h.
var_info
const AP_Param::GroupInfo AP_BoardConfig::var_info static
Definition at line 53 of file AP_BoardConfig.h.
Referenced by AP_BoardConfig().
vehicleSerialNumber
AP_Int16 AP_BoardConfig::vehicleSerialNumber private
Definition at line 173 of file AP_BoardConfig.h.
The documentation for this class was generated from the following files:
libraries/AP_BoardConfig/AP_BoardConfig.h
libraries/AP_BoardConfig/AP_BoardConfig.cpp
libraries/AP_BoardConfig/board_drivers.cpp