APM:Libraries: AC_Fence Class Reference
AC_Fence Class Reference
#include <AC_Fence.h>
Public Member Functions
AC_Fence ()
Default constructor.
AC_Fence (const AC_Fence &other)=delete
AC_Fence & operator= (const AC_Fence &)=delete
void enable (bool value)
enable - allows fence to be enabled/disabled. Note: this does not update the eeprom saved value
bool enabled () const
enabled - returns true if fence is enabled
uint8_t get_enabled_fences () const
get_enabled_fences - returns bitmask of enabled fences
bool pre_arm_check (const char *&fail_msg) const
pre_arm_check - returns true if all pre-takeoff checks have completed successfully
uint8_t check ()
check - returns the fence type that has been breached (if any)
bool check_destination_within_fence (const Location &loc)
uint8_t get_breaches () const
get_breaches - returns bit mask of the fence types that have been breached
uint32_t get_breach_time () const
get_breach_time - returns time the fence was breached
uint16_t get_breach_count () const
get_breach_count - returns number of times we have breached the fence
float get_breach_distance (uint8_t fence_type) const
get_breach_distance - returns distance in meters outside of the given fence
uint8_t get_action () const
get_action - getter for user requested action on limit breach
float get_safe_alt_max () const
get_safe_alt - returns maximum safe altitude (i.e. alt_max - margin)
float get_safe_alt_min () const
get_safe_alt_min - returns the minimum safe altitude (i.e. alt_min - margin)
float get_radius () const
get_radius - returns the fence radius in meters
float get_margin () const
get_margin - returns the fence margin in meters
void manual_recovery_start ()
bool is_polygon_valid () const
returns true if polygon fence is valid (i.e. has at least 3 sides)
Vector2f * get_boundary_points (uint16_t &num_points) const
returns pointer to array of polygon points and num_points is filled in with the total number
bool boundary_breached (const Vector2f &location, uint16_t num_points, const Vector2f *points) const
returns true if we've breached the polygon boundary. simple passthrough to underlying _poly_loader object
void handle_msg (GCS_MAVLINK &link, mavlink_message_t *msg)
handler for polygon fence messages with GCS
uint32_t get_boundary_update_ms () const
return system time of last update to the boundary (allows external detection of boundary changes)
bool sys_status_present () const
bool sys_status_enabled () const
bool sys_status_failed () const
Static Public Member Functions
static AC_Fence * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool check_fence_alt_max ()
check_fence_alt_max - true if alt fence has been newly breached
bool check_fence_polygon ()
check_fence_polygon - true if polygon fence has been newly breached
bool check_fence_circle ()
check_fence_circle - true if circle fence has been newly breached
void record_breach (uint8_t fence_type)
record_breach - update breach bitmask, time and count
void clear_breach (uint8_t fence_type)
clear_breach - update breach bitmask, time and count
bool pre_arm_check_polygon (const char *&fail_msg) const
bool pre_arm_check_circle (const char *&fail_msg) const
bool pre_arm_check_alt (const char *&fail_msg) const
bool load_polygon_from_eeprom ()
load polygon points stored in eeprom into boundary array and perform validation. returns true if load successfully completed
bool polygon_fence_is_breached ()
Private Attributes
AP_Int8 _enabled
AP_Int8 _enabled_fences
AP_Int8 _action
AP_Float _alt_max
AP_Float _alt_min
AP_Float _circle_radius
AP_Float _margin
AP_Int8 _total
float _alt_max_backup
float _circle_radius_backup
float _alt_max_breach_distance
float _circle_breach_distance
float _home_distance
float _curr_alt
uint8_t _breached_fences
uint32_t _breach_time
uint16_t _breach_count
uint32_t _manual_recovery_start_ms
AC_PolyFence_loader _poly_loader
Vector2f * _boundary = nullptr
uint8_t _boundary_num_points = 0
bool _boundary_create_attempted = false
bool _boundary_valid = false
uint32_t _boundary_update_ms
Static Private Attributes
static AC_Fence * _singleton
Detailed Description
Definition at line 35 of file AC_Fence.h.
Constructor & Destructor Documentation
AC_Fence() [1/2]
AC_Fence::AC_Fence ()
Default constructor.
Definition at line 83 of file AC_Fence.cpp.
AC_Fence() [2/2]
AC_Fence::AC_Fence (const AC_Fence & other) delete
Member Function Documentation
boundary_breached()
bool AC_Fence::boundary_breached (const Vector2f & location, uint16_t num_points, const Vector2f * points) const
returns true if we've breached the polygon boundary. simple passthrough to underlying _poly_loader object
Definition at line 482 of file AC_Fence.cpp.
check()
uint8_t AC_Fence::check ()
check - returns the fence type that has been breached (if any)
check - returns bitmask of fence types breached (if any)
methods to check we are within the boundaries and recover
Definition at line 328 of file AC_Fence.cpp.
check_destination_within_fence()
bool AC_Fence::check_destination_within_fence (const Location & loc)
Definition at line 368 of file AC_Fence.cpp.
check_fence_alt_max()
bool AC_Fence::check_fence_alt_max () private
check_fence_alt_max - true if alt fence has been newly breached
Definition at line 191 of file AC_Fence.cpp.
Referenced by check().
check_fence_circle()
bool AC_Fence::check_fence_circle () private
check_fence_circle - true if circle fence has been newly breached
Definition at line 283 of file AC_Fence.cpp.
Referenced by check().
check_fence_polygon()
bool AC_Fence::check_fence_polygon () private
check_fence_polygon - true if polygon fence has been newly breached
Definition at line 237 of file AC_Fence.cpp.
Referenced by check().
clear_breach()
void AC_Fence::clear_breach (uint8_t fence_type) private
clear_breach - update breach bitmask, time and count
Definition at line 419 of file AC_Fence.cpp.
Referenced by check_fence_alt_max(), check_fence_circle(), check_fence_polygon(), and enable().
enable()
void AC_Fence::enable (bool value)
enable - allows fence to be enabled/disabled. Note: this does not update the eeprom saved value
Definition at line 94 of file AC_Fence.cpp.
Referenced by GCS_MAVLINK::handle_command_do_fence_enable().
enabled()
bool AC_Fence::enabled () const inline
enabled - returns true if fence is enabled
Definition at line 48 of file AC_Fence.h.
Referenced by GCS_MAVLINK::send_fence_status().
get_action()
uint8_t AC_Fence::get_action () const inline
get_action - getter for user requested action on limit breach
Definition at line 79 of file AC_Fence.h.
get_boundary_points()
Vector2f * AC_Fence::get_boundary_points (uint16_t & num_points) const
returns pointer to array of polygon points and num_points is filled in with the total number
returns pointer to array of polygon points and num_points is filled in with the total number points are offsets from EKF origin in NE frame
Definition at line 462 of file AC_Fence.cpp.
Referenced by AC_Avoid::adjust_velocity_polygon_fence(), AP_OABendyRuler::calc_margin_from_polygon_fence(), AP_OADijkstra::create_polygon_fence_visgraph(), AP_OADijkstra::create_polygon_fence_with_margin(), and AP_OADijkstra::update_visgraph().
get_boundary_update_ms()
uint32_t AC_Fence::get_boundary_update_ms () const inline
return system time of last update to the boundary (allows external detection of boundary changes)
Definition at line 116 of file AC_Fence.h.
Referenced by AP_OADijkstra::check_polygon_fence_updated(), and AP_OADijkstra::create_polygon_fence_with_margin().
get_breach_count()
uint16_t AC_Fence::get_breach_count () const inline
get_breach_count - returns number of times we have breached the fence
Definition at line 73 of file AC_Fence.h.
Referenced by GCS_MAVLINK::send_fence_status().
get_breach_distance()
float AC_Fence::get_breach_distance (uint8_t fence_type) const
get_breach_distance - returns distance in meters outside of the given fence
Definition at line 431 of file AC_Fence.cpp.
get_breach_time()
uint32_t AC_Fence::get_breach_time () const inline
get_breach_time - returns time the fence was breached
Definition at line 70 of file AC_Fence.h.
Referenced by GCS_MAVLINK::send_fence_status().
get_breaches()
uint8_t AC_Fence::get_breaches () const inline
get_breaches - returns bit mask of the fence types that have been breached
Definition at line 67 of file AC_Fence.h.
Referenced by AC_Avoid::adjust_velocity_circle_fence(), AC_Avoid::adjust_velocity_polygon_fence(), GCS_MAVLINK::send_fence_status(), and sys_status_failed().
get_enabled_fences()
uint8_t AC_Fence::get_enabled_fences () const
get_enabled_fences - returns bitmask of enabled fences
Definition at line 103 of file AC_Fence.cpp.
Referenced by AC_Avoid::adjust_velocity_circle_fence(), AC_Avoid::adjust_velocity_polygon_fence(), AC_Avoid::adjust_velocity_z(), AP_OABendyRuler::calc_margin_from_circular_fence(), AP_OABendyRuler::calc_margin_from_polygon_fence(), check_destination_within_fence(), and AP_OADijkstra::polygon_fence_enabled().
get_margin()
float AC_Fence::get_margin () const inline
get_margin - returns the fence margin in meters
Definition at line 91 of file AC_Fence.h.
Referenced by AC_Avoid::adjust_velocity_beacon_fence(), AC_Avoid::adjust_velocity_circle_fence(), and AC_Avoid::adjust_velocity_polygon_fence().
get_radius()
float AC_Fence::get_radius () const inline
get_radius - returns the fence radius in meters
Definition at line 88 of file AC_Fence.h.
Referenced by AC_Avoid::adjust_velocity_circle_fence(), and AP_OABendyRuler::calc_margin_from_circular_fence().
get_safe_alt_max()
float AC_Fence::get_safe_alt_max () const inline
get_safe_alt - returns maximum safe altitude (i.e. alt_max - margin)
Definition at line 82 of file AC_Fence.h.
Referenced by AC_Avoid::adjust_velocity_z().
get_safe_alt_min()
float AC_Fence::get_safe_alt_min () const inline
get_safe_alt_min - returns the minimum safe altitude (i.e. alt_min - margin)
Definition at line 85 of file AC_Fence.h.
get_singleton()
static AC_Fence* AC_Fence::get_singleton () inline static
Definition at line 126 of file AC_Fence.h.
Referenced by AP_OABendyRuler::calc_margin_from_circular_fence(), AP_OABendyRuler::calc_margin_from_polygon_fence(), AP_OADijkstra::check_polygon_fence_updated(), AP_OADijkstra::create_polygon_fence_visgraph(), AP_OADijkstra::create_polygon_fence_with_margin(), AP::fence(), AP_OADijkstra::polygon_fence_enabled(), and AP_OADijkstra::update_visgraph().
handle_msg()
void AC_Fence::handle_msg (GCS_MAVLINK & link, mavlink_message_t * msg)
handler for polygon fence messages with GCS
Definition at line 488 of file AC_Fence.cpp.
Referenced by GCS_MAVLINK::handle_fence_message().
is_polygon_valid()
bool AC_Fence::is_polygon_valid () const inline
returns true if polygon fence is valid (i.e. has at least 3 sides)
polygon related methods
Definition at line 103 of file AC_Fence.h.
Referenced by AP_OABendyRuler::calc_margin_from_polygon_fence(), and AP_OADijkstra::polygon_fence_enabled().
load_polygon_from_eeprom()
bool AC_Fence::load_polygon_from_eeprom () private
load polygon points stored in eeprom into boundary array and perform validation. returns true if load successfully completed
load polygon points stored in eeprom into boundary array and perform validation
Definition at line 537 of file AC_Fence.cpp.
Referenced by polygon_fence_is_breached().
manual_recovery_start()
void AC_Fence::manual_recovery_start ()
manual_recovery_start - caller indicates that pilot is re-taking manual control so fence should be disabled for 10 seconds should be called whenever the pilot changes the flight mode has no effect if no breaches have occurred
manual_recovery_start - caller indicates that pilot is re-taking manual control so fence should be disabled for 10 seconds has no effect if no breaches have occurred
Definition at line 450 of file AC_Fence.cpp.
operator=()
AC_Fence& AC_Fence::operator= (const AC_Fence &) delete
polygon_fence_is_breached()
bool AC_Fence::polygon_fence_is_breached () private
Definition at line 254 of file AC_Fence.cpp.
Referenced by check_fence_polygon().
pre_arm_check()
bool AC_Fence::pre_arm_check (const char *& fail_msg) const
pre_arm_check - returns true if all pre-takeoff checks have completed successfully
Definition at line 149 of file AC_Fence.cpp.
Referenced by AP_Arming::fence_checks().
pre_arm_check_alt()
bool AC_Fence::pre_arm_check_alt (const char *& fail_msg) const private
Definition at line 138 of file AC_Fence.cpp.
Referenced by pre_arm_check().
pre_arm_check_circle()
bool AC_Fence::pre_arm_check_circle (const char *& fail_msg) const private
Definition at line 128 of file AC_Fence.cpp.
Referenced by pre_arm_check().
pre_arm_check_polygon()
bool AC_Fence::pre_arm_check_polygon (const char *& fail_msg) const private
Definition at line 112 of file AC_Fence.cpp.
Referenced by pre_arm_check().
record_breach()
void AC_Fence::record_breach (uint8_t fence_type) private
record_breach - update breach bitmask, time and count
Definition at line 402 of file AC_Fence.cpp.
Referenced by check_fence_alt_max(), check_fence_circle(), and check_fence_polygon().
sys_status_enabled()
bool AC_Fence::sys_status_enabled () const
Definition at line 590 of file AC_Fence.cpp.
sys_status_failed()
bool AC_Fence::sys_status_failed () const
Definition at line 601 of file AC_Fence.cpp.
sys_status_present()
bool AC_Fence::sys_status_present () const
Definition at line 585 of file AC_Fence.cpp.
Referenced by sys_status_enabled(), and sys_status_failed().
Member Data Documentation
_action
AP_Int8 AC_Fence::_action private
Definition at line 160 of file AC_Fence.h.
Referenced by get_action(), and sys_status_enabled().
_alt_max
AP_Float AC_Fence::_alt_max private
Definition at line 161 of file AC_Fence.h.
Referenced by check_destination_within_fence(), check_fence_alt_max(), get_safe_alt_max(), pre_arm_check_alt(), and sys_status_failed().
_alt_max_backup
float AC_Fence::_alt_max_backup private
Definition at line 168 of file AC_Fence.h.
Referenced by check_fence_alt_max().
_alt_max_breach_distance
float AC_Fence::_alt_max_breach_distance private
Definition at line 172 of file AC_Fence.h.
Referenced by check_fence_alt_max(), and get_breach_distance().
_alt_min
AP_Float AC_Fence::_alt_min private
Definition at line 162 of file AC_Fence.h.
Referenced by get_safe_alt_min().
_boundary
Vector2f* AC_Fence::_boundary = nullptr private
Definition at line 189 of file AC_Fence.h.
Referenced by check_destination_within_fence(), get_boundary_points(), load_polygon_from_eeprom(), and polygon_fence_is_breached().
_boundary_create_attempted
bool AC_Fence::_boundary_create_attempted = false private
Definition at line 191 of file AC_Fence.h.
Referenced by load_polygon_from_eeprom().
_boundary_num_points
uint8_t AC_Fence::_boundary_num_points = 0 private
Definition at line 190 of file AC_Fence.h.
Referenced by check_destination_within_fence(), get_boundary_points(), handle_msg(), load_polygon_from_eeprom(), and polygon_fence_is_breached().
_boundary_update_ms
uint32_t AC_Fence::_boundary_update_ms private
Definition at line 193 of file AC_Fence.h.
Referenced by get_boundary_update_ms(), and load_polygon_from_eeprom().
_boundary_valid
bool AC_Fence::_boundary_valid = false private
Definition at line 192 of file AC_Fence.h.
Referenced by get_boundary_points(), is_polygon_valid(), load_polygon_from_eeprom(), polygon_fence_is_breached(), pre_arm_check_polygon(), and sys_status_failed().
_breach_count
uint16_t AC_Fence::_breach_count private
Definition at line 183 of file AC_Fence.h.
Referenced by get_breach_count(), and record_breach().
_breach_time
uint32_t AC_Fence::_breach_time private
Definition at line 182 of file AC_Fence.h.
Referenced by get_breach_time(), and record_breach().
_breached_fences
uint8_t AC_Fence::_breached_fences private
Definition at line 181 of file AC_Fence.h.
Referenced by check_fence_alt_max(), check_fence_circle(), check_fence_polygon(), clear_breach(), get_breaches(), manual_recovery_start(), pre_arm_check(), and record_breach().
_circle_breach_distance
float AC_Fence::_circle_breach_distance private
Definition at line 173 of file AC_Fence.h.
Referenced by check_fence_circle(), and get_breach_distance().
_circle_radius
AP_Float AC_Fence::_circle_radius private
Definition at line 163 of file AC_Fence.h.
Referenced by check_destination_within_fence(), check_fence_circle(), get_radius(), pre_arm_check_circle(), and sys_status_failed().
_circle_radius_backup
float AC_Fence::_circle_radius_backup private
Definition at line 169 of file AC_Fence.h.
Referenced by check_fence_circle().
_curr_alt
float AC_Fence::_curr_alt private
Definition at line 177 of file AC_Fence.h.
Referenced by check_fence_alt_max().
_enabled
AP_Int8 AC_Fence::_enabled private
Definition at line 158 of file AC_Fence.h.
Referenced by check(), enable(), enabled(), get_enabled_fences(), pre_arm_check(), and sys_status_present().
_enabled_fences
AP_Int8 AC_Fence::_enabled_fences private
Definition at line 159 of file AC_Fence.h.
Referenced by check(), check_fence_alt_max(), check_fence_circle(), get_enabled_fences(), polygon_fence_is_breached(), pre_arm_check(), pre_arm_check_polygon(), and sys_status_failed().
_home_distance
float AC_Fence::_home_distance private
Definition at line 176 of file AC_Fence.h.
Referenced by check_fence_circle().
_manual_recovery_start_ms
uint32_t AC_Fence::_manual_recovery_start_ms private
Definition at line 185 of file AC_Fence.h.
Referenced by check(), and manual_recovery_start().
_margin
AP_Float AC_Fence::_margin private
Definition at line 164 of file AC_Fence.h.
Referenced by get_margin(), get_safe_alt_max(), and get_safe_alt_min().
_poly_loader
AC_PolyFence_loader AC_Fence::_poly_loader private
Definition at line 188 of file AC_Fence.h.
Referenced by boundary_breached(), check_destination_within_fence(), handle_msg(), load_polygon_from_eeprom(), and polygon_fence_is_breached().
_singleton
AC_Fence * AC_Fence::_singleton static private
Definition at line 129 of file AC_Fence.h.
Referenced by AC_Fence(), and get_singleton().
_total
AP_Int8 AC_Fence::_total private
Definition at line 165 of file AC_Fence.h.
Referenced by handle_msg(), load_polygon_from_eeprom(), and polygon_fence_is_breached().
var_info
const AP_Param::GroupInfo AC_Fence::var_info static
Definition at line 118 of file AC_Fence.h.
Referenced by AC_Fence().
The documentation for this class was generated from the following files:
libraries/AC_Fence/AC_Fence.h
libraries/AC_Fence/AC_Fence.cpp