APM:Libraries: Linux::Led_Sysfs Class Reference
Linux::Led_Sysfs Class Reference
#include <Led_Sysfs.h>
Public Member Functions
bool init ()
bool set_brightness (uint8_t brightness)
Led_Sysfs (const char *led_name)
~Led_Sysfs ()
Private Attributes
int _brightness_fd = -1
int _max_brightness = 0
const char * _led_name = nullptr
Detailed Description
Definition at line 26 of file Led_Sysfs.h.
Constructor & Destructor Documentation
Led_Sysfs()
Led_Sysfs::Led_Sysfs (const char * led_name)
Definition at line 33 of file Led_Sysfs.cpp.
~Led_Sysfs()
Led_Sysfs::~Led_Sysfs ()
Definition at line 38 of file Led_Sysfs.cpp.
Member Function Documentation
init()
bool Led_Sysfs::init (void)
Definition at line 45 of file Led_Sysfs.cpp.
Referenced by DiscoLED::hw_init(), and Led_Sysfs::hw_init().
set_brightness()
bool Led_Sysfs::set_brightness (uint8_t brightness)
Definition at line 76 of file Led_Sysfs.cpp.
Referenced by DiscoLED::hw_set_rgb(), and Led_Sysfs::hw_set_rgb().
Member Data Documentation
_brightness_fd
int Linux::Led_Sysfs::_brightness_fd = -1 private
Definition at line 35 of file Led_Sysfs.h.
Referenced by init(), set_brightness(), and ~Led_Sysfs().
_led_name
const char* Linux::Led_Sysfs::_led_name = nullptr private
Definition at line 37 of file Led_Sysfs.h.
Referenced by init().
_max_brightness
int Linux::Led_Sysfs::_max_brightness = 0 private
Definition at line 36 of file Led_Sysfs.h.
Referenced by init(), and set_brightness().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Led_Sysfs.h
libraries/AP_HAL_Linux/Led_Sysfs.cpp