APM:Libraries: RC_Channels_PIDTest Class Reference
RC_Channels_PIDTest Class Reference
Public Member Functions
RC_Channel * channel (uint8_t chan) override
Public Member Functions inherited from RC_Channels
RC_Channels (void)
void init (void)
uint8_t get_radio_in (uint16_t *chans, const uint8_t num_channels)
bool read_input (void)
class RC_Channel * find_channel_for_option (const RC_Channel::aux_func_t option)
bool duplicate_options_exist ()
void init_aux_all ()
void read_aux_all ()
void reset_mode_switch ()
virtual void read_mode_switch ()
virtual bool has_valid_input () const
bool gcs_overrides_enabled () const
void set_gcs_overrides_enabled (bool enable)
bool ignore_rc_failsafe (void) const
bool ignore_overrides () const
bool ignore_receiver () const
float override_timeout_ms () const
Public Attributes
RC_Channel_PIDTest obj_channels [NUM_RC_CHANNELS]
Private Member Functions
int8_t flight_mode_channel_number () const override
Additional Inherited Members
Static Public Member Functions inherited from RC_Channels
static RC_Channels * get_singleton ()
static uint16_t get_radio_in (const uint8_t chan)
static RC_Channel * rc_channel (const uint8_t chan)
static uint8_t get_valid_channel_count (void)
static int16_t get_receiver_rssi (void)
static void clear_overrides (void)
static bool receiver_bind (const int dsmMode)
static void set_override (const uint8_t chan, const int16_t value, const uint32_t timestamp_ms=0)
static bool has_active_overrides (void)
Static Public Attributes inherited from RC_Channels
static const struct AP_Param::GroupInfo var_info []
Protected Types inherited from RC_Channels
enum Option { Option::IGNORE_RECEIVER = (1 << 0), Option::IGNORE_OVERRIDES = (1 << 1), Option::IGNORE_FAILSAFE = (1 << 2) }
Protected Member Functions inherited from RC_Channels
void new_override_received ()
Detailed Description
Definition at line 27 of file AC_PID_test.cpp.
Member Function Documentation
channel()
RC_Channel* RC_Channels_PIDTest::channel (uint8_t chan) inline override virtual
Implements RC_Channels.
Definition at line 30 of file AC_PID_test.cpp.
Referenced by RC_Channels::clear_overrides(), RC_Channels::has_active_overrides(), and RC_Channels::set_override().
flight_mode_channel_number()
int8_t RC_Channels_PIDTest::flight_mode_channel_number () const inline override private virtual
Implements RC_Channels.
Definition at line 36 of file AC_PID_test.cpp.
Member Data Documentation
obj_channels
RC_Channel_PIDTest RC_Channels_PIDTest::obj_channels[NUM_RC_CHANNELS]
Definition at line 34 of file AC_PID_test.cpp.
Referenced by channel().
The documentation for this class was generated from the following file:
libraries/AC_PID/examples/AC_PID_test/AC_PID_test.cpp