APM:Libraries: CompassCalibrator Class Reference
CompassCalibrator Class Reference
#include <CompassCalibrator.h>
Classes
class AttitudeSample
class CompassSample
class param_t
Public Types
typedef uint8_t completion_mask_t[10]
Public Member Functions
CompassCalibrator ()
void start (bool retry, float delay, uint16_t offset_max, uint8_t compass_idx)
void clear ()
void update (bool &failure)
void new_sample (const Vector3f &sample)
bool check_for_timeout ()
bool running () const
void set_orientation (enum Rotation orientation, bool is_external, bool fix_orientation)
void set_tolerance (float tolerance)
void get_calibration (Vector3f &offsets, Vector3f &diagonals, Vector3f &offdiagonals)
enum Rotation get_orientation (void)
enum Rotation get_original_orientation (void)
float get_completion_percent () const
completion_mask_t & get_completion_mask ()
enum compass_cal_status_t get_status () const
float get_fitness () const
float get_orientation_confidence () const
uint8_t get_attempt () const
Private Member Functions
bool set_status (compass_cal_status_t status)
bool accept_sample (const Vector3f &sample)
bool accept_sample (const CompassSample &sample)
bool fit_acceptable ()
void reset_state ()
void initialize_fit ()
bool fitting () const
void thin_samples ()
float calc_residual (const Vector3f &sample, const param_t &params) const
float calc_mean_squared_residuals (const param_t &params) const
float calc_mean_squared_residuals () const
void calc_initial_offset ()
void calc_sphere_jacob (const Vector3f &sample, const param_t &params, float *ret) const
void run_sphere_fit ()
void calc_ellipsoid_jacob (const Vector3f &sample, const param_t &params, float *ret) const
void run_ellipsoid_fit ()
void update_completion_mask (const Vector3f &v)
void update_completion_mask ()
Vector3f calculate_earth_field (CompassSample &sample, enum Rotation r)
bool calculate_orientation ()
Private Attributes
enum Rotation _orientation
enum Rotation _orig_orientation
bool _is_external
bool _check_orientation
bool _fix_orientation
uint8_t _compass_idx
enum compass_cal_status_t _status
uint32_t _last_sample_ms
float _delay_start_sec
uint32_t _start_time_ms
bool _retry
float _tolerance
uint8_t _attempt
uint16_t _offset_max
completion_mask_t _completion_mask
class param_t _params
uint16_t _fit_step
CompassSample * _sample_buffer
float _fitness
float _initial_fitness
float _sphere_lambda
float _ellipsoid_lambda
uint16_t _samples_collected
uint16_t _samples_thinned
float _orientation_confidence
Detailed Description
Definition at line 22 of file CompassCalibrator.h.
Member Typedef Documentation
completion_mask_t
typedef uint8_t CompassCalibrator::completion_mask_t[10]
Definition at line 24 of file CompassCalibrator.h.
Constructor & Destructor Documentation
CompassCalibrator()
CompassCalibrator::CompassCalibrator ()
Definition at line 72 of file CompassCalibrator.cpp.
Member Function Documentation
accept_sample() [1/2]
bool CompassCalibrator::accept_sample (const Vector3f & sample) private
Definition at line 412 of file CompassCalibrator.cpp.
Referenced by accept_sample(), new_sample(), and thin_samples().
accept_sample() [2/2]
bool CompassCalibrator::accept_sample (const CompassSample & sample) private
Definition at line 433 of file CompassCalibrator.cpp.
calc_ellipsoid_jacob()
void CompassCalibrator::calc_ellipsoid_jacob (const Vector3f & sample, const param_t & params, float * ret) const private
Definition at line 581 of file CompassCalibrator.cpp.
Referenced by run_ellipsoid_fit().
calc_initial_offset()
void CompassCalibrator::calc_initial_offset () private
Definition at line 489 of file CompassCalibrator.cpp.
Referenced by update().
calc_mean_squared_residuals() [1/2]
float CompassCalibrator::calc_mean_squared_residuals (const param_t & params) const private
Definition at line 451 of file CompassCalibrator.cpp.
calc_mean_squared_residuals() [2/2]
float CompassCalibrator::calc_mean_squared_residuals () const private
Definition at line 446 of file CompassCalibrator.cpp.
Referenced by initialize_fit(), run_ellipsoid_fit(), and run_sphere_fit().
calc_residual()
float CompassCalibrator::calc_residual (const Vector3f & sample, const param_t & params) const private
Definition at line 437 of file CompassCalibrator.cpp.
Referenced by calc_mean_squared_residuals(), run_ellipsoid_fit(), and run_sphere_fit().
calc_sphere_jacob()
void CompassCalibrator::calc_sphere_jacob (const Vector3f & sample, const param_t & params, float * ret) const private
Definition at line 466 of file CompassCalibrator.cpp.
Referenced by run_sphere_fit().
calculate_earth_field()
Vector3f CompassCalibrator::calculate_earth_field (CompassSample & sample, enum Rotation r) private
Definition at line 744 of file CompassCalibrator.cpp.
Referenced by calculate_orientation().
calculate_orientation()
bool CompassCalibrator::calculate_orientation (void) private
Definition at line 776 of file CompassCalibrator.cpp.
Referenced by update().
check_for_timeout()
bool CompassCalibrator::check_for_timeout ()
Definition at line 155 of file CompassCalibrator.cpp.
clear()
void CompassCalibrator::clear ()
Definition at line 79 of file CompassCalibrator.cpp.
Referenced by Compass::_accept_calibration_mask(), Compass::_cancel_calibration(), and CompassCalibrator().
fit_acceptable()
bool CompassCalibrator::fit_acceptable () private
Definition at line 352 of file CompassCalibrator.cpp.
Referenced by calculate_orientation(), and update().
fitting()
bool CompassCalibrator::fitting () const private
Definition at line 226 of file CompassCalibrator.cpp.
Referenced by update().
get_attempt()
uint8_t CompassCalibrator::get_attempt () const inline
Definition at line 57 of file CompassCalibrator.h.
Referenced by Compass::send_mag_cal_progress().
get_calibration()
void CompassCalibrator::get_calibration (Vector3f & offsets, Vector3f & diagonals, Vector3f & offdiagonals)
Definition at line 97 of file CompassCalibrator.cpp.
Referenced by Compass::_accept_calibration(), and Compass::send_mag_cal_report().
get_completion_mask()
CompassCalibrator::completion_mask_t & CompassCalibrator::get_completion_mask ()
Definition at line 150 of file CompassCalibrator.cpp.
get_completion_percent()
float CompassCalibrator::get_completion_percent () const
Definition at line 107 of file CompassCalibrator.cpp.
get_fitness()
float CompassCalibrator::get_fitness () const inline
Definition at line 55 of file CompassCalibrator.h.
Referenced by Compass::send_mag_cal_report().
get_orientation()
enum Rotation CompassCalibrator::get_orientation (void) inline
Definition at line 49 of file CompassCalibrator.h.
Referenced by Compass::_accept_calibration(), and Compass::send_mag_cal_report().
get_orientation_confidence()
float CompassCalibrator::get_orientation_confidence () const inline
Definition at line 56 of file CompassCalibrator.h.
Referenced by Compass::send_mag_cal_report().
get_original_orientation()
enum Rotation CompassCalibrator::get_original_orientation (void) inline
Definition at line 50 of file CompassCalibrator.h.
Referenced by Compass::send_mag_cal_report().
get_status()
enum compass_cal_status_t CompassCalibrator::get_status () const inline
Definition at line 54 of file CompassCalibrator.h.
Referenced by Compass::_accept_calibration(), Compass::send_mag_cal_progress(), and Compass::send_mag_cal_report().
initialize_fit()
void CompassCalibrator::initialize_fit () private
Definition at line 230 of file CompassCalibrator.cpp.
Referenced by calculate_orientation(), reset_state(), and set_status().
new_sample()
void CompassCalibrator::new_sample (const Vector3f & sample)
Definition at line 165 of file CompassCalibrator.cpp.
Referenced by AP_Compass_Backend::publish_raw_field().
reset_state()
void CompassCalibrator::reset_state () private
Definition at line 243 of file CompassCalibrator.cpp.
Referenced by set_status().
run_ellipsoid_fit()
void CompassCalibrator::run_ellipsoid_fit () private
Definition at line 610 of file CompassCalibrator.cpp.
Referenced by calculate_orientation(), and update().
run_sphere_fit()
void CompassCalibrator::run_sphere_fit () private
Definition at line 499 of file CompassCalibrator.cpp.
Referenced by calculate_orientation(), and update().
running()
bool CompassCalibrator::running () const
Definition at line 222 of file CompassCalibrator.cpp.
Referenced by check_for_timeout(), fitting(), new_sample(), and start().
set_orientation()
void CompassCalibrator::set_orientation (enum Rotation orientation, bool is_external, bool fix_orientation) inline
Definition at line 38 of file CompassCalibrator.h.
Referenced by Compass::_start_calibration().
set_status()
bool CompassCalibrator::set_status (compass_cal_status_t status) private
Definition at line 255 of file CompassCalibrator.cpp.
Referenced by calculate_orientation(), check_for_timeout(), clear(), new_sample(), start(), and update().
set_tolerance()
void CompassCalibrator::set_tolerance (float tolerance) inline
Definition at line 46 of file CompassCalibrator.h.
Referenced by Compass::_start_calibration().
start()
void CompassCalibrator::start (bool retry, float delay, uint16_t offset_max, uint8_t compass_idx)
Definition at line 83 of file CompassCalibrator.cpp.
Referenced by Compass::_start_calibration().
thin_samples()
void CompassCalibrator::thin_samples () private
Definition at line 370 of file CompassCalibrator.cpp.
Referenced by set_status().
update()
void CompassCalibrator::update (bool & failure)
Definition at line 180 of file CompassCalibrator.cpp.
Referenced by Compass::cal_update().
update_completion_mask() [1/2]
void CompassCalibrator::update_completion_mask (const Vector3f & v) private
Update _completion_mask for the geodesic section of v. Corrections are applied to v with _params.
Parameters
v[in] A vector representing one calibration sample.
Definition at line 127 of file CompassCalibrator.cpp.
update_completion_mask() [2/2]
void CompassCalibrator::update_completion_mask () private
Reset and update _completion_mask with the current samples.
Definition at line 142 of file CompassCalibrator.cpp.
Referenced by new_sample(), run_ellipsoid_fit(), run_sphere_fit(), and thin_samples().
Member Data Documentation
_attempt
uint8_t CompassCalibrator::_attempt private
Definition at line 115 of file CompassCalibrator.h.
Referenced by get_attempt(), set_status(), and start().
_check_orientation
bool CompassCalibrator::_check_orientation private
Definition at line 101 of file CompassCalibrator.h.
Referenced by calculate_orientation(), and set_orientation().
_compass_idx
uint8_t CompassCalibrator::_compass_idx private
Definition at line 103 of file CompassCalibrator.h.
Referenced by calculate_orientation(), and start().
_completion_mask
completion_mask_t CompassCalibrator::_completion_mask private
Definition at line 118 of file CompassCalibrator.h.
Referenced by get_completion_mask(), reset_state(), and update_completion_mask().
_delay_start_sec
float CompassCalibrator::_delay_start_sec private
Definition at line 111 of file CompassCalibrator.h.
Referenced by set_status(), and start().
_ellipsoid_lambda
float CompassCalibrator::_ellipsoid_lambda private
Definition at line 127 of file CompassCalibrator.h.
Referenced by initialize_fit(), and run_ellipsoid_fit().
_fit_step
uint16_t CompassCalibrator::_fit_step private
Definition at line 122 of file CompassCalibrator.h.
Referenced by initialize_fit(), and update().
_fitness
float CompassCalibrator::_fitness private
Definition at line 124 of file CompassCalibrator.h.
Referenced by fit_acceptable(), get_fitness(), initialize_fit(), run_ellipsoid_fit(), run_sphere_fit(), and update().
_fix_orientation
bool CompassCalibrator::_fix_orientation private
Definition at line 102 of file CompassCalibrator.h.
Referenced by calculate_orientation(), and set_orientation().
_initial_fitness
float CompassCalibrator::_initial_fitness private
Definition at line 125 of file CompassCalibrator.h.
Referenced by initialize_fit(), and update().
_is_external
bool CompassCalibrator::_is_external private
Definition at line 100 of file CompassCalibrator.h.
Referenced by calculate_orientation(), and set_orientation().
_last_sample_ms
uint32_t CompassCalibrator::_last_sample_ms private
Definition at line 108 of file CompassCalibrator.h.
Referenced by check_for_timeout(), and new_sample().
_offset_max
uint16_t CompassCalibrator::_offset_max private
Definition at line 116 of file CompassCalibrator.h.
Referenced by fit_acceptable(), and start().
_orientation
enum Rotation CompassCalibrator::_orientation private
Definition at line 98 of file CompassCalibrator.h.
Referenced by calculate_earth_field(), calculate_orientation(), get_orientation(), and set_orientation().
_orientation_confidence
float CompassCalibrator::_orientation_confidence private
Definition at line 130 of file CompassCalibrator.h.
Referenced by calculate_orientation(), and get_orientation_confidence().
_orig_orientation
enum Rotation CompassCalibrator::_orig_orientation private
Definition at line 99 of file CompassCalibrator.h.
Referenced by get_original_orientation(), and set_orientation().
_params
class param_t CompassCalibrator::_params private
Definition at line 121 of file CompassCalibrator.h.
Referenced by accept_sample(), calc_initial_offset(), calc_mean_squared_residuals(), calculate_earth_field(), calculate_orientation(), fit_acceptable(), get_calibration(), initialize_fit(), reset_state(), run_ellipsoid_fit(), run_sphere_fit(), and update_completion_mask().
_retry
bool CompassCalibrator::_retry private
Definition at line 113 of file CompassCalibrator.h.
Referenced by check_for_timeout(), set_status(), and start().
_sample_buffer
CompassSample* CompassCalibrator::_sample_buffer private
Definition at line 123 of file CompassCalibrator.h.
Referenced by accept_sample(), calc_initial_offset(), calc_mean_squared_residuals(), calculate_orientation(), new_sample(), run_ellipsoid_fit(), run_sphere_fit(), set_status(), thin_samples(), and update_completion_mask().
_samples_collected
uint16_t CompassCalibrator::_samples_collected private
Definition at line 128 of file CompassCalibrator.h.
Referenced by accept_sample(), calc_initial_offset(), calc_mean_squared_residuals(), calculate_orientation(), fitting(), get_completion_percent(), initialize_fit(), new_sample(), reset_state(), run_ellipsoid_fit(), run_sphere_fit(), thin_samples(), and update_completion_mask().
_samples_thinned
uint16_t CompassCalibrator::_samples_thinned private
Definition at line 129 of file CompassCalibrator.h.
Referenced by get_completion_percent(), reset_state(), and thin_samples().
_sphere_lambda
float CompassCalibrator::_sphere_lambda private
Definition at line 126 of file CompassCalibrator.h.
Referenced by initialize_fit(), and run_sphere_fit().
_start_time_ms
uint32_t CompassCalibrator::_start_time_ms private
Definition at line 112 of file CompassCalibrator.h.
Referenced by set_status(), and start().
_status
enum compass_cal_status_t CompassCalibrator::_status private
Definition at line 105 of file CompassCalibrator.h.
Referenced by get_calibration(), get_completion_percent(), get_status(), new_sample(), running(), set_status(), and update().
_tolerance
float CompassCalibrator::_tolerance private
Definition at line 114 of file CompassCalibrator.h.
Referenced by fit_acceptable(), and set_tolerance().
The documentation for this class was generated from the following files:
libraries/AP_Compass/CompassCalibrator.h
libraries/AP_Compass/CompassCalibrator.cpp