APM:Libraries: Linux::UtilRPI Class Reference
Linux::UtilRPI Class Reference
#include <Util_RPI.h>
Public Member Functions
UtilRPI ()
int get_rpi_version () const
Public Member Functions inherited from Linux::Util
void init (int argc, char *const *argv)
bool run_debug_shell (AP_HAL::BetterStream *stream) override
void commandline_arguments (uint8_t &argc, char *const *&argv) override
void set_hw_rtc (uint64_t time_utc_usec) override
const char * get_custom_log_directory () const override final
const char * get_custom_terrain_directory () const override final
const char * get_custom_storage_directory () const override final
void set_custom_log_directory (const char *_custom_log_directory)
void set_custom_terrain_directory (const char *_custom_terrain_directory)
void set_custom_storage_directory (const char *_custom_storage_directory)
bool is_chardev_node (const char *path)
void set_imu_temp (float current) override
void set_imu_target_temp (int8_t *target) override
uint32_t available_memory (void) override
bool get_system_id (char buf[40]) override
bool get_system_id_unformatted (uint8_t buf[], uint8_t &len) override
int write_file (const char *path, const char *fmt,...) FMT_PRINTF(3
int int read_file (const char *path, const char *fmt,...) FMT_SCANF(3
int int perf_counter_t perf_alloc (enum perf_counter_type t, const char *name) override
void perf_begin (perf_counter_t perf) override
void perf_end (perf_counter_t perf) override
void perf_count (perf_counter_t perf) override
int get_hw_arm32 ()
bool toneAlarm_init () override
void toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) override
Public Member Functions inherited from AP_HAL::Util
int snprintf (char *str, size_t size, const char *format,...)
int vsnprintf (char *str, size_t size, const char *format, va_list ap)
void set_soft_armed (const bool b)
bool get_soft_armed () const
uint32_t get_last_armed_change () const
virtual bool was_watchdog_reset () const
bool was_watchdog_safety_off () const
bool was_watchdog_armed () const
virtual const char * get_custom_defaults_file () const
virtual enum safety_state safety_switch_state (void)
virtual uint64_t get_hw_rtc () const
virtual bool flash_bootloader ()
virtual AP_HAL::BetterStream * get_shell_stream ()
virtual void * malloc_type (size_t size, Memory_Type mem_type)
virtual void free_type (void *ptr, size_t size, Memory_Type mem_type)
virtual bool fs_init (void)
Static Public Member Functions
static UtilRPI * from (AP_HAL::Util *util)
Static Public Member Functions inherited from Linux::Util
static Util * from (AP_HAL::Util *util)
Protected Member Functions
int _check_rpi_version ()
Private Attributes
int _rpi_version = 0
Additional Inherited Members
Public Types inherited from AP_HAL::Util
enum safety_state { SAFETY_NONE, SAFETY_DISARMED, SAFETY_ARMED }
enum perf_counter_type { PC_COUNT, PC_ELAPSED, PC_INTERVAL }
enum Memory_Type { MEM_DMA_SAFE, MEM_FAST }
typedef void * perf_counter_t
Public Attributes inherited from AP_HAL::Util
struct PersistentData persistent_data
Protected Attributes inherited from AP_HAL::Util
bool soft_armed = false
uint32_t last_armed_change_ms
Detailed Description
Definition at line 7 of file Util_RPI.h.
Constructor & Destructor Documentation
UtilRPI()
UtilRPI::UtilRPI ()
Definition at line 26 of file Util_RPI.cpp.
Member Function Documentation
_check_rpi_version()
int UtilRPI::_check_rpi_version () protected
Definition at line 31 of file Util_RPI.cpp.
Referenced by UtilRPI().
from()
static UtilRPI* Linux::UtilRPI::from (AP_HAL::Util * util) inline static
Definition at line 11 of file Util_RPI.h.
Referenced by Linux::GPIO_RPI::init(), and Linux::RCInput_RPI::init().
get_rpi_version()
int UtilRPI::get_rpi_version () const
Definition at line 74 of file Util_RPI.cpp.
Referenced by Linux::GPIO_RPI::init(), and Linux::RCInput_RPI::init().
Member Data Documentation
_rpi_version
int Linux::UtilRPI::_rpi_version = 0 private
Definition at line 23 of file Util_RPI.h.
Referenced by _check_rpi_version(), and get_rpi_version().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Util_RPI.h
libraries/AP_HAL_Linux/Util_RPI.cpp