APM:Libraries: AP_AHRS_DCM Class Reference
AP_AHRS_DCM Class Reference
#include <AP_AHRS_DCM.h>
Public Member Functions
AP_AHRS_DCM ()
AP_AHRS_DCM (const AP_AHRS_DCM &other)=delete
AP_AHRS_DCM & operator= (const AP_AHRS_DCM &)=delete
const Vector3f & get_gyro () const override
const Matrix3f & get_rotation_body_to_ned () const override
const Matrix3f & get_DCM_rotation_body_to_ned (void) const override
const Vector3f & get_gyro_drift () const override
void reset_gyro_drift () override
void update (bool skip_ins_update=false) override
void reset (bool recover_eulers=false) override
void reset_attitude (const float &roll, const float &pitch, const float &yaw) override
virtual bool get_position (struct Location &loc) const override
float get_error_rp () const override
float get_error_yaw () const override
Vector3f wind_estimate () const override
void get_relative_position_D_home (float &posD) const override
bool airspeed_estimate (float *airspeed_ret) const override
bool use_compass () override
bool set_home (const Location &loc) override WARN_IF_UNUSED
void estimate_wind (void)
bool healthy () const override
bool get_velocity_NED (Vector3f &vec) const override
Public Member Functions inherited from AP_AHRS
AP_AHRS ()
virtual ~AP_AHRS ()
virtual void init ()
void set_fly_forward (bool b)
bool get_fly_forward (void) const
void set_likely_flying (bool b)
bool get_likely_flying (void) const
uint32_t get_time_flying_ms (void) const
AHRS_VehicleClass get_vehicle_class (void) const
void set_vehicle_class (AHRS_VehicleClass vclass)
void set_wind_estimation (bool b)
void set_compass (Compass *compass)
const Compass * get_compass () const
void set_optflow (const OpticalFlow *optflow)
const OpticalFlow * get_optflow () const
void update_orientation ()
void set_airspeed (AP_Airspeed *airspeed)
const AP_Airspeed * get_airspeed (void) const
virtual uint8_t get_primary_accel_index (void) const
virtual uint8_t get_primary_gyro_index (void) const
virtual const Vector3f & get_accel_ef (uint8_t i) const
virtual const Vector3f & get_accel_ef (void) const
virtual const Vector3f & get_accel_ef_blended (void) const
float get_yaw_rate_earth (void) const
virtual const char * prearm_failure_reason (void) const
virtual bool attitudes_consistent (char *failure_msg, const uint8_t failure_msg_len) const
virtual bool have_ekf_logging (void) const
virtual void check_lane_switch (void)
Vector3f get_gyro_latest (void) const
void get_quat_body_to_ned (Quaternion &quat) const
const Matrix3f & get_rotation_autopilot_body_to_vehicle_body (void) const
const Matrix3f & get_rotation_vehicle_body_to_autopilot_body (void) const
virtual bool get_hagl (float &height) const
bool airspeed_estimate_true (float *airspeed_ret) const WARN_IF_UNUSED
float get_EAS2TAS (void) const
bool airspeed_sensor_enabled (void) const
uint8_t get_max_wind () const
virtual Vector2f groundspeed_vector (void)
virtual bool get_expected_mag_field_NED (Vector3f &ret) const WARN_IF_UNUSED
virtual bool get_mag_field_correction (Vector3f &ret) const WARN_IF_UNUSED
virtual bool get_relative_position_NED_home (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_relative_position_NED_origin (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_relative_position_NE_home (Vector2f &vecNE) const WARN_IF_UNUSED
virtual bool get_relative_position_NE_origin (Vector2f &vecNE) const WARN_IF_UNUSED
virtual bool get_relative_position_D_origin (float &posD) const WARN_IF_UNUSED
float groundspeed (void)
bool yaw_initialised (void) const
void set_correct_centrifugal (bool setting)
bool get_correct_centrifugal (void) const
const Vector3f & get_trim () const
void set_trim (const Vector3f &new_trim)
void add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom=true)
float cos_roll () const
float cos_pitch () const
float cos_yaw () const
float sin_roll () const
float sin_pitch () const
float sin_yaw () const
virtual bool get_secondary_attitude (Vector3f &eulers) const WARN_IF_UNUSED
virtual bool get_secondary_quaternion (Quaternion &quat) const WARN_IF_UNUSED
virtual bool get_secondary_position (struct Location &loc) const WARN_IF_UNUSED
const struct Location & get_home (void) const
void lock_home ()
bool home_is_locked () const
bool home_is_set (void) const
virtual bool set_origin (const Location &loc) WARN_IF_UNUSED
virtual bool get_origin (Location &ret) const WARN_IF_UNUSED
void Log_Write_Home_And_Origin ()
virtual bool have_inertial_nav (void) const
uint8_t get_active_accel_instance (void) const
virtual bool prearm_healthy (void) const
virtual bool initialised (void) const
virtual uint32_t getLastYawResetAngle (float &yawAng) const
virtual uint32_t getLastPosNorthEastReset (Vector2f &pos) const WARN_IF_UNUSED
virtual uint32_t getLastVelNorthEastReset (Vector2f &vel) const WARN_IF_UNUSED
virtual uint32_t getLastPosDownReset (float &posDelta) const WARN_IF_UNUSED
virtual bool resetHeightDatum (void) WARN_IF_UNUSED
virtual bool get_variances (float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar, Vector2f &offset) const
int8_t get_ekf_type (void) const
virtual void getCorrectedDeltaVelocityNED (Vector3f &ret, float &dt) const
AP_AHRS_View * create_view (enum Rotation rotation, float pitch_trim_deg=0)
float getAOA (void)
float getSSA (void)
Vector2f rotate_earth_to_body2D (const Vector2f &ef_vector) const
Vector2f rotate_body_to_earth2D (const Vector2f &bf) const
virtual void update_AOA_SSA (void)
virtual bool get_hgt_ctrl_limit (float &limit) const WARN_IF_UNUSED
virtual void writeExtNavData (const Vector3f &sensOffset, const Vector3f &pos, const Quaternion &quat, float posErr, float angErr, uint32_t timeStamp_ms, uint32_t resetTime_ms)
HAL_Semaphore & get_semaphore (void)
Private Member Functions
void matrix_update (float _G_Dt)
void normalize (void)
void check_matrix (void)
bool renorm (Vector3f const &a, Vector3f &result)
void drift_correction (float deltat)
void drift_correction_yaw (void)
float yaw_error_compass ()
void euler_angles (void)
bool have_gps (void) const
bool use_fast_gains (void) const
void load_watchdog_home ()
void backup_attitude (void)
Vector3f ra_delayed (uint8_t instance, const Vector3f &ra)
float _P_gain (float spin_rate)
float _yaw_gain (void) const
Private Attributes
float _ki
float _ki_yaw
Matrix3f _dcm_matrix
Matrix3f _body_dcm_matrix
Vector3f _omega_P
Vector3f _omega_yaw_P
Vector3f _omega_I
Vector3f _omega_I_sum
float _omega_I_sum_time
Vector3f _omega
Vector3f _ra_delay_buffer [INS_MAX_INSTANCES]
float _renorm_val_sum
uint16_t _renorm_val_count
float _error_rp
float _error_yaw
uint32_t _gps_last_update
Vector3f _ra_sum [INS_MAX_INSTANCES]
Vector3f _last_velocity
float _ra_deltat
uint32_t _ra_sum_start
float _last_declination
Vector2f _mag_earth
bool _have_gps_lock
int32_t _last_lat
int32_t _last_lng
float _position_offset_north
float _position_offset_east
bool _have_position
Vector3f _last_fuse
Vector3f _last_vel
uint32_t _last_wind_time
float _last_airspeed
uint32_t _last_consistent_heading
Vector3f _wind
float _imu1_weight
uint32_t _last_failure_ms
uint32_t _last_startup_ms
Additional Inherited Members
Static Public Member Functions inherited from AP_AHRS
static AP_AHRS * get_singleton ()
Public Attributes inherited from AP_AHRS
float roll
float pitch
float yaw
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
Static Public Attributes inherited from AP_AHRS
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions inherited from AP_AHRS
void update_nmea_out ()
void calc_trig (const Matrix3f &rot, float &cr, float &cp, float &cy, float &sr, float &sp, float &sy) const
void update_trig (void)
void update_cd_values (void)
Protected Attributes inherited from AP_AHRS
HAL_Semaphore_Recursive _rsem
AHRS_VehicleClass _vehicle_class
AP_Float _kp_yaw
AP_Float _kp
AP_Float gps_gain
AP_Float beta
AP_Int8 _gps_use
AP_Int8 _wind_max
AP_Int8 _board_orientation
AP_Int8 _gps_minsats
AP_Int8 _gps_delay
AP_Int8 _ekf_type
AP_Float _custom_roll
AP_Float _custom_pitch
AP_Float _custom_yaw
Matrix3f _custom_rotation
struct AP_AHRS::ahrs_flags _flags
uint32_t _last_flying_ms
Compass * _compass
const OpticalFlow * _optflow
AP_Airspeed * _airspeed
uint32_t _compass_last_update
AP_Vector3f _trim
Vector3f _last_trim
Matrix3f _rotation_autopilot_body_to_vehicle_body
Matrix3f _rotation_vehicle_body_to_autopilot_body
float _gyro_drift_limit
Vector3f _accel_ef [INS_MAX_INSTANCES]
Vector3f _accel_ef_blended
Vector2f _lp
Vector2f _hp
Vector2f _lastGndVelADS
struct Location _home
bool _home_is_set:1
bool _home_locked:1
float _cos_roll
float _cos_pitch
float _cos_yaw
float _sin_roll
float _sin_pitch
float _sin_yaw
uint8_t _active_accel_instance
AP_AHRS_View * _view
float _AOA
float _SSA
uint32_t _last_AOA_update_ms
Detailed Description
Definition at line 24 of file AP_AHRS_DCM.h.
Constructor & Destructor Documentation
AP_AHRS_DCM() [1/2]
AP_AHRS_DCM::AP_AHRS_DCM () inline
Definition at line 26 of file AP_AHRS_DCM.h.
AP_AHRS_DCM() [2/2]
AP_AHRS_DCM::AP_AHRS_DCM (const AP_AHRS_DCM & other) delete
Member Function Documentation
_P_gain()
float AP_AHRS_DCM::_P_gain (float spin_rate) private
Definition at line 388 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), and drift_correction_yaw().
_yaw_gain()
float AP_AHRS_DCM::_yaw_gain (void) const private
Definition at line 407 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction_yaw().
airspeed_estimate()
bool AP_AHRS_DCM::airspeed_estimate (float * airspeed_ret) const override virtual
Reimplemented from AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1042 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::airspeed_estimate().
backup_attitude()
void AP_AHRS_DCM::backup_attitude (void) private
Definition at line 126 of file AP_AHRS_DCM.cpp.
Referenced by update().
check_matrix()
void AP_AHRS_DCM::check_matrix (void) private
Definition at line 250 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), and update().
drift_correction()
void AP_AHRS_DCM::drift_correction (float deltat) private
Definition at line 629 of file AP_AHRS_DCM.cpp.
Referenced by update().
drift_correction_yaw()
void AP_AHRS_DCM::drift_correction_yaw (void) private
Definition at line 480 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction().
estimate_wind()
void AP_AHRS_DCM::estimate_wind (void)
Definition at line 947 of file AP_AHRS_DCM.cpp.
euler_angles()
void AP_AHRS_DCM::euler_angles (void) private
Definition at line 1014 of file AP_AHRS_DCM.cpp.
Referenced by update().
get_DCM_rotation_body_to_ned()
const Matrix3f& AP_AHRS_DCM::get_DCM_rotation_body_to_ned (void) const inline override virtual
Implements AP_AHRS.
Definition at line 57 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::attitudes_consistent().
get_error_rp()
float AP_AHRS_DCM::get_error_rp (void) const inline override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 79 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_error_rp().
get_error_yaw()
float AP_AHRS_DCM::get_error_yaw (void) const inline override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 82 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_error_yaw().
get_gyro()
const Vector3f& AP_AHRS_DCM::get_gyro (void) const inline override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 47 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_gyro().
get_gyro_drift()
const Vector3f& AP_AHRS_DCM::get_gyro_drift (void) const inline override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 60 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::get_gyro_drift().
get_position()
bool AP_AHRS_DCM::get_position (struct Location & loc) const override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1024 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::get_position(), and AP_AHRS_NavEKF::get_secondary_position().
get_relative_position_D_home()
void AP_AHRS_DCM::get_relative_position_D_home (float & posD) const override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1113 of file AP_AHRS_DCM.cpp.
get_rotation_body_to_ned()
const Matrix3f& AP_AHRS_DCM::get_rotation_body_to_ned (void) const inline override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 52 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), AP_AHRS_NavEKF::get_rotation_body_to_ned(), and AP_AHRS_NavEKF::get_secondary_quaternion().
get_velocity_NED()
bool AP_AHRS_DCM::get_velocity_NED (Vector3f & vec) const override virtual
Reimplemented from AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1130 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::get_velocity_NED().
have_gps()
bool AP_AHRS_DCM::have_gps (void) const private
Definition at line 419 of file AP_AHRS_DCM.cpp.
Referenced by airspeed_estimate(), drift_correction(), drift_correction_yaw(), and use_compass().
healthy()
bool AP_AHRS_DCM::healthy (void) const override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 1121 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::healthy().
load_watchdog_home()
void AP_AHRS_DCM::load_watchdog_home () private
Definition at line 53 of file AP_AHRS_DCM.cpp.
Referenced by reset(), and update().
matrix_update()
void AP_AHRS_DCM::matrix_update (float _G_Dt) private
Definition at line 136 of file AP_AHRS_DCM.cpp.
Referenced by update().
normalize()
void AP_AHRS_DCM::normalize (void) private
Definition at line 334 of file AP_AHRS_DCM.cpp.
Referenced by check_matrix(), and update().
operator=()
AP_AHRS_DCM& AP_AHRS_DCM::operator= (const AP_AHRS_DCM &) delete
ra_delayed()
Vector3f AP_AHRS_DCM::ra_delayed (uint8_t instance, const Vector3f & ra) private
return an accel vector delayed by AHRS_ACCEL_DELAY samples for a specific accelerometer instance
Definition at line 606 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction().
renorm()
bool AP_AHRS_DCM::renorm (Vector3f const & a, Vector3f & result) private
Definition at line 280 of file AP_AHRS_DCM.cpp.
Referenced by normalize().
reset()
void AP_AHRS_DCM::reset (bool recover_eulers = false) override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 177 of file AP_AHRS_DCM.cpp.
Referenced by check_matrix(), normalize(), and AP_AHRS_NavEKF::reset().
reset_attitude()
void AP_AHRS_DCM::reset_attitude (const float & roll, const float & pitch, const float & yaw) override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 241 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::reset_attitude().
reset_gyro_drift()
void AP_AHRS_DCM::reset_gyro_drift (void) override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 44 of file AP_AHRS_DCM.cpp.
Referenced by AP_AHRS_NavEKF::reset_gyro_drift().
set_home()
bool AP_AHRS_DCM::set_home (const Location & loc) override virtual
Implements AP_AHRS.
Definition at line 1078 of file AP_AHRS_DCM.cpp.
update()
void AP_AHRS_DCM::update (bool skip_ins_update = false) override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 68 of file AP_AHRS_DCM.cpp.
Referenced by loop(), and AP_AHRS_NavEKF::update_DCM().
use_compass()
bool AP_AHRS_DCM::use_compass (void) override virtual
Reimplemented from AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 442 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), drift_correction_yaw(), and AP_AHRS_NavEKF::use_compass().
use_fast_gains()
bool AP_AHRS_DCM::use_fast_gains (void) const private
Definition at line 435 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction(), and drift_correction_yaw().
wind_estimate()
Vector3f AP_AHRS_DCM::wind_estimate (void) const inline override virtual
Implements AP_AHRS.
Reimplemented in AP_AHRS_NavEKF.
Definition at line 87 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_NavEKF::wind_estimate().
yaw_error_compass()
float AP_AHRS_DCM::yaw_error_compass (void) private
Definition at line 356 of file AP_AHRS_DCM.cpp.
Referenced by drift_correction_yaw().
Member Data Documentation
_body_dcm_matrix
Matrix3f AP_AHRS_DCM::_body_dcm_matrix private
Definition at line 129 of file AP_AHRS_DCM.h.
Referenced by euler_angles(), get_DCM_rotation_body_to_ned(), and get_rotation_body_to_ned().
_dcm_matrix
Matrix3f AP_AHRS_DCM::_dcm_matrix private
Definition at line 126 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_DCM(), check_matrix(), drift_correction(), drift_correction_yaw(), estimate_wind(), euler_angles(), matrix_update(), normalize(), reset(), reset_attitude(), and yaw_error_compass().
_error_rp
float AP_AHRS_DCM::_error_rp private
Definition at line 151 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_error_rp().
_error_yaw
float AP_AHRS_DCM::_error_yaw private
Definition at line 152 of file AP_AHRS_DCM.h.
Referenced by drift_correction_yaw(), and get_error_yaw().
_gps_last_update
uint32_t AP_AHRS_DCM::_gps_last_update private
Definition at line 155 of file AP_AHRS_DCM.h.
Referenced by drift_correction_yaw().
_have_gps_lock
bool AP_AHRS_DCM::_have_gps_lock private
Definition at line 168 of file AP_AHRS_DCM.h.
Referenced by drift_correction().
_have_position
bool AP_AHRS_DCM::_have_position private
Definition at line 179 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
_imu1_weight
float AP_AHRS_DCM::_imu1_weight private
Definition at line 191 of file AP_AHRS_DCM.h.
Referenced by drift_correction().
_ki
float AP_AHRS_DCM::_ki private
Definition at line 108 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_DCM(), and drift_correction().
_ki_yaw
float AP_AHRS_DCM::_ki_yaw private
Definition at line 109 of file AP_AHRS_DCM.h.
Referenced by AP_AHRS_DCM(), and drift_correction_yaw().
_last_airspeed
float AP_AHRS_DCM::_last_airspeed private
Definition at line 185 of file AP_AHRS_DCM.h.
Referenced by airspeed_estimate(), and drift_correction().
_last_consistent_heading
uint32_t AP_AHRS_DCM::_last_consistent_heading private
Definition at line 186 of file AP_AHRS_DCM.h.
Referenced by use_compass().
_last_declination
float AP_AHRS_DCM::_last_declination private
Definition at line 164 of file AP_AHRS_DCM.h.
Referenced by yaw_error_compass().
_last_failure_ms
uint32_t AP_AHRS_DCM::_last_failure_ms private
Definition at line 194 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), healthy(), and normalize().
_last_fuse
Vector3f AP_AHRS_DCM::_last_fuse private
Definition at line 182 of file AP_AHRS_DCM.h.
Referenced by estimate_wind().
_last_lat
int32_t AP_AHRS_DCM::_last_lat private
Definition at line 171 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
_last_lng
int32_t AP_AHRS_DCM::_last_lng private
Definition at line 172 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
_last_startup_ms
uint32_t AP_AHRS_DCM::_last_startup_ms private
Definition at line 197 of file AP_AHRS_DCM.h.
Referenced by reset(), update(), and use_fast_gains().
_last_vel
Vector3f AP_AHRS_DCM::_last_vel private
Definition at line 183 of file AP_AHRS_DCM.h.
Referenced by estimate_wind().
_last_velocity
Vector3f AP_AHRS_DCM::_last_velocity private
Definition at line 159 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and estimate_wind().
_last_wind_time
uint32_t AP_AHRS_DCM::_last_wind_time private
Definition at line 184 of file AP_AHRS_DCM.h.
Referenced by estimate_wind().
_mag_earth
Vector2f AP_AHRS_DCM::_mag_earth private
Definition at line 165 of file AP_AHRS_DCM.h.
Referenced by yaw_error_compass().
_omega
Vector3f AP_AHRS_DCM::_omega private
Definition at line 136 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), drift_correction_yaw(), get_gyro(), matrix_update(), and reset().
_omega_I
Vector3f AP_AHRS_DCM::_omega_I private
Definition at line 133 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), get_gyro_drift(), matrix_update(), reset(), and reset_gyro_drift().
_omega_I_sum
Vector3f AP_AHRS_DCM::_omega_I_sum private
Definition at line 134 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), drift_correction_yaw(), and reset_gyro_drift().
_omega_I_sum_time
float AP_AHRS_DCM::_omega_I_sum_time private
Definition at line 135 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and reset_gyro_drift().
_omega_P
Vector3f AP_AHRS_DCM::_omega_P private
Definition at line 131 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), matrix_update(), and reset().
_omega_yaw_P
Vector3f AP_AHRS_DCM::_omega_yaw_P private
Definition at line 132 of file AP_AHRS_DCM.h.
Referenced by drift_correction_yaw(), matrix_update(), and reset().
_position_offset_east
float AP_AHRS_DCM::_position_offset_east private
Definition at line 176 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
_position_offset_north
float AP_AHRS_DCM::_position_offset_north private
Definition at line 175 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and get_position().
_ra_delay_buffer
Vector3f AP_AHRS_DCM::_ra_delay_buffer[INS_MAX_INSTANCES] private
Definition at line 140 of file AP_AHRS_DCM.h.
Referenced by ra_delayed().
_ra_deltat
float AP_AHRS_DCM::_ra_deltat private
Definition at line 160 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and update().
_ra_sum
Vector3f AP_AHRS_DCM::_ra_sum[INS_MAX_INSTANCES] private
Definition at line 158 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), and update().
_ra_sum_start
uint32_t AP_AHRS_DCM::_ra_sum_start private
Definition at line 161 of file AP_AHRS_DCM.h.
Referenced by drift_correction().
_renorm_val_count
uint16_t AP_AHRS_DCM::_renorm_val_count private
Definition at line 150 of file AP_AHRS_DCM.h.
Referenced by renorm().
_renorm_val_sum
float AP_AHRS_DCM::_renorm_val_sum private
Definition at line 149 of file AP_AHRS_DCM.h.
Referenced by renorm().
_wind
Vector3f AP_AHRS_DCM::_wind private
Definition at line 189 of file AP_AHRS_DCM.h.
Referenced by drift_correction(), estimate_wind(), use_compass(), and wind_estimate().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS_DCM.h
libraries/AP_AHRS/AP_AHRS_DCM.cpp