APM:Libraries: Linux::CameraSensor_Mt9v117 Class Reference
Linux::CameraSensor_Mt9v117 Class Reference
#include <CameraSensor_Mt9v117.h>
Public Member Functions
CameraSensor_Mt9v117 (const char *device_path, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum mt9v117_res res, uint16_t nrst_gpio, uint32_t clock_freq)
Public Member Functions inherited from Linux::CameraSensor
CameraSensor (const char *device_path)
bool set_format (uint32_t width, uint32_t height, uint32_t format)
bool set_crop (uint32_t left, uint32_t top)
Private Member Functions
uint8_t _read_reg8 (uint16_t reg)
void _write_reg8 (uint16_t reg, uint8_t val)
uint16_t _read_reg16 (uint16_t reg)
void _write_reg16 (uint16_t reg, uint16_t val)
void _write_reg32 (uint16_t reg, uint32_t val)
uint16_t _var2reg (uint16_t var, uint16_t offset)
uint16_t _read_var16 (uint16_t var, uint16_t offset)
void _write_var16 (uint16_t var, uint16_t offset, uint16_t value)
uint8_t _read_var8 (uint16_t var, uint16_t offset)
void _write_var8 (uint16_t var, uint16_t offset, uint8_t value)
void _write_var32 (uint16_t var, uint16_t offset, uint32_t value)
void _config_change ()
void _itu656_enable ()
void _soft_reset ()
void _apply_patch ()
void _set_basic_settings ()
void _configure_sensor_qvga ()
void _init_sensor ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
uint32_t _clock_freq
uint16_t _nrst_gpio = 0xFFFF
uint8_t _addr
Static Private Attributes
static const struct mt9v117_patch _patch_lines [MT9V117_PATCH_LINE_NUM]
Detailed Description
Definition at line 35 of file CameraSensor_Mt9v117.h.
Constructor & Destructor Documentation
CameraSensor_Mt9v117()
CameraSensor_Mt9v117::CameraSensor_Mt9v117 (const char * device_path, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum mt9v117_res res, uint16_t nrst_gpio, uint32_t clock_freq)
Definition at line 110 of file CameraSensor_Mt9v117.cpp.
Member Function Documentation
_apply_patch()
void CameraSensor_Mt9v117::_apply_patch () private
Definition at line 289 of file CameraSensor_Mt9v117.cpp.
Referenced by _init_sensor().
_config_change()
void CameraSensor_Mt9v117::_config_change () private
Definition at line 247 of file CameraSensor_Mt9v117.cpp.
Referenced by CameraSensor_Mt9v117().
_configure_sensor_qvga()
void CameraSensor_Mt9v117::_configure_sensor_qvga () private
Definition at line 354 of file CameraSensor_Mt9v117.cpp.
Referenced by CameraSensor_Mt9v117().
_init_sensor()
void CameraSensor_Mt9v117::_init_sensor () private
Definition at line 395 of file CameraSensor_Mt9v117.cpp.
Referenced by CameraSensor_Mt9v117().
_itu656_enable()
void CameraSensor_Mt9v117::_itu656_enable () private
Definition at line 274 of file CameraSensor_Mt9v117.cpp.
Referenced by CameraSensor_Mt9v117().
_read_reg16()
uint16_t CameraSensor_Mt9v117::_read_reg16 (uint16_t reg) private
Definition at line 163 of file CameraSensor_Mt9v117.cpp.
Referenced by _apply_patch(), _config_change(), _init_sensor(), _read_var16(), and _set_basic_settings().
_read_reg8()
uint8_t CameraSensor_Mt9v117::_read_reg8 (uint16_t reg) private
Definition at line 137 of file CameraSensor_Mt9v117.cpp.
Referenced by _read_var8().
_read_var16()
uint16_t CameraSensor_Mt9v117::_read_var16 (uint16_t var, uint16_t offset) private
Definition at line 211 of file CameraSensor_Mt9v117.cpp.
Referenced by _itu656_enable().
_read_var8()
uint8_t CameraSensor_Mt9v117::_read_var8 (uint16_t var, uint16_t offset) private
Definition at line 225 of file CameraSensor_Mt9v117.cpp.
_set_basic_settings()
void CameraSensor_Mt9v117::_set_basic_settings () private
Definition at line 345 of file CameraSensor_Mt9v117.cpp.
Referenced by _init_sensor().
_soft_reset()
void CameraSensor_Mt9v117::_soft_reset () private
Definition at line 281 of file CameraSensor_Mt9v117.cpp.
Referenced by _init_sensor().
_var2reg()
uint16_t CameraSensor_Mt9v117::_var2reg (uint16_t var, uint16_t offset) inline private
Definition at line 205 of file CameraSensor_Mt9v117.cpp.
Referenced by _read_var16(), _read_var8(), _write_var16(), _write_var32(), and _write_var8().
_write_reg16()
void CameraSensor_Mt9v117::_write_reg16 (uint16_t reg, uint16_t val) private
Definition at line 177 of file CameraSensor_Mt9v117.cpp.
Referenced by _apply_patch(), _config_change(), _set_basic_settings(), _soft_reset(), and _write_var16().
_write_reg32()
void CameraSensor_Mt9v117::_write_reg32 (uint16_t reg, uint32_t val) private
Definition at line 190 of file CameraSensor_Mt9v117.cpp.
Referenced by _write_var32().
_write_reg8()
void CameraSensor_Mt9v117::_write_reg8 (uint16_t reg, uint8_t val) private
Definition at line 151 of file CameraSensor_Mt9v117.cpp.
Referenced by _configure_sensor_qvga(), and _write_var8().
_write_var16()
void CameraSensor_Mt9v117::_write_var16 (uint16_t var, uint16_t offset, uint16_t value) private
Definition at line 217 of file CameraSensor_Mt9v117.cpp.
Referenced by _apply_patch(), _configure_sensor_qvga(), _itu656_enable(), and _set_basic_settings().
_write_var32()
void CameraSensor_Mt9v117::_write_var32 (uint16_t var, uint16_t offset, uint32_t value) private
Definition at line 239 of file CameraSensor_Mt9v117.cpp.
Referenced by _apply_patch(), and _set_basic_settings().
_write_var8()
void CameraSensor_Mt9v117::_write_var8 (uint16_t var, uint16_t offset, uint8_t value) private
Definition at line 231 of file CameraSensor_Mt9v117.cpp.
Referenced by _config_change(), and _configure_sensor_qvga().
Member Data Documentation
_addr
uint8_t Linux::CameraSensor_Mt9v117::_addr private
Definition at line 67 of file CameraSensor_Mt9v117.h.
_clock_freq
uint32_t Linux::CameraSensor_Mt9v117::_clock_freq private
Definition at line 65 of file CameraSensor_Mt9v117.h.
Referenced by _init_sensor().
_dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> Linux::CameraSensor_Mt9v117::_dev private
Definition at line 64 of file CameraSensor_Mt9v117.h.
Referenced by _apply_patch(), _read_reg16(), _read_reg8(), _write_reg16(), _write_reg32(), _write_reg8(), and CameraSensor_Mt9v117().
_nrst_gpio
uint16_t Linux::CameraSensor_Mt9v117::_nrst_gpio = 0xFFFF private
Definition at line 66 of file CameraSensor_Mt9v117.h.
Referenced by _init_sensor().
_patch_lines
const struct mt9v117_patch Linux::CameraSensor_Mt9v117::_patch_lines[MT9V117_PATCH_LINE_NUM] static private
Definition at line 43 of file CameraSensor_Mt9v117.h.
Referenced by _apply_patch().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/CameraSensor_Mt9v117.h
libraries/AP_HAL_Linux/CameraSensor_Mt9v117.cpp