APM:Libraries: AP_Gripper Class Reference
AP_Gripper Class Reference
#include <AP_Gripper.h>
Classes
struct Backend_Config
Public Types
enum gripper_state { STATE_GRABBING, STATE_RELEASING, STATE_GRABBED, STATE_RELEASED }
Public Member Functions
AP_Gripper ()
AP_Gripper (const AP_Gripper &other)=delete
AP_Gripper & operator= (const AP_Gripper &)=delete
bool enabled () const
void init ()
void grab ()
void release ()
bool released () const
bool grabbed () const
void update ()
bool valid () const
Static Public Member Functions
static AP_Gripper * get_singleton ()
Public Attributes
AP_Int8 _enabled
struct AP_Gripper::Backend_Config config
Static Public Attributes
static AP_Gripper * _singleton = nullptr
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Gripper_Backend * backend
Detailed Description
Definition at line 22 of file AP_Gripper.h.
Member Enumeration Documentation
gripper_state
enum AP_Gripper::gripper_state
Enumerator
STATE_GRABBING
STATE_RELEASING
STATE_GRABBED
STATE_RELEASED
Definition at line 61 of file AP_Gripper.h.
Constructor & Destructor Documentation
AP_Gripper() [1/2]
AP_Gripper::AP_Gripper ()
Definition at line 71 of file AP_Gripper.cpp.
AP_Gripper() [2/2]
AP_Gripper::AP_Gripper (const AP_Gripper & other) delete
Member Function Documentation
enabled()
bool AP_Gripper::enabled (void) const inline
Definition at line 33 of file AP_Gripper.h.
Referenced by GCS_MAVLINK::handle_command_do_gripper().
get_singleton()
AP_Gripper * AP_Gripper::get_singleton (void) static
Definition at line 88 of file AP_Gripper.cpp.
Referenced by AP::gripper().
grab()
void AP_Gripper::grab ()
Referenced by RC_Channel::do_aux_function_gripper(), GCS_MAVLINK::handle_command_do_gripper(), and AP_Mission::start_command_do_gripper().
grabbed()
bool AP_Gripper::grabbed () const
init()
void AP_Gripper::init (void)
Definition at line 93 of file AP_Gripper.cpp.
operator=()
AP_Gripper& AP_Gripper::operator= (const AP_Gripper &) delete
release()
void AP_Gripper::release ()
Referenced by RC_Channel::do_aux_function_gripper(), GCS_MAVLINK::handle_command_do_gripper(), and AP_Mission::start_command_do_gripper().
released()
bool AP_Gripper::released () const
update()
void AP_Gripper::update ()
valid()
bool AP_Gripper::valid () const
Member Data Documentation
_enabled
AP_Int8 AP_Gripper::_enabled
Definition at line 59 of file AP_Gripper.h.
Referenced by enabled(), and init().
_singleton
AP_Gripper * AP_Gripper::_singleton = nullptr static
Definition at line 30 of file AP_Gripper.h.
Referenced by AP_Gripper(), and get_singleton().
backend
AP_Gripper_Backend* AP_Gripper::backend private
Definition at line 81 of file AP_Gripper.h.
Referenced by init().
config
struct AP_Gripper::Backend_Config AP_Gripper::config
Referenced by init().
var_info
const AP_Param::GroupInfo AP_Gripper::var_info static
Definition at line 56 of file AP_Gripper.h.
Referenced by AP_Gripper().
The documentation for this class was generated from the following files:
libraries/AP_Gripper/AP_Gripper.h
libraries/AP_Gripper/AP_Gripper.cpp