APM:Libraries: AP_OAVisGraph Class Reference
AP_OAVisGraph Class Reference
#include <AP_OAVisGraph.h>
Classes
class OAItemID
struct VisGraphItem
Public Types
enum OAType : uint8_t { OATYPE_SOURCE = 0, OATYPE_DESTINATION, OATYPE_FENCE_POINT }
typedef uint8_t oaid_num
Public Member Functions
AP_OAVisGraph ()
AP_OAVisGraph (const AP_OAVisGraph &other)=delete
AP_OAVisGraph & operator= (const AP_OAVisGraph &)=delete
void clear ()
uint8_t num_items () const
bool add_item (const OAItemID &id1, const OAItemID &id2, float distance_cm)
const VisGraphItem & operator[] (uint8_t i) const
Private Attributes
AP_ExpandingArray< VisGraphItem > _items
uint8_t _num_items
Detailed Description
Definition at line 10 of file AP_OAVisGraph.h.
Member Typedef Documentation
oaid_num
typedef uint8_t AP_OAVisGraph::oaid_num
Definition at line 26 of file AP_OAVisGraph.h.
Member Enumeration Documentation
OAType
enum AP_OAVisGraph::OAType : uint8_t
Enumerator
OATYPE_SOURCE
OATYPE_DESTINATION
OATYPE_FENCE_POINT
Definition at line 19 of file AP_OAVisGraph.h.
Constructor & Destructor Documentation
AP_OAVisGraph() [1/2]
AP_OAVisGraph::AP_OAVisGraph ()
Definition at line 19 of file AP_OAVisGraph.cpp.
AP_OAVisGraph() [2/2]
AP_OAVisGraph::AP_OAVisGraph (const AP_OAVisGraph & other) delete
Member Function Documentation
add_item()
bool AP_OAVisGraph::add_item (const OAItemID & id1, const OAItemID & id2, float distance_cm)
Definition at line 25 of file AP_OAVisGraph.cpp.
Referenced by AP_OADijkstra::create_polygon_fence_visgraph(), and AP_OADijkstra::update_visgraph().
clear()
void AP_OAVisGraph::clear () inline
Definition at line 43 of file AP_OAVisGraph.h.
Referenced by AP_OADijkstra::create_polygon_fence_visgraph(), and AP_OADijkstra::update_visgraph().
num_items()
uint8_t AP_OAVisGraph::num_items () const inline
Definition at line 46 of file AP_OAVisGraph.h.
Referenced by AP_OADijkstra::calc_shortest_path(), and AP_OADijkstra::update_visible_node_distances().
operator=()
AP_OAVisGraph& AP_OAVisGraph::operator= (const AP_OAVisGraph &) delete
operator[]()
const VisGraphItem& AP_OAVisGraph::operator[] (uint8_t i) const inline
Definition at line 53 of file AP_OAVisGraph.h.
Member Data Documentation
_items
AP_ExpandingArray<VisGraphItem> AP_OAVisGraph::_items private
Definition at line 57 of file AP_OAVisGraph.h.
Referenced by add_item(), and operator[]().
_num_items
uint8_t AP_OAVisGraph::_num_items private
Definition at line 58 of file AP_OAVisGraph.h.
Referenced by add_item(), clear(), and num_items().
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AP_OAVisGraph.h
libraries/AC_Avoidance/AP_OAVisGraph.cpp