APM:Libraries: AP_HAL::GPIO Class Reference
AP_HAL::GPIO Class Reference abstract
#include <GPIO.h>
Public Types
enum INTERRUPT_TRIGGER_TYPE { INTERRUPT_NONE, INTERRUPT_FALLING, INTERRUPT_RISING, INTERRUPT_BOTH }
Public Member Functions
GPIO ()
virtual void init ()=0
virtual void pinMode (uint8_t pin, uint8_t output)=0
virtual void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
virtual uint8_t read (uint8_t pin)=0
virtual void write (uint8_t pin, uint8_t value)=0
virtual void toggle (uint8_t pin)=0
virtual AP_HAL::DigitalSource * channel (uint16_t n)=0
FUNCTOR_TYPEDEF (irq_handler_fn_t, void, uint8_t, bool, uint32_t)
virtual bool attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode)
virtual bool attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode)
bool detach_interrupt (uint8_t pin)
virtual bool usb_connected (void)=0
Detailed Description
Definition at line 19 of file GPIO.h.
Member Enumeration Documentation
INTERRUPT_TRIGGER_TYPE
enum AP_HAL::GPIO::INTERRUPT_TRIGGER_TYPE
Enumerator
INTERRUPT_NONE
INTERRUPT_FALLING
INTERRUPT_RISING
INTERRUPT_BOTH
Definition at line 35 of file GPIO.h.
Constructor & Destructor Documentation
GPIO()
AP_HAL::GPIO::GPIO () inline
Definition at line 21 of file GPIO.h.
Member Function Documentation
attach_interrupt() [1/2]
virtual bool AP_HAL::GPIO::attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode) inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 50 of file GPIO.h.
Referenced by AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), detach_interrupt(), AP_BattMonitor_FuelFlow::read(), AP_Camera::setup_feedback_callback(), AP_RPM_Pin::update(), and AP_WheelEncoder_Quadrature::update_pin().
attach_interrupt() [2/2]
virtual bool AP_HAL::GPIO::attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode) inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 56 of file GPIO.h.
channel()
virtual AP_HAL::DigitalSource* AP_HAL::GPIO::channel (uint16_t n) pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
Referenced by AP_InertialSensor_BMI160::_configure_int1_pin(), AP_Baro_BMP085::_init(), AP_InertialSensor_Invensensev2::_init(), AP_InertialSensor_Invensense::_init(), AP_InertialSensor_LSM9DS1::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::CameraSensor_Mt9v117::_init_sensor(), DiscreteRGBLed::hw_init(), Linux::RCOutput_PCA9685::init(), AP_Compass_LSM303D::init(), Linux::RCInput_RPI::init(), Linux::SPIDevice::SPIDevice(), test_gpio_input(), and test_gpio_output().
detach_interrupt()
bool AP_HAL::GPIO::detach_interrupt (uint8_t pin) inline
Definition at line 61 of file GPIO.h.
Referenced by AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), AP_BattMonitor_FuelFlow::read(), AP_RPM_Pin::update(), and AP_WheelEncoder_Quadrature::update_pin().
FUNCTOR_TYPEDEF()
AP_HAL::GPIO::FUNCTOR_TYPEDEF (irq_handler_fn_t , void , uint8_t , bool , uint32_t)
init()
virtual void AP_HAL::GPIO::init () pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
Referenced by AP_BoardConfig::board_setup(), and HAL_Linux::run().
pinMode() [1/2]
virtual void AP_HAL::GPIO::pinMode (uint8_t pin, uint8_t output) pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
Referenced by AP_AdvancedFailsafe::check(), AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), AP_RangeFinder_PWM::check_stop_pin(), AP_AdvancedFailsafe::heartbeat(), Linux::HeatPwm::HeatPwm(), PixRacerLED::hw_init(), Linux::RCInput_PRU::init(), Buzzer::init(), AP_LandingGear::init(), Linux::DigitalSource::mode(), AP_Relay::off(), AP_Relay::on(), AP_LeakDetector_Digital::read(), AP_BattMonitor_FuelFlow::read(), ChibiOS::RCOutput::serial_read_bytes(), AP_Camera::setup_feedback_callback(), AP_Button::setup_pins(), test_gpio_input(), test_gpio_output(), AP_SBusOut::update(), AP_RPM_Pin::update(), AP_RCProtocol_DSM::update(), and AP_WheelEncoder_Quadrature::update_pin().
pinMode() [2/2]
virtual void AP_HAL::GPIO::pinMode (uint8_t pin, uint8_t output, uint8_t alt) inline virtual
Reimplemented in Linux::GPIO_RPI.
Definition at line 26 of file GPIO.h.
read()
virtual uint8_t AP_HAL::GPIO::read (uint8_t pin) pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
Referenced by AP_LandingGear::deployed(), AP_Camera::feedback_pin_timer(), AP_Button::get_mask(), AP_LeakDetector_Digital::read(), Linux::DigitalSource::read(), HALSITL::DigitalSource::read(), test_gpio_input(), HALSITL::DigitalSource::toggle(), AP_Relay::toggle(), AP_LandingGear::update(), and AP_WheelEncoder_Quadrature::update_pin().
toggle()
virtual void AP_HAL::GPIO::toggle (uint8_t pin) pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
usb_connected()
virtual bool AP_HAL::GPIO::usb_connected (void) pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
Referenced by RGBLed::get_brightness(), AP_Logger::handle_log_sending(), GCS_MAVLINK::have_flow_control(), and GCS_MAVLINK::telemetry_delayed().
write()
virtual void AP_HAL::GPIO::write (uint8_t pin, uint8_t value) pure virtual
Implemented in Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, and HALSITL::GPIO.
Referenced by AP_BoardConfig::board_setup(), AP_AdvancedFailsafe::check(), AP_AdvancedFailsafe::heartbeat(), Linux::HeatPwm::HeatPwm(), PixRacerLED::hw_init(), PixRacerLED::hw_set_rgb(), Linux::RCInput_PRU::init(), AP_LandingGear::init(), AP_Relay::off(), AP_Relay::on(), Buzzer::on(), ChibiOS::Util::set_imu_temp(), ChibiOS::UARTDriver::set_options(), AP_Camera::setup_feedback_callback(), AP_Button::setup_pins(), test_gpio_output(), HALSITL::DigitalSource::toggle(), AP_SBusOut::update(), AP_RCProtocol_DSM::update(), AP_RangeFinder_PWM::update(), Linux::DigitalSource::write(), and HALSITL::DigitalSource::write().
The documentation for this class was generated from the following file:
libraries/AP_HAL/GPIO.h