APM:Libraries: AP_Mount Class Reference
AP_Mount Class Reference
#include <AP_Mount.h>
Classes
struct mount_state
Public Types
enum MountType {
Mount_Type_None = 0, Mount_Type_Servo = 1, Mount_Type_SoloGimbal = 2, Mount_Type_Alexmos = 3,
Mount_Type_SToRM32 = 4, Mount_Type_SToRM32_serial = 5
}
Public Member Functions
AP_Mount (const struct Location &current_loc)
AP_Mount (const AP_Mount &other)=delete
AP_Mount & operator= (const AP_Mount &)=delete
void init (const AP_SerialManager &serial_manager)
void update ()
void update_fast ()
AP_Mount::MountType get_mount_type () const
AP_Mount::MountType get_mount_type (uint8_t instance) const
bool has_pan_control () const
bool has_pan_control (uint8_t instance) const
enum MAV_MOUNT_MODE get_mode () const
enum MAV_MOUNT_MODE get_mode (uint8_t instance) const
void set_mode (enum MAV_MOUNT_MODE mode)
void set_mode (uint8_t instance, enum MAV_MOUNT_MODE mode)
void set_mode_to_default ()
void set_mode_to_default (uint8_t instance)
void set_angle_targets (float roll, float tilt, float pan)
void set_angle_targets (uint8_t instance, float roll, float tilt, float pan)
void set_roi_target (const struct Location &target_loc)
void set_roi_target (uint8_t instance, const struct Location &target_loc)
MAV_RESULT handle_command_long (const mavlink_command_long_t &packet)
void handle_param_value (const mavlink_message_t *msg)
void handle_message (mavlink_channel_t chan, const mavlink_message_t *msg)
void send_gimbal_report (mavlink_channel_t chan)
void send_mount_status (mavlink_channel_t chan)
Return mount status information.
Static Public Member Functions
static AP_Mount * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
const struct Location & _current_loc
AP_Int8 _joystick_speed
uint8_t _num_instances
uint8_t _primary
AP_Mount_Backend * _backends [AP_MOUNT_MAX_INSTANCES]
struct AP_Mount::mount_state state [AP_MOUNT_MAX_INSTANCES]
Static Protected Attributes
static AP_Mount * _singleton
Private Member Functions
void handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t *msg)
void handle_mount_configure (const mavlink_message_t *msg)
Change the configuration of the mount.
void handle_mount_control (const mavlink_message_t *msg)
Control the mount (depends on the previously set mount configuration)
MAV_RESULT handle_command_do_mount_configure (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_do_mount_control (const mavlink_command_long_t &packet)
Friends
class AP_Mount_Backend
class AP_Mount_Servo
class AP_Mount_SoloGimbal
class AP_Mount_Alexmos
class AP_Mount_SToRM32
class AP_Mount_SToRM32_serial
Detailed Description
Definition at line 44 of file AP_Mount.h.
Member Enumeration Documentation
MountType
enum AP_Mount::MountType
Enumerator
Mount_Type_None
Mount_Type_Servo
no mount
Mount_Type_SoloGimbal
servo controlled mount
Mount_Type_Alexmos
Solo's gimbal.
Mount_Type_SToRM32
Alexmos mount.
Mount_Type_SToRM32_serial
SToRM32 mount using MAVLink protocol.
Definition at line 67 of file AP_Mount.h.
Constructor & Destructor Documentation
AP_Mount() [1/2]
AP_Mount::AP_Mount (const struct Location & current_loc)
Definition at line 396 of file AP_Mount.cpp.
AP_Mount() [2/2]
AP_Mount::AP_Mount (const AP_Mount & other) delete
Member Function Documentation
get_mode() [1/2]
enum MAV_MOUNT_MODE AP_Mount::get_mode () const inline
Definition at line 94 of file AP_Mount.h.
Referenced by AP_Mount_Backend::control(), AP_Mount_Backend::get_mode(), and GCS_MAVLINK::handle_command_do_set_roi().
get_mode() [2/2]
MAV_MOUNT_MODE AP_Mount::get_mode (uint8_t instance) const
Definition at line 522 of file AP_Mount.cpp.
get_mount_type() [1/2]
AP_Mount::MountType AP_Mount::get_mount_type () const inline
Definition at line 86 of file AP_Mount.h.
Referenced by get_mount_type(), and init().
get_mount_type() [2/2]
AP_Mount::MountType AP_Mount::get_mount_type (uint8_t instance) const
Definition at line 501 of file AP_Mount.cpp.
get_singleton()
static AP_Mount* AP_Mount::get_singleton (void) inline static
Definition at line 62 of file AP_Mount.h.
Referenced by AP::mount().
handle_command_do_mount_configure()
MAV_RESULT AP_Mount::handle_command_do_mount_configure (const mavlink_command_long_t & packet) private
Definition at line 562 of file AP_Mount.cpp.
Referenced by handle_command_long().
handle_command_do_mount_control()
MAV_RESULT AP_Mount::handle_command_do_mount_control (const mavlink_command_long_t & packet) private
Definition at line 576 of file AP_Mount.cpp.
Referenced by handle_command_long().
handle_command_long()
MAV_RESULT AP_Mount::handle_command_long (const mavlink_command_long_t & packet)
Definition at line 588 of file AP_Mount.cpp.
Referenced by GCS_MAVLINK::handle_command_mount().
handle_gimbal_report()
void AP_Mount::handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t * msg) private
Definition at line 649 of file AP_Mount.cpp.
Referenced by handle_message().
handle_message()
void AP_Mount::handle_message (mavlink_channel_t chan, const mavlink_message_t * msg)
Definition at line 658 of file AP_Mount.cpp.
Referenced by GCS_MAVLINK::handle_mount_message().
handle_mount_configure()
void AP_Mount::handle_mount_configure (const mavlink_message_t * msg) private
Change the configuration of the mount.
Definition at line 601 of file AP_Mount.cpp.
Referenced by handle_message().
handle_mount_control()
void AP_Mount::handle_mount_control (const mavlink_message_t * msg) private
Control the mount (depends on the previously set mount configuration)
Definition at line 615 of file AP_Mount.cpp.
Referenced by handle_message().
handle_param_value()
void AP_Mount::handle_param_value (const mavlink_message_t * msg)
Definition at line 679 of file AP_Mount.cpp.
Referenced by GCS_MAVLINK::handle_param_value().
has_pan_control() [1/2]
bool AP_Mount::has_pan_control () const inline
Definition at line 90 of file AP_Mount.h.
Referenced by has_pan_control().
has_pan_control() [2/2]
bool AP_Mount::has_pan_control (uint8_t instance) const
Definition at line 511 of file AP_Mount.cpp.
init()
void AP_Mount::init (const AP_SerialManager & serial_manager)
Definition at line 411 of file AP_Mount.cpp.
operator=()
AP_Mount& AP_Mount::operator= (const AP_Mount &) delete
send_gimbal_report()
void AP_Mount::send_gimbal_report (mavlink_channel_t chan)
Definition at line 689 of file AP_Mount.cpp.
Referenced by GCS_MAVLINK::send_gimbal_report().
send_mount_status()
void AP_Mount::send_mount_status (mavlink_channel_t chan)
Return mount status information.
Definition at line 629 of file AP_Mount.cpp.
Referenced by GCS_MAVLINK::send_mount_status().
set_angle_targets() [1/2]
void AP_Mount::set_angle_targets (float roll, float tilt, float pan) inline
Definition at line 108 of file AP_Mount.h.
Referenced by set_angle_targets().
set_angle_targets() [2/2]
void AP_Mount::set_angle_targets (uint8_t instance, float roll, float tilt, float pan)
Definition at line 552 of file AP_Mount.cpp.
set_mode() [1/2]
void AP_Mount::set_mode (enum MAV_MOUNT_MODE mode) inline
Definition at line 99 of file AP_Mount.h.
Referenced by AP_Mount_Backend::control(), AP_Mount_Backend::set_angle_targets(), set_mode(), set_mode_to_default(), and AP_Mount_Backend::set_roi_target().
set_mode() [2/2]
void AP_Mount::set_mode (uint8_t instance, enum MAV_MOUNT_MODE mode)
Definition at line 540 of file AP_Mount.cpp.
set_mode_to_default() [1/2]
void AP_Mount::set_mode_to_default () inline
Definition at line 104 of file AP_Mount.h.
Referenced by GCS_MAVLINK::handle_command_do_set_roi(), and set_mode_to_default().
set_mode_to_default() [2/2]
void AP_Mount::set_mode_to_default (uint8_t instance)
Definition at line 534 of file AP_Mount.cpp.
set_roi_target() [1/2]
void AP_Mount::set_roi_target (const struct Location & target_loc) inline
Definition at line 112 of file AP_Mount.h.
Referenced by GCS_MAVLINK::handle_command_do_set_roi(), and set_roi_target().
set_roi_target() [2/2]
void AP_Mount::set_roi_target (uint8_t instance, const struct Location & target_loc)
Definition at line 640 of file AP_Mount.cpp.
update()
void AP_Mount::update (void)
Definition at line 479 of file AP_Mount.cpp.
update_fast()
void AP_Mount::update_fast ()
Definition at line 490 of file AP_Mount.cpp.
Friends And Related Function Documentation
AP_Mount_Alexmos
friend class AP_Mount_Alexmos friend
Definition at line 50 of file AP_Mount.h.
Referenced by init().
AP_Mount_Backend
friend class AP_Mount_Backend friend
Definition at line 47 of file AP_Mount.h.
AP_Mount_Servo
friend class AP_Mount_Servo friend
Definition at line 48 of file AP_Mount.h.
Referenced by init().
AP_Mount_SoloGimbal
friend class AP_Mount_SoloGimbal friend
Definition at line 49 of file AP_Mount.h.
Referenced by init().
AP_Mount_SToRM32
friend class AP_Mount_SToRM32 friend
Definition at line 51 of file AP_Mount.h.
Referenced by init().
AP_Mount_SToRM32_serial
friend class AP_Mount_SToRM32_serial friend
Definition at line 52 of file AP_Mount.h.
Referenced by init().
Member Data Documentation
_backends
AP_Mount_Backend* AP_Mount::_backends[AP_MOUNT_MAX_INSTANCES] protected
Definition at line 142 of file AP_Mount.h.
Referenced by handle_command_do_mount_configure(), handle_command_do_mount_control(), handle_gimbal_report(), handle_mount_configure(), handle_mount_control(), handle_param_value(), has_pan_control(), init(), send_gimbal_report(), send_mount_status(), set_angle_targets(), set_mode(), set_roi_target(), update(), and update_fast().
_current_loc
const struct Location& AP_Mount::_current_loc protected
Definition at line 134 of file AP_Mount.h.
Referenced by AP_Mount_Backend::calc_angle_to_location().
_joystick_speed
AP_Int8 AP_Mount::_joystick_speed protected
Definition at line 137 of file AP_Mount.h.
Referenced by AP_Mount_Backend::rate_input_rad(), and AP_Mount_Backend::update_targets_from_rc().
_num_instances
uint8_t AP_Mount::_num_instances protected
Definition at line 140 of file AP_Mount.h.
Referenced by init().
_primary
uint8_t AP_Mount::_primary protected
Definition at line 141 of file AP_Mount.h.
Referenced by get_mode(), get_mount_type(), handle_command_do_mount_configure(), handle_command_do_mount_control(), handle_mount_configure(), handle_mount_control(), has_pan_control(), init(), set_angle_targets(), set_mode(), set_mode_to_default(), and set_roi_target().
_singleton
AP_Mount * AP_Mount::_singleton static protected
Definition at line 131 of file AP_Mount.h.
Referenced by AP_Mount(), and get_singleton().
state
struct AP_Mount::mount_state AP_Mount::state[AP_MOUNT_MAX_INSTANCES] protected
Referenced by get_mode(), get_mount_type(), handle_command_do_mount_configure(), init(), and set_mode_to_default().
var_info
const AP_Param::GroupInfo AP_Mount::var_info static
Definition at line 127 of file AP_Mount.h.
Referenced by AP_Mount().
The documentation for this class was generated from the following files:
libraries/AP_Mount/AP_Mount.h
libraries/AP_Mount/AP_Mount.cpp