APM:Libraries: AP_Navigation Class Reference
AP_Navigation Class Reference abstract
#include <AP_Navigation.h>
Public Types
enum ControllerType { CONTROLLER_DEFAULT = 0, CONTROLLER_L1 = 1 }
Public Member Functions
virtual int32_t nav_roll_cd (void) const =0
virtual float lateral_acceleration (void) const =0
virtual int32_t nav_bearing_cd (void) const =0
virtual int32_t bearing_error_cd (void) const =0
virtual int32_t target_bearing_cd (void) const =0
virtual float crosstrack_error (void) const =0
virtual float crosstrack_error_integrator (void) const
virtual float turn_distance (float wp_radius) const =0
virtual float turn_distance (float wp_radius, float turn_angle) const =0
virtual float loiter_radius (const float radius) const =0
virtual void update_waypoint (const struct Location &prev_WP, const struct Location &next_WP, float dist_min=0.0f)=0
virtual void update_loiter (const struct Location &center_WP, float radius, int8_t loiter_direction)=0
virtual void update_heading_hold (int32_t navigation_heading_cd)=0
virtual void update_level_flight (void)=0
virtual bool reached_loiter_target (void)=0
virtual void set_data_is_stale (void)=0
virtual bool data_is_stale (void) const =0
virtual void set_reverse (bool reverse)=0
Detailed Description
Definition at line 14 of file AP_Navigation.h.
Member Enumeration Documentation
ControllerType
enum AP_Navigation::ControllerType
Enumerator
CONTROLLER_DEFAULT
CONTROLLER_L1
Definition at line 122 of file AP_Navigation.h.
Member Function Documentation
bearing_error_cd()
virtual int32_t AP_Navigation::bearing_error_cd (void) const pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing::type_slope_verify_land().
crosstrack_error()
virtual float AP_Navigation::crosstrack_error (void) const pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing::type_slope_verify_land(), and AR_WPNav::update_steering().
crosstrack_error_integrator()
virtual float AP_Navigation::crosstrack_error_integrator (void) const inline virtual
Reimplemented in AP_L1_Control.
Definition at line 47 of file AP_Navigation.h.
data_is_stale()
virtual bool AP_Navigation::data_is_stale (void) const pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing::type_slope_verify_land().
lateral_acceleration()
virtual float AP_Navigation::lateral_acceleration (void) const pure virtual
Implemented in AP_L1_Control.
Referenced by AR_WPNav::update_steering().
loiter_radius()
virtual float AP_Navigation::loiter_radius (const float radius) const pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing_Deepstall::build_approach_path().
nav_bearing_cd()
virtual int32_t AP_Navigation::nav_bearing_cd (void) const pure virtual
Implemented in AP_L1_Control.
Referenced by AR_WPNav::update_steering().
nav_roll_cd()
virtual int32_t AP_Navigation::nav_roll_cd (void) const pure virtual
Implemented in AP_L1_Control.
reached_loiter_target()
virtual bool AP_Navigation::reached_loiter_target (void) pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing_Deepstall::verify_land().
set_data_is_stale()
virtual void AP_Navigation::set_data_is_stale (void) pure virtual
Implemented in AP_L1_Control.
set_reverse()
virtual void AP_Navigation::set_reverse (bool reverse) pure virtual
Implemented in AP_L1_Control.
Referenced by AR_WPNav::update_steering().
target_bearing_cd()
virtual int32_t AP_Navigation::target_bearing_cd (void) const pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing_Deepstall::verify_land().
turn_distance() [1/2]
virtual float AP_Navigation::turn_distance (float wp_radius) const pure virtual
Implemented in AP_L1_Control.
turn_distance() [2/2]
virtual float AP_Navigation::turn_distance (float wp_radius, float turn_angle) const pure virtual
Implemented in AP_L1_Control.
update_heading_hold()
virtual void AP_Navigation::update_heading_hold (int32_t navigation_heading_cd) pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing::type_slope_verify_abort_landing(), and AP_Landing_Deepstall::verify_abort_landing().
update_level_flight()
virtual void AP_Navigation::update_level_flight (void) pure virtual
Implemented in AP_L1_Control.
update_loiter()
virtual void AP_Navigation::update_loiter (const struct Location & center_WP, float radius, int8_t loiter_direction) pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing_Deepstall::verify_land().
update_waypoint()
virtual void AP_Navigation::update_waypoint (const struct Location & prev_WP, const struct Location & next_WP, float dist_min = 0.0f) pure virtual
Implemented in AP_L1_Control.
Referenced by AP_Landing::type_slope_verify_land(), AR_WPNav::update_steering(), and AP_Landing_Deepstall::verify_land().
The documentation for this class was generated from the following file:
libraries/AP_Navigation/AP_Navigation.h