APM:Libraries: OreoLED_I2C Class Reference
OreoLED_I2C Class Reference
#include <OreoLED_I2C.h>
Classes
struct oreo_state
struct oreoled_cmd_t
Public Member Functions
OreoLED_I2C (uint8_t bus, uint8_t theme)
bool init (void) override
void update () override
void handle_led_control (mavlink_message_t *msg) override
Public Member Functions inherited from NotifyDevice
virtual ~NotifyDevice ()
virtual void handle_play_tune (mavlink_message_t *msg)
virtual void play_tune (const char *tune)
Private Types
enum oreoled_pattern {
OREOLED_PATTERN_OFF = 0, OREOLED_PATTERN_SINE = 1, OREOLED_PATTERN_SOLID = 2, OREOLED_PATTERN_SIREN = 3,
OREOLED_PATTERN_STROBE = 4, OREOLED_PATTERN_FADEIN = 5, OREOLED_PATTERN_FADEOUT = 6, OREOLED_PATTERN_PARAMUPDATE = 7,
OREOLED_PATTERN_ENUM_COUNT
}
enum oreoled_macro {
OREOLED_PARAM_MACRO_RESET = 0, OREOLED_PARAM_MACRO_COLOUR_CYCLE = 1, OREOLED_PARAM_MACRO_BREATH = 2, OREOLED_PARAM_MACRO_STROBE = 3,
OREOLED_PARAM_MACRO_FADEIN = 4, OREOLED_PARAM_MACRO_FADEOUT = 5, OREOLED_PARAM_MACRO_RED = 6, OREOLED_PARAM_MACRO_GREEN = 7,
OREOLED_PARAM_MACRO_BLUE = 8, OREOLED_PARAM_MACRO_YELLOW = 9, OREOLED_PARAM_MACRO_WHITE = 10, OREOLED_PARAM_MACRO_AUTOMOBILE = 11,
OREOLED_PARAM_MACRO_AVIATION = 12, OREOLED_PARAM_MACRO_ENUM_COUNT
}
enum oreoled_param {
OREOLED_PARAM_BIAS_RED = 0, OREOLED_PARAM_BIAS_GREEN = 1, OREOLED_PARAM_BIAS_BLUE = 2, OREOLED_PARAM_AMPLITUDE_RED = 3,
OREOLED_PARAM_AMPLITUDE_GREEN = 4, OREOLED_PARAM_AMPLITUDE_BLUE = 5, OREOLED_PARAM_PERIOD = 6, OREOLED_PARAM_REPEAT = 7,
OREOLED_PARAM_PHASEOFFSET = 8, OREOLED_PARAM_MACRO = 9, OREOLED_PARAM_RESET = 10, OREOLED_PARAM_APP_CHECKSUM = 11,
OREOLED_PARAM_ENUM_COUNT
}
enum oreoled_mode { OREOLED_MODE_NONE =0, OREOLED_MODE_MACRO, OREOLED_MODE_RGB, OREOLED_MODE_RGB_EXTENDED }
enum Oreo_LED_Theme { OreoLED_Disabled = 0, OreoLED_Aircraft = 1, OreoLED_Automobile = 2 }
Private Member Functions
void update_timer (void)
void set_rgb (uint8_t instance, uint8_t red, uint8_t green, uint8_t blue)
void set_rgb (uint8_t instance, enum oreoled_pattern pattern, uint8_t red, uint8_t green, uint8_t blue)
void set_rgb (uint8_t instance, oreoled_pattern pattern, uint8_t red, uint8_t green, uint8_t blue, uint8_t amplitude_red, uint8_t amplitude_green, uint8_t amplitude_blue, uint16_t period, uint16_t phase_offset)
void set_macro (uint8_t instance, enum oreoled_macro macro)
void send_sync ()
bool slow_counter (void)
bool mode_firmware_update (void)
bool mode_init (void)
bool mode_failsafe_radio (void)
bool set_standard_colors (void)
bool mode_failsafe_batt (void)
bool mode_auto_flight (void)
bool mode_pilot_flight (void)
void clear_state (void)
bool command_send (oreoled_cmd_t &cmd)
void boot_leds (void)
Private Attributes
uint8_t _bus
HAL_Semaphore_Recursive _sem
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
bool _send_required
oreo_state _state_desired [OREOLED_NUM_LEDS]
oreo_state _state_sent [OREOLED_NUM_LEDS]
uint8_t _pattern_override
uint8_t _oreo_theme
uint8_t _rear_color_r = 255
uint8_t _rear_color_g = 255
uint8_t _rear_color_b = 255
uint8_t _slow_count
uint8_t _boot_count
uint32_t _last_boot_ms
uint32_t _last_sync_ms
Additional Inherited Members
Public Attributes inherited from NotifyDevice
const AP_Notify * pNotify
Detailed Description
Definition at line 28 of file OreoLED_I2C.h.
Member Enumeration Documentation
Oreo_LED_Theme
enum OreoLED_I2C::Oreo_LED_Theme private
Enumerator
OreoLED_Disabled
OreoLED_Aircraft
OreoLED_Automobile
Definition at line 133 of file OreoLED_I2C.h.
oreoled_macro
enum OreoLED_I2C::oreoled_macro private
Enumerator
OREOLED_PARAM_MACRO_RESET
OREOLED_PARAM_MACRO_COLOUR_CYCLE
OREOLED_PARAM_MACRO_BREATH
OREOLED_PARAM_MACRO_STROBE
OREOLED_PARAM_MACRO_FADEIN
OREOLED_PARAM_MACRO_FADEOUT
OREOLED_PARAM_MACRO_RED
OREOLED_PARAM_MACRO_GREEN
OREOLED_PARAM_MACRO_BLUE
OREOLED_PARAM_MACRO_YELLOW
OREOLED_PARAM_MACRO_WHITE
OREOLED_PARAM_MACRO_AUTOMOBILE
OREOLED_PARAM_MACRO_AVIATION
OREOLED_PARAM_MACRO_ENUM_COUNT
Definition at line 57 of file OreoLED_I2C.h.
oreoled_mode
enum OreoLED_I2C::oreoled_mode private
Enumerator
OREOLED_MODE_NONE
OREOLED_MODE_MACRO
OREOLED_MODE_RGB
OREOLED_MODE_RGB_EXTENDED
Definition at line 125 of file OreoLED_I2C.h.
oreoled_param
enum OreoLED_I2C::oreoled_param private
Enumerator
OREOLED_PARAM_BIAS_RED
OREOLED_PARAM_BIAS_GREEN
OREOLED_PARAM_BIAS_BLUE
OREOLED_PARAM_AMPLITUDE_RED
OREOLED_PARAM_AMPLITUDE_GREEN
OREOLED_PARAM_AMPLITUDE_BLUE
OREOLED_PARAM_PERIOD
OREOLED_PARAM_REPEAT
OREOLED_PARAM_PHASEOFFSET
OREOLED_PARAM_MACRO
OREOLED_PARAM_RESET
OREOLED_PARAM_APP_CHECKSUM
OREOLED_PARAM_ENUM_COUNT
Definition at line 75 of file OreoLED_I2C.h.
oreoled_pattern
enum OreoLED_I2C::oreoled_pattern private
Enumerator
OREOLED_PATTERN_OFF
OREOLED_PATTERN_SINE
OREOLED_PATTERN_SOLID
OREOLED_PATTERN_SIREN
OREOLED_PATTERN_STROBE
OREOLED_PATTERN_FADEIN
OREOLED_PATTERN_FADEOUT
OREOLED_PATTERN_PARAMUPDATE
OREOLED_PATTERN_ENUM_COUNT
Definition at line 44 of file OreoLED_I2C.h.
Constructor & Destructor Documentation
OreoLED_I2C()
OreoLED_I2C::OreoLED_I2C (uint8_t bus, uint8_t theme)
Definition at line 46 of file OreoLED_I2C.cpp.
Member Function Documentation
boot_leds()
void OreoLED_I2C::boot_leds (void) private
Definition at line 414 of file OreoLED_I2C.cpp.
Referenced by update_timer().
clear_state()
void OreoLED_I2C::clear_state (void) private
Definition at line 378 of file OreoLED_I2C.cpp.
Referenced by handle_led_control(), OreoLED_I2C::oreo_state::set_macro(), and OreoLED_I2C::oreo_state::set_rgb().
command_send()
bool OreoLED_I2C::command_send (oreoled_cmd_t & cmd) private
Definition at line 392 of file OreoLED_I2C.cpp.
Referenced by boot_leds(), and update_timer().
handle_led_control()
void OreoLED_I2C::handle_led_control (mavlink_message_t * msg) override virtual
Reimplemented from NotifyDevice.
Definition at line 547 of file OreoLED_I2C.cpp.
init()
bool OreoLED_I2C::init (void) override virtual
Implements NotifyDevice.
Definition at line 56 of file OreoLED_I2C.cpp.
mode_auto_flight()
bool OreoLED_I2C::mode_auto_flight (void) private
Definition at line 224 of file OreoLED_I2C.cpp.
Referenced by update().
mode_failsafe_batt()
bool OreoLED_I2C::mode_failsafe_batt (void) private
Definition at line 191 of file OreoLED_I2C.cpp.
Referenced by update().
mode_failsafe_radio()
bool OreoLED_I2C::mode_failsafe_radio (void) private
Definition at line 150 of file OreoLED_I2C.cpp.
Referenced by update().
mode_firmware_update()
bool OreoLED_I2C::mode_firmware_update (void) private
Definition at line 125 of file OreoLED_I2C.cpp.
Referenced by update().
mode_init()
bool OreoLED_I2C::mode_init (void) private
Definition at line 137 of file OreoLED_I2C.cpp.
Referenced by update().
mode_pilot_flight()
bool OreoLED_I2C::mode_pilot_flight (void) private
Definition at line 261 of file OreoLED_I2C.cpp.
Referenced by update().
send_sync()
void OreoLED_I2C::send_sync (void) private
Definition at line 530 of file OreoLED_I2C.cpp.
Referenced by update_timer().
set_macro()
void OreoLED_I2C::set_macro (uint8_t instance, enum oreoled_macro macro) private
Definition at line 355 of file OreoLED_I2C.cpp.
Referenced by handle_led_control(), and mode_firmware_update().
set_rgb() [1/3]
void OreoLED_I2C::set_rgb (uint8_t instance, uint8_t red, uint8_t green, uint8_t blue) private
Definition at line 297 of file OreoLED_I2C.cpp.
Referenced by handle_led_control(), mode_auto_flight(), mode_failsafe_batt(), mode_failsafe_radio(), mode_init(), and mode_pilot_flight().
set_rgb() [2/3]
void OreoLED_I2C::set_rgb (uint8_t instance, enum oreoled_pattern pattern, uint8_t red, uint8_t green, uint8_t blue) private
Definition at line 304 of file OreoLED_I2C.cpp.
set_rgb() [3/3]
void OreoLED_I2C::set_rgb (uint8_t instance, oreoled_pattern pattern, uint8_t red, uint8_t green, uint8_t blue, uint8_t amplitude_red, uint8_t amplitude_green, uint8_t amplitude_blue, uint16_t period, uint16_t phase_offset) private
Definition at line 329 of file OreoLED_I2C.cpp.
set_standard_colors()
bool OreoLED_I2C::set_standard_colors (void) private
Definition at line 165 of file OreoLED_I2C.cpp.
Referenced by update().
slow_counter()
bool OreoLED_I2C::slow_counter (void) private
Definition at line 110 of file OreoLED_I2C.cpp.
Referenced by update().
update()
void OreoLED_I2C::update (void) override virtual
Implements NotifyDevice.
Definition at line 72 of file OreoLED_I2C.cpp.
update_timer()
void OreoLED_I2C::update_timer (void) private
Definition at line 428 of file OreoLED_I2C.cpp.
Referenced by init().
Member Data Documentation
_boot_count
uint8_t OreoLED_I2C::_boot_count private
Definition at line 194 of file OreoLED_I2C.h.
Referenced by update_timer().
_bus
uint8_t OreoLED_I2C::_bus private
Definition at line 181 of file OreoLED_I2C.h.
Referenced by init().
_dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> OreoLED_I2C::_dev private
Definition at line 183 of file OreoLED_I2C.h.
Referenced by command_send(), init(), and send_sync().
_last_boot_ms
uint32_t OreoLED_I2C::_last_boot_ms private
Definition at line 195 of file OreoLED_I2C.h.
Referenced by update_timer().
_last_sync_ms
uint32_t OreoLED_I2C::_last_sync_ms private
Definition at line 196 of file OreoLED_I2C.h.
Referenced by update_timer().
_oreo_theme
uint8_t OreoLED_I2C::_oreo_theme private
Definition at line 188 of file OreoLED_I2C.h.
Referenced by mode_auto_flight(), mode_failsafe_batt(), and mode_pilot_flight().
_pattern_override
uint8_t OreoLED_I2C::_pattern_override private
Definition at line 187 of file OreoLED_I2C.h.
Referenced by handle_led_control(), and update().
_rear_color_b
uint8_t OreoLED_I2C::_rear_color_b = 255 private
Definition at line 191 of file OreoLED_I2C.h.
Referenced by mode_auto_flight(), mode_failsafe_batt(), mode_pilot_flight(), and set_standard_colors().
_rear_color_g
uint8_t OreoLED_I2C::_rear_color_g = 255 private
Definition at line 190 of file OreoLED_I2C.h.
Referenced by mode_auto_flight(), mode_failsafe_batt(), mode_pilot_flight(), and set_standard_colors().
_rear_color_r
uint8_t OreoLED_I2C::_rear_color_r = 255 private
Definition at line 189 of file OreoLED_I2C.h.
Referenced by mode_auto_flight(), mode_failsafe_batt(), mode_pilot_flight(), and set_standard_colors().
_sem
HAL_Semaphore_Recursive OreoLED_I2C::_sem private
Definition at line 182 of file OreoLED_I2C.h.
Referenced by clear_state(), set_macro(), set_rgb(), and update_timer().
_send_required
bool OreoLED_I2C::_send_required private
Definition at line 184 of file OreoLED_I2C.h.
Referenced by clear_state(), set_macro(), set_rgb(), and update_timer().
_slow_count
uint8_t OreoLED_I2C::_slow_count private
Definition at line 193 of file OreoLED_I2C.h.
Referenced by slow_counter().
_state_desired
oreo_state OreoLED_I2C::_state_desired[OREOLED_NUM_LEDS] private
Definition at line 185 of file OreoLED_I2C.h.
Referenced by clear_state(), set_macro(), set_rgb(), and update_timer().
_state_sent
oreo_state OreoLED_I2C::_state_sent[OREOLED_NUM_LEDS] private
Definition at line 186 of file OreoLED_I2C.h.
Referenced by set_macro(), set_rgb(), and update_timer().
The documentation for this class was generated from the following files:
libraries/AP_Notify/OreoLED_I2C.h
libraries/AP_Notify/OreoLED_I2C.cpp