APM:Libraries: RGBLed Class Reference
RGBLed Class Reference abstract
#include <RGBLed.h>
Public Member Functions
RGBLed (uint8_t led_off, uint8_t led_bright, uint8_t led_medium, uint8_t led_dim)
virtual bool init (void) override
virtual void set_rgb (uint8_t red, uint8_t green, uint8_t blue)
virtual void update () override
virtual void handle_led_control (mavlink_message_t *msg) override
Public Member Functions inherited from NotifyDevice
virtual ~NotifyDevice ()
virtual void handle_play_tune (mavlink_message_t *msg)
virtual void play_tune (const char *tune)
Protected Member Functions
virtual bool hw_init (void)=0
virtual bool hw_set_rgb (uint8_t red, uint8_t green, uint8_t blue)=0
virtual void _set_rgb (uint8_t red, uint8_t green, uint8_t blue)
void update_override ()
Protected Attributes
uint8_t _red_des
uint8_t _green_des
uint8_t _blue_des
uint8_t _red_curr
uint8_t _green_curr
uint8_t _blue_curr
uint8_t _led_off
uint8_t _led_bright
uint8_t _led_medium
uint8_t _led_dim
struct {
uint8_t r
uint8_t g
uint8_t b
uint8_t rate_hz
uint32_t start_ms
} _led_override
Private Types
enum rgb_source_t { standard = 0, mavlink = 1, obc = 2 }
Private Member Functions
void update_colours ()
uint32_t get_colour_sequence () const
uint32_t get_colour_sequence_obc () const
uint8_t get_brightness (void) const
rgb_source_t rgb_source () const
Private Attributes
const uint32_t sequence_initialising = DEFINE_COLOUR_SEQUENCE_ALTERNATE(RED,BLUE)
const uint32_t sequence_trim_or_esc = DEFINE_COLOUR_SEQUENCE(RED,BLUE,GREEN,RED,BLUE,GREEN,RED,BLUE,GREEN,OFF)
const uint32_t sequence_failsafe_leak = DEFINE_COLOUR_SEQUENCE_FAILSAFE(WHITE)
const uint32_t sequence_failsafe_ekf = DEFINE_COLOUR_SEQUENCE_FAILSAFE(RED)
const uint32_t sequence_failsafe_gps_glitching = DEFINE_COLOUR_SEQUENCE_FAILSAFE(BLUE)
const uint32_t sequence_failsafe_radio_or_battery = DEFINE_COLOUR_SEQUENCE_FAILSAFE(OFF)
const uint32_t sequence_armed = DEFINE_COLOUR_SEQUENCE_SOLID(GREEN)
const uint32_t sequence_armed_nogps = DEFINE_COLOUR_SEQUENCE_SOLID(BLUE)
const uint32_t sequence_prearm_failing = DEFINE_COLOUR_SEQUENCE(YELLOW,YELLOW,OFF,OFF,YELLOW,YELLOW,OFF,OFF,OFF,OFF)
const uint32_t sequence_disarmed_good_dgps = DEFINE_COLOUR_SEQUENCE_ALTERNATE(GREEN,OFF)
const uint32_t sequence_disarmed_good_gps = DEFINE_COLOUR_SEQUENCE_SLOW(GREEN)
const uint32_t sequence_disarmed_bad_gps = DEFINE_COLOUR_SEQUENCE_SLOW(BLUE)
uint8_t last_step
Additional Inherited Members
Public Attributes inherited from NotifyDevice
const AP_Notify * pNotify
Detailed Description
Definition at line 25 of file RGBLed.h.
Member Enumeration Documentation
rgb_source_t
enum RGBLed::rgb_source_t private
Enumerator
standard
mavlink
obc
Definition at line 107 of file RGBLed.h.
Constructor & Destructor Documentation
RGBLed()
RGBLed::RGBLed (uint8_t led_off, uint8_t led_bright, uint8_t led_medium, uint8_t led_dim)
Definition at line 26 of file RGBLed.cpp.
Member Function Documentation
_set_rgb()
void RGBLed::_set_rgb (uint8_t red, uint8_t green, uint8_t blue) protected virtual
Definition at line 41 of file RGBLed.cpp.
Referenced by set_rgb(), and update_override().
get_brightness()
uint8_t RGBLed::get_brightness (void) const private
Definition at line 70 of file RGBLed.cpp.
Referenced by update().
get_colour_sequence()
uint32_t RGBLed::get_colour_sequence (void) const private
Definition at line 105 of file RGBLed.cpp.
Referenced by update().
get_colour_sequence_obc()
uint32_t RGBLed::get_colour_sequence_obc (void) const private
Definition at line 96 of file RGBLed.cpp.
Referenced by update().
handle_led_control()
void RGBLed::handle_led_control (mavlink_message_t * msg) override virtual
Reimplemented from NotifyDevice.
Definition at line 205 of file RGBLed.cpp.
hw_init()
virtual bool RGBLed::hw_init (void) protected pure virtual
Implemented in Led_Sysfs, DiscoLED, VRBoard_LED, DiscreteRGBLed, PixRacerLED, NCP5623, PCA9685LED_I2C, ToshibaLED_I2C, RCOutputRGBLed, and UAVCAN_RGB_LED.
Referenced by init().
hw_set_rgb()
virtual bool RGBLed::hw_set_rgb (uint8_t red, uint8_t green, uint8_t blue) protected pure virtual
Implemented in RCOutputRGBLedOff, Led_Sysfs, DiscoLED, VRBoard_LED, DiscreteRGBLed, PixRacerLED, NCP5623, PCA9685LED_I2C, ToshibaLED_I2C, RCOutputRGBLed, and UAVCAN_RGB_LED.
Referenced by _set_rgb().
init()
bool RGBLed::init (void) override virtual
Implements NotifyDevice.
Definition at line 35 of file RGBLed.cpp.
Referenced by setup().
rgb_source()
RGBLed::rgb_source_t RGBLed::rgb_source () const private
Definition at line 55 of file RGBLed.cpp.
Referenced by handle_led_control(), set_rgb(), and update().
set_rgb()
void RGBLed::set_rgb (uint8_t red, uint8_t green, uint8_t blue) virtual
Definition at line 61 of file RGBLed.cpp.
Referenced by blink(), full_spectrum(), and update().
update()
void RGBLed::update (void) override virtual
Implements NotifyDevice.
Definition at line 167 of file RGBLed.cpp.
Referenced by loop().
update_colours()
void RGBLed::update_colours () private
update_override()
void RGBLed::update_override (void) protected
Definition at line 240 of file RGBLed.cpp.
Referenced by update().
Member Data Documentation
_blue_curr
uint8_t RGBLed::_blue_curr protected
Definition at line 54 of file RGBLed.h.
Referenced by _set_rgb().
_blue_des
uint8_t RGBLed::_blue_des protected
Definition at line 53 of file RGBLed.h.
Referenced by update().
_green_curr
uint8_t RGBLed::_green_curr protected
Definition at line 54 of file RGBLed.h.
Referenced by _set_rgb().
_green_des
uint8_t RGBLed::_green_des protected
Definition at line 53 of file RGBLed.h.
Referenced by update().
_led_bright
uint8_t RGBLed::_led_bright protected
Definition at line 56 of file RGBLed.h.
Referenced by get_brightness(), RCOutputRGBLed::get_duty_cycle_for_color(), and RCOutputRGBLedInverted::get_duty_cycle_for_color().
_led_dim
uint8_t RGBLed::_led_dim protected
Definition at line 58 of file RGBLed.h.
Referenced by get_brightness().
_led_medium
uint8_t RGBLed::_led_medium protected
Definition at line 57 of file RGBLed.h.
Referenced by get_brightness().
_led_off
uint8_t RGBLed::_led_off protected
Definition at line 55 of file RGBLed.h.
Referenced by get_brightness(), ToshibaLED_I2C::hw_init(), NCP5623::hw_init(), and RCOutputRGBLedOff::hw_set_rgb().
_led_override
struct { ... } RGBLed::_led_override
Referenced by handle_led_control(), and update_override().
_red_curr
uint8_t RGBLed::_red_curr protected
Definition at line 54 of file RGBLed.h.
Referenced by _set_rgb().
_red_des
uint8_t RGBLed::_red_des protected
Definition at line 53 of file RGBLed.h.
Referenced by update().
b
uint8_t RGBLed::b
Definition at line 61 of file RGBLed.h.
Referenced by PixRacerLED::hw_set_rgb().
g
uint8_t RGBLed::g
Definition at line 61 of file RGBLed.h.
Referenced by PixRacerLED::hw_set_rgb().
last_step
uint8_t RGBLed::last_step private
Definition at line 106 of file RGBLed.h.
Referenced by update().
r
uint8_t RGBLed::r
Definition at line 61 of file RGBLed.h.
Referenced by PixRacerLED::hw_set_rgb().
rate_hz
uint8_t RGBLed::rate_hz
Definition at line 62 of file RGBLed.h.
sequence_armed
const uint32_t RGBLed::sequence_armed = DEFINE_COLOUR_SEQUENCE_SOLID(GREEN) private
Definition at line 99 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_armed_nogps
const uint32_t RGBLed::sequence_armed_nogps = DEFINE_COLOUR_SEQUENCE_SOLID(BLUE) private
Definition at line 100 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_disarmed_bad_gps
const uint32_t RGBLed::sequence_disarmed_bad_gps = DEFINE_COLOUR_SEQUENCE_SLOW(BLUE) private
Definition at line 104 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_disarmed_good_dgps
const uint32_t RGBLed::sequence_disarmed_good_dgps = DEFINE_COLOUR_SEQUENCE_ALTERNATE(GREEN,OFF) private
Definition at line 102 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_disarmed_good_gps
const uint32_t RGBLed::sequence_disarmed_good_gps = DEFINE_COLOUR_SEQUENCE_SLOW(GREEN) private
Definition at line 103 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_failsafe_ekf
const uint32_t RGBLed::sequence_failsafe_ekf = DEFINE_COLOUR_SEQUENCE_FAILSAFE(RED) private
Definition at line 95 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_failsafe_gps_glitching
const uint32_t RGBLed::sequence_failsafe_gps_glitching = DEFINE_COLOUR_SEQUENCE_FAILSAFE(BLUE) private
Definition at line 96 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_failsafe_leak
const uint32_t RGBLed::sequence_failsafe_leak = DEFINE_COLOUR_SEQUENCE_FAILSAFE(WHITE) private
Definition at line 94 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_failsafe_radio_or_battery
const uint32_t RGBLed::sequence_failsafe_radio_or_battery = DEFINE_COLOUR_SEQUENCE_FAILSAFE(OFF) private
Definition at line 97 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_initialising
const uint32_t RGBLed::sequence_initialising = DEFINE_COLOUR_SEQUENCE_ALTERNATE(RED,BLUE) private
Definition at line 92 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_prearm_failing
const uint32_t RGBLed::sequence_prearm_failing = DEFINE_COLOUR_SEQUENCE(YELLOW,YELLOW,OFF,OFF,YELLOW,YELLOW,OFF,OFF,OFF,OFF) private
Definition at line 101 of file RGBLed.h.
Referenced by get_colour_sequence().
sequence_trim_or_esc
const uint32_t RGBLed::sequence_trim_or_esc = DEFINE_COLOUR_SEQUENCE(RED,BLUE,GREEN,RED,BLUE,GREEN,RED,BLUE,GREEN,OFF) private
Definition at line 93 of file RGBLed.h.
Referenced by get_colour_sequence().
start_ms
uint32_t RGBLed::start_ms
Definition at line 63 of file RGBLed.h.
The documentation for this class was generated from the following files:
libraries/AP_Notify/RGBLed.h
libraries/AP_Notify/RGBLed.cpp