APM:Libraries: AuxiliaryBus Class Reference
AuxiliaryBus Class Reference abstract
#include <AuxiliaryBus.h>
Public Member Functions
AP_InertialSensor_Backend & get_backend ()
AuxiliaryBusSlave * request_next_slave (uint8_t addr)
int register_periodic_read (AuxiliaryBusSlave *slave, uint8_t reg, uint8_t size)
virtual AP_HAL::Device::PeriodicHandle register_periodic_callback (uint32_t, AP_HAL::Device::PeriodicCb)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
void set_device_type (uint8_t devtype)
uint32_t get_bus_id (void) const
Protected Member Functions
AuxiliaryBus (AP_InertialSensor_Backend &backend, uint8_t max_slaves, uint32_t devid)
virtual ~AuxiliaryBus ()
virtual AuxiliaryBusSlave * _instantiate_slave (uint8_t addr, uint8_t instance)=0
virtual int _configure_periodic_read (AuxiliaryBusSlave *slave, uint8_t reg, uint8_t size)=0
Protected Attributes
uint8_t _n_slaves = 0
const uint8_t _max_slaves
AuxiliaryBusSlave ** _slaves
AP_InertialSensor_Backend & _ins_backend
uint32_t _devid
Friends
class AP_InertialSensor_Backend
Detailed Description
Definition at line 95 of file AuxiliaryBus.h.
Constructor & Destructor Documentation
AuxiliaryBus()
AuxiliaryBus::AuxiliaryBus (AP_InertialSensor_Backend & backend, uint8_t max_slaves, uint32_t devid) protected
Definition at line 18 of file AuxiliaryBus.cpp.
~AuxiliaryBus()
AuxiliaryBus::~AuxiliaryBus () protected virtual
Definition at line 26 of file AuxiliaryBus.cpp.
Member Function Documentation
_configure_periodic_read()
virtual int AuxiliaryBus::_configure_periodic_read (AuxiliaryBusSlave * slave, uint8_t reg, uint8_t size) protected pure virtual
Implemented in AP_Invensense_AuxiliaryBus, and AP_Invensensev2_AuxiliaryBus.
Referenced by register_periodic_read().
_instantiate_slave()
virtual AuxiliaryBusSlave* AuxiliaryBus::_instantiate_slave (uint8_t addr, uint8_t instance) protected pure virtual
Implemented in AP_Invensense_AuxiliaryBus, and AP_Invensensev2_AuxiliaryBus.
Referenced by request_next_slave().
get_backend()
AP_InertialSensor_Backend& AuxiliaryBus::get_backend () inline
Definition at line 100 of file AuxiliaryBus.h.
Referenced by AP_Invensensev2_AuxiliaryBusSlave::_set_passthrough(), AP_Invensense_AuxiliaryBusSlave::_set_passthrough(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_write(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), AP_Invensensev2_AuxiliaryBusSlave::read(), and AP_Invensense_AuxiliaryBusSlave::read().
get_bus_id()
uint32_t AuxiliaryBus::get_bus_id (void) const inline
Definition at line 130 of file AuxiliaryBus.h.
Referenced by AP_AK8963_BusDriver_Auxiliary::get_bus_id(), and AP_AK09916_BusDriver_Auxiliary::get_bus_id().
get_semaphore()
virtual AP_HAL::Semaphore* AuxiliaryBus::get_semaphore () pure virtual
Implemented in AP_Invensense_AuxiliaryBus, and AP_Invensensev2_AuxiliaryBus.
Referenced by AP_AK8963_BusDriver_Auxiliary::get_semaphore(), and AP_AK09916_BusDriver_Auxiliary::get_semaphore().
register_periodic_callback()
virtual AP_HAL::Device::PeriodicHandle AuxiliaryBus::register_periodic_callback (uint32_t , AP_HAL::Device::PeriodicCb) pure virtual
Implemented in AP_Invensense_AuxiliaryBus, and AP_Invensensev2_AuxiliaryBus.
Referenced by AP_AK8963_BusDriver_Auxiliary::register_periodic_callback(), and AP_AK09916_BusDriver_Auxiliary::register_periodic_callback().
register_periodic_read()
int AuxiliaryBus::register_periodic_read (AuxiliaryBusSlave * slave, uint8_t reg, uint8_t size)
Definition at line 85 of file AuxiliaryBus.cpp.
Referenced by AP_AK8963_BusDriver_Auxiliary::start_measurements(), and AP_AK09916_BusDriver_Auxiliary::start_measurements().
request_next_slave()
AuxiliaryBusSlave * AuxiliaryBus::request_next_slave (uint8_t addr)
Definition at line 47 of file AuxiliaryBus.cpp.
Referenced by AP_AK09916_BusDriver_Auxiliary::AP_AK09916_BusDriver_Auxiliary(), and AP_AK8963_BusDriver_Auxiliary::AP_AK8963_BusDriver_Auxiliary().
set_device_type()
void AuxiliaryBus::set_device_type (uint8_t devtype) inline
Definition at line 125 of file AuxiliaryBus.h.
Referenced by AP_AK8963_BusDriver_Auxiliary::set_device_type(), and AP_AK09916_BusDriver_Auxiliary::set_device_type().
Friends And Related Function Documentation
AP_InertialSensor_Backend
friend class AP_InertialSensor_Backend friend
Definition at line 97 of file AuxiliaryBus.h.
Member Data Documentation
_devid
uint32_t AuxiliaryBus::_devid protected
Definition at line 147 of file AuxiliaryBus.h.
Referenced by get_bus_id(), and set_device_type().
_ins_backend
AP_InertialSensor_Backend& AuxiliaryBus::_ins_backend protected
Definition at line 146 of file AuxiliaryBus.h.
Referenced by AP_Invensensev2_AuxiliaryBus::_configure_slaves(), AP_Invensense_AuxiliaryBus::_configure_slaves(), get_backend(), AP_Invensensev2_AuxiliaryBus::get_semaphore(), AP_Invensense_AuxiliaryBus::get_semaphore(), AP_Invensensev2_AuxiliaryBus::register_periodic_callback(), and AP_Invensense_AuxiliaryBus::register_periodic_callback().
_max_slaves
const uint8_t AuxiliaryBus::_max_slaves protected
Definition at line 144 of file AuxiliaryBus.h.
Referenced by register_periodic_read(), and request_next_slave().
_n_slaves
uint8_t AuxiliaryBus::_n_slaves = 0 protected
Definition at line 143 of file AuxiliaryBus.h.
Referenced by register_periodic_read(), request_next_slave(), and ~AuxiliaryBus().
_slaves
AuxiliaryBusSlave** AuxiliaryBus::_slaves protected
Definition at line 145 of file AuxiliaryBus.h.
Referenced by AuxiliaryBus(), register_periodic_read(), and ~AuxiliaryBus().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AuxiliaryBus.h
libraries/AP_InertialSensor/AuxiliaryBus.cpp