APM:Libraries: AP_HAL::RCOutput Class Reference
AP_HAL::RCOutput Class Reference abstract
#include <RCOutput.h>
Public Types
enum output_mode {
MODE_PWM_NONE, MODE_PWM_NORMAL, MODE_PWM_ONESHOT, MODE_PWM_ONESHOT125,
MODE_PWM_BRUSHED, MODE_PWM_DSHOT150, MODE_PWM_DSHOT300, MODE_PWM_DSHOT600,
MODE_PWM_DSHOT1200
}
Public Member Functions
virtual void init ()=0
virtual void set_freq (uint32_t chmask, uint16_t freq_hz)=0
virtual uint16_t get_freq (uint8_t chan)=0
virtual void enable_ch (uint8_t chan)=0
virtual void disable_ch (uint8_t chan)=0
virtual void write (uint8_t chan, uint16_t period_us)=0
virtual void set_reversible_mask (uint16_t chanmask)
virtual void cork ()=0
virtual void push ()=0
virtual uint16_t read (uint8_t chan)=0
virtual void read (uint16_t *period_us, uint8_t len)=0
virtual uint16_t read_last_sent (uint8_t chan)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void force_safety_no_wait (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
virtual bool get_esc_scaling (uint16_t &min_pwm, uint16_t &max_pwm)
virtual float scale_esc_to_unity (uint16_t pwm)
virtual bool enable_px4io_sbus_out (uint16_t rate_hz)
virtual void timer_tick (void)
virtual bool serial_setup_output (uint8_t chan, uint32_t baudrate, uint16_t chanmask)
virtual bool serial_write_bytes (const uint8_t *bytes, uint16_t len)
virtual uint16_t serial_read_bytes (uint8_t *buf, uint16_t len)
virtual void serial_end (void)
virtual void set_output_mode (uint16_t mask, enum output_mode mode)
virtual void set_default_rate (uint16_t rate_hz)
virtual void set_telem_request_mask (uint16_t mask)
Detailed Description
Definition at line 34 of file RCOutput.h.
Member Enumeration Documentation
output_mode
enum AP_HAL::RCOutput::output_mode
Enumerator
MODE_PWM_NONE
MODE_PWM_NORMAL
MODE_PWM_ONESHOT
MODE_PWM_ONESHOT125
MODE_PWM_BRUSHED
MODE_PWM_DSHOT150
MODE_PWM_DSHOT300
MODE_PWM_DSHOT600
MODE_PWM_DSHOT1200
Definition at line 176 of file RCOutput.h.
Member Function Documentation
cork()
virtual void AP_HAL::RCOutput::cork () pure virtual
Implemented in ap::RCOutput_Tap, Linux::RCOutput_Bebop, Linux::RCOutput_AeroIO, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by SRV_Channels::cork(), and AP_IOMCU_FW::pwm_out_update().
disable_ch()
virtual void AP_HAL::RCOutput::disable_ch (uint8_t chan) pure virtual
Implemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, Linux::RCOutput_AeroIO, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
enable_ch()
virtual void AP_HAL::RCOutput::enable_ch (uint8_t chan) pure virtual
Implemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, ChibiOS::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by SRV_Channels::enable_aux_servos(), SRV_Channels::enable_by_mask(), RCOutputRGBLed::hw_init(), RC_UART::loop(), and setup().
enable_px4io_sbus_out()
virtual bool AP_HAL::RCOutput::enable_px4io_sbus_out (uint16_t rate_hz) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 133 of file RCOutput.h.
Referenced by AP_BoardConfig::board_setup_sbus().
force_safety_no_wait()
virtual void AP_HAL::RCOutput::force_safety_no_wait (void) inline virtual
Definition at line 110 of file RCOutput.h.
Referenced by AP_BoardConfig::board_init_safety(), and GCS_MAVLINK::handle_preflight_reboot().
force_safety_off()
virtual void AP_HAL::RCOutput::force_safety_off (void) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 105 of file RCOutput.h.
Referenced by GCS_MAVLINK::_set_mode_common(), AP_BoardConfig::board_init_safety(), AP_IOMCU_FW::handle_code_write(), AP_IOMCU_FW::init(), RC_UART::loop(), and AP_IOMCU_FW::safety_update().
force_safety_on()
virtual bool AP_HAL::RCOutput::force_safety_on (void) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 100 of file RCOutput.h.
Referenced by GCS_MAVLINK::_set_mode_common(), AP_Arming::disarm(), AP_IOMCU_FW::handle_code_write(), GCS_MAVLINK::handle_preflight_reboot(), ChibiOS::Scheduler::reboot(), and AP_IOMCU_FW::safety_update().
get_esc_scaling()
virtual bool AP_HAL::RCOutput::get_esc_scaling (uint16_t & min_pwm, uint16_t & max_pwm) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 123 of file RCOutput.h.
get_freq()
virtual uint16_t AP_HAL::RCOutput::get_freq (uint8_t chan) pure virtual
Implemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, Linux::RCOutput_AeroIO, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by RCOutputRGBLed::hw_set_rgb().
init()
virtual void AP_HAL::RCOutput::init () pure virtual
Implemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, ChibiOS::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by AP_BoardConfig::board_setup(), HAL_Linux::run(), HAL_SITL::run(), and setup().
push()
virtual void AP_HAL::RCOutput::push () pure virtual
Implemented in ap::RCOutput_Tap, Linux::RCOutput_Bebop, Linux::RCOutput_AeroIO, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by SRV_Channels::push(), and AP_IOMCU_FW::pwm_out_update().
read() [1/2]
virtual uint16_t AP_HAL::RCOutput::read (uint8_t chan) pure virtual
Implemented in Linux::RCOutput_AeroIO, Linux::RCOutput_Bebop, ap::RCOutput_Tap, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by read_last_sent(), GCS_MAVLINK::send_servo_output_raw(), stability_test(), and AP_Logger::Write_RCOUT().
read() [2/2]
virtual void AP_HAL::RCOutput::read (uint16_t * period_us, uint8_t len) pure virtual
Implemented in Linux::RCOutput_AeroIO, Linux::RCOutput_Bebop, ap::RCOutput_Tap, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
read_last_sent() [1/2]
virtual uint16_t AP_HAL::RCOutput::read_last_sent (uint8_t chan) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 81 of file RCOutput.h.
Referenced by SRV_Channels::limit_slew_rate(), and Compass_PerMotor::scaled_output().
read_last_sent() [2/2]
virtual void AP_HAL::RCOutput::read_last_sent (uint16_t * period_us, uint8_t len) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 82 of file RCOutput.h.
scale_esc_to_unity()
virtual float AP_HAL::RCOutput::scale_esc_to_unity (uint16_t pwm) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 128 of file RCOutput.h.
Referenced by Compass_PerMotor::scaled_output().
serial_end()
virtual void AP_HAL::RCOutput::serial_end (void) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 171 of file RCOutput.h.
serial_read_bytes()
virtual uint16_t AP_HAL::RCOutput::serial_read_bytes (uint8_t * buf, uint16_t len) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 164 of file RCOutput.h.
serial_setup_output()
virtual bool AP_HAL::RCOutput::serial_setup_output (uint8_t chan, uint32_t baudrate, uint16_t chanmask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 152 of file RCOutput.h.
serial_write_bytes()
virtual bool AP_HAL::RCOutput::serial_write_bytes (const uint8_t * bytes, uint16_t len) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 158 of file RCOutput.h.
set_default_rate()
virtual void AP_HAL::RCOutput::set_default_rate (uint16_t rate_hz) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 192 of file RCOutput.h.
Referenced by SRV_Channels::enable_aux_servos(), and AP_IOMCU_FW::rcin_update().
set_esc_scaling()
virtual void AP_HAL::RCOutput::set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm) inline virtual
Reimplemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, ChibiOS::RCOutput, and Linux::RCOutput_Disco.
Definition at line 118 of file RCOutput.h.
Referenced by AP_IOMCU_FW::rcout_mode_update(), Linux::RCOutput_Disco::set_esc_scaling(), SRV_Channels::set_esc_scaling_for(), and AP_MotorsMulticopter::set_throttle_range().
set_failsafe_pwm()
virtual void AP_HAL::RCOutput::set_failsafe_pwm (uint32_t chmask, uint16_t period_us) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 93 of file RCOutput.h.
Referenced by SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), and SRV_Channels::setup_failsafe_trim_all_non_motors().
set_freq()
virtual void AP_HAL::RCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) pure virtual
Implemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, Linux::RCOutput_AeroIO, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by drive(), RCOutputRGBLed::hw_set_rgb(), AP_Motors::rc_set_freq(), AP_IOMCU_FW::rcin_update(), AP_IOMCU_FW::rcout_mode_update(), SRV_Channels::set_rc_frequency(), and RC_UART::setup().
set_output_mode()
virtual void AP_HAL::RCOutput::set_output_mode (uint16_t mask, enum output_mode mode) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 187 of file RCOutput.h.
Referenced by AP_Motors::rc_set_freq(), and AP_IOMCU_FW::rcout_mode_update().
set_reversible_mask()
virtual void AP_HAL::RCOutput::set_reversible_mask (uint16_t chanmask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 58 of file RCOutput.h.
set_safety_pwm()
virtual void AP_HAL::RCOutput::set_safety_pwm (uint32_t chmask, uint16_t period_us) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 88 of file RCOutput.h.
Referenced by SRV_Channels::set_safety_limit().
set_telem_request_mask()
virtual void AP_HAL::RCOutput::set_telem_request_mask (uint16_t mask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 198 of file RCOutput.h.
timer_tick()
virtual void AP_HAL::RCOutput::timer_tick (void) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 139 of file RCOutput.h.
Referenced by ChibiOS::Scheduler::_timer_thread(), and AP_IOMCU_FW::update().
write()
virtual void AP_HAL::RCOutput::write (uint8_t chan, uint16_t period_us) pure virtual
Implemented in Linux::RCOutput_Bebop, ap::RCOutput_Tap, Linux::RCOutput_AeroIO, ChibiOS::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PCA9685, Linux::RCOutput_Disco, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by drive(), RC_UART::loop(), loop(), SRV_Channel::output_ch(), AP_IOMCU_FW::pwm_out_update(), and GCS_MAVLINK::zero_rc_outputs().
The documentation for this class was generated from the following file:
libraries/AP_HAL/RCOutput.h