APM:Libraries: CompassCalibrator::CompassSample Class Reference
CompassCalibrator::CompassSample Class Reference
Public Member Functions
Vector3f get () const
void set (const Vector3f &in)
Public Attributes
AttitudeSample att
Private Attributes
int16_t x
int16_t y
int16_t z
Detailed Description
Definition at line 87 of file CompassCalibrator.h.
Member Function Documentation
get()
Vector3f CompassCalibrator::CompassSample::get () const
Definition at line 701 of file CompassCalibrator.cpp.
Referenced by CompassCalibrator::accept_sample(), CompassCalibrator::calc_initial_offset(), CompassCalibrator::calc_mean_squared_residuals(), CompassCalibrator::calculate_earth_field(), CompassCalibrator::calculate_orientation(), CompassCalibrator::run_ellipsoid_fit(), and CompassCalibrator::run_sphere_fit().
set()
void CompassCalibrator::CompassSample::set (const Vector3f & in)
Definition at line 707 of file CompassCalibrator.cpp.
Referenced by CompassCalibrator::calculate_orientation(), and CompassCalibrator::new_sample().
Member Data Documentation
att
AttitudeSample CompassCalibrator::CompassSample::att
Definition at line 91 of file CompassCalibrator.h.
Referenced by CompassCalibrator::calculate_earth_field(), and CompassCalibrator::new_sample().
x
int16_t CompassCalibrator::CompassSample::x private
Definition at line 93 of file CompassCalibrator.h.
Referenced by get().
y
int16_t CompassCalibrator::CompassSample::y private
Definition at line 94 of file CompassCalibrator.h.
Referenced by get().
z
int16_t CompassCalibrator::CompassSample::z private
Definition at line 95 of file CompassCalibrator.h.
Referenced by get().
The documentation for this class was generated from the following files:
libraries/AP_Compass/CompassCalibrator.h
libraries/AP_Compass/CompassCalibrator.cpp