APM:Libraries: Linux::Util Class Reference
Linux::Util Class Reference
#include <Util.h>
Public Member Functions
void init (int argc, char *const *argv)
bool run_debug_shell (AP_HAL::BetterStream *stream) override
void commandline_arguments (uint8_t &argc, char *const *&argv) override
void set_hw_rtc (uint64_t time_utc_usec) override
const char * get_custom_log_directory () const override final
const char * get_custom_terrain_directory () const override final
const char * get_custom_storage_directory () const override final
void set_custom_log_directory (const char *_custom_log_directory)
void set_custom_terrain_directory (const char *_custom_terrain_directory)
void set_custom_storage_directory (const char *_custom_storage_directory)
bool is_chardev_node (const char *path)
void set_imu_temp (float current) override
void set_imu_target_temp (int8_t *target) override
uint32_t available_memory (void) override
bool get_system_id (char buf[40]) override
bool get_system_id_unformatted (uint8_t buf[], uint8_t &len) override
int write_file (const char *path, const char *fmt,...) FMT_PRINTF(3
int int read_file (const char *path, const char *fmt,...) FMT_SCANF(3
int int perf_counter_t perf_alloc (enum perf_counter_type t, const char *name) override
void perf_begin (perf_counter_t perf) override
void perf_end (perf_counter_t perf) override
void perf_count (perf_counter_t perf) override
int get_hw_arm32 ()
bool toneAlarm_init () override
void toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) override
Public Member Functions inherited from AP_HAL::Util
int snprintf (char *str, size_t size, const char *format,...)
int vsnprintf (char *str, size_t size, const char *format, va_list ap)
void set_soft_armed (const bool b)
bool get_soft_armed () const
uint32_t get_last_armed_change () const
virtual bool was_watchdog_reset () const
bool was_watchdog_safety_off () const
bool was_watchdog_armed () const
virtual const char * get_custom_defaults_file () const
virtual enum safety_state safety_switch_state (void)
virtual uint64_t get_hw_rtc () const
virtual bool flash_bootloader ()
virtual AP_HAL::BetterStream * get_shell_stream ()
virtual void * malloc_type (size_t size, Memory_Type mem_type)
virtual void free_type (void *ptr, size_t size, Memory_Type mem_type)
virtual bool fs_init (void)
Static Public Member Functions
static Util * from (AP_HAL::Util *util)
Private Attributes
int saved_argc
Heat * _heat
char *const * saved_argv
const char * custom_log_directory = nullptr
const char * custom_terrain_directory = nullptr
const char * custom_storage_directory = nullptr
Static Private Attributes
static ToneAlarm_Disco _toneAlarm
static const char * _hw_names [UTIL_NUM_HARDWARES]
Additional Inherited Members
Public Types inherited from AP_HAL::Util
enum safety_state { SAFETY_NONE, SAFETY_DISARMED, SAFETY_ARMED }
enum perf_counter_type { PC_COUNT, PC_ELAPSED, PC_INTERVAL }
enum Memory_Type { MEM_DMA_SAFE, MEM_FAST }
typedef void * perf_counter_t
Public Attributes inherited from AP_HAL::Util
struct PersistentData persistent_data
Protected Attributes inherited from AP_HAL::Util
bool soft_armed = false
uint32_t last_armed_change_ms
Detailed Description
Definition at line 25 of file Util.h.
Member Function Documentation
available_memory()
uint32_t Util::available_memory (void) override virtual
how much free memory do we have in bytes. If unknown return 4096
Reimplemented from AP_HAL::Util.
Definition at line 91 of file Util.cpp.
commandline_arguments()
void Util::commandline_arguments (uint8_t & argc, char *const *& argv) override virtual
return commandline arguments, if available
Reimplemented from AP_HAL::Util.
Definition at line 59 of file Util.cpp.
from()
static Util* Linux::Util::from (AP_HAL::Util * util) inline static
Definition at line 27 of file Util.h.
Referenced by Linux::UtilRPI::_check_rpi_version(), Linux::GPIO_Sysfs::_pinMode(), Linux::RCOutput_Bebop::_run_rcout(), Linux::PWM_Sysfs_Base::enable(), Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), Linux::PWM_Sysfs_Base::init(), Linux::Led_Sysfs::init(), Linux::PWM_Sysfs_Base::is_enabled(), Linux::PWM_Sysfs_Base::set_period(), and Linux::PWM_Sysfs_Base::set_polarity().
get_custom_log_directory()
const char* Linux::Util::get_custom_log_directory () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 43 of file Util.h.
get_custom_storage_directory()
const char* Linux::Util::get_custom_storage_directory () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 45 of file Util.h.
get_custom_terrain_directory()
const char* Linux::Util::get_custom_terrain_directory () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 44 of file Util.h.
get_hw_arm32()
int Util::get_hw_arm32 ()
Definition at line 208 of file Util.cpp.
Referenced by Linux::UtilRPI::_check_rpi_version(), and Linux::RCOutput_Bebop::_run_rcout().
get_system_id()
bool Util::get_system_id (char buf[40]) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 142 of file Util.cpp.
get_system_id_unformatted()
bool Util::get_system_id_unformatted (uint8_t buf[], uint8_t & len) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 103 of file Util.cpp.
Referenced by get_system_id().
init()
void Util::init (int argc, char *const * argv)
Definition at line 26 of file Util.cpp.
Referenced by HAL_Linux::run().
is_chardev_node()
bool Util::is_chardev_node (const char * path)
Definition at line 74 of file Util.cpp.
perf_alloc()
int int perf_counter_t Linux::Util::perf_alloc (enum perf_counter_type t, const char * name) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 82 of file Util.h.
perf_begin()
void Linux::Util::perf_begin (perf_counter_t perf) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 87 of file Util.h.
perf_count()
void Linux::Util::perf_count (perf_counter_t perf) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 97 of file Util.h.
perf_end()
void Linux::Util::perf_end (perf_counter_t perf) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 92 of file Util.h.
read_file()
int Util::read_file (const char * path, const char * fmt, ...)
Definition at line 174 of file Util.cpp.
Referenced by Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), Linux::Led_Sysfs::init(), and Linux::PWM_Sysfs_Base::is_enabled().
run_debug_shell()
bool Linux::Util::run_debug_shell (AP_HAL::BetterStream * stream) inline override virtual
Implements AP_HAL::Util.
Definition at line 32 of file Util.h.
set_custom_log_directory()
void Linux::Util::set_custom_log_directory (const char * _custom_log_directory) inline
Definition at line 47 of file Util.h.
Referenced by HAL_Linux::run().
set_custom_storage_directory()
void Linux::Util::set_custom_storage_directory (const char * _custom_storage_directory) inline
Definition at line 49 of file Util.h.
Referenced by HAL_Linux::run().
set_custom_terrain_directory()
void Linux::Util::set_custom_terrain_directory (const char * _custom_terrain_directory) inline
Definition at line 48 of file Util.h.
Referenced by HAL_Linux::run().
set_hw_rtc()
void Util::set_hw_rtc (uint64_t time_utc_usec) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 65 of file Util.cpp.
set_imu_target_temp()
void Util::set_imu_target_temp (int8_t * target) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 51 of file Util.cpp.
set_imu_temp()
void Util::set_imu_temp (float current) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 45 of file Util.cpp.
toneAlarm_init()
bool Linux::Util::toneAlarm_init () inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 104 of file Util.h.
toneAlarm_set_buzzer_tone()
void Linux::Util::toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 105 of file Util.h.
write_file()
int Util::write_file (const char * path, const char * fmt, ...)
Definition at line 149 of file Util.cpp.
Referenced by Linux::GPIO_Sysfs::_pinMode(), Linux::PWM_Sysfs_Base::enable(), Linux::PWM_Sysfs_Base::init(), Linux::PWM_Sysfs_Base::set_period(), and Linux::PWM_Sysfs_Base::set_polarity().
Member Data Documentation
_heat
Heat* Linux::Util::_heat private
Definition at line 116 of file Util.h.
Referenced by init(), set_imu_target_temp(), and set_imu_temp().
_hw_names
const char * Linux::Util::_hw_names static private
Initial value:
= {
    [UTIL_HARDWARE_RPI1]   = "BCM2708",
    [UTIL_HARDWARE_RPI2]   = "BCM2709",
    [UTIL_HARDWARE_BEBOP]  = "Mykonos3 board",
    [UTIL_HARDWARE_BEBOP2] = "Milos board",
    [UTIL_HARDWARE_DISCO]  = "Evinrude board",
}
Definition at line 121 of file Util.h.
Referenced by get_hw_arm32().
_toneAlarm
ToneAlarm_Disco Util::_toneAlarm static private
Definition at line 111 of file Util.h.
Referenced by toneAlarm_init(), and toneAlarm_set_buzzer_tone().
custom_log_directory
const char* Linux::Util::custom_log_directory = nullptr private
Definition at line 118 of file Util.h.
Referenced by get_custom_log_directory(), and set_custom_log_directory().
custom_storage_directory
const char* Linux::Util::custom_storage_directory = nullptr private
Definition at line 120 of file Util.h.
Referenced by get_custom_storage_directory(), and set_custom_storage_directory().
custom_terrain_directory
const char* Linux::Util::custom_terrain_directory = nullptr private
Definition at line 119 of file Util.h.
Referenced by get_custom_terrain_directory(), and set_custom_terrain_directory().
saved_argc
int Linux::Util::saved_argc private
Definition at line 115 of file Util.h.
Referenced by commandline_arguments(), and init().
saved_argv
char* const* Linux::Util::saved_argv private
Definition at line 117 of file Util.h.
Referenced by commandline_arguments(), and init().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Util.h
libraries/AP_HAL_Linux/Util.cpp