APM:Libraries: AP_Proximity_TeraRangerTowerEvo Class Reference
AP_Proximity_TeraRangerTowerEvo Class Reference
#include <AP_Proximity_TeraRangerTowerEvo.h>
Public Member Functions
AP_Proximity_TeraRangerTowerEvo (AP_Proximity &_frontend, AP_Proximity::Proximity_State &_state, AP_SerialManager &serial_manager)
void update (void) override
float distance_max () const override
float distance_min () const override
Public Member Functions inherited from AP_Proximity_Backend
AP_Proximity_Backend (AP_Proximity &_frontend, AP_Proximity::Proximity_State &_state)
virtual ~AP_Proximity_Backend (void)
virtual bool get_upward_distance (float &distance) const
virtual void handle_msg (mavlink_message_t *msg)
bool get_horizontal_distance (float angle_deg, float &distance) const
const Vector2f * get_boundary_points (uint16_t &num_points) const
bool get_closest_object (float &angle_deg, float &distance) const
uint8_t get_object_count () const
bool get_object_angle_and_distance (uint8_t object_number, float &angle_deg, float &distance) const
bool get_horizontal_distances (AP_Proximity::Proximity_Distance_Array &prx_dist_array) const
bool copy_locations (AP_Proximity::Proximity_Location *buff, uint16_t buff_size, uint16_t &num_copied)
Static Public Member Functions
static bool detect (AP_SerialManager &serial_manager)
Private Types
enum InitState {
InitState_Printout = 0, InitState_Sequence, InitState_Rate, InitState_StreamStart,
InitState_Finished
}
Private Member Functions
void initialise_modes ()
bool read_sensor_data ()
void update_sector_data (int16_t angle_deg, uint16_t distance_cm)
void set_mode (const uint8_t *c, int length)
Private Attributes
AP_HAL::UARTDriver * uart = nullptr
uint8_t buffer [21]
uint8_t buffer_count
uint32_t _last_distance_received_ms
uint32_t _last_request_sent_ms
const uint16_t _mode_request_delay = 1000
enum InitState _current_init_state = InitState_Printout
const uint8_t BINARY_MODE [4] = {(uint8_t)0x00, (uint8_t)0x11, (uint8_t)0x02, (uint8_t)0x4C}
const uint8_t TOWER_MODE [4] = {(uint8_t)0x00, (uint8_t)0x31, (uint8_t)0x03, (uint8_t)0xE5}
const uint8_t SEQUENCE_MODE [4] = {(uint8_t)0x00, (uint8_t)0x31, (uint8_t)0x02, (uint8_t)0xE2}
const uint8_t ACTIVATE_STREAM [5] = {(uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x02, (uint8_t)0x01, (uint8_t)0xDF}
const uint8_t REFRESH_50_HZ [5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x02, (uint8_t)0xC3}
const uint8_t REFRESH_100_HZ [5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x03, (uint8_t)0xC4}
const uint8_t REFRESH_250_HZ [5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x04, (uint8_t)0xD1}
const uint8_t REFRESH_500_HZ [5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x05, (uint8_t)0xD6}
const uint8_t REFRESH_600_HZ [5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x06, (uint8_t)0xDF}
Additional Inherited Members
Protected Member Functions inherited from AP_Proximity_Backend
void set_status (AP_Proximity::Proximity_Status status)
bool convert_angle_to_sector (float angle_degrees, uint8_t &sector) const
void init_boundary ()
void update_boundary_for_sector (uint8_t sector)
uint8_t get_ignore_area_count () const
bool get_ignore_area (uint8_t index, uint16_t &angle_deg, uint8_t &width_deg) const
bool get_next_ignore_start_or_end (uint8_t start_or_end, int16_t start_angle, int16_t &ignore_start) const
void update_locations ()
Protected Attributes inherited from AP_Proximity_Backend
AP_Proximity & frontend
AP_Proximity::Proximity_State & state
uint8_t _num_sectors = PROXIMITY_MAX_DIRECTION
uint16_t _sector_middle_deg [PROXIMITY_SECTORS_MAX] = {0, 45, 90, 135, 180, 225, 270, 315, 0, 0, 0, 0}
uint8_t _sector_width_deg [PROXIMITY_SECTORS_MAX] = {45, 45, 45, 45, 45, 45, 45, 45, 0, 0, 0, 0}
float _angle [PROXIMITY_SECTORS_MAX]
float _distance [PROXIMITY_SECTORS_MAX]
bool _distance_valid [PROXIMITY_SECTORS_MAX]
Vector2f _sector_edge_vector [PROXIMITY_SECTORS_MAX]
Vector2f _boundary_point [PROXIMITY_SECTORS_MAX]
uint16_t _location_count
AP_Proximity::Proximity_Location _locations [PROXIMITY_SECTORS_MAX]
HAL_Semaphore_Recursive _rsem
Detailed Description
Definition at line 8 of file AP_Proximity_TeraRangerTowerEvo.h.
Member Enumeration Documentation
InitState
enum AP_Proximity_TeraRangerTowerEvo::InitState private
Enumerator
InitState_Printout
InitState_Sequence
InitState_Rate
InitState_StreamStart
InitState_Finished
Definition at line 32 of file AP_Proximity_TeraRangerTowerEvo.h.
Constructor & Destructor Documentation
AP_Proximity_TeraRangerTowerEvo()
AP_Proximity_TeraRangerTowerEvo::AP_Proximity_TeraRangerTowerEvo (AP_Proximity & _frontend, AP_Proximity::Proximity_State & _state, AP_SerialManager & serial_manager)
Definition at line 30 of file AP_Proximity_TeraRangerTowerEvo.cpp.
Member Function Documentation
detect()
bool AP_Proximity_TeraRangerTowerEvo::detect (AP_SerialManager & serial_manager) static
Definition at line 43 of file AP_Proximity_TeraRangerTowerEvo.cpp.
Referenced by AP_Proximity::detect_instance().
distance_max()
float AP_Proximity_TeraRangerTowerEvo::distance_max () const override virtual
Implements AP_Proximity_Backend.
Definition at line 75 of file AP_Proximity_TeraRangerTowerEvo.cpp.
distance_min()
float AP_Proximity_TeraRangerTowerEvo::distance_min () const override virtual
Implements AP_Proximity_Backend.
Definition at line 79 of file AP_Proximity_TeraRangerTowerEvo.cpp.
initialise_modes()
void AP_Proximity_TeraRangerTowerEvo::initialise_modes () private
Definition at line 84 of file AP_Proximity_TeraRangerTowerEvo.cpp.
Referenced by update().
read_sensor_data()
bool AP_Proximity_TeraRangerTowerEvo::read_sensor_data () private
Definition at line 110 of file AP_Proximity_TeraRangerTowerEvo.cpp.
Referenced by update().
set_mode()
void AP_Proximity_TeraRangerTowerEvo::set_mode (const uint8_t * c, int length) private
Definition at line 103 of file AP_Proximity_TeraRangerTowerEvo.cpp.
Referenced by initialise_modes().
update()
void AP_Proximity_TeraRangerTowerEvo::update (void) override virtual
Implements AP_Proximity_Backend.
Definition at line 51 of file AP_Proximity_TeraRangerTowerEvo.cpp.
update_sector_data()
void AP_Proximity_TeraRangerTowerEvo::update_sector_data (int16_t angle_deg, uint16_t distance_cm) private
Definition at line 170 of file AP_Proximity_TeraRangerTowerEvo.cpp.
Referenced by read_sensor_data().
Member Data Documentation
_current_init_state
enum InitState AP_Proximity_TeraRangerTowerEvo::_current_init_state = InitState_Printout private
Definition at line 49 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by initialise_modes(), read_sensor_data(), and update().
_last_distance_received_ms
uint32_t AP_Proximity_TeraRangerTowerEvo::_last_distance_received_ms private
Definition at line 46 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by update(), and update_sector_data().
_last_request_sent_ms
uint32_t AP_Proximity_TeraRangerTowerEvo::_last_request_sent_ms private
Definition at line 47 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by AP_Proximity_TeraRangerTowerEvo(), initialise_modes(), and set_mode().
_mode_request_delay
const uint16_t AP_Proximity_TeraRangerTowerEvo::_mode_request_delay = 1000 private
Definition at line 48 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by initialise_modes().
ACTIVATE_STREAM
const uint8_t AP_Proximity_TeraRangerTowerEvo::ACTIVATE_STREAM[5] = {(uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x02, (uint8_t)0x01, (uint8_t)0xDF} private
Definition at line 56 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by initialise_modes().
BINARY_MODE
const uint8_t AP_Proximity_TeraRangerTowerEvo::BINARY_MODE[4] = {(uint8_t)0x00, (uint8_t)0x11, (uint8_t)0x02, (uint8_t)0x4C} private
Definition at line 53 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by initialise_modes().
buffer
uint8_t AP_Proximity_TeraRangerTowerEvo::buffer[21] private
Definition at line 42 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by read_sensor_data().
buffer_count
uint8_t AP_Proximity_TeraRangerTowerEvo::buffer_count private
Definition at line 43 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by read_sensor_data().
REFRESH_100_HZ
const uint8_t AP_Proximity_TeraRangerTowerEvo::REFRESH_100_HZ[5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x03, (uint8_t)0xC4} private
Definition at line 58 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by initialise_modes().
REFRESH_250_HZ
const uint8_t AP_Proximity_TeraRangerTowerEvo::REFRESH_250_HZ[5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x04, (uint8_t)0xD1} private
Definition at line 59 of file AP_Proximity_TeraRangerTowerEvo.h.
REFRESH_500_HZ
const uint8_t AP_Proximity_TeraRangerTowerEvo::REFRESH_500_HZ[5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x05, (uint8_t)0xD6} private
Definition at line 60 of file AP_Proximity_TeraRangerTowerEvo.h.
REFRESH_50_HZ
const uint8_t AP_Proximity_TeraRangerTowerEvo::REFRESH_50_HZ[5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x02, (uint8_t)0xC3} private
Definition at line 57 of file AP_Proximity_TeraRangerTowerEvo.h.
REFRESH_600_HZ
const uint8_t AP_Proximity_TeraRangerTowerEvo::REFRESH_600_HZ[5] = { (uint8_t)0x00, (uint8_t)0x52, (uint8_t)0x03, (uint8_t)0x06, (uint8_t)0xDF} private
Definition at line 61 of file AP_Proximity_TeraRangerTowerEvo.h.
SEQUENCE_MODE
const uint8_t AP_Proximity_TeraRangerTowerEvo::SEQUENCE_MODE[4] = {(uint8_t)0x00, (uint8_t)0x31, (uint8_t)0x02, (uint8_t)0xE2} private
Definition at line 55 of file AP_Proximity_TeraRangerTowerEvo.h.
TOWER_MODE
const uint8_t AP_Proximity_TeraRangerTowerEvo::TOWER_MODE[4] = {(uint8_t)0x00, (uint8_t)0x31, (uint8_t)0x03, (uint8_t)0xE5} private
Definition at line 54 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by initialise_modes().
uart
AP_HAL::UARTDriver* AP_Proximity_TeraRangerTowerEvo::uart = nullptr private
Definition at line 41 of file AP_Proximity_TeraRangerTowerEvo.h.
Referenced by AP_Proximity_TeraRangerTowerEvo(), detect(), read_sensor_data(), set_mode(), and update().
The documentation for this class was generated from the following files:
libraries/AP_Proximity/AP_Proximity_TeraRangerTowerEvo.h
libraries/AP_Proximity/AP_Proximity_TeraRangerTowerEvo.cpp