APM:Libraries: AP_WheelEncoder_Backend Class Reference
AP_WheelEncoder_Backend Class Reference abstract
#include <WheelEncoder_Backend.h>
Public Member Functions
AP_WheelEncoder_Backend (AP_WheelEncoder &frontend, uint8_t instance, AP_WheelEncoder::WheelEncoder_State &state)
virtual ~AP_WheelEncoder_Backend (void)
virtual void update ()=0
Protected Member Functions
int8_t get_pin_a () const
int8_t get_pin_b () const
void copy_state_to_frontend (int32_t distance_count, uint32_t total_count, uint32_t error_count, uint32_t last_reading_ms)
Protected Attributes
AP_WheelEncoder & _frontend
AP_WheelEncoder::WheelEncoder_State & _state
Detailed Description
Definition at line 21 of file WheelEncoder_Backend.h.
Constructor & Destructor Documentation
AP_WheelEncoder_Backend()
AP_WheelEncoder_Backend::AP_WheelEncoder_Backend (AP_WheelEncoder & frontend, uint8_t instance, AP_WheelEncoder::WheelEncoder_State & state)
Definition at line 22 of file WheelEncoder_Backend.cpp.
~AP_WheelEncoder_Backend()
virtual AP_WheelEncoder_Backend::~AP_WheelEncoder_Backend (void) inline virtual
Definition at line 29 of file WheelEncoder_Backend.h.
Member Function Documentation
copy_state_to_frontend()
void AP_WheelEncoder_Backend::copy_state_to_frontend (int32_t distance_count, uint32_t total_count, uint32_t error_count, uint32_t last_reading_ms) protected
Definition at line 48 of file WheelEncoder_Backend.cpp.
Referenced by AP_WheelEncoder_Quadrature::update().
get_pin_a()
int8_t AP_WheelEncoder_Backend::get_pin_a () const protected
Definition at line 30 of file WheelEncoder_Backend.cpp.
Referenced by AP_WheelEncoder_Quadrature::update().
get_pin_b()
int8_t AP_WheelEncoder_Backend::get_pin_b () const protected
Definition at line 39 of file WheelEncoder_Backend.cpp.
Referenced by AP_WheelEncoder_Quadrature::update().
update()
virtual void AP_WheelEncoder_Backend::update () pure virtual
Implemented in AP_WheelEncoder_Quadrature.
Referenced by AP_WheelEncoder::update().
Member Data Documentation
_frontend
AP_WheelEncoder& AP_WheelEncoder_Backend::_frontend protected
Definition at line 43 of file WheelEncoder_Backend.h.
Referenced by get_pin_a(), and get_pin_b().
_state
AP_WheelEncoder::WheelEncoder_State& AP_WheelEncoder_Backend::_state protected
Definition at line 44 of file WheelEncoder_Backend.h.
Referenced by copy_state_to_frontend(), get_pin_a(), and get_pin_b().
The documentation for this class was generated from the following files:
libraries/AP_WheelEncoder/WheelEncoder_Backend.h
libraries/AP_WheelEncoder/WheelEncoder_Backend.cpp