APM:Libraries: AP_MotorsHeli_Swash Class Reference
AP_MotorsHeli_Swash Class Reference
#include <AP_MotorsHeli_Swash.h>
Public Member Functions
AP_MotorsHeli_Swash ()
void configure ()
void calculate_roll_pitch_collective_factors ()
SwashPlateType get_swash_type () const
float get_servo_out (int8_t servo_num, float pitch, float roll, float collective) const
float get_linear_servo_output (float input) const
int16_t get_phase_angle () const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
SwashPlateType _swash_type
CollectiveDirection _collective_direction
float _rollFactor [4]
float _pitchFactor [4]
float _collectiveFactor [4]
int8_t _make_servo_linear
AP_Int8 _swashplate_type
AP_Int8 _swash_coll_dir
AP_Int8 _linear_swash_servo
AP_Int8 enable
AP_Int16 _servo1_pos
AP_Int16 _servo2_pos
AP_Int16 _servo3_pos
AP_Int16 _phase_angle
Detailed Description
Definition at line 25 of file AP_MotorsHeli_Swash.h.
Constructor & Destructor Documentation
AP_MotorsHeli_Swash()
AP_MotorsHeli_Swash::AP_MotorsHeli_Swash () inline
Definition at line 28 of file AP_MotorsHeli_Swash.h.
Member Function Documentation
calculate_roll_pitch_collective_factors()
void AP_MotorsHeli_Swash::calculate_roll_pitch_collective_factors ()
Definition at line 104 of file AP_MotorsHeli_Swash.cpp.
Referenced by AP_MotorsHeli_Single::calculate_scalars(), and AP_MotorsHeli_Dual::calculate_scalars().
configure()
void AP_MotorsHeli_Swash::configure ()
Definition at line 90 of file AP_MotorsHeli_Swash.cpp.
Referenced by AP_MotorsHeli_Single::calculate_scalars(), and AP_MotorsHeli_Dual::calculate_scalars().
get_linear_servo_output()
float AP_MotorsHeli_Swash::get_linear_servo_output (float input) const
Definition at line 216 of file AP_MotorsHeli_Swash.cpp.
Referenced by get_servo_out().
get_phase_angle()
int16_t AP_MotorsHeli_Swash::get_phase_angle () const inline
Definition at line 49 of file AP_MotorsHeli_Swash.h.
Referenced by AP_MotorsHeli_Dual::parameter_check(), and AP_MotorsHeli_Single::parameter_check().
get_servo_out()
float AP_MotorsHeli_Swash::get_servo_out (int8_t servo_num, float pitch, float roll, float collective) const
Definition at line 193 of file AP_MotorsHeli_Swash.cpp.
Referenced by AP_MotorsHeli_Single::move_actuators(), and AP_MotorsHeli_Dual::move_actuators().
get_swash_type()
SwashPlateType AP_MotorsHeli_Swash::get_swash_type () const inline
Definition at line 40 of file AP_MotorsHeli_Swash.h.
Referenced by AP_MotorsHeli_Dual::get_motor_mask(), AP_MotorsHeli_Single::get_motor_mask(), AP_MotorsHeli_Dual::init_outputs(), AP_MotorsHeli_Single::init_outputs(), AP_MotorsHeli_Single::move_actuators(), AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Single::output_to_motors(), AP_MotorsHeli_Dual::output_to_motors(), AP_MotorsHeli_Dual::parameter_check(), AP_MotorsHeli_Single::parameter_check(), AP_MotorsHeli_Single::set_update_rate(), and AP_MotorsHeli_Dual::set_update_rate().
Member Data Documentation
_collective_direction
CollectiveDirection AP_MotorsHeli_Swash::_collective_direction private
Definition at line 57 of file AP_MotorsHeli_Swash.h.
Referenced by configure(), and get_servo_out().
_collectiveFactor
float AP_MotorsHeli_Swash::_collectiveFactor[4] private
Definition at line 60 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors(), and get_servo_out().
_linear_swash_servo
AP_Int8 AP_MotorsHeli_Swash::_linear_swash_servo private
Definition at line 66 of file AP_MotorsHeli_Swash.h.
Referenced by configure().
_make_servo_linear
int8_t AP_MotorsHeli_Swash::_make_servo_linear private
Definition at line 61 of file AP_MotorsHeli_Swash.h.
Referenced by configure(), and get_servo_out().
_phase_angle
AP_Int16 AP_MotorsHeli_Swash::_phase_angle private
Definition at line 71 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors(), and get_phase_angle().
_pitchFactor
float AP_MotorsHeli_Swash::_pitchFactor[4] private
Definition at line 59 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors(), and get_servo_out().
_rollFactor
float AP_MotorsHeli_Swash::_rollFactor[4] private
Definition at line 58 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors(), and get_servo_out().
_servo1_pos
AP_Int16 AP_MotorsHeli_Swash::_servo1_pos private
Definition at line 68 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors().
_servo2_pos
AP_Int16 AP_MotorsHeli_Swash::_servo2_pos private
Definition at line 69 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors().
_servo3_pos
AP_Int16 AP_MotorsHeli_Swash::_servo3_pos private
Definition at line 70 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors().
_swash_coll_dir
AP_Int8 AP_MotorsHeli_Swash::_swash_coll_dir private
Definition at line 65 of file AP_MotorsHeli_Swash.h.
Referenced by configure().
_swash_type
SwashPlateType AP_MotorsHeli_Swash::_swash_type private
Definition at line 56 of file AP_MotorsHeli_Swash.h.
Referenced by calculate_roll_pitch_collective_factors(), configure(), get_servo_out(), and get_swash_type().
_swashplate_type
AP_Int8 AP_MotorsHeli_Swash::_swashplate_type private
Definition at line 64 of file AP_MotorsHeli_Swash.h.
Referenced by configure().
enable
AP_Int8 AP_MotorsHeli_Swash::enable private
Definition at line 67 of file AP_MotorsHeli_Swash.h.
Referenced by configure().
var_info
const AP_Param::GroupInfo AP_MotorsHeli_Swash::var_info static
Definition at line 52 of file AP_MotorsHeli_Swash.h.
Referenced by AP_MotorsHeli_Swash().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsHeli_Swash.h
libraries/AP_Motors/AP_MotorsHeli_Swash.cpp