APM:Libraries: AP_ToshibaCAN Class Reference
AP_ToshibaCAN Class Reference
#include <AP_ToshibaCAN.h>
Classes
union motor_lock_cmd_t
union motor_reply_data1_t
union motor_request_data_cmd_t
union motor_rotation_cmd_t
struct telemetry_info_t
Public Member Functions
AP_ToshibaCAN ()
~AP_ToshibaCAN ()
AP_ToshibaCAN (const AP_ToshibaCAN &other)=delete
AP_ToshibaCAN & operator= (const AP_ToshibaCAN &)=delete
void init (uint8_t driver_index, bool enable_filters) override
void update ()
void send_esc_telemetry_mavlink (uint8_t mav_chan)
Static Public Member Functions
static AP_ToshibaCAN * get_tcan (uint8_t driver_index)
Private Member Functions
void loop ()
bool write_frame (uavcan::CanFrame &out_frame, uavcan::MonotonicTime timeout)
bool read_frame (uavcan::CanFrame &recv_frame, uavcan::MonotonicTime timeout)
Private Attributes
bool _initialized
char _thread_name [9]
uint8_t _driver_index
uavcan::ICanDriver * _can_driver
const uavcan::CanFrame * _select_frames [uavcan::MaxCanIfaces] { }
HAL_Semaphore _rc_out_sem
uint16_t _scaled_output [TOSHIBACAN_MAX_NUM_ESCS]
uint16_t update_count
uint16_t update_count_buffered
uint16_t update_count_sent
uint8_t send_stage
HAL_Semaphore _telem_sem
struct AP_ToshibaCAN::telemetry_info_t _telemetry [TOSHIBACAN_MAX_NUM_ESCS]
uint32_t _telemetry_req_ms
uint8_t _telemetry_temp_req_counter
uint16_t _esc_present_bitmask
uavcan::CanFrame unlock_frame
uavcan::CanFrame mot_rot_frame1
uavcan::CanFrame mot_rot_frame2
uavcan::CanFrame mot_rot_frame3
Detailed Description
Definition at line 23 of file AP_ToshibaCAN.h.
Constructor & Destructor Documentation
AP_ToshibaCAN() [1/2]
AP_ToshibaCAN::AP_ToshibaCAN ()
~AP_ToshibaCAN()
AP_ToshibaCAN::~AP_ToshibaCAN ()
AP_ToshibaCAN() [2/2]
AP_ToshibaCAN::AP_ToshibaCAN (const AP_ToshibaCAN & other) delete
Member Function Documentation
get_tcan()
static AP_ToshibaCAN* AP_ToshibaCAN::get_tcan (uint8_t driver_index) static
Referenced by SRV_Channels::push(), and GCS_MAVLINK::try_send_message().
init()
void AP_ToshibaCAN::init (uint8_t driver_index, bool enable_filters) override
loop()
void AP_ToshibaCAN::loop () private
operator=()
AP_ToshibaCAN& AP_ToshibaCAN::operator= (const AP_ToshibaCAN &) delete
read_frame()
bool AP_ToshibaCAN::read_frame (uavcan::CanFrame & recv_frame, uavcan::MonotonicTime timeout) private
send_esc_telemetry_mavlink()
void AP_ToshibaCAN::send_esc_telemetry_mavlink (uint8_t mav_chan)
Referenced by GCS_MAVLINK::try_send_message().
update()
void AP_ToshibaCAN::update ()
Referenced by SRV_Channels::push().
write_frame()
bool AP_ToshibaCAN::write_frame (uavcan::CanFrame & out_frame, uavcan::MonotonicTime timeout) private
Member Data Documentation
_can_driver
uavcan::ICanDriver* AP_ToshibaCAN::_can_driver private
Definition at line 58 of file AP_ToshibaCAN.h.
_driver_index
uint8_t AP_ToshibaCAN::_driver_index private
Definition at line 57 of file AP_ToshibaCAN.h.
_esc_present_bitmask
uint16_t AP_ToshibaCAN::_esc_present_bitmask private
Definition at line 82 of file AP_ToshibaCAN.h.
_initialized
bool AP_ToshibaCAN::_initialized private
Definition at line 55 of file AP_ToshibaCAN.h.
_rc_out_sem
HAL_Semaphore AP_ToshibaCAN::_rc_out_sem private
Definition at line 62 of file AP_ToshibaCAN.h.
_scaled_output
uint16_t AP_ToshibaCAN::_scaled_output[TOSHIBACAN_MAX_NUM_ESCS] private
Definition at line 63 of file AP_ToshibaCAN.h.
_select_frames
const uavcan::CanFrame* AP_ToshibaCAN::_select_frames[uavcan::MaxCanIfaces] { } private
Definition at line 59 of file AP_ToshibaCAN.h.
_telem_sem
HAL_Semaphore AP_ToshibaCAN::_telem_sem private
Definition at line 70 of file AP_ToshibaCAN.h.
_telemetry
struct AP_ToshibaCAN::telemetry_info_t AP_ToshibaCAN::_telemetry[TOSHIBACAN_MAX_NUM_ESCS] private
_telemetry_req_ms
uint32_t AP_ToshibaCAN::_telemetry_req_ms private
Definition at line 78 of file AP_ToshibaCAN.h.
_telemetry_temp_req_counter
uint8_t AP_ToshibaCAN::_telemetry_temp_req_counter private
Definition at line 79 of file AP_ToshibaCAN.h.
_thread_name
char AP_ToshibaCAN::_thread_name[9] private
Definition at line 56 of file AP_ToshibaCAN.h.
mot_rot_frame1
uavcan::CanFrame AP_ToshibaCAN::mot_rot_frame1 private
Definition at line 148 of file AP_ToshibaCAN.h.
mot_rot_frame2
uavcan::CanFrame AP_ToshibaCAN::mot_rot_frame2 private
Definition at line 149 of file AP_ToshibaCAN.h.
mot_rot_frame3
uavcan::CanFrame AP_ToshibaCAN::mot_rot_frame3 private
Definition at line 150 of file AP_ToshibaCAN.h.
send_stage
uint8_t AP_ToshibaCAN::send_stage private
Definition at line 67 of file AP_ToshibaCAN.h.
unlock_frame
uavcan::CanFrame AP_ToshibaCAN::unlock_frame private
Definition at line 147 of file AP_ToshibaCAN.h.
update_count
uint16_t AP_ToshibaCAN::update_count private
Definition at line 64 of file AP_ToshibaCAN.h.
update_count_buffered
uint16_t AP_ToshibaCAN::update_count_buffered private
Definition at line 65 of file AP_ToshibaCAN.h.
update_count_sent
uint16_t AP_ToshibaCAN::update_count_sent private
Definition at line 66 of file AP_ToshibaCAN.h.
The documentation for this class was generated from the following file:
libraries/AP_ToshibaCAN/AP_ToshibaCAN.h