APM:Libraries: SITL::Vicon Class Reference
SITL::Vicon Class Reference
#include <SIM_Vicon.h>
Classes
struct obs_elements
Public Member Functions
Vicon ()
void update (const Location &loc, const Vector3f &position, const Quaternion &attitude)
int fd ()
Private Member Functions
void update_vicon_position_estimate (const Location &loc, const Vector3f &position, const Quaternion &attitude)
void maybe_send_heartbeat ()
bool init_sitl_pointer ()
Private Attributes
SITL * _sitl
const uint8_t system_id = 17
const uint8_t component_id = 18
const mavlink_channel_t mavlink_ch = (mavlink_channel_t)(MAVLINK_COMM_0+5)
int fd_their_end
int fd_my_end
uint64_t last_observation_usec
uint64_t time_send_us
uint64_t time_offset_us
mavlink_message_t obs_msg
uint32_t last_heartbeat_ms
Detailed Description
Definition at line 29 of file SIM_Vicon.h.
Constructor & Destructor Documentation
Vicon()
Vicon::Vicon ()
Definition at line 29 of file SIM_Vicon.cpp.
Member Function Documentation
fd()
int SITL::Vicon::fd () inline
Definition at line 39 of file SIM_Vicon.h.
Referenced by HALSITL::SITL_State::sim_fd().
init_sitl_pointer()
bool Vicon::init_sitl_pointer () private
Definition at line 125 of file SIM_Vicon.cpp.
Referenced by update().
maybe_send_heartbeat()
void Vicon::maybe_send_heartbeat () private
Definition at line 51 of file SIM_Vicon.cpp.
Referenced by update().
update()
void Vicon::update (const Location & loc, const Vector3f & position, const Quaternion & attitude)
Definition at line 139 of file SIM_Vicon.cpp.
Referenced by HALSITL::SITL_State::_fdm_input_local().
update_vicon_position_estimate()
void Vicon::update_vicon_position_estimate (const Location & loc, const Vector3f & position, const Quaternion & attitude) private
Definition at line 72 of file SIM_Vicon.cpp.
Referenced by update().
Member Data Documentation
_sitl
SITL* SITL::Vicon::_sitl private
Definition at line 43 of file SIM_Vicon.h.
Referenced by init_sitl_pointer().
component_id
const uint8_t SITL::Vicon::component_id = 18 private
Definition at line 47 of file SIM_Vicon.h.
Referenced by maybe_send_heartbeat(), and update_vicon_position_estimate().
fd_my_end
int SITL::Vicon::fd_my_end private
Definition at line 53 of file SIM_Vicon.h.
Referenced by update_vicon_position_estimate(), and Vicon().
fd_their_end
int SITL::Vicon::fd_their_end private
Definition at line 52 of file SIM_Vicon.h.
Referenced by fd(), and Vicon().
last_heartbeat_ms
uint32_t SITL::Vicon::last_heartbeat_ms private
Definition at line 71 of file SIM_Vicon.h.
Referenced by maybe_send_heartbeat().
last_observation_usec
uint64_t SITL::Vicon::last_observation_usec private
Definition at line 55 of file SIM_Vicon.h.
Referenced by update_vicon_position_estimate().
mavlink_ch
const mavlink_channel_t SITL::Vicon::mavlink_ch = (mavlink_channel_t)(MAVLINK_COMM_0+5) private
Definition at line 50 of file SIM_Vicon.h.
Referenced by update_vicon_position_estimate(), and Vicon().
obs_msg
mavlink_message_t SITL::Vicon::obs_msg private
Definition at line 58 of file SIM_Vicon.h.
Referenced by update_vicon_position_estimate().
system_id
const uint8_t SITL::Vicon::system_id = 17 private
Definition at line 46 of file SIM_Vicon.h.
Referenced by maybe_send_heartbeat(), and update_vicon_position_estimate().
time_offset_us
uint64_t SITL::Vicon::time_offset_us private
Definition at line 57 of file SIM_Vicon.h.
Referenced by update_vicon_position_estimate().
time_send_us
uint64_t SITL::Vicon::time_send_us private
Definition at line 56 of file SIM_Vicon.h.
Referenced by update_vicon_position_estimate().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Vicon.h
libraries/SITL/SIM_Vicon.cpp