APM:Libraries: AP_HAL::UARTDriver Class Reference
AP_HAL::UARTDriver Class Reference abstract
#include <UARTDriver.h>
Public Types
enum { OPTION_RXINV =(1U<<0), OPTION_TXINV =(1U<<1), OPTION_HDPLEX =(1U<<2), OPTION_SWAP =(1U<<3) }
enum flow_control { FLOW_CONTROL_DISABLE =0, FLOW_CONTROL_ENABLE =1, FLOW_CONTROL_AUTO =2 }
Public Member Functions
UARTDriver ()
virtual void begin (uint32_t baud)=0
virtual void begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace)=0
virtual void end ()=0
virtual void flush ()=0
virtual bool is_initialized ()=0
virtual void set_blocking_writes (bool blocking)=0
virtual bool tx_pending ()=0
virtual bool lock_port (uint32_t write_key, uint32_t read_key)
virtual size_t write_locked (const uint8_t *buffer, size_t size, uint32_t key)
virtual int16_t read_locked (uint32_t key)
virtual bool set_options (uint8_t options)
virtual void set_flow_control (enum flow_control flow_control_setting)
virtual enum flow_control get_flow_control (void)
virtual void configure_parity (uint8_t v)
virtual void set_stop_bits (int n)
virtual bool set_unbuffered_writes (bool on)
virtual bool wait_timeout (uint16_t n, uint32_t timeout_ms)
virtual void _timer_tick (void)
virtual uint64_t receive_time_constraint_us (uint16_t nbytes)
virtual uint32_t bw_in_kilobytes_per_second () const
Public Member Functions inherited from AP_HAL::BetterStream
virtual void printf (const char *,...) FMT_PRINTF(2
virtual void virtual void vprintf (const char *, va_list)
void print (const char *str)
void println (const char *str)
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
virtual uint32_t available ()=0
virtual int16_t read ()=0
virtual uint32_t txspace ()=0
Detailed Description
Definition at line 9 of file UARTDriver.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OPTION_RXINV
OPTION_TXINV
OPTION_HDPLEX
OPTION_SWAP
Definition at line 54 of file UARTDriver.h.
flow_control
enum AP_HAL::UARTDriver::flow_control
Enumerator
FLOW_CONTROL_DISABLE
FLOW_CONTROL_ENABLE
FLOW_CONTROL_AUTO
Definition at line 61 of file UARTDriver.h.
Constructor & Destructor Documentation
UARTDriver()
AP_HAL::UARTDriver::UARTDriver () inline
Definition at line 11 of file UARTDriver.h.
Member Function Documentation
_timer_tick()
virtual void AP_HAL::UARTDriver::_timer_tick (void) inline virtual
Reimplemented in HALSITL::UARTDriver, ChibiOS::UARTDriver, Linux::UARTDriver, and Linux::SPIUARTDriver.
Definition at line 86 of file UARTDriver.h.
Referenced by HALSITL::Scheduler::_run_io_procs(), and Linux::Scheduler::_run_uarts().
begin() [1/2]
virtual void AP_HAL::UARTDriver::begin (uint32_t baud) pure virtual
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_Beacon_Marvelmind::AP_Beacon_Marvelmind(), AP_Beacon_Pozyx::AP_Beacon_Pozyx(), AP_Proximity_LightWareSF40C::AP_Proximity_LightWareSF40C(), AP_Proximity_RPLidarA2::AP_Proximity_RPLidarA2(), AP_Proximity_TeraRangerTower::AP_Proximity_TeraRangerTower(), AP_Proximity_TeraRangerTowerEvo::AP_Proximity_TeraRangerTowerEvo(), AP_RangeFinder_Benewake::AP_RangeFinder_Benewake(), AP_RangeFinder_BLPing::AP_RangeFinder_BLPing(), AP_RangeFinder_LeddarOne::AP_RangeFinder_LeddarOne(), AP_RangeFinder_LightWareSerial::AP_RangeFinder_LightWareSerial(), AP_RangeFinder_MaxsonarSerialLV::AP_RangeFinder_MaxsonarSerialLV(), AP_RangeFinder_NMEA::AP_RangeFinder_NMEA(), AP_RangeFinder_uLanding::AP_RangeFinder_uLanding(), AP_RangeFinder_Wasp::AP_RangeFinder_Wasp(), AP_GPS::detect_instance(), GCS_MAVLINK::handle_serial_control(), AP_OpticalFlow_CXOF::init(), AP_WindVane_NMEA::init(), AP_DEVO_Telem::init(), AP_SerialManager::init(), AP_SerialManager::init_console(), main_loop(), HAL_Linux::run(), HAL_Empty::run(), HAL_SITL::run(), setup(), setup_uart(), GCS_MAVLINK::setup_uart(), AP_Frsky_Telem::tick(), and AP_RangeFinder_Wasp::update().
begin() [2/2]
virtual void AP_HAL::UARTDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) pure virtual
Extended port open method
Allows for both opening with specified buffer sizes, and re-opening to adjust a subset of the port's settings.
Note
Buffer sizes greater than ::_max_buffer_size will be rounded down.
Parameters
baud Selects the speed that the port will be configured to. If zero, the port speed is left unchanged.
rxSpace Sets the receive buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_rx_buffer_size if it is currently closed.
txSpace Sets the transmit buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_tx_buffer_size if it is currently closed.
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, Linux::SPIUARTDriver, and Empty::UARTDriver.
bw_in_kilobytes_per_second()
virtual uint32_t AP_HAL::UARTDriver::bw_in_kilobytes_per_second () const inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 103 of file UARTDriver.h.
Referenced by GCS_MAVLINK::queued_param_send().
configure_parity()
virtual void AP_HAL::UARTDriver::configure_parity (uint8_t v) inline virtual
Reimplemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, and Linux::UARTDriver.
Definition at line 67 of file UARTDriver.h.
Referenced by AP_SerialManager::init().
end()
virtual void AP_HAL::UARTDriver::end () pure virtual
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by AP_RangeFinder_Wasp::update().
flush()
virtual void AP_HAL::UARTDriver::flush () pure virtual
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, and Empty::UARTDriver.
get_flow_control()
virtual enum flow_control AP_HAL::UARTDriver::get_flow_control (void) inline virtual
Reimplemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, and Linux::UARTDriver.
Definition at line 65 of file UARTDriver.h.
Referenced by GCS_MAVLINK::have_flow_control(), and GCS_MAVLINK::setup_uart().
is_initialized()
virtual bool AP_HAL::UARTDriver::is_initialized () pure virtual
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by loop().
lock_port()
virtual bool AP_HAL::UARTDriver::lock_port (uint32_t write_key, uint32_t read_key) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 42 of file UARTDriver.h.
read_locked()
virtual int16_t AP_HAL::UARTDriver::read_locked (uint32_t key) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 49 of file UARTDriver.h.
receive_time_constraint_us()
virtual uint64_t AP_HAL::UARTDriver::receive_time_constraint_us (uint16_t nbytes) inline virtual
Reimplemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, and Linux::UARTDriver.
Definition at line 101 of file UARTDriver.h.
Referenced by AP_GPS_Backend::check_new_itow(), GCS_MAVLINK::correct_offboard_timestamp_usec_to_ms(), AP_GPS_Backend::set_uart_timestamp(), GCS_MAVLINK::timesync_receive_timestamp_ns(), and AP_OpticalFlow_CXOF::update().
set_blocking_writes()
virtual void AP_HAL::UARTDriver::set_blocking_writes (bool blocking) pure virtual
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by AP_SerialManager::set_blocking_writes_all(), and setup().
set_flow_control()
virtual void AP_HAL::UARTDriver::set_flow_control (enum flow_control flow_control_setting) inline virtual
Reimplemented in Linux::UARTDriver.
Definition at line 64 of file UARTDriver.h.
Referenced by AP_BoardConfig::board_setup_uart(), AP_GPS::detect_instance(), GCS_MAVLINK::handle_serial_control(), AP_DEVO_Telem::init(), AP_SerialManager::init(), AP_Frsky_Telem::init(), and GCS_MAVLINK::setup_uart().
set_options()
virtual bool AP_HAL::UARTDriver::set_options (uint8_t options) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 52 of file UARTDriver.h.
Referenced by AP_SerialManager::set_options().
set_stop_bits()
virtual void AP_HAL::UARTDriver::set_stop_bits (int n) inline virtual
Reimplemented in ChibiOS::UARTDriver, and HALSITL::UARTDriver.
Definition at line 68 of file UARTDriver.h.
Referenced by AP_SerialManager::init().
set_unbuffered_writes()
virtual bool AP_HAL::UARTDriver::set_unbuffered_writes (bool on) inline virtual
Reimplemented in ChibiOS::UARTDriver, and HALSITL::UARTDriver.
Definition at line 73 of file UARTDriver.h.
Referenced by AP_SerialManager::init().
tx_pending()
virtual bool AP_HAL::UARTDriver::tx_pending () pure virtual
Implemented in ChibiOS::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, and Empty::UARTDriver.
Referenced by AP_RangeFinder_Wasp::get_reading().
wait_timeout()
virtual bool AP_HAL::UARTDriver::wait_timeout (uint16_t n, uint32_t timeout_ms) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 80 of file UARTDriver.h.
write_locked()
virtual size_t AP_HAL::UARTDriver::write_locked (const uint8_t * buffer, size_t size, uint32_t key) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 46 of file UARTDriver.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/UARTDriver.h