APM:Libraries: AP_InertialSensor_Invensense Class Reference
AP_InertialSensor_Invensense Class Reference
#include <AP_InertialSensor_Invensense.h>
Public Types
enum Invensense_Type {
Invensense_MPU6000 =0, Invensense_MPU6500, Invensense_MPU9250, Invensense_ICM20608,
Invensense_ICM20602, Invensense_ICM20601, Invensense_ICM20789, Invensense_ICM20689
}
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09, DEVTYPE_L3G4200D = 0x10, DEVTYPE_ACC_LSM303D = 0x11, DEVTYPE_ACC_BMA180 = 0x12,
DEVTYPE_ACC_MPU6000 = 0x13, DEVTYPE_ACC_MPU9250 = 0x16, DEVTYPE_ACC_IIS328DQ = 0x17, DEVTYPE_ACC_LSM9DS1 = 0x18,
DEVTYPE_GYR_MPU6000 = 0x21, DEVTYPE_GYR_L3GD20 = 0x22, DEVTYPE_GYR_MPU9250 = 0x24, DEVTYPE_GYR_I3G4250D = 0x25,
DEVTYPE_GYR_LSM9DS1 = 0x26, DEVTYPE_INS_ICM20789 = 0x27, DEVTYPE_INS_ICM20689 = 0x28, DEVTYPE_INS_BMI055 = 0x29,
DEVTYPE_SITL = 0x2A, DEVTYPE_INS_BMI088 = 0x2B, DEVTYPE_INS_ICM20948 = 0x2C, DEVTYPE_INS_ICM20648 = 0x2D,
DEVTYPE_INS_ICM20649 = 0x2E, DEVTYPE_INS_ICM20602 = 0x2F, DEVTYPE_INS_ICM20601 = 0x30
}
Public Member Functions
virtual ~AP_InertialSensor_Invensense ()
bool update () override
void accumulate () override
AuxiliaryBus * get_auxiliary_bus () override
void start () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
int16_t get_id () const
float get_clip_limit () const
void notify_fifo_reset (void)
Static Public Member Functions
static AP_InertialSensor_Invensense & from (AP_InertialSensor_Backend &backend)
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum Rotation rotation=ROTATION_NONE)
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation=ROTATION_NONE)
Public Attributes
const uint16_t multiplier_accel = INT16_MAX/(26*GRAVITY_MSS)
Vector3f accel
Vector3f gyro
uint8_t count
LowPassFilterVector3f accel_filter {4000, 188}
LowPassFilterVector3f gyro_filter {8000, 188}
Private Member Functions
AP_InertialSensor_Invensense (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation)
bool _init ()
bool _hardware_init ()
bool _check_whoami ()
void _set_filter_register (void)
void _fifo_reset ()
bool _has_auxiliary_bus ()
void _read_fifo ()
bool _data_ready ()
void _poll_data ()
bool _block_read (uint8_t reg, uint8_t *buf, uint32_t size)
uint8_t _register_read (uint8_t reg)
void _register_write (uint8_t reg, uint8_t val, bool checked=false)
bool _accumulate (uint8_t *samples, uint8_t n_samples)
bool _accumulate_sensor_rate_sampling (uint8_t *samples, uint8_t n_samples)
bool _check_raw_temp (int16_t t2)
Private Attributes
friend AP_Invensense_AuxiliaryBus
friend AP_Invensense_AuxiliaryBusSlave
int16_t _raw_temp
uint8_t _gyro_instance
uint8_t _accel_instance
float temp_sensitivity = 1.0f/340
float temp_zero = 36.53f
float _temp_filtered
float _accel_scale
float _gyro_scale
float _fifo_accel_scale
float _fifo_gyro_scale
LowPassFilter2pFloat _temp_filter
enum Rotation _rotation
AP_HAL::DigitalSource * _drdy_pin
AP_HAL::OwnPtr< AP_HAL::Device > _dev
AP_Invensense_AuxiliaryBus * _auxiliary_bus
enum Invensense_Type _mpu_type
bool _fast_sampling
uint8_t _fifo_downsample_rate
uint16_t _backend_rate_hz
uint8_t _last_stat_user_ctrl
uint8_t * _fifo_buffer
struct {
Vector3f accel
Vector3f gyro
uint8_t count
LowPassFilterVector3f accel_filter {4000, 188}
LowPassFilterVector3f gyro_filter {8000, 188}
} _accum
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sampl_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
void _inc_accel_error_count (uint8_t instance)
void _inc_gyro_error_count (uint8_t instance)
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
uint16_t _gyro_notch_center_freq_hz (void) const
uint16_t _gyro_notch_bandwidth_hz (void) const
float _gyro_notch_attenuation_dB (void) const
uint8_t _gyro_notch_enabled (void) const
void update_gyro (uint8_t instance)
void update_accel (uint8_t instance)
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance)
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel)
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro)
void notify_accel_fifo_reset (uint8_t instance)
void notify_gyro_fifo_reset (uint8_t instance)
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore_Recursive _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz [INS_MAX_INSTANCES]
uint16_t _last_gyro_filter_hz [INS_MAX_INSTANCES]
uint16_t _last_notch_center_freq_hz [INS_MAX_INSTANCES]
uint16_t _last_notch_bandwidth_hz [INS_MAX_INSTANCES]
float _last_notch_attenuation_dB [INS_MAX_INSTANCES]
Detailed Description
Definition at line 28 of file AP_InertialSensor_Invensense.h.
Member Enumeration Documentation
Invensense_Type
enum AP_InertialSensor_Invensense::Invensense_Type
Enumerator
Invensense_MPU6000
Invensense_MPU6500
Invensense_MPU9250
Invensense_ICM20608
Invensense_ICM20602
Invensense_ICM20601
Invensense_ICM20789
Invensense_ICM20689
Definition at line 59 of file AP_InertialSensor_Invensense.h.
Constructor & Destructor Documentation
~AP_InertialSensor_Invensense()
AP_InertialSensor_Invensense::~AP_InertialSensor_Invensense () virtual
Definition at line 80 of file AP_InertialSensor_Invensense.cpp.
AP_InertialSensor_Invensense()
AP_InertialSensor_Invensense::AP_InertialSensor_Invensense (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation) private
Definition at line 70 of file AP_InertialSensor_Invensense.cpp.
Referenced by probe().
Member Function Documentation
_accumulate()
bool AP_InertialSensor_Invensense::_accumulate (uint8_t * samples, uint8_t n_samples) private
Definition at line 413 of file AP_InertialSensor_Invensense.cpp.
Referenced by _read_fifo().
_accumulate_sensor_rate_sampling()
bool AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling (uint8_t * samples, uint8_t n_samples) private
Definition at line 461 of file AP_InertialSensor_Invensense.cpp.
Referenced by _read_fifo().
_block_read()
bool AP_InertialSensor_Invensense::_block_read (uint8_t reg, uint8_t * buf, uint32_t size) private
Definition at line 642 of file AP_InertialSensor_Invensense.cpp.
Referenced by _check_raw_temp(), and _read_fifo().
_check_raw_temp()
bool AP_InertialSensor_Invensense::_check_raw_temp (int16_t t2) private
Definition at line 629 of file AP_InertialSensor_Invensense.cpp.
Referenced by _accumulate(), and _accumulate_sensor_rate_sampling().
_check_whoami()
bool AP_InertialSensor_Invensense::_check_whoami (void) private
Definition at line 734 of file AP_InertialSensor_Invensense.cpp.
Referenced by _hardware_init().
_data_ready()
bool AP_InertialSensor_Invensense::_data_ready () private
Definition at line 396 of file AP_InertialSensor_Invensense.cpp.
Referenced by _hardware_init().
_fifo_reset()
void AP_InertialSensor_Invensense::_fifo_reset () private
Definition at line 150 of file AP_InertialSensor_Invensense.cpp.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), _read_fifo(), and start().
_hardware_init()
bool AP_InertialSensor_Invensense::_hardware_init (void) private
Definition at line 770 of file AP_InertialSensor_Invensense.cpp.
Referenced by _init().
_has_auxiliary_bus()
bool AP_InertialSensor_Invensense::_has_auxiliary_bus () private
Definition at line 170 of file AP_InertialSensor_Invensense.cpp.
Referenced by get_auxiliary_bus().
_init()
bool AP_InertialSensor_Invensense::_init (void) private
Definition at line 138 of file AP_InertialSensor_Invensense.cpp.
Referenced by probe().
_poll_data()
void AP_InertialSensor_Invensense::_poll_data () private
Definition at line 408 of file AP_InertialSensor_Invensense.cpp.
Referenced by start().
_read_fifo()
void AP_InertialSensor_Invensense::_read_fifo () private
Definition at line 535 of file AP_InertialSensor_Invensense.cpp.
Referenced by _poll_data().
_register_read()
uint8_t AP_InertialSensor_Invensense::_register_read (uint8_t reg) private
Definition at line 648 of file AP_InertialSensor_Invensense.cpp.
Referenced by _check_whoami(), _data_ready(), _hardware_init(), and start().
_register_write()
void AP_InertialSensor_Invensense::_register_write (uint8_t reg, uint8_t val, bool checked = false) private
Definition at line 655 of file AP_InertialSensor_Invensense.cpp.
Referenced by _fifo_reset(), _hardware_init(), _set_filter_register(), AP_Invensense_AuxiliaryBusSlave::_set_passthrough(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), and start().
_set_filter_register()
void AP_InertialSensor_Invensense::_set_filter_register (void) private
Definition at line 663 of file AP_InertialSensor_Invensense.cpp.
Referenced by start().
accumulate()
void AP_InertialSensor_Invensense::accumulate (void) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 372 of file AP_InertialSensor_Invensense.cpp.
from()
static AP_InertialSensor_Invensense& AP_InertialSensor_Invensense::from (AP_InertialSensor_Backend & backend) inline static
Definition at line 36 of file AP_InertialSensor_Invensense.h.
Referenced by AP_Invensense_AuxiliaryBus::_configure_slaves(), AP_Invensense_AuxiliaryBusSlave::_set_passthrough(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), AP_Invensense_AuxiliaryBusSlave::read(), and AP_Invensense_AuxiliaryBus::register_periodic_callback().
get_auxiliary_bus()
AuxiliaryBus * AP_InertialSensor_Invensense::get_auxiliary_bus () override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 377 of file AP_InertialSensor_Invensense.cpp.
probe() [1/2]
AP_InertialSensor_Backend * AP_InertialSensor_Invensense::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum Rotation rotation = ROTATION_NONE) static
Definition at line 88 of file AP_InertialSensor_Invensense.cpp.
Referenced by AP_InertialSensor::detect_backends().
probe() [2/2]
AP_InertialSensor_Backend * AP_InertialSensor_Invensense::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation = ROTATION_NONE) static
Definition at line 111 of file AP_InertialSensor_Invensense.cpp.
start()
void AP_InertialSensor_Invensense::start (void) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 175 of file AP_InertialSensor_Invensense.cpp.
update()
bool AP_InertialSensor_Invensense::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 359 of file AP_InertialSensor_Invensense.cpp.
Member Data Documentation
_accel_instance
uint8_t AP_InertialSensor_Invensense::_accel_instance private
Definition at line 113 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), _fifo_reset(), _read_fifo(), _set_filter_register(), start(), and update().
_accel_scale
float AP_InertialSensor_Invensense::_accel_scale private
Definition at line 119 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), and start().
_accum
struct { ... } AP_InertialSensor_Invensense::_accum
Referenced by _accumulate_sensor_rate_sampling().
_auxiliary_bus
AP_Invensense_AuxiliaryBus* AP_InertialSensor_Invensense::_auxiliary_bus private
Definition at line 130 of file AP_InertialSensor_Invensense.h.
Referenced by get_auxiliary_bus(), and ~AP_InertialSensor_Invensense().
_backend_rate_hz
uint16_t AP_InertialSensor_Invensense::_backend_rate_hz private
Definition at line 142 of file AP_InertialSensor_Invensense.h.
Referenced by _set_filter_register(), and start().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_Invensense::_dev private
Definition at line 129 of file AP_InertialSensor_Invensense.h.
Referenced by _block_read(), _fifo_reset(), _hardware_init(), _has_auxiliary_bus(), _read_fifo(), _register_read(), _register_write(), _set_filter_register(), get_auxiliary_bus(), and start().
_drdy_pin
AP_HAL::DigitalSource* AP_InertialSensor_Invensense::_drdy_pin private
Definition at line 128 of file AP_InertialSensor_Invensense.h.
Referenced by _data_ready(), and _init().
_fast_sampling
bool AP_InertialSensor_Invensense::_fast_sampling private
Definition at line 136 of file AP_InertialSensor_Invensense.h.
Referenced by _read_fifo(), _set_filter_register(), and start().
_fifo_accel_scale
float AP_InertialSensor_Invensense::_fifo_accel_scale private
Definition at line 122 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate_sensor_rate_sampling(), and start().
_fifo_buffer
uint8_t* AP_InertialSensor_Invensense::_fifo_buffer private
Definition at line 148 of file AP_InertialSensor_Invensense.h.
Referenced by _read_fifo(), start(), and ~AP_InertialSensor_Invensense().
_fifo_downsample_rate
uint8_t AP_InertialSensor_Invensense::_fifo_downsample_rate private
Definition at line 139 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate_sensor_rate_sampling(), _set_filter_register(), and start().
_fifo_gyro_scale
float AP_InertialSensor_Invensense::_fifo_gyro_scale private
Definition at line 123 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate_sensor_rate_sampling(), and start().
_gyro_instance
uint8_t AP_InertialSensor_Invensense::_gyro_instance private
Definition at line 112 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), _fifo_reset(), _read_fifo(), _set_filter_register(), start(), and update().
_gyro_scale
float AP_InertialSensor_Invensense::_gyro_scale private
Definition at line 120 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), and start().
_last_stat_user_ctrl
uint8_t AP_InertialSensor_Invensense::_last_stat_user_ctrl private
Definition at line 145 of file AP_InertialSensor_Invensense.h.
Referenced by _fifo_reset(), and _hardware_init().
_mpu_type
enum Invensense_Type AP_InertialSensor_Invensense::_mpu_type private
Definition at line 133 of file AP_InertialSensor_Invensense.h.
Referenced by _check_whoami(), _hardware_init(), _set_filter_register(), probe(), and start().
_raw_temp
int16_t AP_InertialSensor_Invensense::_raw_temp private
Definition at line 109 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), and _check_raw_temp().
_rotation
enum Rotation AP_InertialSensor_Invensense::_rotation private
Definition at line 126 of file AP_InertialSensor_Invensense.h.
Referenced by start().
_temp_filter
LowPassFilter2pFloat AP_InertialSensor_Invensense::_temp_filter private
Definition at line 124 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), and _accumulate_sensor_rate_sampling().
_temp_filtered
float AP_InertialSensor_Invensense::_temp_filtered private
Definition at line 118 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), and update().
accel
Vector3f AP_InertialSensor_Invensense::accel
Definition at line 155 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate().
accel_filter
LowPassFilterVector3f AP_InertialSensor_Invensense::accel_filter {4000, 188}
Definition at line 158 of file AP_InertialSensor_Invensense.h.
AP_Invensense_AuxiliaryBus
friend AP_InertialSensor_Invensense::AP_Invensense_AuxiliaryBus private
Definition at line 30 of file AP_InertialSensor_Invensense.h.
Referenced by get_auxiliary_bus().
AP_Invensense_AuxiliaryBusSlave
friend AP_InertialSensor_Invensense::AP_Invensense_AuxiliaryBusSlave private
Definition at line 31 of file AP_InertialSensor_Invensense.h.
count
uint8_t AP_InertialSensor_Invensense::count
Definition at line 157 of file AP_InertialSensor_Invensense.h.
gyro
Vector3f AP_InertialSensor_Invensense::gyro
Definition at line 156 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate().
gyro_filter
LowPassFilterVector3f AP_InertialSensor_Invensense::gyro_filter {8000, 188}
Definition at line 159 of file AP_InertialSensor_Invensense.h.
multiplier_accel
const uint16_t AP_InertialSensor_Invensense::multiplier_accel = INT16_MAX/(26*GRAVITY_MSS)
Definition at line 73 of file AP_InertialSensor_Invensense.h.
Referenced by start().
temp_sensitivity
float AP_InertialSensor_Invensense::temp_sensitivity = 1.0f/340 private
Definition at line 115 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), and start().
temp_zero
float AP_InertialSensor_Invensense::temp_zero = 36.53f private
Definition at line 116 of file AP_InertialSensor_Invensense.h.
Referenced by _accumulate(), _accumulate_sensor_rate_sampling(), and start().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp