APM:Libraries: RSCThrCrvParam Class Reference
RSCThrCrvParam Class Reference
#include <AP_MotorsHeli_RSC.h>
Public Member Functions
RSCThrCrvParam (void)
void set_thrcrv_enable (int8_t setenable)
float * get_thrcrv ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 enable
AP_Int16 thrcrv [5]
Detailed Description
Definition at line 156 of file AP_MotorsHeli_RSC.h.
Constructor & Destructor Documentation
RSCThrCrvParam()
RSCThrCrvParam::RSCThrCrvParam (void)
Definition at line 127 of file AP_MotorsHeli_RSC.cpp.
Member Function Documentation
get_thrcrv()
float* RSCThrCrvParam::get_thrcrv () inline
Definition at line 163 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_thrcrv_enable()
void RSCThrCrvParam::set_thrcrv_enable (int8_t setenable) inline
Definition at line 162 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::enable_rsc_parameters().
Member Data Documentation
enable
AP_Int8 RSCThrCrvParam::enable private
Definition at line 172 of file AP_MotorsHeli_RSC.h.
Referenced by set_thrcrv_enable().
thrcrv
AP_Int16 RSCThrCrvParam::thrcrv[5] private
Definition at line 173 of file AP_MotorsHeli_RSC.h.
Referenced by get_thrcrv().
var_info
const AP_Param::GroupInfo RSCThrCrvParam::var_info static
Definition at line 160 of file AP_MotorsHeli_RSC.h.
Referenced by RSCThrCrvParam().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp