APM:Libraries: ChibiOS::Storage Class Reference
ChibiOS::Storage Class Reference
#include <Storage.h>
Public Member Functions
void init () override
void read_block (void *dst, uint16_t src, size_t n) override
void write_block (uint16_t dst, const void *src, size_t n) override
void _timer_tick (void) override
bool healthy (void) override
Private Member Functions
void _storage_create (void)
void _storage_open (void)
void _save_backup (void)
void _mark_dirty (uint16_t loc, uint16_t length)
uint8_t _buffer [CH_STORAGE_SIZE] __attribute__ ((aligned(4)))
bool _flash_write_data (uint8_t sector, uint32_t offset, const uint8_t *data, uint16_t length)
bool _flash_read_data (uint8_t sector, uint32_t offset, uint8_t *data, uint16_t length)
bool _flash_erase_sector (uint8_t sector)
bool _flash_erase_ok (void)
void _flash_load (void)
void _flash_write (uint16_t line)
Private Attributes
volatile bool _initialised
Bitmask< CH_STORAGE_NUM_LINES > _dirty_mask
uint8_t _flash_page
bool _flash_failed
uint32_t _last_re_init_ms
uint32_t _last_empty_ms
Detailed Description
Definition at line 37 of file Storage.h.
Member Function Documentation
__attribute__()
uint8_t _buffer [CH_STORAGE_SIZE] ChibiOS::Storage::__attribute__ ((aligned(4))) private
_flash_erase_ok()
bool Storage::_flash_erase_ok (void) private
Definition at line 306 of file Storage.cpp.
Referenced by _flash_write_data().
_flash_erase_sector()
bool Storage::_flash_erase_sector (uint8_t sector) private
Definition at line 292 of file Storage.cpp.
_flash_load()
void Storage::_flash_load (void) private
Definition at line 220 of file Storage.cpp.
Referenced by _storage_open().
_flash_read_data()
bool Storage::_flash_read_data (uint8_t sector, uint32_t offset, uint8_t * data, uint16_t length) private
Definition at line 281 of file Storage.cpp.
_flash_write()
void Storage::_flash_write (uint16_t line) private
Definition at line 238 of file Storage.cpp.
Referenced by _timer_tick().
_flash_write_data()
bool Storage::_flash_write_data (uint8_t sector, uint32_t offset, const uint8_t * data, uint16_t length) private
Definition at line 251 of file Storage.cpp.
_mark_dirty()
void Storage::_mark_dirty (uint16_t loc, uint16_t length) private
Definition at line 131 of file Storage.cpp.
Referenced by write_block().
_save_backup()
void Storage::_save_backup (void) private
Definition at line 111 of file Storage.cpp.
Referenced by _storage_open().
_storage_create()
void ChibiOS::Storage::_storage_create (void) private
_storage_open()
void Storage::_storage_open (void) private
Definition at line 44 of file Storage.cpp.
Referenced by read_block(), and write_block().
_timer_tick()
void Storage::_timer_tick (void) override virtual
Reimplemented from AP_HAL::Storage.
Definition at line 162 of file Storage.cpp.
healthy()
bool Storage::healthy (void) override virtual
Reimplemented from AP_HAL::Storage.
Definition at line 316 of file Storage.cpp.
init()
void ChibiOS::Storage::init (void) inline override virtual
Implements AP_HAL::Storage.
Definition at line 39 of file Storage.h.
read_block()
void Storage::read_block (void * dst, uint16_t src, size_t n) override virtual
Implements AP_HAL::Storage.
Definition at line 141 of file Storage.cpp.
write_block()
void Storage::write_block (uint16_t dst, const void * src, size_t n) override virtual
Implements AP_HAL::Storage.
Definition at line 150 of file Storage.cpp.
Member Data Documentation
_dirty_mask
Bitmask<CH_STORAGE_NUM_LINES> ChibiOS::Storage::_dirty_mask private
Definition at line 53 of file Storage.h.
Referenced by _flash_write(), _mark_dirty(), _storage_open(), and _timer_tick().
_flash_failed
bool ChibiOS::Storage::_flash_failed private
Definition at line 60 of file Storage.h.
_flash_page
uint8_t ChibiOS::Storage::_flash_page private
Definition at line 59 of file Storage.h.
Referenced by _flash_erase_sector(), _flash_load(), _flash_read_data(), and _flash_write_data().
_initialised
volatile bool ChibiOS::Storage::_initialised private
Definition at line 47 of file Storage.h.
Referenced by _storage_open(), _timer_tick(), and healthy().
_last_empty_ms
uint32_t ChibiOS::Storage::_last_empty_ms private
Definition at line 62 of file Storage.h.
Referenced by _timer_tick(), and healthy().
_last_re_init_ms
uint32_t ChibiOS::Storage::_last_re_init_ms private
Definition at line 61 of file Storage.h.
Referenced by _flash_write_data().
The documentation for this class was generated from the following files:
libraries/AP_HAL_ChibiOS/Storage.h
libraries/AP_HAL_ChibiOS/Storage.cpp