APM:Libraries: AP_Compass_HIL Class Reference
AP_Compass_HIL Class Reference
#include <AP_Compass_HIL.h>
Public Member Functions
AP_Compass_HIL ()
void read (void) override
bool init (void)
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * detect ()
Private Attributes
uint8_t _compass_instance [HIL_NUM_COMPASSES]
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01, DEVTYPE_HMC5883 = 0x07, DEVTYPE_LSM303D = 0x02, DEVTYPE_AK8963 = 0x04,
DEVTYPE_BMM150 = 0x05, DEVTYPE_LSM9DS1 = 0x06, DEVTYPE_LIS3MDL = 0x08, DEVTYPE_AK09916 = 0x09,
DEVTYPE_IST8310 = 0x0A, DEVTYPE_ICM20948 = 0x0B, DEVTYPE_MMC3416 = 0x0C, DEVTYPE_QMC5883L = 0x0D,
DEVTYPE_MAG3110 = 0x0E, DEVTYPE_SITL = 0x0F, DEVTYPE_IST8308 = 0x10, DEVTYPE_RM3100 = 0x11
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
HAL_Semaphore_Recursive _sem
Detailed Description
Definition at line 7 of file AP_Compass_HIL.h.
Constructor & Destructor Documentation
AP_Compass_HIL()
AP_Compass_HIL::AP_Compass_HIL ()
Definition at line 28 of file AP_Compass_HIL.cpp.
Referenced by detect().
Member Function Documentation
detect()
AP_Compass_Backend * AP_Compass_HIL::detect () static
Definition at line 35 of file AP_Compass_HIL.cpp.
Referenced by Compass::_detect_backends().
init()
bool AP_Compass_HIL::init (void)
Definition at line 49 of file AP_Compass_HIL.cpp.
Referenced by detect().
read()
void AP_Compass_HIL::read (void) override virtual
Implements AP_Compass_Backend.
Definition at line 58 of file AP_Compass_HIL.cpp.
Member Data Documentation
_compass_instance
uint8_t AP_Compass_HIL::_compass_instance[HIL_NUM_COMPASSES] private
Definition at line 18 of file AP_Compass_HIL.h.
Referenced by AP_Compass_HIL(), init(), and read().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_HIL.h
libraries/AP_Compass/AP_Compass_HIL.cpp