APM:Libraries: AnalogSource_Navio2 Class Reference
AnalogSource_Navio2 Class Reference
#include <AnalogIn_Navio2.h>
Public Member Functions
AnalogSource_Navio2 (uint8_t pin)
float read_average () override
float read_latest () override
void set_pin (uint8_t p) override
void set_stop_pin (uint8_t p) override
void set_settle_time (uint16_t settle_time_ms) override
float voltage_average () override
float voltage_latest () override
float voltage_average_ratiometric () override
Private Member Functions
void set_channel (uint8_t pin)
Private Attributes
uint8_t _pin
int _fd = -1
float _value = 0.0f
Friends
class AnalogIn_Navio2
Detailed Description
Definition at line 9 of file AnalogIn_Navio2.h.
Constructor & Destructor Documentation
AnalogSource_Navio2()
AnalogSource_Navio2::AnalogSource_Navio2 (uint8_t pin)
Definition at line 39 of file AnalogIn_Navio2.cpp.
Member Function Documentation
read_average()
float AnalogSource_Navio2::read_average () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 56 of file AnalogIn_Navio2.cpp.
read_latest()
float AnalogSource_Navio2::read_latest () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 61 of file AnalogIn_Navio2.cpp.
Referenced by read_average(), and voltage_latest().
set_channel()
void AnalogSource_Navio2::set_channel (uint8_t pin) private
Definition at line 14 of file AnalogIn_Navio2.cpp.
Referenced by AnalogSource_Navio2(), and set_pin().
set_pin()
void AnalogSource_Navio2::set_pin (uint8_t p) override virtual
Implements AP_HAL::AnalogSource.
Definition at line 45 of file AnalogIn_Navio2.cpp.
set_settle_time()
void AnalogSource_Navio2::set_settle_time (uint16_t settle_time_ms) inline override virtual
Implements AP_HAL::AnalogSource.
Definition at line 17 of file AnalogIn_Navio2.h.
set_stop_pin()
void AnalogSource_Navio2::set_stop_pin (uint8_t p) inline override virtual
Implements AP_HAL::AnalogSource.
Definition at line 16 of file AnalogIn_Navio2.h.
voltage_average()
float AnalogSource_Navio2::voltage_average () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 66 of file AnalogIn_Navio2.cpp.
Referenced by read_latest(), and voltage_average_ratiometric().
voltage_average_ratiometric()
float AnalogSource_Navio2::voltage_average_ratiometric () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 89 of file AnalogIn_Navio2.cpp.
voltage_latest()
float AnalogSource_Navio2::voltage_latest () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 83 of file AnalogIn_Navio2.cpp.
Friends And Related Function Documentation
AnalogIn_Navio2
friend class AnalogIn_Navio2 friend
Definition at line 11 of file AnalogIn_Navio2.h.
Member Data Documentation
_fd
int AnalogSource_Navio2::_fd = -1 private
Definition at line 24 of file AnalogIn_Navio2.h.
Referenced by set_channel(), and voltage_average().
_pin
uint8_t AnalogSource_Navio2::_pin private
Definition at line 23 of file AnalogIn_Navio2.h.
Referenced by set_pin().
_value
float AnalogSource_Navio2::_value = 0.0f private
Definition at line 25 of file AnalogIn_Navio2.h.
Referenced by voltage_average(), and voltage_latest().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/AnalogIn_Navio2.h
libraries/AP_HAL_Linux/AnalogIn_Navio2.cpp