APM:Libraries: OpticalFlow Class Reference
OpticalFlow Class Reference
#include <OpticalFlow.h>
Classes
struct AP_OpticalFlow_Flags
struct OpticalFlow_state
Public Types
enum OpticalFlowType {
OpticalFlowType::NONE = 0, OpticalFlowType::PX4FLOW = 1, OpticalFlowType::PIXART = 2, OpticalFlowType::BEBOP = 3,
OpticalFlowType::CXOF = 4, OpticalFlowType::MAVLINK = 5, OpticalFlowType::UAVCAN = 6, OpticalFlowType::SITL = 10
}
Public Member Functions
OpticalFlow ()
OpticalFlow (const OpticalFlow &other)=delete
OpticalFlow & operator= (const OpticalFlow &)=delete
void init (uint32_t log_bit)
bool enabled () const
bool healthy () const
void update (void)
void handle_msg (const mavlink_message_t *msg)
uint8_t quality () const
const Vector2f & flowRate () const
const Vector2f & bodyRate () const
uint32_t last_update () const
const Vector3f & get_pos_offset (void) const
Static Public Member Functions
static OpticalFlow * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void update_state (const OpticalFlow_state &state)
void Log_Write_Optflow ()
Private Attributes
OpticalFlow_backend * backend
struct OpticalFlow::AP_OpticalFlow_Flags _flags
AP_Int8 _type
AP_Int16 _flowScalerX
AP_Int16 _flowScalerY
AP_Int16 _yawAngle_cd
AP_Vector3f _pos_offset
AP_Int8 _address
struct OpticalFlow_state _state
uint32_t _last_update_ms
uint32_t _log_bit = -1
Static Private Attributes
static OpticalFlow * _singleton
Friends
class OpticalFlow_backend
Detailed Description
Definition at line 29 of file OpticalFlow.h.
Member Enumeration Documentation
OpticalFlowType
enum OpticalFlow::OpticalFlowType strong
Enumerator
NONE
PX4FLOW
PIXART
BEBOP
CXOF
MAVLINK
UAVCAN
SITL
Definition at line 45 of file OpticalFlow.h.
Constructor & Destructor Documentation
OpticalFlow() [1/2]
OpticalFlow::OpticalFlow ()
Definition at line 97 of file OpticalFlow.cpp.
OpticalFlow() [2/2]
OpticalFlow::OpticalFlow (const OpticalFlow & other) delete
Member Function Documentation
bodyRate()
const Vector2f& OpticalFlow::bodyRate () const inline
Definition at line 78 of file OpticalFlow.h.
Referenced by GCS_MAVLINK::send_opticalflow().
enabled()
bool OpticalFlow::enabled (void) const inline
Definition at line 60 of file OpticalFlow.h.
Referenced by handle_msg(), AP_OSD::next_screen(), update(), and AP_OSD::update_current_screen().
flowRate()
const Vector2f& OpticalFlow::flowRate () const inline
Definition at line 75 of file OpticalFlow.h.
Referenced by GCS_MAVLINK::send_opticalflow().
get_pos_offset()
const Vector3f& OpticalFlow::get_pos_offset (void) const inline
Definition at line 90 of file OpticalFlow.h.
Referenced by update_state().
get_singleton()
static OpticalFlow* OpticalFlow::get_singleton (void) inline static
Definition at line 41 of file OpticalFlow.h.
Referenced by AP::opticalflow().
handle_msg()
void OpticalFlow::handle_msg (const mavlink_message_t * msg)
Definition at line 167 of file OpticalFlow.cpp.
Referenced by GCS_MAVLINK::handle_optical_flow().
healthy()
bool OpticalFlow::healthy (void) const inline
Definition at line 63 of file OpticalFlow.h.
Referenced by GCS_MAVLINK::send_opticalflow(), and setup().
init()
void OpticalFlow::init (uint32_t log_bit)
Definition at line 104 of file OpticalFlow.cpp.
Referenced by setup().
last_update()
uint32_t OpticalFlow::last_update () const inline
Definition at line 81 of file OpticalFlow.h.
Log_Write_Optflow()
void OpticalFlow::Log_Write_Optflow () private
Definition at line 193 of file OpticalFlow.cpp.
Referenced by update_state().
operator=()
OpticalFlow& OpticalFlow::operator= (const OpticalFlow &) delete
quality()
uint8_t OpticalFlow::quality () const inline
Definition at line 72 of file OpticalFlow.h.
Referenced by GCS_MAVLINK::send_opticalflow(), and update_state().
update()
void OpticalFlow::update (void)
Definition at line 153 of file OpticalFlow.cpp.
update_state()
void OpticalFlow::update_state (const OpticalFlow_state & state) private
Definition at line 179 of file OpticalFlow.cpp.
Referenced by OpticalFlow_backend::_update_frontend().
Friends And Related Function Documentation
OpticalFlow_backend
friend class OpticalFlow_backend friend
Definition at line 31 of file OpticalFlow.h.
Member Data Documentation
_address
AP_Int8 OpticalFlow::_address private
Definition at line 113 of file OpticalFlow.h.
Referenced by OpticalFlow_backend::get_address().
_flags
struct OpticalFlow::AP_OpticalFlow_Flags OpticalFlow::_flags private
Referenced by healthy(), and update().
_flowScalerX
AP_Int16 OpticalFlow::_flowScalerX private
Definition at line 109 of file OpticalFlow.h.
Referenced by OpticalFlow_backend::_flowScaler().
_flowScalerY
AP_Int16 OpticalFlow::_flowScalerY private
Definition at line 110 of file OpticalFlow.h.
Referenced by OpticalFlow_backend::_flowScaler().
_last_update_ms
uint32_t OpticalFlow::_last_update_ms private
Definition at line 121 of file OpticalFlow.h.
Referenced by last_update(), update(), and update_state().
_log_bit
uint32_t OpticalFlow::_log_bit = -1 private
Definition at line 124 of file OpticalFlow.h.
Referenced by init(), and Log_Write_Optflow().
_pos_offset
AP_Vector3f OpticalFlow::_pos_offset private
Definition at line 112 of file OpticalFlow.h.
Referenced by get_pos_offset().
_singleton
OpticalFlow * OpticalFlow::_singleton static private
Definition at line 99 of file OpticalFlow.h.
Referenced by get_singleton(), and OpticalFlow().
_state
struct OpticalFlow_state OpticalFlow::_state private
Definition at line 119 of file OpticalFlow.h.
Referenced by bodyRate(), flowRate(), Log_Write_Optflow(), quality(), and update_state().
_type
AP_Int8 OpticalFlow::_type private
Definition at line 108 of file OpticalFlow.h.
Referenced by enabled(), and init().
_yawAngle_cd
AP_Int16 OpticalFlow::_yawAngle_cd private
Definition at line 111 of file OpticalFlow.h.
Referenced by OpticalFlow_backend::_yawAngleRad().
backend
OpticalFlow_backend* OpticalFlow::backend private
Definition at line 101 of file OpticalFlow.h.
Referenced by handle_msg(), healthy(), init(), and update().
var_info
const AP_Param::GroupInfo OpticalFlow::var_info static
Definition at line 95 of file OpticalFlow.h.
Referenced by OpticalFlow().
The documentation for this class was generated from the following files:
libraries/AP_OpticalFlow/OpticalFlow.h
libraries/AP_OpticalFlow/OpticalFlow.cpp