APM:Libraries: AP_LoggerTest_AllTypes Class Reference
AP_LoggerTest_AllTypes Class Reference
Public Member Functions
void setup ()
void loop ()
Private Member Functions
void print_mode (AP_HAL::BetterStream *port, uint8_t mode)
void Log_Write_TypeMessages ()
void Log_Write_TypeMessages_Log_Write ()
void flush_logger (AP_Logger &logger)
Private Attributes
AP_Int32 log_bitmask
AP_Logger logger {log_bitmask}
Detailed Description
Definition at line 86 of file AP_Logger_AllTypes.cpp.
Member Function Documentation
flush_logger()
void AP_LoggerTest_AllTypes::flush_logger (AP_Logger & logger) private
Definition at line 103 of file AP_Logger_AllTypes.cpp.
Referenced by Log_Write_TypeMessages(), and Log_Write_TypeMessages_Log_Write().
Log_Write_TypeMessages()
void AP_LoggerTest_AllTypes::Log_Write_TypeMessages () private
Definition at line 117 of file AP_Logger_AllTypes.cpp.
Referenced by setup().
Log_Write_TypeMessages_Log_Write()
void AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write () private
Definition at line 164 of file AP_Logger_AllTypes.cpp.
Referenced by setup().
loop()
void AP_LoggerTest_AllTypes::loop (void) virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 224 of file AP_Logger_AllTypes.cpp.
print_mode()
void AP_LoggerTest_AllTypes::print_mode (AP_HAL::BetterStream * port, uint8_t mode) private
setup()
void AP_LoggerTest_AllTypes::setup (void) virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 206 of file AP_Logger_AllTypes.cpp.
Member Data Documentation
log_bitmask
AP_Int32 AP_LoggerTest_AllTypes::log_bitmask private
Definition at line 93 of file AP_Logger_AllTypes.cpp.
Referenced by setup().
logger
AP_Logger AP_LoggerTest_AllTypes::logger {log_bitmask} private
Definition at line 94 of file AP_Logger_AllTypes.cpp.
Referenced by Log_Write_TypeMessages(), Log_Write_TypeMessages_Log_Write(), and setup().
The documentation for this class was generated from the following file:
libraries/AP_Logger/examples/AP_Logger_AllTypes/AP_Logger_AllTypes.cpp