APM:Libraries: HALSITL::ADCSource Class Reference
HALSITL::ADCSource Class Reference
#include <AnalogIn.h>
Public Member Functions
ADCSource (SITL_State *sitlState, int16_t pin)
float read_average () override
float read_latest () override
void set_pin (uint8_t p) override
float voltage_average () override
float voltage_latest () override
float voltage_average_ratiometric () override
void set_stop_pin (uint8_t pin) override
void set_settle_time (uint16_t settle_time_ms) override
Private Attributes
SITL_State * _sitlState
int16_t _pin
Friends
class HALSITL::AnalogIn
Detailed Description
Definition at line 8 of file AnalogIn.h.
Constructor & Destructor Documentation
ADCSource()
ADCSource::ADCSource (SITL_State * sitlState, int16_t pin)
Definition at line 12 of file AnalogIn.cpp.
Member Function Documentation
read_average()
float ADCSource::read_average () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 17 of file AnalogIn.cpp.
Referenced by voltage_average().
read_latest()
float ADCSource::read_latest () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 29 of file AnalogIn.cpp.
Referenced by read_average(), and voltage_latest().
set_pin()
void ADCSource::set_pin (uint8_t p) override virtual
Implements AP_HAL::AnalogSource.
Definition at line 61 of file AnalogIn.cpp.
set_settle_time()
void HALSITL::ADCSource::set_settle_time (uint16_t settle_time_ms) inline override virtual
Implements AP_HAL::AnalogSource.
Definition at line 24 of file AnalogIn.h.
set_stop_pin()
void HALSITL::ADCSource::set_stop_pin (uint8_t pin) inline override virtual
Implements AP_HAL::AnalogSource.
Definition at line 23 of file AnalogIn.h.
voltage_average()
float ADCSource::voltage_average () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 21 of file AnalogIn.cpp.
Referenced by voltage_average_ratiometric().
voltage_average_ratiometric()
float HALSITL::ADCSource::voltage_average_ratiometric () inline override virtual
Implements AP_HAL::AnalogSource.
Definition at line 20 of file AnalogIn.h.
voltage_latest()
float ADCSource::voltage_latest () override virtual
Implements AP_HAL::AnalogSource.
Definition at line 25 of file AnalogIn.cpp.
Friends And Related Function Documentation
HALSITL::AnalogIn
friend class HALSITL::AnalogIn friend
Definition at line 10 of file AnalogIn.h.
Member Data Documentation
_pin
int16_t HALSITL::ADCSource::_pin private
Definition at line 28 of file AnalogIn.h.
Referenced by read_latest(), and set_pin().
_sitlState
SITL_State* HALSITL::ADCSource::_sitlState private
Definition at line 27 of file AnalogIn.h.
Referenced by read_latest().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/AnalogIn.h
libraries/AP_HAL_SITL/AnalogIn.cpp