APM:Libraries: Display_Backend Class Reference
Display_Backend Class Reference abstract
#include <Display_Backend.h>
Public Member Functions
virtual void hw_update ()=0
virtual void set_pixel (uint16_t x, uint16_t y)=0
virtual void clear_pixel (uint16_t x, uint16_t y)=0
virtual void clear_screen ()=0
Protected Member Functions
virtual ~Display_Backend ()
virtual bool hw_init ()=0
Detailed Description
Definition at line 7 of file Display_Backend.h.
Constructor & Destructor Documentation
~Display_Backend()
virtual Display_Backend::~Display_Backend () inline protected virtual
Definition at line 18 of file Display_Backend.h.
Member Function Documentation
clear_pixel()
virtual void Display_Backend::clear_pixel (uint16_t x, uint16_t y) pure virtual
Implemented in Display_SH1106_I2C, and Display_SSD1306_I2C.
Referenced by Display::draw_char().
clear_screen()
virtual void Display_Backend::clear_screen () pure virtual
Implemented in Display_SH1106_I2C, and Display_SSD1306_I2C.
Referenced by Display::update().
hw_init()
virtual bool Display_Backend::hw_init () protected pure virtual
Implemented in Display_SH1106_I2C, and Display_SSD1306_I2C.
hw_update()
virtual void Display_Backend::hw_update () pure virtual
Implemented in Display_SH1106_I2C, and Display_SSD1306_I2C.
Referenced by Display::init(), and Display::update().
set_pixel()
virtual void Display_Backend::set_pixel (uint16_t x, uint16_t y) pure virtual
Implemented in Display_SH1106_I2C, and Display_SSD1306_I2C.
Referenced by Display::draw_char().
The documentation for this class was generated from the following file:
libraries/AP_Notify/Display_Backend.h