APM:Libraries: AP_SpdHgtControl Class Reference
AP_SpdHgtControl Class Reference abstract
#include <AP_SpdHgtControl.h>
Public Types
enum ControllerType { CONTROLLER_TECS = 1 }
Public Member Functions
virtual void update_50hz (void)=0
virtual void update_pitch_throttle (int32_t hgt_dem_cm, int32_t EAS_dem_cm, enum AP_Vehicle::FixedWing::FlightStage flight_stage, float distance_beyond_land_wp, int32_t ptchMinCO_cd, int16_t throttle_nudge, float hgt_afe, float load_factor, bool soaring_active)=0
virtual int32_t get_throttle_demand (void)=0
virtual int32_t get_pitch_demand (void)=0
virtual float get_VXdot (void)=0
virtual float get_target_airspeed (void) const =0
virtual float get_max_climbrate (void) const =0
virtual void reset_pitch_I (void)=0
virtual float get_land_sinkrate (void) const =0
virtual float get_land_airspeed (void) const =0
virtual void set_path_proportion (float path_proportion)=0
Detailed Description
Definition at line 17 of file AP_SpdHgtControl.h.
Member Enumeration Documentation
ControllerType
enum AP_SpdHgtControl::ControllerType
Enumerator
CONTROLLER_TECS
Definition at line 69 of file AP_SpdHgtControl.h.
Member Function Documentation
get_land_airspeed()
virtual float AP_SpdHgtControl::get_land_airspeed (void) const pure virtual
Implemented in AP_TECS.
Referenced by AP_Landing::type_slope_get_target_airspeed_cm().
get_land_sinkrate()
virtual float AP_SpdHgtControl::get_land_sinkrate (void) const pure virtual
Implemented in AP_TECS.
Referenced by AP_Landing::type_slope_setup_landing_glide_slope().
get_max_climbrate()
virtual float AP_SpdHgtControl::get_max_climbrate (void) const pure virtual
Implemented in AP_TECS.
get_pitch_demand()
virtual int32_t AP_SpdHgtControl::get_pitch_demand (void) pure virtual
Implemented in AP_TECS.
get_target_airspeed()
virtual float AP_SpdHgtControl::get_target_airspeed (void) const pure virtual
Implemented in AP_TECS.
Referenced by AP_Landing::get_target_airspeed_cm(), and AP_L1_Control::loiter_radius().
get_throttle_demand()
virtual int32_t AP_SpdHgtControl::get_throttle_demand (void) pure virtual
Implemented in AP_TECS.
get_VXdot()
virtual float AP_SpdHgtControl::get_VXdot (void) pure virtual
Implemented in AP_TECS.
reset_pitch_I()
virtual void AP_SpdHgtControl::reset_pitch_I (void) pure virtual
Implemented in AP_TECS.
Referenced by SoaringController::suppress_throttle().
set_path_proportion()
virtual void AP_SpdHgtControl::set_path_proportion (float path_proportion) pure virtual
Implemented in AP_TECS.
update_50hz()
virtual void AP_SpdHgtControl::update_50hz (void) pure virtual
Implemented in AP_TECS.
update_pitch_throttle()
virtual void AP_SpdHgtControl::update_pitch_throttle (int32_t hgt_dem_cm, int32_t EAS_dem_cm, enum AP_Vehicle::FixedWing::FlightStage flight_stage, float distance_beyond_land_wp, int32_t ptchMinCO_cd, int16_t throttle_nudge, float hgt_afe, float load_factor, bool soaring_active) pure virtual
Implemented in AP_TECS.
The documentation for this class was generated from the following file:
libraries/AP_SpdHgtControl/AP_SpdHgtControl.h