APM:Libraries: Matrix3< T > Class Template Reference
Matrix3< T > Class Template Reference
#include <matrix3.h>
Public Member Functions
constexpr Matrix3 ()
constexpr Matrix3 (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
constexpr Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz)
void operator() (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
bool operator== (const Matrix3< T > &m)
bool operator != (const Matrix3< T > &m)
Matrix3< T > operator - (void) const
Matrix3< T > operator+ (const Matrix3< T > &m) const
Matrix3< T > & operator+= (const Matrix3< T > &m)
Matrix3< T > operator - (const Matrix3< T > &m) const
Matrix3< T > & operator -= (const Matrix3< T > &m)
Matrix3< T > operator * (const T num) const
Matrix3< T > & operator *= (const T num)
Matrix3< T > operator/ (const T num) const
Matrix3< T > & operator/= (const T num)
Vector3< T > & operator[] (uint8_t i)
const Vector3< T > & operator[] (uint8_t i) const
Vector3< T > operator * (const Vector3< T > &v) const
Vector3< T > mul_transpose (const Vector3< T > &v) const
Vector2< T > mulXY (const Vector3< T > &v) const
Vector3< T > colx (void) const
Vector3< T > coly (void) const
Vector3< T > colz (void) const
Matrix3< T > operator * (const Matrix3< T > &m) const
Matrix3< T > & operator *= (const Matrix3< T > &m)
Matrix3< T > transposed (void) const
void transpose (void)
T det () const
bool inverse (Matrix3< T > &inv) const
bool invert ()
void zero (void)
void identity (void)
bool is_nan (void)
void from_euler (float roll, float pitch, float yaw)
void to_euler (float *roll, float *pitch, float *yaw) const
void from_rotation (enum Rotation rotation)
Vector3< T > to_euler312 () const
void from_euler312 (float roll, float pitch, float yaw)
void rotate (const Vector3< T > &g)
void from_axis_angle (const Vector3< T > &v, float theta)
void normalize (void)
Public Attributes
Vector3< T > a
Vector3< T > b
Vector3< T > c
Detailed Description
template<typename T>
class Matrix3< T >
Definition at line 45 of file matrix3.h.
Constructor & Destructor Documentation
Matrix3() [1/3]
template<typename T> constexpr Matrix3< T >::Matrix3 () inline
Definition at line 53 of file matrix3.h.
Matrix3() [2/3]
template<typename T> constexpr Matrix3< T >::Matrix3 (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 56 of file matrix3.h.
Matrix3() [3/3]
template<typename T> constexpr Matrix3< T >::Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz) inline
Definition at line 62 of file matrix3.h.
Member Function Documentation
colx()
template<typename T> Vector3<T> Matrix3< T >::colx (void) const inline
Definition at line 158 of file matrix3.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), and Vector3< int32_t >::operator *().
coly()
template<typename T> Vector3<T> Matrix3< T >::coly (void) const inline
Definition at line 164 of file matrix3.h.
Referenced by Vector3< int32_t >::operator *().
colz()
template<typename T> Vector3<T> Matrix3< T >::colz (void) const inline
Definition at line 170 of file matrix3.h.
Referenced by Vector3< int32_t >::operator *().
det()
template<typename T > template double Matrix3< T >::det () const
Calculate the determinant of this matrix.
Returns
The value of the determinant.
Definition at line 190 of file matrix3.cpp.
from_axis_angle()
template<typename T> void Matrix3< T >::from_axis_angle (const Vector3< T > & v, float theta)
Definition at line 241 of file matrix3.cpp.
Referenced by SITL::Calibration::_calibration_poses(), and test_rotation_accuracy().
from_euler()
template<typename T > template void Matrix3< T >::from_euler (float roll, float pitch, float yaw)
Definition at line 26 of file matrix3.cpp.
Referenced by Compass::_setup_earth_field(), SITL::Aircraft::Aircraft(), AP_AHRS::AP_AHRS(), AP_AHRS_View::AP_AHRS_View(), SITL::BalanceBot::BalanceBot(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), SITL::Motor::calculate_forces(), AP_AHRS_DCM::drift_correction_yaw(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AP_Declination::get_earth_field_ga(), CompassCalibrator::AttitudeSample::get_rotmat(), loop(), missing_rotations(), SITL::SilentWings::process_packet(), CompassLearn::process_sample(), SITL::XPlane::receive_data(), SITL::last_letter::recv_fdm(), SITL::CRRCSim::recv_fdm(), SITL::JSBSim::recv_fdm(), AP_AHRS_DCM::reset(), AP_AHRS_DCM::reset_attitude(), AP_AHRS_View::set_pitch_trim(), Compass::setHIL(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_frame_transforms(), test_quaternion(), test_rotation_accuracy(), AP_OpticalFlow_SITL::update(), SITL::BalanceBot::update(), SITL::Morse::update(), SITL::Aircraft::update_dynamics(), SITL::Aircraft::update_mag_field_bf(), AP_AHRS::update_orientation(), AP_AHRS_NavEKF::update_SITL(), and AP_AHRS::update_trig().
from_euler312()
template<typename T > void Matrix3< T >::from_euler312 (float roll, float pitch, float yaw)
Definition at line 92 of file matrix3.cpp.
Referenced by Quaternion::from_vector312(), NavEKF2_core::fuseEulerYaw(), and NavEKF3_core::fuseEulerYaw().
from_rotation()
template<typename T > void Matrix3< T >::from_rotation (enum Rotation rotation)
Definition at line 63 of file matrix3.cpp.
Referenced by SITL::Aircraft::fill_fdm(), and test_rotate_matrix().
identity()
template<typename T> void Matrix3< T >::identity (void) inline
Definition at line 220 of file matrix3.h.
Referenced by AP_Compass_SITL::_setup_eliptical_correcion(), AP_AHRS_DCM::AP_AHRS_DCM(), AP_AHRS_NavEKF::AP_AHRS_NavEKF(), test_matrix_rotate(), CompassLearn::update(), and SITL::BalanceBot::update().
inverse()
template<typename T> template bool Matrix3< T >::inverse (Matrix3< T > & inv) const
Calculate the inverse of this matrix.
Parameters
inv[in] Where to store the result.
Returns
If this matrix is invertible, then true is returned. Otherwise, inv is unmodified and false is returned.
Definition at line 198 of file matrix3.cpp.
Referenced by TEST_P().
invert()
template<typename T > template bool Matrix3< T >::invert ()
Invert this matrix if it is invertible.
Returns
Return true if this matrix could be successfully inverted and false otherwise.
Definition at line 220 of file matrix3.cpp.
Referenced by AP_Compass_SITL::_setup_eliptical_correcion(), and CompassLearn::update().
is_nan()
template<typename T> bool Matrix3< T >::is_nan (void) inline
Definition at line 228 of file matrix3.h.
Referenced by AP_AHRS_DCM::check_matrix(), and test_conversion().
mul_transpose()
template<typename T> template Vector3< double > Matrix3< T >::mul_transpose (const Vector3< T > & v) const
Definition at line 158 of file matrix3.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), Vector3< int32_t >::rotate_inverse(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), Compass::setHIL(), AP_OpticalFlow_SITL::update(), AP_IRLock_SITL::update(), AC_PrecLand_SITL::update(), SITL::FlightAxis::update(), AP_AHRS::update_AOA_SSA(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
mulXY()
template<typename T> template Vector2< double > Matrix3< T >::mulXY (const Vector3< T > & v) const
Definition at line 150 of file matrix3.cpp.
Referenced by AP_AHRS_DCM::yaw_error_compass().
normalize()
template<typename T > void Matrix3< T >::normalize (void)
Definition at line 128 of file matrix3.cpp.
Referenced by SITL::Aircraft::extrapolate_sensors(), SITL::Gimbal::update(), SITL::BalanceBot::update(), SITL::Tracker::update(), SITL::SimRover::update(), SITL::Sailboat::update(), and SITL::Aircraft::update_dynamics().
operator !=()
template<typename T> bool Matrix3< T >::operator != (const Matrix3< T > & m) inline
Definition at line 82 of file matrix3.h.
operator *() [1/3]
template<typename T> Matrix3<T> Matrix3< T >::operator * (const T num) const inline
Definition at line 114 of file matrix3.h.
operator *() [2/3]
template<typename T> Vector3< T > Matrix3< T >::operator * (const Vector3< T > & v) const
Definition at line 141 of file matrix3.cpp.
operator *() [3/3]
template<typename T> Matrix3< T > Matrix3< T >::operator * (const Matrix3< T > & m) const
Definition at line 167 of file matrix3.cpp.
operator *=() [1/2]
template<typename T> Matrix3<T>& Matrix3< T >::operator *= (const T num) inline
Definition at line 118 of file matrix3.h.
operator *=() [2/2]
template<typename T> Matrix3<T>& Matrix3< T >::operator *= (const Matrix3< T > & m) inline
Definition at line 178 of file matrix3.h.
operator -() [1/2]
template<typename T> Matrix3<T> Matrix3< T >::operator - (void) const inline
Definition at line 88 of file matrix3.h.
operator -() [2/2]
template<typename T> Matrix3<T> Matrix3< T >::operator - (const Matrix3< T > & m) const inline
Definition at line 104 of file matrix3.h.
operator -=()
template<typename T> Matrix3<T>& Matrix3< T >::operator -= (const Matrix3< T > & m) inline
Definition at line 108 of file matrix3.h.
operator()()
template<typename T> void Matrix3< T >::operator() (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 70 of file matrix3.h.
operator+()
template<typename T> Matrix3<T> Matrix3< T >::operator+ (const Matrix3< T > & m) const inline
Definition at line 94 of file matrix3.h.
operator+=()
template<typename T> Matrix3<T>& Matrix3< T >::operator+= (const Matrix3< T > & m) inline
Definition at line 98 of file matrix3.h.
operator/()
template<typename T> Matrix3<T> Matrix3< T >::operator/ (const T num) const inline
Definition at line 122 of file matrix3.h.
operator/=()
template<typename T> Matrix3<T>& Matrix3< T >::operator/= (const T num) inline
Definition at line 126 of file matrix3.h.
operator==()
template<typename T> bool Matrix3< T >::operator== (const Matrix3< T > & m) inline
Definition at line 76 of file matrix3.h.
operator[]() [1/2]
template<typename T> Vector3<T>& Matrix3< T >::operator[] (uint8_t i) inline
Definition at line 132 of file matrix3.h.
operator[]() [2/2]
template<typename T> const Vector3<T>& Matrix3< T >::operator[] (uint8_t i) const inline
Definition at line 140 of file matrix3.h.
rotate()
template<typename T> template void Matrix3< T >::rotate (const Vector3< T > & g)
Definition at line 115 of file matrix3.cpp.
Referenced by SITL::Aircraft::extrapolate_sensors(), AP_AHRS_DCM::matrix_update(), test_matrix_rotate(), test_rotation_accuracy(), SITL::Gimbal::update(), SITL::BalanceBot::update(), SITL::Tracker::update(), SITL::SimRover::update(), SITL::Sailboat::update(), and SITL::Aircraft::update_dynamics().
to_euler()
template<typename T > template void Matrix3< T >::to_euler (float * roll, float * pitch, float * yaw) const
Definition at line 49 of file matrix3.cpp.
Referenced by AP_AHRS::calc_trig(), SITL::SITL::convert_earth_frame(), SITL::JSBSim::create_templates(), AP_AHRS_DCM::euler_angles(), SITL::Aircraft::fill_fdm(), CompassCalibrator::AttitudeSample::set_from_ahrs(), SITL::Aircraft::smooth_sensors(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_quaternion(), test_rotation_accuracy(), SITL::BalanceBot::update(), SITL::Tracker::update(), AP_AHRS_View::update(), SITL::Aircraft::update_dynamics(), and AP_AHRS_NavEKF::update_SITL().
to_euler312()
template<typename T > Vector3< T > Matrix3< T >::to_euler312 () const
Definition at line 81 of file matrix3.cpp.
Referenced by Quaternion::to_vector312(), and SITL::Gimbal::update().
transpose()
template<typename T> void Matrix3< T >::transpose (void) inline
Definition at line 186 of file matrix3.h.
Referenced by AP_AHRS_View::AP_AHRS_View(), AP_AHRS_View::set_pitch_trim(), and AP_Mount_Servo::stabilize().
transposed()
template<typename T > template Matrix3< double > Matrix3< T >::transposed (void) const
Definition at line 182 of file matrix3.cpp.
Referenced by SoloGimbalEKF::alignHeading(), AP_AHRS::AP_AHRS(), SITL::Frame::calculate_forces(), SITL::Plane::calculate_forces(), SITL::Aircraft::extrapolate_sensors(), SITL::Aircraft::fill_fdm(), have_rotation(), Matrix3< float >::transpose(), SITL::BalanceBot::update(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::Helicopter::update(), SITL::Sailboat::update(), SITL::SimRover::update(), SITL::Balloon::update(), SITL::SingleCopter::update(), SITL::FlightAxis::update(), SITL::Aircraft::update_dynamics(), SITL::Aircraft::update_mag_field_bf(), AP_AHRS_NavEKF::update_SITL(), and AP_AHRS::update_trig().
zero()
template<typename T > template void Matrix3< T >::zero (void)
Definition at line 231 of file matrix3.cpp.
Referenced by NavEKF2_core::InitialiseVariables(), and NavEKF3_core::InitialiseVariables().
Member Data Documentation
a
template<typename T> Vector3<T> Matrix3< T >::a
Definition at line 49 of file matrix3.h.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_AHRS::calc_trig(), Matrix3< float >::colx(), Matrix3< float >::coly(), Matrix3< float >::colz(), Quaternion::from_rotation_matrix(), Matrix3< float >::identity(), Matrix3< float >::inverse(), Matrix3< float >::is_nan(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator !=(), Matrix3< float >::operator *(), Matrix3< float >::operator -(), Matrix3< float >::operator()(), Matrix3< float >::operator+(), Matrix3< float >::operator/(), operator<<(), Matrix3< float >::operator==(), Matrix3< float >::operator[](), Quaternion::rotation_matrix(), Quaternion::rotation_matrix_norm(), NavEKF3_core::SelectBodyOdomFusion(), AP_Airspeed::send_airspeed_calibration(), test_matrix_rotate(), and Airspeed_Calibration::update().
b
template<typename T> Vector3<T> Matrix3< T >::b
Definition at line 49 of file matrix3.h.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_AHRS::calc_trig(), Matrix3< float >::colx(), Matrix3< float >::coly(), Matrix3< float >::colz(), Quaternion::from_rotation_matrix(), Matrix3< float >::identity(), Matrix3< float >::inverse(), Matrix3< float >::is_nan(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator !=(), Matrix3< float >::operator *(), Matrix3< float >::operator -(), Matrix3< float >::operator()(), Matrix3< float >::operator+(), Matrix3< float >::operator/(), operator<<(), Matrix3< float >::operator==(), Quaternion::rotation_matrix(), Quaternion::rotation_matrix_norm(), AP_Airspeed::send_airspeed_calibration(), test_matrix_rotate(), and Airspeed_Calibration::update().
c
template<typename T> Vector3<T> Matrix3< T >::c
Definition at line 49 of file matrix3.h.
Referenced by AP_AHRS::calc_trig(), Compass::calculate_heading(), AP_AHRS_DCM::check_matrix(), Matrix3< float >::colx(), Matrix3< float >::coly(), Matrix3< float >::colz(), AP_AHRS_DCM::drift_correction_yaw(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), Quaternion::from_rotation_matrix(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), AP_AHRS::get_yaw_rate_earth(), Matrix3< float >::identity(), Matrix3< float >::inverse(), Matrix3< float >::is_nan(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator !=(), Matrix3< float >::operator *(), Matrix3< float >::operator -(), Matrix3< float >::operator()(), Matrix3< float >::operator+(), Matrix3< float >::operator/(), operator<<(), Matrix3< float >::operator==(), Quaternion::rotation_matrix(), Quaternion::rotation_matrix_norm(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), AP_Airspeed::send_airspeed_calibration(), test_matrix_rotate(), AP_OpticalFlow_SITL::update(), Airspeed_Calibration::update(), SITL::Balloon::update(), and AP_TECS::update_50hz().
The documentation for this class was generated from the following files:
libraries/AP_Math/matrix3.h
libraries/AP_Math/matrix3.cpp