APM:Libraries: AP_InertialSensor_BMI088 Class Reference
AP_InertialSensor_BMI088 Class Reference
#include <AP_InertialSensor_BMI088.h>
Public Member Functions
void start () override
bool update () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
void notify_fifo_reset (void)
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, enum Rotation rotation=ROTATION_NONE)
Private Member Functions
AP_InertialSensor_BMI088 (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, enum Rotation rotation=ROTATION_NONE)
bool accel_init ()
bool gyro_init ()
bool init ()
void read_fifo_accel ()
void read_fifo_gyro ()
bool read_accel_registers (uint8_t reg, uint8_t *data, uint8_t len)
bool write_accel_register (uint8_t reg, uint8_t v)
bool setup_accel_config (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > dev_accel
AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro
uint8_t accel_instance
uint8_t gyro_instance
enum Rotation rotation
uint8_t temperature_counter
bool done_accel_config
uint32_t accel_config_count
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09, DEVTYPE_L3G4200D = 0x10, DEVTYPE_ACC_LSM303D = 0x11, DEVTYPE_ACC_BMA180 = 0x12,
DEVTYPE_ACC_MPU6000 = 0x13, DEVTYPE_ACC_MPU9250 = 0x16, DEVTYPE_ACC_IIS328DQ = 0x17, DEVTYPE_ACC_LSM9DS1 = 0x18,
DEVTYPE_GYR_MPU6000 = 0x21, DEVTYPE_GYR_L3GD20 = 0x22, DEVTYPE_GYR_MPU9250 = 0x24, DEVTYPE_GYR_I3G4250D = 0x25,
DEVTYPE_GYR_LSM9DS1 = 0x26, DEVTYPE_INS_ICM20789 = 0x27, DEVTYPE_INS_ICM20689 = 0x28, DEVTYPE_INS_BMI055 = 0x29,
DEVTYPE_SITL = 0x2A, DEVTYPE_INS_BMI088 = 0x2B, DEVTYPE_INS_ICM20948 = 0x2C, DEVTYPE_INS_ICM20648 = 0x2D,
DEVTYPE_INS_ICM20649 = 0x2E, DEVTYPE_INS_ICM20602 = 0x2F, DEVTYPE_INS_ICM20601 = 0x30
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sampl_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
void _inc_accel_error_count (uint8_t instance)
void _inc_gyro_error_count (uint8_t instance)
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
uint16_t _gyro_notch_center_freq_hz (void) const
uint16_t _gyro_notch_bandwidth_hz (void) const
float _gyro_notch_attenuation_dB (void) const
uint8_t _gyro_notch_enabled (void) const
void update_gyro (uint8_t instance)
void update_accel (uint8_t instance)
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance)
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel)
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro)
void notify_accel_fifo_reset (uint8_t instance)
void notify_gyro_fifo_reset (uint8_t instance)
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore_Recursive _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz [INS_MAX_INSTANCES]
uint16_t _last_gyro_filter_hz [INS_MAX_INSTANCES]
uint16_t _last_notch_center_freq_hz [INS_MAX_INSTANCES]
uint16_t _last_notch_bandwidth_hz [INS_MAX_INSTANCES]
float _last_notch_attenuation_dB [INS_MAX_INSTANCES]
Detailed Description
Definition at line 26 of file AP_InertialSensor_BMI088.h.
Constructor & Destructor Documentation
AP_InertialSensor_BMI088()
AP_InertialSensor_BMI088::AP_InertialSensor_BMI088 (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, enum Rotation rotation = ROTATION_NONE) private
Definition at line 61 of file AP_InertialSensor_BMI088.cpp.
Referenced by probe().
Member Function Documentation
accel_init()
bool AP_InertialSensor_BMI088::accel_init () private
Definition at line 189 of file AP_InertialSensor_BMI088.cpp.
Referenced by init().
gyro_init()
bool AP_InertialSensor_BMI088::gyro_init () private
Definition at line 214 of file AP_InertialSensor_BMI088.cpp.
Referenced by init().
init()
bool AP_InertialSensor_BMI088::init (void) private
Definition at line 260 of file AP_InertialSensor_BMI088.cpp.
probe()
AP_InertialSensor_Backend * AP_InertialSensor_BMI088::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, enum Rotation rotation = ROTATION_NONE) static
Definition at line 73 of file AP_InertialSensor_BMI088.cpp.
Referenced by AP_InertialSensor::detect_backends().
read_accel_registers()
bool AP_InertialSensor_BMI088::read_accel_registers (uint8_t reg, uint8_t * data, uint8_t len) private
Definition at line 114 of file AP_InertialSensor_BMI088.cpp.
Referenced by accel_init(), read_fifo_accel(), setup_accel_config(), and write_accel_register().
read_fifo_accel()
void AP_InertialSensor_BMI088::read_fifo_accel (void) private
Definition at line 271 of file AP_InertialSensor_BMI088.cpp.
Referenced by start().
read_fifo_gyro()
void AP_InertialSensor_BMI088::read_fifo_gyro (void) private
Definition at line 363 of file AP_InertialSensor_BMI088.cpp.
Referenced by start().
setup_accel_config()
bool AP_InertialSensor_BMI088::setup_accel_config (void) private
Definition at line 163 of file AP_InertialSensor_BMI088.cpp.
Referenced by accel_init(), and read_fifo_accel().
start()
void AP_InertialSensor_BMI088::start (void) override virtual
Configure the sensors and start reading routine.
Reimplemented from AP_InertialSensor_Backend.
Definition at line 95 of file AP_InertialSensor_BMI088.cpp.
update()
bool AP_InertialSensor_BMI088::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 405 of file AP_InertialSensor_BMI088.cpp.
write_accel_register()
bool AP_InertialSensor_BMI088::write_accel_register (uint8_t reg, uint8_t v) private
Definition at line 136 of file AP_InertialSensor_BMI088.cpp.
Referenced by setup_accel_config().
Member Data Documentation
accel_config_count
uint32_t AP_InertialSensor_BMI088::accel_config_count private
Definition at line 86 of file AP_InertialSensor_BMI088.h.
Referenced by setup_accel_config().
accel_instance
uint8_t AP_InertialSensor_BMI088::accel_instance private
Definition at line 80 of file AP_InertialSensor_BMI088.h.
Referenced by read_fifo_accel(), start(), and update().
dev_accel
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_BMI088::dev_accel private
Definition at line 77 of file AP_InertialSensor_BMI088.h.
Referenced by accel_init(), init(), probe(), read_accel_registers(), start(), and write_accel_register().
dev_gyro
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_BMI088::dev_gyro private
Definition at line 78 of file AP_InertialSensor_BMI088.h.
Referenced by gyro_init(), init(), probe(), read_fifo_gyro(), and start().
done_accel_config
bool AP_InertialSensor_BMI088::done_accel_config private
Definition at line 85 of file AP_InertialSensor_BMI088.h.
Referenced by setup_accel_config().
gyro_instance
uint8_t AP_InertialSensor_BMI088::gyro_instance private
Definition at line 81 of file AP_InertialSensor_BMI088.h.
Referenced by read_fifo_gyro(), start(), and update().
rotation
enum Rotation AP_InertialSensor_BMI088::rotation private
Definition at line 82 of file AP_InertialSensor_BMI088.h.
Referenced by probe(), and start().
temperature_counter
uint8_t AP_InertialSensor_BMI088::temperature_counter private
Definition at line 83 of file AP_InertialSensor_BMI088.h.
Referenced by read_fifo_accel().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp