APM:Libraries: AP_HAL::SPIDevice Class Reference
AP_HAL::SPIDevice Class Reference abstract
#include <SPIDevice.h>
Public Member Functions
SPIDevice ()
virtual ~SPIDevice ()
virtual bool set_speed (Device::Speed speed) override=0
virtual bool transfer (const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len) override=0
virtual bool transfer_fullduplex (const uint8_t *send, uint8_t *recv, uint32_t len)=0
virtual bool clock_pulse (uint32_t len)
virtual Semaphore * get_semaphore () override=0
virtual Device::PeriodicHandle register_periodic_callback (uint32_t period_usec, Device::PeriodicCb) override=0
virtual bool adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec) override
virtual void set_slowdown (uint8_t slowdown)
Public Member Functions inherited from AP_HAL::Device
FUNCTOR_TYPEDEF (PeriodicCb, void)
Device (enum BusType type)
enum BusType bus_type (void) const
uint8_t bus_num (void) const
uint32_t get_bus_id (void) const
uint8_t get_bus_address (void) const
void set_device_type (uint8_t devtype)
virtual ~Device ()
virtual void set_address (uint8_t address)
bool read_registers (uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_register (uint8_t reg, uint8_t val, bool checked=false)
void set_checked_register (uint8_t reg, uint8_t val)
bool setup_checked_registers (uint8_t num_regs, uint8_t frequency=10)
bool check_next_register (void)
bool read (uint8_t *recv, uint32_t recv_len)
virtual PeriodicHandle register_periodic_callback (uint32_t period_usec, PeriodicCb)=0
virtual bool unregister_callback (PeriodicHandle h)
virtual void register_completion_callback (AP_HAL::MemberProc proc)
virtual void register_completion_callback (AP_HAL::Proc proc)
virtual bool set_chip_select (bool set)
void set_read_flag (uint8_t flag)
uint32_t get_bus_id_devtype (uint8_t devtype)
virtual void set_retries (uint8_t retries)
Additional Inherited Members
Public Types inherited from AP_HAL::Device
enum BusType {
BUS_TYPE_UNKNOWN = 0, BUS_TYPE_I2C = 1, BUS_TYPE_SPI = 2, BUS_TYPE_UAVCAN = 3,
BUS_TYPE_SITL = 4
}
enum Speed { SPEED_HIGH, SPEED_LOW }
typedef void * PeriodicHandle
Static Public Member Functions inherited from AP_HAL::Device
static uint32_t make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype)
static uint32_t change_bus_id (uint32_t old_id, uint8_t devtype)
Protected Member Functions inherited from AP_HAL::Device
void set_device_address (uint8_t address)
void set_device_bus (uint8_t bus)
Protected Attributes inherited from AP_HAL::Device
uint8_t _read_flag = 0
union DeviceId _bus_id
Detailed Description
Definition at line 27 of file SPIDevice.h.
Constructor & Destructor Documentation
SPIDevice()
AP_HAL::SPIDevice::SPIDevice () inline
Definition at line 29 of file SPIDevice.h.
~SPIDevice()
virtual AP_HAL::SPIDevice::~SPIDevice () inline virtual
Reimplemented in ChibiOS::SPIDevice, Empty::SPIDevice, and Linux::SPIDevice.
Definition at line 31 of file SPIDevice.h.
Member Function Documentation
adjust_periodic_callback()
virtual bool AP_HAL::SPIDevice::adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec) inline override virtual
Implements AP_HAL::Device.
Reimplemented in ChibiOS::SPIDevice, and Linux::SPIDevice.
Definition at line 62 of file SPIDevice.h.
clock_pulse()
virtual bool AP_HAL::SPIDevice::clock_pulse (uint32_t len) inline virtual
Reimplemented in ChibiOS::SPIDevice.
Definition at line 52 of file SPIDevice.h.
get_semaphore()
virtual Semaphore* AP_HAL::SPIDevice::get_semaphore () override pure virtual
Implements AP_HAL::Device.
Implemented in ChibiOS::SPIDevice, Empty::SPIDevice, and Linux::SPIDevice.
Referenced by AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), AP_InertialSensor_LSM9DS1::_init_sensor(), Linux::SPIUARTDriver::_read_fd(), Linux::SPIUARTDriver::_write_fd(), AP_RAMTRON::init(), Radio_CC2500::lock_bus(), AP_RAMTRON::read(), AP_OpticalFlow_Pixart::setup_sensor(), Radio_CC2500::unlock_bus(), and AP_RAMTRON::write().
register_periodic_callback()
virtual Device::PeriodicHandle AP_HAL::SPIDevice::register_periodic_callback (uint32_t period_usec, Device::PeriodicCb) override pure virtual
Referenced by AP_OpticalFlow_Pixart::setup_sensor(), AP_InertialSensor_LSM9DS1::start(), and AP_InertialSensor_RST::start().
set_slowdown()
virtual void AP_HAL::SPIDevice::set_slowdown (uint8_t slowdown) inline virtual
Reimplemented in ChibiOS::SPIDevice.
Definition at line 66 of file SPIDevice.h.
Referenced by sdcard_init().
set_speed()
virtual bool AP_HAL::SPIDevice::set_speed (Device::Speed speed) override pure virtual
Implements AP_HAL::Device.
Implemented in ChibiOS::SPIDevice, Empty::SPIDevice, and Linux::SPIDevice.
Referenced by AP_InertialSensor_LSM9DS1::_fifo_reset(), AP_InertialSensor_LSM9DS1::_hardware_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), and Linux::SPIUARTDriver::begin().
transfer()
virtual bool AP_HAL::SPIDevice::transfer (const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len) override pure virtual
Implements AP_HAL::Device.
Implemented in ChibiOS::SPIDevice, Empty::SPIDevice, and Linux::SPIDevice.
Referenced by AP_InertialSensor_LSM9DS1::_read_data_transaction_g(), AP_InertialSensor_LSM9DS1::_read_data_transaction_x(), AP_OpticalFlow_Pixart::motion_burst(), AP_RAMTRON::read(), AP_OpticalFlow_Pixart::reg_read(), AP_OpticalFlow_Pixart::reg_write(), AP_RAMTRON::send_offset(), AP_OpticalFlow_Pixart::srom_download(), Radio_CC2500::Strobe(), AP_RAMTRON::write(), and Radio_CC2500::WriteRegisterMulti().
transfer_fullduplex()
virtual bool AP_HAL::SPIDevice::transfer_fullduplex (const uint8_t * send, uint8_t * recv, uint32_t len) pure virtual
Implemented in ChibiOS::SPIDevice, Empty::SPIDevice, and Linux::SPIDevice.
Referenced by Linux::SPIUARTDriver::_read_fd(), and Linux::SPIUARTDriver::_write_fd().
The documentation for this class was generated from the following file:
libraries/AP_HAL/SPIDevice.h