APM:Libraries: RSCGovParam Class Reference
RSCGovParam Class Reference
#include <AP_MotorsHeli_RSC.h>
Public Member Functions
RSCGovParam (void)
void set_gov_enable (int8_t setenable)
int16_t get_reference ()
float get_range ()
float get_disengage ()
float get_droop_response ()
float get_thrcurve ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 enable
AP_Int16 reference
AP_Float range
AP_Float disengage
AP_Float droop_response
AP_Float thrcurve
Detailed Description
Definition at line 177 of file AP_MotorsHeli_RSC.h.
Constructor & Destructor Documentation
RSCGovParam()
RSCGovParam::RSCGovParam (void)
Definition at line 132 of file AP_MotorsHeli_RSC.cpp.
Member Function Documentation
get_disengage()
float RSCGovParam::get_disengage () inline
Definition at line 186 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
get_droop_response()
float RSCGovParam::get_droop_response () inline
Definition at line 187 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
get_range()
float RSCGovParam::get_range () inline
Definition at line 185 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
get_reference()
int16_t RSCGovParam::get_reference () inline
Definition at line 184 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
get_thrcurve()
float RSCGovParam::get_thrcurve () inline
Definition at line 188 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli_Dual::calculate_armed_scalars().
set_gov_enable()
void RSCGovParam::set_gov_enable (int8_t setenable) inline
Definition at line 183 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::enable_rsc_parameters().
Member Data Documentation
disengage
AP_Float RSCGovParam::disengage private
Definition at line 194 of file AP_MotorsHeli_RSC.h.
Referenced by get_disengage().
droop_response
AP_Float RSCGovParam::droop_response private
Definition at line 195 of file AP_MotorsHeli_RSC.h.
Referenced by get_droop_response().
enable
AP_Int8 RSCGovParam::enable private
Definition at line 191 of file AP_MotorsHeli_RSC.h.
Referenced by set_gov_enable().
range
AP_Float RSCGovParam::range private
Definition at line 193 of file AP_MotorsHeli_RSC.h.
Referenced by get_range().
reference
AP_Int16 RSCGovParam::reference private
Definition at line 192 of file AP_MotorsHeli_RSC.h.
Referenced by get_reference().
thrcurve
AP_Float RSCGovParam::thrcurve private
Definition at line 196 of file AP_MotorsHeli_RSC.h.
Referenced by get_thrcurve().
var_info
const AP_Param::GroupInfo RSCGovParam::var_info static
Definition at line 181 of file AP_MotorsHeli_RSC.h.
Referenced by RSCGovParam().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp