APM:Libraries: PosVelEKF Class Reference
PosVelEKF Class Reference
#include <PosVelEKF.h>
Public Member Functions
void init (float pos, float posVar, float vel, float velVar)
void predict (float dt, float dVel, float dVelNoise)
void fusePos (float pos, float posVar)
void fuseVel (float vel, float velVar)
float getPos () const
float getVel () const
float getPosNIS (float pos, float posVar)
Private Attributes
float _state [2]
float _cov [3]
Detailed Description
Definition at line 3 of file PosVelEKF.h.
Member Function Documentation
fusePos()
void PosVelEKF::fusePos (float pos, float posVar)
Definition at line 62 of file PosVelEKF.cpp.
Referenced by AC_PrecLand::run_estimator().
fuseVel()
void PosVelEKF::fuseVel (float vel, float velVar)
Definition at line 74 of file PosVelEKF.cpp.
getPos()
float PosVelEKF::getPos () const inline
Definition at line 10 of file PosVelEKF.h.
Referenced by AC_PrecLand::run_estimator().
getPosNIS()
float PosVelEKF::getPosNIS (float pos, float posVar)
Definition at line 86 of file PosVelEKF.cpp.
Referenced by AC_PrecLand::run_estimator().
getVel()
float PosVelEKF::getVel () const inline
Definition at line 11 of file PosVelEKF.h.
Referenced by AC_PrecLand::run_estimator().
init()
void PosVelEKF::init (float pos, float posVar, float vel, float velVar)
Definition at line 41 of file PosVelEKF.cpp.
Referenced by AC_PrecLand::run_estimator().
predict()
void PosVelEKF::predict (float dt, float dVel, float dVelNoise)
Definition at line 50 of file PosVelEKF.cpp.
Referenced by AC_PrecLand::run_estimator().
Member Data Documentation
_cov
float PosVelEKF::_cov[3] private
Definition at line 17 of file PosVelEKF.h.
Referenced by fusePos(), fuseVel(), getPosNIS(), init(), and predict().
_state
float PosVelEKF::_state[2] private
Definition at line 16 of file PosVelEKF.h.
Referenced by fusePos(), fuseVel(), getPos(), getPosNIS(), getVel(), init(), and predict().
The documentation for this class was generated from the following files:
libraries/AC_PrecLand/PosVelEKF.h
libraries/AC_PrecLand/PosVelEKF.cpp