APM:Libraries: AP_Rally Class Reference
AP_Rally Class Reference
Object managing Rally Points.
#include <AP_Rally.h>
Public Member Functions
AP_Rally ()
AP_Rally (const AP_Rally &other)=delete
AP_Rally & operator= (const AP_Rally &)=delete
bool get_rally_point_with_index (uint8_t i, RallyLocation &ret) const
bool set_rally_point_with_index (uint8_t i, const RallyLocation &rallyLoc)
uint8_t get_rally_total () const
uint8_t get_rally_max (void) const
void truncate (uint8_t num)
bool append (const RallyLocation &loc) WARN_IF_UNUSED
float get_rally_limit_km () const
Location rally_location_to_location (const RallyLocation &ret) const
Location calc_best_rally_or_home_location (const Location &current_loc, float rtl_home_alt) const
bool find_nearest_rally_point (const Location &myloc, RallyLocation &ret) const
uint32_t last_change_time_ms (void) const
Static Public Member Functions
static AP_Rally * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
virtual bool is_valid (const Location &rally_point) const
Private Attributes
AP_Int8 _rally_point_total_count
AP_Float _rally_limit_km
AP_Int8 _rally_incl_home
uint32_t _last_change_time_ms = 0xFFFFFFFF
Static Private Attributes
static AP_Rally * _singleton
static StorageAccess _storage
Detailed Description
Object managing Rally Points.
Definition at line 34 of file AP_Rally.h.
Constructor & Destructor Documentation
AP_Rally() [1/2]
AP_Rally::AP_Rally ()
Definition at line 54 of file AP_Rally.cpp.
AP_Rally() [2/2]
AP_Rally::AP_Rally (const AP_Rally & other) delete
Member Function Documentation
append()
bool AP_Rally::append (const RallyLocation & loc)
Definition at line 90 of file AP_Rally.cpp.
Referenced by MissionItemProtocol_Rally::append_item().
calc_best_rally_or_home_location()
Location AP_Rally::calc_best_rally_or_home_location (const Location & current_loc, float rtl_home_alt) const
Definition at line 169 of file AP_Rally.cpp.
find_nearest_rally_point()
bool AP_Rally::find_nearest_rally_point (const Location & myloc, RallyLocation & ret) const
Definition at line 141 of file AP_Rally.cpp.
Referenced by calc_best_rally_or_home_location(), and AP_Arming::mission_checks().
get_rally_limit_km()
float AP_Rally::get_rally_limit_km () const inline
Definition at line 60 of file AP_Rally.h.
get_rally_max()
uint8_t AP_Rally::get_rally_max (void) const inline
Definition at line 48 of file AP_Rally.h.
Referenced by GCS_MAVLINK::handle_rally_point(), MissionItemProtocol_Rally::max_items(), and set_rally_point_with_index().
get_rally_point_with_index()
bool AP_Rally::get_rally_point_with_index (uint8_t i, RallyLocation & ret) const
Definition at line 66 of file AP_Rally.cpp.
Referenced by find_nearest_rally_point(), MissionItemProtocol_Rally::get_item(), GCS_MAVLINK::handle_rally_fetch_point(), and LoggerMessageWriter_WriteAllRallyPoints::process().
get_rally_total()
uint8_t AP_Rally::get_rally_total () const inline
Definition at line 45 of file AP_Rally.h.
Referenced by append(), GCS_MAVLINK::handle_rally_fetch_point(), GCS_MAVLINK::handle_rally_point(), MissionItemProtocol_Rally::item_count(), and LoggerMessageWriter_WriteAllRallyPoints::process().
get_singleton()
static AP_Rally* AP_Rally::get_singleton (void) inline static
Definition at line 75 of file AP_Rally.h.
Referenced by AP::rally().
is_valid()
virtual bool AP_Rally::is_valid (const Location & rally_point) const inline private virtual
Definition at line 81 of file AP_Rally.h.
Referenced by find_nearest_rally_point().
last_change_time_ms()
uint32_t AP_Rally::last_change_time_ms (void) const inline
Definition at line 69 of file AP_Rally.h.
operator=()
AP_Rally& AP_Rally::operator= (const AP_Rally &) delete
rally_location_to_location()
Location AP_Rally::rally_location_to_location (const RallyLocation & ret) const
Definition at line 122 of file AP_Rally.cpp.
Referenced by calc_best_rally_or_home_location(), and find_nearest_rally_point().
set_rally_point_with_index()
bool AP_Rally::set_rally_point_with_index (uint8_t i, const RallyLocation & rallyLoc)
Definition at line 102 of file AP_Rally.cpp.
Referenced by append(), GCS_MAVLINK::handle_rally_point(), and MissionItemProtocol_Rally::replace_item().
truncate()
void AP_Rally::truncate (uint8_t num)
Definition at line 81 of file AP_Rally.cpp.
Referenced by MissionItemProtocol_Rally::clear_all_items(), and MissionItemProtocol_Rally::truncate().
Member Data Documentation
_last_change_time_ms
uint32_t AP_Rally::_last_change_time_ms = 0xFFFFFFFF private
Definition at line 90 of file AP_Rally.h.
Referenced by last_change_time_ms(), and set_rally_point_with_index().
_rally_incl_home
AP_Int8 AP_Rally::_rally_incl_home private
Definition at line 88 of file AP_Rally.h.
Referenced by calc_best_rally_or_home_location().
_rally_limit_km
AP_Float AP_Rally::_rally_limit_km private
Definition at line 87 of file AP_Rally.h.
Referenced by find_nearest_rally_point(), and get_rally_limit_km().
_rally_point_total_count
AP_Int8 AP_Rally::_rally_point_total_count private
Definition at line 86 of file AP_Rally.h.
Referenced by append(), find_nearest_rally_point(), get_rally_point_with_index(), get_rally_total(), set_rally_point_with_index(), and truncate().
_singleton
AP_Rally * AP_Rally::_singleton static private
Definition at line 79 of file AP_Rally.h.
Referenced by AP_Rally(), and get_singleton().
_storage
StorageAccess AP_Rally::_storage static private
Definition at line 83 of file AP_Rally.h.
Referenced by get_rally_max(), get_rally_point_with_index(), and set_rally_point_with_index().
var_info
const AP_Param::GroupInfo AP_Rally::var_info static
Initial value:
= {
    AP_GROUPINFO("TOTAL", 0, AP_Rally, _rally_point_total_count, 0),
    AP_GROUPINFO("LIMIT_KM", 1, AP_Rally, _rally_limit_km, RALLY_LIMIT_KM_DEFAULT),
    AP_GROUPINFO("INCL_HOME", 2, AP_Rally, _rally_incl_home, RALLY_INCLUDE_HOME_DEFAULT),
    AP_GROUPEND
}
Definition at line 72 of file AP_Rally.h.
Referenced by AP_Rally().
The documentation for this class was generated from the following files:
libraries/AP_Rally/AP_Rally.h
libraries/AP_Rally/AP_Rally.cpp