APM:Libraries: AP_ROMFS Class Reference
AP_ROMFS Class Reference
#include <AP_ROMFS.h>
Classes
struct embedded_file
Static Public Member Functions
static uint8_t * find_decompress (const char *name, uint32_t &size)
Static Private Member Functions
static const uint8_t * find_file (const char *name, uint32_t &size)
Static Private Attributes
static const struct embedded_file files [] = {}
Detailed Description
Definition at line 8 of file AP_ROMFS.h.
Member Function Documentation
find_decompress()
uint8_t * AP_ROMFS::find_decompress (const char * name, uint32_t & size) static
Definition at line 48 of file AP_ROMFS.cpp.
Referenced by ChibiOS::Util::flash_bootloader(), lua_scripts::run(), and AP_OSD_MAX7456::update_font().
find_file()
const uint8_t * AP_ROMFS::find_file (const char * name, uint32_t & size) static private
Definition at line 31 of file AP_ROMFS.cpp.
Referenced by find_decompress().
Member Data Documentation
files
const AP_ROMFS::embedded_file AP_ROMFS::files = {} static private
Definition at line 25 of file AP_ROMFS.h.
Referenced by find_file().
The documentation for this class was generated from the following files:
libraries/AP_ROMFS/AP_ROMFS.h
libraries/AP_ROMFS/AP_ROMFS.cpp