APM:Libraries: Linux::Perf Class Reference
Linux::Perf Class Reference
#include <Perf.h>
Public Member Functions
~Perf ()
perf_counter_t add (perf_counter_type type, const char *name)
void begin (perf_counter_t pc)
void end (perf_counter_t pc)
void count (perf_counter_t pc)
unsigned int get_update_count ()
Static Public Member Functions
static Perf * get_singleton ()
Private Types
using perf_counter_type = AP_HAL::Util::perf_counter_type
using perf_counter_t = AP_HAL::Util::perf_counter_t
Private Member Functions
Perf ()
void _debug_counters ()
Private Attributes
uint64_t _last_debug_msec
std::vector< Perf_Counter > _perf_counters
pthread_rwlock_t _perf_counters_lock
std::atomic< unsigned int > _update_count
Static Private Attributes
static Perf * _singleton
Detailed Description
Definition at line 60 of file Perf.h.
Member Typedef Documentation
perf_counter_t
using Linux::Perf::perf_counter_t = AP_HAL::Util::perf_counter_t private
Definition at line 62 of file Perf.h.
perf_counter_type
using Linux::Perf::perf_counter_type = AP_HAL::Util::perf_counter_type private
Definition at line 61 of file Perf.h.
Constructor & Destructor Documentation
~Perf()
Linux::Perf::~Perf ()
Perf()
Perf::Perf () private
Definition at line 95 of file Perf.cpp.
Referenced by get_singleton().
Member Function Documentation
_debug_counters()
void Perf::_debug_counters () private
Definition at line 56 of file Perf.cpp.
Referenced by Perf().
add()
Util::perf_counter_t Perf::add (Util::perf_counter_type type, const char * name)
Definition at line 211 of file Perf.cpp.
Referenced by Linux::Util::perf_alloc().
begin()
void Perf::begin (Util::perf_counter_t pc)
Definition at line 111 of file Perf.cpp.
Referenced by Linux::Util::perf_begin().
count()
void Perf::count (Util::perf_counter_t pc)
Definition at line 189 of file Perf.cpp.
Referenced by Linux::Util::perf_count().
end()
void Perf::end (Util::perf_counter_t pc)
Definition at line 140 of file Perf.cpp.
Referenced by Linux::Util::perf_end().
get_singleton()
Perf * Perf::get_singleton (void) static
Definition at line 47 of file Perf.cpp.
Referenced by Linux::Util::perf_alloc(), Linux::Util::perf_begin(), Linux::Util::perf_count(), and Linux::Util::perf_end().
get_update_count()
unsigned int Linux::Perf::get_update_count () inline
Definition at line 75 of file Perf.h.
Member Data Documentation
_last_debug_msec
uint64_t Linux::Perf::_last_debug_msec private
Definition at line 84 of file Perf.h.
Referenced by _debug_counters().
_perf_counters
std::vector<Perf_Counter> Linux::Perf::_perf_counters private
Definition at line 86 of file Perf.h.
Referenced by _debug_counters(), add(), begin(), count(), end(), and Perf().
_perf_counters_lock
pthread_rwlock_t Linux::Perf::_perf_counters_lock private
Definition at line 89 of file Perf.h.
Referenced by _debug_counters(), add(), and Perf().
_singleton
Perf * Perf::_singleton static private
Definition at line 78 of file Perf.h.
Referenced by get_singleton().
_update_count
std::atomic<unsigned int> Linux::Perf::_update_count private
Definition at line 92 of file Perf.h.
Referenced by _debug_counters(), begin(), count(), end(), and get_update_count().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Perf.h
libraries/AP_HAL_Linux/Perf.cpp