APM:Libraries: AP_Gripper_EPM Class Reference
AP_Gripper_EPM Class Reference
Class to manage the EPM_CargoGripper.
#include <AP_Gripper_EPM.h>
Public Member Functions
AP_Gripper_EPM (struct AP_Gripper::Backend_Config &_config)
void init_gripper () override
void grab () override
void release () override
bool grabbed () const override
bool released () const override
void update_gripper () override
Public Member Functions inherited from AP_Gripper_Backend
AP_Gripper_Backend (struct AP_Gripper::Backend_Config &_config)
void init ()
void update ()
virtual bool valid () const
Private Member Functions
void neutral ()
bool should_use_uavcan () const
struct UAVCANCommand make_uavcan_command (uint16_t command) const
Private Attributes
int _uavcan_fd = -1
uint32_t _last_grab_or_release
Additional Inherited Members
Protected Attributes inherited from AP_Gripper_Backend
struct AP_Gripper::Backend_Config & config
Detailed Description
Class to manage the EPM_CargoGripper.
Definition at line 25 of file AP_Gripper_EPM.h.
Constructor & Destructor Documentation
AP_Gripper_EPM()
AP_Gripper_EPM::AP_Gripper_EPM (struct AP_Gripper::Backend_Config & _config)
Definition at line 21 of file AP_Gripper_EPM.cpp.
Member Function Documentation
grab()
void AP_Gripper_EPM::grab () override virtual
Implements AP_Gripper_Backend.
Definition at line 43 of file AP_Gripper_EPM.cpp.
Referenced by update_gripper().
grabbed()
bool AP_Gripper_EPM::grabbed () const override virtual
Implements AP_Gripper_Backend.
Definition at line 136 of file AP_Gripper_EPM.cpp.
init_gripper()
void AP_Gripper_EPM::init_gripper () override virtual
Implements AP_Gripper_Backend.
Definition at line 24 of file AP_Gripper_EPM.cpp.
make_uavcan_command()
UAVCANCommand AP_Gripper_EPM::make_uavcan_command (uint16_t command) const private
Definition at line 120 of file AP_Gripper_EPM.cpp.
Referenced by grab(), and release().
neutral()
void AP_Gripper_EPM::neutral () private
Definition at line 89 of file AP_Gripper_EPM.cpp.
Referenced by init_gripper(), and update_gripper().
release()
void AP_Gripper_EPM::release () override virtual
Implements AP_Gripper_Backend.
Definition at line 66 of file AP_Gripper_EPM.cpp.
released()
bool AP_Gripper_EPM::released () const override virtual
Implements AP_Gripper_Backend.
Definition at line 129 of file AP_Gripper_EPM.cpp.
should_use_uavcan()
bool AP_Gripper_EPM::should_use_uavcan () const inline private
Definition at line 53 of file AP_Gripper_EPM.h.
Referenced by grab(), neutral(), and release().
update_gripper()
void AP_Gripper_EPM::update_gripper () override virtual
Reimplemented from AP_Gripper_Backend.
Definition at line 99 of file AP_Gripper_EPM.cpp.
Member Data Documentation
_last_grab_or_release
uint32_t AP_Gripper_EPM::_last_grab_or_release private
Definition at line 61 of file AP_Gripper_EPM.h.
Referenced by grab(), release(), and update_gripper().
_uavcan_fd
int AP_Gripper_EPM::_uavcan_fd = -1 private
Definition at line 58 of file AP_Gripper_EPM.h.
Referenced by grab(), init_gripper(), release(), and should_use_uavcan().
The documentation for this class was generated from the following files:
libraries/AP_Gripper/AP_Gripper_EPM.h
libraries/AP_Gripper/AP_Gripper_EPM.cpp