APM:Libraries: libraries/AP_Math/crc.h File Reference
crc.h File Reference
Functions
uint16_t crc_crc4 (uint16_t *data)
uint8_t crc_crc8 (const uint8_t *p, uint8_t len)
uint16_t crc_xmodem_update (uint16_t crc, uint8_t data)
uint16_t crc_xmodem (const uint8_t *data, uint16_t len)
uint32_t crc_crc32 (uint32_t crc, const uint8_t *buf, uint32_t size)
uint16_t crc16_ccitt (const uint8_t *buf, uint32_t len, uint16_t crc)
Function Documentation
crc16_ccitt()
uint16_t crc16_ccitt (const uint8_t * buf, uint32_t len, uint16_t crc)
Definition at line 226 of file crc.cpp.
Referenced by AP_GPS_SBP2::_detect(), AP_GPS_SBP::_detect(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), HALSITL::SITL_State::_sbp_send_message(), and AP_GPS_SBF::parse().
crc_crc32()
uint32_t crc_crc32 (uint32_t crc, const uint8_t * buf, uint32_t size)
Definition at line 170 of file crc.cpp.
Referenced by AP_IOMCU_FW::calculate_fw_crc().
crc_crc4()
uint16_t crc_crc4 (uint16_t * data)
crc4 method from datasheet for 16 bytes (8 short values)
Parameters
[in] data
Returns
crc4
Definition at line 28 of file crc.cpp.
Referenced by AP_Baro_MS56XX::_read_prom_5611(), AP_Baro_MS56XX::_read_prom_5637(), and AP_Airspeed_MS5525::crc4_prom().
crc_crc8()
uint8_t crc_crc8 (const uint8_t * p, uint8_t len)
Definition at line 81 of file crc.cpp.
Referenced by AP_RangeFinder_TeraRangerI2C::collect_raw(), AP_IOMCU_FW::handle_code_read(), AP_IOMCU_FW::handle_code_write(), AP_IOMCU_FW::process_io_packet(), AP_Proximity_TeraRangerTowerEvo::read_sensor_data(), and AP_Proximity_TeraRangerTower::read_sensor_data().
crc_xmodem()
uint16_t crc_xmodem (const uint8_t * data, uint16_t len)
Definition at line 112 of file crc.cpp.
crc_xmodem_update()
uint16_t crc_xmodem_update (uint16_t crc, uint8_t data)
Definition at line 97 of file crc.cpp.
Referenced by AP_RCProtocol_SUMD::_process_byte(), AP_RCProtocol_SRXL::_process_byte(), crc_xmodem(), srxl_decode(), and sumd_decode().