APM:Libraries: libraries/AP_Param/tools/eedump.c File Reference
eedump.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
Classes
struct EEPROM_header
struct Var_header
Functions
void fail (const char *why)
int main (int argc, char *argv[])
Variables
uint8_t eeprom [0x1000]
static const uint16_t k_EEPROM_magic = 0x5041
static const uint16_t k_EEPROM_revision = 2
static const uint8_t k_key_sentinel = 0xff
Function Documentation
fail()
void fail (const char * why)
Definition at line 28 of file eedump.c.
Referenced by Linux::Storage::_storage_create(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), AP_Compass_AK8963::init(), AP_Compass_IST8308::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), AP_Compass_IST8310::init(), AP_Compass_RM3100::init(), AP_Compass_LIS3MDL::init(), AP_Compass_QMC5883L::init(), AP_Compass_AK09916::init(), main(), AP_Compass_AK09916::probe_ICM20948(), AP_Arming::rc_checks_copter_sub(), and setup().
main()
int main (int argc, char * argv[])
Definition at line 35 of file eedump.c.
Variable Documentation
eeprom
uint8_t eeprom[0x1000]
Definition at line 8 of file eedump.c.
Referenced by main().
k_EEPROM_magic
const uint16_t k_EEPROM_magic = 0x5041 static
Definition at line 16 of file eedump.c.
Referenced by main().
k_EEPROM_revision
const uint16_t k_EEPROM_revision = 2 static
Definition at line 17 of file eedump.c.
k_key_sentinel
const uint8_t k_key_sentinel = 0xff static
Definition at line 25 of file eedump.c.
Referenced by main().