APM:Libraries: libraries/RC_Channel/examples/RC_Channel/RC_Channel.cpp File Reference
RC_Channel.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <RC_Channel/RC_Channel.h>
#include <RC_Channel/RC_Channels_VarInfo.h>
Classes
class RC_Channel_Example
class RC_Channels_Example
Macros
#define RC_CHANNELS_SUBCLASS RC_Channels_Example
#define RC_CHANNEL_SUBCLASS RC_Channel_Example
#define RC_CHANNELS_TO_DISPLAY 8
Functions
void setup ()
void loop ()
static void print_radio_values ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static RC_Channels_Example rc_channels
Macro Definition Documentation
RC_CHANNEL_SUBCLASS
#define RC_CHANNEL_SUBCLASS RC_Channel_Example
Definition at line 47 of file RC_Channel.cpp.
RC_CHANNELS_SUBCLASS
#define RC_CHANNELS_SUBCLASS RC_Channels_Example
Definition at line 46 of file RC_Channel.cpp.
RC_CHANNELS_TO_DISPLAY
#define RC_CHANNELS_TO_DISPLAY 8
Definition at line 55 of file RC_Channel.cpp.
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 91 of file RC_Channel.cpp.
print_radio_values()
static void print_radio_values () static
Definition at line 113 of file RC_Channel.cpp.
Referenced by setup().
setup()
void setup (void)
Definition at line 57 of file RC_Channel.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 19 of file RC_Channel.cpp.
Referenced by RC_Channel::do_aux_function_sprayer(), loop(), print_radio_values(), setup(), and RC_Channel::update().
rc_channels
RC_Channels_Example rc_channels static
Definition at line 51 of file RC_Channel.cpp.