APM:Libraries: libraries/AP_HAL/examples/RCInput/RCInput.cpp File Reference
RCInput.cpp File Reference
#include <AP_Common/AP_Common.h>
#include <AP_HAL/AP_HAL.h>
Macros
#define MAX_CHANNELS 16
Functions
void setup ()
void loop ()
void read_channels (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static uint8_t max_channels_display = 8
static uint16_t last_value [MAX_CHANNELS]
Macro Definition Documentation
MAX_CHANNELS
#define MAX_CHANNELS 16
Definition at line 20 of file RCInput.cpp.
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 71 of file RCInput.cpp.
read_channels()
void read_channels (void)
Definition at line 34 of file RCInput.cpp.
Referenced by RC_Channels::get_radio_in(), and loop().
setup()
void setup (void)
Definition at line 25 of file RCInput.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 18 of file RCInput.cpp.
Referenced by loop(), read_channels(), and setup().
last_value
uint16_t last_value[MAX_CHANNELS] static
Definition at line 23 of file RCInput.cpp.
Referenced by read_channels(), and SITL::Motor::update_servo().
max_channels_display
uint8_t max_channels_display = 8 static
Definition at line 22 of file RCInput.cpp.
Referenced by read_channels().