APM:Libraries: libraries/Filter/examples/LowPassFilter2p/LowPassFilter2p.cpp File Reference
LowPassFilter2p.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <Filter/Filter.h>
#include <Filter/LowPassFilter2p.h>
Functions
void loop ()
static void setup ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static LowPassFilter2pFloat low_pass_filter (800, 30)
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 24 of file LowPassFilter2p.cpp.
setup()
static void setup (void) static
Definition at line 18 of file LowPassFilter2p.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 12 of file LowPassFilter2p.cpp.
Referenced by loop(), and setup().
low_pass_filter
LowPassFilter2pFloat low_pass_filter(800, 30) static
Referenced by loop().