APM:Libraries: libraries/Filter/examples/Filter/Filter.cpp File Reference
Filter.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <Filter/Filter.h>
#include <Filter/ModeFilter.h>
#include <Filter/AverageFilter.h>
Functions
void setup ()
void loop ()
void readTemp ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
int16_t rangevalue [] = {31000, 31000, 50, 55, 60, 55, 10, 0, 31000}
ModeFilterInt16_Size5 mfilter (2)
AverageFilterUInt16_Size4 _temp_filter
butter50hz8_0 butter
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 61 of file Filter.cpp.
readTemp()
void readTemp ()
Definition at line 37 of file Filter.cpp.
Referenced by loop().
setup()
void setup (void)
Definition at line 27 of file Filter.cpp.
Variable Documentation
_temp_filter
AverageFilterUInt16_Size4 _temp_filter
Definition at line 23 of file Filter.cpp.
Referenced by readTemp().
butter
butter50hz8_0 butter
Definition at line 25 of file Filter.cpp.
Referenced by readTemp().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 15 of file Filter.cpp.
Referenced by loop(), readTemp(), and setup().
mfilter
ModeFilterInt16_Size5 mfilter(2)
rangevalue
int16_t rangevalue[] = {31000, 31000, 50, 55, 60, 55, 10, 0, 31000}
Definition at line 17 of file Filter.cpp.