APM:Libraries: libraries/AP_HAL_Linux/Flow_PX4.cpp File Reference
Flow_PX4.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "Flow_PX4.h"
#include <cmath>
#include <stdio.h>
#include <stdlib.h>
Functions
static uint32_t compute_diff (uint8_t *image, uint16_t offx, uint16_t offy, uint16_t row_size, uint8_t window_size)
Compute the average pixel gradient of all horizontal and vertical steps.
static uint32_t compute_sad (uint8_t *image1, uint8_t *image2, uint16_t off1x, uint16_t off1y, uint16_t off2x, uint16_t off2y, uint16_t row_size, uint16_t window_size)
Compute SAD of two pixel windows.
static uint32_t compute_subpixel (uint8_t *image1, uint8_t *image2, uint16_t off1x, uint16_t off1y, uint16_t off2x, uint16_t off2y, uint32_t *acc, uint16_t row_size, uint16_t window_size)
Compute SAD distances of subpixel shift of two pixel patterns.
Variables
const AP_HAL::HAL & hal
Function Documentation
compute_diff()
static uint32_t compute_diff (uint8_t * image, uint16_t offx, uint16_t offy, uint16_t row_size, uint8_t window_size) inline static
Compute the average pixel gradient of all horizontal and vertical steps.
Parameters
image ...
offX x coordinate of upper left corner of 8x8 pattern in image
offY y coordinate of upper left corner of 8x8 pattern in image
Definition at line 86 of file Flow_PX4.cpp.
Referenced by Linux::Flow_PX4::compute_flow().
compute_sad()
static uint32_t compute_sad (uint8_t * image1, uint8_t * image2, uint16_t off1x, uint16_t off1y, uint16_t off2x, uint16_t off2y, uint16_t row_size, uint16_t window_size) inline static
Compute SAD of two pixel windows.
Parameters
image1 ...
image2 ...
off1X x coordinate of upper left corner of pattern in image1
off1Y y coordinate of upper left corner of pattern in image1
off2X x coordinate of upper left corner of pattern in image2
off2Y y coordinate of upper left corner of pattern in image2
Definition at line 127 of file Flow_PX4.cpp.
Referenced by Linux::Flow_PX4::compute_flow().
compute_subpixel()
static uint32_t compute_subpixel (uint8_t * image1, uint8_t * image2, uint16_t off1x, uint16_t off1y, uint16_t off2x, uint16_t off2y, uint32_t * acc, uint16_t row_size, uint16_t window_size) inline static
Compute SAD distances of subpixel shift of two pixel patterns.
Parameters
image1 ...
image2 ...
off1X x coordinate of upper left corner of pattern in image1
off1Y y coordinate of upper left corner of pattern in image1
off2X x coordinate of upper left corner of pattern in image2
off2Y y coordinate of upper left corner of pattern in image2
acc array to store SAD distances for shift in every direction
Definition at line 160 of file Flow_PX4.cpp.
Referenced by Linux::Flow_PX4::compute_flow().
Variable Documentation
hal
const AP_HAL::HAL& hal
Definition at line 21 of file AC_PID_test.cpp.