APM:Libraries: libraries/GCS_MAVLink/GCS.h File Reference
GCS.h File Reference
Interface definition for the various Ground Control System.
#include <AP_HAL/AP_HAL.h>
#include <AP_Common/AP_Common.h>
#include "GCS_MAVLink.h"
#include <AP_Mission/AP_Mission.h>
#include <stdint.h>
#include "MAVLink_routing.h"
#include <AP_Avoidance/AP_Avoidance.h>
#include <AP_Frsky_Telem/AP_Frsky_Telem.h>
#include <AP_AdvancedFailsafe/AP_AdvancedFailsafe.h>
#include <AP_RTC/JitterCorrection.h>
#include <AP_Common/Bitmask.h>
#include <AP_Devo_Telem/AP_Devo_Telem.h>
#include <RC_Channel/RC_Channel.h>
#include <AP_Rally/AP_Rally.h>
Classes
class MissionItemProtocol
class MissionItemProtocol_Waypoints
class MissionItemProtocol_Rally
class GCS_MAVLINK
MAVLink transport control class.
struct GCS_MAVLINK::stream_entries
struct GCS_MAVLINK::deferred_message_t
struct GCS_MAVLINK::deferred_message_bucket_t
struct GCS_MAVLINK::pending_param_request
struct GCS_MAVLINK::pending_param_reply
class GCS
global GCS object
struct GCS::statustext_t
Macros
#define GCS_DEBUG_SEND_MESSAGE_TIMINGS 0
#define PAYLOAD_SIZE(chan, id) (GCS_MAVLINK::packet_overhead_chan(chan)+MAVLINK_MSG_ID_ ## id ## _LEN)
#define HAVE_PAYLOAD_SPACE(chan, id) (comm_get_txspace(chan) >= PAYLOAD_SIZE(chan, id))
#define CHECK_PAYLOAD_SIZE(id) if (comm_get_txspace(chan) < packet_overhead()+MAVLINK_MSG_ID_ ## id ## _LEN) return false
#define CHECK_PAYLOAD_SIZE2(id) if (!HAVE_PAYLOAD_SPACE(chan, id)) return false
#define MAV_STREAM_ENTRY(stream_name)
#define MAV_STREAM_TERMINATOR { (streams)0, nullptr, 0 }
Enumerations
enum ap_message : uint8_t {
MSG_HEARTBEAT, MSG_ATTITUDE, MSG_LOCATION, MSG_SYS_STATUS,
MSG_POWER_STATUS, MSG_MEMINFO, MSG_NAV_CONTROLLER_OUTPUT, MSG_CURRENT_WAYPOINT,
MSG_VFR_HUD, MSG_SERVO_OUTPUT_RAW, MSG_RC_CHANNELS, MSG_RC_CHANNELS_RAW,
MSG_RAW_IMU, MSG_SCALED_IMU, MSG_SCALED_IMU2, MSG_SCALED_IMU3,
MSG_SCALED_PRESSURE, MSG_SCALED_PRESSURE2, MSG_SCALED_PRESSURE3, MSG_SENSOR_OFFSETS,
MSG_GPS_RAW, MSG_GPS_RTK, MSG_GPS2_RAW, MSG_GPS2_RTK,
MSG_SYSTEM_TIME, MSG_SERVO_OUT, MSG_NEXT_MISSION_REQUEST_WAYPOINTS, MSG_NEXT_MISSION_REQUEST_RALLY,
MSG_NEXT_PARAM, MSG_FENCE_STATUS, MSG_AHRS, MSG_SIMSTATE,
MSG_AHRS2, MSG_AHRS3, MSG_HWSTATUS, MSG_WIND,
MSG_RANGEFINDER, MSG_DISTANCE_SENSOR, MSG_TERRAIN, MSG_BATTERY2,
MSG_CAMERA_FEEDBACK, MSG_MOUNT_STATUS, MSG_OPTICAL_FLOW, MSG_GIMBAL_REPORT,
MSG_MAG_CAL_PROGRESS, MSG_MAG_CAL_REPORT, MSG_EKF_STATUS_REPORT, MSG_LOCAL_POSITION,
MSG_PID_TUNING, MSG_VIBRATION, MSG_RPM, MSG_WHEEL_DISTANCE,
MSG_MISSION_ITEM_REACHED, MSG_POSITION_TARGET_GLOBAL_INT, MSG_POSITION_TARGET_LOCAL_NED, MSG_ADSB_VEHICLE,
MSG_BATTERY_STATUS, MSG_AOA_SSA, MSG_LANDING, MSG_ESC_TELEMETRY,
MSG_ORIGIN, MSG_HOME, MSG_NAMED_FLOAT, MSG_EXTENDED_SYS_STATE,
MSG_LAST
}
Functions
GCS & gcs ()
Detailed Description
Interface definition for the various Ground Control System.
Definition in file GCS.h.
Macro Definition Documentation
CHECK_PAYLOAD_SIZE
#define CHECK_PAYLOAD_SIZE (id) if (comm_get_txspace(chan) < packet_overhead()+MAVLINK_MSG_ID_ ## id ## _LEN) return false
Definition at line 26 of file GCS.h.
CHECK_PAYLOAD_SIZE2
#define CHECK_PAYLOAD_SIZE2 (id) if (!HAVE_PAYLOAD_SPACE(chan, id)) return false
Definition at line 27 of file GCS.h.
GCS_DEBUG_SEND_MESSAGE_TIMINGS
#define GCS_DEBUG_SEND_MESSAGE_TIMINGS 0
Definition at line 21 of file GCS.h.
HAVE_PAYLOAD_SPACE
#define HAVE_PAYLOAD_SPACE (chan, id) (comm_get_txspace(chan) >= PAYLOAD_SIZE(chan, id))
Definition at line 25 of file GCS.h.
MAV_STREAM_ENTRY
#define MAV_STREAM_ENTRY (stream_name)
Value:
{                                           \
        GCS_MAVLINK::stream_name,               \
        stream_name ## _msgs,                   \
        ARRAY_SIZE(stream_name ## _msgs)        \
    }
Definition at line 103 of file GCS.h.
MAV_STREAM_TERMINATOR
#define MAV_STREAM_TERMINATOR { (streams)0, nullptr, 0 }
Definition at line 109 of file GCS.h.
PAYLOAD_SIZE
#define PAYLOAD_SIZE (chan, id) (GCS_MAVLINK::packet_overhead_chan(chan)+MAVLINK_MSG_ID_ ## id ## _LEN)
Definition at line 24 of file GCS.h.
Enumeration Type Documentation
ap_message
enum ap_message : uint8_t
NOTE: to ensure we never block on sending MAVLink messages please keep each MSG_ to a single MAVLink message. If need be create new MSG_ IDs for additional messages on the same stream
Enumerator
MSG_HEARTBEAT
MSG_ATTITUDE
MSG_LOCATION
MSG_SYS_STATUS
MSG_POWER_STATUS
MSG_MEMINFO
MSG_NAV_CONTROLLER_OUTPUT
MSG_CURRENT_WAYPOINT
MSG_VFR_HUD
MSG_SERVO_OUTPUT_RAW
MSG_RC_CHANNELS
MSG_RC_CHANNELS_RAW
MSG_RAW_IMU
MSG_SCALED_IMU
MSG_SCALED_IMU2
MSG_SCALED_IMU3
MSG_SCALED_PRESSURE
MSG_SCALED_PRESSURE2
MSG_SCALED_PRESSURE3
MSG_SENSOR_OFFSETS
MSG_GPS_RAW
MSG_GPS_RTK
MSG_GPS2_RAW
MSG_GPS2_RTK
MSG_SYSTEM_TIME
MSG_SERVO_OUT
MSG_NEXT_MISSION_REQUEST_WAYPOINTS
MSG_NEXT_MISSION_REQUEST_RALLY
MSG_NEXT_PARAM
MSG_FENCE_STATUS
MSG_AHRS
MSG_SIMSTATE
MSG_AHRS2
MSG_AHRS3
MSG_HWSTATUS
MSG_WIND
MSG_RANGEFINDER
MSG_DISTANCE_SENSOR
MSG_TERRAIN
MSG_BATTERY2
MSG_CAMERA_FEEDBACK
MSG_MOUNT_STATUS
MSG_OPTICAL_FLOW
MSG_GIMBAL_REPORT
MSG_MAG_CAL_PROGRESS
MSG_MAG_CAL_REPORT
MSG_EKF_STATUS_REPORT
MSG_LOCAL_POSITION
MSG_PID_TUNING
MSG_VIBRATION
MSG_RPM
MSG_WHEEL_DISTANCE
MSG_MISSION_ITEM_REACHED
MSG_POSITION_TARGET_GLOBAL_INT
MSG_POSITION_TARGET_LOCAL_NED
MSG_ADSB_VEHICLE
MSG_BATTERY_STATUS
MSG_AOA_SSA
MSG_LANDING
MSG_ESC_TELEMETRY
MSG_ORIGIN
MSG_HOME
MSG_NAMED_FLOAT
MSG_EXTENDED_SYS_STATE
MSG_LAST
Definition at line 34 of file GCS.h.
Function Documentation
gcs()
GCS& gcs ()
Definition at line 5004 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_save_cfg(), ChibiOS::RCInput::_timer_tick(), AP_Motors::add_motor_num(), lua_scripts::atpanic(), AP_BoardConfig::board_init_safety(), AP_GPS_SBF::broadcast_configuration_failure_reason(), AP_GPS_UBLOX::broadcast_configuration_failure_reason(), AP_GPS::broadcast_first_configuration_failure_reason(), AP_GPS_Backend::broadcast_gps_type(), AP_Landing_Deepstall::build_approach_path(), AP_Frsky_Telem::calc_ap_status(), AP_Frsky_Telem::calc_param(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), CompassCalibrator::calculate_orientation(), AP_WindVane_Analog::calibrate(), AP_WindVane_ModernDevice::calibrate(), AP_WindVane_Backend::calibrate(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), AP_AdvancedFailsafe::check(), AP_Tuning::check_controller_error(), SoaringController::check_cruise_criteria(), AP_Arming::check_failed(), AP_BattMonitor::check_failsafes(), AP_Tuning::check_input(), AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), AP_Tuning::check_selector_switch(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), NavEKF2_core::checkAttitudeAlignmentStatus(), NavEKF3_core::checkAttitudeAlignmentStatus(), NavEKF2::checkLaneSwitch(), NavEKF3::checkLaneSwitch(), AP_BattMonitor::checkPoweringOff(), CompassLearn::CompassLearn(), AC_AutoTune::control_attitude(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AP_SmartRTL::deactivate(), AP_LandingGear::deploy(), RC_Channel::do_aux_function(), AC_AutoTune::do_gcs_announcements(), AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), AP_OSD_Screen::draw_throttle(), AP_ICEngine::engine_control(), NavEKF3_core::FuseBodyVel(), NavEKF3_core::FuseOptFlow(), AP_AdvancedFailsafe::gcs_terminate(), AP_Gripper_Servo::grab(), AP_Gripper_EPM::grab(), GCS_MAVLINK::handle_command_flash_bootloader(), GCS_MAVLINK::handle_mission_clear_all(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_request(), GCS_MAVLINK::handle_mission_request_int(), GCS_MAVLINK::handle_mission_request_list(), MissionItemProtocol::handle_mission_write_partial_list(), GCS_MAVLINK::handle_mission_write_partial_list(), AP_ADSB::handle_out_cfg(), GCS_MAVLINK::handle_timesync(), AP_ADSB::handle_transceiver_report(), AP_Gripper_Servo::has_state_pwm(), AP_Mission::increment_jump_times_run(), AP_MotorsTri::init(), AP_SmartRTL::init(), AP_Airspeed::init(), AP_Compass_AK09916::init(), AP_Frsky_Telem::init(), AP_Logger::Init(), AP_InertialSensor::BatchSampler::init(), AP_Mission::init(), RC_Channel::init_aux_function(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Mission::jump_to_abort_landing_sequence(), AP_Mission::jump_to_landing_sequence(), lua_scripts::load_all_scripts_in_dir(), lua_scripts::load_script(), AP_AHRS_DCM::load_watchdog_home(), AP_Camera::log_picture(), GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame(), AP_Tuning::next_parameter(), AP_Landing_Deepstall::override_servos(), AP_MotorsHeli::parameter_check(), AP_MotorsHeli_Dual::parameter_check(), AP_MotorsHeli_Single::parameter_check(), AP_Landing_Deepstall::predict_travel_distance(), AP_GPS_SBF::prepare_for_arming(), AP_Compass_AK09916::probe_ICM20948(), AP_GPS_SBF::process_message(), AP_BattMonitor_FuelFlow::read(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AP_Gripper_Servo::release(), AP_Gripper_EPM::release(), AP_Parachute::release(), GCS_MAVLINK::requesting_mission_items(), AP_AHRS_DCM::reset(), AP_Landing::restart_landing_sequence(), AP_LandingGear::retract(), AC_AutoTune::run(), lua_scripts::run(), lua_scripts::run_next_script(), AP_Param::save_sync(), AP_Airspeed::send_airspeed_calibration(), AP_Frsky_Telem::send_D(), AP_DEVO_Telem::send_frames(), GCS_MAVLINK::send_heartbeat(), GCS::send_named_float(), AP_Param::send_parameter(), GCS::send_parameter_value(), GCS_MAVLINK::send_power_status(), AP_Button::send_report(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), AC_AutoTune::send_step_string(), GCS_MAVLINK::send_sys_status(), GCS_MAVLINK::send_textv(), AP_BoardConfig::sensor_config_error(), AP_Frsky_Telem::sensor_status_flags(), AP_AHRS_DCM::set_home(), GCS_MAVLINK::set_mavlink_message_id_interval(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), setup(), NavEKF3_core::setup_core(), AP_AccelCal::start(), AP_Mission::start_command(), AP_Mission::start_command_do_gripper(), GCS_MAVLINK::try_send_message(), GCS_MAVLINK::try_send_mission_message(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_do_land(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), CompassLearn::update(), AP_RPM_Pin::update(), AP_ICEngine::update(), SITL::Parachute::update(), AP_Airspeed::update(), AP_WindVane::update(), AP_ADSB::update(), AP_Airspeed::update_calibration(), AC_AutoTune::update_gcs(), AP::PerfInfo::update_logging(), GCS::update_passthru(), AP_WheelEncoder_Quadrature::update_pin(), GCS_MAVLINK::update_receive(), GCS_MAVLINK::update_send(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), AP_Camera::update_trigger(), NavEKF2_core::UpdateFilter(), and AP_Landing::verify_land().