APM:Libraries: libraries/GCS_MAVLink/GCS_Common.cpp File Reference
GCS_Common.cpp File Reference
#include <AP_AHRS/AP_AHRS.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_Arming/AP_Arming.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_Logger/AP_Logger.h>
#include <AP_OpticalFlow/AP_OpticalFlow.h>
#include <AP_Vehicle/AP_Vehicle.h>
#include <AP_RangeFinder/RangeFinder_Backend.h>
#include <AP_Airspeed/AP_Airspeed.h>
#include <AP_Camera/AP_Camera.h>
#include <AP_Gripper/AP_Gripper.h>
#include <AP_BLHeli/AP_BLHeli.h>
#include <AP_RSSI/AP_RSSI.h>
#include <AP_RTC/AP_RTC.h>
#include <AP_Scheduler/AP_Scheduler.h>
#include <AP_SerialManager/AP_SerialManager.h>
#include <AP_Mount/AP_Mount.h>
#include <AP_Common/AP_FWVersion.h>
#include <AP_VisualOdom/AP_VisualOdom.h>
#include <AP_OpticalFlow/OpticalFlow.h>
#include <AP_Baro/AP_Baro.h>
#include "GCS.h"
#include <stdio.h>
#include <SITL/SITL.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <AP_GPS/AP_GPS.h>
Functions
GCS & gcs ()
Variables
const AP_HAL::HAL & hal
Function Documentation
gcs()
GCS& gcs ()
Definition at line 5004 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_save_cfg(), ChibiOS::RCInput::_timer_tick(), AP_Motors::add_motor_num(), lua_scripts::atpanic(), AP_BoardConfig::board_init_safety(), AP_GPS_SBF::broadcast_configuration_failure_reason(), AP_GPS_UBLOX::broadcast_configuration_failure_reason(), AP_GPS::broadcast_first_configuration_failure_reason(), AP_GPS_Backend::broadcast_gps_type(), AP_Landing_Deepstall::build_approach_path(), AP_Frsky_Telem::calc_ap_status(), AP_Frsky_Telem::calc_param(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), CompassCalibrator::calculate_orientation(), AP_WindVane_Analog::calibrate(), AP_WindVane_ModernDevice::calibrate(), AP_WindVane_Backend::calibrate(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), AP_AdvancedFailsafe::check(), AP_Tuning::check_controller_error(), SoaringController::check_cruise_criteria(), AP_Arming::check_failed(), AP_BattMonitor::check_failsafes(), AP_Tuning::check_input(), AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), AP_Tuning::check_selector_switch(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), NavEKF2_core::checkAttitudeAlignmentStatus(), NavEKF3_core::checkAttitudeAlignmentStatus(), NavEKF2::checkLaneSwitch(), NavEKF3::checkLaneSwitch(), AP_BattMonitor::checkPoweringOff(), CompassLearn::CompassLearn(), AC_AutoTune::control_attitude(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AP_SmartRTL::deactivate(), AP_LandingGear::deploy(), RC_Channel::do_aux_function(), AC_AutoTune::do_gcs_announcements(), AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), AP_OSD_Screen::draw_throttle(), AP_ICEngine::engine_control(), NavEKF3_core::FuseBodyVel(), NavEKF3_core::FuseOptFlow(), AP_AdvancedFailsafe::gcs_terminate(), AP_Gripper_Servo::grab(), AP_Gripper_EPM::grab(), GCS_MAVLINK::handle_command_flash_bootloader(), GCS_MAVLINK::handle_mission_clear_all(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_request(), GCS_MAVLINK::handle_mission_request_int(), GCS_MAVLINK::handle_mission_request_list(), MissionItemProtocol::handle_mission_write_partial_list(), GCS_MAVLINK::handle_mission_write_partial_list(), AP_ADSB::handle_out_cfg(), GCS_MAVLINK::handle_timesync(), AP_ADSB::handle_transceiver_report(), AP_Gripper_Servo::has_state_pwm(), AP_Mission::increment_jump_times_run(), AP_MotorsTri::init(), AP_SmartRTL::init(), AP_Airspeed::init(), AP_Compass_AK09916::init(), AP_Frsky_Telem::init(), AP_Logger::Init(), AP_InertialSensor::BatchSampler::init(), AP_Mission::init(), RC_Channel::init_aux_function(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Mission::jump_to_abort_landing_sequence(), AP_Mission::jump_to_landing_sequence(), lua_scripts::load_all_scripts_in_dir(), lua_scripts::load_script(), AP_AHRS_DCM::load_watchdog_home(), AP_Camera::log_picture(), GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame(), AP_Tuning::next_parameter(), AP_Landing_Deepstall::override_servos(), AP_MotorsHeli::parameter_check(), AP_MotorsHeli_Dual::parameter_check(), AP_MotorsHeli_Single::parameter_check(), AP_Landing_Deepstall::predict_travel_distance(), AP_GPS_SBF::prepare_for_arming(), AP_Compass_AK09916::probe_ICM20948(), AP_GPS_SBF::process_message(), AP_BattMonitor_FuelFlow::read(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AP_Gripper_Servo::release(), AP_Gripper_EPM::release(), AP_Parachute::release(), GCS_MAVLINK::requesting_mission_items(), AP_AHRS_DCM::reset(), AP_Landing::restart_landing_sequence(), AP_LandingGear::retract(), AC_AutoTune::run(), lua_scripts::run(), lua_scripts::run_next_script(), AP_Param::save_sync(), AP_Airspeed::send_airspeed_calibration(), AP_Frsky_Telem::send_D(), AP_DEVO_Telem::send_frames(), GCS_MAVLINK::send_heartbeat(), GCS::send_named_float(), AP_Param::send_parameter(), GCS::send_parameter_value(), GCS_MAVLINK::send_power_status(), AP_Button::send_report(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), AC_AutoTune::send_step_string(), GCS_MAVLINK::send_sys_status(), GCS_MAVLINK::send_textv(), AP_BoardConfig::sensor_config_error(), AP_Frsky_Telem::sensor_status_flags(), AP_AHRS_DCM::set_home(), GCS_MAVLINK::set_mavlink_message_id_interval(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), setup(), NavEKF3_core::setup_core(), AP_AccelCal::start(), AP_Mission::start_command(), AP_Mission::start_command_do_gripper(), GCS_MAVLINK::try_send_message(), GCS_MAVLINK::try_send_mission_message(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_do_land(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), CompassLearn::update(), AP_RPM_Pin::update(), AP_ICEngine::update(), SITL::Parachute::update(), AP_Airspeed::update(), AP_WindVane::update(), AP_ADSB::update(), AP_Airspeed::update_calibration(), AC_AutoTune::update_gcs(), AP::PerfInfo::update_logging(), GCS::update_passthru(), AP_WheelEncoder_Quadrature::update_pin(), GCS_MAVLINK::update_receive(), GCS_MAVLINK::update_send(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), AP_Camera::update_trigger(), NavEKF2_core::UpdateFilter(), and AP_Landing::verify_land().
Variable Documentation
hal
const AP_HAL::HAL& hal
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 21 of file AC_PID_test.cpp.
Referenced by GCS_MAVLINK::_set_mode_common(), GCS_MAVLINK::do_try_send_message(), GCS_MAVLINK::find_next_bucket_to_send(), GCS_MAVLINK::handle_command_flash_bootloader(), GCS_MAVLINK::handle_command_int(), GCS_MAVLINK::handle_command_long(), GCS_MAVLINK::handle_command_preflight_calibration(), GCS_MAVLINK::handle_command_preflight_can(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_statustext(), GCS_MAVLINK::init(), GCS_MAVLINK::send_banner(), GCS_MAVLINK::send_hwstatus(), GCS_MAVLINK::send_meminfo(), GCS_MAVLINK::send_power_status(), GCS_MAVLINK::send_servo_output_raw(), GCS_MAVLINK::send_textv(), GCS_MAVLINK::setup_uart(), GCS_MAVLINK::telemetry_delayed(), GCS::update_passthru(), GCS_MAVLINK::update_receive(), GCS_MAVLINK::update_send(), and GCS_MAVLINK::zero_rc_outputs().