APM:Libraries: libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp File Reference
GPS_AUTO_test.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_GPS/AP_GPS.h>
#include <GCS_MAVLink/GCS_Dummy.h>
#include <AP_Notify/AP_Notify.h>
#include <AP_Notify/AP_BoardLED.h>
#include <AP_SerialManager/AP_SerialManager.h>
#include <AP_BoardConfig/AP_BoardConfig.h>
Functions
void setup ()
void loop ()
void print_latlon (AP_HAL::BetterStream *s, int32_t lat_or_lon)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static AP_BoardConfig board_config
AP_BoardLED board_led
GCS_Dummy _gcs
static AP_GPS gps
static AP_SerialManager serial_manager
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 88 of file GPS_AUTO_test.cpp.
print_latlon()
void print_latlon (AP_HAL::BetterStream * s, int32_t lat_or_lon)
Definition at line 69 of file GPS_AUTO_test.cpp.
Referenced by loop().
setup()
void setup (void)
Definition at line 50 of file GPS_AUTO_test.cpp.
Variable Documentation
_gcs
GCS_Dummy _gcs
Definition at line 38 of file GPS_AUTO_test.cpp.
board_config
AP_BoardConfig board_config static
Definition at line 32 of file GPS_AUTO_test.cpp.
Referenced by setup().
board_led
AP_BoardLED board_led
Definition at line 35 of file GPS_AUTO_test.cpp.
Referenced by setup().
gps
AP_GPS gps static
Definition at line 45 of file GPS_AUTO_test.cpp.
Referenced by loop(), and setup().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 30 of file GPS_AUTO_test.cpp.
Referenced by loop(), and setup().
serial_manager
AP_SerialManager serial_manager static
Definition at line 47 of file GPS_AUTO_test.cpp.
Referenced by setup().