APM:Libraries: libraries/AP_HAL_SITL/HAL_SITL_Class.cpp File Reference
HAL_SITL_Class.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include "AP_HAL_SITL.h"
#include "AP_HAL_SITL_Namespace.h"
#include "HAL_SITL_Class.h"
#include "Scheduler.h"
#include "AnalogIn.h"
#include "UARTDriver.h"
#include "Storage.h"
#include "RCInput.h"
#include "RCOutput.h"
#include "GPIO.h"
#include "SITL_State.h"
#include "Util.h"
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_HAL_Empty/AP_HAL_Empty.h>
#include <AP_HAL_Empty/AP_HAL_Empty_Private.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_Logger/AP_Logger.h>
Functions
static bool watchdog_save (const uint32_t *data, uint32_t nwords)
static bool watchdog_load (uint32_t *data, uint32_t nwords)
static void sig_alrm (int signum)
Variables
static Storage sitlStorage
static SITL_State sitlState
static Empty::I2CDeviceManager i2c_mgr_instance
static Empty::SPIDeviceManager emptySPI
static Empty::OpticalFlow emptyOpticalFlow
static Empty::Flash emptyFlash
static UARTDriver sitlUart0Driver (0, &sitlState)
static UARTDriver sitlUart1Driver (1, &sitlState)
static UARTDriver sitlUart2Driver (2, &sitlState)
static UARTDriver sitlUart3Driver (3, &sitlState)
static UARTDriver sitlUart4Driver (4, &sitlState)
static UARTDriver sitlUart5Driver (5, &sitlState)
static UARTDriver sitlUart6Driver (6, &sitlState)
static char * new_argv [100]
Function Documentation
sig_alrm()
static void sig_alrm (int signum) static
Definition at line 115 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
watchdog_load()
static bool watchdog_load (uint32_t * data, uint32_t nwords) static
Definition at line 101 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
watchdog_save()
static bool watchdog_save (const uint32_t * data, uint32_t nwords) static
Definition at line 85 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
Variable Documentation
emptyFlash
Empty::Flash emptyFlash static
Definition at line 43 of file HAL_SITL_Class.cpp.
emptyOpticalFlow
Empty::OpticalFlow emptyOpticalFlow static
Definition at line 42 of file HAL_SITL_Class.cpp.
emptySPI
Empty::SPIDeviceManager emptySPI static
Definition at line 41 of file HAL_SITL_Class.cpp.
i2c_mgr_instance
Empty::I2CDeviceManager i2c_mgr_instance static
Definition at line 40 of file HAL_SITL_Class.cpp.
new_argv
char* new_argv[100] static
Definition at line 80 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::actually_reboot(), HAL_SITL::run(), and sig_alrm().
sitlState
static Util utilInstance & sitlState static
Definition at line 32 of file HAL_SITL_Class.cpp.
Referenced by HALSITL::UARTDriver::UARTDriver().
sitlStorage
Storage sitlStorage static
Definition at line 31 of file HAL_SITL_Class.cpp.
sitlUart0Driver
UARTDriver sitlUart0Driver(0, &sitlState) static
sitlUart1Driver
UARTDriver sitlUart1Driver(1, &sitlState) static
sitlUart2Driver
UARTDriver sitlUart2Driver(2, &sitlState) static
sitlUart3Driver
UARTDriver sitlUart3Driver(3, &sitlState) static
sitlUart4Driver
UARTDriver sitlUart4Driver(4, &sitlState) static
sitlUart5Driver
UARTDriver sitlUart5Driver(5, &sitlState) static
sitlUart6Driver
UARTDriver sitlUart6Driver(6, &sitlState) static