APM:Libraries: libraries/AP_HAL_Linux/HAL_Linux_Class.cpp File Reference
HAL_Linux_Class.cpp File Reference
#include "HAL_Linux_Class.h"
#include <assert.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL/utility/RCOutput_Tap.h>
#include <AP_HAL/utility/getopt_cpp.h>
#include <AP_HAL_Empty/AP_HAL_Empty.h>
#include <AP_HAL_Empty/AP_HAL_Empty_Private.h>
#include <AP_Module/AP_Module.h>
#include "AnalogIn_ADS1115.h"
#include "AnalogIn_IIO.h"
#include "AnalogIn_Navio2.h"
#include "GPIO.h"
#include "I2CDevice.h"
#include "OpticalFlow_Onboard.h"
#include "RCInput.h"
#include "RCInput_AioPRU.h"
#include "RCInput_Navio2.h"
#include "RCInput_PRU.h"
#include "RCInput_RPI.h"
#include "RCInput_SoloLink.h"
#include "RCInput_UART.h"
#include "RCInput_UDP.h"
#include "RCInput_Multi.h"
#include "RCInput_ZYNQ.h"
#include "RCInput_RCProtocol.h"
#include "RCOutput_AioPRU.h"
#include "RCOutput_Bebop.h"
#include "RCOutput_Disco.h"
#include "RCOutput_PCA9685.h"
#include "RCOutput_PRU.h"
#include "RCOutput_Sysfs.h"
#include "RCOutput_ZYNQ.h"
#include "SPIDevice.h"
#include "SPIUARTDriver.h"
#include "Scheduler.h"
#include "Storage.h"
#include "UARTDriver.h"
#include "Util.h"
#include "Util_RPI.h"
Functions
void _usage (void)
Variables
static UtilRPI utilInstance
static UARTDriver uartADriver (true)
static UARTDriver uartCDriver (false)
static UARTDriver uartDDriver (false)
static UARTDriver uartEDriver (false)
static UARTDriver uartFDriver (false)
static UARTDriver uartGDriver (false)
static I2CDeviceManager i2c_mgr_instance
static SPIDeviceManager spi_mgr_instance
static SPIUARTDriver uartBDriver
static AnalogIn_ADS1115 analogIn
static Storage storageDriver
static GPIO_BBB gpioDriver
static RCInput_PRU rcinDriver
static RCOutput_PRU rcoutDriver
static Scheduler schedulerInstance
static OpticalFlow_Onboard opticalFlow
static Empty::Flash flashDriver
static HAL_Linux halInstance
Function Documentation
_usage()
void _usage (void)
Definition at line 238 of file HAL_Linux_Class.cpp.
Referenced by HALSITL::SITL_State::_parse_command_line(), and HAL_Linux::run().
Variable Documentation
analogIn
AnalogIn_ADS1115 analogIn static
Definition at line 85 of file HAL_Linux_Class.cpp.
flashDriver
Empty::Flash flashDriver static
Definition at line 212 of file HAL_Linux_Class.cpp.
gpioDriver
GPIO_BBB gpioDriver static
Definition at line 109 of file HAL_Linux_Class.cpp.
halInstance
HAL_Linux halInstance static
Definition at line 395 of file HAL_Linux_Class.cpp.
Referenced by HAL_Linux::exit_signal_handler().
i2c_mgr_instance
I2CDeviceManager i2c_mgr_instance static
Definition at line 70 of file HAL_Linux_Class.cpp.
opticalFlow
OpticalFlow_Onboard opticalFlow static
Definition at line 207 of file HAL_Linux_Class.cpp.
rcinDriver
RCInput_PRU rcinDriver static
Definition at line 134 of file HAL_Linux_Class.cpp.
rcoutDriver
RCOutput_PRU rcoutDriver static
Definition at line 168 of file HAL_Linux_Class.cpp.
schedulerInstance
Scheduler schedulerInstance static
Definition at line 204 of file HAL_Linux_Class.cpp.
spi_mgr_instance
SPIDeviceManager spi_mgr_instance static
Definition at line 71 of file HAL_Linux_Class.cpp.
storageDriver
Storage storageDriver static
Definition at line 99 of file HAL_Linux_Class.cpp.
uartADriver
UARTDriver uartADriver(true) static
Referenced by HAL_Linux::run().
uartBDriver
SPIUARTDriver uartBDriver static
Definition at line 76 of file HAL_Linux_Class.cpp.
Referenced by HAL_Linux::run().
uartCDriver
UARTDriver uartCDriver(false) static
Referenced by HAL_Linux::run().
uartDDriver
UARTDriver uartDDriver(false) static
Referenced by HAL_Linux::run().
uartEDriver
UARTDriver uartEDriver(false) static
Referenced by HAL_Linux::run().
uartFDriver
UARTDriver uartFDriver(false) static
Referenced by HAL_Linux::run().
uartGDriver
UARTDriver uartGDriver(false) static
Referenced by HAL_Linux::run().
utilInstance
UtilRPI utilInstance static
Definition at line 57 of file HAL_Linux_Class.cpp.
Referenced by HAL_Linux::run().