APM:Libraries: libraries/AP_InertialSensor/examples/INS_generic/INS_generic.cpp File Reference
INS_generic.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_InertialSensor/AP_InertialSensor.h>
Functions
static void display_offsets_and_scaling ()
static void run_test ()
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static AP_InertialSensor ins
static AP_BoardConfig BoardConfig
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
display_offsets_and_scaling()
static void display_offsets_and_scaling () static
Definition at line 77 of file INS_generic.cpp.
Referenced by loop(), and setup().
loop()
void loop (void)
Definition at line 42 of file INS_generic.cpp.
run_test()
static void run_test () static
Definition at line 98 of file INS_generic.cpp.
Referenced by loop().
setup()
void setup (void)
Definition at line 22 of file INS_generic.cpp.
Variable Documentation
BoardConfig
AP_BoardConfig BoardConfig static
Definition at line 17 of file INS_generic.cpp.
Referenced by setup().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 9 of file INS_generic.cpp.
Referenced by display_offsets_and_scaling(), loop(), run_test(), and setup().
ins
AP_InertialSensor ins static
Definition at line 11 of file INS_generic.cpp.
Referenced by display_offsets_and_scaling(), run_test(), and setup().