APM:Libraries: libraries/AP_Scripting/lua/src/lauxlib.c File Reference
lauxlib.c File Reference
#include "lprefix.h"
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Classes
struct UBox
struct LoadF
struct LoadS
Macros
#define lauxlib_c
#define LUA_LIB
#define LEVELS1 10 /* size of the first part of the stack */
#define LEVELS2 11 /* size of the second part of the stack */
#define l_inspectstat(stat, what) /* no op */
#define buffonstack(B) ((B)->b != (B)->initb)
#define freelist 0
Typedefs
typedef struct UBox UBox
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Functions
static int findfield (lua_State *L, int objidx, int level)
static int pushglobalfuncname (lua_State *L, lua_Debug *ar)
static void pushfuncname (lua_State *L, lua_Debug *ar)
static int lastlevel (lua_State *L)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API int luaL_argerror (lua_State *L, int arg, const char *extramsg)
static int typeerror (lua_State *L, int arg, const char *tname)
static void tag_error (lua_State *L, int arg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API int luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[])
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int arg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int arg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int arg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int arg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int arg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int arg, lua_Number def)
static void interror (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int arg, lua_Integer def)
static void * resizebox (lua_State *L, int idx, size_t newsize)
static int boxgc (lua_State *L)
static void * newbox (lua_State *L, size_t newsize)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
static int skipBOM (LoadF *lf)
static int skipcomment (LoadF *lf, int *cp)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t size, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API lua_Integer luaL_len (lua_State *L, int idx)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
static void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
static int panic (lua_State *L)
LUALIB_API lua_State * luaL_newstate (void)
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver, size_t sz)
Macro Definition Documentation
buffonstack
#define buffonstack (B) ((B)->b != (B)->initb)
Definition at line 499 of file lauxlib.c.
freelist
#define freelist 0
Definition at line 592 of file lauxlib.c.
l_inspectstat
#define l_inspectstat (stat, what) /* no op */
Definition at line 267 of file lauxlib.c.
lauxlib_c
#define lauxlib_c
Definition at line 7 of file lauxlib.c.
LEVELS1
#define LEVELS1 10 /* size of the first part of the stack */
Definition at line 37 of file lauxlib.c.
LEVELS2
#define LEVELS2 11 /* size of the second part of the stack */
Definition at line 38 of file lauxlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lauxlib.c.
Typedef Documentation
LoadF
typedef struct LoadF LoadF
LoadS
typedef struct LoadS LoadS
UBox
typedef struct UBox UBox
Function Documentation
boxgc()
static int boxgc (lua_State * L) static
Definition at line 476 of file lauxlib.c.
Referenced by newbox().
errfile()
static int errfile (lua_State * L, const char * what, int fnameindex) static
Definition at line 660 of file lauxlib.c.
Referenced by luaL_loadfilex().
findfield()
static int findfield (lua_State * L, int objidx, int level) static
Definition at line 46 of file lauxlib.c.
Referenced by pushglobalfuncname().
getF()
static const char* getF (lua_State * L, void * ud, size_t * size) static
Definition at line 642 of file lauxlib.c.
Referenced by luaL_loadfilex().
getS()
static const char* getS (lua_State * L, void * ud, size_t * size) static
Definition at line 745 of file lauxlib.c.
Referenced by luaL_loadbufferx().
interror()
static void interror (lua_State * L, int arg) static
Definition at line 422 of file lauxlib.c.
Referenced by luaL_checkinteger().
l_alloc()
static void* l_alloc (void * ud, void * ptr, size_t osize, size_t nsize) static
Definition at line 1008 of file lauxlib.c.
Referenced by luaL_newstate().
lastlevel()
static int lastlevel (lua_State * L) static
Definition at line 110 of file lauxlib.c.
Referenced by luaL_traceback().
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 528 of file lauxlib.c.
Referenced by add_s(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), str_gsub(), str_pack(), tconcat(), and writer().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 537 of file lauxlib.c.
Referenced by addquoted(), and luaL_gsub().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 558 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), addliteral(), findloader(), searchpath(), str_format(), and utfchar().
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int arg, const char * extramsg)
Definition at line 164 of file lauxlib.c.
Referenced by addliteral(), AP_AHRS_get_gyro(), AP_AHRS_get_hagl(), AP_AHRS_get_home(), AP_AHRS_get_position(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_groundspeed_vector(), AP_AHRS_home_is_set(), AP_AHRS_prearm_healthy(), AP_AHRS_wind_estimate(), AP_BattMonitor_capacity_remaining_pct(), AP_BattMonitor_consumed_mah(), AP_BattMonitor_consumed_wh(), AP_BattMonitor_current_amps(), AP_BattMonitor_get_temperature(), AP_BattMonitor_has_consumed_energy(), AP_BattMonitor_has_current(), AP_BattMonitor_has_failsafed(), AP_BattMonitor_healthy(), AP_BattMonitor_num_instances(), AP_BattMonitor_overpower_detected(), AP_BattMonitor_pack_capacity_mah(), AP_BattMonitor_voltage(), AP_BattMonitor_voltage_resting_estimate(), AP_GPS_all_configured(), AP_GPS_first_unconfigured_gps(), AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_num_sensors(), AP_GPS_primary_sensor(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), AP_GPS_vertical_accuracy(), AP_Notify_play_tune(), AP_Relay_enabled(), AP_Relay_off(), AP_Relay_on(), AP_Relay_toggle(), AP_Terrain_enabled(), AP_Terrain_height_above_terrain(), AP_Terrain_height_amsl(), AP_Terrain_height_relative_home_equivalent(), AP_Terrain_height_terrain_difference_home(), AP_Terrain_status(), binding_argcheck(), checkoption(), coerce_to_uint32_t(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), GCS_send_text(), getdetails(), interror(), Location_lat(), Location_lng(), Location_loiter_xtrack(), Location_origin_alt(), Location_relative_alt(), Location_terrain_alt(), luaL_checkany(), luaL_checkoption(), RangeFinder_num_sensors(), str_format(), str_packsize(), str_unpack(), typeerror(), uint32_t___tostring(), uint32_t_tofloat(), uint32_t_toint(), Vector2f_x(), Vector2f_y(), Vector3f_x(), Vector3f_y(), and Vector3f_z().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 569 of file lauxlib.c.
Referenced by findloader(), luaL_buffinitsize(), luaL_gsub(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_buffinitsize()
LUALIB_API char* luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 577 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 788 of file lauxlib.c.
Referenced by luaL_tolstring(), and msghandler().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int arg)
Definition at line 384 of file lauxlib.c.
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), db_setuservalue(), io_type(), luaB_assert(), luaB_getmetatable(), luaB_ipairs(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), math_toint(), math_type(), and pairsmeta().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int arg)
Definition at line 430 of file lauxlib.c.
Referenced by AP_BattMonitor_capacity_remaining_pct(), AP_BattMonitor_consumed_mah(), AP_BattMonitor_consumed_wh(), AP_BattMonitor_current_amps(), AP_BattMonitor_get_temperature(), AP_BattMonitor_has_consumed_energy(), AP_BattMonitor_has_current(), AP_BattMonitor_healthy(), AP_BattMonitor_overpower_detected(), AP_BattMonitor_pack_capacity_mah(), AP_BattMonitor_voltage(), AP_BattMonitor_voltage_resting_estimate(), AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), AP_GPS_vertical_accuracy(), AP_Relay_enabled(), AP_Relay_off(), AP_Relay_on(), AP_Relay_toggle(), auxupvalue(), byteoffset(), checkupval(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), GCS_send_text(), ipairsaux(), l_checktime(), Location_lat(), Location_lng(), lua_servo_set_output_pwm(), luaB_select(), luaB_tonumber(), luaL_optinteger(), math_random(), math_ult(), pushutfchar(), str_char(), str_format(), str_pack(), str_rep(), str_sub(), tinsert(), tmove(), and unpack().
luaL_checklstring()
LUALIB_API const char* luaL_checklstring (lua_State * L, int arg, size_t * len)
Definition at line 390 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), g_write(), gmatch(), iter_aux(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_pack(), str_rep(), str_reverse(), str_sub(), str_unpack(), str_upper(), and utflen().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int arg)
Definition at line 408 of file lauxlib.c.
Referenced by AP_Terrain_height_relative_home_equivalent(), Location_offset(), lua_servo_set_output_pwm(), luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_ceil(), math_cos(), math_deg(), math_exp(), math_floor(), math_fmod(), math_log(), math_modf(), math_rad(), math_randomseed(), math_sin(), math_sqrt(), math_tan(), lua_scripts::run_next_script(), str_format(), str_pack(), Vector2f_x(), Vector2f_y(), Vector3f_x(), Vector3f_y(), and Vector3f_z().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int arg, const char * def, const char *const lst[])
Definition at line 348 of file lauxlib.c.
Referenced by f_seek(), luaB_collectgarbage(), and os_setlocale().
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * msg)
Definition at line 368 of file lauxlib.c.
Referenced by codepoint(), g_read(), generic_reader(), io_readline(), l_print(), load_boxed_numerics(), load_generated_bindings(), luaL_setfuncs(), luaL_traceback(), new_Location(), new_uint32_t(), new_Vector2f(), new_Vector3f(), push_captures(), pushargs(), str_byte(), and str_unpack().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int arg, int t)
Definition at line 378 of file lauxlib.c.
Referenced by auxupvalue(), checktab(), checkupval(), db_sethook(), db_setuservalue(), luaB_cocreate(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaB_tonumber(), luaB_xpcall(), os_time(), sort(), and str_dump().
luaL_checkudata()
LUALIB_API void* luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 333 of file lauxlib.c.
Referenced by AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_time_week_ms(), check_Location(), check_uint32_t(), check_Vector2f(), check_Vector3f(), uint32_t___tostring(), uint32_t_tofloat(), and uint32_t_toint().
luaL_checkversion_()
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver, size_t sz)
Definition at line 1033 of file lauxlib.c.
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 223 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), byteoffset(), capture_to_close(), check_arguments(), check_capture(), checkload(), checkstack(), classend(), codepoint(), findfile(), findloader(), generic_reader(), getfield(), getiofile(), getnumlimit(), getoption(), lua_scripts::hook(), io_readline(), iter_aux(), lstop(), luaB_print(), luaB_setmetatable(), luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), luaL_tolstring(), luaopen_bit32(), match(), matchbalance(), math_random(), opencheck(), os_date(), os_time(), os_tmpname(), partition(), push_onecapture(), pushargs(), resizebox(), scanformat(), start_capture(), str_byte(), str_dump(), str_format(), str_rep(), tinsert(), tofile(), unpack(), and unpackint().
luaL_execresult()
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 274 of file lauxlib.c.
Referenced by io_pclose(), and os_execute().
luaL_fileresult()
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 234 of file lauxlib.c.
Referenced by f_flush(), f_seek(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_popen(), io_tmpfile(), luaL_execresult(), os_remove(), and os_rename().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 772 of file lauxlib.c.
Referenced by luaB_getmetatable(), luaB_setmetatable(), luaL_callmeta(), luaL_tolstring(), pairsmeta(), and typeerror().
luaL_getsubtable()
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 951 of file lauxlib.c.
Referenced by luaL_requiref(), and luaopen_package().
luaL_gsub()
LUALIB_API const char* luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 991 of file lauxlib.c.
Referenced by loadfunc(), searchpath(), and setpath().
luaL_len()
LUALIB_API lua_Integer luaL_len (lua_State * L, int idx)
Definition at line 798 of file lauxlib.c.
Referenced by addtoclib(), gctm(), pushargs(), and unpack().
luaL_loadbufferx()
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t size, const char * name, const char * mode)
Definition at line 755 of file lauxlib.c.
Referenced by luaB_load().
luaL_loadfilex()
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 703 of file lauxlib.c.
Referenced by luaB_loadfile().
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 764 of file lauxlib.c.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 299 of file lauxlib.c.
Referenced by createmeta(), load_boxed_numerics(), load_generated_bindings(), and newbox().
luaL_newstate()
LUALIB_API lua_State* luaL_newstate (void)
Definition at line 1026 of file lauxlib.c.
Referenced by main().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int arg, lua_Integer def)
Definition at line 440 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), db_sethook(), db_traceback(), f_seek(), luaB_collectgarbage(), luaB_error(), os_exit(), str_byte(), str_find_aux(), str_gsub(), str_sub(), str_unpack(), tconcat(), tremove(), unpack(), and utflen().
luaL_optlstring()
LUALIB_API const char* luaL_optlstring (lua_State * L, int arg, const char * def, size_t * len)
Definition at line 397 of file lauxlib.c.
Referenced by os_date(), str_rep(), and tconcat().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int arg, lua_Number def)
Definition at line 417 of file lauxlib.c.
Referenced by math_atan().
luaL_prepbuffsize()
LUALIB_API char* luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 505 of file lauxlib.c.
Referenced by addliteral(), luaL_addlstring(), luaL_buffinitsize(), os_date(), packint(), read_chars(), str_format(), and str_pack().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 542 of file lauxlib.c.
Referenced by findloader(), luaL_gsub(), luaL_pushresultsize(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_pushresultsize()
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 552 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 595 of file lauxlib.c.
Referenced by lua_scripts::load_script(), and lua_scripts::run_next_script().
luaL_requiref()
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 971 of file lauxlib.c.
Referenced by luaL_openlibs().
luaL_setfuncs()
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 934 of file lauxlib.c.
Referenced by createmeta(), load_boxed_numerics(), load_generated_bindings(), luaopen_base(), and luaopen_package().
luaL_setmetatable()
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 312 of file lauxlib.c.
Referenced by newprefile().
luaL_testudata()
LUALIB_API void* luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 318 of file lauxlib.c.
Referenced by coerce_to_uint32_t(), io_type(), and luaL_checkudata().
luaL_tolstring()
LUALIB_API const char* luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 810 of file lauxlib.c.
Referenced by add_s(), addliteral(), luaB_tostring(), and str_format().
luaL_traceback()
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 125 of file lauxlib.c.
Referenced by db_traceback(), and msghandler().
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 616 of file lauxlib.c.
Referenced by lua_scripts::remove_script(), and lua_scripts::run_next_script().
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 205 of file lauxlib.c.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().
newbox()
static void* newbox (lua_State * L, size_t newsize) static
Definition at line 482 of file lauxlib.c.
Referenced by luaL_prepbuffsize().
panic()
static int panic (lua_State * L) static
Definition at line 1019 of file lauxlib.c.
Referenced by luaL_newstate().
pushfuncname()
static void pushfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 94 of file lauxlib.c.
Referenced by luaL_traceback().
pushglobalfuncname()
static int pushglobalfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 73 of file lauxlib.c.
Referenced by luaL_argerror(), and pushfuncname().
resizebox()
static void* resizebox (lua_State * L, int idx, size_t newsize) static
Definition at line 461 of file lauxlib.c.
Referenced by boxgc(), luaL_prepbuffsize(), luaL_pushresult(), and newbox().
skipBOM()
static int skipBOM (LoadF * lf) static
Definition at line 669 of file lauxlib.c.
Referenced by skipcomment().
skipcomment()
static int skipcomment (LoadF * lf, int * cp) static
Definition at line 690 of file lauxlib.c.
Referenced by luaL_loadfilex().
tag_error()
static void tag_error (lua_State * L, int arg, int tag) static
Definition at line 196 of file lauxlib.c.
Referenced by interror(), luaL_checklstring(), luaL_checknumber(), and luaL_checktype().
typeerror()
static int typeerror (lua_State * L, int arg, const char * tname) static
Definition at line 182 of file lauxlib.c.
Referenced by luaL_checkudata(), and tag_error().