APM:Libraries: libraries/AP_Scripting/lua/src/lauxlib.h File Reference
lauxlib.h File Reference
#include <stddef.h>
#include <stdio.h>
#include "lua.h"
Classes
struct luaL_Reg
struct luaL_Buffer
struct luaL_Stream
Macros
#define LUA_ERRFILE (LUA_ERRERR+1)
#define LUA_LOADED_TABLE "_LOADED"
#define LUA_PRELOAD_TABLE "_PRELOAD"
#define LUAL_NUMSIZES (sizeof(lua_Integer)*16 + sizeof(lua_Number))
#define luaL_checkversion(L) luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
#define LUA_NOREF (-2)
#define LUA_REFNIL (-1)
#define luaL_loadfile(L, f) luaL_loadfilex(L,f,NULL)
#define luaL_newlibtable(L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
#define luaL_newlib(L, l) (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
#define luaL_argcheck(L, cond, arg, extramsg) ((void)((cond) || luaL_argerror(L, (arg), (extramsg))))
#define luaL_checkstring(L, n) (luaL_checklstring(L, (n), NULL))
#define luaL_optstring(L, n, d) (luaL_optlstring(L, (n), (d), NULL))
#define luaL_typename(L, i) lua_typename(L, lua_type(L,(i)))
#define luaL_dofile(L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_dostring(L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_getmetatable(L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
#define luaL_opt(L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
#define luaL_loadbuffer(L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
#define luaL_addchar(B, c)
#define luaL_addsize(B, s) ((B)->n += (s))
#define luaL_prepbuffer(B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
#define LUA_FILEHANDLE "FILE*"
#define lua_writestring(s, l) fwrite((s), sizeof(char), (l), stdout)
#define lua_writeline() (lua_writestring("\n", 1), fflush(stdout))
#define lua_writestringerror(s, p) (fprintf(stderr, (s), (p)), fflush(stderr))
Typedefs
typedef struct luaL_Reg luaL_Reg
typedef struct luaL_Buffer luaL_Buffer
typedef struct luaL_Stream luaL_Stream
Functions
LUALIB_API void() luaL_checkversion_ (lua_State *L, lua_Number ver, size_t sz)
LUALIB_API int() luaL_getmetafield (lua_State *L, int obj, const char *e)
LUALIB_API int() luaL_callmeta (lua_State *L, int obj, const char *e)
LUALIB_API const char *() luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API int() luaL_argerror (lua_State *L, int arg, const char *extramsg)
LUALIB_API const char *() luaL_checklstring (lua_State *L, int arg, size_t *l)
LUALIB_API const char *() luaL_optlstring (lua_State *L, int arg, const char *def, size_t *l)
LUALIB_API lua_Number() luaL_checknumber (lua_State *L, int arg)
LUALIB_API lua_Number() luaL_optnumber (lua_State *L, int arg, lua_Number def)
LUALIB_API lua_Integer() luaL_checkinteger (lua_State *L, int arg)
LUALIB_API lua_Integer() luaL_optinteger (lua_State *L, int arg, lua_Integer def)
LUALIB_API void() luaL_checkstack (lua_State *L, int sz, const char *msg)
LUALIB_API void() luaL_checktype (lua_State *L, int arg, int t)
LUALIB_API void() luaL_checkany (lua_State *L, int arg)
LUALIB_API int() luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void() luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void *() luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void *() luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API void() luaL_where (lua_State *L, int lvl)
LUALIB_API int() luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int() luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[])
LUALIB_API int() luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int() luaL_execresult (lua_State *L, int stat)
LUALIB_API int() luaL_ref (lua_State *L, int t)
LUALIB_API void() luaL_unref (lua_State *L, int t, int ref)
LUALIB_API int() luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
LUALIB_API int() luaL_loadbufferx (lua_State *L, const char *buff, size_t sz, const char *name, const char *mode)
LUALIB_API int() luaL_loadstring (lua_State *L, const char *s)
LUALIB_API lua_State *() luaL_newstate (void)
LUALIB_API lua_Integer() luaL_len (lua_State *L, int idx)
LUALIB_API const char *() luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API void() luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int() luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void() luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API void() luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API void() luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char *() luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void() luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void() luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void() luaL_addvalue (luaL_Buffer *B)
LUALIB_API void() luaL_pushresult (luaL_Buffer *B)
LUALIB_API void() luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API char *() luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
Macro Definition Documentation
LUA_ERRFILE
#define LUA_ERRFILE (LUA_ERRERR+1)
Definition at line 20 of file lauxlib.h.
LUA_FILEHANDLE
#define LUA_FILEHANDLE "FILE*"
Definition at line 190 of file lauxlib.h.
LUA_LOADED_TABLE
#define LUA_LOADED_TABLE "_LOADED"
Definition at line 24 of file lauxlib.h.
LUA_NOREF
#define LUA_NOREF (-2)
Definition at line 77 of file lauxlib.h.
LUA_PRELOAD_TABLE
#define LUA_PRELOAD_TABLE "_PRELOAD"
Definition at line 28 of file lauxlib.h.
LUA_REFNIL
#define LUA_REFNIL (-1)
Definition at line 78 of file lauxlib.h.
lua_writeline
#define lua_writeline () (lua_writestring("\n", 1), fflush(stdout))
Definition at line 228 of file lauxlib.h.
lua_writestring
#define lua_writestring (s, l) fwrite((s), sizeof(char), (l), stdout)
Definition at line 223 of file lauxlib.h.
lua_writestringerror
#define lua_writestringerror (s, p) (fprintf(stderr, (s), (p)), fflush(stderr))
Definition at line 233 of file lauxlib.h.
luaL_addchar
#define luaL_addchar (B, c)
Value:
((void)((B)->n < (B)->size || luaL_prepbuffsize((B), 1)), \
   ((B)->b[(B)->n++] = (c)))
Definition at line 157 of file lauxlib.h.
luaL_addsize
#define luaL_addsize (B, s) ((B)->n += (s))
Definition at line 161 of file lauxlib.h.
luaL_argcheck
#define luaL_argcheck (L, cond, arg, extramsg) ((void)((cond) || luaL_argerror(L, (arg), (extramsg))))
Definition at line 122 of file lauxlib.h.
luaL_checkstring
#define luaL_checkstring (L, n) (luaL_checklstring(L, (n), NULL))
Definition at line 124 of file lauxlib.h.
luaL_checkversion
#define luaL_checkversion (L) luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
Definition at line 40 of file lauxlib.h.
luaL_dofile
#define luaL_dofile (L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 129 of file lauxlib.h.
luaL_dostring
#define luaL_dostring (L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 132 of file lauxlib.h.
luaL_getmetatable
#define luaL_getmetatable (L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
Definition at line 135 of file lauxlib.h.
luaL_loadbuffer
#define luaL_loadbuffer (L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
Definition at line 139 of file lauxlib.h.
luaL_loadfile
#define luaL_loadfile (L, f) luaL_loadfilex(L,f,NULL)
Definition at line 86 of file lauxlib.h.
luaL_newlib
#define luaL_newlib (L, l) (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
Definition at line 119 of file lauxlib.h.
luaL_newlibtable
#define luaL_newlibtable (L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
Definition at line 116 of file lauxlib.h.
LUAL_NUMSIZES
#define LUAL_NUMSIZES (sizeof(lua_Integer)*16 + sizeof(lua_Number))
Definition at line 37 of file lauxlib.h.
luaL_opt
#define luaL_opt (L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
Definition at line 137 of file lauxlib.h.
luaL_optstring
#define luaL_optstring (L, n, d) (luaL_optlstring(L, (n), (d), NULL))
Definition at line 125 of file lauxlib.h.
luaL_prepbuffer
#define luaL_prepbuffer (B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
Definition at line 172 of file lauxlib.h.
luaL_typename
#define luaL_typename (L, i) lua_typename(L, lua_type(L,(i)))
Definition at line 127 of file lauxlib.h.
Typedef Documentation
luaL_Buffer
typedef struct luaL_Buffer luaL_Buffer
luaL_Reg
typedef struct luaL_Reg luaL_Reg
luaL_Stream
typedef struct luaL_Stream luaL_Stream
Function Documentation
luaL_addlstring()
LUALIB_API void() luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 528 of file lauxlib.c.
Referenced by add_s(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), str_gsub(), str_pack(), tconcat(), and writer().
luaL_addstring()
LUALIB_API void() luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 537 of file lauxlib.c.
Referenced by addquoted(), and luaL_gsub().
luaL_addvalue()
LUALIB_API void() luaL_addvalue (luaL_Buffer * B)
Definition at line 558 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), addliteral(), findloader(), searchpath(), str_format(), and utfchar().
luaL_argerror()
LUALIB_API int() luaL_argerror (lua_State * L, int arg, const char * extramsg)
Definition at line 164 of file lauxlib.c.
Referenced by addliteral(), AP_AHRS_get_gyro(), AP_AHRS_get_hagl(), AP_AHRS_get_home(), AP_AHRS_get_position(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_groundspeed_vector(), AP_AHRS_home_is_set(), AP_AHRS_prearm_healthy(), AP_AHRS_wind_estimate(), AP_BattMonitor_capacity_remaining_pct(), AP_BattMonitor_consumed_mah(), AP_BattMonitor_consumed_wh(), AP_BattMonitor_current_amps(), AP_BattMonitor_get_temperature(), AP_BattMonitor_has_consumed_energy(), AP_BattMonitor_has_current(), AP_BattMonitor_has_failsafed(), AP_BattMonitor_healthy(), AP_BattMonitor_num_instances(), AP_BattMonitor_overpower_detected(), AP_BattMonitor_pack_capacity_mah(), AP_BattMonitor_voltage(), AP_BattMonitor_voltage_resting_estimate(), AP_GPS_all_configured(), AP_GPS_first_unconfigured_gps(), AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_num_sensors(), AP_GPS_primary_sensor(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), AP_GPS_vertical_accuracy(), AP_Notify_play_tune(), AP_Relay_enabled(), AP_Relay_off(), AP_Relay_on(), AP_Relay_toggle(), AP_Terrain_enabled(), AP_Terrain_height_above_terrain(), AP_Terrain_height_amsl(), AP_Terrain_height_relative_home_equivalent(), AP_Terrain_height_terrain_difference_home(), AP_Terrain_status(), binding_argcheck(), checkoption(), coerce_to_uint32_t(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), GCS_send_text(), getdetails(), interror(), Location_lat(), Location_lng(), Location_loiter_xtrack(), Location_origin_alt(), Location_relative_alt(), Location_terrain_alt(), luaL_checkany(), luaL_checkoption(), RangeFinder_num_sensors(), str_format(), str_packsize(), str_unpack(), typeerror(), uint32_t___tostring(), uint32_t_tofloat(), uint32_t_toint(), Vector2f_x(), Vector2f_y(), Vector3f_x(), Vector3f_y(), and Vector3f_z().
luaL_buffinit()
LUALIB_API void() luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 569 of file lauxlib.c.
Referenced by findloader(), luaL_buffinitsize(), luaL_gsub(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_buffinitsize()
LUALIB_API char*() luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 577 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_callmeta()
LUALIB_API int() luaL_callmeta (lua_State * L, int obj, const char * e)
Definition at line 788 of file lauxlib.c.
Referenced by luaL_tolstring(), and msghandler().
luaL_checkany()
LUALIB_API void() luaL_checkany (lua_State * L, int arg)
Definition at line 384 of file lauxlib.c.
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), db_setuservalue(), io_type(), luaB_assert(), luaB_getmetatable(), luaB_ipairs(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), math_toint(), math_type(), and pairsmeta().
luaL_checkinteger()
LUALIB_API lua_Integer() luaL_checkinteger (lua_State * L, int arg)
Definition at line 430 of file lauxlib.c.
Referenced by AP_BattMonitor_capacity_remaining_pct(), AP_BattMonitor_consumed_mah(), AP_BattMonitor_consumed_wh(), AP_BattMonitor_current_amps(), AP_BattMonitor_get_temperature(), AP_BattMonitor_has_consumed_energy(), AP_BattMonitor_has_current(), AP_BattMonitor_healthy(), AP_BattMonitor_overpower_detected(), AP_BattMonitor_pack_capacity_mah(), AP_BattMonitor_voltage(), AP_BattMonitor_voltage_resting_estimate(), AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), AP_GPS_vertical_accuracy(), AP_Relay_enabled(), AP_Relay_off(), AP_Relay_on(), AP_Relay_toggle(), auxupvalue(), byteoffset(), checkupval(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), GCS_send_text(), ipairsaux(), l_checktime(), Location_lat(), Location_lng(), lua_servo_set_output_pwm(), luaB_select(), luaB_tonumber(), luaL_optinteger(), math_random(), math_ult(), pushutfchar(), str_char(), str_format(), str_pack(), str_rep(), str_sub(), tinsert(), tmove(), and unpack().
luaL_checklstring()
LUALIB_API const char*() luaL_checklstring (lua_State * L, int arg, size_t * l)
Definition at line 390 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), g_write(), gmatch(), iter_aux(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_pack(), str_rep(), str_reverse(), str_sub(), str_unpack(), str_upper(), and utflen().
luaL_checknumber()
LUALIB_API lua_Number() luaL_checknumber (lua_State * L, int arg)
Definition at line 408 of file lauxlib.c.
Referenced by AP_Terrain_height_relative_home_equivalent(), Location_offset(), lua_servo_set_output_pwm(), luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_ceil(), math_cos(), math_deg(), math_exp(), math_floor(), math_fmod(), math_log(), math_modf(), math_rad(), math_randomseed(), math_sin(), math_sqrt(), math_tan(), lua_scripts::run_next_script(), str_format(), str_pack(), Vector2f_x(), Vector2f_y(), Vector3f_x(), Vector3f_y(), and Vector3f_z().
luaL_checkoption()
LUALIB_API int() luaL_checkoption (lua_State * L, int arg, const char * def, const char *const lst[])
Definition at line 348 of file lauxlib.c.
Referenced by f_seek(), luaB_collectgarbage(), and os_setlocale().
luaL_checkstack()
LUALIB_API void() luaL_checkstack (lua_State * L, int sz, const char * msg)
Definition at line 368 of file lauxlib.c.
Referenced by codepoint(), g_read(), generic_reader(), io_readline(), l_print(), load_boxed_numerics(), load_generated_bindings(), luaL_setfuncs(), luaL_traceback(), new_Location(), new_uint32_t(), new_Vector2f(), new_Vector3f(), push_captures(), pushargs(), str_byte(), and str_unpack().
luaL_checktype()
LUALIB_API void() luaL_checktype (lua_State * L, int arg, int t)
Definition at line 378 of file lauxlib.c.
Referenced by auxupvalue(), checktab(), checkupval(), db_sethook(), db_setuservalue(), luaB_cocreate(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaB_tonumber(), luaB_xpcall(), os_time(), sort(), and str_dump().
luaL_checkudata()
LUALIB_API void*() luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 333 of file lauxlib.c.
Referenced by AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_time_week_ms(), check_Location(), check_uint32_t(), check_Vector2f(), check_Vector3f(), uint32_t___tostring(), uint32_t_tofloat(), and uint32_t_toint().
luaL_checkversion_()
LUALIB_API void() luaL_checkversion_ (lua_State * L, lua_Number ver, size_t sz)
Definition at line 1033 of file lauxlib.c.
luaL_error()
LUALIB_API int() luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 223 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), byteoffset(), capture_to_close(), check_arguments(), check_capture(), checkload(), checkstack(), classend(), codepoint(), findfile(), findloader(), generic_reader(), getfield(), getiofile(), getnumlimit(), getoption(), lua_scripts::hook(), io_readline(), iter_aux(), lstop(), luaB_print(), luaB_setmetatable(), luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), luaL_tolstring(), luaopen_bit32(), match(), matchbalance(), math_random(), opencheck(), os_date(), os_time(), os_tmpname(), partition(), push_onecapture(), pushargs(), resizebox(), scanformat(), start_capture(), str_byte(), str_dump(), str_format(), str_rep(), tinsert(), tofile(), unpack(), and unpackint().
luaL_execresult()
LUALIB_API int() luaL_execresult (lua_State * L, int stat)
Definition at line 274 of file lauxlib.c.
Referenced by io_pclose(), and os_execute().
luaL_fileresult()
LUALIB_API int() luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 234 of file lauxlib.c.
Referenced by f_flush(), f_seek(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_popen(), io_tmpfile(), luaL_execresult(), os_remove(), and os_rename().
luaL_getmetafield()
LUALIB_API int() luaL_getmetafield (lua_State * L, int obj, const char * e)
Definition at line 772 of file lauxlib.c.
Referenced by luaB_getmetatable(), luaB_setmetatable(), luaL_callmeta(), luaL_tolstring(), pairsmeta(), and typeerror().
luaL_getsubtable()
LUALIB_API int() luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 951 of file lauxlib.c.
Referenced by luaL_requiref(), and luaopen_package().
luaL_gsub()
LUALIB_API const char*() luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 991 of file lauxlib.c.
Referenced by loadfunc(), searchpath(), and setpath().
luaL_len()
LUALIB_API lua_Integer() luaL_len (lua_State * L, int idx)
Definition at line 798 of file lauxlib.c.
Referenced by addtoclib(), gctm(), pushargs(), and unpack().
luaL_loadbufferx()
LUALIB_API int() luaL_loadbufferx (lua_State * L, const char * buff, size_t sz, const char * name, const char * mode)
Definition at line 755 of file lauxlib.c.
Referenced by luaB_load().
luaL_loadfilex()
LUALIB_API int() luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 703 of file lauxlib.c.
Referenced by luaB_loadfile().
luaL_loadstring()
LUALIB_API int() luaL_loadstring (lua_State * L, const char * s)
Definition at line 764 of file lauxlib.c.
luaL_newmetatable()
LUALIB_API int() luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 299 of file lauxlib.c.
Referenced by createmeta(), load_boxed_numerics(), load_generated_bindings(), and newbox().
luaL_newstate()
LUALIB_API lua_State*() luaL_newstate (void)
Definition at line 1026 of file lauxlib.c.
Referenced by main().
luaL_optinteger()
LUALIB_API lua_Integer() luaL_optinteger (lua_State * L, int arg, lua_Integer def)
Definition at line 440 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), db_sethook(), db_traceback(), f_seek(), luaB_collectgarbage(), luaB_error(), os_exit(), str_byte(), str_find_aux(), str_gsub(), str_sub(), str_unpack(), tconcat(), tremove(), unpack(), and utflen().
luaL_optlstring()
LUALIB_API const char*() luaL_optlstring (lua_State * L, int arg, const char * def, size_t * l)
Definition at line 397 of file lauxlib.c.
Referenced by os_date(), str_rep(), and tconcat().
luaL_optnumber()
LUALIB_API lua_Number() luaL_optnumber (lua_State * L, int arg, lua_Number def)
Definition at line 417 of file lauxlib.c.
Referenced by math_atan().
luaL_prepbuffsize()
LUALIB_API char*() luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 505 of file lauxlib.c.
Referenced by addliteral(), luaL_addlstring(), luaL_buffinitsize(), os_date(), packint(), read_chars(), str_format(), and str_pack().
luaL_pushresult()
LUALIB_API void() luaL_pushresult (luaL_Buffer * B)
Definition at line 542 of file lauxlib.c.
Referenced by findloader(), luaL_gsub(), luaL_pushresultsize(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_pushresultsize()
LUALIB_API void() luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 552 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_ref()
LUALIB_API int() luaL_ref (lua_State * L, int t)
Definition at line 595 of file lauxlib.c.
Referenced by lua_scripts::load_script(), and lua_scripts::run_next_script().
luaL_requiref()
LUALIB_API void() luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 971 of file lauxlib.c.
Referenced by luaL_openlibs().
luaL_setfuncs()
LUALIB_API void() luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 934 of file lauxlib.c.
Referenced by createmeta(), load_boxed_numerics(), load_generated_bindings(), luaopen_base(), and luaopen_package().
luaL_setmetatable()
LUALIB_API void() luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 312 of file lauxlib.c.
Referenced by newprefile().
luaL_testudata()
LUALIB_API void*() luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 318 of file lauxlib.c.
Referenced by coerce_to_uint32_t(), io_type(), and luaL_checkudata().
luaL_tolstring()
LUALIB_API const char*() luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 810 of file lauxlib.c.
Referenced by add_s(), addliteral(), luaB_tostring(), and str_format().
luaL_traceback()
LUALIB_API void() luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 125 of file lauxlib.c.
Referenced by db_traceback(), and msghandler().
luaL_unref()
LUALIB_API void() luaL_unref (lua_State * L, int t, int ref)
Definition at line 616 of file lauxlib.c.
Referenced by lua_scripts::remove_script(), and lua_scripts::run_next_script().
luaL_where()
LUALIB_API void() luaL_where (lua_State * L, int lvl)
Definition at line 205 of file lauxlib.c.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().