APM:Libraries: libraries/AP_Scripting/lua/src/loadlib.c File Reference
loadlib.c File Reference
#include "lprefix.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define loadlib_c
#define LUA_LIB
#define LUA_IGMARK "-"
#define LUA_CSUBSEP LUA_DIRSEP
#define LUA_LSUBSEP LUA_DIRSEP
#define LUA_POF "luaopen_"
#define LUA_OFSEP "_"
#define LIB_FAIL "open"
#define setprogdir(L) ((void)0)
#define LIB_FAIL "absent"
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
#define LUA_PATH_VAR "LUA_PATH"
#define LUA_CPATH_VAR "LUA_CPATH"
#define AUXMARK "\1" /* auxiliary mark */
#define ERRLIB 1
#define ERRFUNC 2
Functions
static void lsys_unloadlib (void *lib)
static void * lsys_load (lua_State *L, const char *path, int seeglb)
static lua_CFunction lsys_sym (lua_State *L, void *lib, const char *sym)
static int noenv (lua_State *L)
static void setpath (lua_State *L, const char *fieldname, const char *envname, const char *dft)
static void * checkclib (lua_State *L, const char *path)
static void addtoclib (lua_State *L, const char *path, void *plib)
static int gctm (lua_State *L)
static int lookforfunc (lua_State *L, const char *path, const char *sym)
static int ll_loadlib (lua_State *L)
static int readable (const char *filename)
static const char * pushnexttemplate (lua_State *L, const char *path)
static const char * searchpath (lua_State *L, const char *name, const char *path, const char *sep, const char *dirsep)
static int ll_searchpath (lua_State *L)
static const char * findfile (lua_State *L, const char *name, const char *pname, const char *dirsep)
static int checkload (lua_State *L, int stat, const char *filename)
static int searcher_Lua (lua_State *L)
static int loadfunc (lua_State *L, const char *filename, const char *modname)
static int searcher_C (lua_State *L)
static int searcher_Croot (lua_State *L)
static int searcher_preload (lua_State *L)
static void findloader (lua_State *L, const char *name)
static int ll_require (lua_State *L)
static void createsearcherstable (lua_State *L)
static void createclibstable (lua_State *L)
LUAMOD_API int luaopen_package (lua_State *L)
Variables
static const int CLIBS = 0
static const luaL_Reg pk_funcs []
static const luaL_Reg ll_funcs []
Macro Definition Documentation
AUXMARK
#define AUXMARK "\1" /* auxiliary mark */
Definition at line 272 of file loadlib.c.
DLMSG
#define DLMSG "dynamic libraries not enabled; check your Lua installation"
Definition at line 228 of file loadlib.c.
ERRFUNC
#define ERRFUNC 2
Definition at line 359 of file loadlib.c.
ERRLIB
#define ERRLIB 1
Definition at line 358 of file loadlib.c.
LIB_FAIL [1/2]
#define LIB_FAIL "open"
Definition at line 225 of file loadlib.c.
LIB_FAIL [2/2]
#define LIB_FAIL "absent"
Definition at line 225 of file loadlib.c.
loadlib_c
#define loadlib_c
Definition at line 11 of file loadlib.c.
LUA_CPATH_VAR
#define LUA_CPATH_VAR "LUA_CPATH"
Definition at line 268 of file loadlib.c.
LUA_CSUBSEP
#define LUA_CSUBSEP LUA_DIRSEP
Definition at line 43 of file loadlib.c.
LUA_IGMARK
#define LUA_IGMARK "-"
Definition at line 32 of file loadlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 12 of file loadlib.c.
LUA_LSUBSEP
#define LUA_LSUBSEP LUA_DIRSEP
Definition at line 47 of file loadlib.c.
LUA_OFSEP
#define LUA_OFSEP "_"
Definition at line 55 of file loadlib.c.
LUA_PATH_VAR
#define LUA_PATH_VAR "LUA_PATH"
Definition at line 264 of file loadlib.c.
LUA_POF
#define LUA_POF "luaopen_"
Definition at line 52 of file loadlib.c.
setprogdir
#define setprogdir (L) ((void)0)
Definition at line 67 of file loadlib.c.
Function Documentation
addtoclib()
static void addtoclib (lua_State * L, const char * path, void * plib) static
Definition at line 331 of file loadlib.c.
Referenced by lookforfunc().
checkclib()
static void* checkclib (lua_State * L, const char * path) static
Definition at line 317 of file loadlib.c.
Referenced by lookforfunc().
checkload()
static int checkload (lua_State * L, int stat, const char * filename) static
Definition at line 484 of file loadlib.c.
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
createclibstable()
static void createclibstable (lua_State * L) static
Definition at line 757 of file loadlib.c.
Referenced by luaopen_package().
createsearcherstable()
static void createsearcherstable (lua_State * L) static
Definition at line 733 of file loadlib.c.
Referenced by luaopen_package().
findfile()
static const char* findfile (lua_State * L, const char * name, const char * pname, const char * dirsep) static
Definition at line 472 of file loadlib.c.
Referenced by searcher_C(), searcher_Croot(), and searcher_Lua().
findloader()
static void findloader (lua_State * L, const char * name) static
Definition at line 569 of file loadlib.c.
Referenced by ll_require().
gctm()
static int gctm (lua_State * L) static
Definition at line 345 of file loadlib.c.
Referenced by createclibstable().
ll_loadlib()
static int ll_loadlib (lua_State * L) static
Definition at line 393 of file loadlib.c.
ll_require()
static int ll_require (lua_State * L) static
Definition at line 597 of file loadlib.c.
ll_searchpath()
static int ll_searchpath (lua_State * L) static
Definition at line 458 of file loadlib.c.
loadfunc()
static int loadfunc (lua_State * L, const char * filename, const char * modname) static
Definition at line 512 of file loadlib.c.
Referenced by searcher_C(), and searcher_Croot().
lookforfunc()
static int lookforfunc (lua_State * L, const char * path, const char * sym) static
Definition at line 372 of file loadlib.c.
Referenced by ll_loadlib(), and loadfunc().
lsys_load()
static void * lsys_load (lua_State * L, const char * path, int seeglb) static
Definition at line 236 of file loadlib.c.
Referenced by lookforfunc().
lsys_sym()
static lua_CFunction lsys_sym (lua_State * L, void * lib, const char * sym) static
Definition at line 243 of file loadlib.c.
Referenced by lookforfunc().
lsys_unloadlib()
static void lsys_unloadlib (void * lib) static
Definition at line 231 of file loadlib.c.
Referenced by gctm().
luaopen_package()
LUAMOD_API int luaopen_package (lua_State * L)
Definition at line 767 of file loadlib.c.
noenv()
static int noenv (lua_State * L) static
Definition at line 278 of file loadlib.c.
Referenced by setpath().
pushnexttemplate()
static const char* pushnexttemplate (lua_State * L, const char * path) static
Definition at line 424 of file loadlib.c.
Referenced by searchpath().
readable()
static int readable (const char * filename) static
Definition at line 416 of file loadlib.c.
Referenced by searchpath().
searcher_C()
static int searcher_C (lua_State * L) static
Definition at line 530 of file loadlib.c.
Referenced by createsearcherstable().
searcher_Croot()
static int searcher_Croot (lua_State * L) static
Definition at line 538 of file loadlib.c.
Referenced by createsearcherstable().
searcher_Lua()
static int searcher_Lua (lua_State * L) static
Definition at line 495 of file loadlib.c.
Referenced by createsearcherstable().
searcher_preload()
static int searcher_preload (lua_State * L) static
Definition at line 560 of file loadlib.c.
Referenced by createsearcherstable().
searchpath()
static const char* searchpath (lua_State * L, const char * name, const char * path, const char * sep, const char * dirsep) static
Definition at line 435 of file loadlib.c.
Referenced by findfile(), and ll_searchpath().
setpath()
static void setpath (lua_State * L, const char * fieldname, const char * envname, const char * dft) static
Definition at line 290 of file loadlib.c.
Referenced by luaopen_package().
Variable Documentation
CLIBS
const int CLIBS = 0 static
Definition at line 62 of file loadlib.c.
Referenced by addtoclib(), checkclib(), and createclibstable().
ll_funcs
const luaL_Reg ll_funcs[] static
Initial value:
= {
  {"require", ll_require},
  {NULL, NULL}
}
Definition at line 724 of file loadlib.c.
Referenced by luaopen_package().
pk_funcs
const luaL_Reg pk_funcs[] static
Initial value:
= {
  {"loadlib", ll_loadlib},
  {"searchpath", ll_searchpath},
  {"preload", NULL},
  {"cpath", NULL},
  {"path", NULL},
  {"searchers", NULL},
  {"loaded", NULL},
  {NULL, NULL}
}
Definition at line 708 of file loadlib.c.
Referenced by luaopen_package().