APM:Libraries: libraries/AP_Math/location.cpp File Reference
location.cpp File Reference
#include <stdlib.h>
#include "AP_Math.h"
#include "location.h"
Functions
float get_horizontal_distance_cm (const Vector3f &origin, const Vector3f &destination)
float get_bearing_cd (const Vector3f &origin, const Vector3f &destination)
bool check_lat (float lat)
bool check_lng (float lng)
bool check_lat (int32_t lat)
bool check_lng (int32_t lng)
bool check_latlng (float lat, float lng)
bool check_latlng (int32_t lat, int32_t lng)
Function Documentation
check_lat() [1/2]
bool check_lat (float lat)
Definition at line 43 of file location.cpp.
Referenced by check_latlng(), Location::check_latlng(), AP_Mission::convert_MISSION_ITEM_INT_to_MISSION_ITEM(), MissionItemProtocol_Rally::convert_MISSION_ITEM_INT_to_RallyLocation(), AP_Mission::convert_MISSION_ITEM_to_MISSION_ITEM_INT(), and AP_Mission::mavlink_int_to_mission_cmd().
check_lat() [2/2]
bool check_lat (int32_t lat)
Definition at line 51 of file location.cpp.
check_latlng() [1/2]
bool check_latlng (float lat, float lng)
Definition at line 59 of file location.cpp.
Referenced by AC_Fence::handle_msg(), GCS_MAVLINK::handle_rally_point(), and GCS_MAVLINK::handle_set_gps_global_origin().
check_latlng() [2/2]
bool check_latlng (int32_t lat, int32_t lng)
Definition at line 63 of file location.cpp.
check_lng() [1/2]
bool check_lng (float lng)
Definition at line 47 of file location.cpp.
Referenced by check_latlng(), Location::check_latlng(), AP_Mission::convert_MISSION_ITEM_INT_to_MISSION_ITEM(), MissionItemProtocol_Rally::convert_MISSION_ITEM_INT_to_RallyLocation(), AP_Mission::convert_MISSION_ITEM_to_MISSION_ITEM_INT(), and AP_Mission::mavlink_int_to_mission_cmd().
check_lng() [2/2]
bool check_lng (int32_t lng)
Definition at line 55 of file location.cpp.
get_bearing_cd()
float get_bearing_cd (const Vector3f & origin, const Vector3f & destination)
Definition at line 33 of file location.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_PosControl::get_bearing_to_target(), AC_WPNav::get_wp_bearing_to_destination(), and AC_Circle::update().
get_horizontal_distance_cm()
float get_horizontal_distance_cm (const Vector3f & origin, const Vector3f & destination)
Definition at line 27 of file location.cpp.