APM:Libraries: libraries/AP_Scripting/lua/src/ltable.h File Reference
ltable.h File Reference
#include "lobject.h"
Macros
#define gnode(t, i) (&(t)->node[i])
#define gval(n) (&(n)->i_val)
#define gnext(n) ((n)->i_key.nk.next)
#define gkey(n) cast(const TValue*, (&(n)->i_key.tvk))
#define wgkey(n) (&(n)->i_key.nk)
#define invalidateTMcache(t) ((t)->flags = 0)
#define isdummy(t) ((t)->lastfree == NULL)
#define allocsizenode(t) (isdummy(t) ? 0 : sizenode(t))
#define keyfromval(v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Functions
LUAI_FUNC const TValue * luaH_getint (Table *t, lua_Integer key)
LUAI_FUNC void luaH_setint (lua_State *L, Table *t, lua_Integer key, TValue *value)
LUAI_FUNC const TValue * luaH_getshortstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_getstr (Table *t, TString *key)
LUAI_FUNC const TValue * luaH_get (Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
LUAI_FUNC Table * luaH_new (lua_State *L)
LUAI_FUNC void luaH_resize (lua_State *L, Table *t, unsigned int nasize, unsigned int nhsize)
LUAI_FUNC void luaH_resizearray (lua_State *L, Table *t, unsigned int nasize)
LUAI_FUNC void luaH_free (lua_State *L, Table *t)
LUAI_FUNC int luaH_next (lua_State *L, Table *t, StkId key)
LUAI_FUNC lua_Unsigned luaH_getn (Table *t)
Macro Definition Documentation
allocsizenode
#define allocsizenode (t) (isdummy(t) ? 0 : sizenode(t))
Definition at line 35 of file ltable.h.
gkey
#define gkey (n) cast(const TValue*, (&(n)->i_key.tvk))
Definition at line 19 of file ltable.h.
gnext
#define gnext (n) ((n)->i_key.nk.next)
Definition at line 15 of file ltable.h.
gnode
#define gnode (t, i) (&(t)->node[i])
Definition at line 13 of file ltable.h.
gval
#define gval (n) (&(n)->i_val)
Definition at line 14 of file ltable.h.
invalidateTMcache
#define invalidateTMcache (t) ((t)->flags = 0)
Definition at line 27 of file ltable.h.
isdummy
#define isdummy (t) ((t)->lastfree == NULL)
Definition at line 31 of file ltable.h.
keyfromval
#define keyfromval (v) (gkey(cast(Node *, cast(char *, (v)) - offsetof(Node, i_val))))
Definition at line 39 of file ltable.h.
wgkey
#define wgkey (n) (&(n)->i_key.nk)
Definition at line 25 of file ltable.h.
Function Documentation
luaH_free()
LUAI_FUNC void luaH_free (lua_State * L, Table * t)
Definition at line 433 of file ltable.c.
Referenced by freeobj().
luaH_get()
LUAI_FUNC const TValue* luaH_get (Table * t, const TValue * key)
Definition at line 589 of file ltable.c.
Referenced by lua_rawget(), lua_rawgetp(), luaH_set(), luaV_finishget(), and luaV_finishset().
luaH_getint()
LUAI_FUNC const TValue* luaH_getint (Table * t, lua_Integer key)
Definition at line 516 of file ltable.c.
Referenced by lua_getglobal(), lua_geti(), lua_load(), lua_rawgeti(), lua_setglobal(), lua_seti(), luaH_get(), luaH_setint(), and unbound_search().
luaH_getn()
LUAI_FUNC lua_Unsigned luaH_getn (Table * t)
Definition at line 660 of file ltable.c.
Referenced by lua_rawlen(), and luaV_objlen().
luaH_getshortstr()
LUAI_FUNC const TValue* luaH_getshortstr (Table * t, TString * key)
Definition at line 539 of file ltable.c.
Referenced by luaH_get(), luaH_getstr(), luaT_gettm(), luaT_gettmbyobj(), and luaT_objtypename().
luaH_getstr()
LUAI_FUNC const TValue* luaH_getstr (Table * t, TString * key)
Definition at line 575 of file ltable.c.
Referenced by auxgetstr(), auxsetstr(), and luaV_execute().
luaH_new()
LUAI_FUNC Table* luaH_new (lua_State * L)
Definition at line 421 of file ltable.c.
Referenced by collectvalidlines(), init_registry(), lua_createtable(), luaV_execute(), and luaY_parser().
luaH_newkey()
LUAI_FUNC TValue* luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 461 of file ltable.c.
Referenced by luaH_set(), luaH_setint(), and luaV_finishset().
luaH_next()
LUAI_FUNC int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 186 of file ltable.c.
Referenced by lua_next().
luaH_resize()
LUAI_FUNC void luaH_resize (lua_State * L, Table * t, unsigned int nasize, unsigned int nhsize)
Definition at line 347 of file ltable.c.
Referenced by init_registry(), lua_createtable(), luaH_resizearray(), luaV_execute(), and rehash().
luaH_resizearray()
LUAI_FUNC void luaH_resizearray (lua_State * L, Table * t, unsigned int nasize)
Definition at line 387 of file ltable.c.
Referenced by luaV_execute().
luaH_set()
LUAI_FUNC TValue* luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 610 of file ltable.c.
Referenced by addk(), lua_rawset(), lua_rawsetp(), luaH_newkey(), luaH_resize(), and luaX_newstring().
luaH_setint()
LUAI_FUNC void luaH_setint (lua_State * L, Table * t, lua_Integer key, TValue * value)
Definition at line 618 of file ltable.c.
Referenced by collectvalidlines(), init_registry(), lua_rawseti(), luaH_resize(), and luaV_execute().