APM:Libraries: libraries/AP_Scripting/lua/src/ltm.c File Reference
ltm.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lvm.h"
Macros
#define ltm_c
#define LUA_CORE
Functions
void luaT_init (lua_State *L)
const TValue * luaT_gettm (Table *events, TMS event, TString *ename)
const TValue * luaT_gettmbyobj (lua_State *L, const TValue *o, TMS event)
const char * luaT_objtypename (lua_State *L, const TValue *o)
void luaT_callTM (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, TValue *p3, int hasres)
int luaT_callbinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
void luaT_trybinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
int luaT_callorderTM (lua_State *L, const TValue *p1, const TValue *p2, TMS event)
Variables
static const char udatatypename [] = "userdata"
LUAI_DDEF const char *const luaT_typenames_ [LUA_TOTALTAGS]
Macro Definition Documentation
ltm_c
#define ltm_c
Definition at line 7 of file ltm.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file ltm.c.
Function Documentation
luaT_callbinTM()
int luaT_callbinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 124 of file ltm.c.
Referenced by luaT_callorderTM(), and luaT_trybinTM().
luaT_callorderTM()
int luaT_callorderTM (lua_State * L, const TValue * p1, const TValue * p2, TMS event)
Definition at line 158 of file ltm.c.
Referenced by luaV_lessequal(), and luaV_lessthan().
luaT_callTM()
void luaT_callTM (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, TValue * p3, int hasres)
Definition at line 102 of file ltm.c.
Referenced by luaT_callbinTM(), luaV_equalobj(), luaV_finishget(), luaV_finishset(), and luaV_objlen().
luaT_gettm()
const TValue* luaT_gettm (Table * events, TMS event, TString * ename)
Definition at line 59 of file ltm.c.
luaT_gettmbyobj()
const TValue* luaT_gettmbyobj (lua_State * L, const TValue * o, TMS event)
Definition at line 70 of file ltm.c.
Referenced by GCTM(), luaT_callbinTM(), luaV_finishget(), luaV_finishset(), luaV_objlen(), and tryfuncTM().
luaT_init()
void luaT_init (lua_State * L)
Definition at line 37 of file ltm.c.
Referenced by f_luaopen().
luaT_objtypename()
const char* luaT_objtypename (lua_State * L, const TValue * o)
Definition at line 90 of file ltm.c.
Referenced by luaG_ordererror(), and luaG_typeerror().
luaT_trybinTM()
void luaT_trybinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 135 of file ltm.c.
Referenced by luaO_arith(), luaV_concat(), and luaV_execute().
Variable Documentation
luaT_typenames_
LUAI_DDEF const char* const luaT_typenames_[LUA_TOTALTAGS]
Initial value:
= {
  "no value",
  "nil", "boolean", udatatypename, "number",
  "string", "table", "function", udatatypename, "thread",
  "proto"
}
Definition at line 29 of file ltm.c.
udatatypename
const char udatatypename[] = "userdata" static
Definition at line 27 of file ltm.c.