APM:Libraries: libraries/AP_Scripting/lua/src/lua.c File Reference
lua.c File Reference
#include "lprefix.h"
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lua_c
#define LUA_PROMPT "> "
#define LUA_PROMPT2 ">> "
#define LUA_PROGNAME "lua"
#define LUA_MAXINPUT 512
#define LUA_INIT_VAR "LUA_INIT"
#define LUA_INITVARVERSION LUA_INIT_VAR LUA_VERSUFFIX
#define lua_stdin_is_tty() 1 /* assume stdin is a tty */
#define lua_readline(L, b, p)
#define lua_saveline(L, line) { (void)L; (void)line; }
#define lua_freeline(L, b) { (void)L; (void)b; }
#define EOFMARK "<eof>"
#define marklen (sizeof(EOFMARK)/sizeof(char) - 1)
#define has_error 1 /* bad option */
#define has_i 2 /* -i */
#define has_v 4 /* -v */
#define has_e 8 /* -e */
#define has_E 16 /* -E */
Functions
static void lstop (lua_State *L, lua_Debug *ar)
static void laction (int i)
static void print_usage (const char *badoption)
static void l_message (const char *pname, const char *msg)
static int report (lua_State *L, int status)
static int msghandler (lua_State *L)
static int docall (lua_State *L, int narg, int nres)
static void print_version (void)
static void createargtable (lua_State *L, char **argv, int argc, int script)
static int dochunk (lua_State *L, int status)
static int dofile (lua_State *L, const char *name)
static int dostring (lua_State *L, const char *s, const char *name)
static int dolibrary (lua_State *L, const char *name)
static const char * get_prompt (lua_State *L, int firstline)
static int incomplete (lua_State *L, int status)
static int pushline (lua_State *L, int firstline)
static int addreturn (lua_State *L)
static int multiline (lua_State *L)
static int loadline (lua_State *L)
static void l_print (lua_State *L)
static void doREPL (lua_State *L)
static int pushargs (lua_State *L)
static int handle_script (lua_State *L, char **argv)
static int collectargs (char **argv, int *first)
static int runargs (lua_State *L, char **argv, int n)
static int handle_luainit (lua_State *L)
static int pmain (lua_State *L)
int main (int argc, char **argv)
Variables
static lua_State * globalL = NULL
static const char * progname = LUA_PROGNAME
Macro Definition Documentation
EOFMARK
#define EOFMARK "<eof>"
Definition at line 282 of file lua.c.
has_e
#define has_e 8 /* -e */
Definition at line 456 of file lua.c.
has_E
#define has_E 16 /* -E */
Definition at line 457 of file lua.c.
has_error
#define has_error 1 /* bad option */
Definition at line 453 of file lua.c.
has_i
#define has_i 2 /* -i */
Definition at line 454 of file lua.c.
has_v
#define has_v 4 /* -v */
Definition at line 455 of file lua.c.
lua_c
#define lua_c
Definition at line 7 of file lua.c.
lua_freeline
#define lua_freeline (L, b) { (void)L; (void)b; }
Definition at line 94 of file lua.c.
LUA_INIT_VAR
#define LUA_INIT_VAR "LUA_INIT"
Definition at line 38 of file lua.c.
LUA_INITVARVERSION
#define LUA_INITVARVERSION LUA_INIT_VAR LUA_VERSUFFIX
Definition at line 41 of file lua.c.
LUA_MAXINPUT
#define LUA_MAXINPUT 512
Definition at line 34 of file lua.c.
LUA_PROGNAME
#define LUA_PROGNAME "lua"
Definition at line 30 of file lua.c.
LUA_PROMPT
#define LUA_PROMPT "> "
Definition at line 25 of file lua.c.
LUA_PROMPT2
#define LUA_PROMPT2 ">> "
Definition at line 26 of file lua.c.
lua_readline
#define lua_readline (L, b, p)
Value:
((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
        fgets(b, LUA_MAXINPUT, stdin) != NULL)  /* get line */
Definition at line 90 of file lua.c.
lua_saveline
#define lua_saveline (L, line) { (void)L; (void)line; }
Definition at line 93 of file lua.c.
lua_stdin_is_tty
#define lua_stdin_is_tty () 1 /* assume stdin is a tty */
Definition at line 65 of file lua.c.
marklen
#define marklen (sizeof(EOFMARK)/sizeof(char) - 1)
Definition at line 283 of file lua.c.
Function Documentation
addreturn()
static int addreturn (lua_State * L) static
Definition at line 332 of file lua.c.
Referenced by loadline().
collectargs()
static int collectargs (char ** argv, int * first) static
Definition at line 465 of file lua.c.
Referenced by pmain().
createargtable()
static void createargtable (lua_State * L, char ** argv, int argc, int script) static
Definition at line 226 of file lua.c.
Referenced by pmain().
docall()
static int docall (lua_State * L, int narg, int nres) static
Definition at line 198 of file lua.c.
Referenced by dochunk(), dolibrary(), doREPL(), and handle_script().
dochunk()
static int dochunk (lua_State * L, int status) static
Definition at line 239 of file lua.c.
Referenced by dofile(), and dostring().
dofile()
static int dofile (lua_State * L, const char * name) static
Definition at line 245 of file lua.c.
Referenced by handle_luainit(), and pmain().
dolibrary()
static int dolibrary (lua_State * L, const char * name) static
Definition at line 259 of file lua.c.
Referenced by runargs().
doREPL()
static void doREPL (lua_State * L) static
Definition at line 405 of file lua.c.
Referenced by pmain().
dostring()
static int dostring (lua_State * L, const char * s, const char * name) static
Definition at line 250 of file lua.c.
Referenced by handle_luainit(), and runargs().
get_prompt()
static const char* get_prompt (lua_State * L, int firstline) static
Definition at line 273 of file lua.c.
Referenced by pushline().
handle_luainit()
static int handle_luainit (lua_State * L) static
Definition at line 535 of file lua.c.
Referenced by pmain().
handle_script()
static int handle_script (lua_State * L, char ** argv) static
Definition at line 437 of file lua.c.
Referenced by pmain().
incomplete()
static int incomplete (lua_State * L, int status) static
Definition at line 291 of file lua.c.
Referenced by multiline().
l_message()
static void l_message (const char * pname, const char * msg) static
Definition at line 155 of file lua.c.
Referenced by l_print(), main(), and report().
l_print()
static void l_print (lua_State * L) static
Definition at line 388 of file lua.c.
Referenced by doREPL().
laction()
static void laction (int i) static
Definition at line 124 of file lua.c.
Referenced by docall().
loadline()
static int loadline (lua_State * L) static
Definition at line 372 of file lua.c.
Referenced by doREPL().
lstop()
static void lstop (lua_State * L, lua_Debug * ar) static
Definition at line 111 of file lua.c.
Referenced by laction().
main()
int main (int argc, char ** argv)
Definition at line 596 of file lua.c.
msghandler()
static int msghandler (lua_State * L) static
Definition at line 179 of file lua.c.
Referenced by docall().
multiline()
static int multiline (lua_State * L) static
Definition at line 350 of file lua.c.
Referenced by loadline().
pmain()
static int pmain (lua_State * L) static
Definition at line 554 of file lua.c.
Referenced by main().
print_usage()
static void print_usage (const char * badoption) static
Definition at line 130 of file lua.c.
Referenced by pmain().
print_version()
static void print_version (void) static
Definition at line 212 of file lua.c.
Referenced by pmain().
pushargs()
static int pushargs (lua_State * L) static
Definition at line 424 of file lua.c.
Referenced by handle_script().
pushline()
static int pushline (lua_State * L, int firstline) static
Definition at line 307 of file lua.c.
Referenced by loadline(), and multiline().
report()
static int report (lua_State * L, int status) static
Definition at line 166 of file lua.c.
Referenced by AP_Arming::airspeed_checks(), AP_Arming::barometer_checks(), AP_Arming::battery_checks(), AP_Arming::board_voltage_checks(), AP_Arming::can_checks(), AP_Arming::check_failed(), AP_Arming::compass_checks(), dochunk(), dolibrary(), doREPL(), AP_Arming::gps_checks(), handle_script(), AP_Arming::hardware_safety_check(), AP_Arming::ins_checks(), AP_Arming::logging_checks(), main(), AP_Arming::manual_transmitter_checks(), AP_Arming::mission_checks(), AP_Arming::pre_arm_checks(), AP_Arming::proximity_checks(), AP_Arming::rc_calibration_checks(), AP_ADC_ADS1115::read(), AP_Arming::servo_checks(), and AP_Arming::system_checks().
runargs()
static int runargs (lua_State * L, char ** argv, int n) static
Definition at line 514 of file lua.c.
Referenced by pmain().
Variable Documentation
globalL
lua_State* globalL = NULL static
Definition at line 103 of file lua.c.
Referenced by docall(), and laction().
progname
const char* progname = LUA_PROGNAME static
Definition at line 105 of file lua.c.
Referenced by doREPL(), AP_HAL::dump_stack_trace(), l_print(), pmain(), print_usage(), and report().