APM:Libraries: libraries/AP_Scripting/lua_generated_bindings.cpp File Reference
lua_generated_bindings.cpp File Reference
#include "lua_generated_bindings.h"
#include "lua_boxed_numerics.h"
#include <GCS_MAVLink/GCS.h>
#include <AP_Relay/AP_Relay.h>
#include <AP_Terrain/AP_Terrain.h>
#include <AP_RangeFinder/AP_RangeFinder.h>
#include <AP_Notify/AP_Notify.h>
#include <AP_Math/AP_Math.h>
#include <AP_GPS/AP_GPS.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_Common/Location.h>
Classes
struct userdata_fun
struct singleton_fun
struct userdata
Functions
static int binding_argcheck (lua_State *L, int expected_arg_count)
int new_Vector2f (lua_State *L)
int new_Vector3f (lua_State *L)
int new_Location (lua_State *L)
Vector2f * check_Vector2f (lua_State *L, int arg)
Vector3f * check_Vector3f (lua_State *L, int arg)
Location * check_Location (lua_State *L, int arg)
static int Vector2f_y (lua_State *L)
static int Vector2f_x (lua_State *L)
static int Vector3f_z (lua_State *L)
static int Vector3f_y (lua_State *L)
static int Vector3f_x (lua_State *L)
static int Location_loiter_xtrack (lua_State *L)
static int Location_origin_alt (lua_State *L)
static int Location_terrain_alt (lua_State *L)
static int Location_relative_alt (lua_State *L)
static int Location_lng (lua_State *L)
static int Location_lat (lua_State *L)
static int Vector2f_is_zero (lua_State *L)
static int Vector2f_is_inf (lua_State *L)
static int Vector2f_is_nan (lua_State *L)
static int Vector2f_normalize (lua_State *L)
static int Vector2f_length (lua_State *L)
static int Vector2f___add (lua_State *L)
static int Vector2f___sub (lua_State *L)
static int Vector3f_is_zero (lua_State *L)
static int Vector3f_is_inf (lua_State *L)
static int Vector3f_is_nan (lua_State *L)
static int Vector3f_normalize (lua_State *L)
static int Vector3f_length (lua_State *L)
static int Vector3f___add (lua_State *L)
static int Vector3f___sub (lua_State *L)
static int Location_get_vector_from_origin_NEU (lua_State *L)
static int Location_offset (lua_State *L)
static int Location_get_distance (lua_State *L)
static int GCS_send_text (lua_State *L)
static int AP_Relay_toggle (lua_State *L)
static int AP_Relay_enabled (lua_State *L)
static int AP_Relay_off (lua_State *L)
static int AP_Relay_on (lua_State *L)
static int AP_Terrain_height_above_terrain (lua_State *L)
static int AP_Terrain_height_relative_home_equivalent (lua_State *L)
static int AP_Terrain_height_terrain_difference_home (lua_State *L)
static int AP_Terrain_height_amsl (lua_State *L)
static int AP_Terrain_status (lua_State *L)
static int AP_Terrain_enabled (lua_State *L)
static int RangeFinder_num_sensors (lua_State *L)
static int AP_Notify_play_tune (lua_State *L)
static int AP_GPS_first_unconfigured_gps (lua_State *L)
static int AP_GPS_all_configured (lua_State *L)
static int AP_GPS_get_antenna_offset (lua_State *L)
static int AP_GPS_have_vertical_velocity (lua_State *L)
static int AP_GPS_last_message_time_ms (lua_State *L)
static int AP_GPS_last_fix_time_ms (lua_State *L)
static int AP_GPS_get_vdop (lua_State *L)
static int AP_GPS_get_hdop (lua_State *L)
static int AP_GPS_time_week_ms (lua_State *L)
static int AP_GPS_time_week (lua_State *L)
static int AP_GPS_num_sats (lua_State *L)
static int AP_GPS_ground_course (lua_State *L)
static int AP_GPS_ground_speed (lua_State *L)
static int AP_GPS_velocity (lua_State *L)
static int AP_GPS_vertical_accuracy (lua_State *L)
static int AP_GPS_horizontal_accuracy (lua_State *L)
static int AP_GPS_speed_accuracy (lua_State *L)
static int AP_GPS_location (lua_State *L)
static int AP_GPS_status (lua_State *L)
static int AP_GPS_primary_sensor (lua_State *L)
static int AP_GPS_num_sensors (lua_State *L)
static int AP_BattMonitor_get_temperature (lua_State *L)
static int AP_BattMonitor_overpower_detected (lua_State *L)
static int AP_BattMonitor_has_failsafed (lua_State *L)
static int AP_BattMonitor_pack_capacity_mah (lua_State *L)
static int AP_BattMonitor_capacity_remaining_pct (lua_State *L)
static int AP_BattMonitor_consumed_wh (lua_State *L)
static int AP_BattMonitor_consumed_mah (lua_State *L)
static int AP_BattMonitor_current_amps (lua_State *L)
static int AP_BattMonitor_voltage_resting_estimate (lua_State *L)
static int AP_BattMonitor_voltage (lua_State *L)
static int AP_BattMonitor_has_current (lua_State *L)
static int AP_BattMonitor_has_consumed_energy (lua_State *L)
static int AP_BattMonitor_healthy (lua_State *L)
static int AP_BattMonitor_num_instances (lua_State *L)
static int AP_AHRS_prearm_healthy (lua_State *L)
static int AP_AHRS_home_is_set (lua_State *L)
static int AP_AHRS_get_relative_position_NED_home (lua_State *L)
static int AP_AHRS_get_velocity_NED (lua_State *L)
static int AP_AHRS_groundspeed_vector (lua_State *L)
static int AP_AHRS_wind_estimate (lua_State *L)
static int AP_AHRS_get_hagl (lua_State *L)
static int AP_AHRS_get_gyro (lua_State *L)
static int AP_AHRS_get_home (lua_State *L)
static int AP_AHRS_get_position (lua_State *L)
void load_generated_bindings (lua_State *L)
void load_generated_sandbox (lua_State *L)
Variables
const luaL_Reg Vector2f_meta []
const luaL_Reg Vector3f_meta []
const luaL_Reg Location_meta []
const luaL_Reg GCS_meta []
const luaL_Reg AP_Relay_meta []
const luaL_Reg AP_Terrain_meta []
const luaL_Reg RangeFinder_meta []
const luaL_Reg AP_Notify_meta []
const luaL_Reg notify_meta []
const luaL_Reg AP_GPS_meta []
const luaL_Reg AP_BattMonitor_meta []
const luaL_Reg AP_AHRS_meta []
const struct userdata_fun userdata_fun []
const struct singleton_fun singleton_fun []
const char * singletons []
const struct userdata new_userdata []
Function Documentation
AP_AHRS_get_gyro()
static int AP_AHRS_get_gyro (lua_State * L) static
Definition at line 1496 of file lua_generated_bindings.cpp.
AP_AHRS_get_hagl()
static int AP_AHRS_get_hagl (lua_State * L) static
Definition at line 1474 of file lua_generated_bindings.cpp.
AP_AHRS_get_home()
static int AP_AHRS_get_home (lua_State * L) static
Definition at line 1513 of file lua_generated_bindings.cpp.
AP_AHRS_get_position()
static int AP_AHRS_get_position (lua_State * L) static
Definition at line 1530 of file lua_generated_bindings.cpp.
AP_AHRS_get_relative_position_NED_home()
static int AP_AHRS_get_relative_position_NED_home (lua_State * L) static
Definition at line 1394 of file lua_generated_bindings.cpp.
AP_AHRS_get_velocity_NED()
static int AP_AHRS_get_velocity_NED (lua_State * L) static
Definition at line 1417 of file lua_generated_bindings.cpp.
AP_AHRS_groundspeed_vector()
static int AP_AHRS_groundspeed_vector (lua_State * L) static
Definition at line 1440 of file lua_generated_bindings.cpp.
AP_AHRS_home_is_set()
static int AP_AHRS_home_is_set (lua_State * L) static
Definition at line 1378 of file lua_generated_bindings.cpp.
AP_AHRS_prearm_healthy()
static int AP_AHRS_prearm_healthy (lua_State * L) static
Definition at line 1362 of file lua_generated_bindings.cpp.
AP_AHRS_wind_estimate()
static int AP_AHRS_wind_estimate (lua_State * L) static
Definition at line 1457 of file lua_generated_bindings.cpp.
AP_BattMonitor_capacity_remaining_pct()
static int AP_BattMonitor_capacity_remaining_pct (lua_State * L) static
Definition at line 1186 of file lua_generated_bindings.cpp.
AP_BattMonitor_consumed_mah()
static int AP_BattMonitor_consumed_mah (lua_State * L) static
Definition at line 1222 of file lua_generated_bindings.cpp.
AP_BattMonitor_consumed_wh()
static int AP_BattMonitor_consumed_wh (lua_State * L) static
Definition at line 1204 of file lua_generated_bindings.cpp.
AP_BattMonitor_current_amps()
static int AP_BattMonitor_current_amps (lua_State * L) static
Definition at line 1240 of file lua_generated_bindings.cpp.
AP_BattMonitor_get_temperature()
static int AP_BattMonitor_get_temperature (lua_State * L) static
Definition at line 1111 of file lua_generated_bindings.cpp.
AP_BattMonitor_has_consumed_energy()
static int AP_BattMonitor_has_consumed_energy (lua_State * L) static
Definition at line 1312 of file lua_generated_bindings.cpp.
AP_BattMonitor_has_current()
static int AP_BattMonitor_has_current (lua_State * L) static
Definition at line 1294 of file lua_generated_bindings.cpp.
AP_BattMonitor_has_failsafed()
static int AP_BattMonitor_has_failsafed (lua_State * L) static
Definition at line 1154 of file lua_generated_bindings.cpp.
AP_BattMonitor_healthy()
static int AP_BattMonitor_healthy (lua_State * L) static
Definition at line 1330 of file lua_generated_bindings.cpp.
AP_BattMonitor_num_instances()
static int AP_BattMonitor_num_instances (lua_State * L) static
Definition at line 1348 of file lua_generated_bindings.cpp.
AP_BattMonitor_overpower_detected()
static int AP_BattMonitor_overpower_detected (lua_State * L) static
Definition at line 1136 of file lua_generated_bindings.cpp.
AP_BattMonitor_pack_capacity_mah()
static int AP_BattMonitor_pack_capacity_mah (lua_State * L) static
Definition at line 1168 of file lua_generated_bindings.cpp.
AP_BattMonitor_voltage()
static int AP_BattMonitor_voltage (lua_State * L) static
Definition at line 1276 of file lua_generated_bindings.cpp.
AP_BattMonitor_voltage_resting_estimate()
static int AP_BattMonitor_voltage_resting_estimate (lua_State * L) static
Definition at line 1258 of file lua_generated_bindings.cpp.
AP_GPS_all_configured()
static int AP_GPS_all_configured (lua_State * L) static
Definition at line 736 of file lua_generated_bindings.cpp.
AP_GPS_first_unconfigured_gps()
static int AP_GPS_first_unconfigured_gps (lua_State * L) static
Definition at line 722 of file lua_generated_bindings.cpp.
AP_GPS_get_antenna_offset()
static int AP_GPS_get_antenna_offset (lua_State * L) static
Definition at line 750 of file lua_generated_bindings.cpp.
AP_GPS_get_hdop()
static int AP_GPS_get_hdop (lua_State * L) static
Definition at line 843 of file lua_generated_bindings.cpp.
AP_GPS_get_vdop()
static int AP_GPS_get_vdop (lua_State * L) static
Definition at line 825 of file lua_generated_bindings.cpp.
AP_GPS_ground_course()
static int AP_GPS_ground_course (lua_State * L) static
Definition at line 916 of file lua_generated_bindings.cpp.
AP_GPS_ground_speed()
static int AP_GPS_ground_speed (lua_State * L) static
Definition at line 934 of file lua_generated_bindings.cpp.
AP_GPS_have_vertical_velocity()
static int AP_GPS_have_vertical_velocity (lua_State * L) static
Definition at line 769 of file lua_generated_bindings.cpp.
AP_GPS_horizontal_accuracy()
static int AP_GPS_horizontal_accuracy (lua_State * L) static
Definition at line 996 of file lua_generated_bindings.cpp.
AP_GPS_last_fix_time_ms()
static int AP_GPS_last_fix_time_ms (lua_State * L) static
Definition at line 806 of file lua_generated_bindings.cpp.
AP_GPS_last_message_time_ms()
static int AP_GPS_last_message_time_ms (lua_State * L) static
Definition at line 787 of file lua_generated_bindings.cpp.
AP_GPS_location()
static int AP_GPS_location (lua_State * L) static
Definition at line 1046 of file lua_generated_bindings.cpp.
AP_GPS_num_sats()
static int AP_GPS_num_sats (lua_State * L) static
Definition at line 898 of file lua_generated_bindings.cpp.
AP_GPS_num_sensors()
static int AP_GPS_num_sensors (lua_State * L) static
Definition at line 1097 of file lua_generated_bindings.cpp.
AP_GPS_primary_sensor()
static int AP_GPS_primary_sensor (lua_State * L) static
Definition at line 1083 of file lua_generated_bindings.cpp.
AP_GPS_speed_accuracy()
static int AP_GPS_speed_accuracy (lua_State * L) static
Definition at line 1021 of file lua_generated_bindings.cpp.
AP_GPS_status()
static int AP_GPS_status (lua_State * L) static
Definition at line 1065 of file lua_generated_bindings.cpp.
AP_GPS_time_week()
static int AP_GPS_time_week (lua_State * L) static
Definition at line 880 of file lua_generated_bindings.cpp.
AP_GPS_time_week_ms()
static int AP_GPS_time_week_ms (lua_State * L) static
Definition at line 861 of file lua_generated_bindings.cpp.
AP_GPS_velocity()
static int AP_GPS_velocity (lua_State * L) static
Definition at line 952 of file lua_generated_bindings.cpp.
AP_GPS_vertical_accuracy()
static int AP_GPS_vertical_accuracy (lua_State * L) static
Definition at line 971 of file lua_generated_bindings.cpp.
AP_Notify_play_tune()
static int AP_Notify_play_tune (lua_State * L) static
Definition at line 707 of file lua_generated_bindings.cpp.
AP_Relay_enabled()
static int AP_Relay_enabled (lua_State * L) static
Definition at line 513 of file lua_generated_bindings.cpp.
AP_Relay_off()
static int AP_Relay_off (lua_State * L) static
Definition at line 531 of file lua_generated_bindings.cpp.
AP_Relay_on()
static int AP_Relay_on (lua_State * L) static
Definition at line 548 of file lua_generated_bindings.cpp.
AP_Relay_toggle()
static int AP_Relay_toggle (lua_State * L) static
Definition at line 496 of file lua_generated_bindings.cpp.
AP_Terrain_enabled()
static int AP_Terrain_enabled (lua_State * L) static
Definition at line 679 of file lua_generated_bindings.cpp.
AP_Terrain_height_above_terrain()
static int AP_Terrain_height_above_terrain (lua_State * L) static
Definition at line 565 of file lua_generated_bindings.cpp.
AP_Terrain_height_amsl()
static int AP_Terrain_height_amsl (lua_State * L) static
Definition at line 639 of file lua_generated_bindings.cpp.
AP_Terrain_height_relative_home_equivalent()
static int AP_Terrain_height_relative_home_equivalent (lua_State * L) static
Definition at line 588 of file lua_generated_bindings.cpp.
AP_Terrain_height_terrain_difference_home()
static int AP_Terrain_height_terrain_difference_home (lua_State * L) static
Definition at line 616 of file lua_generated_bindings.cpp.
AP_Terrain_status()
static int AP_Terrain_status (lua_State * L) static
Definition at line 665 of file lua_generated_bindings.cpp.
binding_argcheck()
static int binding_argcheck (lua_State * L, int expected_arg_count) static
Definition at line 16 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_gyro(), AP_AHRS_get_hagl(), AP_AHRS_get_home(), AP_AHRS_get_position(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_groundspeed_vector(), AP_AHRS_home_is_set(), AP_AHRS_prearm_healthy(), AP_AHRS_wind_estimate(), AP_BattMonitor_capacity_remaining_pct(), AP_BattMonitor_consumed_mah(), AP_BattMonitor_consumed_wh(), AP_BattMonitor_current_amps(), AP_BattMonitor_get_temperature(), AP_BattMonitor_has_consumed_energy(), AP_BattMonitor_has_current(), AP_BattMonitor_has_failsafed(), AP_BattMonitor_healthy(), AP_BattMonitor_num_instances(), AP_BattMonitor_overpower_detected(), AP_BattMonitor_pack_capacity_mah(), AP_BattMonitor_voltage(), AP_BattMonitor_voltage_resting_estimate(), AP_GPS_all_configured(), AP_GPS_first_unconfigured_gps(), AP_GPS_get_antenna_offset(), AP_GPS_get_hdop(), AP_GPS_get_vdop(), AP_GPS_ground_course(), AP_GPS_ground_speed(), AP_GPS_have_vertical_velocity(), AP_GPS_horizontal_accuracy(), AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_location(), AP_GPS_num_sats(), AP_GPS_num_sensors(), AP_GPS_primary_sensor(), AP_GPS_speed_accuracy(), AP_GPS_status(), AP_GPS_time_week(), AP_GPS_time_week_ms(), AP_GPS_velocity(), AP_GPS_vertical_accuracy(), AP_Notify_play_tune(), AP_Relay_enabled(), AP_Relay_off(), AP_Relay_on(), AP_Relay_toggle(), AP_Terrain_enabled(), AP_Terrain_height_above_terrain(), AP_Terrain_height_amsl(), AP_Terrain_height_relative_home_equivalent(), AP_Terrain_height_terrain_difference_home(), AP_Terrain_status(), GCS_send_text(), Location_get_distance(), Location_get_vector_from_origin_NEU(), Location_offset(), RangeFinder_num_sensors(), Vector2f___add(), Vector2f___sub(), Vector2f_is_inf(), Vector2f_is_nan(), Vector2f_is_zero(), Vector2f_length(), Vector2f_normalize(), Vector3f___add(), Vector3f___sub(), Vector3f_is_inf(), Vector3f_is_nan(), Vector3f_is_zero(), Vector3f_length(), and Vector3f_normalize().
check_Location()
Location* check_Location (lua_State * L, int arg)
Definition at line 66 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_home(), AP_AHRS_get_position(), AP_GPS_location(), AP_Terrain_height_amsl(), Location_get_distance(), Location_get_vector_from_origin_NEU(), Location_lat(), Location_lng(), Location_loiter_xtrack(), Location_offset(), Location_origin_alt(), Location_relative_alt(), and Location_terrain_alt().
check_Vector2f()
Vector2f* check_Vector2f (lua_State * L, int arg)
Definition at line 56 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_groundspeed_vector(), Vector2f___add(), Vector2f___sub(), Vector2f_is_inf(), Vector2f_is_nan(), Vector2f_is_zero(), Vector2f_length(), Vector2f_normalize(), Vector2f_x(), and Vector2f_y().
check_Vector3f()
Vector3f* check_Vector3f (lua_State * L, int arg)
Definition at line 61 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_gyro(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_wind_estimate(), AP_GPS_get_antenna_offset(), AP_GPS_velocity(), Location_get_vector_from_origin_NEU(), Vector3f___add(), Vector3f___sub(), Vector3f_is_inf(), Vector3f_is_nan(), Vector3f_is_zero(), Vector3f_length(), Vector3f_normalize(), Vector3f_x(), Vector3f_y(), and Vector3f_z().
GCS_send_text()
static int GCS_send_text (lua_State * L) static
Definition at line 476 of file lua_generated_bindings.cpp.
load_generated_bindings()
void load_generated_bindings (lua_State * L)
Definition at line 1671 of file lua_generated_bindings.cpp.
Referenced by load_lua_bindings().
load_generated_sandbox()
void load_generated_sandbox (lua_State * L)
Definition at line 1721 of file lua_generated_bindings.cpp.
Referenced by lua_scripts::load_script().
Location_get_distance()
static int Location_get_distance (lua_State * L) static
Definition at line 424 of file lua_generated_bindings.cpp.
Location_get_vector_from_origin_NEU()
static int Location_get_vector_from_origin_NEU (lua_State * L) static
Definition at line 389 of file lua_generated_bindings.cpp.
Location_lat()
static int Location_lat (lua_State * L) static
Definition at line 243 of file lua_generated_bindings.cpp.
Location_lng()
static int Location_lng (lua_State * L) static
Definition at line 225 of file lua_generated_bindings.cpp.
Location_loiter_xtrack()
static int Location_loiter_xtrack (lua_State * L) static
Definition at line 161 of file lua_generated_bindings.cpp.
Location_offset()
static int Location_offset (lua_State * L) static
Definition at line 406 of file lua_generated_bindings.cpp.
Location_origin_alt()
static int Location_origin_alt (lua_State * L) static
Definition at line 177 of file lua_generated_bindings.cpp.
Location_relative_alt()
static int Location_relative_alt (lua_State * L) static
Definition at line 209 of file lua_generated_bindings.cpp.
Location_terrain_alt()
static int Location_terrain_alt (lua_State * L) static
Definition at line 193 of file lua_generated_bindings.cpp.
new_Location()
int new_Location (lua_State * L)
Definition at line 46 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_home(), AP_AHRS_get_position(), and AP_GPS_location().
new_Vector2f()
int new_Vector2f (lua_State * L)
Definition at line 26 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_groundspeed_vector(), Vector2f___add(), and Vector2f___sub().
new_Vector3f()
int new_Vector3f (lua_State * L)
Definition at line 36 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_gyro(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_wind_estimate(), AP_GPS_get_antenna_offset(), AP_GPS_velocity(), Location_get_vector_from_origin_NEU(), Vector3f___add(), and Vector3f___sub().
RangeFinder_num_sensors()
static int RangeFinder_num_sensors (lua_State * L) static
Definition at line 693 of file lua_generated_bindings.cpp.
Vector2f___add()
static int Vector2f___add (lua_State * L) static
Definition at line 307 of file lua_generated_bindings.cpp.
Vector2f___sub()
static int Vector2f___sub (lua_State * L) static
Definition at line 316 of file lua_generated_bindings.cpp.
Vector2f_is_inf()
static int Vector2f_is_inf (lua_State * L) static
Definition at line 270 of file lua_generated_bindings.cpp.
Vector2f_is_nan()
static int Vector2f_is_nan (lua_State * L) static
Definition at line 279 of file lua_generated_bindings.cpp.
Vector2f_is_zero()
static int Vector2f_is_zero (lua_State * L) static
Definition at line 261 of file lua_generated_bindings.cpp.
Vector2f_length()
static int Vector2f_length (lua_State * L) static
Definition at line 297 of file lua_generated_bindings.cpp.
Vector2f_normalize()
static int Vector2f_normalize (lua_State * L) static
Definition at line 288 of file lua_generated_bindings.cpp.
Vector2f_x()
static int Vector2f_x (lua_State * L) static
Definition at line 89 of file lua_generated_bindings.cpp.
Vector2f_y()
static int Vector2f_y (lua_State * L) static
Definition at line 71 of file lua_generated_bindings.cpp.
Vector3f___add()
static int Vector3f___add (lua_State * L) static
Definition at line 371 of file lua_generated_bindings.cpp.
Vector3f___sub()
static int Vector3f___sub (lua_State * L) static
Definition at line 380 of file lua_generated_bindings.cpp.
Vector3f_is_inf()
static int Vector3f_is_inf (lua_State * L) static
Definition at line 334 of file lua_generated_bindings.cpp.
Vector3f_is_nan()
static int Vector3f_is_nan (lua_State * L) static
Definition at line 343 of file lua_generated_bindings.cpp.
Vector3f_is_zero()
static int Vector3f_is_zero (lua_State * L) static
Definition at line 325 of file lua_generated_bindings.cpp.
Vector3f_length()
static int Vector3f_length (lua_State * L) static
Definition at line 361 of file lua_generated_bindings.cpp.
Vector3f_normalize()
static int Vector3f_normalize (lua_State * L) static
Definition at line 352 of file lua_generated_bindings.cpp.
Vector3f_x()
static int Vector3f_x (lua_State * L) static
Definition at line 143 of file lua_generated_bindings.cpp.
Vector3f_y()
static int Vector3f_y (lua_State * L) static
Definition at line 125 of file lua_generated_bindings.cpp.
Vector3f_z()
static int Vector3f_z (lua_State * L) static
Definition at line 107 of file lua_generated_bindings.cpp.
Variable Documentation
AP_AHRS_meta
const luaL_Reg AP_AHRS_meta[]
Initial value:
= {
    {"prearm_healthy", AP_AHRS_prearm_healthy},
    {"home_is_set", AP_AHRS_home_is_set},
    {"get_relative_position_NED_home", AP_AHRS_get_relative_position_NED_home},
    {"get_velocity_NED", AP_AHRS_get_velocity_NED},
    {"groundspeed_vector", AP_AHRS_groundspeed_vector},
    {"wind_estimate", AP_AHRS_wind_estimate},
    {"get_hagl", AP_AHRS_get_hagl},
    {"get_gyro", AP_AHRS_get_gyro},
    {"get_home", AP_AHRS_get_home},
    {"get_position", AP_AHRS_get_position},
    {NULL, NULL}
}
Definition at line 1633 of file lua_generated_bindings.cpp.
AP_BattMonitor_meta
const luaL_Reg AP_BattMonitor_meta[]
Initial value:
= {
    {"get_temperature", AP_BattMonitor_get_temperature},
    {"overpower_detected", AP_BattMonitor_overpower_detected},
    {"has_failsafed", AP_BattMonitor_has_failsafed},
    {"pack_capacity_mah", AP_BattMonitor_pack_capacity_mah},
    {"capacity_remaining_pct", AP_BattMonitor_capacity_remaining_pct},
    {"consumed_wh", AP_BattMonitor_consumed_wh},
    {"consumed_mah", AP_BattMonitor_consumed_mah},
    {"current_amps", AP_BattMonitor_current_amps},
    {"voltage_resting_estimate", AP_BattMonitor_voltage_resting_estimate},
    {"voltage", AP_BattMonitor_voltage},
    {"has_current", AP_BattMonitor_has_current},
    {"has_consumed_energy", AP_BattMonitor_has_consumed_energy},
    {"healthy", AP_BattMonitor_healthy},
    {"num_instances", AP_BattMonitor_num_instances},
    {NULL, NULL}
}
Definition at line 1615 of file lua_generated_bindings.cpp.
AP_GPS_meta
const luaL_Reg AP_GPS_meta[]
Initial value:
= {
    {"first_unconfigured_gps", AP_GPS_first_unconfigured_gps},
    {"all_configured", AP_GPS_all_configured},
    {"get_antenna_offset", AP_GPS_get_antenna_offset},
    {"have_vertical_velocity", AP_GPS_have_vertical_velocity},
    {"last_message_time_ms", AP_GPS_last_message_time_ms},
    {"last_fix_time_ms", AP_GPS_last_fix_time_ms},
    {"get_vdop", AP_GPS_get_vdop},
    {"get_hdop", AP_GPS_get_hdop},
    {"time_week_ms", AP_GPS_time_week_ms},
    {"time_week", AP_GPS_time_week},
    {"num_sats", AP_GPS_num_sats},
    {"ground_course", AP_GPS_ground_course},
    {"ground_speed", AP_GPS_ground_speed},
    {"velocity", AP_GPS_velocity},
    {"vertical_accuracy", AP_GPS_vertical_accuracy},
    {"horizontal_accuracy", AP_GPS_horizontal_accuracy},
    {"speed_accuracy", AP_GPS_speed_accuracy},
    {"location", AP_GPS_location},
    {"status", AP_GPS_status},
    {"primary_sensor", AP_GPS_primary_sensor},
    {"num_sensors", AP_GPS_num_sensors},
    {NULL, NULL}
}
Definition at line 1590 of file lua_generated_bindings.cpp.
AP_Notify_meta
const luaL_Reg AP_Notify_meta[]
Initial value:
= {
    {"play_tune", AP_Notify_play_tune},
    {NULL, NULL}
}
Definition at line 1581 of file lua_generated_bindings.cpp.
AP_Relay_meta
const luaL_Reg AP_Relay_meta[]
Initial value:
= {
    {"toggle", AP_Relay_toggle},
    {"enabled", AP_Relay_enabled},
    {"off", AP_Relay_off},
    {"on", AP_Relay_on},
    {NULL, NULL}
}
Definition at line 1558 of file lua_generated_bindings.cpp.
AP_Terrain_meta
const luaL_Reg AP_Terrain_meta[]
Initial value:
= {
    {"height_above_terrain", AP_Terrain_height_above_terrain},
    {"height_relative_home_equivalent", AP_Terrain_height_relative_home_equivalent},
    {"height_terrain_difference_home", AP_Terrain_height_terrain_difference_home},
    {"height_amsl", AP_Terrain_height_amsl},
    {"status", AP_Terrain_status},
    {"enabled", AP_Terrain_enabled},
    {NULL, NULL}
}
Definition at line 1566 of file lua_generated_bindings.cpp.
GCS_meta
const luaL_Reg GCS_meta[]
Initial value:
= {
    {"send_text", GCS_send_text},
    {NULL, NULL}
}
Definition at line 1553 of file lua_generated_bindings.cpp.
Location_meta
const luaL_Reg Location_meta[]
Initial value:
= {
    {"loiter_xtrack", Location_loiter_xtrack},
    {"origin_alt", Location_origin_alt},
    {"terrain_alt", Location_terrain_alt},
    {"relative_alt", Location_relative_alt},
    {"lng", Location_lng},
    {"lat", Location_lat},
    {"get_vector_from_origin_NEU", Location_get_vector_from_origin_NEU},
    {"offset", Location_offset},
    {"get_distance", Location_get_distance},
    {NULL, NULL}
}
Definition at line 463 of file lua_generated_bindings.cpp.
new_userdata
const struct userdata new_userdata[]
Initial value:
= {
    {"Vector2f", new_Vector2f},
    {"Vector3f", new_Vector3f},
    {"Location", new_Location},
}
Referenced by load_generated_sandbox().
notify_meta
const luaL_Reg notify_meta[]
Initial value:
= {
    {NULL, NULL}
}
Definition at line 1586 of file lua_generated_bindings.cpp.
RangeFinder_meta
const luaL_Reg RangeFinder_meta[]
Initial value:
= {
    {"num_sensors", RangeFinder_num_sensors},
    {NULL, NULL}
}
Definition at line 1576 of file lua_generated_bindings.cpp.
singleton_fun
const struct singleton_fun singleton_fun[]
Initial value:
= {
    {"gcs", GCS_meta},
    {"relay", AP_Relay_meta},
    {"terrain", AP_Terrain_meta},
    {"rangefinder", RangeFinder_meta},
    {"AP_Notify", AP_Notify_meta},
    {"notify", notify_meta},
    {"gps", AP_GPS_meta},
    {"battery", AP_BattMonitor_meta},
    {"ahrs", AP_AHRS_meta},
}
singletons
const char* singletons[]
Initial value:
= {
    "gcs",
    "relay",
    "terrain",
    "rangefinder",
    "AP_Notify",
    "notify",
    "gps",
    "battery",
    "ahrs",
}
Definition at line 1700 of file lua_generated_bindings.cpp.
Referenced by load_generated_sandbox().
userdata_fun
const struct userdata_fun userdata_fun[]
Initial value:
= {
    {"Vector2f", Vector2f_meta},
    {"Vector3f", Vector3f_meta},
    {"Location", Location_meta},
}
Vector2f_meta
const luaL_Reg Vector2f_meta[]
Initial value:
= {
    {"y", Vector2f_y},
    {"x", Vector2f_x},
    {"is_zero", Vector2f_is_zero},
    {"is_inf", Vector2f_is_inf},
    {"is_nan", Vector2f_is_nan},
    {"normalize", Vector2f_normalize},
    {"length", Vector2f_length},
    {"__add", Vector2f___add},
    {"__sub", Vector2f___sub},
    {NULL, NULL}
}
Definition at line 436 of file lua_generated_bindings.cpp.
Vector3f_meta
const luaL_Reg Vector3f_meta[]
Initial value:
= {
    {"z", Vector3f_z},
    {"y", Vector3f_y},
    {"x", Vector3f_x},
    {"is_zero", Vector3f_is_zero},
    {"is_inf", Vector3f_is_inf},
    {"is_nan", Vector3f_is_nan},
    {"normalize", Vector3f_normalize},
    {"length", Vector3f_length},
    {"__add", Vector3f___add},
    {"__sub", Vector3f___sub},
    {NULL, NULL}
}
Definition at line 449 of file lua_generated_bindings.cpp.