APM:Libraries: libraries/AP_Scripting/lua_boxed_numerics.cpp File Reference
lua_boxed_numerics.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "lua_boxed_numerics.h"
Macros
#define UINT32_T_BOX_OP(name, sym)
#define UINT32_T_BOX_OP_BOOL(name, sym)
#define UINT32_T_BOX_OP_UNARY(name, sym)
Functions
int new_uint32_t (lua_State *L)
uint32_t * check_uint32_t (lua_State *L, int arg)
static uint32_t coerce_to_uint32_t (lua_State *L, int arg)
static int uint32_t_toint (lua_State *L)
static int uint32_t_tofloat (lua_State *L)
static int uint32_t___tostring (lua_State *L)
void load_boxed_numerics (lua_State *L)
void load_boxed_numerics_sandbox (lua_State *L)
Variables
const AP_HAL::HAL & hal
const luaL_Reg uint32_t_meta []
Macro Definition Documentation
UINT32_T_BOX_OP
#define UINT32_T_BOX_OP (name, sym)
Value:
static int uint32_t___##name(lua_State *L) { \
        const int args = lua_gettop(L); \
        if (args > 2) { \
            return luaL_argerror(L, args, "too many arguments"); \
        } else if (args < 2) { \
            return luaL_argerror(L, args, "too few arguments"); \
        } \
          \
        uint32_t v1 = coerce_to_uint32_t(L, 1); \
        uint32_t v2 = coerce_to_uint32_t(L, 2); \
          \
        new_uint32_t(L); \
        *static_cast<uint32_t *>(luaL_checkudata(L, -1, "uint32_t")) = v1 sym v2; \
        return 1; \
    }
Definition at line 50 of file lua_boxed_numerics.cpp.
UINT32_T_BOX_OP_BOOL
#define UINT32_T_BOX_OP_BOOL (name, sym)
Value:
static int uint32_t___##name(lua_State *L) { \
        const int args = lua_gettop(L); \
        luaL_checkstack(L, 1, "Out of stack"); \
        if (args > 2) { \
            return luaL_argerror(L, args, "too many arguments"); \
        } else if (args < 2) { \
            return luaL_argerror(L, args, "too few arguments"); \
        } \
          \
        uint32_t v1 = coerce_to_uint32_t(L, 1); \
        uint32_t v2 = coerce_to_uint32_t(L, 2); \
          \
        lua_pushboolean(L, v1 sym v2); \
        return 1; \
    }
Definition at line 79 of file lua_boxed_numerics.cpp.
UINT32_T_BOX_OP_UNARY
#define UINT32_T_BOX_OP_UNARY (name, sym)
Value:
static int uint32_t___##name(lua_State *L) { \
        const int args = lua_gettop(L); \
        luaL_checkstack(L, 1, "Out of stack"); \
        if (args != 1) { \
            return luaL_argerror(L, args, "Expected 1 argument"); \
        } \
          \
        uint32_t v1 = coerce_to_uint32_t(L, 1); \
          \
        new_uint32_t(L); \
        *static_cast<uint32_t *>(luaL_checkudata(L, -1, "uint32_t")) = sym v1; \
        return 1; \
    }
Definition at line 100 of file lua_boxed_numerics.cpp.
Function Documentation
check_uint32_t()
uint32_t* check_uint32_t (lua_State * L, int arg)
Definition at line 15 of file lua_boxed_numerics.cpp.
Referenced by lua_millis().
coerce_to_uint32_t()
static uint32_t coerce_to_uint32_t (lua_State * L, int arg) static
Definition at line 20 of file lua_boxed_numerics.cpp.
load_boxed_numerics()
void load_boxed_numerics (lua_State * L)
Definition at line 183 of file lua_boxed_numerics.cpp.
Referenced by load_generated_bindings().
load_boxed_numerics_sandbox()
void load_boxed_numerics_sandbox (lua_State * L)
Definition at line 193 of file lua_boxed_numerics.cpp.
Referenced by load_generated_sandbox().
new_uint32_t()
int new_uint32_t (lua_State * L)
Definition at line 7 of file lua_boxed_numerics.cpp.
Referenced by AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_time_week_ms(), load_boxed_numerics_sandbox(), and lua_millis().
uint32_t___tostring()
static int uint32_t___tostring (lua_State * L) static
Definition at line 144 of file lua_boxed_numerics.cpp.
uint32_t_tofloat()
static int uint32_t_tofloat (lua_State * L) static
Definition at line 131 of file lua_boxed_numerics.cpp.
uint32_t_toint()
static int uint32_t_toint (lua_State * L) static
Definition at line 118 of file lua_boxed_numerics.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal
Definition at line 21 of file AC_PID_test.cpp.
Referenced by uint32_t___tostring().
uint32_t_meta
const luaL_Reg uint32_t_meta[]
Initial value:
= {
    {"__add", uint32_t___add},
    {"__sub", uint32_t___sub},
    {"__mul", uint32_t___mul},
    {"__div", uint32_t___div},
    {"__mod", uint32_t___mod},
    {"__idiv", uint32_t___idiv},
    {"__band", uint32_t___band},
    {"__bor", uint32_t___bor},
    {"__bxor", uint32_t___bxor},
    {"__shl", uint32_t___shl},
    {"__shr", uint32_t___shr},
    {"__shr", uint32_t___shr},
    {"__eq", uint32_t___eq},
    {"__lt", uint32_t___lt},
    {"__le", uint32_t___le},
    {"__bnot", uint32_t___bnot},
    {"__tostring", uint32_t___tostring},
    {"toint", uint32_t_toint},
    {"tofloat", uint32_t_tofloat},
    {NULL, NULL}
}
Definition at line 160 of file lua_boxed_numerics.cpp.
Referenced by load_boxed_numerics().