APM:Libraries: libraries/AP_Scripting/lua_generated_bindings.h File Reference
lua_generated_bindings.h File Reference
#include <GCS_MAVLink/GCS.h>
#include <AP_Relay/AP_Relay.h>
#include <AP_Terrain/AP_Terrain.h>
#include <AP_RangeFinder/AP_RangeFinder.h>
#include <AP_Notify/AP_Notify.h>
#include <AP_Math/AP_Math.h>
#include <AP_GPS/AP_GPS.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_Common/Location.h>
#include "lua/src/lua.hpp"
#include <new>
Functions
int new_Vector2f (lua_State *L)
Vector2f * check_Vector2f (lua_State *L, int arg)
int new_Vector3f (lua_State *L)
Vector3f * check_Vector3f (lua_State *L, int arg)
int new_Location (lua_State *L)
Location * check_Location (lua_State *L, int arg)
void load_generated_bindings (lua_State *L)
void load_generated_sandbox (lua_State *L)
Function Documentation
check_Location()
Location* check_Location (lua_State * L, int arg)
Definition at line 66 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_home(), AP_AHRS_get_position(), AP_GPS_location(), AP_Terrain_height_amsl(), Location_get_distance(), Location_get_vector_from_origin_NEU(), Location_lat(), Location_lng(), Location_loiter_xtrack(), Location_offset(), Location_origin_alt(), Location_relative_alt(), and Location_terrain_alt().
check_Vector2f()
Vector2f* check_Vector2f (lua_State * L, int arg)
Definition at line 56 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_groundspeed_vector(), Vector2f___add(), Vector2f___sub(), Vector2f_is_inf(), Vector2f_is_nan(), Vector2f_is_zero(), Vector2f_length(), Vector2f_normalize(), Vector2f_x(), and Vector2f_y().
check_Vector3f()
Vector3f* check_Vector3f (lua_State * L, int arg)
Definition at line 61 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_gyro(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_wind_estimate(), AP_GPS_get_antenna_offset(), AP_GPS_velocity(), Location_get_vector_from_origin_NEU(), Vector3f___add(), Vector3f___sub(), Vector3f_is_inf(), Vector3f_is_nan(), Vector3f_is_zero(), Vector3f_length(), Vector3f_normalize(), Vector3f_x(), Vector3f_y(), and Vector3f_z().
load_generated_bindings()
void load_generated_bindings (lua_State * L)
Definition at line 1671 of file lua_generated_bindings.cpp.
Referenced by load_lua_bindings().
load_generated_sandbox()
void load_generated_sandbox (lua_State * L)
Definition at line 1721 of file lua_generated_bindings.cpp.
Referenced by lua_scripts::load_script().
new_Location()
int new_Location (lua_State * L)
Definition at line 46 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_home(), AP_AHRS_get_position(), and AP_GPS_location().
new_Vector2f()
int new_Vector2f (lua_State * L)
Definition at line 26 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_groundspeed_vector(), Vector2f___add(), and Vector2f___sub().
new_Vector3f()
int new_Vector3f (lua_State * L)
Definition at line 36 of file lua_generated_bindings.cpp.
Referenced by AP_AHRS_get_gyro(), AP_AHRS_get_relative_position_NED_home(), AP_AHRS_get_velocity_NED(), AP_AHRS_wind_estimate(), AP_GPS_get_antenna_offset(), AP_GPS_velocity(), Location_get_vector_from_origin_NEU(), Vector3f___add(), and Vector3f___sub().