APM:Libraries: libraries/AP_Scripting/lua_boxed_numerics.h File Reference
lua_boxed_numerics.h File Reference
#include "lua/src/lua.hpp"
Functions
int new_uint32_t (lua_State *L)
uint32_t * check_uint32_t (lua_State *L, int arg)
void load_boxed_numerics (lua_State *L)
void load_boxed_numerics_sandbox (lua_State *L)
Function Documentation
check_uint32_t()
uint32_t* check_uint32_t (lua_State * L, int arg)
Definition at line 15 of file lua_boxed_numerics.cpp.
Referenced by lua_millis().
load_boxed_numerics()
void load_boxed_numerics (lua_State * L)
Definition at line 183 of file lua_boxed_numerics.cpp.
Referenced by load_generated_bindings().
load_boxed_numerics_sandbox()
void load_boxed_numerics_sandbox (lua_State * L)
Definition at line 193 of file lua_boxed_numerics.cpp.
Referenced by load_generated_sandbox().
new_uint32_t()
int new_uint32_t (lua_State * L)
Definition at line 7 of file lua_boxed_numerics.cpp.
Referenced by AP_GPS_last_fix_time_ms(), AP_GPS_last_message_time_ms(), AP_GPS_time_week_ms(), load_boxed_numerics_sandbox(), and lua_millis().