APM:Libraries: libraries/AP_Scripting/lua_bindings.cpp File Reference
lua_bindings.cpp File Reference
#include <AP_Common/AP_Common.h>
#include <SRV_Channel/SRV_Channel.h>
#include <AP_HAL/HAL.h>
#include "lua_bindings.h"
#include "lua_boxed_numerics.h"
#include "lua_generated_bindings.h"
Functions
int check_arguments (lua_State *L, int expected_arguments, const char *fn_name)
static int lua_servo_set_output_pwm (lua_State *L)
static int lua_millis (lua_State *L)
void load_lua_bindings (lua_State *L)
Variables
const AP_HAL::HAL & hal
static const luaL_Reg servo_functions []
Function Documentation
check_arguments()
int check_arguments (lua_State * L, int expected_arguments, const char * fn_name)
Definition at line 13 of file lua_bindings.cpp.
Referenced by lua_millis(), and lua_servo_set_output_pwm().
load_lua_bindings()
void load_lua_bindings (lua_State * L)
Definition at line 61 of file lua_bindings.cpp.
Referenced by lua_scripts::run().
lua_millis()
static int lua_millis (lua_State * L) static
Definition at line 46 of file lua_bindings.cpp.
Referenced by load_lua_bindings().
lua_servo_set_output_pwm()
static int lua_servo_set_output_pwm (lua_State * L) static
Definition at line 29 of file lua_bindings.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal
Definition at line 21 of file AC_PID_test.cpp.
servo_functions
const luaL_Reg servo_functions[] static
Initial value:
=
{
    {"set_output_pwm", lua_servo_set_output_pwm},
    {NULL, NULL}
}
Definition at line 55 of file lua_bindings.cpp.
Referenced by load_lua_bindings().