APM:Libraries: libraries/AP_Scripting/lua/src/lutf8lib.c File Reference
lutf8lib.c File Reference
#include "lprefix.h"
#include <assert.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Macros
#define lutf8lib_c
#define LUA_LIB
#define MAXUNICODE 0x10FFFF
#define iscont(p) ((*(p) & 0xC0) == 0x80)
#define UTF8PATT "[\0-\x7F\xC2-\xF4][\x80-\xBF]*"
Functions
static lua_Integer u_posrelat (lua_Integer pos, size_t len)
static const char * utf8_decode (const char *o, int *val)
static int utflen (lua_State *L)
static int codepoint (lua_State *L)
static void pushutfchar (lua_State *L, int arg)
static int utfchar (lua_State *L)
static int byteoffset (lua_State *L)
static int iter_aux (lua_State *L)
static int iter_codes (lua_State *L)
LUAMOD_API int luaopen_utf8 (lua_State *L)
Variables
static const luaL_Reg funcs []
Macro Definition Documentation
iscont
#define iscont (p) ((*(p) & 0xC0) == 0x80)
Definition at line 25 of file lutf8lib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lutf8lib.c.
lutf8lib_c
#define lutf8lib_c
Definition at line 7 of file lutf8lib.c.
MAXUNICODE
#define MAXUNICODE 0x10FFFF
Definition at line 23 of file lutf8lib.c.
UTF8PATT
#define UTF8PATT "[\0-\x7F\xC2-\xF4][\x80-\xBF]*"
Definition at line 235 of file lutf8lib.c.
Function Documentation
byteoffset()
static int byteoffset (lua_State * L) static
Definition at line 160 of file lutf8lib.c.
codepoint()
static int codepoint (lua_State * L) static
Definition at line 100 of file lutf8lib.c.
iter_aux()
static int iter_aux (lua_State * L) static
Definition at line 201 of file lutf8lib.c.
Referenced by iter_codes().
iter_codes()
static int iter_codes (lua_State * L) static
Definition at line 225 of file lutf8lib.c.
luaopen_utf8()
LUAMOD_API int luaopen_utf8 (lua_State * L)
Definition at line 250 of file lutf8lib.c.
pushutfchar()
static void pushutfchar (lua_State * L, int arg) static
Definition at line 128 of file lutf8lib.c.
Referenced by utfchar().
u_posrelat()
static lua_Integer u_posrelat (lua_Integer pos, size_t len) static
Definition at line 30 of file lutf8lib.c.
Referenced by byteoffset(), codepoint(), and utflen().
utf8_decode()
static const char* utf8_decode (const char * o, int * val) static
Definition at line 40 of file lutf8lib.c.
Referenced by codepoint(), iter_aux(), and utflen().
utfchar()
static int utfchar (lua_State * L) static
Definition at line 138 of file lutf8lib.c.
utflen()
static int utflen (lua_State * L) static
Definition at line 71 of file lutf8lib.c.
Variable Documentation
funcs
const luaL_Reg funcs[] static
Initial value:
= {
  {"offset", byteoffset},
  {"codepoint", codepoint},
  {"char", utfchar},
  {"len", utflen},
  {"codes", iter_codes},
  {"charpattern", NULL},
  {NULL, NULL}
}
Definition at line 238 of file lutf8lib.c.
Referenced by luaopen_utf8().