APM:Libraries: libraries/AP_Scripting/lua/src/lzio.c File Reference
lzio.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "llimits.h"
#include "lmem.h"
#include "lstate.h"
#include "lzio.h"
Macros
#define lzio_c
#define LUA_CORE
Functions
int luaZ_fill (ZIO *z)
void luaZ_init (lua_State *L, ZIO *z, lua_Reader reader, void *data)
size_t luaZ_read (ZIO *z, void *b, size_t n)
Macro Definition Documentation
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lzio.c.
lzio_c
#define lzio_c
Definition at line 7 of file lzio.c.
Function Documentation
luaZ_fill()
int luaZ_fill (ZIO * z)
Definition at line 23 of file lzio.c.
Referenced by luaZ_read().
luaZ_init()
void luaZ_init (lua_State * L, ZIO * z, lua_Reader reader, void * data)
Definition at line 38 of file lzio.c.
Referenced by lua_load().
luaZ_read()
size_t luaZ_read (ZIO * z, void * b, size_t n)
Definition at line 48 of file lzio.c.
Referenced by LoadBlock().