APM:Libraries: libraries/AP_Scripting/lua/src/lzio.h File Reference
lzio.h File Reference
#include "lua.h"
#include "lmem.h"
Classes
struct Mbuffer
struct Zio
Macros
#define EOZ (-1) /* end of stream */
#define zgetc(z) (((z)->n--)>0 ? cast_uchar(*(z)->p++) : luaZ_fill(z))
#define luaZ_initbuffer(L, buff) ((buff)->buffer = NULL, (buff)->buffsize = 0)
#define luaZ_buffer(buff) ((buff)->buffer)
#define luaZ_sizebuffer(buff) ((buff)->buffsize)
#define luaZ_bufflen(buff) ((buff)->n)
#define luaZ_buffremove(buff, i) ((buff)->n -= (i))
#define luaZ_resetbuffer(buff) ((buff)->n = 0)
#define luaZ_resizebuffer(L, buff, size)
#define luaZ_freebuffer(L, buff) luaZ_resizebuffer(L, buff, 0)
Typedefs
typedef struct Zio ZIO
typedef struct Mbuffer Mbuffer
Functions
LUAI_FUNC void luaZ_init (lua_State *L, ZIO *z, lua_Reader reader, void *data)
LUAI_FUNC size_t luaZ_read (ZIO *z, void *b, size_t n)
LUAI_FUNC int luaZ_fill (ZIO *z)
Macro Definition Documentation
EOZ
#define EOZ (-1) /* end of stream */
Definition at line 16 of file lzio.h.
luaZ_buffer
#define luaZ_buffer (buff) ((buff)->buffer)
Definition at line 31 of file lzio.h.
luaZ_bufflen
#define luaZ_bufflen (buff) ((buff)->n)
Definition at line 33 of file lzio.h.
luaZ_buffremove
#define luaZ_buffremove (buff, i) ((buff)->n -= (i))
Definition at line 35 of file lzio.h.
luaZ_freebuffer
#define luaZ_freebuffer (L, buff) luaZ_resizebuffer(L, buff, 0)
Definition at line 44 of file lzio.h.
luaZ_initbuffer
#define luaZ_initbuffer (L, buff) ((buff)->buffer = NULL, (buff)->buffsize = 0)
Definition at line 29 of file lzio.h.
luaZ_resetbuffer
#define luaZ_resetbuffer (buff) ((buff)->n = 0)
Definition at line 36 of file lzio.h.
luaZ_resizebuffer
#define luaZ_resizebuffer (L, buff, size)
Value:
((buff)->buffer = luaM_reallocvchar(L, (buff)->buffer, \
                (buff)->buffsize, size), \
    (buff)->buffsize = size)
Definition at line 39 of file lzio.h.
luaZ_sizebuffer
#define luaZ_sizebuffer (buff) ((buff)->buffsize)
Definition at line 32 of file lzio.h.
zgetc
#define zgetc (z) (((z)->n--)>0 ? cast_uchar(*(z)->p++) : luaZ_fill(z))
Definition at line 20 of file lzio.h.
Typedef Documentation
Mbuffer
typedef struct Mbuffer Mbuffer
ZIO
typedef struct Zio ZIO
Definition at line 18 of file lzio.h.
Function Documentation
luaZ_fill()
LUAI_FUNC int luaZ_fill (ZIO * z)
Definition at line 23 of file lzio.c.
Referenced by luaZ_read().
luaZ_init()
LUAI_FUNC void luaZ_init (lua_State * L, ZIO * z, lua_Reader reader, void * data)
Definition at line 38 of file lzio.c.
Referenced by lua_load().
luaZ_read()
LUAI_FUNC size_t luaZ_read (ZIO * z, void * b, size_t n)
Definition at line 48 of file lzio.c.
Referenced by LoadBlock().