APM:Libraries: libraries/AP_Scripting/generator/src/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <assert.h>
#include <readline/readline.h>
#include <string.h>
#include <unistd.h>
Classes
struct header
struct generator_state
struct range_check
struct type
struct argument
struct method
struct userdata_field
struct userdata
Macros
#define TRUE 1
#define FALSE 0
#define NULLABLE_ARG_COUNT_BASE 5000
Enumerations
enum error_codes {
ERROR_OUT_OF_MEMORY = 1, ERROR_HEADER = 2, ERROR_UNKNOWN_KEYWORD = 3, ERROR_USERDATA = 4,
ERROR_INTERNAL = 5, ERROR_GENERAL = 6, ERROR_SINGLETON = 7
}
enum trace_level {
TRACE_TOKENS = (1 << 0), TRACE_HEADER = (1 << 1), TRACE_GENERAL = (1 << 2), TRACE_USERDATA = (1 << 3),
TRACE_SINGLETON = (1 << 4)
}
enum access_flags { ACCESS_FLAG_READ = (1 << 0), ACCESS_FLAG_WRITE = (1 << 1) }
enum field_type {
TYPE_BOOLEAN = 0, TYPE_FLOAT, TYPE_INT8_T, TYPE_INT16_T,
TYPE_INT32_T, TYPE_UINT8_T, TYPE_UINT16_T, TYPE_UINT32_T,
TYPE_NONE, TYPE_STRING, TYPE_ENUM, TYPE_USERDATA
}
enum operator_type {
OP_ADD = (1U << 0), OP_SUB = (1U << 1), OP_MUL = (1U << 2), OP_DIV = (1U << 3),
OP_LAST
}
enum access_type { ACCESS_VALUE = 0, ACCESS_REFERENCE }
enum type_flags { TYPE_FLAGS_NULLABLE = (1U << 1), TYPE_FLAGS_ENUM = (1U << 2) }
enum userdata_type { UD_USERDATA, UD_SINGLETON }
enum userdata_flags { UD_FLAG_SEMAPHORE = (1U << 0) }
enum type_restriction { TYPE_RESTRICTION_NONE = 0, TYPE_RESTRICTION_OPTIONAL = (1U << 1), TYPE_RESTRICTION_NOT_NULLABLE = (1U << 2) }
enum range_check_type { RANGE_CHECK_NONE, RANGE_CHECK_MANDATORY }
Functions
void trace (const int trace, const char *message,...)
void error (const int code, const char *message,...)
char * next_token (void)
char * start_line (void)
void * allocate (const size_t size)
void handle_header (void)
void string_copy (char **dest, const char *src)
struct range_check * parse_range_check (enum field_type type)
unsigned int parse_access_flags (struct type *type)
int parse_type (struct type *type, const uint32_t restrictions, enum range_check_type range_type)
void handle_userdata_field (struct userdata *data)
void handle_method (char *parent_name, struct method **methods)
void handle_operator (struct userdata *data)
void handle_userdata (void)
void handle_singleton (void)
void sanity_check_userdata (void)
void emit_headers (FILE *f)
void emit_userdata_allocators (void)
void emit_userdata_checkers (void)
void emit_userdata_declarations (void)
void emit_checker (const struct type t, int arg_number, const char *indentation, const char *name)
void emit_userdata_field (const struct userdata *data, const struct userdata_field *field)
void emit_userdata_fields ()
void emit_userdata_method (const struct userdata *data, const struct method *method)
const char * get_name_for_operation (enum operator_type op)
void emit_operators (struct userdata *data)
void emit_userdata_methods (struct userdata *node)
void emit_userdata_metatables (void)
void emit_singleton_metatables (void)
void emit_loaders (void)
void emit_sandbox (void)
void emit_argcheck_helper (void)
int main (int argc, char **argv)
Variables
char keyword_alias [] = "alias"
char keyword_comment [] = "--"
char keyword_field [] = "field"
char keyword_include [] = "include"
char keyword_method [] = "method"
char keyword_operator [] = "operator"
char keyword_read [] = "read"
char keyword_semaphore [] = "semaphore"
char keyword_singleton [] = "singleton"
char keyword_userdata [] = "userdata"
char keyword_write [] = "write"
char keyword_attr_enum [] = "'enum"
char keyword_attr_null [] = "'Null"
char keyword_boolean [] = "boolean"
char keyword_float [] = "float"
char keyword_int8_t [] = "int8_t"
char keyword_int16_t [] = "int16_t"
char keyword_int32_t [] = "int32_t"
char keyword_string [] = "string"
char keyword_uint8_t [] = "uint8_t"
char keyword_uint16_t [] = "uint16_t"
char keyword_uint32_t [] = "uint32_t"
char keyword_void [] = "void"
FILE * header
FILE * source
static struct generator_state state = {}
static struct header * headers = NULL
const char * type_labels [TYPE_USERDATA+1]
int TRACE_LEVEL = 0
static struct userdata * parsed_userdata = NULL
struct userdata * parsed_singletons = NULL
char * output_path = NULL
Macro Definition Documentation
FALSE
#define FALSE 0
Definition at line 381 of file main.c.
NULLABLE_ARG_COUNT_BASE
#define NULLABLE_ARG_COUNT_BASE 5000
Definition at line 778 of file main.c.
TRUE
#define TRUE 1
Definition at line 380 of file main.c.
Enumeration Type Documentation
access_flags
enum access_flags
Enumerator
ACCESS_FLAG_READ
ACCESS_FLAG_WRITE
Definition at line 75 of file main.c.
access_type
enum access_type
Enumerator
ACCESS_VALUE
ACCESS_REFERENCE
Definition at line 116 of file main.c.
error_codes
enum error_codes
Enumerator
ERROR_OUT_OF_MEMORY
ERROR_HEADER
ERROR_UNKNOWN_KEYWORD
ERROR_USERDATA
ERROR_INTERNAL
ERROR_GENERAL
ERROR_SINGLETON
Definition at line 38 of file main.c.
field_type
enum field_type
Enumerator
TYPE_BOOLEAN
TYPE_FLOAT
TYPE_INT8_T
TYPE_INT16_T
TYPE_INT32_T
TYPE_UINT8_T
TYPE_UINT16_T
TYPE_UINT32_T
TYPE_NONE
TYPE_STRING
TYPE_ENUM
TYPE_USERDATA
Definition at line 80 of file main.c.
operator_type
enum operator_type
Enumerator
OP_ADD
OP_SUB
OP_MUL
OP_DIV
OP_LAST
Definition at line 108 of file main.c.
range_check_type
enum range_check_type
Enumerator
RANGE_CHECK_NONE
RANGE_CHECK_MANDATORY
Definition at line 389 of file main.c.
trace_level
enum trace_level
Enumerator
TRACE_TOKENS
TRACE_HEADER
TRACE_GENERAL
TRACE_USERDATA
TRACE_SINGLETON
Definition at line 67 of file main.c.
type_flags
enum type_flags
Enumerator
TYPE_FLAGS_NULLABLE
TYPE_FLAGS_ENUM
Definition at line 128 of file main.c.
type_restriction
enum type_restriction
Enumerator
TYPE_RESTRICTION_NONE
TYPE_RESTRICTION_OPTIONAL
TYPE_RESTRICTION_NOT_NULLABLE
Definition at line 383 of file main.c.
userdata_flags
enum userdata_flags
Enumerator
UD_FLAG_SEMAPHORE
Definition at line 287 of file main.c.
userdata_type
enum userdata_type
Enumerator
UD_USERDATA
UD_SINGLETON
Definition at line 258 of file main.c.
Function Documentation
allocate()
void* allocate (const size_t size)
Definition at line 214 of file main.c.
Referenced by handle_header(), handle_method(), handle_singleton(), handle_userdata(), handle_userdata_field(), main(), parse_range_check(), and string_copy().
emit_argcheck_helper()
void emit_argcheck_helper (void)
Definition at line 1457 of file main.c.
Referenced by main().
emit_checker()
void emit_checker (const struct type t, int arg_number, const char * indentation, const char * name)
Definition at line 779 of file main.c.
Referenced by emit_userdata_field(), and emit_userdata_method().
emit_headers()
void emit_headers (FILE * f)
Definition at line 734 of file main.c.
Referenced by main().
emit_loaders()
void emit_loaders (void)
Definition at line 1359 of file main.c.
Referenced by main().
emit_operators()
void emit_operators (struct userdata * data)
Definition at line 1247 of file main.c.
Referenced by emit_userdata_methods().
emit_sandbox()
void emit_sandbox (void)
Definition at line 1415 of file main.c.
Referenced by main().
emit_singleton_metatables()
void emit_singleton_metatables (void)
Definition at line 1341 of file main.c.
Referenced by main().
emit_userdata_allocators()
void emit_userdata_allocators (void)
Definition at line 742 of file main.c.
Referenced by main().
emit_userdata_checkers()
void emit_userdata_checkers (void)
Definition at line 758 of file main.c.
Referenced by main().
emit_userdata_declarations()
void emit_userdata_declarations (void)
Definition at line 769 of file main.c.
Referenced by main().
emit_userdata_field()
void emit_userdata_field (const struct userdata * data, const struct userdata_field * field)
Definition at line 962 of file main.c.
Referenced by emit_userdata_fields().
emit_userdata_fields()
void emit_userdata_fields ()
Definition at line 1015 of file main.c.
Referenced by main().
emit_userdata_metatables()
void emit_userdata_metatables (void)
Definition at line 1309 of file main.c.
Referenced by main().
emit_userdata_method()
void emit_userdata_method (const struct userdata * data, const struct method * method)
Definition at line 1027 of file main.c.
Referenced by emit_userdata_methods().
emit_userdata_methods()
void emit_userdata_methods (struct userdata * node)
Definition at line 1292 of file main.c.
Referenced by main().
error()
void error (const int code, const char * message, ...)
Definition at line 162 of file main.c.
Referenced by SITL::Calibration::_angular_velocity_control(), SITL::Calibration::_attitude_set(), SITL::Calibration::_stop_control(), allocate(), AP_AHRS_DCM::drift_correction(), emit_checker(), emit_userdata_field(), emit_userdata_method(), AC_P::get_p(), PID::get_pid(), NavEKF3::getOutputTrackingError(), NavEKF2::getOutputTrackingError(), NavEKF2_core::getOutputTrackingError(), NavEKF3_core::getOutputTrackingError(), handle_header(), handle_method(), handle_operator(), handle_singleton(), handle_userdata(), handle_userdata_field(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), lua_scripts::load_script(), loop(), main(), AP_AHRS_DCM::normalize(), Matrix3< float >::normalize(), parse_access_flags(), parse_range_check(), parse_type(), Linux::GPIO_Sysfs::read(), Linux::RCOutput_Bebop::read_obs_data(), sanity_check_userdata(), Linux::HeatPwm::set_imu_temp(), AC_AttitudeControl::sqrt_controller(), AC_PosControl::sqrt_controller(), AP_Landing_Deepstall::update_steering(), AP_AHRS_DCM::use_compass(), and Linux::GPIO_Sysfs::write().
get_name_for_operation()
const char* get_name_for_operation (enum operator_type op)
Definition at line 1229 of file main.c.
Referenced by emit_operators(), and emit_userdata_metatables().
handle_header()
void handle_header (void)
Definition at line 224 of file main.c.
Referenced by main().
handle_method()
void handle_method (char * parent_name, struct method ** methods)
Definition at line 530 of file main.c.
Referenced by handle_singleton(), and handle_userdata().
handle_operator()
void handle_operator (struct userdata * data)
Definition at line 587 of file main.c.
Referenced by handle_userdata().
handle_singleton()
void handle_singleton (void)
Definition at line 670 of file main.c.
Referenced by main().
handle_userdata()
void handle_userdata (void)
Definition at line 625 of file main.c.
Referenced by main().
handle_userdata_field()
void handle_userdata_field (struct userdata * data)
Definition at line 502 of file main.c.
Referenced by handle_userdata().
main()
int main (int argc, char ** argv)
Definition at line 1474 of file main.c.
next_token()
char* next_token (void)
Definition at line 182 of file main.c.
Referenced by handle_header(), handle_method(), handle_operator(), handle_singleton(), handle_userdata(), handle_userdata_field(), main(), parse_access_flags(), parse_range_check(), and parse_type().
parse_access_flags()
unsigned int parse_access_flags (struct type * type)
Definition at line 335 of file main.c.
Referenced by handle_userdata_field().
parse_range_check()
struct range_check* parse_range_check (enum field_type type)
Definition at line 310 of file main.c.
Referenced by parse_access_flags(), and parse_type().
parse_type()
int parse_type (struct type * type, const uint32_t restrictions, enum range_check_type range_type)
Definition at line 394 of file main.c.
Referenced by handle_method(), and handle_userdata_field().
sanity_check_userdata()
void sanity_check_userdata (void)
Definition at line 724 of file main.c.
Referenced by main().
start_line()
char* start_line (void)
Definition at line 193 of file main.c.
Referenced by main().
string_copy()
void string_copy (char ** dest, const char * src)
Definition at line 305 of file main.c.
Referenced by handle_method(), handle_userdata_field(), parse_range_check(), and parse_type().
trace()
void trace (const int trace, const char * message, ...)
Definition at line 146 of file main.c.
Referenced by emit_operators(), handle_header(), handle_method(), handle_operator(), handle_singleton(), handle_userdata(), handle_userdata_field(), main(), next_token(), parse_access_flags(), parse_range_check(), and start_line().
Variable Documentation
header
FILE* header
Definition at line 61 of file main.c.
Referenced by HALSITL::SITL_State::_update_gps_nova(), AP_Param::find_old_parameter(), AP_FlashStorage::load_sector(), main(), Linux::RCOutput_Bebop::play_note(), AP_DEVO_Telem::send_frames(), AP_FlashStorage::switch_sectors(), and AP_FlashStorage::write().
headers
struct header* headers = NULL static
Definition at line 65 of file main.c.
Referenced by emit_headers(), and handle_header().
keyword_alias
char keyword_alias[] = "alias"
Definition at line 10 of file main.c.
Referenced by handle_singleton().
keyword_attr_enum
char keyword_attr_enum[] = "'enum"
Definition at line 23 of file main.c.
Referenced by parse_type().
keyword_attr_null
char keyword_attr_null[] = "'Null"
Definition at line 24 of file main.c.
Referenced by parse_type().
keyword_boolean
char keyword_boolean[] = "boolean"
Definition at line 27 of file main.c.
Referenced by parse_type().
keyword_comment
char keyword_comment[] = "--"
Definition at line 11 of file main.c.
Referenced by main(), and next_token().
keyword_field
char keyword_field[] = "field"
Definition at line 12 of file main.c.
Referenced by handle_userdata().
keyword_float
char keyword_float[] = "float"
Definition at line 28 of file main.c.
Referenced by parse_type().
keyword_include
char keyword_include[] = "include"
Definition at line 13 of file main.c.
Referenced by main().
keyword_int16_t
char keyword_int16_t[] = "int16_t"
Definition at line 30 of file main.c.
Referenced by parse_type().
keyword_int32_t
char keyword_int32_t[] = "int32_t"
Definition at line 31 of file main.c.
Referenced by parse_type().
keyword_int8_t
char keyword_int8_t[] = "int8_t"
Definition at line 29 of file main.c.
Referenced by parse_type().
keyword_method
char keyword_method[] = "method"
Definition at line 14 of file main.c.
Referenced by handle_singleton(), and handle_userdata().
keyword_operator
char keyword_operator[] = "operator"
Definition at line 15 of file main.c.
Referenced by handle_userdata().
keyword_read
char keyword_read[] = "read"
Definition at line 16 of file main.c.
Referenced by parse_access_flags().
keyword_semaphore
char keyword_semaphore[] = "semaphore"
Definition at line 17 of file main.c.
Referenced by handle_singleton().
keyword_singleton
char keyword_singleton[] = "singleton"
Definition at line 18 of file main.c.
Referenced by main().
keyword_string
char keyword_string[] = "string"
Definition at line 32 of file main.c.
Referenced by parse_type().
keyword_uint16_t
char keyword_uint16_t[] = "uint16_t"
Definition at line 34 of file main.c.
Referenced by parse_type().
keyword_uint32_t
char keyword_uint32_t[] = "uint32_t"
Definition at line 35 of file main.c.
Referenced by parse_type().
keyword_uint8_t
char keyword_uint8_t[] = "uint8_t"
Definition at line 33 of file main.c.
Referenced by parse_type().
keyword_userdata
char keyword_userdata[] = "userdata"
Definition at line 19 of file main.c.
Referenced by main().
keyword_void
char keyword_void[] = "void"
Definition at line 36 of file main.c.
Referenced by parse_type().
keyword_write
char keyword_write[] = "write"
Definition at line 20 of file main.c.
Referenced by parse_access_flags().
output_path
char* output_path = NULL
Definition at line 1472 of file main.c.
Referenced by main().
parsed_singletons
struct userdata* parsed_singletons = NULL
Definition at line 668 of file main.c.
Referenced by emit_loaders(), emit_sandbox(), emit_singleton_metatables(), handle_singleton(), and main().
parsed_userdata
struct userdata* parsed_userdata = NULL static
Definition at line 302 of file main.c.
Referenced by emit_loaders(), emit_sandbox(), emit_userdata_allocators(), emit_userdata_checkers(), emit_userdata_declarations(), emit_userdata_fields(), emit_userdata_metatables(), handle_userdata(), main(), and sanity_check_userdata().
source
FILE* source
Definition at line 62 of file main.c.
Referenced by AnalogIn_ADS1115::_update(), emit_argcheck_helper(), emit_checker(), emit_loaders(), emit_operators(), emit_sandbox(), emit_singleton_metatables(), emit_userdata_allocators(), emit_userdata_checkers(), emit_userdata_field(), emit_userdata_metatables(), emit_userdata_method(), Linux::RCInput_RPI::init_dma_cb(), luaO_chunkid(), luaX_setinput(), main(), and Test::require().
state
struct generator_state state = {} static
Definition at line 64 of file main.c.
Referenced by HALSITL::SITL_State::_read_rc_sitl_input(), Linux::RCInput_RPI::_timer_tick(), OpticalFlow_backend::_update_frontend(), AP_Compass_Backend::accumulate_sample(), ap_hook_accel_sample(), ap_hook_AHRS_update(), ap_hook_gyro_sample(), AP_WheelEncoder_Backend::AP_WheelEncoder_Backend(), BM_Crop8bpp(), BM_GeodesicGridSections(), BM_MatrixMultiplication(), BM_YuyvToGrey(), AP_BoardConfig::board_init_safety(), AP_BoardConfig::board_setup_sbus(), AP_BoardConfig::board_setup_uart(), AP_Compass_Backend::correct_field(), AP_ServoRelayEvents::do_set_relay(), AP_Compass_Backend::drain_accumulated_samples(), error(), AP_Beacon::get_beacon_data(), AP_BoardConfig::get_safety_mask(), handle_header(), handle_method(), handle_singleton(), handle_userdata_field(), AP_FlashStorage::init(), AP_FlashStorage::load_sector(), AP_LandingGear::log_wow_state(), SITL::SITL::Log_Write_SIMSTATE(), main(), next_token(), AP_MotorsHeli_RSC::output(), parse_access_flags(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), AP_BattMonitor_FuelFlow::read(), ChibiOS::Scheduler::restore_interrupts(), AP_Compass_Backend::rotate_field(), run_test(), AP_ADSB::send_dynamic_out(), AP_Button::send_report(), AP_BoardConfig::set_default_safety_ignore_mask(), SRV_Channels::set_emergency_stop(), AP_Compass_Backend::set_last_update_usec(), SITL::SITL::simstate_send(), start_line(), AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_MAV::update(), AP_OpticalFlow_SITL::update(), AP_OpticalFlow_Onboard::update(), AP_MotorsHeli_Quad::update_motor_control(), AP_MotorsHeli_Dual::update_motor_control(), AP_MotorsHeli_Single::update_motor_control(), and OpticalFlow::update_state().
TRACE_LEVEL
int TRACE_LEVEL = 0
Definition at line 144 of file main.c.
Referenced by trace().
type_labels
const char* type_labels[TYPE_USERDATA+1]
Initial value:
= { "bool",
                                                "float",
                                                "int8_t",
                                                "int16_t",
                                                "int32_t",
                                                "uint8_t",
                                                "uint16_t",
                                                "void",
                                                "string",
                                                "enum",
                                                "userdata",
                                              }
Definition at line 95 of file main.c.
Referenced by emit_userdata_method(), and parse_range_check().