APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c File Reference
malloc.c File Reference
#include <stdio.h>
#include <string.h>
#include <hal.h>
#include <ch.h>
#include <stdarg.h>
#include "stm32_util.h"
Classes
struct memory_region
Macros
#define MEM_REGION_FLAG_DMA_OK 1
#define MEM_REGION_FLAG_FAST 2
#define MEM_REGION_FLAG_SDCARD 4
#define NUM_MEMORY_REGIONS (sizeof(memory_regions)/sizeof(memory_regions[0]))
#define MIN_ALIGNMENT 8
#define DMA_ALIGNMENT 8
#define DMA_RESERVE_SIZE 4096
Functions
void malloc_init (void)
static void * malloc_flags (size_t size, uint32_t flags)
void * malloc (size_t size)
void * malloc_dma (size_t size)
void * malloc_sdcard_dma (size_t size)
void * malloc_fastmem (size_t size)
void * calloc (size_t nmemb, size_t size)
void free (void *ptr)
size_t mem_available (void)
thread_t * thread_create_alloc (size_t size, const char *name, tprio_t prio, tfunc_t pf, void *arg)
void memory_flush_all (void)
Variables
static const struct memory_region memory_regions [] = { HAL_MEMORY_REGIONS }
static memory_heap_t heaps [NUM_MEMORY_REGIONS]
static memory_heap_t dma_reserve_heap
Macro Definition Documentation
DMA_ALIGNMENT
#define DMA_ALIGNMENT 8
Definition at line 57 of file malloc.c.
DMA_RESERVE_SIZE
#define DMA_RESERVE_SIZE 4096
Definition at line 62 of file malloc.c.
MEM_REGION_FLAG_DMA_OK
#define MEM_REGION_FLAG_DMA_OK 1
Definition at line 34 of file malloc.c.
MEM_REGION_FLAG_FAST
#define MEM_REGION_FLAG_FAST 2
Definition at line 35 of file malloc.c.
MEM_REGION_FLAG_SDCARD
#define MEM_REGION_FLAG_SDCARD 4
Definition at line 36 of file malloc.c.
MIN_ALIGNMENT
#define MIN_ALIGNMENT 8
Definition at line 52 of file malloc.c.
NUM_MEMORY_REGIONS
#define NUM_MEMORY_REGIONS (sizeof(memory_regions)/sizeof(memory_regions[0]))
Definition at line 46 of file malloc.c.
Function Documentation
calloc()
void* calloc (size_t nmemb, size_t size)
Definition at line 203 of file malloc.c.
Referenced by Linux::OpticalFlow_Onboard::_run_optflow(), Linux::VideoIn::allocate_buffers(), AuxiliaryBus::AuxiliaryBus(), bouncebuffer_init(), ByteBuffer::ByteBuffer(), AC_PolyFence_loader::create_point_array(), AP_ExpandingArrayGeneric::expand(), fdevopen(), AP_GPS::handle_gps_rtcm_data(), AP_SmartRTL::init(), AP_Logger_MAVLink::Init(), AP_InertialSensor::BatchSampler::init(), ChibiOS::Util::malloc_type(), AP_HAL::Util::malloc_type(), Linux::Memory_table::Memory_table(), AP_Logger::msg_fmt_for_name(), new_file_descriptor(), operator new(), operator new[](), ByteBuffer::set_size(), AccelCalibrator::set_status(), CompassCalibrator::set_status(), and vasprintf().
free()
void free (void * ptr)
Definition at line 208 of file malloc.c.
Referenced by HALSITL::SITL_State::_gps_nmea_printf(), Linux::UARTDriver::_parseDevicePath(), Linux::OpticalFlow_Onboard::_run_optflow(), HALSITL::SITL_State::_set_param_default(), HALSITL::UARTDriver::begin(), BM_Crop8bpp(), BM_YuyvToGrey(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), SITL::FlightAxis::exchange_data(), AP_ROMFS::find_decompress(), ChibiOS::Util::flash_bootloader(), free_file_descriptor(), AP_HAL::Util::free_type(), Linux::I2CDeviceManager::get_device(), Linux::PWM_Sysfs_Base::init(), Linux::Led_Sysfs::init(), AP_SmartRTL::init(), AP_InertialSensor::BatchSampler::init(), l_alloc(), main(), AP_Logger::msg_fmt_for_name(), new_file_descriptor(), Linux::RCInput_Navio2::open_channel(), operator delete(), operator delete[](), SITL::Aircraft::parse_home(), lua_scripts::run(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AnalogSource_Navio2::set_channel(), ByteBuffer::set_size(), AccelCalibrator::set_status(), CompassCalibrator::set_status(), SITL::FlightAxis::soap_request(), start_line(), HALSITL::Scheduler::thread_create(), ChibiOS::Scheduler::thread_create(), HALSITL::Scheduler::thread_create_trampoline(), ChibiOS::Scheduler::thread_create_trampoline(), AP_OSD_MAX7456::update_font(), AP_ExpandingArrayGeneric::~AP_ExpandingArrayGeneric(), AuxiliaryBus::~AuxiliaryBus(), ByteBuffer::~ByteBuffer(), ChibiOS::I2CDevice::~I2CDevice(), Linux::Memory_table::~Memory_table(), Linux::PWM_Sysfs_Base::~PWM_Sysfs_Base(), and ChibiOS::SPIDevice::~SPIDevice().
malloc()
void* malloc (size_t size)
Definition at line 169 of file malloc.c.
Referenced by allocate(), BM_Crop8bpp(), BM_YuyvToGrey(), calloc(), error(), AP_ROMFS::find_decompress(), FlashTest::loop(), ChibiOS::DeviceBus::register_periodic_callback(), HALSITL::Scheduler::thread_create(), ChibiOS::Scheduler::thread_create(), and trace().
malloc_dma()
void* malloc_dma (size_t size)
Definition at line 177 of file malloc.c.
Referenced by ChibiOS::SPIDevice::acquire_bus(), bouncebuffer_init(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), malloc_init(), and ChibiOS::Util::malloc_type().
malloc_fastmem()
void* malloc_fastmem (size_t size)
Definition at line 198 of file malloc.c.
Referenced by ChibiOS::Util::malloc_type().
malloc_flags()
static void* malloc_flags (size_t size, uint32_t flags) static
Definition at line 90 of file malloc.c.
Referenced by malloc(), malloc_dma(), malloc_fastmem(), and malloc_sdcard_dma().
malloc_init()
void malloc_init (void)
Definition at line 72 of file malloc.c.
Referenced by __late_init().
malloc_sdcard_dma()
void* malloc_sdcard_dma (size_t size)
Definition at line 186 of file malloc.c.
Referenced by bouncebuffer_init(), bouncebuffer_setup_read(), and bouncebuffer_setup_write().
mem_available()
size_t mem_available (void)
Definition at line 218 of file malloc.c.
Referenced by ChibiOS::Util::available_memory().
memory_flush_all()
void memory_flush_all (void)
Definition at line 277 of file malloc.c.
thread_create_alloc()
thread_t* thread_create_alloc (size_t size, const char * name, tprio_t prio, tfunc_t pf, void * arg)
Definition at line 249 of file malloc.c.
Referenced by ChibiOS::DeviceBus::register_periodic_callback(), ChibiOS::Scheduler::thread_create(), and ChibiOS::UARTDriver::thread_init().
Variable Documentation
dma_reserve_heap
memory_heap_t dma_reserve_heap static
Definition at line 66 of file malloc.c.
Referenced by malloc_flags(), malloc_init(), and mem_available().
heaps
memory_heap_t heaps[NUM_MEMORY_REGIONS] static
Definition at line 50 of file malloc.c.
Referenced by malloc_flags(), malloc_init(), mem_available(), and thread_create_alloc().
memory_regions
const struct memory_region memory_regions[] = { HAL_MEMORY_REGIONS } static
Referenced by malloc_flags(), malloc_init(), and memory_flush_all().