APM:Libraries: libraries/AP_Math/matrix_alg.cpp File Reference
matrix_alg.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <stdio.h>
#include <fenv.h>
#include <AP_Math/AP_Math.h>
Functions
float * mat_mul (float *A, float *B, uint8_t n)
static void swap (float &a, float &b)
static void mat_pivot (float *A, float *pivot, uint8_t n)
static void mat_forward_sub (float *L, float *out, uint8_t n)
static void mat_back_sub (float *U, float *out, uint8_t n)
static void mat_LU_decompose (float *A, float *L, float *U, float *P, uint8_t n)
static bool mat_inverse (float *A, float *inv, uint8_t n)
bool inverse3x3 (float m[], float invOut[])
bool inverse4x4 (float m[], float invOut[])
bool inverse (float x[], float y[], uint16_t dim)
Variables
const AP_HAL::HAL & hal
Function Documentation
inverse()
bool inverse (float x[], float y[], uint16_t dim)
Definition at line 433 of file matrix_alg.cpp.
Referenced by Matrix3< float >::invert(), CompassCalibrator::run_ellipsoid_fit(), AccelCalibrator::run_fit(), CompassCalibrator::run_sphere_fit(), and test_matrix_inverse().
inverse3x3()
bool inverse3x3 (float m[], float invOut[])
Definition at line 243 of file matrix_alg.cpp.
Referenced by inverse().
inverse4x4()
bool inverse4x4 (float m[], float invOut[])
Definition at line 282 of file matrix_alg.cpp.
Referenced by inverse().
mat_back_sub()
static void mat_back_sub (float * U, float * out, uint8_t n) static
Definition at line 128 of file matrix_alg.cpp.
Referenced by mat_inverse().
mat_forward_sub()
static void mat_forward_sub (float * L, float * out, uint8_t n) static
Definition at line 106 of file matrix_alg.cpp.
Referenced by mat_inverse().
mat_inverse()
static bool mat_inverse (float * A, float * inv, uint8_t n) static
Definition at line 191 of file matrix_alg.cpp.
Referenced by inverse().
mat_LU_decompose()
static void mat_LU_decompose (float * A, float * L, float * U, float * P, uint8_t n) static
Definition at line 151 of file matrix_alg.cpp.
Referenced by mat_inverse().
mat_mul()
float* mat_mul (float * A, float * B, uint8_t n)
Definition at line 42 of file matrix_alg.cpp.
Referenced by mat_inverse(), mat_LU_decompose(), and test_matrix_inverse().
mat_pivot()
static void mat_pivot (float * A, float * pivot, uint8_t n) static
Definition at line 74 of file matrix_alg.cpp.
Referenced by mat_LU_decompose().
swap()
static void swap (float & a, float & b) inline static
Definition at line 57 of file matrix_alg.cpp.
Referenced by Linux::Thread::_poison_stack(), mat_pivot(), and AP_RSSI::scale_and_constrain_float_rssi().
Variable Documentation
hal
const AP_HAL::HAL& hal
Definition at line 21 of file AC_PID_test.cpp.