APM:Libraries: Linux Namespace Reference
Linux Namespace Reference
Classes
class BebopBLDC_ObsData
struct buffer
class CameraSensor
class CameraSensor_Mt9v117
class CAN
class CANManager
class DigitalSource
class DigitalSource_Sysfs
struct dma_cb_t
class Flow_PX4
class GPIO_BBB
class GPIO_RPI
class GPIO_Sysfs
class GyroSample
class Heat
class HeatPwm
class I2CBus
class I2CDevice
class I2CDeviceManager
class Led_Sysfs
class Memory_table
struct memory_table_t
struct mt9v117_patch
class OpticalFlow_Onboard
class Perf
class Perf_Counter
class Perf_Lttng
class PeriodicThread
class Pollable
class Poller
class PollerThread
class PWM_Sysfs
class PWM_Sysfs_Base
class PWM_Sysfs_Bebop
class RCInput
class RCInput_AioPRU
class RCInput_Multi
class RCInput_Navio2
class RCInput_PRU
class RCInput_RCProtocol
class RCInput_RPI
class RCInput_SoloLink
class RCInput_UART
class RCInput_UDP
class RCInput_ZYNQ
class RCOutput_AeroIO
class RCOutput_AioPRU
class RCOutput_Bebop
class RCOutput_Disco
class RCOutput_PCA9685
class RCOutput_PRU
class RCOutput_Sysfs
class RCOutput_ZYNQ
class Scheduler
class Semaphore
class Semaphore_Recursive
class SPIBus
struct SPIDesc
class SPIDevice
class SPIDeviceManager
class SPIUARTDriver
class Storage
class Thread
class TimerPollable
class ToneAlarm
class ToneAlarm_Disco
class UARTDriver
class Util
class UtilRPI
class VideoIn
class WakeupPollable
Enumerations
enum mt9v117_res { MT9V117_QVGA }
enum SocketCanError { SocketCanError::SocketReadFailure, SocketCanError::SocketWriteFailure, SocketCanError::TxTimeout }
enum state_t { RCIN_RPI_INITIAL_STATE = -1, RCIN_RPI_ZERO_STATE = 0, RCIN_RPI_ONE_STATE = 1 }
enum bebop_bldc_motor { BEBOP_BLDC_MOTOR_1 = 0, BEBOP_BLDC_MOTORS_NUM }
enum bebop_bldc_sound { BEBOP_BLDC_SOUND_NONE = 0, BEBOP_BLDC_SOUND_SHORT_BEEP, BEBOP_BLDC_SOUND_BOOT_BEEP, BEBOP_BLDC_SOUND_BEBOP }
enum hw_type {
UTIL_HARDWARE_RPI1 = 0, UTIL_HARDWARE_RPI2, UTIL_HARDWARE_BEBOP, UTIL_HARDWARE_BEBOP2,
UTIL_HARDWARE_DISCO, UTIL_NUM_HARDWARES
}
Functions
static char * startswith (const char *s, const char *prefix)
static void * align_to (void *p, size_t align)
Variables
static const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static const AP_HAL::HAL & hal = AP_HAL::get_HAL()
Enumeration Type Documentation
bebop_bldc_motor
enum Linux::bebop_bldc_motor
Enumerator
BEBOP_BLDC_MOTOR_1
BEBOP_BLDC_MOTORS_NUM
Definition at line 10 of file RCOutput_Bebop.h.
bebop_bldc_sound
enum Linux::bebop_bldc_sound
Enumerator
BEBOP_BLDC_SOUND_NONE
BEBOP_BLDC_SOUND_SHORT_BEEP
BEBOP_BLDC_SOUND_BOOT_BEEP
BEBOP_BLDC_SOUND_BEBOP
Definition at line 20 of file RCOutput_Bebop.h.
hw_type
enum Linux::hw_type
Enumerator
UTIL_HARDWARE_RPI1
UTIL_HARDWARE_RPI2
UTIL_HARDWARE_BEBOP
UTIL_HARDWARE_BEBOP2
UTIL_HARDWARE_DISCO
UTIL_NUM_HARDWARES
Definition at line 16 of file Util.h.
mt9v117_res
enum Linux::mt9v117_res
Enumerator
MT9V117_QVGA
Definition at line 24 of file CameraSensor_Mt9v117.h.
SocketCanError
enum Linux::SocketCanError strong
Enumerator
SocketReadFailure
SocketWriteFailure
TxTimeout
Definition at line 43 of file CAN.h.
state_t
enum Linux::state_t
Enumerator
RCIN_RPI_INITIAL_STATE
RCIN_RPI_ZERO_STATE
RCIN_RPI_ONE_STATE
Definition at line 32 of file RCInput_RPI.h.
Function Documentation
align_to()
static void* Linux::align_to (void * p, size_t align) inline static
Definition at line 76 of file Thread.cpp.
Referenced by Linux::Thread::_poison_stack().
startswith()
static char* Linux::startswith (const char * s, const char * prefix) inline static
Definition at line 69 of file I2CDevice.cpp.
Referenced by Linux::I2CDeviceManager::get_device().
Variable Documentation
hal [1/2]
const AP_HAL::HAL& Linux::hal = AP_HAL::get_HAL() static
Definition at line 44 of file SPIDevice.cpp.
hal [2/2]
const AP_HAL::HAL& Linux::hal = AP_HAL::get_HAL() static
Definition at line 61 of file I2CDevice.cpp.
Referenced by Linux::CameraSensor_Mt9v117::_apply_patch(), Linux::RCInput_SoloLink::_check_hdr(), Linux::UtilRPI::_check_rpi_version(), Linux::CameraSensor_Mt9v117::_config_change(), Linux::VideoIn::_dequeue_frame(), Linux::GPIO_Sysfs::_export_pin(), Linux::CameraSensor_Mt9v117::_init_sensor(), Linux::Scheduler::_io_task(), Linux::GPIO_Sysfs::_open_pin_value(), Linux::GPIO_Sysfs::_pinMode(), Linux::VideoIn::_queue_buffer(), Linux::Scheduler::_rcin_task(), Linux::CameraSensor_Mt9v117::_read_reg16(), Linux::CameraSensor_Mt9v117::_read_reg8(), Linux::PeriodicThread::_run(), Linux::RCOutput_Bebop::_run_rcout(), Linux::Scheduler::_run_uarts(), Linux::CameraSensor_Mt9v117::_soft_reset(), Linux::RCInput_UDP::_timer_tick(), Linux::CameraSensor_Mt9v117::_write_reg16(), Linux::CameraSensor_Mt9v117::_write_reg32(), Linux::CameraSensor_Mt9v117::_write_reg8(), Linux::VideoIn::allocate_buffers(), Linux::SPIUARTDriver::begin(), Linux::UARTDriver::begin(), Linux::Perf::begin(), Linux::Perf::count(), Linux::PWM_Sysfs_Base::enable(), Linux::UARTDriver::end(), Linux::Perf::end(), Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), Linux::HeatPwm::HeatPwm(), Linux::ToneAlarm::init(), Linux::ToneAlarm_Disco::init(), Linux::RCInput_UDP::init(), Linux::RCInput_PRU::init(), Linux::PWM_Sysfs_Base::init(), Linux::Storage::init(), Linux::RCOutput_PCA9685::init(), Linux::Led_Sysfs::init(), Linux::RCOutput_AeroIO::init(), Linux::OpticalFlow_Onboard::init(), Linux::GPIO_Sysfs::init(), Linux::GPIO_RPI::init(), Linux::RCInput_RPI::init(), Linux::RCInput_RPI::init_DMA(), Linux::RCInput_RPI::init_PCM(), Linux::PWM_Sysfs_Base::is_enabled(), Linux::DigitalSource::mode(), Linux::DigitalSource_Sysfs::mode(), Linux::VideoIn::open_device(), Linux::Perf::Perf(), Linux::DigitalSource::read(), Linux::DigitalSource_Sysfs::read(), AP_BattMonitor_Bebop::read(), Linux::GPIO_Sysfs::read(), Linux::Scheduler::register_io_process(), Linux::Scheduler::register_timer_process(), Linux::RCOutput_PCA9685::reset_all_channels(), Linux::VideoIn::set_crop(), Linux::VideoIn::set_format(), Linux::PWM_Sysfs_Base::set_period(), Linux::PWM_Sysfs_Base::set_polarity(), Linux::SPIDevice::SPIDevice(), Linux::Semaphore::take(), Linux::SPIDevice::transfer(), Linux::SPIDevice::transfer_fullduplex(), Linux::DigitalSource::write(), Linux::DigitalSource_Sysfs::write(), Linux::UARTDriver::write(), Linux::GPIO_Sysfs::write(), Linux::I2CDevice::~I2CDevice(), and Linux::SPIDevice::~SPIDevice().