APM:Libraries: libraries/AP_Math/polygon.h File Reference
polygon.h File Reference
#include "vector2.h"
Functions
template<typename T >
bool Polygon_outside (const Vector2< T > &P, const Vector2< T > *V, unsigned n)
template<typename T >
bool Polygon_complete (const Vector2< T > *V, unsigned n)
bool Polygon_intersects (const Vector2f *V, unsigned N, const Vector2f &p1, const Vector2f &p2, Vector2f &intersection)
float Polygon_closest_distance_line (const Vector2f *V, unsigned N, const Vector2f &p1, const Vector2f &p2)
float Polygon_closest_distance_point (const Vector2f *V, unsigned N, const Vector2f &p)
Function Documentation
Polygon_closest_distance_line()
float Polygon_closest_distance_line (const Vector2f * V, unsigned N, const Vector2f & p1, const Vector2f & p2)
Definition at line 180 of file polygon.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_polygon_fence().
Polygon_closest_distance_point()
float Polygon_closest_distance_point (const Vector2f * V, unsigned N, const Vector2f & p)
Definition at line 203 of file polygon.cpp.
Polygon_complete()
template<typename T > bool Polygon_complete (const Vector2< T > * V, unsigned n)
Definition at line 116 of file polygon.cpp.
Referenced by AC_PolyFence_loader::boundary_valid(), Polygon_intersects(), Polygon_outside(), and setup().
Polygon_intersects()
bool Polygon_intersects (const Vector2f * V, unsigned N, const Vector2f & p1, const Vector2f & p2, Vector2f & intersection)
Definition at line 133 of file polygon.cpp.
Referenced by AP_OADijkstra::create_polygon_fence_visgraph(), Polygon_closest_distance_line(), and AP_OADijkstra::update_visgraph().
Polygon_outside()
template<typename T > bool Polygon_outside (const Vector2< T > & P, const Vector2< T > * V, unsigned n)
Definition at line 40 of file polygon.cpp.
Referenced by AC_Avoid::adjust_velocity_polygon(), AC_PolyFence_loader::boundary_breached(), AC_PolyFence_loader::boundary_valid(), AP_OABendyRuler::calc_margin_from_polygon_fence(), AP_OADijkstra::create_polygon_fence_with_margin(), setup(), and TEST().