APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/posix.c File Reference
posix.c File Reference
POSIX wrapper for FatFS.
#include <string.h>
#include "posix.h"
#include "stdio.h"
Macros
#define SWITCH_ERROR(errno) case errno: return #errno; break
Functions
int isatty (int fileno)
Test POSIX fileno if it is a Serial Console/TTY.
int fgetc (FILE *stream)
Get byte from a TTY device or FatFs file stream open() or fopen() sets stream->get = fatfs_getc() for FatFs functions See fdevopen() sets stream->get for TTY devices.
int getc (FILE *fp)
int fputc (int c, FILE *stream)
Put a byte to TTY device or FatFs file stream open() or fopen() sets stream->put = fatfs_outc() for FatFs functions See fdevopen() sets stream->put get for TTY devices.
void clearerr (FILE *stream)
int getchar ()
functions normally defined as macros
int putchar (int c)
put a character to stdout See fdevopen() sets stream->put get for TTY devices
int putc (int c, FILE *stream)
Un-Get byte from a TTY device or FatFs file stream.
char * fgets (char *str, int size, FILE *stream)
get a string from stdin See fdevopen() sets stream->put get for TTY devices
char * gets (char *p)
int fputs (const char *str, FILE *stream)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
int puts (const char *str)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
int feof (FILE *stream)
feof reports if the stream is at EOF
int fgetpos (FILE *stream, size_t *pos)
POSIX get position of file stream.
int fseek (FILE *stream, long offset, int whence)
POSIX seek to file possition.
int fsetpos (FILE *stream, size_t *pos)
POSIX set position of file stream.
long ftell (FILE *stream)
POSIX file position of open stream.
off_t lseek (int fileno, off_t position, int whence)
POSIX seek to file position.
void rewind (FILE *stream)
POSIX rewind file to the beginning.
int close (int fileno)
POSIX Close a file with fileno handel.
int fileno (FILE *stream)
Convert POSIX stream pointer to POSIX fileno (index of __iob[])
FILE * fileno_to_stream (int fileno)
Convert POSIX fileno to POSIX FILE stream pointer. NOT POSIX.
FILE * fopen (const char *path, const char *mode)
POSIX Open a file with path name and ascii file mode string.
size_t __wrap_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
POSIX read nmemb elements from buf, size bytes each, to the stream fd.
int ftruncate (int fd, off_t length)
POSIX truncate open file to length.
size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
POSIX write nmemb elements from buf, size bytes each, to the stream fd.
int open (const char *pathname, int flags)
POSIX Open a file with integer mode flags.
ssize_t read (int fd, void *buf, size_t count)
POSIX read count bytes from *buf to fileno fd.
void sync (void)
POSIX Sync all pending file changes and metadata on ALL files.
int syncfs (int fd)
POSIX Sync pending file changes and metadata for specified fileno.
int truncate (const char *path, off_t length)
POSIX truncate named file to length.
ssize_t write (int fd, const void *buf, size_t count)
POSIX Write count bytes from *buf to fileno fd.
FILE * __wrap_freopen (const char *filename, const char *mode, FILE *stream)
int __wrap_fclose (FILE *stream)
POSIX close a file stream.
int stat (const char *name, struct stat *buf)
Display struct stat, from POSIX stat(0 or fstat(), in ASCII. NOT POSIX.
int utime (const char *filename, const struct utimbuf *times)
Set Modification and Access time of a file.
int64_t fs_getfree ()
int64_t fs_gettotal ()
char * basename (const char *str)
POSIX Basename of filename.
char * baseext (char *str)
File extention of a file name. NOT POSIX.
int chdir (const char *pathname)
POSIX change directory.
int chmod (const char *pathname, mode_t mode)
POSIX chmod function - change file access permission Unfortunately file f_open modes and f_chmod modes are not the same Files that are open have way more options - but only while the file is open.
int dirname (char *str)
POSIX directory name of a filename. Return the index of the last '/' character.
char * getcwd (char *pathname, size_t len)
POSIX get current working directory.
int mkdir (const char *pathname, mode_t mode)
POSIX make a directory.
int rename (const char *oldpath, const char *newpath)
POSIX rename a file by name.
int rmdir (const char *pathname)
POSIX delete a directory.
int unlink (const char *pathname)
POSIX delete a file.
int __wrap_remove (const char *pathname)
int closedir (DIR *dirp)
POSIX closedir.
DIR * opendir (const char *pathdir)
dirent_t * readdir (DIR *dirp)
void clrerror (FILE *stream)
clrerror resets stream EOF and error flags
int ferror (FILE *stream)
ferror reports if the stream has an error flag set
char * strerror (int errnum)
POSIX strerror() - convert POSIX errno to text with user message.
char * __wrap_strerror_r (int errnum, char *buf, size_t buflen)
POSIX strerror_r() - convert POSIX errno to text with user message.
FILE * fdevopen (int(*put)(char, FILE *), int(*get)(FILE *))
Device open functions.
int fatfs_getc (FILE *stream)
Formt SD card.
int fatfs_putc (char c, FILE *stream)
Private FatFs function called by fputc() to put a byte from file stream NOT POSIX open() assigns stream->put = fatfs_putc()
int fatfs_to_errno (FRESULT Result)
Convert FafFs error result to POSIX errno. NOT POSIX.
int fatfs_to_fileno (FIL *fh)
Convert FatFS file handle to POSIX fileno. NOT POSIX.
static time_t replace_mktime (const struct tm *t)
time_t fat_time_to_unix (uint16_t date, uint16_t time)
Convert FatFs file date and time to POSIX epoch seconds. NOT POSIX.
void unix_time_to_fat (time_t epoch, uint16_t *date, uint16_t *time)
Convert Linux POSIX time_t to FAT32 date and time. NOT POSIX.
FIL * fileno_to_fatfs (int fileno)
Convert POSIX fileno to FatFS handle NOT POSIX.
int free_file_descriptor (int fileno)
Free POSIX fileno FILE descriptor. NOT POSIX.
int new_file_descriptor (void)
Allocate a POSIX FILE descriptor. NOT POSIX.
int posix_fopen_modes_to_open (const char *mode)
Convert POSIX fopen mode to POSIX open mode flags. NOT POSIX.
int __wrap_fprintf (FILE *fp, const char *fmt,...)
fprintf character write function
int fsync (int fileno)
Variables
FILE * __iob [MAX_FILES]
Note: fdevopen assigns stdin,stdout,stderr.
static DIR _dp
POSIX opendir.
static dirent_t _de
POSIX opendir.
Detailed Description
POSIX wrapper for FatFS.
Provides many of the common Posix/linux functions
POSIX character I/O functions
isatty
fgetc
fputc
getchar
putc
putchar
ungetc
POSIX string I/O functions
fgets
fputs
puts
POSIX file position functions
feof
fgetpos
fseek
fsetpos
ftell
lseek
rewind
POSIX file functions
close
fileno
fileno_to_stream NOT POSIX
fopen
fread
ftruncate
fwrite
open
read
sync
syncfs
truncate
write
fclose
POSIX file information functions
dump_stat - NOT POSIX
fstat
mctime - NOT POSIX
stat
POSIX file and directory manipulation
basename
baseext - NOT POSIX
chmod
chdir
dirname
getcwd
mkdir
rename
rmdir
unlink
utime
POSIX - directory scanning functions
closedir
opendir
readdir
POSIX error functions
clrerror
ferror
perror
strerror
strerror_r
Device open functions
fdevopen - NOT POSIX
FatFS to POSIX bridge functions - NOT POSIX
fatfs_getc
fatfs_putc
fatfs_to_errno
fatfs_to_fileno
fat_time_to_unix
fileno_to_fatfs
free_file_descriptor
new_file_descriptor
mkfs
posix_fopen_modes_to_open
unix_time_to_fat
Copyright © 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file posix.c.
Macro Definition Documentation
SWITCH_ERROR
#define SWITCH_ERROR (errno) case errno: return #errno; break
Function Documentation
__wrap_fclose()
int __wrap_fclose (FILE * stream)
POSIX close a file stream.
man page flose (3).
Parameters
[in] stream POSIX stream pointer.
Returns
0 on sucess.
-1 on error witrh errno set.
Definition at line 1188 of file posix.c.
__wrap_fprintf()
int __wrap_fprintf (FILE * fp, const char * fmt, ...)
fprintf character write function
POSIX fprintf function
Parameters
[in] *p printf user buffer
[in] ch character TODO if fputc fails we might want to also set an error in the *p structure - error in the stream will already be set fprintf function Example user defined printf function using fputc for I/O This method allows I/O to devices and strings without typical C++ overhead
[in] *fp FILE stream pointer
[in] fmt printf forat string
[in] ... vararg list or arguments
Returns
size of printed result
Definition at line 2507 of file posix.c.
__wrap_fread()
size_t __wrap_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
POSIX read nmemb elements from buf, size bytes each, to the stream fd.
man page fread (3).
Parameters
[in] ptr buffer.
[in] nmemb number of items to read.
[in] size size of each item in bytes.
[in] stream POSIX file stream.
Returns
count on sucess.
0 or < size on error with errno set.
Definition at line 745 of file posix.c.
__wrap_freopen()
FILE* __wrap_freopen (const char * filename, const char * mode, FILE * stream)
Definition at line 1170 of file posix.c.
__wrap_remove()
int __wrap_remove (const char * pathname)
Definition at line 1658 of file posix.c.
__wrap_strerror_r()
char* __wrap_strerror_r (int errnum, char * buf, size_t buflen)
POSIX strerror_r() - convert POSIX errno to text with user message.
man page strerror (3).
Parameters
[in] errnum index for sys_errlist[]
[in] buf user buffer for error message
[in] buflen length of user buffer for error message
See also
sys_errlist[].
Returns
char *
Definition at line 1838 of file posix.c.
baseext()
char* baseext (char * str)
File extention of a file name. NOT POSIX.
Parameters
[in] str string to find extension in.
Returns
pointer to basename extension.
Definition at line 1419 of file posix.c.
basename()
char* basename (const char * str)
POSIX Basename of filename.
POSIX file and directory manipulation- man page (3).
Parameters
[in] str string to find basename in.
Returns
pointer to basename of string.
Definition at line 1398 of file posix.c.
chdir()
int chdir (const char * pathname)
POSIX change directory.
man page chdir (2).
Parameters
[in] pathname directory to change to
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1441 of file posix.c.
Referenced by SITL::JSBSim::start_JSBSim().
chmod()
int chmod (const char * pathname, mode_t mode)
POSIX chmod function - change file access permission Unfortunately file f_open modes and f_chmod modes are not the same Files that are open have way more options - but only while the file is open.
so this is a bit of a hack - we can only set read only - if on one has write perms
man page chmod (2).
Parameters
[in] pathname filename string.
[in] mode POSIX chmod modes.
Returns
fileno on success.
Definition at line 1466 of file posix.c.
Referenced by mkdir().
clearerr()
void clearerr (FILE * stream)
Definition at line 248 of file posix.c.
Referenced by g_read().
close()
int close (int fileno)
POSIX Close a file with fileno handel.
POSIX file functions- man page close (2).
Parameters
[in] fileno fileno of file.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 627 of file posix.c.
Referenced by __wrap_fclose(), __wrap_freopen(), Linux::GPIO_Sysfs::_export_pin(), Linux::OpticalFlow_Onboard::_run_optflow(), ChibiOS::Storage::_save_backup(), Linux::Storage::_storage_create(), HALSITL::Storage::_storage_open(), ChibiOS::Storage::_storage_open(), HALSITL::UARTDriver::_tcp_start_client(), HALSITL::UARTDriver::_tcp_start_connection(), Linux::Storage::_timer_tick(), HALSITL::UARTDriver::_timer_tick(), HALSITL::UARTDriver::_udp_start_client(), AP_RangeFinder_BBB_PRU::detect(), AP_HAL::dump_stack_trace(), HALSITL::Util::get_system_id_unformatted(), Linux::Util::get_system_id_unformatted(), Linux::RCOutput_ZYNQ::init(), Linux::RCInput_ZYNQ::init(), Linux::RCInput_PRU::init(), Linux::RCOutput_PRU::init(), Linux::Storage::init(), Linux::RCOutput_AioPRU::init(), Linux::RCInput_AioPRU::init(), Linux::GPIO_RPI::init(), Linux::GPIO_BBB::init(), Linux::RCInput_RPI::map_peripheral(), Linux::Memory_table::Memory_table(), Linux::RCInput_RCProtocol::open_115200(), Linux::VideoIn::open_device(), Linux::RCInput_RCProtocol::open_sbus(), Linux::Poller::Poller(), Linux::GPIO_Sysfs::read(), AnalogSource_Navio2::set_channel(), Linux::TimerPollable::setup_timer(), SITL::JSBSim::start_JSBSim(), SITL::last_letter::start_last_letter(), watchdog_load(), watchdog_save(), Linux::GPIO_Sysfs::write(), HALSITL::UARTDriver::write(), Linux::Util::write_file(), Linux::DigitalSource_Sysfs::~DigitalSource_Sysfs(), Linux::I2CBus::~I2CBus(), Linux::Led_Sysfs::~Led_Sysfs(), Linux::Pollable::~Pollable(), Linux::Poller::~Poller(), Linux::PWM_Sysfs_Base::~PWM_Sysfs_Base(), Linux::RCInput_UART::~RCInput_UART(), and Linux::SPIBus::~SPIBus().
closedir()
int closedir (DIR * dirp)
POSIX closedir.
POSIX - directory scanning functions- man page closedir (2).
Parameters
[in] dirp DIR * directory handle
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1682 of file posix.c.
Referenced by Linux::I2CDeviceManager::get_device(), and lua_scripts::load_all_scripts_in_dir().
clrerror()
void clrerror (FILE * stream)
clrerror resets stream EOF and error flags
POSIX error functions- man page clrerror(3).
Parameters
[in] stream POSIX stream pointer.
Returns
EOF on error with errno set.
Definition at line 1751 of file posix.c.
dirname()
int dirname (char * str)
POSIX directory name of a filename. Return the index of the last '/' character.
Example:
dir[0] = 0;
ret = dirname(path)
if(ret)
 strncpy(dir,path,ret);
Parameters
[in] str string to examine.
Returns
0 if no directory part.
index of last '/' character.
Definition at line 1504 of file posix.c.
Referenced by Linux::I2CDeviceManager::get_device(), and lua_scripts::load_all_scripts_in_dir().
fat_time_to_unix()
time_t fat_time_to_unix (uint16_t date, uint16_t time)
Convert FatFs file date and time to POSIX epoch seconds. NOT POSIX.
man page timegm (3).
Parameters
[in] date FatFs date.
[in] time FatFs time.
See also
timegm()
Returns
epoch seconds
Definition at line 2250 of file posix.c.
Referenced by stat().
fatfs_getc()
int fatfs_getc (FILE * stream)
Formt SD card.
FatFS to POSIX bridge functions
Parameters
[in] *name device name @retrun void Private FatFs function called by fgetc() to get a byte from file stream FIXME buffer this function call NOT POSIX open() assigns stream->get = fatfs_getc()
man page fgetc (3).
Notes: fgetc does all tests prior to caling us, including ungetc.
Parameters
[in] stream POSIX stream pointer.
Returns
character.
EOF on error with errno set.
Definition at line 1965 of file posix.c.
Referenced by open().
fatfs_putc()
int fatfs_putc (char c, FILE * stream)
Private FatFs function called by fputc() to put a byte from file stream NOT POSIX open() assigns stream->put = fatfs_putc()
man page fputc (3).
Notes: fputc does all tests prior to caling us.
Parameters
[in] c character.
[in] stream POSIX stream pointer.
Returns
character
EOF on error with errno set.
Definition at line 2055 of file posix.c.
Referenced by fputc(), and open().
fatfs_to_errno()
int fatfs_to_errno (FRESULT Result)
Convert FafFs error result to POSIX errno. NOT POSIX.
man page errno (3).
Parameters
[in] Result FatFs Result code.
Returns
POSIX errno.
EBADMSG if no conversion possible.
Definition at line 2095 of file posix.c.
Referenced by __wrap_remove(), chdir(), chmod(), close(), closedir(), fatfs_getc(), fatfs_putc(), fsync(), ftruncate(), getcwd(), lseek(), mkdir(), open(), opendir(), read(), readdir(), rename(), rmdir(), stat(), syncfs(), truncate(), unlink(), utime(), and write().
fatfs_to_fileno()
int fatfs_to_fileno (FIL * fh)
Convert FatFS file handle to POSIX fileno. NOT POSIX.
Parameters
[in] fh FatFS file pointer.
Returns
fileno on success.
-1 on error with errno set to EBADF.
Definition at line 2172 of file posix.c.
fdevopen()
FILE* fdevopen (int(*)(char, FILE *) put, int(*)(FILE *) get)
Device open functions.
Assign stdin,stdout,stderr or any use defined I/O NOT POSIX
Parameters
[in] *put uart putc function pointer
[in] *get uart gutc function pointer
Definition at line 1856 of file posix.c.
feof()
int feof (FILE * stream)
feof reports if the stream is at EOF
POSIX file position functions- man page feof (3).
Parameters
[in] stream POSIX stream pointer.
Returns
1 if EOF set, 0 otherwise.
Definition at line 452 of file posix.c.
Referenced by getF().
ferror()
int ferror (FILE * stream)
ferror reports if the stream has an error flag set
man page ferror (3).
Parameters
[in] stream POSIX stream pointer.
Returns
1 if EOF set, 0 otherwise.
Definition at line 1763 of file posix.c.
Referenced by g_read(), luaL_loadfilex(), and pmain().
fgetc()
int fgetc (FILE * stream)
Get byte from a TTY device or FatFs file stream open() or fopen() sets stream->get = fatfs_getc() for FatFs functions See fdevopen() sets stream->get for TTY devices.
man page fgetc (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
EOF on error with errno set.
Definition at line 157 of file posix.c.
Referenced by fgets(), getc(), getchar(), and read().
fgetpos()
int fgetpos (FILE * stream, size_t * pos)
POSIX get position of file stream.
man page fgetpos (3).
Parameters
[in] stream POSIX file stream.
[in] pos position pointer for return.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 469 of file posix.c.
fgets()
char* fgets (char * str, int size, FILE * stream)
get a string from stdin See fdevopen() sets stream->put get for TTY devices
POSIX string I/O
man page fgets (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
Definition at line 350 of file posix.c.
Referenced by Linux::UtilRPI::_check_rpi_version(), db_debug(), Linux::Util::get_hw_arm32(), and gets().
fileno()
int fileno (FILE * stream)
Convert POSIX stream pointer to POSIX fileno (index of __iob[])
man page fileno (3)
Parameters
[in] stream stream pointer
Returns
int fileno on success
-1 with errno = EBAFD if stream is NULL or not found
Definition at line 666 of file posix.c.
Referenced by __wrap_fclose(), __wrap_fread(), __wrap_freopen(), close(), fileno_to_fatfs(), fileno_to_stream(), fopen(), free_file_descriptor(), fseek(), fsync(), ftell(), fwrite(), isatty(), lseek(), and open().
fileno_to_fatfs()
FIL* fileno_to_fatfs (int fileno)
Convert POSIX fileno to FatFS handle NOT POSIX.
FatFS file handle is pointed to by the avr-libc stream->udata.
Parameters
[in] fileno fileno of file
Returns
FIL * FatFS file handle on success.
NULL if POSIX fileno is invalid NULL
Definition at line 2299 of file posix.c.
Referenced by close(), fsync(), ftell(), ftruncate(), lseek(), open(), read(), sync(), syncfs(), and write().
fileno_to_stream()
FILE* fileno_to_stream (int fileno)
Convert POSIX fileno to POSIX FILE stream pointer. NOT POSIX.
inverse of POSIX fileno()
man page fileno (3)
Parameters
[in] fileno POSIX fileno is the index of __iob[].
See also
fileno()
Returns
FILE * on success
NULL on error with errno set, NULL if fileno out of bounds
Definition at line 696 of file posix.c.
Referenced by close(), fileno_to_fatfs(), fopen(), free_file_descriptor(), fsync(), lseek(), open(), read(), syncfs(), and write().
fopen()
FILE* fopen (const char * path, const char * mode)
POSIX Open a file with path name and ascii file mode string.
man page fopen(3).
Parameters
[in] path filename string.
[in] mode POSIX open mode strings.
Returns
stream * on success.
NULL on error with errno set.
Definition at line 724 of file posix.c.
Referenced by __wrap_freopen(), Linux::UtilRPI::_check_rpi_version(), Linux::RCInput::_process_rc_pulse(), SITL::JSBSim::create_templates(), AP_RangeFinder_BBB_PRU::detect(), Linux::Util::get_hw_arm32(), io_open(), luaL_loadfilex(), main(), opencheck(), pmain(), AP_GPS_NMEA::read(), Linux::Util::read_file(), and readable().
fputc()
int fputc (int c, FILE * stream)
Put a byte to TTY device or FatFs file stream open() or fopen() sets stream->put = fatfs_outc() for FatFs functions See fdevopen() sets stream->put get for TTY devices.
man page fputc (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
Definition at line 216 of file posix.c.
Referenced by __wrap_fprintf(), fputs(), putc(), putchar(), puts(), and write().
fputs()
int fputs (const char * str, FILE * stream)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
man page fputs (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
Definition at line 404 of file posix.c.
free_file_descriptor()
int free_file_descriptor (int fileno)
Free POSIX fileno FILE descriptor. NOT POSIX.
Parameters
[in] fileno POSIX file number __iob[] index.
Returns
fileno on success.
-1 on failure.
Definition at line 2334 of file posix.c.
Referenced by close(), and open().
fs_getfree()
int64_t fs_getfree ()
Definition at line 1357 of file posix.c.
fs_gettotal()
int64_t fs_gettotal ()
Definition at line 1372 of file posix.c.
fseek()
int fseek (FILE * stream, long offset, int whence)
POSIX seek to file possition.
man page fseek (3).
Parameters
[in] stream POSIX file stream.
[in] offset offset to seek to.
[in] whence
SEEK_SET The offset is set to offset bytes.
SEEK_CUR The offset is set to its current location plus offset bytes.
SEEK_END The offset is set to the size of the file plus offset bytes.
Returns
file position on sucess.
-1 on error.
Definition at line 492 of file posix.c.
Referenced by fsetpos(), and rewind().
fsetpos()
int fsetpos (FILE * stream, size_t * pos)
POSIX set position of file stream.
man page fsetpos (3).
Parameters
[in] stream POSIX file stream.
[in] pos position pointer.
Returns
0 with *pos set to position on sucess.
-1 on error with errno set.
Definition at line 518 of file posix.c.
fsync()
int fsync (int fileno)
Definition at line 2531 of file posix.c.
Referenced by Linux::Storage::_storage_create(), Linux::Storage::_timer_tick(), and ChibiOS::Storage::_timer_tick().
ftell()
long ftell (FILE * stream)
POSIX file position of open stream.
man page fteel (3).
Parameters
[in] stream POSIX file stream.
Returns
file position on sucess.
-1 on error with errno set.
Definition at line 532 of file posix.c.
Referenced by fgetpos().
ftruncate()
int ftruncate (int fd, off_t length)
POSIX truncate open file to length.
man page ftruncate (3).
Parameters
[in] fd open file number.
[in] length length to truncate to.
Returns
0 on success.
-1 on fail.
Definition at line 769 of file posix.c.
Referenced by Linux::Storage::_storage_create(), and AP_Logger_SITL::Init().
fwrite()
size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
POSIX write nmemb elements from buf, size bytes each, to the stream fd.
man page write (2).
Parameters
[in] ptr buffer.
[in] nmemb number of items to write.
[in] size size of each item in bytes.
[in] stream POSIX file stream.
Returns
count written on sucess.
0 or < size on error with errno set.
Definition at line 810 of file posix.c.
Referenced by g_write(), AP_GPS_NMEA::read(), and writer().
getc()
int getc (FILE * fp)
Definition at line 202 of file posix.c.
Referenced by skipBOM(), skipcomment(), and test_eof().
getchar()
int getchar ()
functions normally defined as macros
get a character from stdin See fdevopen() sets stream->get for TTY devices
man page getchar (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
Definition at line 266 of file posix.c.
getcwd()
char* getcwd (char * pathname, size_t len)
POSIX get current working directory.
man page getcwd (2).
Parameters
[in] pathname directory to change to
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1549 of file posix.c.
gets()
char* gets (char * p)
char *gets(p) – get line from stdin
Definition at line 381 of file posix.c.
isatty()
int isatty (int fileno)
Test POSIX fileno if it is a Serial Console/TTY.
POSIX character I/O functions
man page isatty (3).
Parameters
[in] fileno POSIX fileno of open file.
Returns
1 if fileno is a serial TTY/Console (uart in avr-libc terms).
0 if POSIX fileno is NOT a Serial TTY.
Todo:
Perhaps we should verify console functions have been added ?
Definition at line 137 of file posix.c.
Referenced by fileno_to_fatfs(), free_file_descriptor(), ftell(), ftruncate(), lseek(), new_file_descriptor(), sync(), and syncfs().
lseek()
off_t lseek (int fileno, off_t position, int whence)
POSIX seek to file position.
man page lseek (2).
Parameters
[in] fileno POSIX fileno of open file.
[in] position offset to seek to.
[in] whence
SEEK_SET The offset is set to offset bytes.
SEEK_CUR The offset is set to its current location plus offset bytes.
SEEK_END The offset is set to the size of the file plus offset bytes.
Returns
file position on sucess.
-1 on error.
Definition at line 564 of file posix.c.
Referenced by HALSITL::Storage::_storage_open(), ChibiOS::Storage::_storage_open(), HALSITL::Storage::_timer_tick(), Linux::Storage::_timer_tick(), ChibiOS::Storage::_timer_tick(), HALSITL::SITL_State::_update_gps_file(), fseek(), and Linux::Memory_table::Memory_table().
mkdir()
int mkdir (const char * pathname, mode_t mode)
POSIX make a directory.
man page mkdir (2).
Parameters
[in] pathname directory to create
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1572 of file posix.c.
Referenced by mkdir_p(), and sdcard_init().
new_file_descriptor()
int new_file_descriptor (void)
Allocate a POSIX FILE descriptor. NOT POSIX.
Returns
fileno on success.
-1 on failure with errno set.
Definition at line 2378 of file posix.c.
Referenced by open().
open()
int open (const char * pathname, int flags)
POSIX Open a file with integer mode flags.
man page open (2).
Parameters
[in] pathname filename string.
[in] flags POSIX open modes.
Returns
fileno on success.
-1 on error with errno set.
Seek to end of the file
Definition at line 837 of file posix.c.
Referenced by Linux::GPIO_Sysfs::_export_pin(), Linux::GPIO_Sysfs::_open_pin_value(), Linux::OpticalFlow_Onboard::_run_optflow(), ChibiOS::Storage::_save_backup(), Linux::Storage::_storage_create(), HALSITL::Storage::_storage_open(), ChibiOS::Storage::_storage_open(), HALSITL::UARTDriver::_uart_start_connection(), HALSITL::SITL_State::_update_gps_file(), AP_RangeFinder_BBB_PRU::detect(), AP_HAL::dump_stack_trace(), fopen(), HALSITL::Util::get_system_id_unformatted(), Linux::Util::get_system_id_unformatted(), Linux::RCOutput_ZYNQ::init(), Linux::RCInput_ZYNQ::init(), AP_Logger_SITL::Init(), Linux::RCInput_PRU::init(), Linux::RCOutput_PRU::init(), Linux::PWM_Sysfs_Base::init(), Linux::Storage::init(), Linux::RCOutput_AioPRU::init(), Linux::Led_Sysfs::init(), Linux::RCInput_AioPRU::init(), Linux::GPIO_RPI::init(), Linux::GPIO_BBB::init(), AP_Gripper_EPM::init_gripper(), AnalogSource_IIO::init_pins(), Linux::RCInput_RPI::map_peripheral(), Linux::Memory_table::Memory_table(), Linux::RCInput_RCProtocol::open_115200(), Linux::RCInput_Navio2::open_channel(), Linux::VideoIn::open_device(), Linux::RCInput_RCProtocol::open_sbus(), Linux::RCInput_UART::RCInput_UART(), AnalogSource_Navio2::set_channel(), Linux::CameraSensor::set_format(), setup(), SITL::JSBSim::start_JSBSim(), SITL::last_letter::start_last_letter(), AP_OpticalFlow_Pixart::timer(), Linux::ToneAlarm::ToneAlarm(), watchdog_load(), watchdog_save(), and Linux::Util::write_file().
opendir()
DIR* opendir (const char * pathdir)
Definition at line 1701 of file posix.c.
Referenced by Linux::I2CDeviceManager::get_device(), and lua_scripts::load_all_scripts_in_dir().
posix_fopen_modes_to_open()
int posix_fopen_modes_to_open (const char * mode)
Convert POSIX fopen mode to POSIX open mode flags. NOT POSIX.
man page fopen (3).
man page open (2).
Valid modes.
Read
"r", "rb"
Read and Write
"r+", "r+b", "rb+"
Write
"w", "wb"
Write and Read.
"w+", "w+b", "wb+"
"w+" implies write/read access.
Append
"a", "ab"
Append and Read
"a+", "a+b", "ab+"
Note: ORDER IS IMPORTANT! so w+ is NOT the same as r+.
ALWAYS do a fflush or fseek between rear write operations if + is used..
Parameters
[in] mode POSIX file mode string.
Returns
open mode flags.
-1 on error.
Warning
read and write BOTH share the same stream buffer and buffer index pointers.
Definition at line 2441 of file posix.c.
Referenced by fopen().
putc()
int putc (int c, FILE * stream)
Un-Get byte from a TTY device or FatFs file stream.
man page ungetc (3).
Parameters
[in] c Character to unget
[in] stream POSIX stream pointer.
Returns
character.
EOF on error with errno set. Put a character to a stream See fdevopen() sets stream->put get for TTY devices
man page putc (3).
Parameters
[in] stream POSIX stream pointer.
Definition at line 331 of file posix.c.
putchar()
int putchar (int c)
put a character to stdout See fdevopen() sets stream->put get for TTY devices
man page putchar (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
Definition at line 281 of file posix.c.
puts()
int puts (const char * str)
put a string to stdout See fdevopen() sets stream->put get for TTY devices
man page puts (3).
Parameters
[in] stream POSIX stream pointer.
Returns
character.
Definition at line 427 of file posix.c.
read()
ssize_t read (int fd, void * buf, size_t count)
POSIX read count bytes from *buf to fileno fd.
man page read (2).
Parameters
[in] fd POSIX fileno.
[in] buf buffer.
[in] count number of bytes to write.
Returns
count on sucess.
-1 on error with errno set.
Definition at line 947 of file posix.c.
Referenced by __wrap_fread(), HALSITL::Storage::_storage_open(), ChibiOS::Storage::_storage_open(), HALSITL::SITL_State::_update_gps(), HALSITL::SITL_State::_update_gps_file(), SITL::JSBSim::check_stdout(), AP_HAL::dump_stack_trace(), SITL::JSBSim::expect(), HALSITL::Util::get_system_id_unformatted(), Linux::Util::get_system_id_unformatted(), HALSITL::SITL_State::gps_read(), Linux::Storage::init(), loop(), Linux::Memory_table::Memory_table(), Linux::TimerPollable::on_can_read(), Linux::WakeupPollable::on_can_read(), ConsoleDevice::read(), UARTDevice::read(), SITL::JSBSim::start_JSBSim(), and watchdog_load().
readdir()
dirent_t* readdir (DIR * dirp)
Definition at line 1720 of file posix.c.
Referenced by Linux::I2CDeviceManager::get_device(), and lua_scripts::load_all_scripts_in_dir().
rename()
int rename (const char * oldpath, const char * newpath)
POSIX rename a file by name.
man page (2).
Parameters
[in] oldpath original name.
[in] newpath new name.
Returns
0 on success.
-1 on error with errno set.
Definition at line 1600 of file posix.c.
Referenced by os_rename().
replace_mktime()
static time_t replace_mktime (const struct tm * t) static
Definition at line 2200 of file posix.c.
Referenced by fat_time_to_unix().
rewind()
void rewind (FILE * stream)
POSIX rewind file to the beginning.
man page rewind (3).
Parameters
[in] stream POSIX file stream.
Returns
void.
Definition at line 608 of file posix.c.
rmdir()
int rmdir (const char * pathname)
POSIX delete a directory.
man page rmdir (2).
Parameters
[in] pathname directory to delete.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1623 of file posix.c.
stat()
int stat (const char * name, struct stat * buf)
Display struct stat, from POSIX stat(0 or fstat(), in ASCII. NOT POSIX.
POSIX file information functions
Parameters
[in] sp struct stat pointer.
Returns
void. POSIX stat - get file status of named file.
man page (2).
Parameters
[in] name file name.
[in] buf struct stat buffer to return results in.
Returns
0 on success.
-1 on error with errno set.
Definition at line 1271 of file posix.c.
Referenced by Linux::UARTDriver::_parseDevicePath(), checkload(), AP_HAL::dump_stack_trace(), Linux::Util::is_chardev_node(), is_dir(), ll_loadlib(), loadfunc(), luaL_execresult(), luaL_fileresult(), os_execute(), searcher_Croot(), and AP_Compass_IST8308::timer().
strerror()
char* strerror (int errnum)
POSIX strerror() - convert POSIX errno to text with user message.
man page strerror (3).
Parameters
[in] errnum error provided from <errno.h>
Returns
char *
Definition at line 1779 of file posix.c.
Referenced by __wrap_strerror_r(), Linux::VideoIn::_dequeue_frame(), Linux::VideoIn::_queue_buffer(), Linux::RCOutput_Bebop::_run_rcout(), Linux::VideoIn::_set_streaming(), HALSITL::SITL_State::_setup_fdm(), HALSITL::UARTDriver::_tcp_start_client(), HALSITL::UARTDriver::_tcp_start_connection(), HALSITL::UARTDriver::_udp_start_client(), HALSITL::UARTDriver::_udp_start_multicast(), HAL_SITL::actually_reboot(), Linux::VideoIn::allocate_buffers(), cannot(), SITL::Gazebo::drain_sockets(), errfile(), Linux::RCInput_UART::init(), Linux::PWM_Sysfs_Base::init(), Linux::Scheduler::init(), Linux::Scheduler::init_realtime(), luaL_fileresult(), TCPServerDevice::open(), UARTDevice::open(), Linux::SPIBus::open(), Linux::VideoIn::open_device(), opencheck(), Linux::RCInput_UART::RCInput_UART(), SITL::JSBSim::send_servos(), ConsoleDevice::set_blocking(), UARTDevice::set_blocking(), AnalogSource_Navio2::set_channel(), Linux::VideoIn::set_crop(), Linux::VideoIn::set_format(), SITL::Gazebo::set_interface_ports(), SITL::SilentWings::set_interface_ports(), Linux::Thread::start(), Linux::SPIDevice::transfer(), and Linux::SPIDevice::transfer_fullduplex().
sync()
void sync (void)
POSIX Sync all pending file changes and metadata on ALL files.
man page sync (2).
Returns
void.
Definition at line 1010 of file posix.c.
syncfs()
int syncfs (int fd)
POSIX Sync pending file changes and metadata for specified fileno.
man page syncfs (2).
Parameters
[in] fd POSIX fileno to sync.
Returns
0.
-1 on error witrh errno set.
Definition at line 1037 of file posix.c.
Referenced by sync().
truncate()
int truncate (const char * path, off_t length)
POSIX truncate named file to length.
man page truncate (2).
Parameters
[in] path file name to truncate.
[in] length length to truncate to.
Returns
0 on sucess.
-1 n fail.
Definition at line 1083 of file posix.c.
unix_time_to_fat()
void unix_time_to_fat (time_t epoch, uint16_t * date, uint16_t * time)
Convert Linux POSIX time_t to FAT32 date and time. NOT POSIX.
man page gmtime (3).
Parameters
[in] epoch unix epoch seconds
[in] *date fat32 date
[in] *time fat32 time
Returns
void
Definition at line 2275 of file posix.c.
Referenced by utime().
unlink()
int unlink (const char * pathname)
POSIX delete a file.
man page unlink (2).
Parameters
[in] pathname filename to delete.
Returns
0 on sucess.
-1 on error with errno set.
Definition at line 1645 of file posix.c.
Referenced by HALSITL::SITL_State::_parse_command_line().
utime()
int utime (const char * filename, const struct utimbuf * times)
Set Modification and Access time of a file.
Parameters
[in] filename file name
[in *times: access and modication utimbuf structure, if NULL use current time
Returns
0 if ok, -1 on error
Definition at line 1334 of file posix.c.
write()
ssize_t write (int fd, const void * buf, size_t count)
POSIX Write count bytes from *buf to fileno fd.
man page write (2).
Parameters
[in] fd POSIX fileno.
[in] buf buffer.
[in] count number of bytes to write.
Returns
count on sucess.
-1 on error with errno set.
Definition at line 1121 of file posix.c.
Referenced by HALSITL::SITL_State::_gps_write(), Linux::OpticalFlow_Onboard::_run_optflow(), ChibiOS::Storage::_save_backup(), HALSITL::Storage::_storage_open(), ChibiOS::Storage::_storage_open(), HALSITL::Storage::_timer_tick(), Linux::Storage::_timer_tick(), ChibiOS::Storage::_timer_tick(), SITL::JSBSim::check_stdout(), AP_HAL::dump_stack_trace(), SITL::JSBSim::expect(), fwrite(), SITL::Vicon::update_vicon_position_estimate(), Linux::Poller::wakeup(), watchdog_save(), ConsoleDevice::write(), Empty::UARTDriver::write(), and AP_HAL::BetterStream::write().
Variable Documentation
__iob
FILE* __iob[MAX_FILES]
Note: fdevopen assigns stdin,stdout,stderr.
POSIX fileno to POSIX FILE stream table
Note: the index of __iob[] is reffered to "fileno".
Reference: libc/avr-libc-1.8.0/libc/stdio.
stdin = __iob[0].
__iob[1] = stdout.
__iob[2] = stderr.
Definition at line 124 of file posix.c.
Referenced by fatfs_to_fileno(), fileno(), fileno_to_stream(), free_file_descriptor(), and new_file_descriptor().
_de
dirent_t _de static
POSIX opendir.
man page readdir(2).
Parameters
[in] dirp DIR * directory handle
Returns
DIR * on sucess.
NULL on error with errno set.
Definition at line 1719 of file posix.c.
Referenced by readdir().
_dp
DIR _dp static
POSIX opendir.
man page opendir (2).
Parameters
[in] pathname directory to delete.
Returns
DIR * on sucess.
NULL on error with errno set.
Definition at line 1700 of file posix.c.
Referenced by opendir().