APM:Libraries: libraries/AP_HAL/utility/print_vprintf.cpp File Reference
print_vprintf.cpp File Reference
#include "print_vprintf.h"
#include <cmath>
#include <stdarg.h>
#include <string.h>
#include <AP_HAL/AP_HAL.h>
#include "ftoa_engine.h"
#include "xtoa_fast.h"
Macros
#define FL_ZFILL 0x01
#define FL_PLUS 0x02
#define FL_SPACE 0x04
#define FL_LPAD 0x08
#define FL_ALT 0x10
#define FL_WIDTH 0x20
#define FL_PREC 0x40
#define FL_LONG 0x80
#define FL_LONGLONG 0x100
#define FL_NEGATIVE FL_LONG
#define FL_ALTUPP FL_PLUS
#define FL_ALTHEX FL_SPACE
#define FL_FLTUPP FL_ALT
#define FL_FLTEXP FL_PREC
#define FL_FLTFIX FL_LONG
Functions
void print_vprintf (AP_HAL::BetterStream *s, const char *fmt, va_list ap)
Macro Definition Documentation
FL_ALT
#define FL_ALT 0x10
Definition at line 54 of file print_vprintf.cpp.
FL_ALTHEX
#define FL_ALTHEX FL_SPACE
Definition at line 63 of file print_vprintf.cpp.
FL_ALTUPP
#define FL_ALTUPP FL_PLUS
Definition at line 62 of file print_vprintf.cpp.
FL_FLTEXP
#define FL_FLTEXP FL_PREC
Definition at line 66 of file print_vprintf.cpp.
FL_FLTFIX
#define FL_FLTFIX FL_LONG
Definition at line 67 of file print_vprintf.cpp.
FL_FLTUPP
#define FL_FLTUPP FL_ALT
Definition at line 65 of file print_vprintf.cpp.
FL_LONG
#define FL_LONG 0x80
Definition at line 57 of file print_vprintf.cpp.
FL_LONGLONG
#define FL_LONGLONG 0x100
Definition at line 58 of file print_vprintf.cpp.
FL_LPAD
#define FL_LPAD 0x08
Definition at line 53 of file print_vprintf.cpp.
FL_NEGATIVE
#define FL_NEGATIVE FL_LONG
Definition at line 60 of file print_vprintf.cpp.
FL_PLUS
#define FL_PLUS 0x02
Definition at line 51 of file print_vprintf.cpp.
FL_PREC
#define FL_PREC 0x40
Definition at line 56 of file print_vprintf.cpp.
FL_SPACE
#define FL_SPACE 0x04
Definition at line 52 of file print_vprintf.cpp.
FL_WIDTH
#define FL_WIDTH 0x20
Definition at line 55 of file print_vprintf.cpp.
FL_ZFILL
#define FL_ZFILL 0x01
Definition at line 50 of file print_vprintf.cpp.
Function Documentation
print_vprintf()
void print_vprintf (AP_HAL::BetterStream * s, const char * fmt, va_list ap)
Definition at line 69 of file print_vprintf.cpp.
Referenced by AP_HAL::BetterStream::vprintf(), AP_HAL::Util::vsnprintf(), and vsnprintf().