APM:Libraries: libraries/RC_Channel/examples/RC_UART/RC_UART.cpp File Reference
RC_UART.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <GCS_MAVLink/include/mavlink/v2.0/checksum.h>
Classes
class RC_UART
Macros
#define NUM_CHANNELS 4
#define ESC_MAGIC 0xF7
#define RC_SPEED 490
#define UART uartE
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
RC_UART rc_uart
Macro Definition Documentation
ESC_MAGIC
#define ESC_MAGIC 0xF7
Definition at line 11 of file RC_UART.cpp.
NUM_CHANNELS
#define NUM_CHANNELS 4
Definition at line 10 of file RC_UART.cpp.
RC_SPEED
#define RC_SPEED 490
Definition at line 12 of file RC_UART.cpp.
UART
#define UART uartE
Definition at line 13 of file RC_UART.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 8 of file RC_UART.cpp.
Referenced by RC_UART::loop(), RC_UART::read_wait(), and RC_UART::setup().
rc_uart
AP_HAL_MAIN_CALLBACKS & rc_uart
Definition at line 120 of file RC_UART.cpp.