APM:Libraries: libraries/RC_Channel/RC_Channels.cpp File Reference
RC_Channels.cpp File Reference
#include <stdlib.h>
#include <cmath>
#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>
#include <AP_Logger/AP_Logger.h>
#include "RC_Channel.h"
Functions
RC_Channels & rc ()
Variables
const AP_HAL::HAL & hal
Function Documentation
rc()
RC_Channels& rc ()
Definition at line 209 of file RC_Channels.cpp.
Referenced by AnalogIn_ADS1115::_update(), AP_RCProtocol_Backend::add_input(), AP_Mount_Backend::angle_input_rad(), DigitalLPF< Vector2f >::apply(), AC_PI_2D::calc_filt_alpha(), AC_PID_2D::calc_filt_alpha(), AC_PID_2D::calc_filt_alpha_d(), AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), chmod(), RC_Channels::clear_overrides(), DigitalLPF< Vector2f >::compute_alpha(), SRV_Channels::copy_radio_in_out(), SRV_Channels::copy_radio_in_out_mask(), RC_Channel::do_aux_function_rc_override_enable(), AP_ICEngine::engine_control(), ftruncate(), AC_PID::get_filt_alpha(), RC_Channels::has_active_overrides(), RC_Channel::has_override(), loop(), luaV_execute(), SRV_Channel::output_ch(), print_radio_values(), AP_Arming::rc_calibration_checks(), AP_RSSI::read_channel_rssi(), rename(), GCS_MAVLINK::send_rc_channels(), GCS_MAVLINK::send_rc_channels_raw(), SRV_Channels::set_output_limit(), RC_Channel::set_override(), RC_Channels::set_override(), setup(), truncate(), AP_ICEngine::update(), RC_Channel::update(), AP_WindVane_Home::update_direction(), AP_Mount_Backend::update_targets_from_rc(), SRV_Channels::upgrade_parameters(), and AP_Logger::Write_RCIN().
Variable Documentation
hal
const AP_HAL::HAL& hal
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 21 of file AC_PID_test.cpp.
Referenced by RC_Channels::get_receiver_rssi(), RC_Channels::get_valid_channel_count(), RC_Channels::read_input(), and RC_Channels::receiver_bind().