APM:Libraries: libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp File Reference
RCProtocolTest.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_RCProtocol/AP_RCProtocol.h>
#include <stdio.h>
Functions
void setup ()
void loop ()
static bool check_result (const char *name, bool bytes, const uint16_t *values, uint8_t nvalues)
static bool test_byte_protocol (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats)
static void send_bit (uint8_t bit, uint32_t baudrate)
static void send_byte (uint8_t b, uint32_t baudrate)
static bool test_pulse_protocol (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats)
static bool test_protocol (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats=1)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static AP_RCProtocol * rcprot
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
check_result()
static bool check_result (const char * name, bool bytes, const uint16_t * values, uint8_t nvalues) static
Definition at line 38 of file RCProtocolTest.cpp.
Referenced by test_byte_protocol(), and test_pulse_protocol().
loop()
void loop (void)
Definition at line 184 of file RCProtocolTest.cpp.
send_bit()
static void send_bit (uint8_t bit, uint32_t baudrate) static
Definition at line 87 of file RCProtocolTest.cpp.
Referenced by send_byte(), and test_pulse_protocol().
send_byte()
static void send_byte (uint8_t b, uint32_t baudrate) static
Definition at line 113 of file RCProtocolTest.cpp.
Referenced by test_pulse_protocol().
setup()
void setup (void)
Definition at line 31 of file RCProtocolTest.cpp.
test_byte_protocol()
static bool test_byte_protocol (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats) static
Definition at line 69 of file RCProtocolTest.cpp.
Referenced by test_protocol().
test_protocol()
static bool test_protocol (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats = 1) static
Definition at line 163 of file RCProtocolTest.cpp.
Referenced by loop().
test_pulse_protocol()
static bool test_pulse_protocol (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats) static
Definition at line 137 of file RCProtocolTest.cpp.
Referenced by test_protocol().
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 26 of file RCProtocolTest.cpp.
Referenced by setup(), and test_byte_protocol().
rcprot
AP_RCProtocol* rcprot static
Definition at line 28 of file RCProtocolTest.cpp.
Referenced by check_result(), send_bit(), test_byte_protocol(), and test_protocol().