APM:Libraries: libraries/AP_Math/examples/rotations/rotations.cpp File Reference
rotations.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>
Functions
void setup ()
void loop ()
static void print_vector (Vector3f &v)
static void test_rotation_accuracy (void)
static void test_euler (enum Rotation rotation, float roll, float pitch, float yaw)
static void test_rotate_inverse (void)
static void test_eulers (void)
static bool have_rotation (const Matrix3f &m)
static void missing_rotations (void)
static void test_rotate_matrix (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
have_rotation()
static bool have_rotation (const Matrix3f & m) static
Definition at line 226 of file rotations.cpp.
Referenced by missing_rotations().
loop()
void loop (void)
Definition at line 295 of file rotations.cpp.
missing_rotations()
static void missing_rotations (void) static
Definition at line 243 of file rotations.cpp.
Referenced by setup().
print_vector()
static void print_vector (Vector3f & v) static
Definition at line 13 of file rotations.cpp.
Referenced by test_euler(), and test_rotate_inverse().
setup()
void setup (void)
Definition at line 283 of file rotations.cpp.
test_euler()
static void test_euler (enum Rotation rotation, float roll, float pitch, float yaw) static
Definition at line 129 of file rotations.cpp.
Referenced by test_eulers().
test_eulers()
static void test_eulers (void) static
Definition at line 181 of file rotations.cpp.
Referenced by setup().
test_rotate_inverse()
static void test_rotate_inverse (void) static
Definition at line 161 of file rotations.cpp.
Referenced by setup().
test_rotate_matrix()
static void test_rotate_matrix (void) static
Definition at line 257 of file rotations.cpp.
Referenced by setup().
test_rotation_accuracy()
static void test_rotation_accuracy (void) static
Definition at line 22 of file rotations.cpp.
Referenced by setup().
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 11 of file rotations.cpp.
Referenced by missing_rotations(), print_vector(), setup(), test_euler(), test_eulers(), test_rotate_inverse(), test_rotate_matrix(), and test_rotation_accuracy().