APM:Libraries: libraries/AP_HAL_ChibiOS/stdio.cpp File Reference
stdio.cpp File Reference
#include <string.h>
#include <hal.h>
#include <memstreams.h>
#include <chprintf.h>
#include <ctype.h>
#include "hwdef/common/posix.h"
#include "hwdef/common/stdio.h"
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL/utility/print_vprintf.h>
Classes
class StdioBufferPrinter
Functions
int vsnprintf (char *str, size_t size, const char *fmt, va_list ap)
int __wrap_snprintf (char *str, size_t size, const char *fmt,...)
int vasprintf (char **strp, const char *fmt, va_list ap)
int asprintf (char **strp, const char *fmt,...)
int vprintf (const char *fmt, va_list arg)
int printf (const char *fmt,...)
int scanf (const char *fmt,...)
int __wrap_sscanf (const char *buf, const char *fmt,...)
static char * _getbase (char *p, int *basep)
static int16_t _atob (uint32_t *vp, char *p, int base)
static int16_t atob (uint32_t *vp, char *p, int base)
Variables
const AP_HAL::HAL & hal
int(* vprintf_console_hook)(const char *fmt, va_list arg) = vprintf
Function Documentation
__wrap_snprintf()
int __wrap_snprintf (char * str, size_t size, const char * fmt, ...)
Definition at line 82 of file stdio.cpp.
__wrap_sscanf()
int __wrap_sscanf (const char * buf, const char * fmt, ...)
Definition at line 159 of file stdio.cpp.
_atob()
static int16_t _atob (uint32_t * vp, char * p, int base) static
Definition at line 195 of file stdio.cpp.
Referenced by atob().
_getbase()
static char* _getbase (char * p, int * basep) static
Definition at line 171 of file stdio.cpp.
Referenced by atob().
asprintf()
int asprintf (char ** strp, const char * fmt, ...)
Definition at line 109 of file stdio.cpp.
Referenced by Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), HALSITL::SITL_State::_parse_command_line(), SITL::JSBSim::create_templates(), Linux::I2CDeviceManager::get_device(), ChibiOS::I2CDevice::I2CDevice(), Linux::Led_Sysfs::init(), Linux::RCInput_Navio2::open_channel(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AnalogSource_Navio2::set_channel(), AP_Param::set_defaults_from_table(), SITL::FlightAxis::soap_request(), ChibiOS::SPIDevice::SPIDevice(), and SITL::JSBSim::start_JSBSim().
atob()
static int16_t atob (uint32_t * vp, char * p, int base) static
Definition at line 249 of file stdio.cpp.
printf()
int printf (const char * fmt, ...)
Definition at line 131 of file stdio.cpp.
Referenced by Linux::UtilRPI::_check_rpi_version(), AP_Compass_BMM150::_compensate_z(), AP_Compass_QMC5883L::_dump_registers(), AP_Compass_MAG3110::_hardware_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), HALSITL::SITL_State::_parse_command_line(), Linux::RCOutput_Bebop::_run_rcout(), HALSITL::SITL_State::_set_param_default(), Linux::VideoIn::_set_streaming(), HALSITL::SITL_State::_update_gps_file(), AP_TECS::_update_pitch(), AP_InertialSensor_Backend::_update_sensor_rate(), HALSITL::SITL_State::_usage(), _usage(), Linux::RCInput::add_dsm_input(), Linux::RCInput::add_sbus_input(), SITL::Aircraft::Aircraft(), Linux::VideoIn::allocate_buffers(), ap_hook_accel_sample(), ap_hook_AHRS_update(), ap_hook_gyro_sample(), ap_hook_setup_complete(), ap_hook_setup_start(), SITL::BalanceBot::BalanceBot(), AP_Logger_SITL::BufferToPage(), AP_Airspeed_MS5525::calculate(), MAVLink_routing::check_and_forward(), AP_RangeFinder_VL53L0X::check_id(), AP_RangeFinder_VL53L1X::check_id(), AP_HAL::Device::check_next_register(), check_result(), SITL::Morse::connect_sockets(), SITL::JSBSim::create_templates(), doargs(), SITL::FlightAxis::exchange_data(), MAVLink_routing::handle_heartbeat(), AP_IRLock_I2C::init(), TSYS01::init(), Linux::RCOutput_Disco::init(), AP_Baro_DPS280::init(), AP_RangeFinder_VL53L0X::init(), AP_Baro_FBM320::init(), Linux::Led_Sysfs::init(), Linux::RCInput_RCProtocol::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_BoardConfig::init(), AP_Compass_RM3100::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_QMC5883L::init(), Linux::GPIO_BBB::init(), AP_Gripper_EPM::init_gripper(), SITL::JSBSim::JSBSim(), MAVLink_routing::learn_route(), AP_Param::load_embedded_param_defaults(), loop(), FlashTest::loop(), main(), Linux::RCInput_RPI::map_peripheral(), SITL::Morse::Morse(), SITL::MultiCopter::MultiCopter(), TCPServerDevice::open(), SITL::JSBSim::open_control_socket(), AP_Logger_SITL::PageToBuffer(), SITL::Aircraft::parse_home(), SITL::FlightAxis::parse_reply(), SITL::Morse::parse_sensors(), PrintCode(), PrintConstant(), PrintDebug(), PrintHeader(), PrintString(), SITL::SilentWings::process_packet(), SITL::QuadPlane::QuadPlane(), read_calibration_data(), AP_IRLock_I2C::read_frames(), Linux::RCOutput_Bebop::read_obs_data(), AP_Airspeed_MS5525::read_prom(), SITL::XPlane::receive_data(), AP_Param::reload_defaults_file(), SITL::Morse::report_FPS(), SITL::FlightAxis::report_FPS(), HAL_Linux::run(), AP_OpticalFlow_PX4Flow::scan_buses(), sdcard_init(), AP_Logger_SITL::SectorErase(), SITL::XPlane::select_data(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), MAVLink_routing::send_to_components(), AP_BoardConfig::sensor_config_error(), AP_HAL::Device::set_checked_register(), SITL::Gazebo::set_interface_ports(), SITL::SilentWings::set_interface_ports(), set_object_value_and_report(), setup(), show_matrix(), show_stack_usage(), sig_alrm(), SITL::SimRover::SimRover(), SITL::Aircraft::smooth_sensors(), SITL::FlightAxis::soap_request(), srxl_channels_get_v5(), AP_Logger_MAVLink::stats_log(), sumd_decode(), SITL::Aircraft::sync_frame_time(), test_matrix_inverse(), AP_Compass_IST8308::timer(), AP_Compass_MMC3416::timer(), AP_Compass_QMC5883L::timer(), type_size(), AP_Proximity_MorseSITL::update(), SITL::Tracker::update(), SITL::SilentWings::update(), SITL::Balloon::update(), SITL::Sprayer::update(), SITL::FlightAxis::update(), SITL::XPlane::update(), SITL::ICEngine::update(), SITL::Aircraft::update_dynamics(), SITL::Gripper_EPM::update_from_demand(), AP_TECS::update_pitch_throttle(), SITL::Vicon::update_vicon_position_estimate(), FlashTest::write(), SITL::XPlane::XPlane(), and ChibiOS::I2CDevice::~I2CDevice().
scanf()
int scanf (const char * fmt, ...)
Definition at line 150 of file stdio.cpp.
vasprintf()
int vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 94 of file stdio.cpp.
Referenced by __wrap_fprintf(), HALSITL::SITL_State::_gps_nmea_printf(), asprintf(), and SITL::FlightAxis::soap_request().
vprintf()
int vprintf (const char * fmt, va_list arg)
Definition at line 118 of file stdio.cpp.
Referenced by AP_HAL::panic().
vsnprintf()
int vsnprintf (char * str, size_t size, const char * fmt, va_list ap)
Definition at line 72 of file stdio.cpp.
Referenced by __wrap_snprintf(), and vasprintf().
Variable Documentation
hal
const AP_HAL::HAL& hal
Definition at line 21 of file AC_PID_test.cpp.
vprintf_console_hook
int(* vprintf_console_hook) (const char *fmt, va_list arg) = vprintf
Definition at line 129 of file stdio.cpp.
Referenced by ChibiOS::UARTDriver::begin(), and printf().