APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/stdio.h File Reference
stdio.h File Reference
#include "posix.h"
#include <stdarg.h>
#include <stdint.h>
#include <stddef.h>
Macros
#define L_tmpnam 32
Functions
int vsnprintf (char *str, size_t size, const char *fmt, va_list ap)
int __wrap_snprintf (char *str, size_t size, const char *fmt,...)
int snprintf (char *str, size_t size, const char *fmt,...)
int vasprintf (char **strp, const char *fmt, va_list ap)
int asprintf (char **strp, const char *fmt,...)
int vprintf (const char *fmt, va_list arg)
int printf (const char *fmt,...)
int scanf (const char *fmt,...)
int __wrap_sscanf (const char *buf, const char *fmt,...)
int sscanf (const char *buf, const char *fmt,...)
int vsscanf (const char *buf, const char *s, va_list ap)
void * malloc (size_t size)
void * calloc (size_t nmemb, size_t size)
void free (void *ptr)
Variables
int(* vprintf_console_hook)(const char *fmt, va_list arg)
Macro Definition Documentation
L_tmpnam
#define L_tmpnam 32
Definition at line 48 of file stdio.h.
Function Documentation
__wrap_snprintf()
int __wrap_snprintf (char * str, size_t size, const char * fmt, ...)
Definition at line 82 of file stdio.cpp.
__wrap_sscanf()
int __wrap_sscanf (const char * buf, const char * fmt, ...)
Definition at line 159 of file stdio.cpp.
asprintf()
int asprintf (char ** strp, const char * fmt, ...)
Definition at line 109 of file stdio.cpp.
Referenced by Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), HALSITL::SITL_State::_parse_command_line(), SITL::JSBSim::create_templates(), Linux::I2CDeviceManager::get_device(), ChibiOS::I2CDevice::I2CDevice(), Linux::Led_Sysfs::init(), Linux::RCInput_Navio2::open_channel(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AnalogSource_Navio2::set_channel(), AP_Param::set_defaults_from_table(), SITL::FlightAxis::soap_request(), ChibiOS::SPIDevice::SPIDevice(), and SITL::JSBSim::start_JSBSim().
calloc()
void* calloc (size_t nmemb, size_t size)
Definition at line 203 of file malloc.c.
Referenced by Linux::OpticalFlow_Onboard::_run_optflow(), Linux::VideoIn::allocate_buffers(), AuxiliaryBus::AuxiliaryBus(), bouncebuffer_init(), ByteBuffer::ByteBuffer(), AC_PolyFence_loader::create_point_array(), AP_ExpandingArrayGeneric::expand(), fdevopen(), AP_GPS::handle_gps_rtcm_data(), AP_SmartRTL::init(), AP_Logger_MAVLink::Init(), AP_InertialSensor::BatchSampler::init(), ChibiOS::Util::malloc_type(), AP_HAL::Util::malloc_type(), Linux::Memory_table::Memory_table(), AP_Logger::msg_fmt_for_name(), new_file_descriptor(), operator new(), operator new[](), ByteBuffer::set_size(), AccelCalibrator::set_status(), CompassCalibrator::set_status(), and vasprintf().
free()
void free (void * ptr)
Definition at line 208 of file malloc.c.
Referenced by HALSITL::SITL_State::_gps_nmea_printf(), Linux::UARTDriver::_parseDevicePath(), Linux::OpticalFlow_Onboard::_run_optflow(), HALSITL::SITL_State::_set_param_default(), HALSITL::UARTDriver::begin(), BM_Crop8bpp(), BM_YuyvToGrey(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), SITL::FlightAxis::exchange_data(), AP_ROMFS::find_decompress(), ChibiOS::Util::flash_bootloader(), free_file_descriptor(), AP_HAL::Util::free_type(), Linux::I2CDeviceManager::get_device(), Linux::PWM_Sysfs_Base::init(), Linux::Led_Sysfs::init(), AP_SmartRTL::init(), AP_InertialSensor::BatchSampler::init(), l_alloc(), main(), AP_Logger::msg_fmt_for_name(), new_file_descriptor(), Linux::RCInput_Navio2::open_channel(), operator delete(), operator delete[](), SITL::Aircraft::parse_home(), lua_scripts::run(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AnalogSource_Navio2::set_channel(), ByteBuffer::set_size(), AccelCalibrator::set_status(), CompassCalibrator::set_status(), SITL::FlightAxis::soap_request(), start_line(), HALSITL::Scheduler::thread_create(), ChibiOS::Scheduler::thread_create(), HALSITL::Scheduler::thread_create_trampoline(), ChibiOS::Scheduler::thread_create_trampoline(), AP_OSD_MAX7456::update_font(), AP_ExpandingArrayGeneric::~AP_ExpandingArrayGeneric(), AuxiliaryBus::~AuxiliaryBus(), ByteBuffer::~ByteBuffer(), ChibiOS::I2CDevice::~I2CDevice(), Linux::Memory_table::~Memory_table(), Linux::PWM_Sysfs_Base::~PWM_Sysfs_Base(), and ChibiOS::SPIDevice::~SPIDevice().
malloc()
void* malloc (size_t size)
Definition at line 169 of file malloc.c.
Referenced by allocate(), BM_Crop8bpp(), BM_YuyvToGrey(), calloc(), error(), AP_ROMFS::find_decompress(), FlashTest::loop(), ChibiOS::DeviceBus::register_periodic_callback(), HALSITL::Scheduler::thread_create(), ChibiOS::Scheduler::thread_create(), and trace().
printf()
int printf (const char * fmt, ...)
Definition at line 131 of file stdio.cpp.
Referenced by Linux::UtilRPI::_check_rpi_version(), AP_Compass_BMM150::_compensate_z(), AP_Compass_QMC5883L::_dump_registers(), AP_Compass_MAG3110::_hardware_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), HALSITL::SITL_State::_parse_command_line(), Linux::RCOutput_Bebop::_run_rcout(), HALSITL::SITL_State::_set_param_default(), Linux::VideoIn::_set_streaming(), HALSITL::SITL_State::_update_gps_file(), AP_TECS::_update_pitch(), AP_InertialSensor_Backend::_update_sensor_rate(), HALSITL::SITL_State::_usage(), _usage(), Linux::RCInput::add_dsm_input(), Linux::RCInput::add_sbus_input(), SITL::Aircraft::Aircraft(), Linux::VideoIn::allocate_buffers(), ap_hook_accel_sample(), ap_hook_AHRS_update(), ap_hook_gyro_sample(), ap_hook_setup_complete(), ap_hook_setup_start(), SITL::BalanceBot::BalanceBot(), AP_Logger_SITL::BufferToPage(), AP_Airspeed_MS5525::calculate(), MAVLink_routing::check_and_forward(), AP_RangeFinder_VL53L0X::check_id(), AP_RangeFinder_VL53L1X::check_id(), AP_HAL::Device::check_next_register(), check_result(), SITL::Morse::connect_sockets(), SITL::JSBSim::create_templates(), doargs(), SITL::FlightAxis::exchange_data(), MAVLink_routing::handle_heartbeat(), AP_IRLock_I2C::init(), TSYS01::init(), Linux::RCOutput_Disco::init(), AP_Baro_DPS280::init(), AP_RangeFinder_VL53L0X::init(), AP_Baro_FBM320::init(), Linux::Led_Sysfs::init(), Linux::RCInput_RCProtocol::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_BoardConfig::init(), AP_Compass_RM3100::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_QMC5883L::init(), Linux::GPIO_BBB::init(), AP_Gripper_EPM::init_gripper(), SITL::JSBSim::JSBSim(), MAVLink_routing::learn_route(), AP_Param::load_embedded_param_defaults(), loop(), FlashTest::loop(), main(), Linux::RCInput_RPI::map_peripheral(), SITL::Morse::Morse(), SITL::MultiCopter::MultiCopter(), TCPServerDevice::open(), SITL::JSBSim::open_control_socket(), AP_Logger_SITL::PageToBuffer(), SITL::Aircraft::parse_home(), SITL::FlightAxis::parse_reply(), SITL::Morse::parse_sensors(), PrintCode(), PrintConstant(), PrintDebug(), PrintHeader(), PrintString(), SITL::SilentWings::process_packet(), SITL::QuadPlane::QuadPlane(), read_calibration_data(), AP_IRLock_I2C::read_frames(), Linux::RCOutput_Bebop::read_obs_data(), AP_Airspeed_MS5525::read_prom(), SITL::XPlane::receive_data(), AP_Param::reload_defaults_file(), SITL::Morse::report_FPS(), SITL::FlightAxis::report_FPS(), HAL_Linux::run(), AP_OpticalFlow_PX4Flow::scan_buses(), sdcard_init(), AP_Logger_SITL::SectorErase(), SITL::XPlane::select_data(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), MAVLink_routing::send_to_components(), AP_BoardConfig::sensor_config_error(), AP_HAL::Device::set_checked_register(), SITL::Gazebo::set_interface_ports(), SITL::SilentWings::set_interface_ports(), set_object_value_and_report(), setup(), show_matrix(), show_stack_usage(), sig_alrm(), SITL::SimRover::SimRover(), SITL::Aircraft::smooth_sensors(), SITL::FlightAxis::soap_request(), srxl_channels_get_v5(), AP_Logger_MAVLink::stats_log(), sumd_decode(), SITL::Aircraft::sync_frame_time(), test_matrix_inverse(), AP_Compass_IST8308::timer(), AP_Compass_MMC3416::timer(), AP_Compass_QMC5883L::timer(), type_size(), AP_Proximity_MorseSITL::update(), SITL::Tracker::update(), SITL::SilentWings::update(), SITL::Balloon::update(), SITL::Sprayer::update(), SITL::FlightAxis::update(), SITL::XPlane::update(), SITL::ICEngine::update(), SITL::Aircraft::update_dynamics(), SITL::Gripper_EPM::update_from_demand(), AP_TECS::update_pitch_throttle(), SITL::Vicon::update_vicon_position_estimate(), FlashTest::write(), SITL::XPlane::XPlane(), and ChibiOS::I2CDevice::~I2CDevice().
scanf()
int scanf (const char * fmt, ...)
Definition at line 150 of file stdio.cpp.
snprintf()
int snprintf (char * str, size_t size, const char * fmt, ...)
Referenced by Linux::GPIO_Sysfs::_export_pin(), HALSITL::SITL_State::_gps_nmea_printf(), Linux::GPIO_Sysfs::_open_pin_value(), HALSITL::SITL_State::_parse_command_line(), Linux::GPIO_Sysfs::_pinMode(), HALSITL::SITL_State::_update_gps_nmea(), check_result(), AP_HAL::dump_stack_trace(), AP_ADSB::get_encoded_callsign_null_char(), AP_Frsky_Telem::init(), GCS_MAVLINK::init(), lua_scripts::load_all_scripts_in_dir(), Linux::I2CBus::open(), Linux::SPIBus::open(), SITL::Morse::output_pwm(), SITL::Morse::output_quad(), SITL::Morse::output_rover(), ChibiOS::DeviceBus::register_periodic_callback(), Linux::SPIDevice::register_periodic_callback(), Linux::I2CDevice::register_periodic_callback(), AP_Proximity_LightWareSF40C::send_request_for_distance(), AP_ADSB::set_callsign(), AP_Proximity_LightWareSF40C::set_forward_direction(), SITL::ADSB_Vehicle::update(), Display::update_battery(), Display::update_gps(), Display::update_mode(), and Display::update_text().
sscanf()
int sscanf (const char * buf, const char * fmt, ...)
Referenced by Linux::UtilRPI::_check_rpi_version(), Linux::I2CDeviceManager::get_device(), main(), SITL::Morse::parse_sensors(), and AP_Proximity_LightWareSF40C::process_reply().
vasprintf()
int vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 94 of file stdio.cpp.
Referenced by __wrap_fprintf(), HALSITL::SITL_State::_gps_nmea_printf(), asprintf(), and SITL::FlightAxis::soap_request().
vprintf()
int vprintf (const char * fmt, va_list arg)
Definition at line 118 of file stdio.cpp.
Referenced by AP_HAL::panic().
vsnprintf()
int vsnprintf (char * str, size_t size, const char * fmt, va_list ap)
Definition at line 72 of file stdio.cpp.
Referenced by __wrap_snprintf(), and vasprintf().
vsscanf()
int vsscanf (const char * buf, const char * s, va_list ap)
Referenced by __wrap_sscanf().
Variable Documentation
vprintf_console_hook
int(* vprintf_console_hook) (const char *fmt, va_list arg)
Definition at line 129 of file stdio.cpp.
Referenced by ChibiOS::UARTDriver::begin(), and printf().