APM:Libraries: libraries/StorageManager/examples/StorageTest/StorageTest.cpp File Reference
StorageTest.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <StorageManager/StorageManager.h>
Macros
#define DO_INITIALISATION 1
Functions
void setup ()
void loop ()
static uint16_t get_random (void)
static uint8_t pvalue (uint16_t offset)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static StorageAccess all_storage [4]
Macro Definition Documentation
DO_INITIALISATION
#define DO_INITIALISATION 1
Definition at line 13 of file StorageTest.cpp.
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
get_random()
static uint16_t get_random (void) static
Definition at line 28 of file StorageTest.cpp.
Referenced by loop().
loop()
void loop (void)
Definition at line 59 of file StorageTest.cpp.
pvalue()
static uint8_t pvalue (uint16_t offset) static
Definition at line 40 of file StorageTest.cpp.
Referenced by loop(), and setup().
setup()
void setup (void)
Definition at line 45 of file StorageTest.cpp.
Variable Documentation
all_storage
StorageAccess all_storage[4] static
Initial value:
= {
    StorageAccess(StorageManager::StorageParam),
    StorageAccess(StorageManager::StorageMission),
    StorageAccess(StorageManager::StorageFence),
    StorageAccess(StorageManager::StorageRally)
}
Definition at line 18 of file StorageTest.cpp.
Referenced by loop(), and setup().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 11 of file StorageTest.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), AP_InertialSensor_LSM9DS1::_accel_init(), AP_InertialSensor_LSM9DS0::_accel_init(), AP_InertialSensor::_calculate_trim(), AP_Compass_LSM9DS1::_check_id(), AP_Baro_LPS2XH::_check_whoami(), AP_InertialSensor_BMI160::_configure_accel(), AP_InertialSensor_BMI160::_configure_fifo(), AP_InertialSensor_BMI160::_configure_gyro(), AP_InertialSensor_BMI160::_configure_int1_pin(), AP_ADC_ADS1115::_convert_register_data_to_mv(), Compass::_detect_backends(), AP_GPS_Backend::_detection_message(), AP_Compass_LSM9DS1::_dump_registers(), HALSITL::SITL_State::_fdm_input_local(), AP_InertialSensor_LSM9DS1::_fifo_reset(), AP_InertialSensor_Invensensev2::_fifo_reset(), AP_InertialSensor_Invensense::_fifo_reset(), AP_InertialSensor_LSM9DS1::_gyro_init(), AP_InertialSensor_LSM9DS0::_gyro_init(), AP_Compass_LSM303D::_hardware_init(), AP_Compass_MAG3110::_hardware_init(), AP_InertialSensor_LSM9DS1::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), Menu::_help(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_BMP085::_init(), AP_RangeFinder_MaxsonarI2CXL::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_BMI160::_init(), AP_InertialSensor_Invensensev2::_init(), AP_InertialSensor_Invensense::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), AP_InertialSensor::_init_gyro(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_LSM9DS1::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), ChibiOS::Scheduler::_io_thread(), AP_Compass_BMM150::_load_trim_values(), ChibiOS::Scheduler::_monitor_thread(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_GPS_UBLOX::_parse_gps(), AP_AccelCal::_printf(), AP_Baro::_probe_i2c_barometers(), AP_RCProtocol_SUMD::_process_byte(), AP_InertialSensor_Backend::_publish_temperature(), ChibiOS::Scheduler::_rcin_thread(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS1::_read_data_transaction_g(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), AP_InertialSensor_LSM9DS1::_read_data_transaction_x(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_BMI160::_read_fifo(), AP_Compass_LSM303D::_read_sample(), AP_GPS_UBLOX::_request_next_config(), HALSITL::Scheduler::_run_io_procs(), ChibiOS::Scheduler::_run_timers(), GCS_MAVLINK::_set_mode_common(), HALSITL::SITL_State::_sitl_setup(), ChibiOS::Scheduler::_storage_thread(), ChibiOS::Scheduler::_timer_thread(), ChibiOS::UARTDriver::_timer_tick(), ChibiOS::I2CDevice::_transfer(), AP_Compass_BMM150::_update(), AP_Airspeed_MS4525::_voltage_correction(), AP_InertialSensor::acal_update(), AP_InertialSensor_BMI055::accel_init(), AP_InertialSensor_BMI088::accel_init(), AP_AHRS_NavEKF::active_EKF_type(), lua_scripts::alloc(), AP_Airspeed_Analog::AP_Airspeed_Analog(), AP_Baro_SITL::AP_Baro_SITL(), AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_Compass_SITL::AP_Compass_SITL(), AP_LeakDetector_Analog::AP_LeakDetector_Analog(), AP_Logger_Block::AP_Logger_Block(), AP_OpticalFlow_Pixart::AP_OpticalFlow_Pixart(), AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_WindVane_Analog::AP_WindVane_Analog(), AP_WindVane_ModernDevice::AP_WindVane_ModernDevice(), AP_BattMonitor::arming_checks(), lua_scripts::atpanic(), ChibiOS::SoftSigReader::attach_capture_timer(), AP_AHRS_NavEKF::attitudes_consistent(), AP_OAPathPlanner::avoidance_thread(), AP_AHRS_DCM::backup_attitude(), HALSITL::UARTDriver::begin(), ChibiOS::UARTDriver::begin(), AP_BoardConfig::board_init_safety(), AP_BoardConfig::board_setup(), AP_BoardConfig::board_setup_sbus(), AP_BoardConfig::board_setup_uart(), AP_Arming::board_voltage_checks(), Compass::cal_update(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), AP_InertialSensor::calibrate_trim(), Compass_PerMotor::calibration_start(), AnalogIn_ADS1115::channel(), AP_AdvancedFailsafe::check(), AP_Tuning::check_controller_error(), AP_Arming::check_failed(), AP_BattMonitor::check_failsafes(), Menu::check_input(), AP_RangeFinder_PWM::check_pin(), AP_RSSI::check_pwm_pin_rssi(), AP_RangeFinder_PWM::check_stop_pin(), ChibiOS::I2CBus::clear_bus(), NavEKF2_core::controlFilterModes(), NavEKF3_core::controlFilterModes(), AP_Param::convert_old_parameter(), RangeFinder::convert_params(), AP_BattMonitor::convert_params(), SRV_Channels::cork(), NavEKF2_core::CovariancePrediction(), NavEKF3_core::CovariancePrediction(), AC_PolyFence_loader::create_point_array(), AP_LandingGear::deployed(), AP_RangeFinder_BBB_PRU::detect(), AP_InertialSensor::detect_backends(), RangeFinder::detect_instance(), AP_Arming::disarm(), ChibiOS::SPIDevice::do_transfer(), GCS_MAVLINK::do_try_send_message(), SRV_Channels::enable_aux_servos(), SRV_Channels::enable_by_mask(), ChibiOS::UARTDriver::end(), StorageManager::erase(), AP_InternalError::error(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), ExpectDelay::ExpectDelay(), AP_Camera::feedback_pin_timer(), GCS_MAVLINK::find_next_bucket_to_send(), ChibiOS::Util::flash_bootloader(), AP_Param::flush(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseMagnetometer(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), RGBLed::get_brightness(), AP_Button::get_mask(), AP_RangeFinder_PWM::get_reading(), AP_RangeFinder_VL53L1X::get_reading(), RC_Channels::get_receiver_rssi(), AP_RangeFinder_VL53L0X::get_SPAD_info(), RC_Channels::get_valid_channel_count(), AP_InertialSensor::gyro_calibration_timing(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), hal_console_vprintf(), AP_IOMCU_FW::handle_code_write(), GCS_MAVLINK::handle_command_flash_bootloader(), GCS_MAVLINK::handle_command_int(), GCS_MAVLINK::handle_command_long(), GCS_MAVLINK::handle_command_preflight_calibration(), GCS_MAVLINK::handle_command_preflight_can(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), AP_Logger::handle_log_send(), AP_Logger::handle_log_sending(), Compass::handle_mag_cal_command(), GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_serial_control(), GCS_MAVLINK::handle_setup_signing(), GCS_MAVLINK::handle_statustext(), AP_Arming::hardware_safety_check(), GCS_MAVLINK::have_flow_control(), AP_AdvancedFailsafe::heartbeat(), NCP5623::hw_init(), PCA9685LED_I2C::hw_init(), ToshibaLED_I2C::hw_init(), DiscreteRGBLed::hw_init(), PixRacerLED::hw_init(), PixRacerLED::hw_set_rgb(), ChibiOS::I2CDevice::I2CDevice(), AP_Baro_ICM20789::imu_i2c_init(), AP_Baro_ICM20789::imu_spi_init(), AP_RAMTRON::init(), AP_Logger_Block::Init(), AP_IRLock_I2C::init(), Display::init(), TSYS01::init(), AP_ADC_ADS1115::init(), AP_IRLock_SITL_Gazebo::init(), AP_IOMCU_FW::init(), AP_Baro_ICM20789::init(), AP_Compass_LSM9DS1::init(), AP_Compass_LSM303D::init(), AP_OpticalFlow_Onboard::init(), AnalogIn_ADS1115::init(), AP_DEVO_Telem::init(), AP_ToneAlarm::init(), Buzzer::init(), AP_OSD_MAX7456::init(), AP_SBusOut::init(), AP_SmartRTL::init(), OreoLED_I2C::init(), AP_RangeFinder_TeraRangerI2C::init(), AP_Airspeed_DLVR::init(), HALSITL::SITL_State::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_SDP3X::init(), AP_Compass_BMM150::init(), AP_Compass_AK8963::init(), AP_Airspeed_MS5525::init(), AP_RSSI::init(), AP_Baro::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), AP_BoardConfig::init(), AP_LandingGear::init(), AP_Compass_MMC3416::init(), Compass::init(), AP_BattMonitor::init(), AP_ADSB::init(), AP_SerialManager::init(), AP_Frsky_Telem::init(), AP_Avoidance::init(), AP_Logger::Init(), AP_OSD::init(), AP_InertialSensor::BatchSampler::init(), GCS_MAVLINK::init(), AP_SerialManager::init_console(), AP_InertialSensor_SITL::init_sensor(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AP_TempCalibration::learn_calibration(), SRV_Channels::limit_slew_rate(), AP_Param::load_all(), lua_scripts::load_all_scripts_in_dir(), AP_Param::load_embedded_param_defaults(), AP_Param::load_object_from_eeprom(), lua_scripts::load_script(), GCS_MAVLINK::load_signing_key(), AP_AHRS_DCM::load_watchdog_home(), AP_Logger::log_while_disarmed(), AP_Scheduler::Log_Write_Performance(), loop(), AP_Scheduler::loop(), lua_scripts::lua_scripts(), main_loop(), AP_OAPathPlanner::mission_avoidance(), AP_OpticalFlow_Pixart::motion_burst(), NavEKF2_core::NavEKF2_core(), NavEKF3_core::NavEKF3_core(), AP_Relay::off(), AP_Relay::on(), Buzzer::on(), AP_OSD::osd_thread(), GCS::out_of_time(), SRV_Channel::output_ch(), AP_HAL::panic(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_write(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), AP_RangeFinder_VL53L0X::performSingleRefCalibration(), AP_OAPathPlanner::pre_arm_check(), AC_PosControl::pre_arm_checks(), AC_AttitudeControl::pre_arm_checks(), SoloGimbalEKF::predictCovariance(), AP_Logger_Block::Prep(), AP_Compass_AK09916::probe_ICM20948(), LoggerMessageWriter_WriteSysInfo::process(), AP_RobotisServo::process_packet(), SRV_Channels::push(), AP_IOMCU_FW::pwm_out_update(), AP_Motors::rc_set_freq(), AP_IOMCU_FW::rcin_update(), AP_IOMCU_FW::rcout_mode_update(), AP_LeakDetector_Digital::read(), AP_BattMonitor_FuelFlow::read(), HALSITL::DigitalSource::read(), AP_GPS_MTK19::read(), AP_GPS_SBF::read(), AP_GPS_UBLOX::read(), AP_Invensensev2_AuxiliaryBusSlave::read(), AP_Invensense_AuxiliaryBusSlave::read(), StorageAccess::read_block(), RC_Channels::read_input(), AP_Airspeed_MS5525::read_prom(), AP_RSSI::read_pwm_pin_rssi(), ChibiOS::Scheduler::reboot(), RC_Channels::receiver_bind(), AP_OpticalFlow_Pixart::reg_read(), AP_OpticalFlow_Pixart::reg_write(), ChibiOS::Scheduler::register_io_process(), ChibiOS::Scheduler::register_timer_process(), AP_Param::reload_defaults_file(), lua_scripts::remove_script(), AP_AHRS_DCM::reset(), Radio_CC2500::Reset(), lua_scripts::run(), AP_Scheduler::run(), Menu::run(), lua_scripts::run_next_script(), SoloGimbalEKF::RunEKF(), ChibiOS::Util::safety_switch_state(), AP_IOMCU_FW::safety_update(), AP_Param::save(), AP_Param::save_sync(), AP_SBusOut::sbus_format_frame(), Compass_PerMotor::scaled_output(), AP_OpticalFlow_PX4Flow::scan_buses(), NavEKF3_core::SelectBodyOdomFusion(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::SelectMagFusion(), NavEKF3_core::SelectMagFusion(), GCS_MAVLINK::send_banner(), GCS_MAVLINK::send_hwstatus(), AP_Logger_MAVLink::send_log_block(), GCS_MAVLINK::send_meminfo(), GCS_MAVLINK::send_power_status(), GCS_MAVLINK::send_servo_output_raw(), GCS_Dummy::send_statustext(), GCS_MAVLINK::send_textv(), GCS::send_textv(), AP_BoardConfig::sensor_config_error(), SRV_Channels::set_aux_channel_default(), SRV_Channels::set_esc_scaling_for(), SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), AP_AHRS_DCM::set_home(), ChibiOS::Util::set_imu_temp(), ChibiOS::UARTDriver::set_options(), AP_SerialManager::set_options(), SRV_Channels::set_rc_frequency(), SRV_Channels::set_safety_limit(), AP_MotorsMulticopter::set_throttle_range(), AP_RTC::set_utc_usec(), setup(), AP_InertialSensor_BMI088::setup_accel_config(), SRV_Channels::setup_failsafe_trim_all_non_motors(), AP_Camera::setup_feedback_callback(), AP_Button::setup_pins(), AP_OpticalFlow_Pixart::setup_sensor(), GCS_MAVLINK::setup_uart(), AP_Logger_Backend::ShouldLog(), AP_InertialSensor::simple_accel_cal(), HALSITL::Scheduler::sitl_end_atomic(), AP_OpticalFlow_Pixart::srom_download(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensense::start(), AP_Compass_IST8310::start_conversion(), MMLPlayer::start_note(), MMLPlayer::start_silence(), AP_Logger_Backend::StartNewLogOK(), MMLPlayer::stop(), AP_Arming::system_checks(), HALSITL::Semaphore::take(), ChibiOS::Semaphore::take(), GCS_MAVLINK::telemetry_delayed(), test_high_low_byte(), AP_Compass_IST8308::timer(), AP_Compass_IST8310::timer(), HALSITL::DigitalSource::toggle(), AP_Relay::toggle(), ChibiOS::I2CDevice::transfer(), ChibiOS::SPIDevice::transfer(), uint32_t___tostring(), CompassLearn::update(), AR_WPNav::update(), AP_RangeFinder_Wasp::update(), AP_IOMCU_FW::update(), AP_SBusOut::update(), AP_WheelEncoder_Quadrature::update(), AP_OpticalFlow_Onboard::update(), AP_RPM_Pin::update(), SITL::BalanceBot::update(), AP_RCProtocol_DSM::update(), AP_ICEngine::update(), AP_Button::update(), AP_RangeFinder_PWM::update(), AP_WindVane::update(), SoloGimbal_Parameters::update(), AP_AHRS_NavEKF::update(), AP_LandingGear::update(), AP_Mission::update(), AP_OSD_MAX7456::update_font(), AP_OSD_MAX7456::update_font_char(), GCS::update_passthru(), AP_WheelEncoder_Quadrature::update_pin(), GCS_MAVLINK::update_receive(), GCS_MAVLINK::update_send(), GCS::update_sensor_status_flags(), NavEKF3::UpdateFilter(), NavEKF2::UpdateFilter(), NavEKF2_core::UpdateFilter(), NavEKF3_core::UpdateFilter(), AP_AHRS_DCM::use_fast_gains(), HALSITL::SITL_State::wait_clock(), AP_InertialSensor::wait_for_sample(), WithSemaphore::WithSemaphore(), HALSITL::DigitalSource::write(), AP_OSD_Backend::write(), ChibiOS::UARTDriver::write(), StorageAccess::write_block(), AP_Logger_Backend::Write_MessageF(), AP_Logger::Write_MessageF(), ChibiOS::UARTDriver::write_pending_bytes(), AP_Logger::Write_Power(), AP_Logger::Write_RCOUT(), AP_Logger_Backend::WriteBlockCheckStartupMessages(), GCS_MAVLINK::zero_rc_outputs(), AP_InertialSensor_Invensense::~AP_InertialSensor_Invensense(), AP_InertialSensor_Invensensev2::~AP_InertialSensor_Invensensev2(), and ExpectDelay::~ExpectDelay().