APM:Libraries: AP_HAL::HAL::Callbacks Struct Reference
AP_HAL::HAL::Callbacks Struct Reference abstract
#include <HAL.h>
Public Member Functions
virtual void setup ()=0
virtual void loop ()=0
Detailed Description
Definition at line 81 of file HAL.h.
Member Function Documentation
loop()
virtual void AP_HAL::HAL::Callbacks::loop () pure virtual
Implemented in AP_HAL::HAL::FunCallbacks, AP_LoggerTest_AllTypes, RC_UART, and FlashTest.
Referenced by main_loop(), HAL_Linux::run(), HAL_Empty::run(), and HAL_SITL::run().
setup()
virtual void AP_HAL::HAL::Callbacks::setup () pure virtual
Implemented in AP_HAL::HAL::FunCallbacks, AP_LoggerTest_AllTypes, RC_UART, and FlashTest.
Referenced by main_loop(), HAL_Linux::run(), HAL_Empty::run(), and HAL_SITL::run().
The documentation for this struct was generated from the following file:
libraries/AP_HAL/HAL.h