APM:Libraries: GCS_MAVLINK Class Reference
GCS_MAVLINK Class Reference abstract
MAVLink transport control class.
#include <GCS.h>
Classes
struct deferred_message_bucket_t
struct deferred_message_t
struct pending_param_reply
struct pending_param_request
struct stream_entries
Public Types
enum streams : uint8_t {
STREAM_RAW_SENSORS, STREAM_EXTENDED_STATUS, STREAM_RC_CHANNELS, STREAM_RAW_CONTROLLER,
STREAM_POSITION, STREAM_EXTRA1, STREAM_EXTRA2, STREAM_EXTRA3,
STREAM_PARAMS, STREAM_ADSB, NUM_STREAMS
}
Public Member Functions
GCS_MAVLINK ()
void update_receive (uint32_t max_time_us=1000)
void update_send ()
void init (AP_HAL::UARTDriver *port, mavlink_channel_t mav_chan)
void setup_uart (uint8_t instance)
void send_message (enum ap_message id)
void send_text (MAV_SEVERITY severity, const char *fmt,...) const
void send_textv (MAV_SEVERITY severity, const char *fmt, va_list arg_list) const
void queued_param_send ()
Send the next pending parameter, called from deferred message handling code.
void queued_mission_request_send ()
bool requesting_mission_items () const
void send_mission_ack (const mavlink_message_t &msg, MAV_MISSION_TYPE mission_type, MAV_MISSION_RESULT result) const
virtual void packetReceived (const mavlink_status_t &status, mavlink_message_t &msg)
void send_message (uint32_t msgid, const char *pkt) const
void send_message (const char *pkt, const mavlink_msg_entry_t *entry) const
AP_HAL::UARTDriver * get_uart ()
virtual uint8_t sysid_my_gcs () const =0
virtual bool sysid_enforce () const
bool is_high_bandwidth ()
bool have_flow_control ()
bool is_active () const
bool is_streaming () const
mavlink_channel_t get_chan () const
uint32_t get_last_heartbeat_time () const
void send_heartbeat (void) const
void send_meminfo (void)
void send_fence_status () const
void send_power_status (void)
void send_battery_status (const uint8_t instance) const
bool send_battery_status () const
void send_distance_sensor () const
virtual void send_rangefinder () const
void send_proximity () const
virtual void send_nav_controller_output () const =0
virtual void send_pid_tuning ()=0
void send_ahrs2 ()
void send_ahrs3 ()
void send_system_time ()
void send_rc_channels () const
void send_rc_channels_raw () const
void send_raw_imu ()
void send_scaled_pressure_instance (uint8_t instance, void(*send_fn)(mavlink_channel_t chan, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature))
void send_scaled_pressure ()
void send_scaled_pressure2 ()
virtual void send_scaled_pressure3 ()
void send_sensor_offsets ()
virtual void send_simstate () const
void send_ahrs ()
void send_battery2 ()
void send_opticalflow ()
virtual void send_attitude () const
void send_autopilot_version () const
void send_extended_sys_state () const
void send_local_position () const
void send_vfr_hud ()
void send_vibration () const
void send_mount_status () const
void send_named_float (const char *name, float value) const
void send_gimbal_report () const
void send_home_position () const
void send_gps_global_origin () const
virtual void send_position_target_global_int ()
virtual void send_position_target_local_ned ()
void send_servo_output_raw ()
void send_accelcal_vehicle_position (uint32_t position)
void send_scaled_imu (uint8_t instance, void(*send_fn)(mavlink_channel_t chan, uint32_t time_ms, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag))
void send_sys_status ()
void send_set_position_target_global_int (uint8_t target_system, uint8_t target_component, const Location &loc)
void send_rpm () const
bool is_private (void) const
FUNCTOR_TYPEDEF (protocol_handler_fn_t, bool, uint8_t, AP_HAL::UARTDriver *)
virtual uint64_t capabilities () const
uint8_t get_stream_slowdown_ms () const
Static Public Member Functions
static void send_collision_all (const AP_Avoidance::Obstacle &threat, MAV_COLLISION_ACTION behaviour)
static uint8_t active_channel_mask (void)
static uint8_t streaming_channel_mask (void)
static void set_channel_private (mavlink_channel_t chan)
static bool is_private (mavlink_channel_t _chan)
static void send_to_components (const mavlink_message_t *msg)
static void disable_channel_routing (mavlink_channel_t chan)
static bool find_by_mavtype (uint8_t mav_type, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
static void update_signing_timestamp (uint64_t timestamp_usec)
static uint8_t packet_overhead_chan (mavlink_channel_t chan)
Public Attributes
bool initialised
uint32_t last_heartbeat_time
uint16_t mission_item_reached_index = AP_MISSION_CMD_INDEX_NONE
int64_t sent_ts1
uint32_t last_sent_ms
const uint16_t interval_ms = 10000
GCS_MAVLINK::protocol_handler_fn_t handler
uint32_t last_mavlink_ms
uint32_t last_alternate_ms
bool active
Static Public Attributes
static const MAV_MISSION_TYPE supported_mission_types [2]
static const struct AP_Param::GroupInfo var_info []
static uint32_t last_radio_status_remrssi_ms
static const struct stream_entries all_stream_entries []
Protected Member Functions
virtual bool in_hil_mode () const
bool mavlink_coordinate_frame_to_location_alt_frame (uint8_t coordinate_frame, Location::AltFrame &frame)
bool accept_packet (const mavlink_status_t &status, mavlink_message_t &msg)
virtual AP_AdvancedFailsafe * get_advanced_failsafe () const
virtual bool set_mode (uint8_t mode)=0
void set_ekf_origin (const Location &loc)
virtual MAV_MODE base_mode () const =0
virtual MAV_STATE system_status () const =0
virtual MAV_VTOL_STATE vtol_state () const
virtual MAV_LANDED_STATE landed_state () const
uint8_t packet_overhead (void) const
virtual bool persist_streamrates () const
void handle_request_data_stream (mavlink_message_t *msg)
virtual void handle_command_ack (const mavlink_message_t *msg)
void handle_set_mode (mavlink_message_t *msg)
void handle_command_int (mavlink_message_t *msg)
MAV_RESULT handle_command_int_do_set_home (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_command_int_packet (const mavlink_command_int_t &packet)
virtual bool set_home_to_current_location (bool lock)=0
virtual bool set_home (const Location &loc, bool lock)=0
MAV_RESULT handle_command_do_set_home (const mavlink_command_long_t &packet)
void handle_mission_request_list (const mavlink_message_t *msg)
void handle_mission_request (mavlink_message_t *msg)
void handle_mission_request_int (mavlink_message_t *msg)
void handle_mission_clear_all (const mavlink_message_t *msg)
virtual void handle_mission_set_current (AP_Mission &mission, mavlink_message_t *msg)
void handle_mission_count (const mavlink_message_t *msg)
void handle_mission_write_partial_list (const mavlink_message_t *msg)
void handle_mission_item (const mavlink_message_t *msg)
void handle_common_param_message (mavlink_message_t *msg)
void handle_param_set (mavlink_message_t *msg)
void handle_param_request_list (mavlink_message_t *msg)
void handle_param_request_read (mavlink_message_t *msg)
virtual bool params_ready () const
virtual void handle_rc_channels_override (const mavlink_message_t *msg)
void handle_system_time_message (const mavlink_message_t *msg)
void handle_common_rally_message (mavlink_message_t *msg)
void handle_rally_fetch_point (mavlink_message_t *msg)
void handle_rally_point (mavlink_message_t *msg)
virtual void handle_mount_message (const mavlink_message_t *msg)
void handle_fence_message (mavlink_message_t *msg)
void handle_param_value (mavlink_message_t *msg)
void handle_radio_status (mavlink_message_t *msg, bool log_radio)
void handle_serial_control (const mavlink_message_t *msg)
void handle_vision_position_delta (mavlink_message_t *msg)
void handle_common_message (mavlink_message_t *msg)
void handle_set_gps_global_origin (const mavlink_message_t *msg)
void handle_setup_signing (const mavlink_message_t *msg)
virtual bool should_zero_rc_outputs_on_reboot () const
MAV_RESULT handle_preflight_reboot (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_set_message_interval (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_get_message_interval (const mavlink_command_long_t &packet)
bool get_ap_message_interval (ap_message id, uint16_t &interval_ms) const
MAV_RESULT handle_command_request_message (const mavlink_command_long_t &packet)
MAV_RESULT handle_rc_bind (const mavlink_command_long_t &packet)
virtual MAV_RESULT handle_flight_termination (const mavlink_command_long_t &packet)
void handle_send_autopilot_version (const mavlink_message_t *msg)
MAV_RESULT handle_command_request_autopilot_capabilities (const mavlink_command_long_t &packet)
virtual void send_banner ()
void handle_device_op_read (mavlink_message_t *msg)
void handle_device_op_write (mavlink_message_t *msg)
void send_timesync ()
uint64_t timesync_receive_timestamp_ns () const
uint64_t timesync_timestamp_ns () const
void handle_timesync (mavlink_message_t *msg)
void handle_statustext (mavlink_message_t *msg)
bool telemetry_delayed () const
virtual uint32_t telem_delay () const =0
MAV_RESULT handle_command_preflight_set_sensor_offsets (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_flash_bootloader (const mavlink_command_long_t &packet)
virtual MAV_RESULT handle_command_preflight_calibration (const mavlink_command_long_t &packet)
virtual MAV_RESULT _handle_command_preflight_calibration (const mavlink_command_long_t &packet)
virtual MAV_RESULT _handle_command_preflight_calibration_baro ()
MAV_RESULT handle_command_preflight_can (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_battery_reset (const mavlink_command_long_t &packet)
void handle_command_long (mavlink_message_t *msg)
MAV_RESULT handle_command_accelcal_vehicle_pos (const mavlink_command_long_t &packet)
virtual MAV_RESULT handle_command_mount (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_mag_cal (const mavlink_command_long_t &packet)
virtual MAV_RESULT handle_command_long_packet (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_camera (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_do_send_banner (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_do_set_roi (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_set_roi (const mavlink_command_long_t &packet)
virtual MAV_RESULT handle_command_do_set_roi (const Location &roi_loc)
MAV_RESULT handle_command_do_gripper (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_do_set_mode (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_get_home_position (const mavlink_command_long_t &packet)
MAV_RESULT handle_command_do_fence_enable (const mavlink_command_long_t &packet)
void handle_optical_flow (const mavlink_message_t *msg)
virtual bool try_send_message (enum ap_message id)
virtual void send_global_position_int ()
bool try_send_compass_message (enum ap_message id)
bool try_send_mission_message (enum ap_message id)
void send_hwstatus ()
void handle_data_packet (mavlink_message_t *msg)
virtual int32_t global_position_int_alt () const
virtual int32_t global_position_int_relative_alt () const
virtual float vfr_hud_climbrate () const
virtual float vfr_hud_airspeed () const
virtual int16_t vfr_hud_throttle () const
virtual float vfr_hud_alt () const
virtual bool allow_disarm () const
void manual_override (RC_Channel *c, int16_t value_in, uint16_t offset, float scaler, const uint32_t tnow, bool reversed=false)
Protected Attributes
AP_Param * _queued_parameter
next parameter to
mavlink_channel_t chan
AP_Int16 streamRates [NUM_STREAMS]
struct {
int64_t sent_ts1
uint32_t last_sent_ms
const uint16_t interval_ms = 10000
} _timesync_request
Static Protected Attributes
static constexpr const float magic_force_arm_value = 2989.0f
static constexpr const float magic_force_disarm_value = 21196.0f
Private Member Functions
void log_mavlink_stats ()
MAV_RESULT _set_mode_common (const MAV_MODE base_mode, const uint32_t custom_mode)
virtual void handleMessage (mavlink_message_t *msg)=0
MAV_RESULT handle_servorelay_message (const mavlink_command_long_t &packet)
bool calibrate_gyros ()
int8_t get_deferred_message_index (const ap_message id) const
int8_t deferred_message_to_send_index ()
ap_message next_deferred_bucket_message_to_send ()
void find_next_bucket_to_send ()
void remove_message_from_bucket (int8_t bucket, ap_message id)
bool should_send_message_in_delay_callback (const ap_message id) const
bool get_default_interval_for_ap_message (const ap_message id, uint16_t &interval) const
bool get_default_interval_for_mavlink_message_id (const uint32_t mavlink_message_id, uint16_t &interval) const
uint16_t get_interval_for_stream (GCS_MAVLINK::streams id) const
bool set_mavlink_message_id_interval (const uint32_t mavlink_id, const uint16_t interval_ms)
ap_message mavlink_id_to_ap_message_id (const uint32_t mavlink_id) const
bool set_ap_message_interval (enum ap_message id, uint16_t interval_ms)
void initialise_message_intervals_for_stream (GCS_MAVLINK::streams id)
void initialise_message_intervals_from_streamrates ()
uint16_t get_reschedule_interval_ms (const deferred_message_bucket_t &deferred) const
bool do_try_send_message (const ap_message id)
void param_io_timer (void)
uint8_t send_parameter_async_replies ()
void send_distance_sensor (const AP_RangeFinder_Backend *sensor, const uint8_t instance) const
virtual bool handle_guided_request (AP_Mission::Mission_Command &cmd)=0
virtual void handle_change_alt_request (AP_Mission::Mission_Command &cmd)=0
void handle_common_mission_message (mavlink_message_t *msg)
void handle_vicon_position_estimate (mavlink_message_t *msg)
void handle_vision_position_estimate (mavlink_message_t *msg)
void handle_global_vision_position_estimate (mavlink_message_t *msg)
void handle_att_pos_mocap (mavlink_message_t *msg)
void handle_common_vision_position_estimate_data (const uint64_t usec, const float x, const float y, const float z, const float roll, const float pitch, const float yaw, const uint16_t payload_size)
void log_vision_position_estimate_data (const uint64_t usec, const float x, const float y, const float z, const float roll, const float pitch, const float yaw)
void lock_channel (mavlink_channel_t chan, bool lock)
uint32_t correct_offboard_timestamp_usec_to_ms (uint64_t offboard_usec, uint16_t payload_size)
void load_signing_key (void)
bool signing_enabled (void) const
void zero_rc_outputs ()
Static Private Member Functions
static bool signing_key_save (const struct SigningKey &key)
static bool signing_key_load (struct SigningKey &key)
static void save_signing_timestamp (bool force_save_now)
Private Attributes
AP_HAL::UARTDriver * _port
The stream we are communicating over.
enum ap_var_type _queued_parameter_type
type of the next
AP_Param::ParamToken _queued_parameter_token
uint16_t _queued_parameter_index
AP_Param token for.
uint16_t _queued_parameter_count
saved count of
uint32_t _queued_parameter_send_time_ms
uint16_t packet_drops
so that we can report to a GCS the number of parameters it should
uint16_t stream_slowdown_ms
AP_HAL::Util::perf_counter_t _perf_packet
AP_HAL::Util::perf_counter_t _perf_update
char _perf_packet_name [16]
char _perf_update_name [16]
struct GCS_MAVLINK::deferred_message_t deferred_message [2]
int8_t next_deferred_message_to_send_cache = -1
deferred_message_bucket_t deferred_message_bucket [10]
uint8_t sending_bucket_id = no_bucket_to_send
Bitmask< MSG_LAST > bucket_message_ids_to_send
Bitmask< MSG_LAST > pushed_ap_message_ids
bool deferred_messages_initialised
mavlink_signing_t signing
struct {
GCS_MAVLINK::protocol_handler_fn_t handler
uint32_t last_mavlink_ms
uint32_t last_alternate_ms
bool active
} alternative
JitterCorrection lag_correction
struct Location global_position_current_loc
uint8_t last_tx_seq
uint16_t send_packet_count
uint32_t last_mavlink_stats_logged
Static Private Attributes
static const uint8_t no_bucket_to_send = -1
static const ap_message no_message_to_send = (ap_message)-1
static uint32_t reserve_param_space_start_ms
static uint8_t mavlink_active = 0
static uint8_t mavlink_private = 0
static uint8_t chan_is_streaming = 0
static MAVLink_routing routing
static ObjectBuffer< pending_param_request > param_requests
static ObjectBuffer< pending_param_reply > param_replies
static bool param_timer_registered
static mavlink_signing_streams_t signing_streams
static uint32_t last_signing_save_ms
static StorageAccess _signing_storage
Friends
class GCS
Detailed Description
MAVLink transport control class.
Definition at line 104 of file AHRS_Test.cpp.
Member Enumeration Documentation
streams
enum GCS_MAVLINK::streams : uint8_t
Enumerator
STREAM_RAW_SENSORS
STREAM_EXTENDED_STATUS
STREAM_RC_CHANNELS
STREAM_RAW_CONTROLLER
STREAM_POSITION
STREAM_EXTRA1
STREAM_EXTRA2
STREAM_EXTRA3
STREAM_PARAMS
STREAM_ADSB
NUM_STREAMS
Definition at line 358 of file GCS.h.
Constructor & Destructor Documentation
GCS_MAVLINK()
GCS_MAVLINK::GCS_MAVLINK ()
Definition at line 79 of file GCS_Common.cpp.
Member Function Documentation
_handle_command_preflight_calibration()
MAV_RESULT GCS_MAVLINK::_handle_command_preflight_calibration (const mavlink_command_long_t & packet) protected virtual
Definition at line 3653 of file GCS_Common.cpp.
Referenced by handle_command_preflight_calibration().
_handle_command_preflight_calibration_baro()
MAV_RESULT GCS_MAVLINK::_handle_command_preflight_calibration_baro () protected virtual
Definition at line 3638 of file GCS_Common.cpp.
Referenced by _handle_command_preflight_calibration().
_set_mode_common()
MAV_RESULT GCS_MAVLINK::_set_mode_common (const MAV_MODE base_mode, const uint32_t custom_mode) private
Definition at line 2346 of file GCS_Common.cpp.
Referenced by handle_command_do_set_mode(), and handle_set_mode().
accept_packet()
bool GCS_MAVLINK::accept_packet (const mavlink_status_t & status, mavlink_message_t & msg) protected
Definition at line 4832 of file GCS_Common.cpp.
Referenced by packetReceived().
active_channel_mask()
static uint8_t GCS_MAVLINK::active_channel_mask (void) inline static
Definition at line 447 of file GCS.h.
Referenced by MAVLink_routing::handle_heartbeat(), is_active(), GCS::send_statustext(), and GCS::send_textv().
allow_disarm()
virtual bool GCS_MAVLINK::allow_disarm () const inline protected virtual
Definition at line 662 of file GCS.h.
Referenced by handle_command_long_packet().
base_mode()
virtual MAV_MODE GCS_MAVLINK::base_mode () const protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by send_heartbeat().
calibrate_gyros()
bool GCS_MAVLINK::calibrate_gyros () private
Definition at line 3628 of file GCS_Common.cpp.
Referenced by _handle_command_preflight_calibration().
capabilities()
uint64_t GCS_MAVLINK::capabilities () const virtual
Definition at line 4965 of file GCS_Common.cpp.
Referenced by send_autopilot_version().
correct_offboard_timestamp_usec_to_ms()
uint32_t GCS_MAVLINK::correct_offboard_timestamp_usec_to_ms (uint64_t offboard_usec, uint16_t payload_size) private
Definition at line 4812 of file GCS_Common.cpp.
Referenced by handle_att_pos_mocap(), and handle_common_vision_position_estimate_data().
deferred_message_to_send_index()
int8_t GCS_MAVLINK::deferred_message_to_send_index () private
Definition at line 1391 of file GCS_Common.cpp.
Referenced by update_send().
disable_channel_routing()
static void GCS_MAVLINK::disable_channel_routing (mavlink_channel_t chan) inline static
Definition at line 473 of file GCS.h.
do_try_send_message()
bool GCS_MAVLINK::do_try_send_message (const ap_message id) private
Definition at line 1349 of file GCS_Common.cpp.
Referenced by update_send().
find_by_mavtype()
static bool GCS_MAVLINK::find_by_mavtype (uint8_t mav_type, uint8_t & sysid, uint8_t & compid, mavlink_channel_t & channel) inline static
Definition at line 479 of file GCS.h.
Referenced by AP_Mount_SToRM32::find_gimbal().
find_next_bucket_to_send()
void GCS_MAVLINK::find_next_bucket_to_send () private
Definition at line 1274 of file GCS_Common.cpp.
Referenced by next_deferred_bucket_message_to_send(), remove_message_from_bucket(), and update_send().
FUNCTOR_TYPEDEF()
GCS_MAVLINK::FUNCTOR_TYPEDEF (protocol_handler_fn_t , bool , uint8_t , AP_HAL::UARTDriver *)
get_advanced_failsafe()
virtual AP_AdvancedFailsafe* GCS_MAVLINK::get_advanced_failsafe () const inline protected virtual
Definition at line 511 of file GCS.h.
Referenced by capabilities(), and handle_flight_termination().
get_ap_message_interval()
bool GCS_MAVLINK::get_ap_message_interval (ap_message id, uint16_t & interval_ms) const protected
Definition at line 2608 of file GCS_Common.cpp.
Referenced by handle_command_get_message_interval().
get_chan()
mavlink_channel_t GCS_MAVLINK::get_chan () const inline
Definition at line 383 of file GCS.h.
Referenced by MissionItemProtocol_Waypoints::get_item(), AP_Logger::handle_log_request_data(), AP_Logger::handle_log_send_data(), AP_Logger::handle_log_send_listing(), AP_Logger::handle_mavlink_msg(), MissionItemProtocol::handle_mission_item(), MissionItemProtocol::handle_mission_request(), MissionItemProtocol::handle_mission_request_int(), MissionItemProtocol::handle_mission_request_list(), AC_Fence::handle_msg(), MissionItemProtocol::queued_request_send(), MissionItemProtocol::send_mission_ack(), and send_simstate().
get_default_interval_for_ap_message()
bool GCS_MAVLINK::get_default_interval_for_ap_message (const ap_message id, uint16_t & interval) const private
Definition at line 4775 of file GCS_Common.cpp.
Referenced by get_default_interval_for_mavlink_message_id().
get_default_interval_for_mavlink_message_id()
bool GCS_MAVLINK::get_default_interval_for_mavlink_message_id (const uint32_t mavlink_message_id, uint16_t & interval) const private
Definition at line 4796 of file GCS_Common.cpp.
Referenced by handle_command_set_message_interval().
get_deferred_message_index()
int8_t GCS_MAVLINK::get_deferred_message_index (const ap_message id) const private
Definition at line 1381 of file GCS_Common.cpp.
Referenced by get_ap_message_interval(), and set_ap_message_interval().
get_interval_for_stream()
uint16_t GCS_MAVLINK::get_interval_for_stream (GCS_MAVLINK::streams id) const private
Definition at line 4737 of file GCS_Common.cpp.
Referenced by get_default_interval_for_ap_message(), and initialise_message_intervals_for_stream().
get_last_heartbeat_time()
uint32_t GCS_MAVLINK::get_last_heartbeat_time () const inline
Definition at line 384 of file GCS.h.
Referenced by AP_Logger::handle_log_send_data(), and AP_Logger::handle_log_send_listing().
get_reschedule_interval_ms()
uint16_t GCS_MAVLINK::get_reschedule_interval_ms (const deferred_message_bucket_t & deferred) const private
Definition at line 1249 of file GCS_Common.cpp.
Referenced by find_next_bucket_to_send(), next_deferred_bucket_message_to_send(), and update_send().
get_stream_slowdown_ms()
uint8_t GCS_MAVLINK::get_stream_slowdown_ms () const inline
Definition at line 499 of file GCS.h.
Referenced by MissionItemProtocol::update().
get_uart()
AP_HAL::UARTDriver* GCS_MAVLINK::get_uart () inline
Definition at line 345 of file GCS.h.
Referenced by AP_AccelCal::_printf(), and GCS::send_to_active_channels().
global_position_int_alt()
int32_t GCS_MAVLINK::global_position_int_alt () const protected virtual
Definition at line 4336 of file GCS_Common.cpp.
Referenced by send_global_position_int().
global_position_int_relative_alt()
int32_t GCS_MAVLINK::global_position_int_relative_alt () const protected virtual
Definition at line 4339 of file GCS_Common.cpp.
Referenced by send_global_position_int().
handle_att_pos_mocap()
void GCS_MAVLINK::handle_att_pos_mocap (mavlink_message_t * msg) private
Definition at line 3228 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_change_alt_request()
virtual void GCS_MAVLINK::handle_change_alt_request (AP_Mission::Mission_Command & cmd) private pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by handle_mission_item().
handle_command_accelcal_vehicle_pos()
MAV_RESULT GCS_MAVLINK::handle_command_accelcal_vehicle_pos (const mavlink_command_long_t & packet) protected
Definition at line 3843 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_ack()
void GCS_MAVLINK::handle_command_ack (const mavlink_message_t * msg) protected virtual
Definition at line 3264 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_command_battery_reset()
MAV_RESULT GCS_MAVLINK::handle_command_battery_reset (const mavlink_command_long_t & packet) protected
Definition at line 3755 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_camera()
MAV_RESULT GCS_MAVLINK::handle_command_camera (const mavlink_command_long_t & packet) protected
Definition at line 3019 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_do_fence_enable()
MAV_RESULT GCS_MAVLINK::handle_command_do_fence_enable (const mavlink_command_long_t & packet) protected
Definition at line 5 of file GCS_Fence.cpp.
Referenced by handle_command_long_packet().
handle_command_do_gripper()
MAV_RESULT GCS_MAVLINK::handle_command_do_gripper (const mavlink_command_long_t & packet) protected
Definition at line 3813 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_do_send_banner()
MAV_RESULT GCS_MAVLINK::handle_command_do_send_banner (const mavlink_command_long_t & packet) protected
Definition at line 3782 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_do_set_home()
MAV_RESULT GCS_MAVLINK::handle_command_do_set_home (const mavlink_command_long_t & packet) protected
Definition at line 3860 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_do_set_mode()
MAV_RESULT GCS_MAVLINK::handle_command_do_set_mode (const mavlink_command_long_t & packet) protected
Definition at line 3788 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_do_set_roi() [1/3]
MAV_RESULT GCS_MAVLINK::handle_command_do_set_roi (const mavlink_command_int_t & packet) protected
Definition at line 4114 of file GCS_Common.cpp.
Referenced by handle_command_do_set_roi(), handle_command_int_packet(), and handle_command_long_packet().
handle_command_do_set_roi() [2/3]
MAV_RESULT GCS_MAVLINK::handle_command_do_set_roi (const mavlink_command_long_t & packet) protected
Definition at line 4136 of file GCS_Common.cpp.
handle_command_do_set_roi() [3/3]
MAV_RESULT GCS_MAVLINK::handle_command_do_set_roi (const Location & roi_loc) protected virtual
Definition at line 4060 of file GCS_Common.cpp.
handle_command_flash_bootloader()
MAV_RESULT GCS_MAVLINK::handle_command_flash_bootloader (const mavlink_command_long_t & packet) protected
Definition at line 3595 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_get_home_position()
MAV_RESULT GCS_MAVLINK::handle_command_get_home_position (const mavlink_command_long_t & packet) protected
Definition at line 3796 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_get_message_interval()
MAV_RESULT GCS_MAVLINK::handle_command_get_message_interval (const mavlink_command_long_t & packet) protected
Definition at line 2629 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_int()
void GCS_MAVLINK::handle_command_int (mavlink_message_t * msg) protected
Definition at line 4165 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_command_int_do_set_home()
MAV_RESULT GCS_MAVLINK::handle_command_int_do_set_home (const mavlink_command_int_t & packet) protected
Definition at line 4084 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_int_packet()
MAV_RESULT GCS_MAVLINK::handle_command_int_packet (const mavlink_command_int_t & packet) protected virtual
Definition at line 4151 of file GCS_Common.cpp.
Referenced by handle_command_int().
handle_command_long()
void GCS_MAVLINK::handle_command_long (mavlink_message_t * msg) protected
Definition at line 4044 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_command_long_packet()
MAV_RESULT GCS_MAVLINK::handle_command_long_packet (const mavlink_command_long_t & packet) protected virtual
Definition at line 3886 of file GCS_Common.cpp.
Referenced by handle_command_long().
handle_command_mag_cal()
MAV_RESULT GCS_MAVLINK::handle_command_mag_cal (const mavlink_command_long_t & packet) protected
Definition at line 3765 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_mount()
MAV_RESULT GCS_MAVLINK::handle_command_mount (const mavlink_command_long_t & packet) protected virtual
Definition at line 3851 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_preflight_calibration()
MAV_RESULT GCS_MAVLINK::handle_command_preflight_calibration (const mavlink_command_long_t & packet) protected virtual
Definition at line 3698 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_preflight_can()
MAV_RESULT GCS_MAVLINK::handle_command_preflight_can (const mavlink_command_long_t & packet) protected
Definition at line 3708 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_preflight_set_sensor_offsets()
MAV_RESULT GCS_MAVLINK::handle_command_preflight_set_sensor_offsets (const mavlink_command_long_t & packet) protected
Definition at line 3609 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_request_autopilot_capabilities()
MAV_RESULT GCS_MAVLINK::handle_command_request_autopilot_capabilities (const mavlink_command_long_t & packet) protected
Definition at line 3770 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_request_message()
MAV_RESULT GCS_MAVLINK::handle_command_request_message (const mavlink_command_long_t & packet) protected
Definition at line 2597 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_command_set_message_interval()
MAV_RESULT GCS_MAVLINK::handle_command_set_message_interval (const mavlink_command_long_t & packet) protected
Definition at line 2568 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_common_message()
void GCS_MAVLINK::handle_common_message (mavlink_message_t * msg) protected
Definition at line 3326 of file GCS_Common.cpp.
handle_common_mission_message()
void GCS_MAVLINK::handle_common_mission_message (mavlink_message_t * msg) private
Definition at line 3495 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_common_param_message()
void GCS_MAVLINK::handle_common_param_message (mavlink_message_t * msg) protected
Definition at line 420 of file GCS_Param.cpp.
Referenced by handle_common_message().
handle_common_rally_message()
void GCS_MAVLINK::handle_common_rally_message (mavlink_message_t * msg) protected
Definition at line 88 of file GCS_Rally.cpp.
Referenced by handle_common_message().
handle_common_vision_position_estimate_data()
void GCS_MAVLINK::handle_common_vision_position_estimate_data (const uint64_t usec, const float x, const float y, const float z, const float roll, const float pitch, const float yaw, const uint16_t payload_size) private
Definition at line 3171 of file GCS_Common.cpp.
Referenced by handle_global_vision_position_estimate(), handle_vicon_position_estimate(), and handle_vision_position_estimate().
handle_data_packet()
void GCS_MAVLINK::handle_data_packet (mavlink_message_t * msg) protected
Definition at line 3110 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_device_op_read()
void GCS_MAVLINK::handle_device_op_read (mavlink_message_t * msg) protected
Definition at line 29 of file GCS_DeviceOp.cpp.
Referenced by handle_common_message().
handle_device_op_write()
void GCS_MAVLINK::handle_device_op_write (mavlink_message_t * msg) protected
Definition at line 81 of file GCS_DeviceOp.cpp.
Referenced by handle_common_message().
handle_fence_message()
void GCS_MAVLINK::handle_fence_message (mavlink_message_t * msg) protected
Definition at line 24 of file GCS_Fence.cpp.
Referenced by handle_common_message().
handle_flight_termination()
MAV_RESULT GCS_MAVLINK::handle_flight_termination (const mavlink_command_long_t & packet) protected virtual
Definition at line 2865 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_global_vision_position_estimate()
void GCS_MAVLINK::handle_global_vision_position_estimate (mavlink_message_t * msg) private
Definition at line 3150 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_guided_request()
virtual bool GCS_MAVLINK::handle_guided_request (AP_Mission::Mission_Command & cmd) private pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by handle_mission_item().
handle_mission_clear_all()
void GCS_MAVLINK::handle_mission_clear_all (const mavlink_message_t * msg) protected
Definition at line 799 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_count()
void GCS_MAVLINK::handle_mission_count (const mavlink_message_t * msg) protected
Definition at line 717 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_item()
void GCS_MAVLINK::handle_mission_item (const mavlink_message_t * msg) protected
Definition at line 960 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_request()
void GCS_MAVLINK::handle_mission_request (mavlink_message_t * msg) protected
Definition at line 646 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_request_int()
void GCS_MAVLINK::handle_mission_request_int (mavlink_message_t * msg) protected
Definition at line 591 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_request_list()
void GCS_MAVLINK::handle_mission_request_list (const mavlink_message_t * msg) protected
Definition at line 513 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_set_current()
void GCS_MAVLINK::handle_mission_set_current (AP_Mission & mission, mavlink_message_t * msg) protected virtual
Definition at line 702 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_write_partial_list()
void GCS_MAVLINK::handle_mission_write_partial_list (const mavlink_message_t * msg) protected
Definition at line 846 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mount_message()
void GCS_MAVLINK::handle_mount_message (const mavlink_message_t * msg) protected virtual
Definition at line 881 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_optical_flow()
void GCS_MAVLINK::handle_optical_flow (const mavlink_message_t * msg) protected
Definition at line 3314 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_param_request_list()
void GCS_MAVLINK::handle_param_request_list (mavlink_message_t * msg) protected
Definition at line 205 of file GCS_Param.cpp.
Referenced by handle_common_param_message().
handle_param_request_read()
void GCS_MAVLINK::handle_param_request_read (mavlink_message_t * msg) protected
Definition at line 224 of file GCS_Param.cpp.
Referenced by handle_common_param_message().
handle_param_set()
void GCS_MAVLINK::handle_param_set (mavlink_message_t * msg) protected
Definition at line 262 of file GCS_Param.cpp.
Referenced by handle_common_param_message().
handle_param_value()
void GCS_MAVLINK::handle_param_value (mavlink_message_t * msg) protected
Definition at line 893 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_preflight_reboot()
MAV_RESULT GCS_MAVLINK::handle_preflight_reboot (const mavlink_command_long_t & packet) protected
Definition at line 2809 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_radio_status()
void GCS_MAVLINK::handle_radio_status (mavlink_message_t * msg, bool log_radio) protected
Definition at line 916 of file GCS_Common.cpp.
handle_rally_fetch_point()
void GCS_MAVLINK::handle_rally_fetch_point (mavlink_message_t * msg) protected
Definition at line 61 of file GCS_Rally.cpp.
Referenced by handle_common_rally_message().
handle_rally_point()
void GCS_MAVLINK::handle_rally_point (mavlink_message_t * msg) protected
Definition at line 22 of file GCS_Rally.cpp.
Referenced by handle_common_rally_message().
handle_rc_bind()
MAV_RESULT GCS_MAVLINK::handle_rc_bind (const mavlink_command_long_t & packet) protected
Definition at line 2883 of file GCS_Common.cpp.
Referenced by handle_command_long_packet().
handle_rc_channels_override()
void GCS_MAVLINK::handle_rc_channels_override (const mavlink_message_t * msg) protected virtual
Definition at line 3274 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_request_data_stream()
void GCS_MAVLINK::handle_request_data_stream (mavlink_message_t * msg) protected
Definition at line 128 of file GCS_Param.cpp.
Referenced by handle_common_message().
handle_send_autopilot_version()
void GCS_MAVLINK::handle_send_autopilot_version (const mavlink_message_t * msg) protected
Definition at line 3555 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_serial_control()
void GCS_MAVLINK::handle_serial_control (const mavlink_message_t * msg) protected
handle a SERIAL_CONTROL message
Definition at line 31 of file GCS_serial_control.cpp.
Referenced by handle_common_message().
handle_servorelay_message()
MAV_RESULT GCS_MAVLINK::handle_servorelay_message (const mavlink_command_long_t & packet) private
Definition at line 5 of file GCS_ServoRelay.cpp.
Referenced by handle_command_long_packet().
handle_set_gps_global_origin()
void GCS_MAVLINK::handle_set_gps_global_origin (const mavlink_message_t * msg) protected
Definition at line 3089 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_set_mode()
void GCS_MAVLINK::handle_set_mode (mavlink_message_t * msg) protected
Definition at line 2329 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_setup_signing()
void GCS_MAVLINK::handle_setup_signing (const mavlink_message_t * msg) protected
Definition at line 66 of file GCS_Signing.cpp.
Referenced by handle_common_message().
handle_statustext()
void GCS_MAVLINK::handle_statustext (mavlink_message_t * msg) protected
Definition at line 2983 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_system_time_message()
void GCS_MAVLINK::handle_system_time_message (const mavlink_message_t * msg) protected
Definition at line 3011 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_timesync()
void GCS_MAVLINK::handle_timesync (mavlink_message_t * msg) protected
Definition at line 2914 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_vicon_position_estimate()
void GCS_MAVLINK::handle_vicon_position_estimate (mavlink_message_t * msg) private
Definition at line 3159 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_vision_position_delta()
void GCS_MAVLINK::handle_vision_position_delta (mavlink_message_t * msg) protected
Definition at line 3132 of file GCS_Common.cpp.
Referenced by handle_common_message().
handle_vision_position_estimate()
void GCS_MAVLINK::handle_vision_position_estimate (mavlink_message_t * msg) private
Definition at line 3141 of file GCS_Common.cpp.
Referenced by handle_common_message().
handleMessage()
virtual void GCS_MAVLINK::handleMessage (mavlink_message_t * msg) private pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by packetReceived().
have_flow_control()
bool GCS_MAVLINK::have_flow_control (void)
Definition at line 104 of file GCS_Param.cpp.
Referenced by AP_Logger::handle_log_sending(), and queued_param_send().
in_hil_mode()
virtual bool GCS_MAVLINK::in_hil_mode () const inline protected virtual
Definition at line 503 of file GCS.h.
Referenced by send_servo_output_raw(), and should_send_message_in_delay_callback().
init()
void GCS_MAVLINK::init (AP_HAL::UARTDriver * port, mavlink_channel_t mav_chan)
Definition at line 85 of file GCS_Common.cpp.
Referenced by setup(), and setup_uart().
initialise_message_intervals_for_stream()
void GCS_MAVLINK::initialise_message_intervals_for_stream (GCS_MAVLINK::streams id) private
Definition at line 4750 of file GCS_Common.cpp.
Referenced by handle_request_data_stream(), and initialise_message_intervals_from_streamrates().
initialise_message_intervals_from_streamrates()
void GCS_MAVLINK::initialise_message_intervals_from_streamrates () private
Definition at line 4766 of file GCS_Common.cpp.
Referenced by update_send().
is_active()
bool GCS_MAVLINK::is_active () const inline
Definition at line 376 of file GCS.h.
Referenced by GCS::send_to_active_channels(), and update_receive().
is_high_bandwidth()
bool GCS_MAVLINK::is_high_bandwidth () inline
Definition at line 372 of file GCS.h.
Referenced by AP_Logger::handle_log_sending().
is_private() [1/2]
static bool GCS_MAVLINK::is_private (mavlink_channel_t _chan) inline static
Definition at line 457 of file GCS.h.
is_private() [2/2]
bool GCS_MAVLINK::is_private (void) const inline
Definition at line 462 of file GCS.h.
Referenced by MAVLink_routing::check_and_forward(), is_private(), and update_receive().
is_streaming()
bool GCS_MAVLINK::is_streaming () const inline
Definition at line 379 of file GCS.h.
Referenced by send_message(), and update_receive().
landed_state()
virtual MAV_LANDED_STATE GCS_MAVLINK::landed_state () const inline protected virtual
Definition at line 519 of file GCS.h.
Referenced by send_extended_sys_state().
load_signing_key()
void GCS_MAVLINK::load_signing_key (void) private
Definition at line 123 of file GCS_Signing.cpp.
Referenced by handle_setup_signing(), and setup_uart().
lock_channel()
void GCS_MAVLINK::lock_channel (mavlink_channel_t chan, bool lock) private
Definition at line 57 of file GCS_MAVLink.cpp.
Referenced by handle_serial_control().
log_mavlink_stats()
void GCS_MAVLINK::log_mavlink_stats () private
Definition at line 1869 of file GCS_Common.cpp.
Referenced by update_receive().
log_vision_position_estimate_data()
void GCS_MAVLINK::log_vision_position_estimate_data (const uint64_t usec, const float x, const float y, const float z, const float roll, const float pitch, const float yaw) private
Definition at line 3208 of file GCS_Common.cpp.
Referenced by handle_att_pos_mocap(), and handle_common_vision_position_estimate_data().
manual_override()
void GCS_MAVLINK::manual_override (RC_Channel * c, int16_t value_in, uint16_t offset, float scaler, const uint32_t tnow, bool reversed = false) protected
Definition at line 4987 of file GCS_Common.cpp.
mavlink_coordinate_frame_to_location_alt_frame()
bool GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame (uint8_t coordinate_frame, Location::AltFrame & frame) protected
Definition at line 4942 of file GCS_Common.cpp.
Referenced by handle_command_int_do_set_home().
mavlink_id_to_ap_message_id()
ap_message GCS_MAVLINK::mavlink_id_to_ap_message_id (const uint32_t mavlink_id) const private
Definition at line 1132 of file GCS_Common.cpp.
Referenced by get_default_interval_for_mavlink_message_id(), handle_command_get_message_interval(), handle_command_request_message(), and set_mavlink_message_id_interval().
next_deferred_bucket_message_to_send()
ap_message GCS_MAVLINK::next_deferred_bucket_message_to_send () private
Definition at line 1320 of file GCS_Common.cpp.
Referenced by update_send().
packet_overhead()
uint8_t GCS_MAVLINK::packet_overhead (void) const inline protected
Definition at line 524 of file GCS.h.
Referenced by queued_param_send(), and GCS::send_to_active_channels().
packet_overhead_chan()
uint8_t GCS_MAVLINK::packet_overhead_chan (mavlink_channel_t chan) static
Definition at line 245 of file GCS_Signing.cpp.
Referenced by MAVLink_routing::check_and_forward(), MAVLink_routing::handle_heartbeat(), packet_overhead(), and MAVLink_routing::send_to_components().
packetReceived()
void GCS_MAVLINK::packetReceived (const mavlink_status_t & status, mavlink_message_t & msg) virtual
Definition at line 1681 of file GCS_Common.cpp.
Referenced by update_receive().
param_io_timer()
void GCS_MAVLINK::param_io_timer (void) private
Definition at line 329 of file GCS_Param.cpp.
Referenced by handle_param_request_read().
params_ready()
virtual bool GCS_MAVLINK::params_ready () const inline protected virtual
Definition at line 557 of file GCS.h.
Referenced by handle_param_request_list().
persist_streamrates()
virtual bool GCS_MAVLINK::persist_streamrates () const inline protected virtual
Definition at line 529 of file GCS.h.
Referenced by handle_request_data_stream().
queued_mission_request_send()
void GCS_MAVLINK::queued_mission_request_send ()
queued_param_send()
void GCS_MAVLINK::queued_param_send ()
Send the next pending parameter, called from deferred message handling code.
Definition at line 37 of file GCS_Param.cpp.
Referenced by try_send_message().
remove_message_from_bucket()
void GCS_MAVLINK::remove_message_from_bucket (int8_t bucket, ap_message id) private
Definition at line 1539 of file GCS_Common.cpp.
Referenced by set_ap_message_interval().
requesting_mission_items()
bool GCS_MAVLINK::requesting_mission_items () const
Definition at line 835 of file GCS_Common.cpp.
Referenced by get_reschedule_interval_ms().
save_signing_timestamp()
void GCS_MAVLINK::save_signing_timestamp (bool force_save_now) static private
Definition at line 200 of file GCS_Signing.cpp.
Referenced by send_message(), and update_signing_timestamp().
send_accelcal_vehicle_position()
void GCS_MAVLINK::send_accelcal_vehicle_position (uint32_t position)
Definition at line 2732 of file GCS_Common.cpp.
Referenced by AP_AccelCal::update().
send_ahrs()
void GCS_MAVLINK::send_ahrs ()
Definition at line 2130 of file GCS_Common.cpp.
Referenced by try_send_message().
send_ahrs2()
void GCS_MAVLINK::send_ahrs2 ()
Definition at line 459 of file GCS_Common.cpp.
Referenced by try_send_message().
send_ahrs3()
void GCS_MAVLINK::send_ahrs3 ()
Definition at line 478 of file GCS_Common.cpp.
Referenced by try_send_message().
send_attitude()
void GCS_MAVLINK::send_attitude () const virtual
Definition at line 4321 of file GCS_Common.cpp.
Referenced by try_send_message().
send_autopilot_version()
void GCS_MAVLINK::send_autopilot_version () const
Definition at line 2416 of file GCS_Common.cpp.
Referenced by handle_command_request_autopilot_capabilities(), and handle_send_autopilot_version().
send_banner()
void GCS_MAVLINK::send_banner () protected virtual
Definition at line 3560 of file GCS_Common.cpp.
Referenced by handle_command_do_send_banner(), and handle_param_request_list().
send_battery2()
void GCS_MAVLINK::send_battery2 ()
Definition at line 2311 of file GCS_Common.cpp.
Referenced by try_send_message().
send_battery_status() [1/2]
void GCS_MAVLINK::send_battery_status (const uint8_t instance) const
Definition at line 275 of file GCS_Common.cpp.
send_battery_status() [2/2]
bool GCS_MAVLINK::send_battery_status () const
Definition at line 318 of file GCS_Common.cpp.
Referenced by try_send_message().
send_collision_all()
void GCS_MAVLINK::send_collision_all (const AP_Avoidance::Obstacle & threat, MAV_COLLISION_ACTION behaviour) static
Definition at line 2711 of file GCS_Common.cpp.
Referenced by AP_Avoidance::handle_threat_gcs_notify().
send_distance_sensor() [1/2]
void GCS_MAVLINK::send_distance_sensor () const
Definition at line 354 of file GCS_Common.cpp.
Referenced by try_send_message().
send_distance_sensor() [2/2]
void GCS_MAVLINK::send_distance_sensor (const AP_RangeFinder_Backend * sensor, const uint8_t instance) const private
Definition at line 331 of file GCS_Common.cpp.
send_extended_sys_state()
void GCS_MAVLINK::send_extended_sys_state () const
Definition at line 4316 of file GCS_Common.cpp.
Referenced by try_send_message().
send_fence_status()
void GCS_MAVLINK::send_fence_status () const
Definition at line 45 of file GCS_Fence.cpp.
Referenced by try_send_message().
send_gimbal_report()
void GCS_MAVLINK::send_gimbal_report () const
Definition at line 4369 of file GCS_Common.cpp.
Referenced by try_send_message().
send_global_position_int()
void GCS_MAVLINK::send_global_position_int () protected virtual
Definition at line 4345 of file GCS_Common.cpp.
Referenced by try_send_message().
send_gps_global_origin()
void GCS_MAVLINK::send_gps_global_origin () const
Definition at line 2540 of file GCS_Common.cpp.
Referenced by try_send_message().
send_heartbeat()
void GCS_MAVLINK::send_heartbeat (void) const
Definition at line 2557 of file GCS_Common.cpp.
Referenced by try_send_message().
send_home_position()
void GCS_MAVLINK::send_home_position () const
Definition at line 2520 of file GCS_Common.cpp.
Referenced by try_send_message().
send_hwstatus()
void GCS_MAVLINK::send_hwstatus () protected
Definition at line 4245 of file GCS_Common.cpp.
Referenced by try_send_message().
send_local_position()
void GCS_MAVLINK::send_local_position () const
Definition at line 2471 of file GCS_Common.cpp.
Referenced by try_send_message().
send_meminfo()
void GCS_MAVLINK::send_meminfo (void)
Definition at line 255 of file GCS_Common.cpp.
Referenced by try_send_message().
send_message() [1/3]
void GCS_MAVLINK::send_message (enum ap_message id)
Definition at line 1666 of file GCS_Common.cpp.
Referenced by handle_command_get_home_position(), handle_command_request_message(), MissionItemProtocol::handle_mission_item(), MissionItemProtocol::init_send_requests(), send_message(), GCS::send_message(), GCS::send_mission_item_reached_message(), GCS::send_to_active_channels(), set_ekf_origin(), and MissionItemProtocol::update().
send_message() [2/3]
void GCS_MAVLINK::send_message (uint32_t msgid, const char * pkt) const inline
Definition at line 328 of file GCS.h.
send_message() [3/3]
void GCS_MAVLINK::send_message (const char * pkt, const mavlink_msg_entry_t * entry) const inline
Definition at line 335 of file GCS.h.
send_mission_ack()
void GCS_MAVLINK::send_mission_ack (const mavlink_message_t & msg, MAV_MISSION_TYPE mission_type, MAV_MISSION_RESULT result) const inline
Definition at line 310 of file GCS.h.
Referenced by handle_mission_clear_all(), handle_mission_item(), and handle_mission_write_partial_list().
send_mount_status()
void GCS_MAVLINK::send_mount_status () const
Definition at line 4378 of file GCS_Common.cpp.
Referenced by try_send_message().
send_named_float()
void GCS_MAVLINK::send_named_float (const char * name, float value) const
Definition at line 2513 of file GCS_Common.cpp.
send_nav_controller_output()
virtual void GCS_MAVLINK::send_nav_controller_output () const pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by try_send_message().
send_opticalflow()
void GCS_MAVLINK::send_opticalflow ()
Definition at line 2374 of file GCS_Common.cpp.
Referenced by try_send_message().
send_parameter_async_replies()
uint8_t GCS_MAVLINK::send_parameter_async_replies () private
Definition at line 378 of file GCS_Param.cpp.
Referenced by queued_param_send().
send_pid_tuning()
virtual void GCS_MAVLINK::send_pid_tuning () pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by try_send_message().
send_position_target_global_int()
virtual void GCS_MAVLINK::send_position_target_global_int () inline virtual
Definition at line 435 of file GCS.h.
Referenced by try_send_message().
send_position_target_local_ned()
virtual void GCS_MAVLINK::send_position_target_local_ned () inline virtual
Definition at line 436 of file GCS.h.
Referenced by try_send_message().
send_power_status()
void GCS_MAVLINK::send_power_status (void)
Definition at line 263 of file GCS_Common.cpp.
Referenced by try_send_message().
send_proximity()
void GCS_MAVLINK::send_proximity () const
Definition at line 408 of file GCS_Common.cpp.
Referenced by send_distance_sensor().
send_rangefinder()
void GCS_MAVLINK::send_rangefinder () const virtual
Definition at line 392 of file GCS_Common.cpp.
Referenced by try_send_message().
send_raw_imu()
void GCS_MAVLINK::send_raw_imu ()
Definition at line 1977 of file GCS_Common.cpp.
Referenced by try_send_message().
send_rc_channels()
void GCS_MAVLINK::send_rc_channels () const
Definition at line 1906 of file GCS_Common.cpp.
Referenced by try_send_message().
send_rc_channels_raw()
void GCS_MAVLINK::send_rc_channels_raw () const
Definition at line 1942 of file GCS_Common.cpp.
Referenced by try_send_message().
send_rpm()
void GCS_MAVLINK::send_rpm () const
Definition at line 4253 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_imu()
void GCS_MAVLINK::send_scaled_imu (uint8_t instance, void(*)(mavlink_channel_t chan, uint32_t time_ms, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag) send_fn)
Definition at line 2005 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure()
void GCS_MAVLINK::send_scaled_pressure ()
Definition at line 2081 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure2()
void GCS_MAVLINK::send_scaled_pressure2 ()
Definition at line 2086 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure3()
void GCS_MAVLINK::send_scaled_pressure3 () virtual
Definition at line 2091 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure_instance()
void GCS_MAVLINK::send_scaled_pressure_instance (uint8_t instance, void(*)(mavlink_channel_t chan, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature) send_fn)
Definition at line 2047 of file GCS_Common.cpp.
Referenced by send_scaled_pressure(), send_scaled_pressure2(), and send_scaled_pressure3().
send_sensor_offsets()
void GCS_MAVLINK::send_sensor_offsets ()
Definition at line 2096 of file GCS_Common.cpp.
Referenced by try_send_message().
send_servo_output_raw()
void GCS_MAVLINK::send_servo_output_raw ()
Definition at line 2685 of file GCS_Common.cpp.
Referenced by try_send_message().
send_set_position_target_global_int()
void GCS_MAVLINK::send_set_position_target_global_int (uint8_t target_system, uint8_t target_component, const Location & loc)
Definition at line 4387 of file GCS_Common.cpp.
send_simstate()
void GCS_MAVLINK::send_simstate () const virtual
Definition at line 3584 of file GCS_Common.cpp.
Referenced by try_send_message().
send_sys_status()
void GCS_MAVLINK::send_sys_status ()
Definition at line 4270 of file GCS_Common.cpp.
Referenced by try_send_message().
send_system_time()
void GCS_MAVLINK::send_system_time ()
Definition at line 1891 of file GCS_Common.cpp.
Referenced by try_send_message().
send_text()
void GCS_MAVLINK::send_text (MAV_SEVERITY severity, const char * fmt, ...) const
Definition at line 908 of file GCS_Common.cpp.
Referenced by AP_AccelCal::_printf(), MissionItemProtocol_Waypoints::complete(), MissionItemProtocol_Rally::complete(), handle_command_long_packet(), AP_Logger::handle_log_request_data(), AP_Logger::handle_log_request_list(), AC_Fence::handle_msg(), handle_preflight_reboot(), handle_rally_fetch_point(), handle_rally_point(), handle_setup_signing(), send_banner(), MissionItemProtocol_Waypoints::timeout(), and MissionItemProtocol_Rally::timeout().
send_textv()
void GCS_MAVLINK::send_textv (MAV_SEVERITY severity, const char * fmt, va_list arg_list) const
Definition at line 902 of file GCS_Common.cpp.
Referenced by send_text().
send_timesync()
void GCS_MAVLINK::send_timesync () protected
Definition at line 2973 of file GCS_Common.cpp.
Referenced by update_receive().
send_to_components()
static void GCS_MAVLINK::send_to_components (const mavlink_message_t * msg) inline static
Definition at line 468 of file GCS.h.
Referenced by AP_BattMonitor::checkPoweringOff(), AP_Camera::configure(), AP_Camera::control(), and AP_Camera::take_picture().
send_vfr_hud()
void GCS_MAVLINK::send_vfr_hud ()
Definition at line 2773 of file GCS_Common.cpp.
Referenced by try_send_message().
send_vibration()
void GCS_MAVLINK::send_vibration () const
Definition at line 2496 of file GCS_Common.cpp.
Referenced by try_send_message().
set_ap_message_interval()
bool GCS_MAVLINK::set_ap_message_interval (enum ap_message id, uint16_t interval_ms) private
Definition at line 1557 of file GCS_Common.cpp.
Referenced by initialise_message_intervals_for_stream(), and set_mavlink_message_id_interval().
set_channel_private()
void GCS_MAVLINK::set_channel_private (mavlink_channel_t chan) static
Definition at line 71 of file GCS_MAVLink.cpp.
set_ekf_origin()
void GCS_MAVLINK::set_ekf_origin (const Location & loc) protected
Definition at line 3061 of file GCS_Common.cpp.
Referenced by handle_set_gps_global_origin().
set_home()
virtual bool GCS_MAVLINK::set_home (const Location & loc, bool lock) protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by handle_command_do_set_home(), and handle_command_int_do_set_home().
set_home_to_current_location()
virtual bool GCS_MAVLINK::set_home_to_current_location (bool lock) protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by handle_command_do_set_home(), and handle_command_int_do_set_home().
set_mavlink_message_id_interval()
bool GCS_MAVLINK::set_mavlink_message_id_interval (const uint32_t mavlink_id, const uint16_t interval_ms) private
Definition at line 1216 of file GCS_Common.cpp.
Referenced by handle_command_set_message_interval(), and initialise_message_intervals_from_streamrates().
set_mode()
virtual bool GCS_MAVLINK::set_mode (uint8_t mode) protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by _set_mode_common().
setup_uart()
void GCS_MAVLINK::setup_uart (uint8_t instance)
Definition at line 111 of file GCS_Common.cpp.
Referenced by GCS::setup_uarts().
should_send_message_in_delay_callback()
bool GCS_MAVLINK::should_send_message_in_delay_callback (const ap_message id) const private
Definition at line 1227 of file GCS_Common.cpp.
Referenced by do_try_send_message().
should_zero_rc_outputs_on_reboot()
virtual bool GCS_MAVLINK::should_zero_rc_outputs_on_reboot () const inline protected virtual
Definition at line 573 of file GCS.h.
Referenced by handle_preflight_reboot().
signing_enabled()
bool GCS_MAVLINK::signing_enabled (void) const private
Definition at line 233 of file GCS_Signing.cpp.
signing_key_load()
bool GCS_MAVLINK::signing_key_load (struct SigningKey & key) static private
Definition at line 49 of file GCS_Signing.cpp.
Referenced by load_signing_key(), and save_signing_timestamp().
signing_key_save()
bool GCS_MAVLINK::signing_key_save (const struct SigningKey & key) static private
Definition at line 41 of file GCS_Signing.cpp.
Referenced by handle_setup_signing(), and save_signing_timestamp().
streaming_channel_mask()
static uint8_t GCS_MAVLINK::streaming_channel_mask (void) inline static
Definition at line 450 of file GCS.h.
Referenced by GCS::send_statustext(), and GCS::send_textv().
sysid_enforce()
virtual bool GCS_MAVLINK::sysid_enforce () const inline virtual
Definition at line 348 of file GCS.h.
Referenced by accept_packet().
sysid_my_gcs()
virtual uint8_t GCS_MAVLINK::sysid_my_gcs () const pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by accept_packet(), handle_rc_channels_override(), and handle_statustext().
system_status()
virtual MAV_STATE GCS_MAVLINK::system_status () const protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by send_heartbeat().
telem_delay()
virtual uint32_t GCS_MAVLINK::telem_delay () const protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by telemetry_delayed().
telemetry_delayed()
bool GCS_MAVLINK::telemetry_delayed () const protected
Definition at line 2666 of file GCS_Common.cpp.
Referenced by do_try_send_message().
timesync_receive_timestamp_ns()
uint64_t GCS_MAVLINK::timesync_receive_timestamp_ns () const protected
Definition at line 2894 of file GCS_Common.cpp.
Referenced by handle_timesync().
timesync_timestamp_ns()
uint64_t GCS_MAVLINK::timesync_timestamp_ns () const protected
Definition at line 2903 of file GCS_Common.cpp.
Referenced by send_timesync().
try_send_compass_message()
bool GCS_MAVLINK::try_send_compass_message (enum ap_message id) protected
Definition at line 4181 of file GCS_Common.cpp.
Referenced by try_send_message().
try_send_message()
bool GCS_MAVLINK::try_send_message (enum ap_message id) protected virtual
Reimplemented in GCS_MAVLINK_Dummy.
Definition at line 4415 of file GCS_Common.cpp.
Referenced by do_try_send_message(), handle_command_get_home_position(), and set_ekf_origin().
try_send_mission_message()
bool GCS_MAVLINK::try_send_mission_message (enum ap_message id) protected
Definition at line 4209 of file GCS_Common.cpp.
Referenced by try_send_message().
update_receive()
void GCS_MAVLINK::update_receive (uint32_t max_time_us = 1000)
Definition at line 1715 of file GCS_Common.cpp.
Referenced by GCS::update_receive().
update_send()
void GCS_MAVLINK::update_send ()
Definition at line 1430 of file GCS_Common.cpp.
Referenced by GCS::update_send().
update_signing_timestamp()
void GCS_MAVLINK::update_signing_timestamp (uint64_t timestamp_usec) static
Definition at line 171 of file GCS_Signing.cpp.
Referenced by AP_RTC::set_utc_usec().
vfr_hud_airspeed()
float GCS_MAVLINK::vfr_hud_airspeed () const protected virtual
Definition at line 2747 of file GCS_Common.cpp.
Referenced by send_vfr_hud().
vfr_hud_alt()
float GCS_MAVLINK::vfr_hud_alt () const protected virtual
Definition at line 2768 of file GCS_Common.cpp.
Referenced by send_vfr_hud().
vfr_hud_climbrate()
float GCS_MAVLINK::vfr_hud_climbrate () const protected virtual
Definition at line 2759 of file GCS_Common.cpp.
Referenced by send_vfr_hud().
vfr_hud_throttle()
virtual int16_t GCS_MAVLINK::vfr_hud_throttle () const inline protected virtual
Definition at line 656 of file GCS.h.
Referenced by GCS::get_hud_throttle(), and send_vfr_hud().
vtol_state()
virtual MAV_VTOL_STATE GCS_MAVLINK::vtol_state () const inline protected virtual
Definition at line 518 of file GCS.h.
Referenced by send_extended_sys_state().
zero_rc_outputs()
void GCS_MAVLINK::zero_rc_outputs () private
Definition at line 2790 of file GCS_Common.cpp.
Referenced by handle_preflight_reboot().
Friends And Related Function Documentation
GCS
friend class GCS friend
Definition at line 295 of file GCS.h.
Member Data Documentation
_perf_packet
AP_HAL::Util::perf_counter_t GCS_MAVLINK::_perf_packet private
Definition at line 710 of file GCS.h.
Referenced by init(), and update_receive().
_perf_packet_name
char GCS_MAVLINK::_perf_packet_name[16] private
Definition at line 712 of file GCS.h.
Referenced by init().
_perf_update
AP_HAL::Util::perf_counter_t GCS_MAVLINK::_perf_update private
Definition at line 711 of file GCS.h.
Referenced by init(), and update_receive().
_perf_update_name
char GCS_MAVLINK::_perf_update_name[16] private
Definition at line 713 of file GCS.h.
Referenced by init().
_port
AP_HAL::UARTDriver* GCS_MAVLINK::_port private
The stream we are communicating over.
Definition at line 679 of file GCS.h.
Referenced by correct_offboard_timestamp_usec_to_ms(), get_uart(), have_flow_control(), init(), queued_param_send(), timesync_receive_timestamp_ns(), and update_receive().
_queued_parameter
AP_Param* GCS_MAVLINK::_queued_parameter protected
next parameter to
Definition at line 521 of file GCS.h.
Referenced by get_reschedule_interval_ms(), handle_param_request_list(), init(), and queued_param_send().
_queued_parameter_count
uint16_t GCS_MAVLINK::_queued_parameter_count private
saved count of
Definition at line 689 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_queued_parameter_index
uint16_t GCS_MAVLINK::_queued_parameter_index private
AP_Param token for.
next queued
Definition at line 687 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_queued_parameter_send_time_ms
uint32_t GCS_MAVLINK::_queued_parameter_send_time_ms private
Definition at line 692 of file GCS.h.
Referenced by handle_param_request_list(), queued_param_send(), and send_parameter_async_replies().
_queued_parameter_token
AP_Param::ParamToken GCS_MAVLINK::_queued_parameter_token private
Definition at line 685 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_queued_parameter_type
enum ap_var_type GCS_MAVLINK::_queued_parameter_type private
type of the next
Perform queued sending operations
Definition at line 683 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_signing_storage
StorageAccess GCS_MAVLINK::_signing_storage static private
Definition at line 873 of file GCS.h.
Referenced by signing_key_load(), and signing_key_save().
_timesync_request
struct { ... } GCS_MAVLINK::_timesync_request
Referenced by handle_timesync(), send_timesync(), and update_receive().
active
bool GCS_MAVLINK::active
Definition at line 885 of file GCS.h.
all_stream_entries
const struct stream_entries GCS_MAVLINK::all_stream_entries[] static
Definition at line 496 of file GCS.h.
Referenced by get_default_interval_for_ap_message(), initialise_message_intervals_for_stream(), and initialise_message_intervals_from_streamrates().
alternative
struct { ... } GCS_MAVLINK::alternative
Referenced by GCS::install_alternative_protocol(), and update_receive().
bucket_message_ids_to_send
Bitmask<MSG_LAST> GCS_MAVLINK::bucket_message_ids_to_send private
Definition at line 746 of file GCS.h.
Referenced by find_next_bucket_to_send(), next_deferred_bucket_message_to_send(), remove_message_from_bucket(), set_ap_message_interval(), and update_send().
chan
mavlink_channel_t GCS_MAVLINK::chan protected
Definition at line 523 of file GCS.h.
Referenced by capabilities(), disable_channel_routing(), get_chan(), handle_att_pos_mocap(), handle_command_get_message_interval(), handle_command_int(), handle_command_long(), handle_data_packet(), handle_device_op_read(), handle_device_op_write(), handle_global_vision_position_estimate(), handle_mission_count(), handle_mission_request_list(), handle_mission_set_current(), handle_mount_message(), handle_param_request_read(), handle_preflight_reboot(), handle_rally_fetch_point(), handle_serial_control(), handle_set_mode(), handle_timesync(), handle_vicon_position_estimate(), handle_vision_position_estimate(), have_flow_control(), init(), is_active(), is_high_bandwidth(), is_private(), load_signing_key(), lock_channel(), log_mavlink_stats(), packet_overhead(), packet_overhead_chan(), packetReceived(), queued_param_send(), save_signing_timestamp(), send_accelcal_vehicle_position(), send_ahrs(), send_ahrs2(), send_ahrs3(), send_attitude(), send_autopilot_version(), send_battery2(), send_battery_status(), send_collision_all(), send_distance_sensor(), send_extended_sys_state(), send_fence_status(), send_gimbal_report(), send_global_position_int(), send_gps_global_origin(), send_heartbeat(), send_home_position(), send_hwstatus(), send_local_position(), send_meminfo(), send_message(), send_mission_ack(), send_mount_status(), send_named_float(), send_opticalflow(), send_parameter_async_replies(), send_power_status(), send_proximity(), send_rangefinder(), send_raw_imu(), send_rc_channels(), send_rc_channels_raw(), send_rpm(), send_scaled_imu(), send_scaled_pressure_instance(), send_sensor_offsets(), send_servo_output_raw(), send_set_position_target_global_int(), send_sys_status(), send_system_time(), send_textv(), send_timesync(), send_vfr_hud(), send_vibration(), setup_uart(), signing_enabled(), telemetry_delayed(), timesync_receive_timestamp_ns(), try_send_compass_message(), try_send_message(), try_send_mission_message(), update_receive(), update_send(), and update_signing_timestamp().
chan_is_streaming
uint8_t GCS_MAVLINK::chan_is_streaming = 0 static private
Definition at line 803 of file GCS.h.
Referenced by send_message(), and streaming_channel_mask().
deferred_message
struct GCS_MAVLINK::deferred_message_t GCS_MAVLINK::deferred_message[2] private
Initial value:
= {
        { MSG_HEARTBEAT, },
        { MSG_NEXT_PARAM, },
    }
Referenced by deferred_message_to_send_index(), get_ap_message_interval(), get_deferred_message_index(), set_ap_message_interval(), and update_send().
deferred_message_bucket
deferred_message_bucket_t GCS_MAVLINK::deferred_message_bucket[10] private
Definition at line 742 of file GCS.h.
Referenced by find_next_bucket_to_send(), get_ap_message_interval(), next_deferred_bucket_message_to_send(), remove_message_from_bucket(), set_ap_message_interval(), update_receive(), and update_send().
deferred_messages_initialised
bool GCS_MAVLINK::deferred_messages_initialised private
Definition at line 785 of file GCS.h.
Referenced by update_send().
global_position_current_loc
struct Location GCS_MAVLINK::global_position_current_loc private
Definition at line 892 of file GCS.h.
Referenced by global_position_int_alt(), send_global_position_int(), send_vfr_hud(), and vfr_hud_alt().
handler
GCS_MAVLINK::protocol_handler_fn_t GCS_MAVLINK::handler
Definition at line 882 of file GCS.h.
Referenced by handle_servorelay_message(), and GCS::install_alternative_protocol().
initialised
bool GCS_MAVLINK::initialised
Definition at line 353 of file GCS.h.
Referenced by init(), queued_param_send(), GCS::send_message(), GCS::send_mission_item_reached_message(), GCS::send_to_active_channels(), GCS::update_receive(), and GCS::update_send().
interval_ms
const uint16_t GCS_MAVLINK::interval_ms = 10000
Definition at line 602 of file GCS.h.
Referenced by deferred_message_to_send_index(), get_ap_message_interval(), get_reschedule_interval_ms(), handle_command_get_message_interval(), handle_command_set_message_interval(), initialise_message_intervals_for_stream(), set_ap_message_interval(), set_mavlink_message_id_interval(), and update_receive().
lag_correction
JitterCorrection GCS_MAVLINK::lag_correction private
Definition at line 888 of file GCS.h.
Referenced by correct_offboard_timestamp_usec_to_ms().
last_alternate_ms
uint32_t GCS_MAVLINK::last_alternate_ms
Definition at line 884 of file GCS.h.
last_heartbeat_time
uint32_t GCS_MAVLINK::last_heartbeat_time
Definition at line 384 of file GCS.h.
Referenced by try_send_message().
last_mavlink_ms
uint32_t GCS_MAVLINK::last_mavlink_ms
Definition at line 883 of file GCS.h.
last_mavlink_stats_logged
uint32_t GCS_MAVLINK::last_mavlink_stats_logged private
Definition at line 913 of file GCS.h.
Referenced by update_receive().
last_radio_status_remrssi_ms
uint32_t GCS_MAVLINK::last_radio_status_remrssi_ms static
Definition at line 389 of file GCS.h.
Referenced by handle_radio_status().
last_sent_ms
uint32_t GCS_MAVLINK::last_sent_ms
Definition at line 601 of file GCS.h.
last_signing_save_ms
uint32_t GCS_MAVLINK::last_signing_save_ms static private
Definition at line 871 of file GCS.h.
Referenced by save_signing_timestamp().
last_tx_seq
uint8_t GCS_MAVLINK::last_tx_seq private
Definition at line 896 of file GCS.h.
Referenced by update_send().
magic_force_arm_value
constexpr const float GCS_MAVLINK::magic_force_arm_value = 2989.0f static protected
Definition at line 659 of file GCS.h.
Referenced by handle_command_long_packet().
magic_force_disarm_value
constexpr const float GCS_MAVLINK::magic_force_disarm_value = 21196.0f static protected
Definition at line 660 of file GCS.h.
Referenced by handle_command_long_packet().
mavlink_active
uint8_t GCS_MAVLINK::mavlink_active = 0 static private
Definition at line 797 of file GCS.h.
Referenced by active_channel_mask(), packetReceived(), send_collision_all(), and set_channel_private().
mavlink_private
uint8_t GCS_MAVLINK::mavlink_private = 0 static private
Definition at line 800 of file GCS.h.
Referenced by is_private(), packetReceived(), and set_channel_private().
mission_item_reached_index
uint16_t GCS_MAVLINK::mission_item_reached_index = AP_MISSION_CMD_INDEX_NONE
Definition at line 392 of file GCS.h.
Referenced by GCS::send_mission_item_reached_message(), and try_send_mission_message().
next_deferred_message_to_send_cache
int8_t GCS_MAVLINK::next_deferred_message_to_send_cache = -1 private
Definition at line 735 of file GCS.h.
Referenced by deferred_message_to_send_index(), and update_send().
no_bucket_to_send
const uint8_t GCS_MAVLINK::no_bucket_to_send = -1 static private
Definition at line 743 of file GCS.h.
Referenced by find_next_bucket_to_send(), is_streaming(), next_deferred_bucket_message_to_send(), and set_ap_message_interval().
no_message_to_send
const ap_message GCS_MAVLINK::no_message_to_send = (ap_message)-1 static private
Definition at line 744 of file GCS.h.
Referenced by next_deferred_bucket_message_to_send(), and update_send().
packet_drops
uint16_t GCS_MAVLINK::packet_drops private
so that we can report to a GCS the number of parameters it should
Count the number of reportable parameters.
Not all parameters can be reported via MAVlink. We count the numberrequests the full set.
Returns
The number of reportable parameters.
Definition at line 704 of file GCS.h.
param_replies
ObjectBuffer< GCS_MAVLINK::pending_param_reply > GCS_MAVLINK::param_replies static private
Definition at line 825 of file GCS.h.
Referenced by param_io_timer(), and send_parameter_async_replies().
param_requests
ObjectBuffer< GCS_MAVLINK::pending_param_request > GCS_MAVLINK::param_requests static private
Definition at line 824 of file GCS.h.
Referenced by handle_param_request_read(), and param_io_timer().
param_timer_registered
bool GCS_MAVLINK::param_timer_registered static private
Definition at line 828 of file GCS.h.
Referenced by handle_param_request_read().
pushed_ap_message_ids
Bitmask<MSG_LAST> GCS_MAVLINK::pushed_ap_message_ids private
Definition at line 754 of file GCS.h.
Referenced by send_message(), and update_send().
reserve_param_space_start_ms
uint32_t GCS_MAVLINK::reserve_param_space_start_ms static private
Definition at line 794 of file GCS.h.
Referenced by handle_param_request_read(), packet_overhead_chan(), and send_parameter_async_replies().
routing
MAVLink_routing GCS_MAVLINK::routing static private
Definition at line 806 of file GCS.h.
Referenced by disable_channel_routing(), find_by_mavtype(), packetReceived(), and send_to_components().
send_packet_count
uint16_t GCS_MAVLINK::send_packet_count private
Definition at line 897 of file GCS.h.
Referenced by log_mavlink_stats(), and update_send().
sending_bucket_id
uint8_t GCS_MAVLINK::sending_bucket_id = no_bucket_to_send private
Definition at line 745 of file GCS.h.
Referenced by find_next_bucket_to_send(), is_streaming(), next_deferred_bucket_message_to_send(), remove_message_from_bucket(), set_ap_message_interval(), and update_send().
sent_ts1
int64_t GCS_MAVLINK::sent_ts1
Definition at line 600 of file GCS.h.
signing
mavlink_signing_t GCS_MAVLINK::signing private
Definition at line 869 of file GCS.h.
Referenced by load_signing_key().
signing_streams
mavlink_signing_streams_t GCS_MAVLINK::signing_streams static private
Definition at line 870 of file GCS.h.
Referenced by load_signing_key().
stream_slowdown_ms
uint16_t GCS_MAVLINK::stream_slowdown_ms private
Definition at line 707 of file GCS.h.
Referenced by get_reschedule_interval_ms(), get_stream_slowdown_ms(), and handle_radio_status().
streamRates
AP_Int16 GCS_MAVLINK::streamRates[NUM_STREAMS] protected
Definition at line 527 of file GCS.h.
Referenced by get_interval_for_stream(), and handle_request_data_stream().
supported_mission_types
const MAV_MISSION_TYPE GCS_MAVLINK::supported_mission_types static
Initial value:
= {
    MAV_MISSION_TYPE_MISSION,
    MAV_MISSION_TYPE_RALLY,
}
Definition at line 320 of file GCS.h.
Referenced by requesting_mission_items().
var_info
const AP_Param::GroupInfo GCS_MAVLINK::var_info static
Initial value:
= {
        AP_GROUPEND
}
Definition at line 350 of file GCS.h.
Referenced by GCS_MAVLINK().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/examples/AHRS_Test/AHRS_Test.cpp
libraries/GCS_MAVLink/GCS.h
libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp
libraries/GCS_MAVLink/examples/routing/routing.cpp
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_DeviceOp.cpp
libraries/GCS_MAVLink/GCS_Fence.cpp
libraries/GCS_MAVLink/GCS_MAVLink.cpp
libraries/GCS_MAVLink/GCS_Param.cpp
libraries/GCS_MAVLink/GCS_Rally.cpp
libraries/GCS_MAVLink/GCS_serial_control.cpp
libraries/GCS_MAVLink/GCS_ServoRelay.cpp
libraries/GCS_MAVLink/GCS_Signing.cpp