APM:Libraries: libraries/AP_ROMFS/tinf.h File Reference
tinf.h File Reference
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
Classes
struct TINF_TREE
struct TINF_DATA
Macros
#define TINFCC
#define TINF_OK 0
#define TINF_DONE 1
#define TINF_DATA_ERROR (-3)
#define TINF_CHKSUM_ERROR (-4)
#define TINF_DICT_ERROR (-5)
#define TINF_CHKSUM_NONE 0
#define TINF_CHKSUM_ADLER 1
#define TINF_CHKSUM_CRC 2
#define TINF_ARRAY_SIZE(arr) (sizeof(arr) / sizeof(*(arr)))
#define TINF_PUT(d, c)
Typedefs
typedef struct TINF_DATA TINF_DATA
Functions
unsigned char TINFCC uzlib_get_byte (TINF_DATA *d)
void TINFCC uzlib_init (void)
void TINFCC uzlib_uncompress_init (TINF_DATA *d, void *dict, unsigned int dictLen)
int TINFCC uzlib_uncompress (TINF_DATA *d)
int TINFCC uzlib_uncompress_chksum (TINF_DATA *d)
int TINFCC uzlib_zlib_parse_header (TINF_DATA *d)
int TINFCC uzlib_gzip_parse_header (TINF_DATA *d)
void TINFCC uzlib_compress (void *data, const uint8_t *src, unsigned slen)
uint32_t TINFCC uzlib_adler32 (const void *data, unsigned int length, uint32_t prev_sum)
uint32_t TINFCC uzlib_crc32 (const void *data, unsigned int length, uint32_t crc)
Macro Definition Documentation
TINF_ARRAY_SIZE
#define TINF_ARRAY_SIZE (arr) (sizeof(arr) / sizeof(*(arr)))
Definition at line 45 of file tinf.h.
TINF_CHKSUM_ADLER
#define TINF_CHKSUM_ADLER 1
Definition at line 41 of file tinf.h.
TINF_CHKSUM_CRC
#define TINF_CHKSUM_CRC 2
Definition at line 42 of file tinf.h.
TINF_CHKSUM_ERROR
#define TINF_CHKSUM_ERROR (-4)
Definition at line 36 of file tinf.h.
TINF_CHKSUM_NONE
#define TINF_CHKSUM_NONE 0
Definition at line 40 of file tinf.h.
TINF_DATA_ERROR
#define TINF_DATA_ERROR (-3)
Definition at line 35 of file tinf.h.
TINF_DICT_ERROR
#define TINF_DICT_ERROR (-5)
Definition at line 37 of file tinf.h.
TINF_DONE
#define TINF_DONE 1
Definition at line 34 of file tinf.h.
TINF_OK
#define TINF_OK 0
Definition at line 32 of file tinf.h.
TINF_PUT
#define TINF_PUT (d, c)
Value:
{ \
        *d->dest++ = c; \
        if (d->dict_ring) { d->dict_ring[d->dict_idx++] = c; if (d->dict_idx == d->dict_size) d->dict_idx = 0; } \
    }
Definition at line 97 of file tinf.h.
TINFCC
#define TINFCC
Definition at line 23 of file tinf.h.
Typedef Documentation
TINF_DATA
typedef struct TINF_DATA TINF_DATA
Function Documentation
uzlib_adler32()
uint32_t TINFCC uzlib_adler32 (const void * data, unsigned int length, uint32_t prev_sum)
uzlib_compress()
void TINFCC uzlib_compress (void * data, const uint8_t * src, unsigned slen)
uzlib_crc32()
uint32_t TINFCC uzlib_crc32 (const void * data, unsigned int length, uint32_t crc)
uzlib_get_byte()
unsigned char TINFCC uzlib_get_byte (TINF_DATA * d)
Definition at line 176 of file tinflate.cpp.
Referenced by tinf_get_be_uint32(), tinf_get_le_uint32(), tinf_get_uint16(), tinf_getbit(), tinf_inflate_uncompressed_block(), tinf_skip_bytes(), and uzlib_gzip_parse_header().
uzlib_gzip_parse_header()
int TINFCC uzlib_gzip_parse_header (TINF_DATA * d)
Definition at line 59 of file tinfgzip.cpp.
Referenced by AP_ROMFS::find_decompress().
uzlib_init()
void TINFCC uzlib_init (void)
Definition at line 473 of file tinflate.cpp.
uzlib_uncompress()
int TINFCC uzlib_uncompress (TINF_DATA * d)
Definition at line 502 of file tinflate.cpp.
Referenced by AP_ROMFS::find_decompress().
uzlib_uncompress_chksum()
int TINFCC uzlib_uncompress_chksum (TINF_DATA * d)
uzlib_uncompress_init()
void TINFCC uzlib_uncompress_init (TINF_DATA * d, void * dict, unsigned int dictLen)
Definition at line 487 of file tinflate.cpp.
Referenced by AP_ROMFS::find_decompress().
uzlib_zlib_parse_header()
int TINFCC uzlib_zlib_parse_header (TINF_DATA * d)