APM:Libraries: libraries/AP_ROMFS/tinfgzip.cpp File Reference
tinfgzip.cpp File Reference
#include "tinf.h"
Macros
#define FTEXT 1
#define FHCRC 2
#define FEXTRA 4
#define FNAME 8
#define FCOMMENT 16
Functions
void tinf_skip_bytes (TINF_DATA *d, int num)
uint16_t tinf_get_uint16 (TINF_DATA *d)
int uzlib_gzip_parse_header (TINF_DATA *d)
Macro Definition Documentation
FCOMMENT
#define FCOMMENT 16
Definition at line 42 of file tinfgzip.cpp.
FEXTRA
#define FEXTRA 4
Definition at line 40 of file tinfgzip.cpp.
FHCRC
#define FHCRC 2
Definition at line 39 of file tinfgzip.cpp.
FNAME
#define FNAME 8
Definition at line 41 of file tinfgzip.cpp.
FTEXT
#define FTEXT 1
Definition at line 38 of file tinfgzip.cpp.
Function Documentation
tinf_get_uint16()
uint16_t tinf_get_uint16 (TINF_DATA * d)
Definition at line 52 of file tinfgzip.cpp.
Referenced by uzlib_gzip_parse_header().
tinf_skip_bytes()
void tinf_skip_bytes (TINF_DATA * d, int num)
Definition at line 47 of file tinfgzip.cpp.
Referenced by uzlib_gzip_parse_header().
uzlib_gzip_parse_header()
int uzlib_gzip_parse_header (TINF_DATA * d)
Definition at line 59 of file tinfgzip.cpp.
Referenced by AP_ROMFS::find_decompress().