APM:Libraries: libraries/AP_ROMFS/tinflate.cpp File Reference
tinflate.cpp File Reference
#include <assert.h>
#include "tinf.h"
Functions
uint32_t tinf_get_le_uint32 (TINF_DATA *d)
uint32_t tinf_get_be_uint32 (TINF_DATA *d)
static void tinf_build_fixed_trees (TINF_TREE *lt, TINF_TREE *dt)
static void tinf_build_tree (TINF_TREE *t, const unsigned char *lengths, unsigned int num)
unsigned char uzlib_get_byte (TINF_DATA *d)
static int tinf_getbit (TINF_DATA *d)
static unsigned int tinf_read_bits (TINF_DATA *d, int num, int base)
static int tinf_decode_symbol (TINF_DATA *d, TINF_TREE *t)
static int tinf_decode_trees (TINF_DATA *d, TINF_TREE *lt, TINF_TREE *dt)
static int tinf_inflate_block_data (TINF_DATA *d, TINF_TREE *lt, TINF_TREE *dt)
static int tinf_inflate_uncompressed_block (TINF_DATA *d)
void uzlib_init (void)
void uzlib_uncompress_init (TINF_DATA *d, void *dict, unsigned int dictLen)
int uzlib_uncompress (TINF_DATA *d)
Variables
static const unsigned char length_bits [30]
static const unsigned short length_base [30]
static const unsigned char dist_bits [30]
static const unsigned short dist_base [30]
static const unsigned char clcidx []
Function Documentation
tinf_build_fixed_trees()
static void tinf_build_fixed_trees (TINF_TREE * lt, TINF_TREE * dt) static
Definition at line 120 of file tinflate.cpp.
Referenced by uzlib_uncompress().
tinf_build_tree()
static void tinf_build_tree (TINF_TREE * t, const unsigned char * lengths, unsigned int num) static
Definition at line 145 of file tinflate.cpp.
Referenced by tinf_decode_trees().
tinf_decode_symbol()
static int tinf_decode_symbol (TINF_DATA * d, TINF_TREE * t) static
Definition at line 261 of file tinflate.cpp.
Referenced by tinf_decode_trees(), and tinf_inflate_block_data().
tinf_decode_trees()
static int tinf_decode_trees (TINF_DATA * d, TINF_TREE * lt, TINF_TREE * dt) static
Definition at line 288 of file tinflate.cpp.
Referenced by uzlib_uncompress().
tinf_get_be_uint32()
uint32_t tinf_get_be_uint32 (TINF_DATA * d)
Definition at line 212 of file tinflate.cpp.
tinf_get_le_uint32()
uint32_t tinf_get_le_uint32 (TINF_DATA * d)
Definition at line 202 of file tinflate.cpp.
tinf_getbit()
static int tinf_getbit (TINF_DATA * d) static
Definition at line 223 of file tinflate.cpp.
Referenced by tinf_decode_symbol(), tinf_read_bits(), and uzlib_uncompress().
tinf_inflate_block_data()
static int tinf_inflate_block_data (TINF_DATA * d, TINF_TREE * lt, TINF_TREE * dt) static
Definition at line 375 of file tinflate.cpp.
Referenced by uzlib_uncompress().
tinf_inflate_uncompressed_block()
static int tinf_inflate_uncompressed_block (TINF_DATA * d) static
Definition at line 437 of file tinflate.cpp.
Referenced by uzlib_uncompress().
tinf_read_bits()
static unsigned int tinf_read_bits (TINF_DATA * d, int num, int base) static
Definition at line 243 of file tinflate.cpp.
Referenced by tinf_decode_trees(), tinf_inflate_block_data(), and uzlib_uncompress().
uzlib_get_byte()
unsigned char uzlib_get_byte (TINF_DATA * d)
Definition at line 176 of file tinflate.cpp.
Referenced by tinf_get_be_uint32(), tinf_get_le_uint32(), tinf_get_uint16(), tinf_getbit(), tinf_inflate_uncompressed_block(), tinf_skip_bytes(), and uzlib_gzip_parse_header().
uzlib_init()
void uzlib_init (void)
Definition at line 473 of file tinflate.cpp.
uzlib_uncompress()
int uzlib_uncompress (TINF_DATA * d)
Definition at line 502 of file tinflate.cpp.
Referenced by AP_ROMFS::find_decompress().
uzlib_uncompress_init()
void uzlib_uncompress_init (TINF_DATA * d, void * dict, unsigned int dictLen)
Definition at line 487 of file tinflate.cpp.
Referenced by AP_ROMFS::find_decompress().
Variable Documentation
clcidx
const unsigned char clcidx[] static
Initial value:
= {
   16, 17, 18, 0, 8, 7, 9, 6,
   10, 5, 11, 4, 12, 3, 13, 2,
   14, 1, 15
}
Definition at line 90 of file tinflate.cpp.
Referenced by tinf_decode_trees().
dist_base
const unsigned short dist_base[30] static
Initial value:
= {
   1, 2, 3, 4, 5, 7, 9, 13,
   17, 25, 33, 49, 65, 97, 129, 193,
   257, 385, 513, 769, 1025, 1537, 2049, 3073,
   4097, 6145, 8193, 12289, 16385, 24577
}
Definition at line 80 of file tinflate.cpp.
Referenced by tinf_inflate_block_data(), and uzlib_init().
dist_bits
const unsigned char dist_bits[30] static
Initial value:
= {
   0, 0, 0, 0, 1, 1, 2, 2,
   3, 3, 4, 4, 5, 5, 6, 6,
   7, 7, 8, 8, 9, 9, 10, 10,
   11, 11, 12, 12, 13, 13
}
Definition at line 74 of file tinflate.cpp.
Referenced by tinf_inflate_block_data(), and uzlib_init().
length_base
const unsigned short length_base[30] static
Initial value:
= {
   3, 4, 5, 6, 7, 8, 9, 10,
   11, 13, 15, 17, 19, 23, 27, 31,
   35, 43, 51, 59, 67, 83, 99, 115,
   131, 163, 195, 227, 258
}
Definition at line 67 of file tinflate.cpp.
Referenced by tinf_inflate_block_data(), and uzlib_init().
length_bits
const unsigned char length_bits[30] static
Initial value:
= {
   0, 0, 0, 0, 0, 0, 0, 0,
   1, 1, 1, 1, 2, 2, 2, 2,
   3, 3, 3, 3, 4, 4, 4, 4,
   5, 5, 5, 5
}
Definition at line 61 of file tinflate.cpp.
Referenced by tinf_inflate_block_data(), and uzlib_init().