APM:Libraries: libraries/AP_HAL/examples/UART_test/UART_test.cpp File Reference
UART_test.cpp File Reference
#include <AP_HAL/AP_HAL.h>
Functions
void setup ()
void loop ()
static void setup_uart (AP_HAL::UARTDriver *uart, const char *name)
static void test_uart (AP_HAL::UARTDriver *uart, const char *name)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 54 of file UART_test.cpp.
setup()
void setup (void)
Definition at line 29 of file UART_test.cpp.
setup_uart()
static void setup_uart (AP_HAL::UARTDriver * uart, const char * name) static
Definition at line 19 of file UART_test.cpp.
Referenced by setup().
test_uart()
static void test_uart (AP_HAL::UARTDriver * uart, const char * name) static
Definition at line 44 of file UART_test.cpp.
Referenced by loop().
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 14 of file UART_test.cpp.
Referenced by loop(), and setup().