APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/watchdog.c File Reference
watchdog.c File Reference
#include "hal.h"
#include "watchdog.h"
#include "stm32_util.h"
Classes
struct IWDG_Regs
Macros
#define IWDGD (*(IWDG_Regs *)(IWDG_BASE))
Functions
void stm32_watchdog_init (void)
void stm32_watchdog_pat (void)
void stm32_watchdog_save_reason (void)
void stm32_watchdog_clear_reason (void)
bool stm32_was_watchdog_reset (void)
void stm32_watchdog_save (const uint32_t *data, uint32_t nwords)
void stm32_watchdog_load (uint32_t *data, uint32_t nwords)
Variables
static bool was_watchdog_reset
static bool watchdog_enabled
Macro Definition Documentation
IWDGD
#define IWDGD (*(IWDG_Regs *)(IWDG_BASE))
Definition at line 53 of file watchdog.c.
Function Documentation
stm32_was_watchdog_reset()
bool stm32_was_watchdog_reset (void)
Definition at line 103 of file watchdog.c.
Referenced by main_loop(), and ChibiOS::Util::was_watchdog_reset().
stm32_watchdog_clear_reason()
void stm32_watchdog_clear_reason (void)
Definition at line 95 of file watchdog.c.
Referenced by __late_init().
stm32_watchdog_init()
void stm32_watchdog_init (void)
Definition at line 61 of file watchdog.c.
Referenced by main_loop().
stm32_watchdog_load()
void stm32_watchdog_load (uint32_t * data, uint32_t nwords)
Definition at line 119 of file watchdog.c.
Referenced by main_loop().
stm32_watchdog_pat()
void stm32_watchdog_pat (void)
Definition at line 75 of file watchdog.c.
Referenced by AP_IOMCU_FW::safety_update(), and ChibiOS::Scheduler::watchdog_pat().
stm32_watchdog_save()
void stm32_watchdog_save (const uint32_t * data, uint32_t nwords)
Definition at line 111 of file watchdog.c.
Referenced by ChibiOS::Scheduler::_monitor_thread().
stm32_watchdog_save_reason()
void stm32_watchdog_save_reason (void)
Definition at line 85 of file watchdog.c.
Referenced by __late_init().
Variable Documentation
was_watchdog_reset
bool was_watchdog_reset static
Definition at line 55 of file watchdog.c.
Referenced by AP_HAL::Util::set_soft_armed(), stm32_was_watchdog_reset(), and stm32_watchdog_save_reason().
watchdog_enabled
bool watchdog_enabled static
Definition at line 56 of file watchdog.c.
Referenced by stm32_watchdog_init(), and stm32_watchdog_pat().